Storage Class Reference
#include <Storage.h>
Static Public Member Functions
static bool init ()
static void cleanup ()
static bool write (uint8_t slot, ByteStream &buffer)
static bool read (uint8_t slot, ByteStream &buffer)
static uint32_t lastSaveSize ()
Private Member Functions
Storage ()
Static Private Member Functions
static void eepromWriteByte (uint16_t index, uint8_t in)
static uint8_t eepromReadByte (uint16_t index)
Static Private Attributes
static uint32_t m_lastSaveSize = 0
Detailed Description
Definition at line 12 of file Storage.h.
Constructor & Destructor Documentation
Storage()
Storage::Storage () [private]
Definition at line 52 of file Storage.cpp.
{
}
Member Function Documentation
cleanup()
void Storage::cleanup () [static]
Definition at line 66 of file Storage.cpp.
{
}
Referenced by VortexEngine::cleanup().
eepromReadByte()
uint8_t Storage::eepromReadByte (uint16_t index) [static], [private]
Definition at line 291 of file Storage.cpp.
{
  return *(volatile uint8_t *)(MAPPED_EEPROM_START + index);
}
Referenced by eepromWriteByte().
eepromWriteByte()
void Storage::eepromWriteByte (uint16_t index, uint8_t in) [static], [private]
Definition at line 265 of file Storage.cpp.
{
  if (eepromReadByte(index) == in) {
    return;
  }
  // The first two pages of the data goes into the eeprom and then the last page goes
  // into the USERROW which is located at 0x1300
  uint16_t adr = MAPPED_EEPROM_START + (index);
  __asm__ __volatile__(
    "ldi r30, 0x00" "\n\t"
    "ldi r31, 0x10" "\n\t"
    "ldd r18, Z+2" "\n\t"
    "andi r18, 3" "\n\t"
    "brne .-6" "\n\t"
    "st X, %0" "\n\t"
    "ldi %0, 0x9D" "\n\t"
    "out 0x34, %0" "\n\t"
    "ldi %0, 0x03" "\n\t"
    "st Z, %0" "\n\t"
    :"+d"(in)
    : "x"(adr)
    : "r30", "r31", "r18");
  while (!(NVMCTRL.STATUS & NVMCTRL_EEBUSY_bm));
}
References eepromReadByte().
Referenced by write().
init()
bool Storage::init () [static]
Definition at line 56 of file Storage.cpp.
{
#ifdef VORTEX_LIB
  if (!m_storageFilename.length() && Vortex::storageEnabled()) {
    m_storageFilename = DEFAULT_STORAGE_FILENAME;
  }
#endif
  return true;
}
References DEFAULT_STORAGE_FILENAME, and Vortex::storageEnabled().
Referenced by VortexEngine::init().
lastSaveSize()
uint32_t Storage::lastSaveSize () [static]
Definition at line 258 of file Storage.cpp.
{
  return m_lastSaveSize;
}
References m_lastSaveSize.
read()
bool Storage::read (uint8_t slot, ByteStream & buffer) [static]
Definition at line 187 of file Storage.cpp.
{
#ifdef VORTEX_LIB
  if (!Vortex::storageEnabled()) {
    // return false here, but true in write because we don't want to return
    // an empty buffer after returning true
    return false;
  }
#endif
  uint32_t size = MAX_MODE_SIZE;
  if (size > STORAGE_SIZE || size < sizeof(ByteStream::RawBuffer) + 4 || slot >= NUM_MODE_SLOTS) {
    return false;
  }
  if (!buffer.init(size)) {
    return false;
  }
#ifdef VORTEX_EMBEDDED
  uint8_t *buf = (uint8_t *)buffer.rawData();
  volatile uint8_t *src;
  if (slot == 0) { // slot 0 is header eeprom
    src = (volatile uint8_t *)MAPPED_EEPROM_START;
    size = STORAGE_HEADER_SIZE;
  } else if (slot < 4) { // slots 1-3 are eeprom
    src = (volatile uint8_t *)MAPPED_EEPROM_START + STORAGE_HEADER_SIZE + (MAX_MODE_SIZE * (slot - 1));
  } else { // slots 4-9 are flash
    src = (volatile uint8_t *)FLASH_STORAGE_SPACE + (MAX_MODE_SIZE * (slot - 4));
  }
  for (uint8_t i = 0; i < size; ++i) {
    buf[i] = src[i];
  }
#elif defined(_WIN32)
  HANDLE hFile = CreateFile(STORAGE_FILENAME, GENERIC_READ, 0, NULL, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, NULL);
  if (hFile == INVALID_HANDLE_VALUE) {
    // error
    return false;
  }
  DWORD bytesRead = 0;
  DWORD offset = slot * MAX_MODE_SIZE;
  SetFilePointer(hFile, offset, NULL, FILE_BEGIN);
  if (!ReadFile(hFile, buffer.rawData(), MAX_MODE_SIZE, &bytesRead, NULL)) {
    // error
    return false;
  }
  CloseHandle(hFile);
#else
  FILE *f = fopen(STORAGE_FILENAME, "r");
  if (!f) {
    return false;
  }
  long offset = slot * MAX_MODE_SIZE;
  fseek(f, offset, SEEK_SET);
  if (!fread(buffer.rawData(), sizeof(char), MAX_MODE_SIZE, f)) {
    return false;
  }
  fclose(f);
#endif
  // ensure the internal buffer is sane after reading it out, this
  // prevents segfaults if the internal size reports larger than capacity
  buffer.sanity();
  // check crc immediately since we read into raw data copying the
  // array could be dangerous
  if (!buffer.checkCRC()) {
    buffer.clear();
    ERROR_LOG("Could not verify buffer");
    return false;
  }
  m_lastSaveSize = size;
  DEBUG_LOGF("Loaded savedata (Size: %u)", buffer.size());
  return true;
}
References ByteStream::checkCRC(), ByteStream::clear(), DEBUG_LOGF, ERROR_LOG, FLASH_STORAGE_SPACE, ByteStream::init(), m_lastSaveSize, MAX_MODE_SIZE, NUM_MODE_SLOTS, ByteStream::rawData(), ByteStream::sanity(), ByteStream::size(), STORAGE_FILENAME, STORAGE_HEADER_SIZE, STORAGE_SIZE, and Vortex::storageEnabled().
Referenced by Modes::init(), Modes::loadHeader(), and Modes::loadStorage().
write()
bool Storage::write (uint8_t slot, ByteStream & buffer) [static]
Definition at line 74 of file Storage.cpp.
{
#ifdef VORTEX_LIB
  if (!Vortex::storageEnabled()) {
    // success so the system thinks it all worked
    return true;
  }
#endif
  // check size
  uint16_t size = buffer.rawSize();
  if (buffer.rawSize() > MAX_MODE_SIZE) {
    ERROR_LOG("Buffer too big for storage space");
    return false;
  }
  if (slot >= NUM_MODE_SLOTS) {
    return false;
  }
  // just in case
  buffer.recalcCRC();
#ifdef VORTEX_EMBEDDED
  const uint8_t *buf = (const uint8_t *)buffer.rawData();
  // the header is slot 0 and it gets 17 bytes in the start of the eeprom then
  // the next 3 modes are 76 bytes each taking up 228 bytes for a total of 245
  if (slot < 4) {
    uint8_t eepSlot = 0;
    if (slot > 0) {
      eepSlot = STORAGE_HEADER_SIZE + (MAX_MODE_SIZE * (slot - 1));
    }
    // header eeprom (12 bytes of 256)
    // 3 modes eeprom (76 x 3 bytes of 244)
    uint8_t slotSize = (slot == 0) ? STORAGE_HEADER_SIZE : MAX_MODE_SIZE;
    for (uint8_t i = 0; i < slotSize; ++i) {
      uint8_t b = (i < size) ? buf[i] : 0x00;
      eepromWriteByte(eepSlot + i, b);
    }
  } else {
    // Then flash storage is 0x200 or 512 bytes which allows for 6 x 76 byte modes
    // the base address of the slot we are writing
    uint16_t slotAddr = (uint16_t)FLASH_STORAGE_SPACE + (MAX_MODE_SIZE * (slot - 4));
    // The storage slot may lay across a page boundary which means potentially writing
    // two pages instead of just one. In order to update only part of a page, the page
    // buffer must be filled with both the previous content along with the new data.
    // For example, imagine 2 pages of data: |xxxxxxSSSS|SSSxxxxxxx| the x's are other
    // data that must be preserved, and the S's denote the storage slot being written.
    // This would take place over two iterations of the loop, each writing out one page
    // by read-then-writing-back the x's and writing out the new S's. This is necessary
    // because the page buffer must be filled to perform a page write, at least I think
    while (size > 0) {
      uint16_t pageStart = slotAddr & ~(FLASH_PAGE_SIZE - 1);
      uint16_t offset = slotAddr % FLASH_PAGE_SIZE;
      uint16_t space = FLASH_PAGE_SIZE - offset;
      uint16_t writeSize = (size < space) ? size : space;
      for (uint8_t i = 0; i < FLASH_PAGE_SIZE; ++i) {
        uint8_t value;
        if (i >= offset && i < offset + writeSize) {
          // if this is within the slot then write out the new data
          value = buf[i - offset];
        } else {
          // otherwise just write-back the same value to fill the pagebuffer
          value = *(volatile uint8_t *)(pageStart + i);
        }
        *(volatile uint8_t *)(pageStart + i) = value;
      }
      // Erase and write the flash page
      _PROTECTED_WRITE_SPM(NVMCTRL.CTRLA, NVMCTRL_CMD_PAGEERASEWRITE_gc);
      while (NVMCTRL.STATUS & (NVMCTRL_FBUSY_bm | NVMCTRL_EEBUSY_bm));
      // continue to the next page
      slotAddr += writeSize;
      buf += writeSize;
      size -= writeSize;
    }
  }
#elif defined(_WIN32)
  HANDLE hFile = CreateFile(STORAGE_FILENAME, GENERIC_READ | GENERIC_WRITE, 0, NULL, OPEN_ALWAYS, FILE_ATTRIBUTE_NORMAL, NULL);
  if (hFile == INVALID_HANDLE_VALUE) {
    // error
    return false;
  }
  DWORD written = 0;
  DWORD offset = slot * MAX_MODE_SIZE;
  SetFilePointer(hFile, offset, NULL, FILE_BEGIN);
  uint8_t modeBuffer[MAX_MODE_SIZE] = {0};
  // copy the mode data into a temp buffer
  memcpy(modeBuffer, buffer.rawData(), size);
  // then copy the full size of the temp buffer in
  if (!WriteFile(hFile, modeBuffer, MAX_MODE_SIZE, &written, NULL)) {
    // error
    return false;
  }
  CloseHandle(hFile);
#else
  FILE *f = fopen(STORAGE_FILENAME, "w");
  if (!f) {
    return false;
  }
  long offset = slot * MAX_MODE_SIZE;
  fseek(f, offset, SEEK_SET);
  uint8_t modeBuffer[MAX_MODE_SIZE] = {0};
  // copy the mode data into a temp buffer
  memcpy(modeBuffer, buffer.rawData(), size);
  if (!fwrite(modeBuffer, sizeof(char), MAX_MODE_SIZE, f)) {
    return false;
  }
  fclose(f);
#endif // VORTEX_EMBEDDED
  DEBUG_LOGF("Wrote %u bytes to storage (max: %u)", m_lastSaveSize, STORAGE_SIZE);
  return true;
}
References DEBUG_LOGF, eepromWriteByte(), ERROR_LOG, FLASH_PAGE_SIZE, FLASH_STORAGE_SPACE, m_lastSaveSize, MAX_MODE_SIZE, NUM_MODE_SLOTS, ByteStream::rawData(), ByteStream::rawSize(), ByteStream::recalcCRC(), STORAGE_FILENAME, STORAGE_HEADER_SIZE, STORAGE_SIZE, and Vortex::storageEnabled().
Referenced by Modes::saveHeader(), and Modes::saveStorage().
Member Data Documentation
m_lastSaveSize
uint32_t Storage::m_lastSaveSize = 0 [static], [private]
Definition at line 44 of file Storage.h.
Referenced by lastSaveSize(), read(), and write().
The documentation for this class was generated from the following files:
VortexEngine/src/Storage/Storage.h
VortexEngine/src/Storage/Storage.cpp