Button Class Reference
#include <Button.h>
Public Member Functions
Button ()
~Button ()
bool init (uint8_t pin)
bool check ()
void update ()
void enableWake ()
bool onPress () const
bool onRelease () const
bool isPressed () const
bool onShortClick () const
bool onLongClick () const
bool onConsecutivePresses (uint8_t numPresses)
uint32_t pressTime () const
uint32_t releaseTime () const
uint32_t holdDuration () const
uint32_t releaseDuration () const
uint8_t consecutivePresses () const
uint8_t releaseCount () const
Private Member Functions
Button (Button const &)
void operator= (Button const &)
Private Attributes
uint32_t m_pressTime
uint32_t m_releaseTime
uint32_t m_holdDuration
uint32_t m_releaseDuration
uint8_t m_consecutivePresses
uint8_t m_releaseCount
bool m_buttonState
bool m_newPress
bool m_newRelease
bool m_isPressed
bool m_shortClick
bool m_longClick
Detailed Description
Definition at line 10 of file Button.h.
Constructor & Destructor Documentation
Button() [1/2]
Button::Button (Button const &) [private]
Button() [2/2]
Button::Button ()
Definition at line 51 of file Button.cpp.
               :
  m_pressTime(0),
  m_releaseTime(0),
  m_holdDuration(0),
  m_releaseDuration(0),
  m_consecutivePresses(0),
  m_releaseCount(0),
  m_buttonState(false),
  m_newPress(false),
  m_newRelease(false),
  m_isPressed(false),
  m_shortClick(false),
  m_longClick(false)
{
}
 Button()
Button::~Button ()
Definition at line 67 of file Button.cpp.
{
}
Member Function Documentation
check()
bool Button::check ()
Definition at line 93 of file Button.cpp.
{
#ifdef VORTEX_LIB
  return (Vortex::vcallbacks()->checkPinHook(0) == 0);
#else
  return ((BUTTON_VPORT.IN & BUTTON_PIN) == 0);
#endif
}
References BUTTON_PIN, and BUTTON_VPORT.
Referenced by init(), VortexEngine::tick(), and update().
consecutivePresses()
uint8_t Button::consecutivePresses () const [inline]
Definition at line 59 of file Button.h.
{ return m_consecutivePresses; }
References m_consecutivePresses.
enableWake()
void Button::enableWake ()
Definition at line 44 of file Button.cpp.
{
  // turn on the above interrupt for FALLING edge, maintain the pullup enabled
  BUTTON_PORT.PIN_CTRL = PORT_PULLUPEN_bm | PORT_ISC_FALLING_gc;
}
References BUTTON_PORT.
Referenced by VortexEngine::enterSleep().
holdDuration()
uint32_t Button::holdDuration () const [inline]
Definition at line 54 of file Button.h.
{ return m_holdDuration; }
References m_holdDuration.
Referenced by ColorSelect::onLongClick(), FactoryReset::onLongClick(), VortexEngine::runMainLogic(), Menus::runMenuSelection(), Menu::showExit(), FactoryReset::showReset(), Menus::showSelection(), and ColorSelect::showSlotSelection().
init()
bool Button::init (uint8_t pin)
Definition at line 71 of file Button.cpp.
{
  m_pressTime = 0;
  m_releaseTime = 0;
  m_holdDuration = 0;
  m_releaseDuration = 0;
  m_consecutivePresses = 0;
  m_newPress = false;
  m_newRelease = false;
  m_shortClick = false;
  m_longClick = false;
  // this is weird, when I did m_releaseCount = !m_buttonState the
  // compiler generated a huge amount of assembly, but not !check()
  m_buttonState = check();
  m_releaseCount = !check();
  m_isPressed = m_buttonState;
#ifdef VORTEX_EMBEDDED
  BUTTON_PORT.PIN_CTRL = PORT_PULLUPEN_bm;
#endif
  return true;
}
References BUTTON_PORT, check(), m_buttonState, m_consecutivePresses, m_holdDuration, m_isPressed, m_longClick, m_newPress, m_newRelease, m_pressTime, m_releaseCount, m_releaseDuration, m_releaseTime, and m_shortClick.
isPressed()
bool Button::isPressed () const [inline]
Definition at line 38 of file Button.h.
{ return m_isPressed; }
References m_isPressed.
Referenced by ColorSelect::run(), GlobalBrightness::runKeychainMode(), VortexEngine::runMainLogic(), Menus::runMenuSelection(), Menu::showExit(), Randomizer::showRandomizationSelect(), FactoryReset::showReset(), Menus::showSelection(), and ColorSelect::showSlotSelection().
onConsecutivePresses()
bool Button::onConsecutivePresses (uint8_t numPresses)
Definition at line 170 of file Button.cpp.
{
  if (m_consecutivePresses >= numPresses) {
    m_consecutivePresses = 0;
    return true;
  }
  return false;
}
References m_consecutivePresses.
Referenced by PatternSelect::onShortClick(), ColorSelect::run(), Randomizer::run(), GlobalBrightness::runKeychainMode(), VortexEngine::runMainLogic(), Menus::runMenuSelection(), and VortexEngine::tick().
onLongClick()
bool Button::onLongClick () const [inline]
Definition at line 43 of file Button.h.
{ return m_longClick; }
References m_longClick.
Referenced by Menu::run(), Menus::runCurMenu(), and Menus::runMenuSelection().
onPress()
bool Button::onPress () const [inline]
Definition at line 34 of file Button.h.
{ return m_newPress; }
References m_newPress.
Referenced by GlobalBrightness::runKeychainMode().
onRelease()
bool Button::onRelease () const [inline]
Definition at line 36 of file Button.h.
{ return m_newRelease; }
References m_newRelease.
Referenced by Randomizer::run(), GlobalBrightness::runKeychainMode(), VortexEngine::runMainLogic(), and VortexEngine::tick().
onShortClick()
bool Button::onShortClick () const [inline]
Definition at line 41 of file Button.h.
{ return m_shortClick; }
References m_shortClick.
Referenced by Modes::play(), Menu::run(), Menus::runCurMenu(), and Menus::runMenuSelection().
operator=()
void Button::operator= (Button const &) [private]
pressTime()
uint32_t Button::pressTime () const [inline]
Definition at line 49 of file Button.h.
{ return m_pressTime; }
References m_pressTime.
Referenced by GlobalBrightness::runKeychainMode(), and Menus::runMenuSelection().
releaseCount()
uint8_t Button::releaseCount () const [inline]
Definition at line 61 of file Button.h.
{ return m_releaseCount; }
References m_releaseCount.
Referenced by VortexEngine::runMainLogic().
releaseDuration()
uint32_t Button::releaseDuration () const [inline]
Definition at line 56 of file Button.h.
{ return m_releaseDuration; }
References m_releaseDuration.
releaseTime()
uint32_t Button::releaseTime () const [inline]
Definition at line 51 of file Button.h.
{ return m_releaseTime; }
References m_releaseTime.
Referenced by Menus::checkOpen().
update()
void Button::update ()
Definition at line 102 of file Button.cpp.
{
  // reset the new press/release members this tick
  m_newPress = false;
  m_newRelease = false;
  // read the new button state
  bool newButtonState = check();
  // did the button change (press/release occurred)
  if (newButtonState != m_buttonState) {
    // set the new state
    m_buttonState = newButtonState;
    // update the currently pressed member
    m_isPressed = m_buttonState;
    // update the press/release times and newpress/newrelease members
    if (m_isPressed) {
      // the button was just pressed
      m_pressTime = Time::getCurtime();
      m_newPress = true;
    } else {
      // simply ignore the first release, always. Because they just turned the device
      // on and we don't want them to cycle to the next mode or something
      if (m_releaseCount > 0) {
        // the button was just released
        m_releaseTime = Time::getCurtime();
        m_newRelease = true;
      }
      // count releases even inside the ignore window so that
      // we can tell if the button was released to stop ignoring
      m_releaseCount++;
    }
  }
  // calculate new hold/release durations if currently held/released
  if (m_isPressed) {
    // update the hold duration as long as the button is pressed
    if (Time::getCurtime() >= m_pressTime) {
      m_holdDuration = (uint32_t)(Time::getCurtime() - m_pressTime);
    }
  } else {
    // update the release duration as long as the button is released
    if (Time::getCurtime() >= m_releaseTime) {
      m_releaseDuration = (uint32_t)(Time::getCurtime() - m_releaseTime);
      if (m_releaseDuration > CONSECUTIVE_WINDOW_TICKS) {
        // if the release duration is greater than the threshold, reset the consecutive presses
        m_consecutivePresses = 0;
      }
    }
  }
  if (m_newRelease) {
    m_consecutivePresses++;
  }
  // whether a shortclick or long click just occurred
  m_shortClick = (m_newRelease && (m_holdDuration <= SHORT_CLICK_THRESHOLD_TICKS));
  m_longClick = (m_newRelease && (m_holdDuration > SHORT_CLICK_THRESHOLD_TICKS));
  if (m_shortClick) {
    DEBUG_LOG("Short click");
  }
  if (m_longClick) {
    DEBUG_LOG("Long click");
  }
}
References check(), CONSECUTIVE_WINDOW_TICKS, DEBUG_LOG, Time::getCurtime(), m_buttonState, m_consecutivePresses, m_holdDuration, m_isPressed, m_longClick, m_newPress, m_newRelease, m_pressTime, m_releaseCount, m_releaseDuration, m_releaseTime, m_shortClick, and SHORT_CLICK_THRESHOLD_TICKS.
Referenced by Buttons::update().
Member Data Documentation
m_buttonState
bool Button::m_buttonState [private]
Definition at line 83 of file Button.h.
Referenced by init(), and update().
m_consecutivePresses
uint8_t Button::m_consecutivePresses [private]
Definition at line 78 of file Button.h.
Referenced by consecutivePresses(), init(), onConsecutivePresses(), and update().
m_holdDuration
uint32_t Button::m_holdDuration [private]
Definition at line 73 of file Button.h.
Referenced by holdDuration(), init(), and update().
m_isPressed
bool Button::m_isPressed [private]
Definition at line 90 of file Button.h.
Referenced by init(), isPressed(), and update().
m_longClick
bool Button::m_longClick [private]
Definition at line 94 of file Button.h.
Referenced by init(), onLongClick(), and update().
m_newPress
bool Button::m_newPress [private]
Definition at line 86 of file Button.h.
Referenced by init(), onPress(), and update().
m_newRelease
bool Button::m_newRelease [private]
Definition at line 88 of file Button.h.
Referenced by init(), onRelease(), and update().
m_pressTime
uint32_t Button::m_pressTime [private]
Definition at line 68 of file Button.h.
Referenced by init(), pressTime(), and update().
m_releaseCount
uint8_t Button::m_releaseCount [private]
Definition at line 80 of file Button.h.
Referenced by init(), releaseCount(), and update().
m_releaseDuration
uint32_t Button::m_releaseDuration [private]
Definition at line 75 of file Button.h.
Referenced by init(), releaseDuration(), and update().
m_releaseTime
uint32_t Button::m_releaseTime [private]
Definition at line 70 of file Button.h.
Referenced by init(), releaseTime(), and update().
m_shortClick
bool Button::m_shortClick [private]
Definition at line 92 of file Button.h.
Referenced by init(), onShortClick(), and update().
The documentation for this class was generated from the following files:
VortexEngine/src/Buttons/Button.h
VortexEngine/src/Buttons/Button.cpp