Leds Class Reference
#include <Leds.h>
Static Public Member Functions
static bool init ()
static void cleanup ()
static void setIndex (LedPos target, RGBColor col)
static void setRange (LedPos first, LedPos last, RGBColor col)
static void setAll (RGBColor col)
static void clearIndex (LedPos target)
static void clearRange (LedPos first, LedPos last)
static void clearAll ()
static void setPair (Pair pair, RGBColor col)
static void setPairs (Pair first, Pair last, RGBColor col)
static void clearPair (Pair pair)
static void clearPairs (Pair first, Pair last)
static void setRangeEvens (Pair first, Pair last, RGBColor)
static void setAllEvens (RGBColor col)
static void setRangeOdds (Pair first, Pair last, RGBColor)
static void setAllOdds (RGBColor col)
static void clearRangeEvens (Pair first, Pair last)
static void clearAllEvens ()
static void clearRangeOdds (Pair first, Pair last)
static void clearAllOdds ()
static void setMap (LedMap map, RGBColor col)
static void clearMap (LedMap map)
static void stashAll (LedStash &stash)
static void restoreAll (const LedStash &stash)
static void adjustBrightnessIndex (LedPos target, uint8_t fadeBy)
static void adjustBrightnessRange (LedPos first, LedPos last, uint8_t fadeBy)
static void adjustBrightnessAll (uint8_t fadeBy)
static void blinkIndexOffset (LedPos target, uint32_t time, uint16_t offMs=250, uint16_t onMs=500, RGBColor col=RGB_OFF)
static void blinkRangeOffset (LedPos first, LedPos last, uint32_t time, uint16_t offMs=250, uint16_t onMs=500, RGBColor col=RGB_OFF)
static void blinkIndex (LedPos target, uint16_t offMs=250, uint16_t onMs=500, RGBColor col=RGB_OFF)
static void blinkRange (LedPos first, LedPos last, uint16_t offMs=250, uint16_t onMs=500, RGBColor col=RGB_OFF)
static void blinkMap (LedMap targets, uint16_t offMs=250, uint16_t onMs=500, RGBColor col=RGB_OFF)
static void blinkAll (uint16_t offMs=250, uint16_t onMs=500, RGBColor col=RGB_OFF)
static void blinkPair (Pair pair, uint16_t offMs=250, uint16_t onMs=500, RGBColor col=RGB_OFF)
static void blinkPairs (Pair first, Pair last, uint16_t offMs=250, uint16_t onMs=500, RGBColor col=RGB_OFF)
static void breatheIndex (LedPos target, uint8_t hue, uint32_t variance, uint32_t magnitude=15, uint8_t sat=255, uint8_t val=210)
static void breatheRange (LedPos first, LedPos last, uint8_t hue, uint32_t variance, uint32_t magnitude=15, uint8_t sat=255, uint8_t val=210)
static void breatheIndexSat (LedPos target, uint8_t hue, uint32_t variance, uint32_t magnitude=15, uint8_t sat=255, uint8_t val=210)
static void breatheIndexVal (LedPos target, uint8_t hue, uint32_t variance, uint32_t magnitude=15, uint8_t sat=255, uint8_t val=210)
static void holdAll (RGBColor col)
static RGBColor getLed (LedPos pos)
static uint8_t getBrightness ()
static void setBrightness (uint8_t brightness)
static void update ()
Private Member Functions
Leds ()
Static Private Member Functions
static RGBColor & led (LedPos pos)
Static Private Attributes
static uint8_t m_brightness = DEFAULT_BRIGHTNESS
static RGBColor m_ledColors [LED_COUNT] = { RGB_OFF }
static volatile uint8_t * m_port = nullptr
static uint8_t m_pinMask = 0
Detailed Description
Definition at line 11 of file Leds.h.
Constructor & Destructor Documentation
Leds()
Leds::Leds () [private]
Member Function Documentation
adjustBrightnessAll()
void Leds::adjustBrightnessAll (uint8_t fadeBy) [static]
Definition at line 192 of file Leds.cpp.
{
  adjustBrightnessRange(LED_FIRST, LED_LAST, fadeBy);
}
References adjustBrightnessRange(), LED_FIRST, and LED_LAST.
adjustBrightnessIndex()
void Leds::adjustBrightnessIndex (LedPos target, uint8_t fadeBy) [static]
Definition at line 180 of file Leds.cpp.
{
  led(target).adjustBrightness(fadeBy);
}
References RGBColor::adjustBrightness(), and led().
Referenced by adjustBrightnessRange().
adjustBrightnessRange()
void Leds::adjustBrightnessRange (LedPos first, LedPos last, uint8_t fadeBy) [static]
Definition at line 185 of file Leds.cpp.
{
  for (LedPos pos = first; pos <= last; pos++) {
    adjustBrightnessIndex(pos, fadeBy);
  }
}
References adjustBrightnessIndex().
Referenced by adjustBrightnessAll().
blinkAll()
void Leds::blinkAll (uint16_t offMs = 250, uint16_t onMs = 500, RGBColor col = RGB_OFF) [static]
Definition at line 237 of file Leds.cpp.
{
  if ((Time::getCurtime() % MS_TO_TICKS(offMs + onMs)) < MS_TO_TICKS(onMs)) {
    setRange(LED_FIRST, LED_LAST, col);
  }
}
References Time::getCurtime(), LED_FIRST, LED_LAST, MS_TO_TICKS, and setRange().
Referenced by EditorConnection::showEditor(), Randomizer::showRandomizationSelect(), FactoryReset::showReset(), and ColorSelect::showSlotSelection().
blinkIndex()
void Leds::blinkIndex (LedPos target, uint16_t offMs = 250, uint16_t onMs = 500, RGBColor col = RGB_OFF) [static]
Definition at line 212 of file Leds.cpp.
{
  if ((Time::getCurtime() % MS_TO_TICKS(offMs + onMs)) < MS_TO_TICKS(onMs)) {
    setIndex(target, col);
  }
}
References Time::getCurtime(), MS_TO_TICKS, and setIndex().
Referenced by Menus::runMenuSelection(), Menu::showExit(), FactoryReset::showReset(), and ColorSelect::showSlotSelection().
blinkIndexOffset()
void Leds::blinkIndexOffset (LedPos target, uint32_t time, uint16_t offMs = 250, uint16_t onMs = 500, RGBColor col = RGB_OFF) [static]
Definition at line 198 of file Leds.cpp.
{
  if ((time % MS_TO_TICKS(offMs + onMs)) < MS_TO_TICKS(onMs)) {
    setIndex(target, col);
  }
}
References MS_TO_TICKS, and setIndex().
Referenced by GlobalBrightness::runKeychainMode().
blinkMap()
void Leds::blinkMap (LedMap targets, uint16_t offMs = 250, uint16_t onMs = 500, RGBColor col = RGB_OFF) [static]
Definition at line 226 of file Leds.cpp.
{
  if ((Time::getCurtime() % MS_TO_TICKS(offMs + onMs)) < MS_TO_TICKS(onMs)) {
    for (LedPos pos = LED_FIRST; pos < LED_COUNT; pos++) {
      if (ledmapCheckLed(targets, pos)) {
        setIndex(pos, col);
      }
    }
  }
}
References Time::getCurtime(), LED_COUNT, LED_FIRST, ledmapCheckLed(), MS_TO_TICKS, and setIndex().
Referenced by Menu::showBulbSelection().
blinkPair()
void Leds::blinkPair (Pair pair, uint16_t offMs = 250, uint16_t onMs = 500, RGBColor col = RGB_OFF) [static]
Definition at line 244 of file Leds.cpp.
{
  if ((Time::getCurtime() % MS_TO_TICKS(offMs + onMs)) < MS_TO_TICKS(onMs)) {
    setRange(pairEven(pair), pairOdd(pair), col);
  }
}
References Time::getCurtime(), MS_TO_TICKS, pairEven, pairOdd, and setRange().
blinkPairs()
void Leds::blinkPairs (Pair first, Pair last, uint16_t offMs = 250, uint16_t onMs = 500, RGBColor col = RGB_OFF) [static]
Definition at line 251 of file Leds.cpp.
{
  if ((Time::getCurtime() % MS_TO_TICKS(offMs + onMs)) < MS_TO_TICKS(onMs)) {
    setRange(pairEven(first), pairOdd(last), col);
  }
}
References Time::getCurtime(), MS_TO_TICKS, pairEven, pairOdd, and setRange().
blinkRange()
void Leds::blinkRange (LedPos first, LedPos last, uint16_t offMs = 250, uint16_t onMs = 500, RGBColor col = RGB_OFF) [static]
Definition at line 219 of file Leds.cpp.
{
  if ((Time::getCurtime() % MS_TO_TICKS(offMs + onMs)) < MS_TO_TICKS(onMs)) {
    setRange(first, last, col);
  }
}
References Time::getCurtime(), MS_TO_TICKS, and setRange().
blinkRangeOffset()
void Leds::blinkRangeOffset (LedPos first, LedPos last, uint32_t time, uint16_t offMs = 250, uint16_t onMs = 500, RGBColor col = RGB_OFF) [static]
Definition at line 205 of file Leds.cpp.
{
  if ((time % MS_TO_TICKS(offMs + onMs)) < MS_TO_TICKS(onMs)) {
    setRange(first, last, col);
  }
}
References MS_TO_TICKS, and setRange().
breatheIndex()
void Leds::breatheIndex (LedPos target, uint8_t hue, uint32_t variance, uint32_t magnitude = 15, uint8_t sat = 255, uint8_t val = 210) [static]
Definition at line 258 of file Leds.cpp.
{
  setIndex(target, HSVColor((uint8_t)(hue + ((sin(variance * 0.0174533) + 1) * magnitude)), sat, val));
}
References setIndex().
Referenced by ColorSelect::showSelection(), and ColorSelect::showSlotSelection().
breatheIndexSat()
void Leds::breatheIndexSat (LedPos target, uint8_t hue, uint32_t variance, uint32_t magnitude = 15, uint8_t sat = 255, uint8_t val = 210) [static]
Definition at line 268 of file Leds.cpp.
{
  setIndex(target, HSVColor(hue, 255 - (uint8_t)(sat + 128 + ((sin(variance * 0.0174533) + 1) * magnitude)), val));
}
References setIndex().
Referenced by ColorSelect::showSelection().
breatheIndexVal()
void Leds::breatheIndexVal (LedPos target, uint8_t hue, uint32_t variance, uint32_t magnitude = 15, uint8_t sat = 255, uint8_t val = 210) [static]
Definition at line 273 of file Leds.cpp.
{
  setIndex(target, HSVColor(hue, sat, 255 - (uint8_t)(val + 128 + ((sin(variance * 0.0174533) + 1) * magnitude))));
}
References setIndex().
Referenced by ColorSelect::showSelection().
breatheRange()
void Leds::breatheRange (LedPos first, LedPos last, uint8_t hue, uint32_t variance, uint32_t magnitude = 15, uint8_t sat = 255, uint8_t val = 210) [static]
Definition at line 263 of file Leds.cpp.
{
  setRange(first, last, HSVColor((uint8_t)(hue + ((sin(variance * 0.0174533) + 1) * magnitude)), sat, val));
}
References setRange().
cleanup()
void Leds::cleanup () [static]
Definition at line 52 of file Leds.cpp.
{
  for (uint8_t i = 0; i < LED_COUNT; ++i) {
    m_ledColors[i].clear();
  }
}
References RGBColor::clear(), LED_COUNT, and m_ledColors.
Referenced by VortexEngine::cleanup().
clearAll()
static void Leds::clearAll () [inline], [static]
Definition at line 30 of file Leds.h.
{ setAll(RGB_OFF); }
References RGB_OFF, and setAll().
Referenced by BlinkStepPattern::blinkOff(), DripMorphPattern::blinkOff(), LighthousePattern::blinkOff(), MeteorPattern::blinkOff(), Modes::clearModes(), Menus::closeCurMenu(), ZigzagPattern::Snake::draw(), VortexEngine::enterSleep(), ModeSharing::onShortClick(), Menus::openMenu(), Menus::openMenuSelection(), Modes::play(), HueShiftPattern::play(), ColorSelect::run(), GlobalBrightness::runKeychainMode(), VortexEngine::runMainLogic(), Menus::runMenuSelection(), Modes::setCurMode(), Menu::showBulbSelection(), EditorConnection::showEditor(), FactoryReset::showReset(), VLSender::startPWM(), and VLSender::stopPWM().
clearAllEvens()
void Leds::clearAllEvens () [static]
Definition at line 127 of file Leds.cpp.
{
  for (Pair pos = PAIR_FIRST; pos <= PAIR_LAST; pos++) {
    clearIndex(pairEven(pos));
  }
}
References clearIndex(), PAIR_FIRST, PAIR_LAST, and pairEven.
clearAllOdds()
void Leds::clearAllOdds () [static]
Definition at line 141 of file Leds.cpp.
{
  for (Pair pos = PAIR_FIRST; pos <= PAIR_LAST; pos++) {
    clearIndex(pairOdd(pos));
  }
}
References clearIndex(), PAIR_FIRST, PAIR_LAST, and pairOdd.
clearIndex()
static void Leds::clearIndex (LedPos target) [inline], [static]
Definition at line 28 of file Leds.h.
{ setIndex(target, RGB_OFF); }
References RGB_OFF, and setIndex().
Referenced by BasicPattern::beginGap(), clearAllEvens(), clearAllOdds(), clearMap(), clearRangeEvens(), clearRangeOdds(), BasicPattern::onBlinkOff(), Mode::play(), SequencedPattern::playSequenceStep(), Menu::showExit(), and ModeSharing::showReceiveMode().
clearMap()
void Leds::clearMap (LedMap map) [static]
Definition at line 157 of file Leds.cpp.
{
  for (LedPos pos = LED_FIRST; pos <= LED_LAST; pos++) {
    if (ledmapCheckLed(map, pos)) {
      clearIndex(pos);
    }
  }
}
References clearIndex(), LED_FIRST, LED_LAST, and ledmapCheckLed().
clearPair()
static void Leds::clearPair (Pair pair) [inline], [static]
Definition at line 37 of file Leds.h.
{ setPair(pair, RGB_OFF); }
References RGB_OFF, and setPair().
Referenced by PulsishPattern::play().
clearPairs()
static void Leds::clearPairs (Pair first, Pair last) [inline], [static]
Definition at line 38 of file Leds.h.
{ setPairs(first, last, RGB_OFF); }
References RGB_OFF, and setPairs().
clearRange()
static void Leds::clearRange (LedPos first, LedPos last) [inline], [static]
Definition at line 29 of file Leds.h.
{ setRange(first, last, RGB_OFF); }
References RGB_OFF, and setRange().
clearRangeEvens()
void Leds::clearRangeEvens (Pair first, Pair last) [static]
Definition at line 120 of file Leds.cpp.
{
  for (Pair pos = first; pos <= last; pos++) {
    clearIndex(pairEven(pos));
  }
}
References clearIndex(), and pairEven.
clearRangeOdds()
void Leds::clearRangeOdds (Pair first, Pair last) [static]
Definition at line 134 of file Leds.cpp.
{
  for (Pair pos = first; pos <= last; pos++) {
    clearIndex(pairOdd(pos));
  }
}
References clearIndex(), and pairOdd.
getBrightness()
static uint8_t Leds::getBrightness () [inline], [static]
Definition at line 107 of file Leds.h.
{ return m_brightness; }
References m_brightness.
Referenced by GlobalBrightness::init(), Modes::serializeSaveHeader(), and VLSender::startPWM().
getLed()
static RGBColor Leds::getLed (LedPos pos) [inline], [static]
Definition at line 104 of file Leds.h.
{ return led(pos); }
References led().
holdAll()
void Leds::holdAll (RGBColor col) [static]
Definition at line 278 of file Leds.cpp.
{
  setAll(col);
  update();
  Time::delayMilliseconds(250);
}
References Time::delayMilliseconds(), setAll(), and update().
Referenced by PatternSelect::onShortClick(), Randomizer::onShortClick(), VortexEngine::runMainLogic(), and Menus::runMenuSelection().
init()
bool Leds::init () [static]
Definition at line 35 of file Leds.cpp.
{
#ifdef VORTEX_EMBEDDED
  // clear the onboard led so it displays nothing
  // tiny neo pixels
  PORTB.DIRSET |= PIN4_bm;
  // register ouput port
  m_port = &VPORTB.OUT;
  // create a pin mask to use later
  m_pinMask = PIN4_bm;
#endif
#ifdef VORTEX_LIB
  Vortex::vcallbacks()->ledsInit(m_ledColors, LED_COUNT);
#endif
  return true;
}
References LED_COUNT, m_ledColors, m_pinMask, and m_port.
Referenced by VortexEngine::init().
led()
static RGBColor& Leds::led (LedPos pos) [inline], [static], [private]
Definition at line 115 of file Leds.h.
  {
    if (pos > LED_LAST) {
      pos = LED_LAST;
    }
    return m_ledColors[pos];
  }
References LED_LAST, and m_ledColors.
Referenced by adjustBrightnessIndex(), getLed(), restoreAll(), setIndex(), and stashAll().
restoreAll()
void Leds::restoreAll (const LedStash & stash) [static]
Definition at line 173 of file Leds.cpp.
{
  for (LedPos pos = LED_FIRST; pos <= LED_LAST; pos++) {
    led(pos) = stash.m_ledColorsStash[pos];
  }
}
References led(), LED_FIRST, LED_LAST, and LedStash::m_ledColorsStash.
Referenced by LighthousePattern::blinkOn(), and MeteorPattern::blinkOn().
setAll()
void Leds::setAll (RGBColor col) [static]
Definition at line 75 of file Leds.cpp.
{
  setRange(LED_FIRST, LED_LAST, col);
}
References LED_FIRST, LED_LAST, and setRange().
Referenced by BouncePattern::blinkOn(), DripPattern::blinkOn(), SnowballPattern::blinkOn(), SparkleTracePattern::blinkOn(), WarpPattern::blinkOn(), WarpWormPattern::blinkOn(), clearAll(), holdAll(), setIndex(), GlobalBrightness::showBrightnessSelection(), ColorSelect::showFullSet(), Randomizer::showRandomizationSelect(), ModeSharing::showReceiveMode(), FactoryReset::showReset(), Menus::showSelection(), and ModeSharing::showSendMode().
setAllEvens()
void Leds::setAllEvens (RGBColor col) [static]
Definition at line 99 of file Leds.cpp.
{
  for (Pair pos = PAIR_FIRST; pos <= PAIR_LAST; pos++) {
    setIndex(pairEven(pos), col);
  }
}
References PAIR_FIRST, PAIR_LAST, pairEven, and setIndex().
Referenced by DripMorphPattern::blinkOn(), DoubleStrobePattern::blinkOn(), and DripPattern::blinkOn().
setAllOdds()
void Leds::setAllOdds (RGBColor col) [static]
Definition at line 113 of file Leds.cpp.
{
  for (Pair pos = PAIR_FIRST; pos <= PAIR_LAST; pos++) {
    setIndex(pairOdd(pos), col);
  }
}
References PAIR_FIRST, PAIR_LAST, pairOdd, and setIndex().
Referenced by DripMorphPattern::blinkOn(), DoubleStrobePattern::blinkOn(), and DripPattern::blinkOn().
setBrightness()
static void Leds::setBrightness (uint8_t brightness) [inline], [static]
Definition at line 108 of file Leds.h.
{ m_brightness = brightness; }
References m_brightness.
Referenced by FactoryReset::onLongClick(), GlobalBrightness::onLongClick(), VLSender::startPWM(), and Modes::unserializeSaveHeader().
setIndex()
void Leds::setIndex (LedPos target, RGBColor col) [static]
Definition at line 59 of file Leds.cpp.
{
  if (target >= LED_COUNT) {
    setAll(col);
    return;
  }
  led(target) = col;
}
References led(), LED_COUNT, and setAll().
Referenced by BasicPattern::beginDash(), blinkIndex(), blinkIndexOffset(), blinkMap(), LighthousePattern::blinkOn(), SnowballPattern::blinkOn(), VortexPattern::blinkOn(), VortexWipePattern::blinkOn(), WarpWormPattern::blinkOn(), breatheIndex(), breatheIndexSat(), breatheIndexVal(), clearIndex(), ZigzagPattern::Snake::drawSnake(), BasicPattern::onBlinkOn(), BlendPattern::onBlinkOn(), HueShiftPattern::play(), Menus::runMenuSelection(), setAllEvens(), setAllOdds(), setMap(), setRange(), setRangeEvens(), setRangeOdds(), Menu::showExit(), ColorSelect::showFullSet(), Randomizer::showRandomizationSelect(), ModeSharing::showReceiveMode(), ColorSelect::showSelection(), ColorSelect::showSlotSelection(), and VLSender::startPWM().
setMap()
void Leds::setMap (LedMap map, RGBColor col) [static]
Definition at line 148 of file Leds.cpp.
{
  for (LedPos pos = LED_FIRST; pos <= LED_LAST; pos++) {
    if (ledmapCheckLed(map, pos)) {
      setIndex(pos, col);
    }
  }
}
References LED_FIRST, LED_LAST, ledmapCheckLed(), and setIndex().
Referenced by CrossDopsPattern::blinkOn(), TheaterChasePattern::blinkOn(), and ColorSelect::showSelection().
setPair()
void Leds::setPair (Pair pair, RGBColor col) [static]
Definition at line 80 of file Leds.cpp.
{
  // start from tip and go to top
  setRange(pairEven(pair), pairOdd(pair), col);
}
References pairEven, pairOdd, and setRange().
Referenced by BouncePattern::blinkOn(), WarpPattern::blinkOn(), clearPair(), PulsishPattern::play(), and SparkleTracePattern::poststep().
setPairs()
void Leds::setPairs (Pair first, Pair last, RGBColor col) [static]
Definition at line 86 of file Leds.cpp.
{
  // start from tip and go to top
  setRange(pairEven(first), pairOdd(last), col);
}
References pairEven, pairOdd, and setRange().
Referenced by FillPattern::blinkOn(), and clearPairs().
setRange()
void Leds::setRange (LedPos first, LedPos last, RGBColor col) [static]
Definition at line 68 of file Leds.cpp.
{
  for (LedPos pos = first; pos <= last; pos++) {
    setIndex(pos, col);
  }
}
References setIndex().
Referenced by blinkAll(), blinkPair(), blinkPairs(), blinkRange(), blinkRangeOffset(), breatheRange(), clearRange(), setAll(), setPair(), and setPairs().
setRangeEvens()
void Leds::setRangeEvens (Pair first, Pair last, RGBColor col) [static]
Definition at line 92 of file Leds.cpp.
{
  for (Pair pos = first; pos <= last; pos++) {
    setIndex(pairEven(pos), col);
  }
}
References pairEven, and setIndex().
setRangeOdds()
void Leds::setRangeOdds (Pair first, Pair last, RGBColor col) [static]
Definition at line 106 of file Leds.cpp.
{
  for (Pair pos = first; pos <= last; pos++) {
    setIndex(pairOdd(pos), col);
  }
}
References pairOdd, and setIndex().
stashAll()
void Leds::stashAll (LedStash & stash) [static]
Definition at line 166 of file Leds.cpp.
{
  for (LedPos pos = LED_FIRST; pos <= LED_LAST; pos++) {
    stash.m_ledColorsStash[pos] = led(pos);
  }
}
References led(), LED_FIRST, LED_LAST, and LedStash::m_ledColorsStash.
Referenced by LighthousePattern::blinkOff(), and LighthousePattern::blinkOn().
update()
void Leds::update () [static]
Definition at line 285 of file Leds.cpp.
{
#ifdef VORTEX_EMBEDDED
  RGBColor ledbackups[LED_COUNT];
  memcpy(ledbackups, m_ledColors, sizeof(m_ledColors));
  for (int c = 0; c < LED_COUNT; ++c) {
#define SCALE8(i, scale) (((uint16_t)i * (uint16_t)(scale)) >> 8)
    m_ledColors[c].red = SCALE8(m_ledColors[c].red, m_brightness);
    m_ledColors[c].green = SCALE8(m_ledColors[c].green, m_brightness);
    m_ledColors[c].blue = SCALE8(m_ledColors[c].blue, m_brightness);
  }
  // swap the red and green channels for the 2nd led on the microlight,
  // they will be swapped back at the end of this function
  SWAP(m_ledColors[LED_1].red, m_ledColors[LED_1].green);
#endif
#ifdef VORTEX_LIB
  Vortex::vcallbacks()->ledsShow();
#endif
  // Thanks to TinyNeoPixel for this code
#ifdef VORTEX_EMBEDDED
  volatile uint16_t
    i = LED_COUNT * sizeof(RGBColor); // Loop counter
  volatile uint8_t
    *ptr = (volatile uint8_t *)m_ledColors, // Pointer to next byte
    b = *ptr++, // Current byte value
    hi, // PORT w/output bit set high
    lo; // PORT w/output bit set low
  // AVRxt MCUs -- tinyAVR 0/1/2, megaAVR 0, AVR Dx ----------------------
  // with extended maximum speeds to supm_port vigorously overclocked
  // Dx-series parts. This is by no means intended to imply that they will
  // run at those speeds, only that - if they do - you can control WS2812s
  // with them.
  // Hand-tuned assembly code issues data to the LED drivers at a specific
  // rate. There's separate code for different CPU speeds (8, 12, 16 MHz)
  // for both the WS2811 (400 KHz) and WS2812 (800 KHz) drivers. The
  // datastream timing for the LED drivers allows a little wiggle room each
  // way (listed in the datasheets), so the conditions for compiling each
  // case are set up for a range of frequencies rather than just the exact
  // 8, 12 or 16 MHz values, permitting use with some close-but-not-spot-on
  // devices (e.g. 16.5 MHz DigiSpark). The ranges were arrived at based
  // on the datasheet figures and have not been extensively tested outside
  // the canonical 8/12/16 MHz speeds; there's no guarantee these will work
  // close to the extremes (or possibly they could be pushed further).
  // Keep in mind only one CPU speed case actually gets compiled; the
  // resulting program isn't as massive as it might look from source here.
  #if (F_CPU >= 9500000UL) && (F_CPU <= 11100000UL)
    /*
    volatile uint8_t n1, n2 = 0; // First, next bits out
    */
    // 14 instruction clocks per bit: HHHHxxxxLLLLL
    // ST instructions: ^ ^ ^ (T=0,4,7)
    volatile uint8_t next;
    hi = *m_port | m_pinMask;
    lo = *m_port & ~m_pinMask;
    next = lo;
    if (b & 0x80) {
      next = hi;
    }
    // Don't "optimize" the OUT calls into the bitTime subroutine;
    // we're exploiting the RCALL and RET as 3- and 4-cycle NOPs!
    asm volatile(
      "_head10:" "\n\t" // (T = 0)
      "st %a[port], %[hi]" "\n\t" // (T = 1)
      "rcall _bitTime10" "\n\t" // Bit 7 (T = 14)
      "st %a[port], %[hi]" "\n\t"
      "rcall _bitTime10" "\n\t" // Bit 6
      "st %a[port], %[hi]" "\n\t"
      "rcall _bitTime10" "\n\t" // Bit 5
      "st %a[port], %[hi]" "\n\t"
      "rcall _bitTime10" "\n\t" // Bit 4
      "st %a[port], %[hi]" "\n\t"
      "rcall _bitTime10" "\n\t" // Bit 3
      "st %a[port], %[hi]" "\n\t"
      "rcall _bitTime10" "\n\t" // Bit 2
      "st %a[port], %[hi]" "\n\t"
      "rcall _bitTime10" "\n\t" // Bit 1
      // Bit 0:
      "st %a[port], %[hi]" "\n\t" // 1 PORT = hi (T = 1)
      "ld %[byte] , %a[ptr]+" "\n\t" // 2 b = *ptr++ (T = 4)
      "st %a[port], %[next]" "\n\t" // 1 PORT = next (T = 5)
      "nop" "\n\t" // 1 nop (T = 6)
      "mov %[next] , %[lo]" "\n\t" // 1 next = lo (T = 7)
      "sbrc %[byte] , 7" "\n\t" // 1-2 if (b & 0x80) (T = 8)
       "mov %[next] , %[hi]" "\n\t" // 0-1 next = hi (T = 9)
      "st %a[port], %[lo]" "\n\t" // 1 PORT = lo (T = 10)
      "sbiw %[count], 1" "\n\t" // 2 i-- (T = 12)
      "brne _head10" "\n\t" // 2 if (i != 0) -> (next byte) (T = 14)
       "rjmp _done10" "\n\t"
      "_bitTime10:" "\n\t" // nop nop nop (T = 4)
       "st %a[port], %[next]" "\n\t" // 1 PORT = next (T = 5)
       "mov %[next], %[lo]" "\n\t" // 1 next = lo (T = 6)
       "lsl %[byte]" "\n\t" // 1 b <<= 1 (T = 7)
       "sbrc %[byte], 7" "\n\t" // 1-2 if (b & 0x80) (T = 8)
        "mov %[next], %[hi]" "\n\t" // 0-1 next = hi (T = 9)
       "st %a[port], %[lo]" "\n\t" // 1 PORT = lo (T = 10)
       "ret" "\n\t" // 4 return to above where we called from
       "_done10:" "\n"
    : [ptr] "+e" (ptr),
      [byte] "+r" (b),
      [next] "+r" (next),
      [count] "+w" (i)
    : [port] "e" (m_port),
      [hi] "r" (hi),
      [lo] "r" (lo));
// 20 MHz(ish) AVRxt ------------------------------------------------------
#elif (F_CPU >= 19000000UL) && (F_CPU <= 22000000L)
    // 25 inst. clocks per bit: HHHHHHHxxxxxxxxLLLLLLLLLL
    // ST instructions: ^ ^ ^ (T=0,7,15)
    volatile uint8_t next, bit;
    hi = *m_port | m_pinMask;
    lo = *m_port & ~m_pinMask;
    next = lo;
    bit = 8;
    asm volatile(
     "head20:" "\n\t" // Clk Pseudocode (T = 0)
      "st %a[port], %[hi]" "\n\t" // 1 PORT = hi (T = 1)
      "sbrc %[byte], 7" "\n\t" // 1-2 if (b & 128)
       "mov %[next], %[hi]" "\n\t" // 0-1 next = hi (T = 3)
      "dec %[bit]" "\n\t" // 1 bit-- (T = 4)
      "nop" "\n\t" // 1 nop (T = 5)
      "rjmp .+0" "\n\t" // 2 nop nop (T = 7)
      "st %a[port], %[next]" "\n\t" // 1 PORT = next (T = 8)
      "mov %[next] , %[lo]" "\n\t" // 1 next = lo (T = 9)
      "breq nextbyte20" "\n\t" // 1-2 if (bit == 0) (from dec above)
      "rol %[byte]" "\n\t" // 1 b <<= 1 (T = 11)
      "rjmp .+0" "\n\t" // 2 nop nop (T = 13)
      "rjmp .+0" "\n\t" // 2 nop nop (T = 15)
      "st %a[port], %[lo]" "\n\t" // 1 PORT = lo (T = 16)
      "nop" "\n\t" // 1 nop (T = 17)
      "rjmp .+0" "\n\t" // 2 nop nop (T = 19)
      "rjmp .+0" "\n\t" // 2 nop nop (T = 21)
      "rjmp .+0" "\n\t" // 2 nop nop (T = 23)
      "rjmp head20" "\n\t" // 2 -> head20 (next bit out)
     "nextbyte20:" "\n\t" // (T = 11)
      "ldi %[bit] , 8" "\n\t" // 1 bit = 8 (T = 12)
      "ld %[byte] , %a[ptr]+" "\n\t" // 2 b = *ptr++ (T = 14)
      "nop" "\n\t" // 1 nop (T = 15)
      "st %a[port], %[lo]" "\n\t" // 1 PORT = lo (T = 16)
      "nop" "\n\t" // 1 nop (T = 17)
      "rjmp .+0" "\n\t" // 2 nop nop (T = 19)
      "rjmp .+0" "\n\t" // 2 nop nop (T = 21)
      "sbiw %[count], 1" "\n\t" // 2 i-- (T = 23)
       "brne head20" "\n" // 2 if (i != 0) -> (next byte) ()
    : [ptr] "+e" (ptr),
      [byte] "+r" (b),
      [bit] "+d" (bit),
      [next] "+r" (next),
      [count] "+w" (i)
    : [port] "e" (m_port),
      [hi] "r" (hi),
      [lo] "r" (lo));
  #else
    #error "CPU SPEED NOT SUPPORTED"
  #endif
  // END AVR ----------------------------------------------------------------
#endif
#ifdef VORTEX_EMBEDDED
  // swap red and green channels back so all algorithms continue working
  SWAP(m_ledColors[LED_1].red, m_ledColors[LED_1].green);
  // restore the led colors from the backup (brightness mod)
  memcpy(m_ledColors, ledbackups, sizeof(m_ledColors));
#endif
}
References RGBColor::blue, RGBColor::green, LED_1, LED_COUNT, m_brightness, m_ledColors, m_pinMask, m_port, RGBColor::red, SCALE8, and SWAP.
Referenced by VortexEngine::enterSleep(), holdAll(), VLSender::startPWM(), VLSender::stopPWM(), and VortexEngine::tick().
Member Data Documentation
m_brightness
uint8_t Leds::m_brightness = DEFAULT_BRIGHTNESS [static], [private]
Definition at line 124 of file Leds.h.
Referenced by getBrightness(), setBrightness(), and update().
m_ledColors
RGBColor Leds::m_ledColors = { RGB_OFF } [static], [private]
Definition at line 127 of file Leds.h.
Referenced by cleanup(), init(), led(), and update().
m_pinMask
uint8_t Leds::m_pinMask = 0 [static], [private]
Definition at line 132 of file Leds.h.
Referenced by init(), and update().
m_port
volatile uint8_t * Leds::m_port = nullptr [static], [private]
Definition at line 130 of file Leds.h.
Referenced by init(), and update().
The documentation for this class was generated from the following files:
VortexEngine/src/Leds/Leds.h
VortexEngine/src/Leds/Leds.cpp