BlinkStepPattern Class Reference
#include <BlinkStepPattern.h>
Public Member Functions
virtual ~BlinkStepPattern ()
virtual void init () override
virtual void play () override
Protected Member Functions
BlinkStepPattern (const PatternArgs &args)
virtual void blinkOn ()
virtual void blinkOff ()
virtual void prestep ()
virtual void poststep ()
Private Attributes
uint8_t m_blinkOnDuration
uint8_t m_blinkOffDuration
uint8_t m_stepDuration
Timer m_blinkTimer
Timer m_stepTimer
Additional Inherited Members
Detailed Description
Definition at line 9 of file BlinkStepPattern.h.
Constructor & Destructor Documentation
BlinkStepPattern()
BlinkStepPattern::BlinkStepPattern (const PatternArgs & args) [protected]
Definition at line 8 of file BlinkStepPattern.cpp.
                                                          :
  MultiLedPattern(args),
  m_blinkOnDuration(0),
  m_blinkOffDuration(0),
  m_stepDuration(0),
  m_blinkTimer(),
  m_stepTimer()
{
  // BlinkStep is an abstract class it cannot be directly
  // instantiated so we do not need to assign a pattern id
  REGISTER_ARG(m_blinkOnDuration);
  REGISTER_ARG(m_blinkOffDuration);
  REGISTER_ARG(m_stepDuration);
}
References m_blinkOffDuration, m_blinkOnDuration, m_stepDuration, and REGISTER_ARG.
 BlinkStepPattern()
BlinkStepPattern::~BlinkStepPattern () [virtual]
Definition at line 23 of file BlinkStepPattern.cpp.
{
}
Member Function Documentation
blinkOff()
void BlinkStepPattern::blinkOff () [protected], [virtual]
Reimplemented in MeteorPattern, and LighthousePattern.
Definition at line 74 of file BlinkStepPattern.cpp.
{
  // override me
  Leds::clearAll();
}
References Leds::clearAll().
Referenced by play().
blinkOn()
void BlinkStepPattern::blinkOn () [protected], [virtual]
Reimplemented in WarpWormPattern, WarpPattern, VortexWipePattern, TheaterChasePattern, SparkleTracePattern, SnowballPattern, MeteorPattern, LighthousePattern, FillPattern, DripPattern, DoubleStrobePattern, CrossDopsPattern, and BouncePattern.
Definition at line 69 of file BlinkStepPattern.cpp.
{
  // override me
}
Referenced by play().
init()
void BlinkStepPattern::init () [override], [virtual]
Reimplemented from MultiLedPattern.
Reimplemented in WarpWormPattern, WarpPattern, VortexWipePattern, TheaterChasePattern, SnowballPattern, LighthousePattern, FillPattern, DripPattern, DoubleStrobePattern, CrossDopsPattern, and BouncePattern.
Definition at line 28 of file BlinkStepPattern.cpp.
{
  MultiLedPattern::init();
  // reset the blink timer entirely
  m_blinkTimer.reset();
  // dops timing
  m_blinkTimer.addAlarm(m_blinkOnDuration);
  m_blinkTimer.addAlarm(m_blinkOffDuration);
  // start the blink timer from the next frame
  m_blinkTimer.start();
  // reset and add alarm
  m_stepTimer.reset();
  m_stepTimer.addAlarm(m_stepDuration);
  m_stepTimer.start();
}
References Timer::addAlarm(), MultiLedPattern::init(), m_blinkOffDuration, m_blinkOnDuration, m_blinkTimer, m_stepDuration, m_stepTimer, Timer::reset(), and Timer::start().
Referenced by BouncePattern::init(), CrossDopsPattern::init(), DoubleStrobePattern::init(), DripPattern::init(), FillPattern::init(), LighthousePattern::init(), SnowballPattern::init(), TheaterChasePattern::init(), VortexWipePattern::init(), WarpPattern::init(), and WarpWormPattern::init().
play()
void BlinkStepPattern::play () [override], [virtual]
Implements Pattern.
Reimplemented in LighthousePattern.
Definition at line 47 of file BlinkStepPattern.cpp.
{
  // whether to trigger a step event based on the step timer
  bool shouldStep = (m_stepTimer.alarm() == 0);
  if (shouldStep) {
    prestep();
  }
  switch (m_blinkTimer.alarm()) {
  case -1: // just break and still run post-step
    break;
  case 0: // turn on the leds for given mapping
    blinkOn();
    break;
  case 1: // turn off the leds
    blinkOff();
    break;
  }
  if (shouldStep) {
    poststep();
  }
}
References Timer::alarm(), blinkOff(), blinkOn(), m_blinkTimer, m_stepTimer, poststep(), and prestep().
Referenced by LighthousePattern::play().
poststep()
void BlinkStepPattern::poststep () [protected], [virtual]
Reimplemented in WarpWormPattern, WarpPattern, VortexWipePattern, TheaterChasePattern, SparkleTracePattern, SnowballPattern, MeteorPattern, LighthousePattern, FillPattern, DripPattern, CrossDopsPattern, and BouncePattern.
Definition at line 85 of file BlinkStepPattern.cpp.
{
  // override me
  m_colorset.getNext();
}
References Colorset::getNext(), and Pattern::m_colorset.
Referenced by play().
prestep()
void BlinkStepPattern::prestep () [protected], [virtual]
Definition at line 80 of file BlinkStepPattern.cpp.
{
  // override me
}
Referenced by play().
Member Data Documentation
m_blinkOffDuration
uint8_t BlinkStepPattern::m_blinkOffDuration [private]
Definition at line 33 of file BlinkStepPattern.h.
Referenced by BlinkStepPattern(), and init().
m_blinkOnDuration
uint8_t BlinkStepPattern::m_blinkOnDuration [private]
Definition at line 32 of file BlinkStepPattern.h.
Referenced by BlinkStepPattern(), and init().
m_blinkTimer
Timer BlinkStepPattern::m_blinkTimer [private]
Definition at line 35 of file BlinkStepPattern.h.
Referenced by init(), and play().
m_stepDuration
uint8_t BlinkStepPattern::m_stepDuration [private]
Definition at line 34 of file BlinkStepPattern.h.
Referenced by BlinkStepPattern(), and init().
m_stepTimer
Timer BlinkStepPattern::m_stepTimer [private]
Definition at line 36 of file BlinkStepPattern.h.
Referenced by init(), and play().
The documentation for this class was generated from the following files:
VortexEngine/src/Patterns/Multi/BlinkStepPattern.h
VortexEngine/src/Patterns/Multi/BlinkStepPattern.cpp