SingleLedPattern Class Reference
#include <SingleLedPattern.h>
Public Member Functions
virtual ~SingleLedPattern ()
virtual void init () override
Protected Member Functions
SingleLedPattern (const PatternArgs &args)
Additional Inherited Members
Detailed Description
Definition at line 6 of file SingleLedPattern.h.
Constructor & Destructor Documentation
SingleLedPattern()
SingleLedPattern::SingleLedPattern (const PatternArgs & args) [protected]
Definition at line 5 of file SingleLedPattern.cpp.
                                                          :
  Pattern(args)
{
  // SingleLed is an abstract class it cannot be directly
  // instantiated so we do not need to assign a pattern id
}
 SingleLedPattern()
SingleLedPattern::~SingleLedPattern () [virtual]
Definition at line 12 of file SingleLedPattern.cpp.
{
}
Member Function Documentation
init()
void SingleLedPattern::init () [override], [virtual]
Reimplemented from Pattern.
Reimplemented in BlendPattern, and BasicPattern.
Definition at line 16 of file SingleLedPattern.cpp.
{
  Pattern::init();
}
References Pattern::init().
Referenced by SequencedPattern::play(), and CompoundPattern::setPatternAt().
The documentation for this class was generated from the following files:
VortexEngine/src/Patterns/Single/SingleLedPattern.h
VortexEngine/src/Patterns/Single/SingleLedPattern.cpp