ColorSelect Class Reference
#include <ColorSelect.h>
Public Member Functions
ColorSelect (const RGBColor &col, bool advanced)
~ColorSelect ()
bool init () override
MenuAction run () override
void onShortClick () override
void onShortClick2 () override
void onLongClick () override
void onLongClick2 () override
Private Types
enum ColorSelectState : uint32_t {
STATE_INIT
, STATE_PICK_SLOT
, STATE_PICK_HUE1
, STATE_PICK_HUE2
,
STATE_PICK_SAT
, STATE_PICK_VAL
 }
Private Member Functions
void blinkSelection (uint32_t offMs=350, uint32_t onMs=500) override
void showSlotSelection ()
void showSelection (ColorSelectState mode)
Private Attributes
const uint8_t sats [4]
const uint8_t vals [4]
ColorSelectState m_state
Colorset m_colorset
uint32_t m_curPage
uint32_t m_slot
uint32_t m_quadrant
HSVColor m_newColor
Additional Inherited Members
Detailed Description
Definition at line 8 of file ColorSelect.h.
Member Enumeration Documentation
ColorSelectState
enum ColorSelect::ColorSelectState : uint32_t [private]
Enumerator
STATE_INIT
STATE_PICK_SLOT
STATE_PICK_HUE1
STATE_PICK_HUE2
STATE_PICK_SAT
STATE_PICK_VAL
Definition at line 28 of file ColorSelect.h.
  {
    STATE_INIT,
    // currently picking the color slot to change
    STATE_PICK_SLOT,
    // first pick a quadrant 0, 90, 180, 240
    STATE_PICK_HUE1,
    // next pick a quadrant within that quadrant 0, 25, 50, 70
    STATE_PICK_HUE2,
    // picking a saturation for the color
    STATE_PICK_SAT,
    // picking a value for the color
    STATE_PICK_VAL,
  };
Constructor & Destructor Documentation
ColorSelect()
ColorSelect::ColorSelect (const RGBColor & col, bool advanced)
Definition at line 18 of file ColorSelect.cpp.
                                                           :
  Menu(col, advanced),
  m_state(STATE_PICK_SLOT),
  m_curPage(0),
  m_slot(0),
  m_quadrant(0),
  m_newColor()
{
  // NOTE! Specifically using hsv_to_rgb_rainbow instead of generic because
  // it will generate nicer looking colors and a nicer rainbow to select
  // from than a regular hsv conversion will. This is because the rainbow
  // function uses a different algorithm to generate the colors that results
  // in a smaller color space with less bright colors. The tradeoff is you lose
  // the bright colors but the rainbow looks a lot better
  g_hsv_rgb_alg = HSV_TO_RGB_RAINBOW;
}
References g_hsv_rgb_alg, and HSV_TO_RGB_RAINBOW.
 ColorSelect()
ColorSelect::~ColorSelect ()
Definition at line 35 of file ColorSelect.cpp.
{
  // revert the hsv to rgb algorithm to normal
  g_hsv_rgb_alg = HSV_TO_RGB_GENERIC;
}
References g_hsv_rgb_alg, and HSV_TO_RGB_GENERIC.
Member Function Documentation
blinkSelection()
void ColorSelect::blinkSelection (uint32_t offMs = 350, uint32_t onMs = 500) [override], [private], [virtual]
Reimplemented from Menu.
Definition at line 380 of file ColorSelect.cpp.
{
  // if we're in the slot selection
  if (m_state == STATE_PICK_SLOT) {
    // and the current selected slot is the end slot, except for when we're on the thumb
    if (m_slot == m_colorset.numColors() && m_curSelection != QUADRANT_LAST) {
      // clear the finger so it turns off, then blink this slot to either
      // white or dim white to indicate we can add a color here
      Leds::clearQuadrant(m_curSelection);
      Leds::blinkQuadrant(m_curSelection, 150, 350,
        g_pButton->isPressed() ? RGB_WHITE6 : RGB_WHITE4);
      return;
    } else if (m_slot < m_colorset.numColors() &&
      g_pButton->isPressed() &&
      g_pButton->holdDuration() >= DELETE_THRESHOLD_TICKS) {
      // if we're pressing down on a slot then glow the tip white/red
      if ((g_pButton->holdDuration() % (DELETE_CYCLE_TICKS * 2)) > DELETE_CYCLE_TICKS) {
        // breath red instead of white blink
        Leds::breathQuadrant(m_curSelection, 0, g_pButton->holdDuration());
        return;
      }
    } else if (m_slot == (uint32_t)(m_colorset.numColors() + 1)) {
      Leds::blinkQuadrantFive(150, 350, RGB_WHITE);
    }
  }
  // otherwise run the default blink logic
  Menu::blinkSelection(offMs, onMs);
}
References Leds::blinkQuadrant(), Leds::blinkQuadrantFive(), Menu::blinkSelection(), Leds::breathQuadrant(), Leds::clearQuadrant(), DELETE_CYCLE_TICKS, DELETE_THRESHOLD_TICKS, g_pButton, Button::holdDuration(), Button::isPressed(), m_colorset, Menu::m_curSelection, m_slot, m_state, Colorset::numColors(), QUADRANT_LAST, RGB_WHITE, RGB_WHITE4, RGB_WHITE6, and STATE_PICK_SLOT.
Referenced by run().
init()
bool ColorSelect::init () [override], [virtual]
Reimplemented from Menu.
Definition at line 41 of file ColorSelect.cpp.
{
  if (!Menu::init()) {
    return false;
  }
  Mode *cur = Modes::curMode();
  if (cur->isEmpty()) {
    // cannot work with an empty mode
    return false;
  }
  if (cur->isMultiLed()) {
    m_targetLeds = MAP_LED(LED_MULTI);
    m_ledSelected = true;
  }
  m_state = STATE_INIT;
  DEBUG_LOG("Entered color select");
  return true;
}
References Modes::curMode(), DEBUG_LOG, Menu::init(), Mode::isEmpty(), Mode::isMultiLed(), LED_MULTI, Menu::m_ledSelected, m_state, Menu::m_targetLeds, MAP_LED, and STATE_INIT.
onLongClick()
void ColorSelect::onLongClick () [override], [virtual]
Reimplemented from Menu.
Definition at line 202 of file ColorSelect.cpp.
{
  bool needsSave = false;
  // if we're exiting a menu
  if (m_curSelection == QUADRANT_LAST) {
    Mode *cur = Modes::curMode();
    // leaving a menu, clear everything
    Leds::clearAll();
    switch (m_state) {
    case STATE_PICK_SLOT:
    default:
      // if we're targetting more than one led then screw
      // checking if the colorset has changed because it's
      // not worth the effort
      needsSave = (!MAP_IS_ONE_LED(m_targetLeds) ||
        !m_colorset.equals(cur->getColorset(mapGetFirstLed(m_targetLeds))));
      // if we need to save, then actually update the colorset
      if (needsSave) {
        // save the colorset
        cur->setColorsetMap(m_targetLeds, m_colorset);
        cur->init();
      }
      // leave menu and save if we made changes
      leaveMenu(needsSave);
      return;
    case STATE_PICK_HUE1:
      m_state = STATE_PICK_SLOT;
      // reset selection and page based on chosen slot
      m_curSelection = (Quadrant)((m_slot % PAGE_SIZE));
      m_curPage = m_slot / PAGE_SIZE;
      return;
    case STATE_PICK_HUE2:
      // save the quadrant of hue that was selected so that if
      // they navigate backwards we know where to place them
      m_curSelection = (Quadrant)m_quadrant;
      m_state = (ColorSelectState)(m_state - 1);
      return;
    case STATE_PICK_SAT:
    case STATE_PICK_VAL:
      m_state = (ColorSelectState)(m_state - 1);
      m_curSelection = QUADRANT_FIRST;
      return;
    }
  }
  switch (m_state) {
  default:
    break;
  case STATE_PICK_SLOT:
    if (m_slot < m_colorset.numColors() &&
      g_pButton->holdDuration() >= DELETE_THRESHOLD_TICKS &&
      (g_pButton->holdDuration() % (DELETE_CYCLE_TICKS * 2)) >(DELETE_CYCLE_TICKS)) {
      // delete current slot
      m_colorset.removeColor(m_slot);
      if (m_slot > m_colorset.numColors()) {
        m_slot--;
      }
      m_curSelection = (Quadrant)((m_slot % PAGE_SIZE));
      m_curPage = m_slot / PAGE_SIZE;
      return;
    }
    m_state = STATE_PICK_HUE1;
    // the page is only used for slot selection so reset current page
    // for next time they use the color select
    m_curPage = 0;
    m_quadrant = 0;
    break;
  case STATE_PICK_HUE1:
    // save the quadrant of hue that was selected so that if
    // they navigate backwards we know where to place them
    m_quadrant = m_curSelection;
    // pick a hue1
    m_newColor.hue = m_quadrant * (256 / 4);
    m_state = STATE_PICK_HUE2;
    break;
  case STATE_PICK_HUE2:
    // pick a hue2
    m_newColor.hue = (m_quadrant * (256 / 4)) + (m_curSelection * (256 / 16));
    m_state = STATE_PICK_SAT;
    break;
  case STATE_PICK_SAT:
    // pick a saturation
    m_newColor.sat = sats[m_curSelection];
    m_state = STATE_PICK_VAL;
    break;
  case STATE_PICK_VAL:
    // pick a value
    m_newColor.val = vals[m_curSelection];
    // replace the slot with the new color, this might
    // result in adding a new color if the slot is at
    // hightest color index + 1
    m_colorset.set(m_slot, m_newColor);
    // go back to beginning for next time
    m_state = STATE_PICK_SLOT;
    // reset the color
    m_newColor.clear();
    // go back to the slot we just added
    m_curSelection = (Quadrant)((m_slot % PAGE_SIZE));
    m_curPage = m_slot / PAGE_SIZE;
    // return instead of break so the cur selection isn't reset
    return;
  }
  // reset selection after choosing anything
  m_curSelection = QUADRANT_FIRST;
}
References HSVColor::clear(), Leds::clearAll(), Modes::curMode(), DELETE_CYCLE_TICKS, DELETE_THRESHOLD_TICKS, Colorset::equals(), g_pButton, Mode::getColorset(), Button::holdDuration(), HSVColor::hue, Mode::init(), Menu::leaveMenu(), m_colorset, m_curPage, Menu::m_curSelection, m_newColor, m_quadrant, m_slot, m_state, Menu::m_targetLeds, MAP_IS_ONE_LED, mapGetFirstLed(), Colorset::numColors(), PAGE_SIZE, QUADRANT_FIRST, QUADRANT_LAST, Colorset::removeColor(), HSVColor::sat, sats, Colorset::set(), Mode::setColorsetMap(), STATE_PICK_HUE1, STATE_PICK_HUE2, STATE_PICK_SAT, STATE_PICK_SLOT, STATE_PICK_VAL, HSVColor::val, and vals.
onLongClick2()
void ColorSelect::onLongClick2 () [override], [virtual]
Reimplemented from Menu.
Definition at line 308 of file ColorSelect.cpp.
{
  // leaving a menu, clear everything
  Leds::clearAll();
  switch (m_state) {
  case STATE_PICK_SLOT:
  default:
    // leave menu without saving
    leaveMenu();
    return;
  case STATE_PICK_HUE1:
    m_state = STATE_PICK_SLOT;
    // reset selection and page based on chosen slot
    m_curSelection = (Quadrant)((m_slot % PAGE_SIZE));
    m_curPage = m_slot / PAGE_SIZE;
    return;
  case STATE_PICK_HUE2:
  case STATE_PICK_SAT:
  case STATE_PICK_VAL:
    m_state = (ColorSelectState)(m_state - 1);
    return;
  }
}
References Leds::clearAll(), Menu::leaveMenu(), m_curPage, Menu::m_curSelection, m_slot, m_state, PAGE_SIZE, STATE_PICK_HUE1, STATE_PICK_HUE2, STATE_PICK_SAT, STATE_PICK_SLOT, and STATE_PICK_VAL.
onShortClick()
void ColorSelect::onShortClick () [override], [virtual]
Reimplemented from Menu.
Definition at line 107 of file ColorSelect.cpp.
{
  // keep track of pages when in slot selection
  if (m_state == STATE_PICK_SLOT) {
    // if the current selection is on the index finger then it's at the
    // end of the current page and we might need to go to the next page
    if ((m_curSelection == QUADRANT_4 && (m_curPage == 0 && m_colorset.numColors() > 3))) {
      // increase the page number to 1
      m_curPage = (m_curPage + 1) % NUM_PAGES;
      // skip past the thumb if we're on index
      m_curSelection = QUADRANT_LAST;
      // clear all leds because we went to the next page
      Leds::clearAll();
    } else if (m_curSelection == QUADRANT_LAST && (m_curPage == 1 || (m_curPage == 0 && m_colorset.numColors() <= 3))) {
      m_curPage = 0;
      // skip past the thumb if we're on index
      m_curSelection = QUADRANT_LAST;
      // clear all leds because we went to the next page
      Leds::clearAll();
    }
  }
  // iterate selection forward and wrap after the thumb
  m_curSelection = (Quadrant)((m_curSelection + 1) % (QUADRANT_LAST + 1));
  // only when we're not on thumb calculate the current 'slot' based on page
  if (m_curSelection != QUADRANT_LAST && m_state == STATE_PICK_SLOT) {
    // the slot is an index in the colorset, where as curselection is a finger index
    m_slot = (uint32_t)m_curSelection + (m_curPage * PAGE_SIZE);
  }
  if (m_slot > m_colorset.numColors()) {
    if (m_curSelection != QUADRANT_LAST) {
      m_curSelection = QUADRANT_LAST;
    } else {
      m_curPage = m_slot = 0;
      m_curSelection = QUADRANT_FIRST;
    }
  }
}
References Leds::clearAll(), m_colorset, m_curPage, Menu::m_curSelection, m_slot, m_state, NUM_PAGES, Colorset::numColors(), PAGE_SIZE, QUADRANT_4, QUADRANT_FIRST, QUADRANT_LAST, and STATE_PICK_SLOT.
onShortClick2()
void ColorSelect::onShortClick2 () [override], [virtual]
Reimplemented from Menu.
Definition at line 145 of file ColorSelect.cpp.
{
  // keep track of pages when in slot selection
  if (m_state == STATE_PICK_SLOT) {
    // if the current selection is on the index finger then it's at the
    // end of the current page and we might need to go to the next page
    if (m_curSelection == QUADRANT_1 && m_curPage > 0) {
      // increase the page number to 1
      if (!m_curPage) {
        m_curPage = NUM_PAGES - 1;
      } else {
        --m_curPage;
      }
      // skip past the
      m_curSelection = QUADRANT_5;
      // clear all leds because we went to the next page
      Leds::clearAll();
    } else if (m_curSelection == QUADRANT_1 && (m_curPage > 0 || (m_curPage == 0 && m_colorset.numColors() > 3))) {
      if (!m_curPage) {
        m_curPage = NUM_PAGES - 1;
      } else {
        --m_curPage;
      }
      // skip past the thumb if we're on index
      m_curSelection = QUADRANT_5;
      // clear all leds because we went to the next page
      Leds::clearAll();
      // if we are moving backwards from the first slot in a 4 color set
    } else if (m_curSelection == QUADRANT_5) {
      m_curSelection = (Quadrant)((m_colorset.numColors() + 1) % PAGE_SIZE);
      Leds::clearAll();
    }
  }
  // iterate selection backward and wrap after the thumb
  if (!m_curSelection) {
    if (!m_curPage) {
      m_curSelection = QUADRANT_5;
    } else {
      m_curSelection = QUADRANT_LAST;
    }
  } else {
    m_curSelection = m_curSelection - 1;
  }
  if (m_curSelection != QUADRANT_5 && m_state == STATE_PICK_SLOT) {
    // the slot is an index in the colorset, where as curselection is a finger index
    m_slot = (uint32_t)m_curSelection + (m_curPage * PAGE_SIZE);
  }
  if (m_slot > m_colorset.numColors()) {
    if (m_curSelection != QUADRANT_5) {
      m_curSelection = QUADRANT_5;
    } else {
      m_curPage = m_slot = 0;
      m_curSelection = QUADRANT_FIRST;
    }
  }
}
References Leds::clearAll(), m_colorset, m_curPage, Menu::m_curSelection, m_slot, m_state, NUM_PAGES, Colorset::numColors(), PAGE_SIZE, QUADRANT_1, QUADRANT_5, QUADRANT_FIRST, QUADRANT_LAST, and STATE_PICK_SLOT.
run()
Menu::MenuAction ColorSelect::run () [override], [virtual]
Reimplemented from Menu.
Definition at line 60 of file ColorSelect.cpp.
{
  MenuAction result = Menu::run();
  if (result != MENU_CONTINUE) {
    return result;
  }
  // all states start with a blank slate
  Leds::clearAll();
  switch (m_state) {
  case STATE_INIT:
    // this is separate from the init function because the target led
    // hasn't been chosen yet at the time of the init function running
    // where as this will run after the target led has been chosen and
    // we can fetch the correct colorset to work with
    //m_newColor.clear();
    m_newColor = HSVColor(0, 255, 255);
    m_curPage = 0;
    m_slot = 0;
    m_quadrant = 0;
    // grab the colorset from our selected target led
    if (m_targetLeds == MAP_LED_ALL) {
      m_colorset = Modes::curMode()->getColorset();
    } else {
      m_colorset = Modes::curMode()->getColorset(mapGetFirstLed(m_targetLeds));
    }
    // move on to picking slot
    m_state = STATE_PICK_SLOT;
    break;
  case STATE_PICK_SLOT:
    showSlotSelection();
    break;
  case STATE_PICK_HUE1:
  case STATE_PICK_HUE2:
  case STATE_PICK_SAT:
  case STATE_PICK_VAL:
    showSelection(m_state);
    break;
  }
  // blink whichever slot is currently selected regardless of state
  blinkSelection();
  return MENU_CONTINUE;
}
References blinkSelection(), Leds::clearAll(), Modes::curMode(), Mode::getColorset(), m_colorset, m_curPage, m_newColor, m_quadrant, m_slot, m_state, Menu::m_targetLeds, MAP_LED_ALL, mapGetFirstLed(), Menu::MENU_CONTINUE, Menu::run(), showSelection(), showSlotSelection(), STATE_INIT, STATE_PICK_HUE1, STATE_PICK_HUE2, STATE_PICK_SAT, STATE_PICK_SLOT, and STATE_PICK_VAL.
showSelection()
void ColorSelect::showSelection (ColorSelectState mode) [private]
Definition at line 345 of file ColorSelect.cpp.
{
  for (Quadrant f = QUADRANT_FIRST; f <= QUADRANT_4; ++f) {
    HSVColor color;
    switch (mode) {
    case STATE_PICK_HUE1:
      if (f != QUADRANT_FIRST) {
        return;
      }
      for (Pair p = PAIR_FIRST; p < PAIR_COUNT; ++p) {
        Leds::setPair(p, HSVColor((256 / PAIR_COUNT) * p, 255, 255));
      }
      return;
    case STATE_PICK_HUE2:
      // calculate the hue with the stored 'quadrant' variable because
      // they may have gotten here by going back from the next state (pick sat)
      // and the m_newColor.hue value may have been irreversibly changed
      color = HSVColor((m_quadrant * (256 / 4)) + ((256 / 16) * f), 255, 255);
      break;
    case STATE_PICK_SAT:
      color = HSVColor(m_newColor.hue, sats[f], 255);
      break;
    case STATE_PICK_VAL:
      color = HSVColor(m_newColor.hue, m_newColor.sat, vals[f]);
      break;
    default:
      return;
    }
    Leds::setQuadrant(f, color);
  }
  if (m_curSelection >= 4) {
    showExit();
  }
}
References HSVColor::hue, Menu::m_curSelection, m_newColor, m_quadrant, PAIR_COUNT, PAIR_FIRST, QUADRANT_4, QUADRANT_FIRST, HSVColor::sat, sats, Leds::setPair(), Leds::setQuadrant(), Menu::showExit(), STATE_PICK_HUE1, STATE_PICK_HUE2, STATE_PICK_SAT, STATE_PICK_VAL, and vals.
Referenced by run().
showSlotSelection()
void ColorSelect::showSlotSelection () [private]
Definition at line 332 of file ColorSelect.cpp.
{
  // the index of the first color to show changes based on the page
  // will be either 0 or 4 for the two page color select
  uint32_t idx = (m_curPage * PAGE_SIZE);
  for (Quadrant f = QUADRANT_FIRST; f <= QUADRANT_4; ++f) {
    // set the current colorset slot color on the current finger
    // display the extra slots as solid blank
    Leds::setQuadrant(f, (idx >= m_colorset.numColors()) ? RGB_WHITE0 : m_colorset[idx]);
    idx++;
  }
}
References m_colorset, m_curPage, Colorset::numColors(), PAGE_SIZE, QUADRANT_4, QUADRANT_FIRST, RGB_WHITE0, and Leds::setQuadrant().
Referenced by run().
Member Data Documentation
m_colorset
Colorset ColorSelect::m_colorset [private]
Definition at line 72 of file ColorSelect.h.
Referenced by blinkSelection(), onLongClick(), onShortClick(), onShortClick2(), run(), and showSlotSelection().
m_curPage
uint32_t ColorSelect::m_curPage [private]
Definition at line 75 of file ColorSelect.h.
Referenced by onLongClick(), onLongClick2(), onShortClick(), onShortClick2(), run(), and showSlotSelection().
m_newColor
HSVColor ColorSelect::m_newColor [private]
Definition at line 84 of file ColorSelect.h.
Referenced by onLongClick(), run(), and showSelection().
m_quadrant
uint32_t ColorSelect::m_quadrant [private]
Definition at line 81 of file ColorSelect.h.
Referenced by onLongClick(), run(), and showSelection().
m_slot
uint32_t ColorSelect::m_slot [private]
Definition at line 78 of file ColorSelect.h.
Referenced by blinkSelection(), onLongClick(), onLongClick2(), onShortClick(), onShortClick2(), and run().
m_state
ColorSelectState ColorSelect::m_state [private]
Definition at line 69 of file ColorSelect.h.
Referenced by blinkSelection(), init(), onLongClick(), onLongClick2(), onShortClick(), onShortClick2(), and run().
sats
const uint8_t ColorSelect::sats[4] [private]
Initial value:
= {
    255,
    170,
    85,
    0
  }
Definition at line 53 of file ColorSelect.h.
Referenced by onLongClick(), and showSelection().
vals
const uint8_t ColorSelect::vals[4] [private]
Initial value:
= {
    255,
    170,
    85,
    0
  }
Definition at line 61 of file ColorSelect.h.
Referenced by onLongClick(), and showSelection().
The documentation for this class was generated from the following files:
VortexEngine/src/Menus/MenuList/ColorSelect.h
VortexEngine/src/Menus/MenuList/ColorSelect.cpp