PatternSelect Class Reference
#include <PatternSelect.h>
Public Member Functions
PatternSelect (const RGBColor &col, bool advanced)
~PatternSelect ()
bool init () override
MenuAction run () override
void onLedSelected () override
void onShortClick () override
void onShortClick2 () override
void onLongClick () override
void onLongClick2 () override
Private Types
enum PatternSelectState : uint32_t { STATE_PICK_LIST
, STATE_PICK_PATTERN
 }
Private Member Functions
void showListSelection ()
void showPatternSelection ()
void nextPattern ()
void previousPattern ()
Private Attributes
PatternSelectState m_state
PatternID m_newPatternID
Mode m_patternMode
bool m_started
Additional Inherited Members
Detailed Description
Definition at line 9 of file PatternSelect.h.
Member Enumeration Documentation
PatternSelectState
enum PatternSelect::PatternSelectState : uint32_t [private]
Enumerator
STATE_PICK_LIST
STATE_PICK_PATTERN
Definition at line 34 of file PatternSelect.h.
  {
    // currently picking the list of patterns
    STATE_PICK_LIST,
    // currently picking a pattern in the list
    STATE_PICK_PATTERN
  };
Constructor & Destructor Documentation
PatternSelect()
PatternSelect::PatternSelect (const RGBColor & col, bool advanced)
Definition at line 14 of file PatternSelect.cpp.
                                                               :
  Menu(col, advanced),
  m_state(STATE_PICK_LIST),
  m_newPatternID(PATTERN_FIRST),
  m_started(false)
{
}
 PatternSelect()
PatternSelect::~PatternSelect ()
Definition at line 22 of file PatternSelect.cpp.
{
}
Member Function Documentation
init()
bool PatternSelect::init () [override], [virtual]
Reimplemented from Menu.
Definition at line 26 of file PatternSelect.cpp.
{
  if (!Menu::init()) {
    return false;
  }
  m_state = STATE_PICK_LIST;
  m_newPatternID = PATTERN_FIRST;
  DEBUG_LOG("Entered pattern select");
  return true;
}
References DEBUG_LOG, Menu::init(), m_newPatternID, m_state, PATTERN_FIRST, and STATE_PICK_LIST.
nextPattern()
void PatternSelect::nextPattern () [private]
Definition at line 115 of file PatternSelect.cpp.
{
  LedPos srcLed = LED_MULTI;
  if (!m_previewMode.isMultiLed()) {
    srcLed = mapGetFirstLed(m_targetLeds);
  }
  PatternID newID = (PatternID)(m_previewMode.getPatternID(srcLed) + 1);
  PatternID endList = PATTERN_SINGLE_LAST;
  PatternID beginList = PATTERN_SINGLE_FIRST;
#if VORTEX_SLIM == 0
  if (m_targetLeds == MAP_LED_ALL || m_targetLeds == MAP_LED(LED_MULTI)) {
    endList = PATTERN_MULTI_LAST;
  }
  if (m_targetLeds == MAP_LED(LED_MULTI)) {
    beginList = PATTERN_MULTI_FIRST;
  }
#endif
  if (newID > endList || newID < beginList) {
    newID = beginList;
  }
  if (!m_started) {
    m_started = true;
    m_newPatternID = PATTERN_FIRST;
  }
  // set the new pattern id
  if (isMultiLedPatternID(newID)) {
    m_previewMode.setPattern(newID);
  } else {
    // TODO: clear multi a better way
    m_previewMode.setPatternMap(m_targetLeds, newID);
    m_previewMode.clearPattern(LED_MULTI);
  }
  m_previewMode.init();
  DEBUG_LOGF("Iterated to pattern id %d", newID);
}
References Mode::clearPattern(), DEBUG_LOGF, Mode::getPatternID(), Mode::init(), Mode::isMultiLed(), isMultiLedPatternID(), LED_MULTI, m_newPatternID, Menu::m_previewMode, m_started, Menu::m_targetLeds, MAP_LED, MAP_LED_ALL, mapGetFirstLed(), PATTERN_FIRST, PATTERN_MULTI_FIRST, PATTERN_MULTI_LAST, PATTERN_SINGLE_FIRST, PATTERN_SINGLE_LAST, Mode::setPattern(), and Mode::setPatternMap().
Referenced by onShortClick().
onLedSelected()
void PatternSelect::onLedSelected () [override], [virtual]
Reimplemented from Menu.
Definition at line 79 of file PatternSelect.cpp.
{
  m_previewMode.setPatternMap(m_targetLeds, PATTERN_FIRST);
  m_previewMode.init();
}
References Mode::init(), Menu::m_previewMode, Menu::m_targetLeds, PATTERN_FIRST, and Mode::setPatternMap().
onLongClick()
void PatternSelect::onLongClick () [override], [virtual]
Reimplemented from Menu.
Definition at line 187 of file PatternSelect.cpp.
{
  Mode *cur = Modes::curMode();
  bool needsSave = false;
  switch (m_state) {
  case STATE_PICK_LIST:
    if (m_curSelection == QUADRANT_LAST) {
      leaveMenu();
      return;
    }
    m_state = STATE_PICK_PATTERN;
    // start the new pattern ID selection based on the chosen list
    m_newPatternID = (PatternID)(PATTERN_FIRST + (m_curSelection * (PATTERN_COUNT / 4)));
    m_previewMode.setPattern(m_newPatternID);
    m_previewMode.init();
    DEBUG_LOGF("Started picking pattern at %u", m_newPatternID);
    break;
  case STATE_PICK_PATTERN:
    // need to save the new pattern if it's different from current
    needsSave = (cur->getPatternID() != m_previewMode.getPatternID());
    // update the current mode with the new pattern
    Modes::updateCurMode(&m_previewMode);
    // then done here, save if the mode was different
    leaveMenu(needsSave);
    break;
  }
  // reset selection after choosing anything
  m_curSelection = QUADRANT_FIRST;
}
References Modes::curMode(), DEBUG_LOGF, Mode::getPatternID(), Mode::init(), Menu::leaveMenu(), Menu::m_curSelection, m_newPatternID, Menu::m_previewMode, m_state, PATTERN_COUNT, PATTERN_FIRST, QUADRANT_FIRST, QUADRANT_LAST, Mode::setPattern(), STATE_PICK_LIST, STATE_PICK_PATTERN, and Modes::updateCurMode().
onLongClick2()
void PatternSelect::onLongClick2 () [override], [virtual]
Reimplemented from Menu.
Definition at line 217 of file PatternSelect.cpp.
{
  leaveMenu();
}
References Menu::leaveMenu().
onShortClick()
void PatternSelect::onShortClick () [override], [virtual]
Reimplemented from Menu.
Definition at line 85 of file PatternSelect.cpp.
{
  switch (m_state) {
  case STATE_PICK_LIST:
    // wrap at the index back to pinkie
    m_curSelection = (Quadrant)((m_curSelection + 1) % (QUADRANT_COUNT));
    break;
  case STATE_PICK_PATTERN:
    nextPattern();
    break;
  }
}
References Menu::m_curSelection, m_state, nextPattern(), QUADRANT_COUNT, STATE_PICK_LIST, and STATE_PICK_PATTERN.
onShortClick2()
void PatternSelect::onShortClick2 () [override], [virtual]
Reimplemented from Menu.
Definition at line 98 of file PatternSelect.cpp.
{
  switch (m_state) {
  case STATE_PICK_LIST:
    // wrap at the index back to pinkie
    if (!m_curSelection) {
      m_curSelection = QUADRANT_LAST;
    } else {
      m_curSelection = m_curSelection - 1;
    }
    break;
  case STATE_PICK_PATTERN:
    previousPattern();
    break;
  }
}
References Menu::m_curSelection, m_state, previousPattern(), QUADRANT_LAST, STATE_PICK_LIST, and STATE_PICK_PATTERN.
previousPattern()
void PatternSelect::previousPattern () [private]
Definition at line 151 of file PatternSelect.cpp.
{
  LedPos srcLed = LED_MULTI;
  if (!m_previewMode.isMultiLed()) {
    srcLed = mapGetFirstLed(m_targetLeds);
  }
  PatternID newID = (PatternID)(m_previewMode.getPatternID(srcLed) - 1);
  PatternID endList = PATTERN_SINGLE_LAST;
  PatternID beginList = PATTERN_SINGLE_FIRST;
#if VORTEX_SLIM == 0
  if (m_targetLeds == MAP_LED_ALL || m_targetLeds == MAP_LED(LED_MULTI)) {
    endList = PATTERN_MULTI_LAST;
  }
  if (m_targetLeds == MAP_LED(LED_MULTI)) {
    beginList = PATTERN_MULTI_FIRST;
  }
#endif
  if (newID > endList || newID < beginList) {
    newID = endList;
  }
  if (!m_started) {
    m_started = true;
    m_newPatternID = PATTERN_FIRST;
  }
  // set the new pattern id
  if (isMultiLedPatternID(newID)) {
    m_previewMode.setPattern(newID);
  } else {
    // TODO: clear multi a better way
    m_previewMode.setPatternMap(m_targetLeds, newID);
    m_previewMode.clearPattern(LED_MULTI);
  }
  m_previewMode.init();
  DEBUG_LOGF("Iterated to pattern id %d", newID);
}
References Mode::clearPattern(), DEBUG_LOGF, Mode::getPatternID(), Mode::init(), Mode::isMultiLed(), isMultiLedPatternID(), LED_MULTI, m_newPatternID, Menu::m_previewMode, m_started, Menu::m_targetLeds, MAP_LED, MAP_LED_ALL, mapGetFirstLed(), PATTERN_FIRST, PATTERN_MULTI_FIRST, PATTERN_MULTI_LAST, PATTERN_SINGLE_FIRST, PATTERN_SINGLE_LAST, Mode::setPattern(), and Mode::setPatternMap().
Referenced by onShortClick2().
run()
Menu::MenuAction PatternSelect::run () [override], [virtual]
Reimplemented from Menu.
Definition at line 37 of file PatternSelect.cpp.
{
  MenuAction result = Menu::run();
  if (result != MENU_CONTINUE) {
    return result;
  }
  switch (m_state) {
  case STATE_PICK_LIST:
    // display lists
    showListSelection();
    blinkSelection();
    break;
  case STATE_PICK_PATTERN:
    // display patterns
    showPatternSelection();
    break;
  }
  // show selections
  Menus::showSelection();
  return MENU_CONTINUE;
}
References Menu::blinkSelection(), m_state, Menu::MENU_CONTINUE, Menu::run(), showListSelection(), showPatternSelection(), Menus::showSelection(), STATE_PICK_LIST, and STATE_PICK_PATTERN.
showListSelection()
void PatternSelect::showListSelection () [private]
Definition at line 61 of file PatternSelect.cpp.
{
  for (Quadrant f = QUADRANT_FIRST; f <= QUADRANT_4; ++f) {
    // hue split into 4 quadrants of 90
    Leds::breathQuadrant(f, f * (255 / 4), (uint32_t)Time::getCurtime(), 10, 255, 255);
  }
  Leds::blinkQuadrantFive(10, 50, RGB_OFF);
}
References Leds::blinkQuadrantFive(), Leds::breathQuadrant(), Time::getCurtime(), QUADRANT_4, QUADRANT_FIRST, and RGB_OFF.
Referenced by run().
showPatternSelection()
void PatternSelect::showPatternSelection () [private]
Definition at line 70 of file PatternSelect.cpp.
{
  // run the current mode
  m_previewMode.play();
  if (g_pButton->isPressed() && g_pButton->holdDuration() > SHORT_CLICK_THRESHOLD_TICKS) {
    Leds::setAll(RGB_WHITE4);
  }
}
References g_pButton, Button::holdDuration(), Button::isPressed(), Menu::m_previewMode, Mode::play(), RGB_WHITE4, Leds::setAll(), and SHORT_CLICK_THRESHOLD_TICKS.
Referenced by run().
Member Data Documentation
m_newPatternID
PatternID PatternSelect::m_newPatternID [private]
Definition at line 46 of file PatternSelect.h.
Referenced by init(), nextPattern(), onLongClick(), and previousPattern().
m_patternMode
Mode PatternSelect::m_patternMode [private]
Definition at line 49 of file PatternSelect.h.
m_started
bool PatternSelect::m_started [private]
Definition at line 53 of file PatternSelect.h.
Referenced by nextPattern(), and previousPattern().
m_state
PatternSelectState PatternSelect::m_state [private]
Definition at line 43 of file PatternSelect.h.
Referenced by init(), onLongClick(), onShortClick(), onShortClick2(), and run().
The documentation for this class was generated from the following files:
VortexEngine/src/Menus/MenuList/PatternSelect.h
VortexEngine/src/Menus/MenuList/PatternSelect.cpp