VortexEngine/src/Leds/Leds.cpp File Reference
#include <math.h>
#include `LedStash.h`
#include `Leds.h`
#include `../Time/TimeControl.h`
#include `../Modes/Modes.h`
#include `../VortexConfig.h`
#include <Arduino.h>
Macros
#define LED_DATA_PIN 4
#define POWER_LED_PIN 7
#define CPU_FREQUENCY_MHZ 48
#define NS_TO_CYCLES(ns) (((ns) * CPU_FREQUENCY_MHZ) / 1000)
#define T0H 1
#define T0L 50
#define T1H 50
#define T1L 1
Functions
void delay_loop (uint32_t loop)
void sendBit (bool bitVal)
void sendByte (unsigned char byte)
Macro Definition Documentation
CPU_FREQUENCY_MHZ
#define CPU_FREQUENCY_MHZ 48
Definition at line 262 of file Leds.cpp.
LED_DATA_PIN
#define LED_DATA_PIN 4
Definition at line 17 of file Leds.cpp.
NS_TO_CYCLES
#define NS_TO_CYCLES(ns) (((ns) * CPU_FREQUENCY_MHZ) / 1000)
Definition at line 263 of file Leds.cpp.
POWER_LED_PIN
#define POWER_LED_PIN 7
Definition at line 18 of file Leds.cpp.
T0H
#define T0H 1
Definition at line 266 of file Leds.cpp.
T0L
#define T0L 50
Definition at line 267 of file Leds.cpp.
T1H
#define T1H 50
Definition at line 268 of file Leds.cpp.
T1L
#define T1L 1
Definition at line 269 of file Leds.cpp.
Function Documentation
delay_loop()
void delay_loop (uint32_t loop) [inline]
Definition at line 271 of file Leds.cpp.
{
  while (loop--) {
    __asm__ __volatile__("nop");
  }
}
Referenced by sendBit().
sendBit()
void sendBit (bool bitVal) [inline]
Definition at line 278 of file Leds.cpp.
{
  uint32_t pinMask = (1ul << g_APinDescription[LED_DATA_PIN].ulPin);
  volatile uint32_t *outSet = &(PORT->Group[g_APinDescription[LED_DATA_PIN].ulPort].OUTSET.reg);
  volatile uint32_t *outClr = &(PORT->Group[g_APinDescription[LED_DATA_PIN].ulPort].OUTCLR.reg);
  if (bitVal) { // Send 1 bit
    *outSet = pinMask; // Set the output bit
    delay_loop(NS_TO_CYCLES(T1H)); // Delay for T1H
    *outClr = pinMask; // Clear the output bit
    delay_loop(NS_TO_CYCLES(T0L)); // Delay for T0L (since T1L can lead to early latch)
  } else { // Send 0 bit
    *outSet = pinMask; // Set the output bit
    delay_loop(NS_TO_CYCLES(T0H)); // Delay for T0H
    *outClr = pinMask; // Clear the output bit
    delay_loop(NS_TO_CYCLES(T1L)); // Delay for T1L
  }
}
References delay_loop(), LED_DATA_PIN, NS_TO_CYCLES, T0H, T0L, T1H, and T1L.
Referenced by sendByte().
sendByte()
void sendByte (unsigned char byte) [inline]
Definition at line 296 of file Leds.cpp.
{
  for (unsigned char bit = 0; bit < 8; bit++) {
    sendBit(bitRead(byte, 7)); // Neopixel wants bit in highest-to-lowest order
    // so send highest bit (bit #7 in an 8-bit byte since they start at 0)
    byte <<= 1; // and then shift left so bit 6 moves into 7, 5 moves into 6, etc
  }
}
References sendBit().
Referenced by Leds::update().