MateriaPattern Class Reference
#include <MateriaPattern.h>
Public Member Functions
MateriaPattern (const PatternArgs &args)
virtual ~MateriaPattern ()
virtual void init () override
virtual void play () override
Private Attributes
uint8_t m_onDuration1
uint8_t m_offDuration1
uint8_t m_onDuration2
uint8_t m_offDuration2
uint8_t m_stepSpeed
Timer m_blinkTimer1
Timer m_blinkTimer2
Timer m_stepTimer
LedMap m_ledMap
bool m_switch
Additional Inherited Members
Detailed Description
Definition at line 10 of file MateriaPattern.h.
Constructor & Destructor Documentation
MateriaPattern()
MateriaPattern::MateriaPattern (const PatternArgs & args)
Definition at line 8 of file MateriaPattern.cpp.
                                                      :
  MultiLedPattern(args),
  m_onDuration1(0),
  m_offDuration1(0),
  m_onDuration2(0),
  m_offDuration2(0),
  m_stepSpeed(0),
  m_stepTimer(),
  m_ledMap(0),
  m_switch(false)
{
  m_patternID = PATTERN_MATERIA;
  REGISTER_ARG(m_onDuration1);
  REGISTER_ARG(m_offDuration1);
  REGISTER_ARG(m_onDuration2);
  REGISTER_ARG(m_offDuration2);
  REGISTER_ARG(m_stepSpeed);
  setArgs(args);
}
References m_offDuration1, m_offDuration2, m_onDuration1, m_onDuration2, Pattern::m_patternID, m_stepSpeed, PATTERN_MATERIA, REGISTER_ARG, and Pattern::setArgs().
 MateriaPattern()
MateriaPattern::~MateriaPattern () [virtual]
Definition at line 28 of file MateriaPattern.cpp.
{
}
Member Function Documentation
init()
void MateriaPattern::init () [override], [virtual]
Reimplemented from MultiLedPattern.
Definition at line 33 of file MateriaPattern.cpp.
{
  MultiLedPattern::init();
  // start on index 1
  m_colorset.setCurIndex(1);
  // reset the blink timer entirely
  m_blinkTimer1.reset();
  // dops timing
  m_blinkTimer1.addAlarm(m_onDuration1);
  m_blinkTimer1.addAlarm(m_offDuration1);
  // start the blink timer from the next frame
  m_blinkTimer1.start();
  // reset the blink timer entirely
  m_blinkTimer2.reset();
  // dops timing
  m_blinkTimer2.addAlarm(m_onDuration2);
  m_blinkTimer2.addAlarm(m_offDuration2);
  // start the blink timer from the next frame
  m_blinkTimer2.start();
  // reset and add alarm
  m_stepTimer.reset();
  m_stepTimer.addAlarm(m_stepSpeed * 100);
  m_stepTimer.start();
  // map of the Thumb, Index, Ring, and Pinkie Tops
  m_ledMap = MAP_LED(LED_9) | MAP_LED(LED_7) | MAP_LED(LED_3) | MAP_LED(LED_1);
  //Set the middle top to solid color 0
  Leds::setIndex(LED_5, m_colorset.get(0));
}
References Timer::addAlarm(), Colorset::get(), MultiLedPattern::init(), LED_1, LED_3, LED_5, LED_7, LED_9, m_blinkTimer1, m_blinkTimer2, Pattern::m_colorset, m_ledMap, m_offDuration1, m_offDuration2, m_onDuration1, m_onDuration2, m_stepSpeed, m_stepTimer, MAP_LED, Timer::reset(), Colorset::setCurIndex(), Leds::setIndex(), and Timer::start().
play()
void MateriaPattern::play () [override], [virtual]
Implements Pattern.
Definition at line 68 of file MateriaPattern.cpp.
{
  // get next color on stepTimer alarm, skip color 0
  if (m_stepTimer.alarm() == 0) {
    m_colorset.getNext();
    if (m_colorset.curIndex() == 0) {
      m_colorset.getNext();
    }
  }
  switch (m_blinkTimer1.alarm()) {
  case -1: // just break and still run post-step
    break;
  case 0: // turn on the leds for given mapping
    m_switch = !m_switch;
    // alternate between showing the current and next color
    if (m_switch) {
      // if this is the last color of the set, skip color 0 (color 0 is for Middle top only)
      if (m_colorset.curIndex() != m_colorset.numColors() - 1) {
        Leds::setAllEvens(m_colorset.peekNext());
      } else {
        Leds::setAllEvens(m_colorset.peek(2));
      }
    }
    else {
      Leds::setAllEvens(m_colorset.cur());
    }
    break;
  case 1: // turn off the leds
    Leds::clearAllEvens();
    break;
  }
  switch (m_blinkTimer2.alarm()) {
  case -1: // just break and still run post-step
    break;
  case 0: // turn on the leds for given mapping
    Leds::setMap(m_ledMap, m_colorset.cur());
    break;
  case 1: // turn off the leds
    Leds::clearMap(m_ledMap);
    break;
  }
 }
References Timer::alarm(), Leds::clearAllEvens(), Leds::clearMap(), Colorset::cur(), Colorset::curIndex(), Colorset::getNext(), m_blinkTimer1, m_blinkTimer2, Pattern::m_colorset, m_ledMap, m_stepTimer, m_switch, Colorset::numColors(), Colorset::peek(), Colorset::peekNext(), Leds::setAllEvens(), and Leds::setMap().
Member Data Documentation
m_blinkTimer1
Timer MateriaPattern::m_blinkTimer1 [private]
Definition at line 31 of file MateriaPattern.h.
Referenced by init(), and play().
m_blinkTimer2
Timer MateriaPattern::m_blinkTimer2 [private]
Definition at line 32 of file MateriaPattern.h.
Referenced by init(), and play().
m_ledMap
LedMap MateriaPattern::m_ledMap [private]
Definition at line 35 of file MateriaPattern.h.
Referenced by init(), and play().
m_offDuration1
uint8_t MateriaPattern::m_offDuration1 [private]
Definition at line 25 of file MateriaPattern.h.
Referenced by init(), and MateriaPattern().
m_offDuration2
uint8_t MateriaPattern::m_offDuration2 [private]
Definition at line 27 of file MateriaPattern.h.
Referenced by init(), and MateriaPattern().
m_onDuration1
uint8_t MateriaPattern::m_onDuration1 [private]
Definition at line 24 of file MateriaPattern.h.
Referenced by init(), and MateriaPattern().
m_onDuration2
uint8_t MateriaPattern::m_onDuration2 [private]
Definition at line 26 of file MateriaPattern.h.
Referenced by init(), and MateriaPattern().
m_stepSpeed
uint8_t MateriaPattern::m_stepSpeed [private]
Definition at line 29 of file MateriaPattern.h.
Referenced by init(), and MateriaPattern().
m_stepTimer
Timer MateriaPattern::m_stepTimer [private]
Definition at line 33 of file MateriaPattern.h.
Referenced by init(), and play().
m_switch
bool MateriaPattern::m_switch [private]
Definition at line 37 of file MateriaPattern.h.
Referenced by play().
The documentation for this class was generated from the following files:
VortexEngine/src/Patterns/Multi/MateriaPattern.h
VortexEngine/src/Patterns/Multi/MateriaPattern.cpp