Random Class Reference
#include <Random.h>
Public Member Functions
Random ()
Random (uint32_t newseed)
~Random ()
void seed (uint32_t newseed)
uint8_t next8 (uint8_t minValue=0, uint8_t maxValue=0xFF)
uint16_t next16 (uint16_t minValue=0, uint16_t maxValue=0xFFFF)
Private Attributes
uint32_t m_seed
Detailed Description
Definition at line 5 of file Random.h.
Constructor & Destructor Documentation
Random() [1/2]
Random::Random ()
Definition at line 3 of file Random.cpp.
               :
  m_seed(0)
{
}
Random() [2/2]
Random::Random (uint32_t newseed)
Definition at line 8 of file Random.cpp.
                               :
  Random()
{
  seed(newseed);
}
References seed().
 Random()
Random::~Random ()
Definition at line 14 of file Random.cpp.
{
}
Member Function Documentation
next16()
uint16_t Random::next16 (uint16_t minValue = 0, uint16_t maxValue = 0xFFFF)
Definition at line 26 of file Random.cpp.
{
  // walk the LCG forward to the next step
  m_seed = (m_seed * 1103515245 + 12345) & 0x7FFFFFFF;
  uint32_t range = maxValue - minValue;
  if (range != 0xFFFFFFFF) {
    // shift the seed 16 bits to the right because the lower 16 bits
    // of this LCG are apparently not uniform whatsoever, where as the
    // upper 16 bits appear to be quite uniform as per tests. We don't
    // really need 32bit random values so we offer max 16bits of entropy
    return ((m_seed >> 16) % (range + 1)) + minValue;
  }
  return (m_seed >> 16);
}
References m_seed.
Referenced by next8().
next8()
uint8_t Random::next8 (uint8_t minValue = 0, uint8_t maxValue = 0xFF)
Definition at line 41 of file Random.cpp.
{
  uint32_t result = next16(minValue, maxValue);
  return static_cast<uint8_t>(result);
}
References next16().
Referenced by Colorset::addColorWithValueStyle(), Randomizer::crushPattern(), Randomizer::dashPattern(), Randomizer::gapPattern(), MeteorPattern::poststep(), SparkleTracePattern::poststep(), Colorset::randomize(), Colorset::randomizeColorTheory(), Colorset::randomizeDoubleSplitComplimentary(), Colorset::randomizeEvenlySpaced(), Colorset::randomizeMonochromatic(), Colorset::randomizeTetradic(), Randomizer::rollColorset(), Randomizer::rollPattern(), Randomizer::rollPatternID(), and Randomizer::traditionalPattern().
seed()
void Random::seed (uint32_t newseed)
Definition at line 18 of file Random.cpp.
{
  if (!newseed) {
    m_seed = 42;
  }
  m_seed = newseed;
}
References m_seed.
Referenced by Randomizer::init(), and Random().
Member Data Documentation
m_seed
uint32_t Random::m_seed [private]
Definition at line 18 of file Random.h.
Referenced by next16(), and seed().
The documentation for this class was generated from the following files:
VortexEngine/src/Random/Random.h
VortexEngine/src/Random/Random.cpp