IRSender Class Reference
#include <IRSender.h>
Static Public Member Functions
static bool init ()
static void cleanup ()
static bool loadMode (const Mode *targetMode)
static bool send ()
static bool isSending ()
static uint32_t percentDone ()
Private Member Functions
IRSender ()
Static Private Member Functions
static void beginSend ()
static void sendByte (uint8_t data)
static void sendMark (uint16_t time)
static void sendSpace (uint16_t time)
static void initPWM ()
static void startPWM ()
static void stopPWM ()
Static Private Attributes
static ByteStream m_serialBuf
static BitStream m_bitStream
static bool m_isSending = false
static uint32_t m_lastSendTime = 0
static uint32_t m_size = 0
static uint8_t m_numBlocks = 0
static uint8_t m_remainder = 0
static uint32_t m_blockSize = 0
static uint32_t m_writeCounter = 0
Detailed Description
Definition at line 13 of file IRSender.h.
Constructor & Destructor Documentation
IRSender()
IRSender::IRSender () [private]
Member Function Documentation
beginSend()
void IRSender::beginSend () [static], [private]
Definition at line 117 of file IRSender.cpp.
{
  m_isSending = true;
  DEBUG_LOGF("[%zu] Beginning send size %u (blocks: %u remainder: %u blocksize: %u)",
    Time::microseconds(), m_size, m_numBlocks, m_remainder, m_blockSize);
  // init sender before writing, is this necessary here? I think so
  initPWM();
  // wakeup the other receiver with a very quick mark/space
  sendMark(50);
  sendSpace(100);
  // now send the header
  sendMark(IR_HEADER_MARK);
  sendSpace(IR_HEADER_SPACE);
  // reset writeCounter
  m_writeCounter = 0;
  // write the number of blocks being sent, most likely just 1
  sendByte(m_numBlocks);
  // now write the number of bytes in the last block
  sendByte(m_remainder);
}
References DEBUG_LOGF, initPWM(), IR_HEADER_MARK, IR_HEADER_SPACE, m_blockSize, m_isSending, m_numBlocks, m_remainder, m_size, m_writeCounter, Time::microseconds(), sendByte(), sendMark(), and sendSpace().
Referenced by send().
cleanup()
void IRSender::cleanup () [static]
Definition at line 46 of file IRSender.cpp.
{
}
Referenced by VortexEngine::cleanup().
init()
bool IRSender::init () [static]
Definition at line 39 of file IRSender.cpp.
{
  // initialize the IR device
  initPWM();
  return true;
}
References initPWM().
Referenced by VortexEngine::init().
initPWM()
void IRSender::initPWM () [static], [private]
Definition at line 175 of file IRSender.cpp.
{
#if defined(VORTEX_EMBEDDED)
  // just in case
  pinMode(IR_SEND_PWM_PIN, OUTPUT);
  digitalWrite(IR_SEND_PWM_PIN, LOW); // When not sending PWM, we want it low
  uint8_t port = g_APinDescription[IR_SEND_PWM_PIN].ulPort; // 0
  uint8_t pin = g_APinDescription[IR_SEND_PWM_PIN].ulPin; // 8
  ETCChannel IR_TCC_Channel = TCC0_CH0;
  int8_t IR_PER_EorF = PORT_PMUX_PMUXE_E;
  //println();Serial.print("Port:"); Serial.print(port,DEC); Serial.print(" Pin:"); Serial.println(pin,DEC);
  // Enable the port multiplexer for the PWM channel on pin
  PORT->Group[port].PINCFG[pin].bit.PMUXEN = 1;
  // Connect the TCC timer to the port outputs - port pins are paired odd PMUXO and even PMUXEII
  // F & E peripherals specify the timers: TCC0, TCC1 and TCC2
  PORT->Group[port].PMUX[pin >> 1].reg |= IR_PER_EorF;
// pinPeripheral (IR_SEND_PWM_PIN,PIO_TIMER_ALT);
  // Feed GCLK0 to TCC0 and TCC1
  REG_GCLK_CLKCTRL = GCLK_CLKCTRL_CLKEN | // Enable GCLK0 to TCC0 and TCC1
                     GCLK_CLKCTRL_GEN_GCLK0 | // Select GCLK0
                     GCLK_CLKCTRL_ID_TCC0_TCC1; // Feed GCLK0 to TCC0 and TCC1
  while (GCLK->STATUS.bit.SYNCBUSY); // Wait for synchronization
  // Normal (single slope) PWM operation: timers countinuously count up to PER
  // register value and then is reset to 0
  IR_TCCx = (Tcc*) GetTC(IR_TCC_Channel);
  IR_TCCx->WAVE.reg |= TCC_WAVE_WAVEGEN_NPWM; // Setup single slope PWM on TCCx
  while (IR_TCCx->SYNCBUSY.bit.WAVE); // Wait for synchronization
  // Each timer counts up to a maximum or TOP value set by the PER register,
  // this determines the frequency of the PWM operation.
  uint32_t cc = F_CPU/(38*1000) - 1;
  IR_TCCx->PER.reg = cc; // Set the frequency of the PWM on IR_TCCx
  while(IR_TCCx->SYNCBUSY.bit.PER);
  // The CCx register value corresponds to the pulsewidth in microseconds (us)
  // Set the duty cycle of the PWM on TCC0 to 33%
  IR_TCCx->CC[GetTCChannelNumber(IR_TCC_Channel)].reg = cc/3;
  while (IR_TCCx->SYNCBUSY.reg & TCC_SYNCBUSY_MASK);
  //while(IR_TCCx->SYNCBUSY.bit.CC3);
  // Enable IR_TCCx timer but do not turn on PWM yet. Will turn it on later.
  IR_TCCx->CTRLA.reg |= TCC_CTRLA_PRESCALER_DIV1; // Divide GCLK0 by 1
  while (IR_TCCx->SYNCBUSY.bit.ENABLE);
  IR_TCCx->CTRLA.reg &= ~TCC_CTRLA_ENABLE; //initially off will turn on later
  while (IR_TCCx->SYNCBUSY.bit.ENABLE);
#endif
}
References IR_SEND_PWM_PIN, and IR_TCCx.
Referenced by beginSend(), and init().
isSending()
static bool IRSender::isSending () [inline], [static]
Definition at line 25 of file IRSender.h.
{ return m_isSending; }
References m_isSending.
Referenced by ModeSharing::beginSendingIR(), and ModeSharing::continueSendingIR().
loadMode()
bool IRSender::loadMode (const Mode * targetMode) [static]
Definition at line 50 of file IRSender.cpp.
{
  m_serialBuf.clear();
  // save the target mode to it's savefile buffer format
  if (!targetMode->saveToBuffer(m_serialBuf)) {
    DEBUG_LOG("Failed to save mode to buffer");
    return false;
  }
  // ensure the data isn't too big
  if (m_serialBuf.rawSize() > IR_MAX_DATA_TRANSFER) {
    DEBUG_LOGF("Cannot transfer that much data: %u bytes", m_serialBuf.rawSize());
    return false;
  }
  // point the bitstream at the serial buffer
  m_bitStream.init((uint8_t *)m_serialBuf.rawData(), m_serialBuf.rawSize());
  // the size of the packet
  m_size = m_serialBuf.rawSize();
  // the number of blocks that will be sent (possibly just 1 with less than 32 bytes)
  m_numBlocks = (m_size + (IR_DEFAULT_BLOCK_SIZE - 1)) / IR_DEFAULT_BLOCK_SIZE;
  // the amount in the final block (possibly the only block)
  m_remainder = m_size % (IR_DEFAULT_BLOCK_SIZE + 0);
  DEBUG_LOGF("Num blocks: %u", m_numBlocks);
  DEBUG_LOGF("Remainder: %u", m_remainder);
  DEBUG_LOGF("Size: %u", m_size);
  // reset write counter
  m_writeCounter = 0;
  return true;
}
References ByteStream::clear(), DEBUG_LOG, DEBUG_LOGF, BitStream::init(), IR_DEFAULT_BLOCK_SIZE, IR_MAX_DATA_TRANSFER, m_bitStream, m_numBlocks, m_remainder, m_serialBuf, m_size, m_writeCounter, ByteStream::rawData(), ByteStream::rawSize(), and Mode::saveToBuffer().
Referenced by ModeSharing::beginSendingIR().
percentDone()
static uint32_t IRSender::percentDone () [inline], [static]
Definition at line 27 of file IRSender.h.
{ return (uint32_t)(((float)m_writeCounter / (float)m_size) * 100.0); }
References m_size, and m_writeCounter.
send()
bool IRSender::send () [static]
Definition at line 79 of file IRSender.cpp.
{
  // must have at least one block to send
  if (m_numBlocks < 1) {
    m_isSending = false;
    return m_isSending;
  }
  if (!m_isSending) {
    beginSend();
  }
  if (m_lastSendTime > 0 && m_lastSendTime + IR_DEFAULT_BLOCK_SPACING > Time::getCurtime()) {
    // don't send yet
    return m_isSending;
  }
  // blocksize is default unless it's the last block, then it's the remainder
  uint32_t blocksize = (m_numBlocks == 1) ? m_remainder : IR_DEFAULT_BLOCK_SIZE;
  DEBUG_LOGF("IRSender Sending block #%u", m_numBlocks);
  // pointer to the data at the correct location
  const uint8_t *buf_ptr = m_bitStream.data() + m_writeCounter;
  // iterate each byte in the block and write it
  for (uint32_t i = 0; i < blocksize; ++i) {
    // write the byte
    sendByte(*buf_ptr);
    // increment to next byte in buffer
    buf_ptr++;
    // record the written byte
    m_writeCounter++;
  }
  // wrote one block
  m_numBlocks--;
  // still sending if we have more blocks
  m_isSending = (m_numBlocks > 0);
  // the curtime
  m_lastSendTime = Time::getCurtime();
  // return whether still sending
  return m_isSending;
}
References beginSend(), BitStream::data(), DEBUG_LOGF, Time::getCurtime(), IR_DEFAULT_BLOCK_SIZE, IR_DEFAULT_BLOCK_SPACING, m_bitStream, m_isSending, m_lastSendTime, m_numBlocks, m_remainder, m_writeCounter, and sendByte().
Referenced by ModeSharing::beginSendingIR(), and ModeSharing::continueSendingIR().
sendByte()
void IRSender::sendByte (uint8_t data) [static], [private]
Definition at line 138 of file IRSender.cpp.
{
  // Sends from left to right, MSB first
  for (int b = 0; b < 8; b++) {
    // grab the bit of data at the indexspace
    uint32_t bit = (data >> (7 - b)) & 1;
    // send 3x timing size for 1s and 1x timing for 0
    sendMark(IR_TIMING + (IR_TIMING * (2 * bit)));
    // send 1x timing size for space
    sendSpace(IR_TIMING);
  }
  DEBUG_LOGF("Sent byte[%u]: 0x%x", m_writeCounter, data);
 }
References DEBUG_LOGF, IR_TIMING, m_writeCounter, sendMark(), and sendSpace().
Referenced by beginSend(), and send().
sendMark()
void IRSender::sendMark (uint16_t time) [static], [private]
Definition at line 152 of file IRSender.cpp.
{
#ifdef VORTEX_LIB
  // send mark timing over socket
  Vortex::vcallbacks()->infraredWrite(true, time);
#else
  startPWM();
  Time::delayMicroseconds(time);
#endif
}
References Time::delayMicroseconds(), and startPWM().
Referenced by beginSend(), and sendByte().
sendSpace()
void IRSender::sendSpace (uint16_t time) [static], [private]
Definition at line 163 of file IRSender.cpp.
{
#ifdef VORTEX_LIB
  // send space timing over socket
  Vortex::vcallbacks()->infraredWrite(false, time);
#else
  stopPWM();
  Time::delayMicroseconds(time);
#endif
}
References Time::delayMicroseconds(), and stopPWM().
Referenced by beginSend(), and sendByte().
startPWM()
void IRSender::startPWM () [static], [private]
Definition at line 226 of file IRSender.cpp.
{
#if defined(VORTEX_EMBEDDED)
  // start the PWM
  IR_TCCx->CTRLA.reg |= TCC_CTRLA_ENABLE;
  while (IR_TCCx->SYNCBUSY.bit.ENABLE);
#endif
}
References IR_TCCx.
Referenced by sendMark().
stopPWM()
void IRSender::stopPWM () [static], [private]
Definition at line 235 of file IRSender.cpp.
{
#if defined(VORTEX_EMBEDDED)
  // stop the PWM
  IR_TCCx->CTRLA.reg &= ~TCC_CTRLA_ENABLE;
  while (IR_TCCx->SYNCBUSY.bit.ENABLE);
#endif
}
References IR_TCCx.
Referenced by sendSpace().
Member Data Documentation
m_bitStream
BitStream IRSender::m_bitStream [static], [private]
Definition at line 46 of file IRSender.h.
Referenced by loadMode(), and send().
m_blockSize
uint32_t IRSender::m_blockSize = 0 [static], [private]
Definition at line 58 of file IRSender.h.
Referenced by beginSend().
m_isSending
bool IRSender::m_isSending = false [static], [private]
Definition at line 47 of file IRSender.h.
Referenced by beginSend(), isSending(), and send().
m_lastSendTime
uint32_t IRSender::m_lastSendTime = 0 [static], [private]
Definition at line 48 of file IRSender.h.
Referenced by send().
m_numBlocks
uint8_t IRSender::m_numBlocks = 0 [static], [private]
Definition at line 53 of file IRSender.h.
Referenced by beginSend(), loadMode(), and send().
m_remainder
uint8_t IRSender::m_remainder = 0 [static], [private]
Definition at line 55 of file IRSender.h.
Referenced by beginSend(), loadMode(), and send().
m_serialBuf
ByteStream IRSender::m_serialBuf [static], [private]
Definition at line 44 of file IRSender.h.
Referenced by loadMode().
m_size
uint32_t IRSender::m_size = 0 [static], [private]
Definition at line 51 of file IRSender.h.
Referenced by beginSend(), loadMode(), and percentDone().
m_writeCounter
uint32_t IRSender::m_writeCounter = 0 [static], [private]
Definition at line 61 of file IRSender.h.
Referenced by beginSend(), loadMode(), percentDone(), send(), and sendByte().
The documentation for this class was generated from the following files:
VortexEngine/src/Wireless/IRSender.h
VortexEngine/src/Wireless/IRSender.cpp