ByteStream Class Reference
#include <ByteStream.h>
Classes
struct RawBuffer
Public Member Functions
ByteStream (uint32_t size=0, const uint8_t *buf=nullptr)
~ByteStream ()
ByteStream (const ByteStream &other)
void operator= (const ByteStream &other)
void move (ByteStream *target)
bool rawInit (const uint8_t *rawdata, uint32_t size)
bool init (uint32_t capacity=0, const uint8_t *buf=nullptr)
void clear ()
bool shrink ()
bool append (const ByteStream &other)
bool extend (uint32_t size)
void trim (uint32_t bytes)
bool compress ()
bool decompress ()
uint32_t recalcCRC (bool force=false)
void sanity ()
bool checkCRC () const
bool isCRCDirty () const
bool serialize8 (uint8_t byte)
bool serialize16 (uint16_t bytes)
bool serialize32 (uint32_t bytes)
void resetUnserializer ()
void moveUnserializer (uint32_t idx)
bool unserializerAtEnd () const
bool unserialize8 (uint8_t *byte)
bool unserialize16 (uint16_t *bytes)
bool unserialize32 (uint32_t *bytes)
uint8_t peek8 () const
uint16_t peek16 () const
uint32_t peek32 () const
uint8_t & operator[] (uint32_t index)
operator uint8_t * () const
operator const uint8_t * () const
const uint8_t * data () const
void * rawData () const
uint32_t rawSize () const
uint32_t size () const
uint32_t capacity () const
bool is_compressed () const
uint32_t CRC () const
uint8_t * frontUnserializer () const
Private Member Functions
uint8_t * frontSerializer () const
bool largeEnough (uint32_t amount) const
uint32_t getWidth (uint32_t value) const
Private Attributes
RawBuffer * m_pData
uint32_t m_position
uint32_t m_capacity
Friends
class Storage
Detailed Description
Definition at line 17 of file ByteStream.h.
Constructor & Destructor Documentation
ByteStream() [1/2]
ByteStream::ByteStream (uint32_t size = 0, const uint8_t * buf = nullptr)
Definition at line 15 of file ByteStream.cpp.
                                                        :
  m_pData(),
  m_position(0),
  m_capacity(0)
{
  init(size, buf);
}
References init(), and size().
 ByteStream()
ByteStream::~ByteStream ()
Definition at line 23 of file ByteStream.cpp.
{
  clear();
}
References clear().
ByteStream() [2/2]
ByteStream::ByteStream (const ByteStream & other)
Definition at line 28 of file ByteStream.cpp.
                                              :
  ByteStream()
{
  init(other.capacity(), other.data());
  m_pData->flags = other.m_pData->flags;
  m_pData->crc32 = other.m_pData->crc32;
  m_pData->size = other.m_pData->size;
}
References capacity(), ByteStream::RawBuffer::crc32, data(), ByteStream::RawBuffer::flags, init(), m_pData, and ByteStream::RawBuffer::size.
Member Function Documentation
append()
bool ByteStream::append (const ByteStream & other)
Definition at line 136 of file ByteStream.cpp.
{
  if (!other.m_pData) {
    // nothing to append
    return true;
  }
  if (!m_pData || other.size() > (m_capacity - size())) {
    if (!extend(other.size())) {
      return false;
    }
  }
  memcpy(frontSerializer(), other.data(), other.size());
  m_pData->size += other.size();
  return true;
}
References data(), extend(), frontSerializer(), m_capacity, m_pData, size(), and ByteStream::RawBuffer::size.
capacity()
uint32_t ByteStream::capacity () const [inline]
Definition at line 112 of file ByteStream.h.
{ return m_capacity; }
References m_capacity.
Referenced by ByteStream(), VortexCLI::init(), and operator=().
checkCRC()
bool ByteStream::checkCRC () const
Definition at line 327 of file ByteStream.cpp.
{
  // don't check if dirty
  if (!m_pData || isCRCDirty()) {
    return false;
  }
  return m_pData->verify();
}
References isCRCDirty(), m_pData, and ByteStream::RawBuffer::verify().
Referenced by Storage::read().
clear()
void ByteStream::clear ()
Definition at line 107 of file ByteStream.cpp.
{
  if (m_pData) {
    vfree(m_pData);
    m_pData = nullptr;
  }
  m_capacity = 0;
  m_position = 0;
}
References m_capacity, m_pData, m_position, and vfree.
Referenced by init(), IRSender::loadMode(), VLSender::loadMode(), move(), Storage::read(), EditorConnection::receiveDemoMode(), EditorConnection::receiveMessage(), EditorConnection::receiveModes(), EditorConnection::run(), and ~ByteStream().
compress()
bool ByteStream::compress ()
Definition at line 205 of file ByteStream.cpp.
{
  // only compress if we have valid data
  if (!m_pData) {
    DEBUG_LOG("No data to compress");
    return false;
  }
  // recalculate the CRC even if we don't compress, this ensures the
  // CRC is always up to date as long as compress() is called
  recalcCRC();
  // don't actually perform any compression if VORTEX SLIM is enabled
#if VORTEX_SLIM == 0
  // check to see if the buffer is already compressed
  if (is_compressed()) {
    // already compressed
    return true;
  }
  // use LZ4_compressBound for the output buffer size, it may be larger
  // but it will allow for faster compression then we can shrink it after
  ByteStream compressedBuffer(compress_size(m_pData->size));
  // compress the data
  int compressedSize = compress_buffer(m_pData->buf, compressedBuffer.m_pData->buf,
    m_pData->size, compressedBuffer.m_capacity);
  // check for compression error
  if (compressedSize < 0) {
    DEBUG_LOGF("Failed to compress, error: %d", compressedSize);
    return false;
  }
  // check for useless compression
  if (!compressedSize || (uint32_t)compressedSize >= m_pData->size) {
    // cannot compress, or compressed no smaller than original
    return true;
  }
  // update the buffer size
  compressedBuffer.m_pData->size = compressedSize;
  // buffer is now compressed
  compressedBuffer.m_pData->flags = (m_pData->flags | BUFFER_FLAG_COMRPESSED);
  // recalc the crc on the data buffer
  compressedBuffer.m_pData->recalcCRC();
  // shrink buffer capacity to match size
  compressedBuffer.shrink();
  // move into self
  compressedBuffer.move(this);
#endif
  return true;
}
References ByteStream::RawBuffer::buf, BUFFER_FLAG_COMRPESSED, compress_buffer, compress_size, DEBUG_LOG, DEBUG_LOGF, ByteStream::RawBuffer::flags, is_compressed(), m_capacity, m_pData, move(), ByteStream::RawBuffer::recalcCRC(), recalcCRC(), shrink(), and ByteStream::RawBuffer::size.
Referenced by Modes::saveToBuffer(), and Mode::saveToBuffer().
CRC()
uint32_t ByteStream::CRC () const [inline]
Definition at line 114 of file ByteStream.h.
{ return m_pData ? m_pData->crc32 : 0; }
References ByteStream::RawBuffer::crc32, and m_pData.
Referenced by Vortex::addUndoBuffer().
data()
const uint8_t* ByteStream::data () const [inline]
Definition at line 108 of file ByteStream.h.
{ return m_pData ? m_pData->buf : nullptr; }
References ByteStream::RawBuffer::buf, and m_pData.
Referenced by append(), ByteStream(), operator=(), EditorConnection::receiveDemoMode(), and EditorConnection::receiveModes().
decompress()
bool ByteStream::decompress ()
Definition at line 252 of file ByteStream.cpp.
{
  // ensure the internal buffer is sane after reading it out, this
  // prevents segfaults if the internal size reports larger than capacity
  sanity();
  // only decompress if we have valid data
  if (!m_pData || !m_pData->verify()) {
    DEBUG_LOG("Cannot verify crc, not decompressing");
    return false;
  }
  // don't actually perform any compression if VORTEX SLIM is enabled
#if VORTEX_SLIM == 0
  if (!is_compressed()) {
    // already decompressed
    return true;
  }
  // first multiple will be 2x
  uint32_t multiple = 1;
  int decompressedSize = 0;
  ByteStream decompressedBuffer;
  do {
    // double the amount each time
    multiple *= 2;
    // create buffer to receive decompressed data
    decompressedBuffer.init(m_pData->size * multiple);
    // decompress the data
    decompressedSize = decompress_buffer(m_pData->buf, decompressedBuffer.m_pData->buf,
      m_pData->size, decompressedBuffer.m_capacity);
  } while (decompressedSize < 0 && multiple < 512);
  // still error
  if (decompressedSize < 0) {
    ERROR_LOGF("Failed to decompress: %d", decompressedSize);
    return false;
  }
  // size changed
  decompressedBuffer.m_pData->size = decompressedSize;
  // data is no longer compressed
  decompressedBuffer.m_pData->flags = (m_pData->flags & ~BUFFER_FLAG_COMRPESSED);
  // recalc crc of buffer
  decompressedBuffer.m_pData->recalcCRC();
  DEBUG_LOGF("Decompressed %u to %u bytes", m_pData->size, decompressedBuffer.m_pData->size);
  // shrink buffer capacity to match size
  decompressedBuffer.shrink();
  // move into self
  decompressedBuffer.move(this);
#endif
  return true;
}
References ByteStream::RawBuffer::buf, BUFFER_FLAG_COMRPESSED, DEBUG_LOG, DEBUG_LOGF, decompress_buffer, ERROR_LOGF, ByteStream::RawBuffer::flags, init(), is_compressed(), m_capacity, m_pData, move(), ByteStream::RawBuffer::recalcCRC(), sanity(), shrink(), ByteStream::RawBuffer::size, and ByteStream::RawBuffer::verify().
Referenced by Mode::loadFromBuffer(), Modes::loadFromBuffer(), and VLSender::loadMode().
extend()
bool ByteStream::extend (uint32_t size)
Definition at line 173 of file ByteStream.cpp.
{
  if (!size) {
    // ???
    return true;
  }
  // if the buffer is empty just initialize a new buffer
  if (!m_capacity) {
    return init(size);
  }
  // new size is current plus extension amount
  uint32_t buffer_size = m_capacity + size + 3;
  // round size up to nearest 4 and add the size of the base raw buffer
  buffer_size -= buffer_size % 4;
  // the size of the actual new block of memory
  uint32_t new_size = buffer_size + sizeof(RawBuffer);
  RawBuffer *temp = (RawBuffer *)vrealloc(m_pData, new_size);
  if (!temp) {
    ERROR_OUT_OF_MEMORY();
    return false;
  }
  // calc the region that was newly allocated by realloc
  uint8_t *new_mem = ((uint8_t *)temp) + sizeof(RawBuffer) + m_capacity;
  size_t new_mem_size = buffer_size - m_capacity;
  // zero out the new memory
  memset(new_mem, 0, new_mem_size);
  // update the pointer and size of the serial buffer
  m_pData = temp;
  m_capacity = buffer_size;
  return true;
}
References ERROR_OUT_OF_MEMORY, init(), m_capacity, m_pData, size(), and vrealloc.
Referenced by append(), serialize16(), serialize32(), and serialize8().
frontSerializer()
uint8_t* ByteStream::frontSerializer () const [inline], [private]
Definition at line 121 of file ByteStream.h.
{ return m_pData ? m_pData->buf + m_pData->size : nullptr; }
References ByteStream::RawBuffer::buf, m_pData, and ByteStream::RawBuffer::size.
Referenced by append().
frontUnserializer()
uint8_t* ByteStream::frontUnserializer () const [inline]
Definition at line 116 of file ByteStream.h.
{ return m_pData ? m_pData->buf + m_position : nullptr; }
References ByteStream::RawBuffer::buf, m_pData, and m_position.
Referenced by peek16(), peek32(), peek8(), and EditorConnection::receiveMessage().
getWidth()
uint32_t ByteStream::getWidth (uint32_t value) const [private]
Definition at line 493 of file ByteStream.cpp.
{
  if (!value) {
    return 0;
  }
  for (uint32_t i = 0; i < 31; ++i) {
    if (value < (uint32_t)(1 << i)) {
      return i;
    }
  }
  return 0;
}
init()
bool ByteStream::init (uint32_t capacity = 0, const uint8_t * buf = nullptr)
Definition at line 82 of file ByteStream.cpp.
{
  clear();
  if (size) {
    // round up to nearest 4
    m_capacity = (size + 4) - (size % 4);
    m_pData = (RawBuffer *)vcalloc(1, m_capacity + sizeof(RawBuffer));
    if (!m_pData) {
      m_capacity = 0;
      ERROR_OUT_OF_MEMORY();
      return false;
    }
    m_pData->size = 0;
    m_pData->flags = 0;
    m_pData->crc32 = 0;
    memset(m_pData->buf, 0, m_capacity);
  }
  if (buf && m_pData) {
    memcpy(m_pData->buf, buf, size);
    m_pData->size = size;
    m_pData->recalcCRC();
  }
  return true;
}
References ByteStream::RawBuffer::buf, clear(), ByteStream::RawBuffer::crc32, ERROR_OUT_OF_MEMORY, ByteStream::RawBuffer::flags, m_capacity, m_pData, ByteStream::RawBuffer::recalcCRC(), size(), ByteStream::RawBuffer::size, and vcalloc.
Referenced by ByteStream(), decompress(), extend(), operator=(), and Storage::read().
is_compressed()
bool ByteStream::is_compressed () const
Definition at line 474 of file ByteStream.cpp.
{
  if (!m_pData) {
    return false;
  }
  return (m_pData->flags & BUFFER_FLAG_COMRPESSED) != 0;
}
References BUFFER_FLAG_COMRPESSED, ByteStream::RawBuffer::flags, and m_pData.
Referenced by compress(), and decompress().
isCRCDirty()
bool ByteStream::isCRCDirty () const
Definition at line 336 of file ByteStream.cpp.
{
  return (m_pData && (m_pData->flags & BUFFER_FLAG_DIRTY) != 0);
}
References BUFFER_FLAG_DIRTY, ByteStream::RawBuffer::flags, and m_pData.
Referenced by checkCRC().
largeEnough()
bool ByteStream::largeEnough (uint32_t amount) const [private]
Definition at line 482 of file ByteStream.cpp.
{
  if (!m_pData) {
    return false;
  }
  return ((m_pData->size + amount) <= m_capacity);
}
References m_capacity, m_pData, and ByteStream::RawBuffer::size.
move()
void ByteStream::move (ByteStream * target)
Definition at line 45 of file ByteStream.cpp.
{
  if (!target) {
    return;
  }
  target->clear();
  target->m_pData = m_pData;
  target->m_position = m_position;
  target->m_capacity = m_capacity;
  m_pData = nullptr;
  m_position = 0;
  m_capacity = 0;
}
References clear(), m_capacity, m_pData, and m_position.
Referenced by compress(), and decompress().
moveUnserializer()
void ByteStream::moveUnserializer (uint32_t idx)
Definition at line 397 of file ByteStream.cpp.
{
  if (!m_pData) {
    return;
  }
  if (idx >= m_pData->size) {
    idx = 0;
  }
  m_position = idx;
}
References m_pData, m_position, and ByteStream::RawBuffer::size.
Referenced by resetUnserializer().
operator const uint8_t *()
ByteStream::operator const uint8_t * () const [inline]
Definition at line 105 of file ByteStream.h.
{ return m_pData ? m_pData->buf : nullptr; }
References ByteStream::RawBuffer::buf, and m_pData.
operator uint8_t *()
ByteStream::operator uint8_t * () const [inline]
Definition at line 104 of file ByteStream.h.
{ return m_pData ? m_pData->buf : nullptr; }
References ByteStream::RawBuffer::buf, and m_pData.
operator=()
void ByteStream::operator= (const ByteStream & other)
Definition at line 37 of file ByteStream.cpp.
{
  init(other.capacity(), other.data());
  m_pData->flags = other.m_pData->flags;
  m_pData->crc32 = other.m_pData->crc32;
  m_pData->size = other.m_pData->size;
}
References capacity(), ByteStream::RawBuffer::crc32, data(), ByteStream::RawBuffer::flags, init(), m_pData, and ByteStream::RawBuffer::size.
operator[]()
uint8_t& ByteStream::operator[] (uint32_t index) [inline]
Definition at line 102 of file ByteStream.h.
{ return m_pData->buf[index]; }
References ByteStream::RawBuffer::buf, and m_pData.
peek16()
uint16_t ByteStream::peek16 () const
Definition at line 458 of file ByteStream.cpp.
{
  if (!m_pData) {
    return 0;
  }
  return *(uint16_t *)frontUnserializer();
}
References frontUnserializer(), and m_pData.
peek32()
uint32_t ByteStream::peek32 () const
Definition at line 466 of file ByteStream.cpp.
{
  if (!m_pData) {
    return 0;
  }
  return *(uint32_t *)frontUnserializer();
}
References frontUnserializer(), and m_pData.
Referenced by EditorConnection::receiveDemoMode(), and EditorConnection::receiveModes().
peek8()
uint8_t ByteStream::peek8 () const
Definition at line 450 of file ByteStream.cpp.
{
  if (!m_pData) {
    return 0;
  }
  return *(uint8_t *)frontUnserializer();
}
References frontUnserializer(), and m_pData.
rawData()
void* ByteStream::rawData () const [inline]
Definition at line 109 of file ByteStream.h.
{ return m_pData; }
References m_pData.
Referenced by VortexCLI::cleanup(), VortexCLI::init(), IRSender::loadMode(), VLSender::loadMode(), Storage::read(), EditorConnection::receiveDemoMode(), EditorConnection::receiveModes(), SerialComs::write(), and Storage::write().
rawInit()
bool ByteStream::rawInit (const uint8_t * rawdata, uint32_t size)
Definition at line 59 of file ByteStream.cpp.
{
  if (!rawdata || size < sizeof(RawBuffer)) {
    DEBUG_LOGF("Cannot rawInit: %p %u", rawdata, size);
    return false;
  }
  // round up to nearest 4
  m_capacity = (size + 4) - (size % 4);
  m_pData = (RawBuffer *)vcalloc(1, m_capacity + sizeof(RawBuffer));
  if (!m_pData) {
    m_capacity = 0;
    ERROR_OUT_OF_MEMORY();
    return false;
  }
  // copy in the actual data from the serial buffer, this will fill the
  // members: size, flags, and crc32 of m_pData as well as the buf
  memcpy(m_pData, rawdata, size);
  // ensure the internal size doesn't exceed outer size
  sanity();
  return true;
}
References DEBUG_LOGF, ERROR_OUT_OF_MEMORY, m_capacity, m_pData, sanity(), size(), and vcalloc.
Referenced by IRReceiver::read(), and VLReceiver::read().
rawSize()
uint32_t ByteStream::rawSize () const [inline]
Definition at line 110 of file ByteStream.h.
{ return m_pData ? m_pData->size + sizeof(RawBuffer) : 0; }
References m_pData, and ByteStream::RawBuffer::size.
Referenced by VortexCLI::cleanup(), IRSender::loadMode(), VLSender::loadMode(), EditorConnection::receiveDemoMode(), IRReceiver::receiveMode(), VLReceiver::receiveMode(), EditorConnection::receiveModes(), SerialComs::write(), and Storage::write().
recalcCRC()
uint32_t ByteStream::recalcCRC (bool force = false)
Definition at line 301 of file ByteStream.cpp.
{
  if (!m_pData || !m_pData->size) {
    return 0;
  }
  // is the crc dirty?
  // or is the recalc being forced anyway?
  if (!force && !(m_pData->flags & BUFFER_FLAG_DIRTY)) {
    return 0;
  }
  // re-calculate the CRC on the buffer
  m_pData->recalcCRC();
  // unset dirty flag
  m_pData->flags &= ~BUFFER_FLAG_DIRTY;
  // return the newly calculated crc
  return m_pData->crc32;
}
References BUFFER_FLAG_DIRTY, ByteStream::RawBuffer::crc32, ByteStream::RawBuffer::flags, m_pData, ByteStream::RawBuffer::recalcCRC(), and ByteStream::RawBuffer::size.
Referenced by compress(), Randomizer::init(), SerialComs::write(), and Storage::write().
resetUnserializer()
void ByteStream::resetUnserializer ()
Definition at line 391 of file ByteStream.cpp.
{
  moveUnserializer(0);
}
References moveUnserializer().
Referenced by Mode::loadFromBuffer(), EditorConnection::receiveDemoMode(), and EditorConnection::receiveModes().
sanity()
void ByteStream::sanity ()
Definition at line 319 of file ByteStream.cpp.
{
  // to ensure size never exceeds the buffer capacity
  if (m_pData && m_pData->size > m_capacity) {
    m_pData->size = m_capacity;
  }
}
References m_capacity, m_pData, and ByteStream::RawBuffer::size.
Referenced by decompress(), rawInit(), and Storage::read().
serialize16()
bool ByteStream::serialize16 (uint16_t bytes)
Definition at line 357 of file ByteStream.cpp.
{
  //DEBUG_LOGF("Serialize16(): %u", bytes);
  if (!m_pData || (m_pData->size + sizeof(uint16_t)) > m_capacity) {
    if (!extend(sizeof(uint32_t))) {
      return false;
    }
  }
  memcpy(m_pData->buf + m_pData->size, &bytes, sizeof(uint16_t));
  // walk forward
  m_pData->size += sizeof(uint16_t);
  // dirty the crc
  m_pData->flags |= BUFFER_FLAG_DIRTY;
  return true;
}
References ByteStream::RawBuffer::buf, BUFFER_FLAG_DIRTY, extend(), ByteStream::RawBuffer::flags, m_capacity, m_pData, and ByteStream::RawBuffer::size.
Referenced by SequenceStep::serialize().
serialize32()
bool ByteStream::serialize32 (uint32_t bytes)
Definition at line 373 of file ByteStream.cpp.
{
  //DEBUG_LOGF("Serialize32(): %u", bytes);
  if (!m_pData || (m_pData->size + sizeof(uint32_t)) > m_capacity) {
    if (!extend(sizeof(uint32_t))) {
      return false;
    }
  }
  memcpy(m_pData->buf + m_pData->size, &bytes, sizeof(uint32_t));
  // walk forward
  m_pData->size += sizeof(uint32_t);
  // dirty the crc
  m_pData->flags |= BUFFER_FLAG_DIRTY;
  return true;
}
References ByteStream::RawBuffer::buf, BUFFER_FLAG_DIRTY, extend(), ByteStream::RawBuffer::flags, m_capacity, m_pData, and ByteStream::RawBuffer::size.
Referenced by Mode::serialize().
serialize8()
bool ByteStream::serialize8 (uint8_t byte)
Definition at line 341 of file ByteStream.cpp.
{
  //DEBUG_LOGF("Serialize8(): %u", byte);
  if (!m_pData || (m_pData->size + sizeof(uint8_t)) > m_capacity) {
    if (!extend(sizeof(uint32_t))) {
      return false;
    }
  }
  memcpy(m_pData->buf + m_pData->size, &byte, sizeof(uint8_t));
  // walk forward
  m_pData->size += sizeof(uint8_t);
  // dirty the crc
  m_pData->flags |= BUFFER_FLAG_DIRTY;
  return true;
}
References ByteStream::RawBuffer::buf, BUFFER_FLAG_DIRTY, extend(), ByteStream::RawBuffer::flags, m_capacity, m_pData, and ByteStream::RawBuffer::size.
Referenced by SerialComs::read(), Modes::saveHeader(), Modes::serialize(), Colorset::serialize(), RGBColor::serialize(), PatternMap::serialize(), Sequence::serialize(), Pattern::serialize(), PatternArgs::serialize(), Mode::serialize(), Modes::serializeSaveHeader(), and VortexEngine::serializeVersion().
shrink()
bool ByteStream::shrink ()
Definition at line 117 of file ByteStream.cpp.
{
  if (!m_pData) {
    return false;
  }
  if (m_pData->size == m_capacity) {
    return true;
  }
  m_capacity = m_pData->size;
  RawBuffer *temp = (RawBuffer *)vrealloc(m_pData, m_pData->size + sizeof(RawBuffer));
  if (!temp) {
    ERROR_OUT_OF_MEMORY();
    return false;
  }
  m_pData = temp;
  return true;
}
References ERROR_OUT_OF_MEMORY, m_capacity, m_pData, ByteStream::RawBuffer::size, and vrealloc.
Referenced by compress(), and decompress().
size()
uint32_t ByteStream::size () const [inline]
Definition at line 111 of file ByteStream.h.
{ return m_pData ? m_pData->size : 0; }
References m_pData, and ByteStream::RawBuffer::size.
Referenced by Vortex::addUndoBuffer(), Modes::ModeLink::append(), append(), ByteStream(), extend(), init(), Modes::loadHeader(), Modes::loadStorage(), Modes::ModeLink::ModeLink(), rawInit(), Storage::read(), EditorConnection::receiveDemoMode(), EditorConnection::receiveMessage(), EditorConnection::receiveModes(), Modes::saveToBuffer(), Mode::saveToBuffer(), Modes::serializeSaveHeader(), and Modes::unserialize().
trim()
void ByteStream::trim (uint32_t bytes)
Definition at line 153 of file ByteStream.cpp.
{
  if (!m_pData) {
    return;
  }
  // just adjust the data size no need to reallocate, this
  // will put the extra bytes into 'extra space' and shrink()
  // could be called to reallocate the buffer without them
  if (m_pData->size <= bytes) {
    m_pData->size = 0;
  } else {
    m_pData->size -= bytes;
  }
  // move the unserializer back if necessary
  if (m_position >= m_pData->size) {
    m_position = m_pData->size;
  }
}
References m_pData, m_position, and ByteStream::RawBuffer::size.
unserialize16()
bool ByteStream::unserialize16 (uint16_t * bytes)
Definition at line 428 of file ByteStream.cpp.
{
  if (!m_pData || m_position >= m_pData->size || (m_pData->size - m_position) < sizeof(uint16_t)) {
    return false;
  }
  memcpy(bytes, m_pData->buf + m_position, sizeof(uint16_t));
  //DEBUG_LOGF("Unserialize16(): %u", *bytes);
  m_position += sizeof(uint16_t);
  return true;
}
References ByteStream::RawBuffer::buf, m_pData, m_position, and ByteStream::RawBuffer::size.
Referenced by SequenceStep::unserialize().
unserialize32()
bool ByteStream::unserialize32 (uint32_t * bytes)
Definition at line 439 of file ByteStream.cpp.
{
  if (!m_pData || m_position >= m_pData->size || (m_pData->size - m_position) < sizeof(uint32_t)) {
    return false;
  }
  memcpy(bytes, m_pData->buf + m_position, sizeof(uint32_t));
  //DEBUG_LOGF("Unserialize32(): %u", *bytes);
  m_position += sizeof(uint32_t);
  return true;
}
References ByteStream::RawBuffer::buf, m_pData, m_position, and ByteStream::RawBuffer::size.
Referenced by EditorConnection::receiveDemoMode(), EditorConnection::receiveModes(), and Mode::unserialize().
unserialize8()
bool ByteStream::unserialize8 (uint8_t * byte)
Definition at line 417 of file ByteStream.cpp.
{
  if (!m_pData || m_position >= m_pData->size || (m_pData->size - m_position) < sizeof(uint8_t)) {
    return false;
  }
  memcpy(byte, m_pData->buf + m_position, sizeof(uint8_t));
  //DEBUG_LOGF("Unserialize8(): %u", *byte);
  m_position += sizeof(uint8_t);
  return true;
}
References ByteStream::RawBuffer::buf, m_pData, m_position, and ByteStream::RawBuffer::size.
Referenced by Mode::loadFromBuffer(), Modes::loadStorage(), EditorConnection::receiveMessage(), Colorset::unserialize(), RGBColor::unserialize(), Mode::unserialize(), Modes::unserialize(), PatternMap::unserialize(), Sequence::unserialize(), PatternArgs::unserialize(), and PatternBuilder::unserialize().
unserializerAtEnd()
bool ByteStream::unserializerAtEnd () const
Definition at line 408 of file ByteStream.cpp.
{
  // the serializer always points to the end of the buffer,
  // if the unserializer points there too then there's nothing
  // more for the unserializer to read
  return m_pData && m_position == m_pData->size;
}
References m_pData, m_position, and ByteStream::RawBuffer::size.
Referenced by EditorConnection::receiveMessage().
Friends And Related Function Documentation
Storage
friend class Storage [friend]
Definition at line 19 of file ByteStream.h.
Member Data Documentation
m_capacity
uint32_t ByteStream::m_capacity [private]
Definition at line 178 of file ByteStream.h.
Referenced by append(), capacity(), clear(), compress(), decompress(), extend(), init(), largeEnough(), move(), rawInit(), sanity(), serialize16(), serialize32(), serialize8(), and shrink().
m_pData
RawBuffer* ByteStream::m_pData [private]
Definition at line 174 of file ByteStream.h.
Referenced by append(), ByteStream(), checkCRC(), clear(), compress(), CRC(), data(), decompress(), extend(), frontSerializer(), frontUnserializer(), init(), is_compressed(), isCRCDirty(), largeEnough(), move(), moveUnserializer(), operator const uint8_t *(), operator uint8_t *(), operator=(), operator[](), peek16(), peek32(), peek8(), rawData(), rawInit(), rawSize(), recalcCRC(), sanity(), serialize16(), serialize32(), serialize8(), shrink(), size(), trim(), unserialize16(), unserialize32(), unserialize8(), and unserializerAtEnd().
m_position
uint32_t ByteStream::m_position [private]
Definition at line 176 of file ByteStream.h.
Referenced by clear(), frontUnserializer(), move(), moveUnserializer(), trim(), unserialize16(), unserialize32(), unserialize8(), and unserializerAtEnd().
The documentation for this class was generated from the following files:
VortexEngine/src/Serial/ByteStream.h
VortexEngine/src/Serial/ByteStream.cpp