Sequence Class Reference
#include <Sequence.h>
Public Member Functions
Sequence ()
~Sequence ()
Sequence (const Sequence &other)
Sequence (Sequence &&other) noexcept
void operator= (const Sequence &other)
bool operator== (const Sequence &other) const
bool operator!= (const Sequence &other) const
void initSteps (uint8_t numSteps)
uint8_t addStep (const SequenceStep &step)
uint8_t addStep (uint16_t duration, const PatternMap &patternMap, const ColorsetMap &colorsetMap=Colorset())
void clear ()
bool serialize (ByteStream &buffer) const
bool unserialize (ByteStream &buffer)
uint8_t numSteps () const
const SequenceStep & operator[] (uint8_t index) const
Private Attributes
SequenceStep * m_sequenceSteps
uint8_t m_numSteps
Detailed Description
Definition at line 70 of file Sequence.h.
Constructor & Destructor Documentation
Sequence() [1/3]
Sequence::Sequence ()
Definition at line 150 of file Sequence.cpp.
                   :
  m_sequenceSteps(nullptr),
  m_numSteps(0)
{
}
 Sequence()
Sequence::~Sequence ()
Definition at line 156 of file Sequence.cpp.
{
  clear();
}
References clear().
Sequence() [2/3]
Sequence::Sequence (const Sequence & other)
Definition at line 161 of file Sequence.cpp.
                                        :
  Sequence()
{
  // invoke = operator
  *this = other;
}
Sequence() [3/3]
Sequence::Sequence (Sequence && other) [noexcept]
Definition at line 168 of file Sequence.cpp.
                                            :
  m_sequenceSteps(other.m_sequenceSteps),
  m_numSteps(other.m_numSteps)
{
  other.m_sequenceSteps = nullptr;
  other.m_numSteps = 0;
}
Member Function Documentation
addStep() [1/2]
uint8_t Sequence::addStep (const SequenceStep & step)
Definition at line 210 of file Sequence.cpp.
{
  if (m_numSteps >= MAX_SEQUENCE_STEPS) {
    return false;
  }
  // allocate a new palette one larger than before
  SequenceStep *temp = new SequenceStep[m_numSteps + 1];
  if (!temp) {
    return false;
  }
  // if there is already some colors in the palette
  if (m_numSteps && m_sequenceSteps) {
    // copy over existing colors
    for (uint8_t i = 0; i < m_numSteps; ++i) {
      temp[i] = m_sequenceSteps[i];
    }
    // and delete the existing palette
    delete[] m_sequenceSteps;
  }
  // reassign new palette
  m_sequenceSteps = temp;
  // insert new color and increment number of colors
  m_sequenceSteps[m_numSteps] = step;
  m_numSteps++;
  return true;
}
References m_numSteps, m_sequenceSteps, and MAX_SEQUENCE_STEPS.
Referenced by addStep(), and ChaserPattern::ChaserPattern().
addStep() [2/2]
uint8_t Sequence::addStep (uint16_t duration, const PatternMap & patternMap, const ColorsetMap & colorsetMap = Colorset())
Definition at line 237 of file Sequence.cpp.
{
  return addStep(SequenceStep(duration, patternMap, colorsetMap));
}
References addStep().
clear()
void Sequence::clear ()
Definition at line 242 of file Sequence.cpp.
{
  if (m_sequenceSteps) {
    delete[] m_sequenceSteps;
    m_sequenceSteps = nullptr;
  }
  m_numSteps = 0;
}
References m_numSteps, and m_sequenceSteps.
Referenced by operator=(), and ~Sequence().
initSteps()
void Sequence::initSteps (uint8_t numSteps)
Definition at line 197 of file Sequence.cpp.
{
  if (m_sequenceSteps) {
    delete[] m_sequenceSteps;
  }
  m_sequenceSteps = new SequenceStep[numSteps];
  if (!m_sequenceSteps) {
    ERROR_OUT_OF_MEMORY();
    return;
  }
  m_numSteps = numSteps;
}
References ERROR_OUT_OF_MEMORY, m_numSteps, m_sequenceSteps, and numSteps().
Referenced by operator=().
numSteps()
uint8_t Sequence::numSteps () const
Definition at line 277 of file Sequence.cpp.
{
  return m_numSteps;
}
References m_numSteps.
Referenced by SequencedPattern::init(), initSteps(), and SequencedPattern::play().
operator!=()
bool Sequence::operator!= (const Sequence & other) const
Definition at line 192 of file Sequence.cpp.
{
  return !operator==(other);
}
References operator==().
operator=()
void Sequence::operator= (const Sequence & other)
Definition at line 176 of file Sequence.cpp.
{
  clear();
  initSteps(other.m_numSteps);
  for (uint8_t i = 0; i < other.m_numSteps; ++i) {
    m_sequenceSteps[i] = other.m_sequenceSteps[i];
  }
}
References clear(), initSteps(), m_numSteps, and m_sequenceSteps.
operator==()
bool Sequence::operator== (const Sequence & other) const
Definition at line 185 of file Sequence.cpp.
{
  // only compare the palettes for equality
  return (m_numSteps == other.m_numSteps) &&
    (memcmp(m_sequenceSteps, other.m_sequenceSteps, m_numSteps * sizeof(SequenceStep)) == 0);
}
References m_numSteps, and m_sequenceSteps.
Referenced by operator!=().
operator[]()
const SequenceStep & Sequence::operator[] (uint8_t index) const
Definition at line 282 of file Sequence.cpp.
{
  return m_sequenceSteps[index];
}
References m_sequenceSteps.
serialize()
bool Sequence::serialize (ByteStream & buffer) const
Definition at line 251 of file Sequence.cpp.
{
  if (!buffer.serialize8(m_numSteps)) {
    return false;
  }
  for (uint8_t i = 0; i < m_numSteps; ++i) {
    if (!m_sequenceSteps[i].serialize(buffer)) {
      return false;
    }
  }
  return true;
}
References m_numSteps, m_sequenceSteps, and ByteStream::serialize8().
unserialize()
bool Sequence::unserialize (ByteStream & buffer)
Definition at line 264 of file Sequence.cpp.
{
  if (!buffer.unserialize8(&m_numSteps)) {
    return false;
  }
  for (uint8_t i = 0; i < m_numSteps; ++i) {
    if (!m_sequenceSteps[i].unserialize(buffer)) {
      return false;
    }
  }
  return true;
}
References m_numSteps, m_sequenceSteps, and ByteStream::unserialize8().
Member Data Documentation
m_numSteps
uint8_t Sequence::m_numSteps [private]
Definition at line 97 of file Sequence.h.
Referenced by addStep(), clear(), initSteps(), numSteps(), operator=(), operator==(), serialize(), and unserialize().
m_sequenceSteps
SequenceStep* Sequence::m_sequenceSteps [private]
Definition at line 96 of file Sequence.h.
Referenced by addStep(), clear(), initSteps(), operator=(), operator==(), operator[](), serialize(), and unserialize().
The documentation for this class was generated from the following files:
VortexEngine/src/Patterns/Multi/Sequencer/Sequence.h
VortexEngine/src/Patterns/Multi/Sequencer/Sequence.cpp