Buttons Class Reference
#include <Buttons.h>
Public Member Functions
Buttons (VortexEngine &engine)
~Buttons ()
bool init ()
void cleanup ()
void update ()
Button & button (uint8_t index=0)
Private Attributes
VortexEngine & m_engine
Button m_buttons [NUM_BUTTONS]
Detailed Description
Definition at line 14 of file Buttons.h.
Constructor & Destructor Documentation
Buttons()
Buttons::Buttons (VortexEngine & engine)
Definition at line 10 of file Buttons.cpp.
                                     :
  m_engine(engine),
  m_buttons{ engine }
{
}
 Buttons()
Buttons::~Buttons ()
Definition at line 16 of file Buttons.cpp.
{
}
Member Function Documentation
button()
Button& Buttons::button (uint8_t index = 0) [inline]
Definition at line 28 of file Buttons.h.
{ return m_buttons[index]; }
References m_buttons.
Referenced by VortexEngine::button().
cleanup()
void Buttons::cleanup ()
Definition at line 29 of file Buttons.cpp.
{
}
Referenced by VortexEngine::cleanup().
init()
bool Buttons::init ()
Definition at line 20 of file Buttons.cpp.
{
  // initialize the button on pin 1
  if (!m_buttons[0].init(1)) {
    return false;
  }
  return true;
}
References m_buttons.
Referenced by VortexEngine::init().
update()
void Buttons::update ()
Definition at line 33 of file Buttons.cpp.
{
  // would iterate all buttons and check them here
  // but there's only one button so
  for (uint8_t i = 0; i < NUM_BUTTONS; ++i) {
    m_buttons[i].update();
  }
#ifdef VORTEX_LIB
  // read input from the vortex lib interface, for example m_engine.vortexLib().shortClick()
  m_engine.vortexLib().handleInputQueue(m_buttons, NUM_BUTTONS);
#endif
}
References m_buttons, m_engine, NUM_BUTTONS, Button::update(), and VortexEngine::vortexLib().
Referenced by VortexEngine::tick().
Member Data Documentation
m_buttons
Button Buttons::m_buttons[NUM_BUTTONS] [private]
Definition at line 35 of file Buttons.h.
Referenced by button(), init(), and update().
m_engine
VortexEngine& Buttons::m_engine [private]
Definition at line 32 of file Buttons.h.
Referenced by update().
The documentation for this class was generated from the following files:
VortexEngine/src/Buttons/Buttons.h
VortexEngine/src/Buttons/Buttons.cpp