EditorConnection Class Reference
#include <EditorConnection.h>
Public Member Functions
EditorConnection (VortexEngine &engine, const RGBColor &col, bool advanced)
~EditorConnection ()
bool init () override
MenuAction run () override
void sendCurModeVL ()
void onShortClick () override
void onLongClick () override
void leaveMenu (bool doSave=false) override
Private Types
enum EditorConnectionState {
STATE_DISCONNECTED,
STATE_GREETING,
STATE_IDLE,
STATE_PULL_MODES,
STATE_PULL_MODES_SEND,
STATE_PULL_MODES_DONE,
STATE_PUSH_MODES,
STATE_PUSH_MODES_RECEIVE,
STATE_PUSH_MODES_DONE,
STATE_DEMO_MODE,
STATE_DEMO_MODE_RECEIVE,
STATE_DEMO_MODE_DONE,
STATE_CLEAR_DEMO,
STATE_TRANSMIT_MODE_VL,
STATE_TRANSMIT_MODE_VL_DONE
 }
Private Member Functions
void showEditor ()
void receiveData ()
void sendModes ()
bool receiveModes ()
bool receiveDemoMode ()
void handleCommand ()
bool receiveMessage (const char *message)
void clearDemo ()
Private Attributes
EditorConnectionState m_state
ByteStream m_receiveBuffer
Additional Inherited Members
Detailed Description
Definition at line 9 of file EditorConnection.h.
Member Enumeration Documentation
EditorConnectionState
enum EditorConnection::EditorConnectionState [private]
Enumerator
STATE_DISCONNECTED
STATE_GREETING
STATE_IDLE
STATE_PULL_MODES
STATE_PULL_MODES_SEND
STATE_PULL_MODES_DONE
STATE_PUSH_MODES
STATE_PUSH_MODES_RECEIVE
STATE_PUSH_MODES_DONE
STATE_DEMO_MODE
STATE_DEMO_MODE_RECEIVE
STATE_DEMO_MODE_DONE
STATE_CLEAR_DEMO
STATE_TRANSMIT_MODE_VL
STATE_TRANSMIT_MODE_VL_DONE
Definition at line 38 of file EditorConnection.h.
                             {
    // the editor is not connec
    STATE_DISCONNECTED,
    // Sending the greeting message
    STATE_GREETING,
    // entirely idle, waiting for commands
    STATE_IDLE,
    // engine pulls the modes from gloves, then wait for the sent modes ack
    STATE_PULL_MODES,
    STATE_PULL_MODES_SEND,
    STATE_PULL_MODES_DONE,
    // engine pushes modes to gloves, then waits for done
    STATE_PUSH_MODES,
    STATE_PUSH_MODES_RECEIVE,
    STATE_PUSH_MODES_DONE,
    // engine pushes mode to gloves for demo while idle
    STATE_DEMO_MODE,
    STATE_DEMO_MODE_RECEIVE,
    STATE_DEMO_MODE_DONE,
    // engine tells gloves to clear the demo preview, gloves acknowledge
    STATE_CLEAR_DEMO,
    // transmit the mode over visible light
    STATE_TRANSMIT_MODE_VL,
    STATE_TRANSMIT_MODE_VL_DONE,
  };
Constructor & Destructor Documentation
EditorConnection()
EditorConnection::EditorConnection (VortexEngine & engine, const RGBColor & col, bool advanced)
Definition at line 19 of file EditorConnection.cpp.
                                                                                           :
  Menu(engine, col, advanced),
  m_state(STATE_DISCONNECTED)
{
}
 EditorConnection()
EditorConnection::~EditorConnection ()
Definition at line 25 of file EditorConnection.cpp.
{
  clearDemo();
}
References clearDemo().
Member Function Documentation
clearDemo()
void EditorConnection::clearDemo () [private]
Definition at line 65 of file EditorConnection.cpp.
{
  Colorset set(RGB_WHITE0);
  PatternArgs args(1, 0, 0);
  m_previewMode.setPattern(PATTERN_STROBE, LED_ALL, &args, &set);
  m_previewMode.init();
}
References Mode::init(), LED_ALL, Menu::m_previewMode, PATTERN_STROBE, RGB_WHITE0, and Mode::setPattern().
Referenced by init(), onShortClick(), run(), and ~EditorConnection().
handleCommand()
void EditorConnection::handleCommand () [private]
Definition at line 321 of file EditorConnection.cpp.
{
  if (receiveMessage(EDITOR_VERB_PULL_MODES)) {
    m_state = STATE_PULL_MODES;
  } else if (receiveMessage(EDITOR_VERB_PUSH_MODES)) {
    m_state = STATE_PUSH_MODES;
  } else if (receiveMessage(EDITOR_VERB_DEMO_MODE)) {
    m_state = STATE_DEMO_MODE;
  } else if (receiveMessage(EDITOR_VERB_CLEAR_DEMO)) {
    m_state = STATE_CLEAR_DEMO;
  } else if (receiveMessage(EDITOR_VERB_TRANSMIT_VL)) {
    sendCurModeVL();
  }
}
References EDITOR_VERB_CLEAR_DEMO, EDITOR_VERB_DEMO_MODE, EDITOR_VERB_PULL_MODES, EDITOR_VERB_PUSH_MODES, EDITOR_VERB_TRANSMIT_VL, m_state, receiveMessage(), sendCurModeVL(), STATE_CLEAR_DEMO, STATE_DEMO_MODE, STATE_PULL_MODES, and STATE_PUSH_MODES.
Referenced by run().
init()
bool EditorConnection::init () [override], [virtual]
Reimplemented from Menu.
Definition at line 30 of file EditorConnection.cpp.
{
  if (!Menu::init()) {
    return false;
  }
  // skip led selection
  m_ledSelected = true;
  clearDemo();
  DEBUG_LOG("Entering Editor Connection");
  return true;
}
References clearDemo(), DEBUG_LOG, Menu::init(), and Menu::m_ledSelected.
leaveMenu()
void EditorConnection::leaveMenu (bool doSave = false) [override], [virtual]
Reimplemented from Menu.
Definition at line 218 of file EditorConnection.cpp.
{
  m_engine.serial().write(EDITOR_VERB_GOODBYE);
  Menu::leaveMenu(true);
}
References EDITOR_VERB_GOODBYE, Menu::leaveMenu(), Menu::m_engine, VortexEngine::serial(), and SerialComs::write().
Referenced by onLongClick().
onLongClick()
void EditorConnection::onLongClick () [override], [virtual]
Reimplemented from Menu.
Definition at line 213 of file EditorConnection.cpp.
{
  leaveMenu(true);
}
References leaveMenu().
onShortClick()
void EditorConnection::onShortClick () [override], [virtual]
Reimplemented from Menu.
Definition at line 205 of file EditorConnection.cpp.
{
  // reset, this won't actually disconnect the com port
  m_state = STATE_DISCONNECTED;
  // clear the demo
  clearDemo();
}
References clearDemo(), m_state, and STATE_DISCONNECTED.
receiveData()
void EditorConnection::receiveData () [private]
Definition at line 242 of file EditorConnection.cpp.
{
  // read more data into the receive buffer
  m_engine.serial().read(m_receiveBuffer);
}
References Menu::m_engine, m_receiveBuffer, SerialComs::read(), and VortexEngine::serial().
Referenced by run().
receiveDemoMode()
bool EditorConnection::receiveDemoMode () [private]
Definition at line 287 of file EditorConnection.cpp.
{
  // need at least the buffer size first
  uint32_t size = 0;
  if (m_receiveBuffer.size() < sizeof(size)) {
    // wait, not enough data available yet
    return false;
  }
  // grab the size out of the start
  m_receiveBuffer.resetUnserializer();
  size = m_receiveBuffer.peek32();
  if (m_receiveBuffer.size() < (size + sizeof(size))) {
    // don't unserialize yet, not ready
    return false;
  }
  // okay unserialize now, first unserialize the size
  if (!m_receiveBuffer.unserialize32(&size)) {
    return false;
  }
  // create a new ByteStream that will hold the full buffer of data
  ByteStream buf(m_receiveBuffer.rawSize());
  // then copy everything from the receive buffer into the rawdata
  // which is going to overwrite the crc/size/flags of the ByteStream
  memcpy(buf.rawData(), m_receiveBuffer.data() + sizeof(size),
    m_receiveBuffer.size() - sizeof(size));
  // clear the receive buffer
  m_receiveBuffer.clear();
  // unserialize the mode into the demo mode
  if (!m_previewMode.loadFromBuffer(buf)) {
    // failure
  }
  return true;
}
References ByteStream::clear(), ByteStream::data(), Mode::loadFromBuffer(), Menu::m_previewMode, m_receiveBuffer, ByteStream::peek32(), ByteStream::rawData(), ByteStream::rawSize(), ByteStream::resetUnserializer(), ByteStream::size(), and ByteStream::unserialize32().
Referenced by run().
receiveMessage()
bool EditorConnection::receiveMessage (const char * message) [private]
Definition at line 42 of file EditorConnection.cpp.
{
  size_t len = strlen(message);
  uint8_t byte = 0;
  // wait for the editor to ack the idle
  if (m_receiveBuffer.size() < len) {
    return false;
  }
  if (memcmp(m_receiveBuffer.frontUnserializer(), message, len) != 0) {
    return false;
  }
  for (size_t i = 0; i < len; ++i) {
    if (!m_receiveBuffer.unserialize8(&byte)) {
      return false;
    }
  }
  // if everything was read out, reset
  if (m_receiveBuffer.unserializerAtEnd()) {
    m_receiveBuffer.clear();
  }
  return true;
}
References ByteStream::clear(), ByteStream::frontUnserializer(), m_receiveBuffer, ByteStream::size(), ByteStream::unserialize8(), and ByteStream::unserializerAtEnd().
Referenced by handleCommand(), and run().
receiveModes()
bool EditorConnection::receiveModes () [private]
Definition at line 255 of file EditorConnection.cpp.
{
  // need at least the buffer size first
  uint32_t size = 0;
  if (m_receiveBuffer.size() < sizeof(size)) {
    // wait, not enough data available yet
    return false;
  }
  // grab the size out of the start
  m_receiveBuffer.resetUnserializer();
  size = m_receiveBuffer.peek32();
  if (m_receiveBuffer.size() < (size + sizeof(size))) {
    // don't unserialize yet, not ready
    return false;
  }
  // okay unserialize now, first unserialize the size
  if (!m_receiveBuffer.unserialize32(&size)) {
    return false;
  }
  // create a new ByteStream that will hold the full buffer of data
  ByteStream buf(m_receiveBuffer.rawSize());
  // then copy everything from the receive buffer into the rawdata
  // which is going to overwrite the crc/size/flags of the ByteStream
  memcpy(buf.rawData(), m_receiveBuffer.data() + sizeof(size),
    m_receiveBuffer.size() - sizeof(size));
  // clear the receive buffer
  m_receiveBuffer.clear();
  m_engine.modes().loadFromBuffer(buf);
  m_engine.modes().saveStorage();
  return true;
}
References ByteStream::clear(), ByteStream::data(), Modes::loadFromBuffer(), Menu::m_engine, m_receiveBuffer, VortexEngine::modes(), ByteStream::peek32(), ByteStream::rawData(), ByteStream::rawSize(), ByteStream::resetUnserializer(), Modes::saveStorage(), ByteStream::size(), and ByteStream::unserialize32().
Referenced by run().
run()
Menu::MenuAction EditorConnection::run () [override], [virtual]
Reimplemented from Menu.
Definition at line 73 of file EditorConnection.cpp.
{
  MenuAction result = Menu::run();
  if (result != MENU_CONTINUE) {
    return result;
  }
  // TODO: auto leave the editor menu when unplugged
  // show the editor
  showEditor();
  // receive any data from serial into the receive buffer
  receiveData();
  // operate on the state of the editor connection
  switch (m_state) {
  case STATE_DISCONNECTED:
    // not connected yet so check for connections
    if (!m_engine.serial().isConnected()) {
      if (!m_engine.serial().checkSerial()) {
        // no connection found just continue waiting
        break;
      }
    }
    // a connection was found, say hello
    m_state = STATE_GREETING;
    break;
  case STATE_GREETING:
    m_receiveBuffer.clear();
    // send the hello greeting with our version number and build time
    m_engine.serial().write(EDITOR_VERB_GREETING);
    m_state = STATE_IDLE;
    break;
  case STATE_IDLE:
    // parse the receive buffer for any commands from the editor
    handleCommand();
    break;
  case STATE_PULL_MODES:
    // editor requested pull modes, send the modes
    sendModes();
    m_state = STATE_PULL_MODES_SEND;
    break;
  case STATE_PULL_MODES_SEND:
    // recive the send modes ack from the editor
    if (receiveMessage(EDITOR_VERB_PULL_MODES_DONE)) {
      m_state = STATE_PULL_MODES_DONE;
    }
    break;
  case STATE_PULL_MODES_DONE:
    m_receiveBuffer.clear();
    // send our acknowledgement that the modes were sent
    m_engine.serial().write(EDITOR_VERB_PULL_MODES_ACK);
    // go idle
    m_state = STATE_IDLE;
    break;
  case STATE_PUSH_MODES:
    // editor requested to push modes, clear first and reset first
    m_receiveBuffer.clear();
    // now say we are ready
    m_engine.serial().write(EDITOR_VERB_READY);
    // move to receiving
    m_state = STATE_PUSH_MODES_RECEIVE;
    break;
  case STATE_PUSH_MODES_RECEIVE:
    // receive the modes into the receive buffer
    if (receiveModes()) {
      // success modes were received send the done
      m_state = STATE_PUSH_MODES_DONE;
    }
    break;
  case STATE_PUSH_MODES_DONE:
    // say we are done
    m_receiveBuffer.clear();
    m_engine.serial().write(EDITOR_VERB_PUSH_MODES_ACK);
    m_state = STATE_IDLE;
    break;
  case STATE_DEMO_MODE:
    // editor requested to push modes, clear first and reset first
    m_receiveBuffer.clear();
    // now say we are ready
    m_engine.serial().write(EDITOR_VERB_READY);
    // move to receiving
    m_state = STATE_DEMO_MODE_RECEIVE;
    break;
  case STATE_DEMO_MODE_RECEIVE:
    // receive the modes into the receive buffer
    if (receiveDemoMode()) {
      // success modes were received send the done
      m_state = STATE_DEMO_MODE_DONE;
    }
    break;
  case STATE_DEMO_MODE_DONE:
    // say we are done
    m_receiveBuffer.clear();
    m_engine.serial().write(EDITOR_VERB_DEMO_MODE_ACK);
    m_state = STATE_IDLE;
    break;
  case STATE_CLEAR_DEMO:
    clearDemo();
    m_receiveBuffer.clear();
    m_engine.serial().write(EDITOR_VERB_CLEAR_DEMO_ACK);
    m_state = STATE_IDLE;
    break;
  case STATE_TRANSMIT_MODE_VL:
#if VL_ENABLE_SENDER == 1
    // if still sending and the send command indicated more data
    if (m_engine.vlSender().isSending() && m_engine.vlSender().send()) {
      // then continue sending
      break;
    }
#endif
    // othewrise, done, switch to the transmit done state
    m_state = STATE_TRANSMIT_MODE_VL_DONE;
    break;
  case STATE_TRANSMIT_MODE_VL_DONE:
    // done transmitting
    m_receiveBuffer.clear();
    m_engine.serial().write(EDITOR_VERB_TRANSMIT_VL_ACK);
    m_state = STATE_IDLE;
    break;
  }
  return MENU_CONTINUE;
}
References SerialComs::checkSerial(), ByteStream::clear(), clearDemo(), EDITOR_VERB_CLEAR_DEMO_ACK, EDITOR_VERB_DEMO_MODE_ACK, EDITOR_VERB_GREETING, EDITOR_VERB_PULL_MODES_ACK, EDITOR_VERB_PULL_MODES_DONE, EDITOR_VERB_PUSH_MODES_ACK, EDITOR_VERB_READY, EDITOR_VERB_TRANSMIT_VL_ACK, handleCommand(), SerialComs::isConnected(), VLSender::isSending(), Menu::m_engine, m_receiveBuffer, m_state, Menu::MENU_CONTINUE, receiveData(), receiveDemoMode(), receiveMessage(), receiveModes(), Menu::run(), VLSender::send(), sendModes(), VortexEngine::serial(), showEditor(), STATE_CLEAR_DEMO, STATE_DEMO_MODE, STATE_DEMO_MODE_DONE, STATE_DEMO_MODE_RECEIVE, STATE_DISCONNECTED, STATE_GREETING, STATE_IDLE, STATE_PULL_MODES, STATE_PULL_MODES_DONE, STATE_PULL_MODES_SEND, STATE_PUSH_MODES, STATE_PUSH_MODES_DONE, STATE_PUSH_MODES_RECEIVE, STATE_TRANSMIT_MODE_VL, STATE_TRANSMIT_MODE_VL_DONE, VortexEngine::vlSender(), and SerialComs::write().
sendCurModeVL()
void EditorConnection::sendCurModeVL ()
Definition at line 194 of file EditorConnection.cpp.
{
#if VL_ENABLE_SENDER == 1
  // immediately load the mode and send it now
  m_engine.vlSender().loadMode(&m_previewMode);
  m_engine.vlSender().send();
#endif
  m_state = STATE_TRANSMIT_MODE_VL;
}
References VLSender::loadMode(), Menu::m_engine, Menu::m_previewMode, m_state, VLSender::send(), STATE_TRANSMIT_MODE_VL, and VortexEngine::vlSender().
Referenced by handleCommand().
sendModes()
void EditorConnection::sendModes () [private]
Definition at line 248 of file EditorConnection.cpp.
{
  ByteStream modesBuffer;
  m_engine.modes().saveToBuffer(modesBuffer);
  m_engine.serial().write(modesBuffer);
}
References Menu::m_engine, VortexEngine::modes(), Modes::saveToBuffer(), VortexEngine::serial(), and SerialComs::write().
Referenced by run().
showEditor()
void EditorConnection::showEditor () [private]
Definition at line 224 of file EditorConnection.cpp.
{
  switch (m_state) {
  case STATE_DISCONNECTED:
    m_engine.leds().clearAll();
    m_engine.leds().blinkAll(250, 150, RGB_WHITE0);
    break;
  case STATE_IDLE:
    m_previewMode.play();
    break;
  default:
    // do nothing!
    // Note if you clear the leds while selecting color
    // it may make the color selection choppy
    break;
  }
}
References Leds::blinkAll(), Leds::clearAll(), VortexEngine::leds(), Menu::m_engine, Menu::m_previewMode, m_state, Mode::play(), RGB_WHITE0, STATE_DISCONNECTED, and STATE_IDLE.
Referenced by run().
Member Data Documentation
m_receiveBuffer
ByteStream EditorConnection::m_receiveBuffer [private]
Definition at line 74 of file EditorConnection.h.
Referenced by receiveData(), receiveDemoMode(), receiveMessage(), receiveModes(), and run().
m_state
EditorConnectionState EditorConnection::m_state [private]
Definition at line 72 of file EditorConnection.h.
Referenced by handleCommand(), onShortClick(), run(), sendCurModeVL(), and showEditor().
The documentation for this class was generated from the following files:
VortexEngine/src/Menus/MenuList/EditorConnection.h
VortexEngine/src/Menus/MenuList/EditorConnection.cpp