VortexEngine Class Reference
#include <VortexEngine.h>
Public Member Functions
VortexEngine (Vortex &vortexLib)
~VortexEngine ()
bool init ()
void cleanup ()
void tick ()
void runMainLogic ()
bool serializeVersion (ByteStream &stream)
bool checkVersion (uint8_t major, uint8_t minor)
Mode * curMode ()
void enterSleep (bool save=true)
void wakeup (bool reset=true)
void setAutoCycle (bool enabled)
Vortex & vortexLib ()
SerialComs & serial ()
Time & time ()
Storage & storage ()
IRReceiver & irReceiver ()
IRSender & irSender ()
VLReceiver & vlReceiver ()
VLSender & vlSender ()
Leds & leds ()
Buttons & buttons ()
Button & button (uint8_t index=0)
Menus & menus ()
Modes & modes ()
PatternBuilder & patternBuilder ()
Private Attributes
Vortex & m_vortexLib
VortexEngine & m_engine
SerialComs m_serial
Time m_time
Storage m_storage
IRReceiver m_irReceiver
IRSender m_irSender
VLReceiver m_vlReceiver
VLSender m_vlSender
Leds m_leds
Buttons m_buttons
Menus m_menus
Modes m_modes
PatternBuilder m_patternBuilder
volatile bool m_sleeping
bool m_autoCycle
Detailed Description
Definition at line 27 of file VortexEngine.h.
Constructor & Destructor Documentation
VortexEngine()
VortexEngine::VortexEngine (Vortex & vortexLib)
Definition at line 8 of file VortexEngine.cpp.
                                            :
  m_vortexLib(vortexLib),
  m_engine(*this),
  m_serial(m_engine),
  m_time(m_engine),
  m_storage(m_engine),
  m_irReceiver(m_engine),
  m_irSender(m_engine),
  m_vlReceiver(m_engine),
  m_vlSender(m_engine),
  m_leds(m_engine),
  m_buttons(m_engine),
  m_menus(m_engine),
  m_modes(m_engine),
  m_patternBuilder(m_engine),
  m_sleeping(false),
  m_autoCycle(false)
{
}
 VortexEngine()
VortexEngine::~VortexEngine ()
Definition at line 28 of file VortexEngine.cpp.
{
}
Member Function Documentation
button()
Button& VortexEngine::button (uint8_t index = 0) [inline]
Definition at line 80 of file VortexEngine.h.
{ return m_buttons.button(index); }
References Buttons::button(), and m_buttons.
Referenced by Menus::checkOpen(), ColorSelect::onLongClick(), FactoryReset::onLongClick(), PatternSelect::onShortClick(), Modes::play(), Menu::run(), Randomizer::run(), Menus::runCurMenu(), runMainLogic(), Menus::runMenuSelection(), Menu::showExit(), FactoryReset::showReset(), Menus::showSelection(), ColorSelect::showSlotSelection(), and tick().
buttons()
Buttons& VortexEngine::buttons () [inline]
Definition at line 79 of file VortexEngine.h.
{ return m_buttons; }
References m_buttons.
checkVersion()
bool VortexEngine::checkVersion (uint8_t major, uint8_t minor)
Definition at line 201 of file VortexEngine.cpp.
{
  if (major != VORTEX_VERSION_MAJOR) {
    return false;
  }
  // minor version doesn't matter
  return true;
}
References VORTEX_VERSION_MAJOR.
Referenced by Mode::loadFromBuffer(), and Modes::unserializeSaveHeader().
cleanup()
void VortexEngine::cleanup ()
Definition at line 99 of file VortexEngine.cpp.
{
  // cleanup in reverse order
  // NOTE: the embedded doesn't actually cleanup,
  // but the test frameworks do
#ifdef VORTEX_LIB
  m_patternBuilder.cleanup();
  m_modes.cleanup();
  m_menus.cleanup();
  m_buttons.cleanup();
  m_leds.cleanup();
  m_vlSender.cleanup();
  m_vlReceiver.cleanup();
  m_irSender.cleanup();
  m_irReceiver.cleanup();
  m_storage.cleanup();
  m_time.cleanup();
  m_serial.cleanup();
#endif
}
References Buttons::cleanup(), Leds::cleanup(), Menus::cleanup(), Modes::cleanup(), PatternBuilder::cleanup(), SerialComs::cleanup(), Storage::cleanup(), Time::cleanup(), IRReceiver::cleanup(), IRSender::cleanup(), VLReceiver::cleanup(), VLSender::cleanup(), m_buttons, m_irReceiver, m_irSender, m_leds, m_menus, m_modes, m_patternBuilder, m_serial, m_storage, m_time, m_vlReceiver, and m_vlSender.
Referenced by wakeup().
curMode()
Mode * VortexEngine::curMode ()
Definition at line 210 of file VortexEngine.cpp.
{
#ifdef VORTEX_LIB
  return m_modes.curMode();
#else
  // don't need this outside vortex lib
  return nullptr;
#endif
}
References Modes::curMode(), and m_modes.
enterSleep()
void VortexEngine::enterSleep (bool save = true)
Definition at line 232 of file VortexEngine.cpp.
{
  DEBUG_LOG("Sleeping");
  if (save) {
    // update the startup mode when going to sleep
    m_modes.setStartupMode(m_modes.curModeIndex());
    // save anything that hasn't been saved
    m_modes.saveStorage();
  }
  // clear all the leds
  m_leds.clearAll();
  m_leds.update();
  // enable the sleep bool
  m_sleeping = true;
}
References Leds::clearAll(), Modes::curModeIndex(), DEBUG_LOG, m_leds, m_modes, m_sleeping, Modes::saveStorage(), Modes::setStartupMode(), and Leds::update().
init()
bool VortexEngine::init ()
Definition at line 32 of file VortexEngine.cpp.
{
  // all of the global controllers
  if (!m_serial.init()) {
    DEBUG_LOG("Serial failed to initialize");
    return false;
  }
  if (!m_time.init()) {
    DEBUG_LOG("Time failed to initialize");
    return false;
  }
  if (!m_storage.init()) {
    DEBUG_LOG("Storage failed to initialize");
    return false;
  }
  if (!m_irReceiver.init()) {
    DEBUG_LOG("IRReceiver failed to initialize");
    return false;
  }
  if (!m_irSender.init()) {
    DEBUG_LOG("IRSender failed to initialize");
    return false;
  }
  if (!m_vlReceiver.init()) {
    DEBUG_LOG("VLReceiver failed to initialize");
    return false;
  }
  if (!m_vlSender.init()) {
    DEBUG_LOG("VLSender failed to initialize");
    return false;
  }
  if (!m_leds.init()) {
    DEBUG_LOG("Leds failed to initialize");
    return false;
  }
  if (!m_buttons.init()) {
    DEBUG_LOG("Buttons failed to initialize");
    return false;
  }
  if (!m_menus.init()) {
    DEBUG_LOG("Menus failed to initialize");
    return false;
  }
  if (!m_modes.init()) {
    DEBUG_LOG("Settings failed to initialize");
    return false;
  }
  if (!m_patternBuilder.init()) {
    DEBUG_LOG("Pattern builder failed to initialize");
    return false;
  }
#if COMPRESSION_TEST == 1
  compressionTest();
#endif
#if SERIALIZATION_TEST == 1
  serializationTest();
#endif
#if TIMER_TEST == 1
  timerTest();
#endif
  return true;
}
References DEBUG_LOG, Buttons::init(), Leds::init(), Menus::init(), Modes::init(), PatternBuilder::init(), SerialComs::init(), Storage::init(), Time::init(), IRReceiver::init(), IRSender::init(), VLReceiver::init(), VLSender::init(), m_buttons, m_irReceiver, m_irSender, m_leds, m_menus, m_modes, m_patternBuilder, m_serial, m_storage, m_time, m_vlReceiver, and m_vlSender.
Referenced by wakeup().
irReceiver()
IRReceiver& VortexEngine::irReceiver () [inline]
Definition at line 74 of file VortexEngine.h.
{ return m_irReceiver; }
References m_irReceiver.
Referenced by ModeSharing::beginReceivingIR(), ModeSharing::onShortClick(), ModeSharing::receiveModeIR(), and ModeSharing::showReceiveMode().
irSender()
IRSender& VortexEngine::irSender () [inline]
Definition at line 75 of file VortexEngine.h.
{ return m_irSender; }
References m_irSender.
Referenced by ModeSharing::beginSendingIR(), and ModeSharing::continueSendingIR().
leds()
Leds& VortexEngine::leds () [inline]
Definition at line 78 of file VortexEngine.h.
{ return m_leds; }
References m_leds.
Referenced by BasicPattern::beginDash(), BasicPattern::beginGap(), BlinkStepPattern::blinkOff(), DripMorphPattern::blinkOff(), LighthousePattern::blinkOff(), MeteorPattern::blinkOff(), DripMorphPattern::blinkOn(), BouncePattern::blinkOn(), CrossDopsPattern::blinkOn(), DoubleStrobePattern::blinkOn(), DripPattern::blinkOn(), FillPattern::blinkOn(), LighthousePattern::blinkOn(), MeteorPattern::blinkOn(), SnowballPattern::blinkOn(), SparkleTracePattern::blinkOn(), TheaterChasePattern::blinkOn(), VortexPattern::blinkOn(), VortexWipePattern::blinkOn(), WarpPattern::blinkOn(), WarpWormPattern::blinkOn(), Modes::clearModes(), Menus::closeCurMenu(), ZigzagPattern::Snake::draw(), ZigzagPattern::Snake::drawSnake(), Mode::getSingleLedMap(), GlobalBrightness::init(), Menu::nextBulbSelection(), BasicPattern::onBlinkOff(), BasicPattern::onBlinkOn(), BlendPattern::onBlinkOn(), ColorSelect::onLedSelected(), PatternSelect::onLedSelected(), FactoryReset::onLongClick(), GlobalBrightness::onLongClick(), PatternSelect::onLongClick(), ModeSharing::onShortClick(), PatternSelect::onShortClick(), Menus::openMenu(), Menus::openMenuSelection(), Mode::play(), Modes::play(), HueShiftPattern::play(), PulsishPattern::play(), SequencedPattern::playSequenceStep(), SparkleTracePattern::poststep(), ColorSelect::run(), Randomizer::run(), Menus::runMenuSelection(), Modes::serializeSaveHeader(), ColorsetMap::setColorsetAt(), Modes::setCurMode(), PatternMap::setPatternAt(), GlobalBrightness::showBrightnessSelection(), Menu::showBulbSelection(), EditorConnection::showEditor(), Menu::showExit(), ColorSelect::showFullSet(), Randomizer::showRandomizationSelect(), ModeSharing::showReceiveMode(), FactoryReset::showReset(), ColorSelect::showSelection(), Menus::showSelection(), ModeSharing::showSendModeIR(), ModeSharing::showSendModeVL(), ColorSelect::showSlotSelection(), and Modes::unserializeSaveHeader().
menus()
Menus& VortexEngine::menus () [inline]
Definition at line 81 of file VortexEngine.h.
{ return m_menus; }
References m_menus.
Referenced by ColorSelect::run(), GlobalBrightness::run(), PatternSelect::run(), Randomizer::run(), Menu::showBulbSelection(), and Randomizer::showRandomizationSelect().
modes()
Modes& VortexEngine::modes () [inline]
Definition at line 82 of file VortexEngine.h.
{ return m_modes; }
References m_modes.
Referenced by ModeSharing::beginSendingIR(), ModeSharing::beginSendingVL(), Menu::init(), ColorSelect::init(), FactoryReset::init(), Randomizer::init(), Menu::leaveMenu(), Menu::nextBulbSelection(), ColorSelect::onLedSelected(), ColorSelect::onLongClick(), FactoryReset::onLongClick(), ModeSharing::onLongClick(), PatternSelect::onLongClick(), Randomizer::onLongClick(), ModeSharing::receiveModeIR(), EditorConnection::receiveModes(), Menus::runMenuSelection(), and EditorConnection::sendModes().
patternBuilder()
PatternBuilder& VortexEngine::patternBuilder () [inline]
Definition at line 83 of file VortexEngine.h.
{ return m_patternBuilder; }
References m_patternBuilder.
Referenced by Mode::operator=(), SequencedPattern::playSequenceStep(), Pattern::serialize(), CompoundPattern::setEvensOdds(), Mode::setPattern(), CompoundPattern::setPatternAt(), Mode::unserialize(), and Pattern::unserialize().
runMainLogic()
void VortexEngine::runMainLogic ()
Definition at line 161 of file VortexEngine.cpp.
{
  // the current tick
  uint32_t now = m_time.getCurtime();
  // if the menus are open and running then just return
  if (m_menus.run()) {
    return;
  }
  // check if we should enter the menu
  if (m_engine.button().isPressed() && m_engine.button().holdDuration() > MENU_TRIGGER_THRESHOLD_TICKS) {
    DEBUG_LOG("Entering Menu Selection...");
    m_menus.openMenuSelection();
    return;
  }
  // toggle auto cycle mode with many clicks at main modes
  if (m_engine.button().onConsecutivePresses(AUTO_CYCLE_MODES_CLICKS)) {
    m_autoCycle = !m_autoCycle;
    m_leds.holdAll(m_autoCycle ? RGB_GREEN : RGB_RED);
  }
  // if auto cycle is enabled and the last switch was more than the delay ago
  if (m_autoCycle && (m_modes.lastSwitchTime() + AUTO_RANDOM_DELAY < now)) {
    // then switch to the next mode automatically
    m_modes.nextModeSkipEmpty();
  }
  // otherwise just play the modes
  m_modes.play();
}
References AUTO_CYCLE_MODES_CLICKS, AUTO_RANDOM_DELAY, button(), DEBUG_LOG, Time::getCurtime(), Leds::holdAll(), Button::holdDuration(), Button::isPressed(), Modes::lastSwitchTime(), m_autoCycle, m_engine, m_leds, m_menus, m_modes, m_time, MENU_TRIGGER_THRESHOLD_TICKS, Modes::nextModeSkipEmpty(), Button::onConsecutivePresses(), Menus::openMenuSelection(), Modes::play(), RGB_GREEN, RGB_RED, and Menus::run().
Referenced by tick().
serial()
SerialComs& VortexEngine::serial () [inline]
Definition at line 71 of file VortexEngine.h.
{ return m_serial; }
References m_serial.
Referenced by EditorConnection::leaveMenu(), EditorConnection::receiveData(), EditorConnection::run(), and EditorConnection::sendModes().
serializeVersion()
bool VortexEngine::serializeVersion (ByteStream & stream)
Definition at line 194 of file VortexEngine.cpp.
{
  // serialize the vortex version
  return stream.serialize((uint8_t)VORTEX_VERSION_MAJOR) &&
         stream.serialize((uint8_t)VORTEX_VERSION_MINOR);
}
References ByteStream::serialize(), VORTEX_VERSION_MAJOR, and VORTEX_VERSION_MINOR.
Referenced by Mode::saveToBuffer(), and Modes::serializeSaveHeader().
setAutoCycle()
void VortexEngine::setAutoCycle (bool enabled) [inline]
Definition at line 65 of file VortexEngine.h.
{ m_autoCycle = enabled; }
References m_autoCycle.
Referenced by FactoryReset::onLongClick().
storage()
Storage& VortexEngine::storage () [inline]
Definition at line 73 of file VortexEngine.h.
{ return m_storage; }
References m_storage.
Referenced by Modes::loadStorage(), and Modes::saveStorage().
tick()
void VortexEngine::tick ()
Definition at line 120 of file VortexEngine.cpp.
{
#ifdef VORTEX_LIB
  if (m_sleeping) {
    // update the buttons to check for wake
    m_buttons.update();
    // several fast clicks will unlock the device
    if (m_modes.locked() && m_engine.button().onConsecutivePresses(DEVICE_LOCK_CLICKS - 1)) {
      // turn off the lock flag and save it to disk
      m_modes.setLocked(false);
    }
    // check for any kind of press to wakeup
    if (m_engine.button().check() || m_engine.button().onRelease() || !m_vortexLib.sleepEnabled()) {
      wakeup();
    }
    return;
  }
#endif
  // handle any fatal errors that may have occurred
  // but only if the error blinker is enabled
#if VORTEX_ERROR_BLINK == 1
  if (getError() != ERROR_NONE) {
    // just blink the error and don't run anything
    blinkError();
    return;
  }
#endif
  // tick the current time counter forward
  m_time.tickClock();
  // poll the button(s) and update the button object states
  m_buttons.update();
  // run the main logic for the engine
  runMainLogic();
  // update the leds
  m_leds.update();
}
References button(), Button::check(), DEVICE_LOCK_CLICKS, ERROR_NONE, Modes::locked(), m_buttons, m_engine, m_leds, m_modes, m_sleeping, m_time, m_vortexLib, Button::onConsecutivePresses(), Button::onRelease(), runMainLogic(), Modes::setLocked(), Time::tickClock(), Buttons::update(), Leds::update(), and wakeup().
time()
Time& VortexEngine::time () [inline]
Definition at line 72 of file VortexEngine.h.
{ return m_time; }
References m_time.
Referenced by Timer::alarm(), IRSender::beginSend(), VLSender::beginSend(), Leds::blinkAll(), Leds::blinkIndex(), Leds::blinkMap(), Leds::blinkPair(), Leds::blinkPairs(), Leds::blinkRange(), SerialComs::checkSerial(), Timer::getStartTime(), Leds::holdAll(), Timer::onEnd(), Timer::onStart(), Menus::openMenuSelection(), ModeSharing::receiveModeIR(), IRReceiver::recvPCIHandler(), VLReceiver::recvPCIHandler(), Randomizer::run(), Menus::runMenuSelection(), IRSender::send(), VLSender::send(), IRSender::sendMark(), VLSender::sendMark(), IRSender::sendSpace(), VLSender::sendSpace(), Modes::setCurMode(), Timer::setStartTime(), Menu::showBulbSelection(), ColorSelect::showFullSet(), ColorSelect::showSelection(), Timer::start(), and Button::update().
vlReceiver()
VLReceiver& VortexEngine::vlReceiver () [inline]
Definition at line 76 of file VortexEngine.h.
{ return m_vlReceiver; }
References m_vlReceiver.
vlSender()
VLSender& VortexEngine::vlSender () [inline]
Definition at line 77 of file VortexEngine.h.
{ return m_vlSender; }
References m_vlSender.
Referenced by ModeSharing::beginSendingVL(), and ModeSharing::continueSendingVL().
vortexLib()
Vortex& VortexEngine::vortexLib () [inline]
Definition at line 68 of file VortexEngine.h.
{ return m_vortexLib; }
References m_vortexLib.
Referenced by Button::check(), SerialComs::checkSerial(), SerialComs::dataReady(), Leds::init(), Storage::init(), SerialComs::read(), Storage::read(), IRSender::sendMark(), VLSender::sendMark(), IRSender::sendSpace(), VLSender::sendSpace(), Leds::setLedCount(), Buttons::update(), Leds::update(), SerialComs::write(), and Storage::write().
wakeup()
void VortexEngine::wakeup (bool reset = true)
Definition at line 248 of file VortexEngine.cpp.
{
  DEBUG_LOG("Waking up");
  m_sleeping = false;
  // need to fake the reset in vortexlib, lol this works I guess
  if (reset) {
    cleanup();
    init();
  }
}
References cleanup(), DEBUG_LOG, init(), and m_sleeping.
Referenced by tick().
Member Data Documentation
m_autoCycle
bool VortexEngine::m_autoCycle [private]
Definition at line 110 of file VortexEngine.h.
Referenced by runMainLogic(), and setAutoCycle().
m_buttons
Buttons VortexEngine::m_buttons [private]
Definition at line 101 of file VortexEngine.h.
Referenced by button(), buttons(), cleanup(), init(), and tick().
m_engine
VortexEngine& VortexEngine::m_engine [private]
Definition at line 90 of file VortexEngine.h.
Referenced by runMainLogic(), and tick().
m_irReceiver
IRReceiver VortexEngine::m_irReceiver [private]
Definition at line 96 of file VortexEngine.h.
Referenced by cleanup(), init(), and irReceiver().
m_irSender
IRSender VortexEngine::m_irSender [private]
Definition at line 97 of file VortexEngine.h.
Referenced by cleanup(), init(), and irSender().
m_leds
Leds VortexEngine::m_leds [private]
Definition at line 100 of file VortexEngine.h.
Referenced by cleanup(), enterSleep(), init(), leds(), runMainLogic(), and tick().
m_menus
Menus VortexEngine::m_menus [private]
Definition at line 102 of file VortexEngine.h.
Referenced by cleanup(), init(), menus(), and runMainLogic().
m_modes
Modes VortexEngine::m_modes [private]
Definition at line 103 of file VortexEngine.h.
Referenced by cleanup(), curMode(), enterSleep(), init(), modes(), runMainLogic(), and tick().
m_patternBuilder
PatternBuilder VortexEngine::m_patternBuilder [private]
Definition at line 104 of file VortexEngine.h.
Referenced by cleanup(), init(), and patternBuilder().
m_serial
SerialComs VortexEngine::m_serial [private]
Definition at line 93 of file VortexEngine.h.
Referenced by cleanup(), init(), and serial().
m_sleeping
volatile bool VortexEngine::m_sleeping [private]
Definition at line 107 of file VortexEngine.h.
Referenced by enterSleep(), tick(), and wakeup().
m_storage
Storage VortexEngine::m_storage [private]
Definition at line 95 of file VortexEngine.h.
Referenced by cleanup(), init(), and storage().
m_time
Time VortexEngine::m_time [private]
Definition at line 94 of file VortexEngine.h.
Referenced by cleanup(), init(), runMainLogic(), tick(), and time().
m_vlReceiver
VLReceiver VortexEngine::m_vlReceiver [private]
Definition at line 98 of file VortexEngine.h.
Referenced by cleanup(), init(), and vlReceiver().
m_vlSender
VLSender VortexEngine::m_vlSender [private]
Definition at line 99 of file VortexEngine.h.
Referenced by cleanup(), init(), and vlSender().
m_vortexLib
Vortex& VortexEngine::m_vortexLib [private]
Definition at line 87 of file VortexEngine.h.
Referenced by tick(), and vortexLib().
The documentation for this class was generated from the following files:
VortexEngine/src/VortexEngine.h
VortexEngine/src/VortexEngine.cpp