DripMorphPattern Class Reference
#include <DripMorphPattern.h>
Public Member Functions
DripMorphPattern (VortexEngine &engine, const PatternArgs &args)
virtual ~DripMorphPattern ()
virtual void init () override
virtual void play () override
Protected Member Functions
virtual void blinkOn ()
virtual void blinkOff ()
Private Attributes
uint8_t m_blinkOnDuration
uint8_t m_blinkOffDuration
Timer m_blinkTimer
uint8_t m_speed
HSVColor m_cur
HSVColor m_next
Additional Inherited Members
Detailed Description
Definition at line 9 of file DripMorphPattern.h.
Constructor & Destructor Documentation
DripMorphPattern()
DripMorphPattern::DripMorphPattern (VortexEngine & engine, const PatternArgs & args)
Definition at line 9 of file DripMorphPattern.cpp.
                                                                                :
  MultiLedPattern(engine, args),
  m_blinkOnDuration(0),
  m_blinkOffDuration(0),
  m_blinkTimer(engine),
  m_speed(0),
  m_cur(),
  m_next()
{
  m_patternID = PATTERN_DRIPMORPH;
  REGISTER_ARG(m_blinkOnDuration);
  REGISTER_ARG(m_blinkOffDuration);
  REGISTER_ARG(m_speed);
  setArgs(args);
}
References m_blinkOffDuration, m_blinkOnDuration, Pattern::m_patternID, m_speed, PATTERN_DRIPMORPH, REGISTER_ARG, and Pattern::setArgs().
 DripMorphPattern()
DripMorphPattern::~DripMorphPattern () [virtual]
Definition at line 25 of file DripMorphPattern.cpp.
{
}
Member Function Documentation
blinkOff()
void DripMorphPattern::blinkOff () [protected], [virtual]
Definition at line 83 of file DripMorphPattern.cpp.
{
  m_engine.leds().clearAll();
}
References Leds::clearAll(), VortexEngine::leds(), and Pattern::m_engine.
Referenced by play().
blinkOn()
void DripMorphPattern::blinkOn () [protected], [virtual]
Definition at line 60 of file DripMorphPattern.cpp.
{
  // if the current hue has reached the next hue
  if (m_cur.hue == m_next.hue) {
    // copy over the sat/val
    m_cur = m_next;
    // get the next color and convert to hsv
    m_next = m_colorset.getNext();
  }
  // check which direction is closer for the next hue
  // tbh idk really how this even works anymore but it does
  int sign = ((((m_next.hue + 255) - m_cur.hue) % 256) <= 128) ? 1 : -1;
  // move hue in the direction of next hue at chosen speed
  // NOTE: if the speed isn't a multiple of the hue values then
  // it will cause oscillation around the target hue
  // because it will never reach the target hue and
  // always over/under shoot
  m_cur.hue += m_speed * sign;
  // set the target led with the current HSV color
  m_engine.leds().setAllEvens(m_cur);
  m_engine.leds().setAllOdds(m_colorset.cur());
}
References Colorset::cur(), Colorset::getNext(), HSVColor::hue, VortexEngine::leds(), Pattern::m_colorset, m_cur, Pattern::m_engine, m_next, m_speed, Leds::setAllEvens(), and Leds::setAllOdds().
Referenced by play().
init()
void DripMorphPattern::init () [override], [virtual]
Reimplemented from MultiLedPattern.
Definition at line 29 of file DripMorphPattern.cpp.
{
  MultiLedPattern::init();
  // reset the blink timer entirely
  m_blinkTimer.reset();
  // dops timing
  m_blinkTimer.addAlarm(m_blinkOnDuration);
  m_blinkTimer.addAlarm(m_blinkOffDuration);
  // start the blink timer from the next frame
  m_blinkTimer.start();
  // convert current/next colors to HSV
  m_cur = m_colorset.getNext();
  m_next = m_colorset.getNext();
}
References Timer::addAlarm(), Colorset::getNext(), MultiLedPattern::init(), m_blinkOffDuration, m_blinkOnDuration, m_blinkTimer, Pattern::m_colorset, m_cur, m_next, Timer::reset(), and Timer::start().
play()
void DripMorphPattern::play () [override], [virtual]
Implements Pattern.
Definition at line 46 of file DripMorphPattern.cpp.
{
  switch (m_blinkTimer.alarm()) {
  case -1: // just break
    break;
  case 0: // turn on the leds for given mapping
    blinkOn();
    break;
  case 1: // turn off the leds
    blinkOff();
    break;
  }
}
References Timer::alarm(), blinkOff(), blinkOn(), and m_blinkTimer.
Member Data Documentation
m_blinkOffDuration
uint8_t DripMorphPattern::m_blinkOffDuration [private]
Definition at line 27 of file DripMorphPattern.h.
Referenced by DripMorphPattern(), and init().
m_blinkOnDuration
uint8_t DripMorphPattern::m_blinkOnDuration [private]
Definition at line 26 of file DripMorphPattern.h.
Referenced by DripMorphPattern(), and init().
m_blinkTimer
Timer DripMorphPattern::m_blinkTimer [private]
Definition at line 28 of file DripMorphPattern.h.
Referenced by init(), and play().
m_cur
HSVColor DripMorphPattern::m_cur [private]
Definition at line 33 of file DripMorphPattern.h.
Referenced by blinkOn(), and init().
m_next
HSVColor DripMorphPattern::m_next [private]
Definition at line 34 of file DripMorphPattern.h.
Referenced by blinkOn(), and init().
m_speed
uint8_t DripMorphPattern::m_speed [private]
Definition at line 30 of file DripMorphPattern.h.
Referenced by blinkOn(), and DripMorphPattern().
The documentation for this class was generated from the following files:
VortexEngine/src/Patterns/Multi/DripMorphPattern.h
VortexEngine/src/Patterns/Multi/DripMorphPattern.cpp