VortexPattern Class Reference
#include <VortexPattern.h>
Public Member Functions
VortexPattern (VortexEngine &engine, const PatternArgs &args)
virtual ~VortexPattern ()
virtual void init () override
Protected Member Functions
virtual void blinkOn () override
virtual void poststep () override
Private Attributes
uint8_t m_progress
Additional Inherited Members
Detailed Description
Definition at line 8 of file VortexPattern.h.
Constructor & Destructor Documentation
VortexPattern()
VortexPattern::VortexPattern (VortexEngine & engine, const PatternArgs & args)
Definition at line 13 of file VortexPattern.cpp.
                                                                          :
  BlinkStepPattern(engine, args),
  m_progress(0)
{
  m_patternID = PATTERN_VORTEXWIPE;
  setArgs(args);
}
References Pattern::m_patternID, PATTERN_VORTEXWIPE, and Pattern::setArgs().
 VortexPattern()
VortexPattern::~VortexPattern () [virtual]
Definition at line 21 of file VortexPattern.cpp.
{
}
Member Function Documentation
blinkOn()
void VortexPattern::blinkOn () [override], [protected], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 35 of file VortexPattern.cpp.
{
  // Sets an LED at opposite ends of the strip and progresses towards the center
  m_engine.leds().setIndex((LedPos)m_progress, m_colorset.peekNext());
  m_engine.leds().setIndex((LedPos)(LED_LAST - m_progress), m_colorset.peekNext());
}
References LED_LAST, VortexEngine::leds(), Pattern::m_colorset, Pattern::m_engine, m_progress, Colorset::peekNext(), and Leds::setIndex().
init()
void VortexPattern::init () [override], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 26 of file VortexPattern.cpp.
{
  BlinkStepPattern::init();
  // reset progress
  m_progress = 0;
  // start colorset at index 0 so cur() works
  m_colorset.setCurIndex(0);
}
References BlinkStepPattern::init(), Pattern::m_colorset, m_progress, and Colorset::setCurIndex().
poststep()
void VortexPattern::poststep () [override], [protected], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 42 of file VortexPattern.cpp.
{
  // step till the middle point
  m_progress = (m_progress + 1) % MIDDLE_POINT;
  // each cycle progress to the next color
  if (m_progress == 0) {
    m_colorset.getNext();
  }
}
References Colorset::getNext(), Pattern::m_colorset, m_progress, and MIDDLE_POINT.
Member Data Documentation
m_progress
uint8_t VortexPattern::m_progress [private]
Definition at line 23 of file VortexPattern.h.
Referenced by blinkOn(), init(), and poststep().
The documentation for this class was generated from the following files:
VortexEngine/src/Patterns/Multi/VortexPattern.h
VortexEngine/src/Patterns/Multi/VortexPattern.cpp