WarpPattern Class Reference
#include <WarpPattern.h>
Public Member Functions
WarpPattern (VortexEngine &engine, const PatternArgs &args)
virtual ~WarpPattern ()
virtual void init () override
Protected Member Functions
virtual void blinkOn () override
virtual void poststep () override
Private Attributes
uint8_t m_progress
Additional Inherited Members
Detailed Description
Definition at line 5 of file WarpPattern.h.
Constructor & Destructor Documentation
WarpPattern()
WarpPattern::WarpPattern (VortexEngine & engine, const PatternArgs & args)
Definition at line 10 of file WarpPattern.cpp.
                                                                      :
  BlinkStepPattern(engine, args),
  m_progress(0)
{
  m_patternID = PATTERN_WARP;
  setArgs(args);
}
References Pattern::m_patternID, PATTERN_WARP, and Pattern::setArgs().
 WarpPattern()
WarpPattern::~WarpPattern () [virtual]
Definition at line 18 of file WarpPattern.cpp.
{
}
Member Function Documentation
blinkOn()
void WarpPattern::blinkOn () [override], [protected], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 32 of file WarpPattern.cpp.
{
  m_engine.leds().setAll(m_colorset.cur());
  m_engine.leds().setPair((Pair)m_progress, m_colorset.peekNext());
}
References Colorset::cur(), VortexEngine::leds(), Pattern::m_colorset, Pattern::m_engine, m_progress, Colorset::peekNext(), Leds::setAll(), and Leds::setPair().
init()
void WarpPattern::init () [override], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 23 of file WarpPattern.cpp.
{
  BlinkStepPattern::init();
  // reset progress
  m_progress = 0;
  // start colorset at index 0 so cur() works
  m_colorset.setCurIndex(0);
}
References BlinkStepPattern::init(), Pattern::m_colorset, m_progress, and Colorset::setCurIndex().
poststep()
void WarpPattern::poststep () [override], [protected], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 38 of file WarpPattern.cpp.
{
  m_progress = (m_progress + 1) % PAIR_COUNT;
  if (m_progress == 0) {
    m_colorset.getNext();
  }
}
References Colorset::getNext(), Pattern::m_colorset, m_progress, and PAIR_COUNT.
Member Data Documentation
m_progress
uint8_t WarpPattern::m_progress [private]
Definition at line 20 of file WarpPattern.h.
Referenced by blinkOn(), init(), and poststep().
The documentation for this class was generated from the following files:
VortexEngine/src/Patterns/Multi/WarpPattern.h
VortexEngine/src/Patterns/Multi/WarpPattern.cpp