VLSender Class Reference
#include <VLSender.h>
Public Member Functions
VLSender (VortexEngine &engine)
~VLSender ()
bool init ()
void cleanup ()
bool loadMode (const Mode *targetMode)
bool send ()
bool isSending ()
uint32_t percentDone ()
Private Member Functions
void beginSend ()
void sendByte (uint8_t data)
void sendMark (uint16_t time)
void sendSpace (uint16_t time)
void initPWM ()
void startPWM ()
void stopPWM ()
Private Attributes
VortexEngine & m_engine
ByteStream m_serialBuf
BitStream m_bitStream
bool m_isSending
uint32_t m_lastSendTime
uint32_t m_size
uint8_t m_numBlocks
uint8_t m_remainder
uint32_t m_blockSize
uint32_t m_writeCounter
Detailed Description
Definition at line 14 of file VLSender.h.
Constructor & Destructor Documentation
VLSender()
VLSender::VLSender (VortexEngine & engine)
Definition at line 14 of file VLSender.cpp.
                                       :
  m_engine(engine),
  m_serialBuf(),
  m_bitStream(),
  m_isSending(false),
  m_lastSendTime(0),
  m_size(0),
  m_numBlocks(0),
  m_remainder(0),
  m_blockSize(0),
  m_writeCounter(0)
{
}
 VLSender()
VLSender::~VLSender ()
Definition at line 28 of file VLSender.cpp.
{
}
Member Function Documentation
beginSend()
void VLSender::beginSend () [private]
Definition at line 113 of file VLSender.cpp.
{
  m_isSending = true;
  DEBUG_LOGF("[%zu] Beginning send size %u (blocks: %u remainder: %u blocksize: %u)",
    m_engine.time().microseconds(), m_size, m_numBlocks, m_remainder, m_blockSize);
  // wakeup the other receiver with a very quick mark/space
  sendMark(50);
  sendSpace(100);
  // now send the header
  sendMark(VL_HEADER_MARK);
  sendSpace(VL_HEADER_SPACE);
  // reset writeCounter
  m_writeCounter = 0;
  // write the number of blocks being sent, most likely just 1
  sendByte(m_numBlocks);
  // now write the number of bytes in the last block
  sendByte(m_remainder);
}
References DEBUG_LOGF, m_blockSize, m_engine, m_isSending, m_numBlocks, m_remainder, m_size, m_writeCounter, Time::microseconds(), sendByte(), sendMark(), sendSpace(), VortexEngine::time(), VL_HEADER_MARK, and VL_HEADER_SPACE.
Referenced by send().
cleanup()
void VLSender::cleanup ()
Definition at line 37 of file VLSender.cpp.
{
}
Referenced by VortexEngine::cleanup().
init()
bool VLSender::init ()
Definition at line 32 of file VLSender.cpp.
{
  return true;
}
Referenced by VortexEngine::init().
initPWM()
void VLSender::initPWM () [private]
isSending()
bool VLSender::isSending () [inline]
Definition at line 27 of file VLSender.h.
{ return m_isSending; }
References m_isSending.
Referenced by ModeSharing::beginSendingVL(), and ModeSharing::continueSendingVL().
loadMode()
bool VLSender::loadMode (const Mode * targetMode)
Definition at line 41 of file VLSender.cpp.
{
  m_serialBuf.clear();
  // save the target mode to it's savefile buffer format
  if (!targetMode->saveToBuffer(m_serialBuf, 2)) {
    DEBUG_LOG("Failed to save mode to buffer");
    return false;
  }
  // decompress the mode on lifi, no compression here
  if (!m_serialBuf.decompress()) {
    DEBUG_LOG("Failed to decompress VL buf for sending");
    return false;
  }
  // ensure the data isn't too big
  if (m_serialBuf.rawSize() > VL_MAX_DATA_TRANSFER) {
    DEBUG_LOGF("Cannot transfer that much data: %u bytes", m_serialBuf.rawSize());
    return false;
  }
  // point the bitstream at the serial buffer
  m_bitStream.init((uint8_t *)m_serialBuf.rawData(), m_serialBuf.rawSize());
  // the size of the packet
  m_size = m_serialBuf.rawSize();
  // the number of blocks that will be sent (possibly just 1 with less than 32 bytes)
  m_numBlocks = (m_size + (VL_DEFAULT_BLOCK_SIZE - 1)) / VL_DEFAULT_BLOCK_SIZE;
  // the amount in the final block (possibly the only block)
  m_remainder = m_size % (VL_DEFAULT_BLOCK_SIZE + 0);
  DEBUG_LOGF("Num blocks: %u", m_numBlocks);
  DEBUG_LOGF("Remainder: %u", m_remainder);
  DEBUG_LOGF("Size: %u", m_size);
  // reset write counter
  m_writeCounter = 0;
  return true;
}
References ByteStream::clear(), DEBUG_LOG, DEBUG_LOGF, ByteStream::decompress(), BitStream::init(), m_bitStream, m_numBlocks, m_remainder, m_serialBuf, m_size, m_writeCounter, ByteStream::rawData(), ByteStream::rawSize(), Mode::saveToBuffer(), VL_DEFAULT_BLOCK_SIZE, and VL_MAX_DATA_TRANSFER.
Referenced by ModeSharing::beginSendingVL().
percentDone()
uint32_t VLSender::percentDone () [inline]
Definition at line 29 of file VLSender.h.
{ return (uint32_t)(((float)m_writeCounter / (float)m_size) * 100.0); }
References m_size, and m_writeCounter.
send()
bool VLSender::send ()
Definition at line 75 of file VLSender.cpp.
{
  // must have at least one block to send
  if (m_numBlocks < 1) {
    m_isSending = false;
    return m_isSending;
  }
  if (!m_isSending) {
    beginSend();
  }
  if (m_lastSendTime > 0 && m_lastSendTime + VL_DEFAULT_BLOCK_SPACING > m_engine.time().getCurtime()) {
    // don't send yet
    return m_isSending;
  }
  // blocksize is default unless it's the last block, then it's the remainder
  uint32_t blocksize = (m_numBlocks == 1) ? m_remainder : VL_DEFAULT_BLOCK_SIZE;
  DEBUG_LOGF("VLSender Sending block #%u", m_numBlocks);
  // pointer to the data at the correct location
  const uint8_t *buf_ptr = m_bitStream.data() + m_writeCounter;
  // iterate each byte in the block and write it
  for (uint32_t i = 0; i < blocksize; ++i) {
    // write the byte
    sendByte(*buf_ptr);
    // increment to next byte in buffer
    buf_ptr++;
    // record the written byte
    m_writeCounter++;
  }
  // wrote one block
  m_numBlocks--;
  // still sending if we have more blocks
  m_isSending = (m_numBlocks > 0);
  // the curtime
  m_lastSendTime = m_engine.time().getCurtime();
  // return whether still sending
  return m_isSending;
}
References beginSend(), BitStream::data(), DEBUG_LOGF, Time::getCurtime(), m_bitStream, m_engine, m_isSending, m_lastSendTime, m_numBlocks, m_remainder, m_writeCounter, sendByte(), VortexEngine::time(), VL_DEFAULT_BLOCK_SIZE, and VL_DEFAULT_BLOCK_SPACING.
Referenced by ModeSharing::beginSendingVL(), and ModeSharing::continueSendingVL().
sendByte()
void VLSender::sendByte (uint8_t data) [private]
Definition at line 132 of file VLSender.cpp.
{
  // Sends from left to right, MSB first
  for (int b = 0; b < 8; b++) {
    // grab the bit of data at the indexspace
    uint32_t bit = (data >> (7 - b)) & 1;
    // send 3x timing size for 1s and 1x timing for 0
    sendMark(VL_TIMING + (VL_TIMING * (2 * bit)));
    // send 1x timing size for space
    sendSpace(VL_TIMING);
  }
  DEBUG_LOGF("Sent byte[%u]: 0x%x", m_writeCounter, data);
 }
References DEBUG_LOGF, m_writeCounter, sendMark(), sendSpace(), and VL_TIMING.
Referenced by beginSend(), and send().
sendMark()
void VLSender::sendMark (uint16_t time) [private]
Definition at line 146 of file VLSender.cpp.
{
#ifdef VORTEX_LIB
  // send mark timing over socket
  m_engine.vortexLib().vcallbacks()->infraredWrite(true, time);
#else
  startPWM();
  m_engine.time().delayMicroseconds(time);
#endif
}
References Time::delayMicroseconds(), m_engine, startPWM(), VortexEngine::time(), and VortexEngine::vortexLib().
Referenced by beginSend(), and sendByte().
sendSpace()
void VLSender::sendSpace (uint16_t time) [private]
Definition at line 157 of file VLSender.cpp.
{
#ifdef VORTEX_LIB
  // send space timing over socket
  m_engine.vortexLib().vcallbacks()->infraredWrite(false, time);
#else
  stopPWM();
  m_engine.time().delayMicroseconds(time);
#endif
}
References Time::delayMicroseconds(), m_engine, stopPWM(), VortexEngine::time(), and VortexEngine::vortexLib().
Referenced by beginSend(), and sendByte().
startPWM()
void VLSender::startPWM () [private]
Definition at line 168 of file VLSender.cpp.
{
#if defined(VORTEX_EMBEDDED)
  // brightness backup
  uint8_t oldBrightness = Leds::getBrightness();
  // ensure max brightness
  Leds::setBrightness(255);
  Leds::clearAll();
  Leds::setIndex(LED_0, RGB_WHITE);
  Leds::update();
  // restore brightness
  Leds::setBrightness(oldBrightness);
#endif
}
References Leds::clearAll(), Leds::getBrightness(), LED_0, RGB_WHITE, Leds::setBrightness(), Leds::setIndex(), and Leds::update().
Referenced by sendMark().
stopPWM()
void VLSender::stopPWM () [private]
Definition at line 183 of file VLSender.cpp.
{
#if defined(VORTEX_EMBEDDED)
  Leds::clearAll();
  Leds::update();
#endif
}
References Leds::clearAll(), and Leds::update().
Referenced by sendSpace().
Member Data Documentation
m_bitStream
BitStream VLSender::m_bitStream [private]
Definition at line 51 of file VLSender.h.
Referenced by loadMode(), and send().
m_blockSize
uint32_t VLSender::m_blockSize [private]
Definition at line 63 of file VLSender.h.
Referenced by beginSend().
m_engine
VortexEngine& VLSender::m_engine [private]
Definition at line 46 of file VLSender.h.
Referenced by beginSend(), send(), sendMark(), and sendSpace().
m_isSending
bool VLSender::m_isSending [private]
Definition at line 52 of file VLSender.h.
Referenced by beginSend(), isSending(), and send().
m_lastSendTime
uint32_t VLSender::m_lastSendTime [private]
Definition at line 53 of file VLSender.h.
Referenced by send().
m_numBlocks
uint8_t VLSender::m_numBlocks [private]
Definition at line 58 of file VLSender.h.
Referenced by beginSend(), loadMode(), and send().
m_remainder
uint8_t VLSender::m_remainder [private]
Definition at line 60 of file VLSender.h.
Referenced by beginSend(), loadMode(), and send().
m_serialBuf
ByteStream VLSender::m_serialBuf [private]
Definition at line 49 of file VLSender.h.
Referenced by loadMode().
m_size
uint32_t VLSender::m_size [private]
Definition at line 56 of file VLSender.h.
Referenced by beginSend(), loadMode(), and percentDone().
m_writeCounter
uint32_t VLSender::m_writeCounter [private]
Definition at line 66 of file VLSender.h.
Referenced by beginSend(), loadMode(), percentDone(), send(), and sendByte().
The documentation for this class was generated from the following files:
VortexEngine/src/Wireless/VLSender.h
VortexEngine/src/Wireless/VLSender.cpp