BouncePattern Class Reference
#include <BouncePattern.h>
Public Member Functions
BouncePattern (VortexEngine &engine, const PatternArgs &args)
virtual ~BouncePattern ()
virtual void init () override
Protected Member Functions
virtual void blinkOn () override
virtual void poststep () override
Private Attributes
uint8_t m_progress
uint8_t m_fadeAmount
Additional Inherited Members
Detailed Description
Definition at line 5 of file BouncePattern.h.
Constructor & Destructor Documentation
BouncePattern()
BouncePattern::BouncePattern (VortexEngine & engine, const PatternArgs & args)
Definition at line 14 of file BouncePattern.cpp.
                                                                          :
  BlinkStepPattern(engine, args),
  m_progress(0),
  m_fadeAmount(0)
{
  m_patternID = PATTERN_BOUNCE;
  REGISTER_ARG(m_fadeAmount);
  setArgs(args);
}
References m_fadeAmount, Pattern::m_patternID, PATTERN_BOUNCE, REGISTER_ARG, and Pattern::setArgs().
 BouncePattern()
BouncePattern::~BouncePattern () [virtual]
Definition at line 24 of file BouncePattern.cpp.
{
}
Member Function Documentation
blinkOn()
void BouncePattern::blinkOn () [override], [protected], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 38 of file BouncePattern.cpp.
{
  m_engine.leds().setAll(m_colorset.cur());
  if (m_progress < PAIR_COUNT) {
    m_engine.leds().setPair((Pair)m_progress, m_colorset.peekNext());
  } else {
    m_engine.leds().setPair((Pair)(TOTAL_STEPS - m_progress), m_colorset.peekNext());
  }
}
References Colorset::cur(), VortexEngine::leds(), Pattern::m_colorset, Pattern::m_engine, m_progress, PAIR_COUNT, Colorset::peekNext(), Leds::setAll(), Leds::setPair(), and TOTAL_STEPS.
init()
void BouncePattern::init () [override], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 29 of file BouncePattern.cpp.
{
  BlinkStepPattern::init();
  // reset progress
  m_progress = 0;
  // start colorset at index 0 so cur() works
  m_colorset.setCurIndex(0);
}
References BlinkStepPattern::init(), Pattern::m_colorset, m_progress, and Colorset::setCurIndex().
poststep()
void BouncePattern::poststep () [override], [protected], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 48 of file BouncePattern.cpp.
{
  m_progress = (m_progress + 1) % TOTAL_STEPS;
  if (m_progress == 0 || m_progress == HALF_STEPS) {
    m_colorset.getNext();
  }
}
References Colorset::getNext(), HALF_STEPS, Pattern::m_colorset, m_progress, and TOTAL_STEPS.
Member Data Documentation
m_fadeAmount
uint8_t BouncePattern::m_fadeAmount [private]
Definition at line 22 of file BouncePattern.h.
Referenced by BouncePattern().
m_progress
uint8_t BouncePattern::m_progress [private]
Definition at line 20 of file BouncePattern.h.
Referenced by blinkOn(), init(), and poststep().
The documentation for this class was generated from the following files:
VortexEngine/src/Patterns/Multi/BouncePattern.h
VortexEngine/src/Patterns/Multi/BouncePattern.cpp