PatternArgs Class Reference
#include <PatternArgs.h>
Public Member Functions
PatternArgs ()
PatternArgs (uint8_t a1)
PatternArgs (uint8_t a1, uint8_t a2)
PatternArgs (uint8_t a1, uint8_t a2, uint8_t a3)
PatternArgs (uint8_t a1, uint8_t a2, uint8_t a3, uint8_t a4)
PatternArgs (uint8_t a1, uint8_t a2, uint8_t a3, uint8_t a4, uint8_t a5)
PatternArgs (uint8_t a1, uint8_t a2, uint8_t a3, uint8_t a4, uint8_t a5, uint8_t a6)
PatternArgs (uint8_t a1, uint8_t a2, uint8_t a3, uint8_t a4, uint8_t a5, uint8_t a6, uint8_t a7)
PatternArgs (uint8_t a1, uint8_t a2, uint8_t a3, uint8_t a4, uint8_t a5, uint8_t a6, uint8_t a7, uint8_t a8)
void init ()
void init (uint8_t a1)
void init (uint8_t a1, uint8_t a2)
void init (uint8_t a1, uint8_t a2, uint8_t a3)
void init (uint8_t a1, uint8_t a2, uint8_t a3, uint8_t a4)
void init (uint8_t a1, uint8_t a2, uint8_t a3, uint8_t a4, uint8_t a5)
void init (uint8_t a1, uint8_t a2, uint8_t a3, uint8_t a4, uint8_t a5, uint8_t a6)
void init (uint8_t a1, uint8_t a2, uint8_t a3, uint8_t a4, uint8_t a5, uint8_t a6, uint8_t a7)
void init (uint8_t a1, uint8_t a2, uint8_t a3, uint8_t a4, uint8_t a5, uint8_t a6, uint8_t a7, uint8_t a8)
void addArgs (uint8_t a1)
void addArgs (uint8_t a1, uint8_t a2)
void addArgs (uint8_t a1, uint8_t a2, uint8_t a3)
void addArgs (uint8_t a1, uint8_t a2, uint8_t a3, uint8_t a4)
void addArgs (uint8_t a1, uint8_t a2, uint8_t a3, uint8_t a4, uint8_t a5)
void addArgs (uint8_t a1, uint8_t a2, uint8_t a3, uint8_t a4, uint8_t a5, uint8_t a6)
void addArgs (uint8_t a1, uint8_t a2, uint8_t a3, uint8_t a4, uint8_t a5, uint8_t a6, uint8_t a7)
void addArgs (uint8_t a1, uint8_t a2, uint8_t a3, uint8_t a4, uint8_t a5, uint8_t a6, uint8_t a7, uint8_t a8)
bool operator!= (const PatternArgs &rhs) const
bool operator== (const PatternArgs &rhs) const
uint8_t operator[] (int index) const
bool serialize (ByteStream &buffer, ArgMap argmap=ARG_ALL) const
ArgMap unserialize (ByteStream &buffer)
Public Attributes
xx xx xx xx xx xx xx xx xx
union {
 uint8_t args [8]
 struct {
  uint8_t arg1
  uint8_t arg2
  uint8_t arg3
  uint8_t arg4
  uint8_t arg5
  uint8_t arg6
  uint8_t arg7
  uint8_t arg8
 }
 struct {
  uint8_t onDuration
  uint8_t offDuration
  uint8_t gapDuration
  uint8_t dashDuration
  uint8_t groupSize
 } basic
 struct {
  uint8_t onDuration
  uint8_t offDuration
  uint8_t gapDuration
  uint8_t dashDuration
  uint8_t groupSize
  uint8_t blendSpeed
  uint8_t numFlips
 } blend
 struct {
  uint8_t onDuration
  uint8_t offDuration
  uint8_t gapDuration
  uint8_t dashDuration
  uint8_t groupSize
  uint8_t colorIndex
 } solid
};
uint8_t numArgs
Detailed Description
Definition at line 36 of file PatternArgs.h.
Constructor & Destructor Documentation
PatternArgs() [1/9]
PatternArgs::PatternArgs ()
Definition at line 5 of file PatternArgs.cpp.
                         :
  arg1(0), arg2(0), arg3(0), arg4(0), arg5(0), arg6(0), arg7(0), arg8(0), numArgs(0)
{
}
Referenced by init().
PatternArgs() [2/9]
PatternArgs::PatternArgs (uint8_t a1)
Definition at line 9 of file PatternArgs.cpp.
                                   :
  arg1(a1), arg2(0), arg3(0), arg4(0), arg5(0), arg6(0), arg7(0), arg8(0), numArgs(1)
{
}
PatternArgs() [3/9]
PatternArgs::PatternArgs (uint8_t a1, uint8_t a2)
Definition at line 13 of file PatternArgs.cpp.
                                               :
  arg1(a1), arg2(a2), arg3(0), arg4(0), arg5(0), arg6(0), arg7(0), arg8(0), numArgs(2)
{
}
PatternArgs() [4/9]
PatternArgs::PatternArgs (uint8_t a1, uint8_t a2, uint8_t a3)
Definition at line 17 of file PatternArgs.cpp.
                                                           :
  arg1(a1), arg2(a2), arg3(a3), arg4(0), arg5(0), arg6(0), arg7(0), arg8(0), numArgs(3)
{
}
PatternArgs() [5/9]
PatternArgs::PatternArgs (uint8_t a1, uint8_t a2, uint8_t a3, uint8_t a4)
Definition at line 21 of file PatternArgs.cpp.
                                                                       :
  arg1(a1), arg2(a2), arg3(a3), arg4(a4), arg5(0), arg6(0), arg7(0), arg8(0), numArgs(4)
{
}
PatternArgs() [6/9]
PatternArgs::PatternArgs (uint8_t a1, uint8_t a2, uint8_t a3, uint8_t a4, uint8_t a5)
Definition at line 25 of file PatternArgs.cpp.
                                                                                   :
  arg1(a1), arg2(a2), arg3(a3), arg4(a4), arg5(a5), arg6(0), arg7(0), arg8(0), numArgs(5)
{
}
PatternArgs() [7/9]
PatternArgs::PatternArgs (uint8_t a1, uint8_t a2, uint8_t a3, uint8_t a4, uint8_t a5, uint8_t a6)
Definition at line 29 of file PatternArgs.cpp.
                                                                                               :
  arg1(a1), arg2(a2), arg3(a3), arg4(a4), arg5(a5), arg6(a6), arg7(0), arg8(0), numArgs(6)
{
}
PatternArgs() [8/9]
PatternArgs::PatternArgs (uint8_t a1, uint8_t a2, uint8_t a3, uint8_t a4, uint8_t a5, uint8_t a6, uint8_t a7)
Definition at line 33 of file PatternArgs.cpp.
                                                                                                           :
  arg1(a1), arg2(a2), arg3(a3), arg4(a4), arg5(a5), arg6(a6), arg7(a7), arg8(0), numArgs(7)
{
}
PatternArgs() [9/9]
PatternArgs::PatternArgs (uint8_t a1, uint8_t a2, uint8_t a3, uint8_t a4, uint8_t a5, uint8_t a6, uint8_t a7, uint8_t a8)
Definition at line 37 of file PatternArgs.cpp.
                                                                                                                       :
  arg1(a1), arg2(a2), arg3(a3), arg4(a4), arg5(a5), arg6(a6), arg7(a7), arg8(a8), numArgs(8)
{
}
Member Function Documentation
addArgs() [1/8]
void PatternArgs::addArgs (uint8_t a1)
Definition at line 79 of file PatternArgs.cpp.
{
  args[numArgs++] = a1;
}
References args, and numArgs.
Referenced by Pattern::getArgs().
addArgs() [2/8]
void PatternArgs::addArgs (uint8_t a1, uint8_t a2)
Definition at line 84 of file PatternArgs.cpp.
{
  args[numArgs++] = a1;
  args[numArgs++] = a2;
}
References args, and numArgs.
addArgs() [3/8]
void PatternArgs::addArgs (uint8_t a1, uint8_t a2, uint8_t a3)
Definition at line 90 of file PatternArgs.cpp.
{
  args[numArgs++] = a1;
  args[numArgs++] = a2;
  args[numArgs++] = a3;
}
References args, and numArgs.
addArgs() [4/8]
void PatternArgs::addArgs (uint8_t a1, uint8_t a2, uint8_t a3, uint8_t a4)
Definition at line 97 of file PatternArgs.cpp.
{
  args[numArgs++] = a1;
  args[numArgs++] = a2;
  args[numArgs++] = a3;
  args[numArgs++] = a4;
}
References args, and numArgs.
addArgs() [5/8]
void PatternArgs::addArgs (uint8_t a1, uint8_t a2, uint8_t a3, uint8_t a4, uint8_t a5)
Definition at line 105 of file PatternArgs.cpp.
{
  args[numArgs++] = a1;
  args[numArgs++] = a2;
  args[numArgs++] = a3;
  args[numArgs++] = a4;
  args[numArgs++] = a5;
}
References args, and numArgs.
addArgs() [6/8]
void PatternArgs::addArgs (uint8_t a1, uint8_t a2, uint8_t a3, uint8_t a4, uint8_t a5, uint8_t a6)
Definition at line 114 of file PatternArgs.cpp.
{
  args[numArgs++] = a1;
  args[numArgs++] = a2;
  args[numArgs++] = a3;
  args[numArgs++] = a4;
  args[numArgs++] = a5;
  args[numArgs++] = a6;
}
References args, and numArgs.
addArgs() [7/8]
void PatternArgs::addArgs (uint8_t a1, uint8_t a2, uint8_t a3, uint8_t a4, uint8_t a5, uint8_t a6, uint8_t a7)
Definition at line 124 of file PatternArgs.cpp.
{
  args[numArgs++] = a1;
  args[numArgs++] = a2;
  args[numArgs++] = a3;
  args[numArgs++] = a4;
  args[numArgs++] = a5;
  args[numArgs++] = a6;
  args[numArgs++] = a7;
}
References args, and numArgs.
addArgs() [8/8]
void PatternArgs::addArgs (uint8_t a1, uint8_t a2, uint8_t a3, uint8_t a4, uint8_t a5, uint8_t a6, uint8_t a7, uint8_t a8)
Definition at line 135 of file PatternArgs.cpp.
{
  args[numArgs++] = a1;
  args[numArgs++] = a2;
  args[numArgs++] = a3;
  args[numArgs++] = a4;
  args[numArgs++] = a5;
  args[numArgs++] = a6;
  args[numArgs++] = a7;
  args[numArgs++] = a7;
}
References args, and numArgs.
init() [1/9]
void PatternArgs::init ()
Definition at line 42 of file PatternArgs.cpp.
{
  *this = PatternArgs();
}
References PatternArgs().
Referenced by Randomizer::crushPattern(), Randomizer::dashPattern(), Randomizer::gapPattern(), Pattern::getArgs(), and Randomizer::traditionalPattern().
init() [2/9]
void PatternArgs::init (uint8_t a1)
Definition at line 46 of file PatternArgs.cpp.
{
  *this = PatternArgs(a1);
}
References PatternArgs().
init() [3/9]
void PatternArgs::init (uint8_t a1, uint8_t a2)
Definition at line 50 of file PatternArgs.cpp.
{
  *this = PatternArgs(a1, a2);
}
References PatternArgs().
init() [4/9]
void PatternArgs::init (uint8_t a1, uint8_t a2, uint8_t a3)
Definition at line 54 of file PatternArgs.cpp.
{
  *this = PatternArgs(a1, a2, a3);
}
References PatternArgs().
init() [5/9]
void PatternArgs::init (uint8_t a1, uint8_t a2, uint8_t a3, uint8_t a4)
Definition at line 58 of file PatternArgs.cpp.
{
  *this = PatternArgs(a1, a2, a3, a4);
}
References PatternArgs().
init() [6/9]
void PatternArgs::init (uint8_t a1, uint8_t a2, uint8_t a3, uint8_t a4, uint8_t a5)
Definition at line 62 of file PatternArgs.cpp.
{
  *this = PatternArgs(a1, a2, a3, a4, a5);
}
References PatternArgs().
init() [7/9]
void PatternArgs::init (uint8_t a1, uint8_t a2, uint8_t a3, uint8_t a4, uint8_t a5, uint8_t a6)
Definition at line 66 of file PatternArgs.cpp.
{
  *this = PatternArgs(a1, a2, a3, a4, a5, a6);
}
References PatternArgs().
init() [8/9]
void PatternArgs::init (uint8_t a1, uint8_t a2, uint8_t a3, uint8_t a4, uint8_t a5, uint8_t a6, uint8_t a7)
Definition at line 70 of file PatternArgs.cpp.
{
  *this = PatternArgs(a1, a2, a3, a4, a5, a6, a7);
}
References PatternArgs().
init() [9/9]
void PatternArgs::init (uint8_t a1, uint8_t a2, uint8_t a3, uint8_t a4, uint8_t a5, uint8_t a6, uint8_t a7, uint8_t a8)
Definition at line 74 of file PatternArgs.cpp.
{
  *this = PatternArgs(a1, a2, a3, a4, a5, a6, a7, a8);
}
References PatternArgs().
operator!=()
bool PatternArgs::operator!= (const PatternArgs & rhs) const
Definition at line 147 of file PatternArgs.cpp.
{
  return !(*this == rhs);
}
operator==()
bool PatternArgs::operator== (const PatternArgs & rhs) const
Definition at line 152 of file PatternArgs.cpp.
{
  // just check number of args first
  if (rhs.numArgs != numArgs) {
    return false;
  }
  // compare num args
  for (uint8_t i = 0; i < numArgs; ++i) {
    if (args[i] != rhs.args[i]) {
      return false;
    }
  }
  return true;
}
References args, and numArgs.
operator[]()
uint8_t PatternArgs::operator[] (int index) const
Definition at line 167 of file PatternArgs.cpp.
{
  if (index > 7) {
    return 0;
  }
  return args[index];
}
References args.
serialize()
bool PatternArgs::serialize (ByteStream & buffer, ArgMap argmap = ARG_ALL) const
Definition at line 175 of file PatternArgs.cpp.
{
  if (!buffer.serialize8(argmap)) {
    return false;
  }
  for (uint8_t i = 0; i < MAX_ARGS; ++i) {
    if (ARGMAP_ISSET(argmap, i)) {
      if (!buffer.serialize8(args[i])) {
        return false;
      }
    }
  }
  return true;
}
References ARGMAP_ISSET, args, MAX_ARGS, and ByteStream::serialize8().
Referenced by Pattern::serialize().
unserialize()
ArgMap PatternArgs::unserialize (ByteStream & buffer)
Definition at line 190 of file PatternArgs.cpp.
{
  ArgMap argmap = ARG_NONE;
  if (!buffer.unserialize8(&argmap)) {
    return ARG_NONE;
  }
  for (uint8_t i = 0; i < MAX_ARGS; ++i) {
    if (ARGMAP_ISSET(argmap, i)) {
      if (!buffer.unserialize8(args + i)) {
        break;
      }
    }
  }
  return argmap;
}
References ARG_NONE, ARGMAP_ISSET, args, MAX_ARGS, and ByteStream::unserialize8().
Referenced by Pattern::unserialize().
Member Data Documentation
union { ... }
arg1
uint8_t PatternArgs::arg1
Definition at line 83 of file PatternArgs.h.
Referenced by BackStrobePattern::BackStrobePattern().
arg2
uint8_t PatternArgs::arg2
Definition at line 84 of file PatternArgs.h.
Referenced by BackStrobePattern::BackStrobePattern().
arg3
uint8_t PatternArgs::arg3
Definition at line 85 of file PatternArgs.h.
Referenced by BackStrobePattern::BackStrobePattern().
arg4
uint8_t PatternArgs::arg4
Definition at line 86 of file PatternArgs.h.
arg5
uint8_t PatternArgs::arg5
Definition at line 87 of file PatternArgs.h.
arg6
uint8_t PatternArgs::arg6
Definition at line 88 of file PatternArgs.h.
Referenced by Randomizer::rollCustomPattern().
arg7
uint8_t PatternArgs::arg7
Definition at line 89 of file PatternArgs.h.
Referenced by Randomizer::rollCustomPattern().
arg8
uint8_t PatternArgs::arg8
Definition at line 90 of file PatternArgs.h.
args
uint8_t PatternArgs::args[8]
Definition at line 81 of file PatternArgs.h.
Referenced by addArgs(), operator==(), operator[](), Pattern::serialize(), serialize(), Pattern::setArgs(), and unserialize().
struct { ... } PatternArgs::basic
struct { ... } PatternArgs::blend
blendSpeed
uint8_t PatternArgs::blendSpeed
Definition at line 107 of file PatternArgs.h.
colorIndex
uint8_t PatternArgs::colorIndex
Definition at line 117 of file PatternArgs.h.
dashDuration
uint8_t PatternArgs::dashDuration
Definition at line 97 of file PatternArgs.h.
gapDuration
uint8_t PatternArgs::gapDuration
Definition at line 96 of file PatternArgs.h.
groupSize
uint8_t PatternArgs::groupSize
Definition at line 98 of file PatternArgs.h.
numArgs
uint8_t PatternArgs::numArgs
Definition at line 121 of file PatternArgs.h.
Referenced by addArgs(), PatternBuilder::isDefaultArgs(), operator==(), and Randomizer::rollCustomPattern().
numFlips
uint8_t PatternArgs::numFlips
Definition at line 108 of file PatternArgs.h.
offDuration
uint8_t PatternArgs::offDuration
Definition at line 95 of file PatternArgs.h.
onDuration
uint8_t PatternArgs::onDuration
Definition at line 94 of file PatternArgs.h.
struct { ... } PatternArgs::solid
The documentation for this class was generated from the following files:
VortexEngine/src/Patterns/PatternArgs.h
VortexEngine/src/Patterns/PatternArgs.cpp