ZigzagPattern::Snake Class Reference
Public Member Functions
Snake (VortexEngine &engine)
void init (uint8_t onDuration, uint8_t offDuration, const Colorset &colorset, uint32_t colorOffset, uint8_t step=0, uint8_t snakeSize=1, uint8_t fadeAmount=55, uint8_t changeBoundary=3)
void step ()
void draw ()
Private Member Functions
void drawSnake ()
Private Attributes
VortexEngine & m_engine
Timer m_blinkTimer
Colorset m_colorset
uint8_t m_step
uint8_t m_snakeSize
uint8_t m_fadeAmount
uint8_t m_changeBoundary
Detailed Description
Definition at line 23 of file ZigzagPattern.h.
Constructor & Destructor Documentation
Snake()
ZigzagPattern::Snake::Snake (VortexEngine & engine)
Definition at line 85 of file ZigzagPattern.cpp.
                                              :
  m_engine(engine),
  m_blinkTimer(engine),
  m_colorset(),
  m_step(0),
  m_snakeSize(1),
  m_fadeAmount(55),
  m_changeBoundary(3)
{
}
Member Function Documentation
draw()
void ZigzagPattern::Snake::draw ()
Definition at line 128 of file ZigzagPattern.cpp.
{
  // when the blinkTimer triggers
  switch (m_blinkTimer.alarm()) {
  case 0: // blinking on
    // draw two snakes, one on the current step, one on the opposite side
    drawSnake();
    break;
  case 1: // blinking off
    m_engine.leds().clearAll();
    break;
  default:
  case -1:
    // nothing
    break;
  }
}
References Leds::clearAll(), VortexEngine::leds(), and Pattern::m_engine.
Referenced by ZigzagPattern::play().
drawSnake()
void ZigzagPattern::Snake::drawSnake () [private]
Definition at line 146 of file ZigzagPattern.cpp.
{
  uint8_t segment_position;
  int32_t colIndex = 0;
  for (uint8_t segment = 0; segment < m_snakeSize; ++segment) {
    // calculate the position of this segment, if the segment being rendered is
    // greater than the head position it means the snake head is at an index that
    // won't support it's entire tail without wrapping below 0
    if (segment > m_step) {
      segment_position = NUM_ZIGZAG_STEPS - (segment - m_step);
    } else {
      segment_position = m_step - segment;
    }
    // adjust the brightness of the color before setting
    RGBColor col = m_colorset.peek(colIndex);
    if (segment < m_snakeSize) {
      col.adjustBrightness(m_fadeAmount * segment);
    }
    // lookup the target in the step positions array and turn it on with given color/brightness
    m_engine.leds().setIndex(ledStepPositions[segment_position], col);
    // if this segment is on the step where the color changes
    if (segment_position == m_changeBoundary) {
      // then decrement the color index for the rest of the snake so that the
      // tail of the snake has the old color till it reaches the change point
      colIndex--;
    }
  }
}
References RGBColor::adjustBrightness(), VortexEngine::leds(), ZigzagPattern::ledStepPositions, Pattern::m_colorset, Pattern::m_engine, ZigzagPattern::m_fadeAmount, ZigzagPattern::m_snakeSize, NUM_ZIGZAG_STEPS, Colorset::peek(), and Leds::setIndex().
init()
void ZigzagPattern::Snake::init (uint8_t onDuration, uint8_t offDuration, const Colorset & colorset, uint32_t colorOffset, uint8_t step = 0, uint8_t snakeSize = 1, uint8_t fadeAmount = 55, uint8_t changeBoundary = 3)
Definition at line 96 of file ZigzagPattern.cpp.
{
  // reset the blink timer entirely
  m_blinkTimer.reset();
  // dops timing
  m_blinkTimer.addAlarm(onDuration);
  m_blinkTimer.addAlarm(offDuration);
  // start the blink timer from the next frame
  m_blinkTimer.start();
  // start on the first color so that cur() works immediately
  m_colorset = colorset;
  m_colorset.setCurIndex(colorOffset);
  // set the starting step
  m_step = step;
  // set the snake size
  m_snakeSize = snakeSize;
  // set fade amount and change boundary
  m_fadeAmount = fadeAmount;
  m_changeBoundary = changeBoundary;
}
References Pattern::m_colorset, ZigzagPattern::m_fadeAmount, ZigzagPattern::m_snakeSize, and Colorset::setCurIndex().
Referenced by ZigzagPattern::init().
step()
void ZigzagPattern::Snake::step ()
Definition at line 118 of file ZigzagPattern.cpp.
{
  // increment to the next step
  m_step = (m_step + 1) % NUM_ZIGZAG_STEPS;
  // if the step is on a change boundary then increment the snake color
  if (m_step == m_changeBoundary) {
    m_colorset.getNext();
  }
}
References Colorset::getNext(), Pattern::m_colorset, and NUM_ZIGZAG_STEPS.
Referenced by ZigzagPattern::play().
Member Data Documentation
m_blinkTimer
Timer ZigzagPattern::Snake::m_blinkTimer [private]
Definition at line 36 of file ZigzagPattern.h.
m_changeBoundary
uint8_t ZigzagPattern::Snake::m_changeBoundary [private]
Definition at line 41 of file ZigzagPattern.h.
m_colorset
Colorset ZigzagPattern::Snake::m_colorset [private]
Definition at line 37 of file ZigzagPattern.h.
m_engine
VortexEngine& ZigzagPattern::Snake::m_engine [private]
Definition at line 35 of file ZigzagPattern.h.
m_fadeAmount
uint8_t ZigzagPattern::Snake::m_fadeAmount [private]
Definition at line 40 of file ZigzagPattern.h.
m_snakeSize
uint8_t ZigzagPattern::Snake::m_snakeSize [private]
Definition at line 39 of file ZigzagPattern.h.
m_step
uint8_t ZigzagPattern::Snake::m_step [private]
Definition at line 38 of file ZigzagPattern.h.
The documentation for this class was generated from the following files:
VortexEngine/src/Patterns/Multi/ZigzagPattern.h
VortexEngine/src/Patterns/Multi/ZigzagPattern.cpp