SolidPattern Class Reference
#include <SolidPattern.h>
Public Member Functions
SolidPattern (VortexEngine &engine, const PatternArgs &args)
Protected Member Functions
virtual void onBlinkOn () override
Protected Attributes
uint8_t m_colIndex
Additional Inherited Members
Detailed Description
Definition at line 8 of file SolidPattern.h.
Constructor & Destructor Documentation
SolidPattern()
SolidPattern::SolidPattern (VortexEngine & engine, const PatternArgs & args)
Definition at line 3 of file SolidPattern.cpp.
                                                                        :
  BasicPattern(engine, args),
  m_colIndex(0)
{
  m_patternID = PATTERN_SOLID;
  REGISTER_ARG(m_colIndex);
  setArgs(args);
}
References m_colIndex, Pattern::m_patternID, PATTERN_SOLID, REGISTER_ARG, and Pattern::setArgs().
Member Function Documentation
onBlinkOn()
void SolidPattern::onBlinkOn () [override], [protected], [virtual]
Reimplemented from BasicPattern.
Definition at line 13 of file SolidPattern.cpp.
{
  if (m_colIndex == 0) {
    m_colorset.resetIndex();
  } else {
    m_colorset.setCurIndex(m_colIndex - 1);
  }
  BasicPattern::onBlinkOn();
}
References m_colIndex, Pattern::m_colorset, BasicPattern::onBlinkOn(), Colorset::resetIndex(), and Colorset::setCurIndex().
Member Data Documentation
m_colIndex
uint8_t SolidPattern::m_colIndex [protected]
Definition at line 17 of file SolidPattern.h.
Referenced by onBlinkOn(), and SolidPattern().
The documentation for this class was generated from the following files:
VortexEngine/src/Patterns/Single/SolidPattern.h
VortexEngine/src/Patterns/Single/SolidPattern.cpp