WarpWormPattern Class Reference
#include <WarpWormPattern.h>
Public Member Functions
WarpWormPattern (VortexEngine &engine, const PatternArgs &args)
virtual ~WarpWormPattern ()
virtual void init () override
Protected Member Functions
virtual void blinkOn () override
virtual void poststep () override
Private Attributes
uint8_t m_progress
Additional Inherited Members
Detailed Description
Definition at line 5 of file WarpWormPattern.h.
Constructor & Destructor Documentation
WarpWormPattern()
WarpWormPattern::WarpWormPattern (VortexEngine & engine, const PatternArgs & args)
Definition at line 10 of file WarpWormPattern.cpp.
                                                                              :
  BlinkStepPattern(engine, args),
  m_progress(0)
{
  m_patternID = PATTERN_WARPWORM;
  setArgs(args);
}
References Pattern::m_patternID, PATTERN_WARPWORM, and Pattern::setArgs().
 WarpWormPattern()
WarpWormPattern::~WarpWormPattern () [virtual]
Definition at line 18 of file WarpWormPattern.cpp.
{
}
Member Function Documentation
blinkOn()
void WarpWormPattern::blinkOn () [override], [protected], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 32 of file WarpWormPattern.cpp.
{
  int wormSize = 6;
  m_engine.leds().setAll(m_colorset.get(0));
  for (int body = 0; body < wormSize; ++body) {
    if (body + m_progress < LED_COUNT) {
      m_engine.leds().setIndex((LedPos)(body + m_progress), m_colorset.cur());
    } else {
      RGBColor col = m_colorset.peekNext();
      if (m_colorset.curIndex() == m_colorset.numColors() - 1) {
        col = m_colorset.peek(2);
      }
      m_engine.leds().setIndex((LedPos)((body + m_progress) % LED_COUNT), col);
    }
  }
}
References Colorset::cur(), Colorset::curIndex(), Colorset::get(), LED_COUNT, VortexEngine::leds(), Pattern::m_colorset, Pattern::m_engine, m_progress, Colorset::numColors(), Colorset::peek(), Colorset::peekNext(), Leds::setAll(), and Leds::setIndex().
init()
void WarpWormPattern::init () [override], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 23 of file WarpWormPattern.cpp.
{
  BlinkStepPattern::init();
  // reset progress
  m_progress = 0;
  // start colorset at index 0 so cur() works
  m_colorset.setCurIndex(1);
}
References BlinkStepPattern::init(), Pattern::m_colorset, m_progress, and Colorset::setCurIndex().
poststep()
void WarpWormPattern::poststep () [override], [protected], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 49 of file WarpWormPattern.cpp.
{
  m_progress = (m_progress + 1) % LED_COUNT;
  if (m_progress == 0) {
    m_colorset.getNext();
    if (m_colorset.curIndex() == 0) {
      m_colorset.getNext();
    }
  }
}
References Colorset::curIndex(), Colorset::getNext(), LED_COUNT, Pattern::m_colorset, and m_progress.
Member Data Documentation
m_progress
uint8_t WarpWormPattern::m_progress [private]
Definition at line 20 of file WarpWormPattern.h.
Referenced by blinkOn(), init(), and poststep().
The documentation for this class was generated from the following files:
VortexEngine/src/Patterns/Multi/WarpWormPattern.h
VortexEngine/src/Patterns/Multi/WarpWormPattern.cpp