Menus Class Reference
#include <Menus.h>
Public Member Functions
Menus (VortexEngine &engine)
~Menus ()
bool init ()
void cleanup ()
bool run ()
bool openMenuSelection ()
bool openMenu (uint32_t index, bool advanced=false)
void showSelection (RGBColor colval=RGB_WHITE5)
bool checkOpen ()
bool checkInMenu ()
Menu * curMenu ()
MenuEntryID curMenuID ()
Private Types
enum MenuState { MENU_STATE_NOT_OPEN = 0
, MENU_STATE_MENU_SELECTION
, MENU_STATE_IN_MENU
 }
Private Member Functions
bool runCurMenu ()
bool runMenuSelection ()
LedPos calcLedPos ()
void closeCurMenu ()
Private Attributes
VortexEngine & m_engine
MenuState m_menuState
uint8_t m_selection
uint32_t m_openTime
Menu * m_pCurMenu
Detailed Description
Definition at line 33 of file Menus.h.
Member Enumeration Documentation
MenuState
enum Menus::MenuState [private]
Enumerator
MENU_STATE_NOT_OPEN
MENU_STATE_MENU_SELECTION
MENU_STATE_IN_MENU
Definition at line 81 of file Menus.h.
                 {
    // menus aren't open at all
    MENU_STATE_NOT_OPEN = 0,
    // menus are open and the user is choosing a menu
    MENU_STATE_MENU_SELECTION,
    // the menus are open and we opened a menu
    MENU_STATE_IN_MENU
  };
Constructor & Destructor Documentation
Menus()
Menus::Menus (VortexEngine & engine)
Definition at line 64 of file Menus.cpp.
                                 :
  m_engine(engine),
  m_menuState(MENU_STATE_NOT_OPEN),
  m_selection(0),
  m_openTime(0),
  m_pCurMenu(nullptr)
{
}
 Menus()
Menus::~Menus ()
Definition at line 73 of file Menus.cpp.
{
}
Member Function Documentation
calcLedPos()
LedPos Menus::calcLedPos () [private]
checkInMenu()
bool Menus::checkInMenu ()
Definition at line 269 of file Menus.cpp.
{
  return m_menuState == MENU_STATE_IN_MENU;
}
References m_menuState, and MENU_STATE_IN_MENU.
checkOpen()
bool Menus::checkOpen ()
Definition at line 264 of file Menus.cpp.
{
  return m_menuState != MENU_STATE_NOT_OPEN && m_engine.button().releaseTime() > m_openTime;
}
References VortexEngine::button(), m_engine, m_menuState, m_openTime, MENU_STATE_NOT_OPEN, and Button::releaseTime().
cleanup()
void Menus::cleanup ()
Definition at line 84 of file Menus.cpp.
{
  if (m_pCurMenu) {
    delete m_pCurMenu;
    m_pCurMenu = nullptr;
  }
  m_menuState = MENU_STATE_NOT_OPEN;
  m_selection = 0;
  m_openTime = 0;
}
References m_menuState, m_openTime, m_pCurMenu, m_selection, and MENU_STATE_NOT_OPEN.
Referenced by VortexEngine::cleanup().
closeCurMenu()
void Menus::closeCurMenu () [private]
Definition at line 284 of file Menus.cpp.
{
  // delete the currently open menu object
  if (m_pCurMenu) {
    delete m_pCurMenu;
    m_pCurMenu = nullptr;
  }
  m_menuState = MENU_STATE_NOT_OPEN;
  m_selection = 0;
  // clear the leds
  m_engine.leds().clearAll();
}
References Leds::clearAll(), VortexEngine::leds(), m_engine, m_menuState, m_pCurMenu, m_selection, and MENU_STATE_NOT_OPEN.
Referenced by runCurMenu().
curMenu()
Menu * Menus::curMenu ()
Definition at line 274 of file Menus.cpp.
{
  return m_pCurMenu;
}
References m_pCurMenu.
curMenuID()
MenuEntryID Menus::curMenuID ()
Definition at line 279 of file Menus.cpp.
{
  return (MenuEntryID)m_selection;
}
References m_selection.
init()
bool Menus::init ()
Definition at line 77 of file Menus.cpp.
{
  m_menuState = MENU_STATE_NOT_OPEN;
  // sub-menus are initialized right before they run
  return true;
}
References m_menuState, and MENU_STATE_NOT_OPEN.
Referenced by VortexEngine::init().
openMenu()
bool Menus::openMenu (uint32_t index, bool advanced = false)
Definition at line 224 of file Menus.cpp.
{
  if (index >= NUM_MENUS) {
    return false;
  }
  m_selection = index;
  Menu *newMenu = menuList[m_selection].initMenu(m_engine, menuList[m_selection].color, advanced);
  if (!newMenu) {
    return false;
  }
  // initialiaze the new menu with the current mode
  if (!newMenu->init()) {
    DEBUG_LOGF("Failed to initialize %s menu", menuList[m_selection].menuName);
    // if the menu failed to init, don't open it
    delete newMenu;
    return false;
  }
  if (m_pCurMenu) {
    delete m_pCurMenu;
  }
  // assign the new menu
  m_pCurMenu = newMenu;
  // and the menus are open just in case
  // clear all the leds
  m_engine.leds().clearAll();
  m_menuState = MENU_STATE_IN_MENU;
  return true;
}
References Leds::clearAll(), DEBUG_LOGF, Menu::init(), MenuEntry::initMenu, VortexEngine::leds(), m_engine, m_menuState, m_pCurMenu, m_selection, MENU_STATE_IN_MENU, menuList, and NUM_MENUS.
Referenced by runMenuSelection().
openMenuSelection()
bool Menus::openMenuSelection ()
Definition at line 210 of file Menus.cpp.
{
  if (m_menuState != MENU_STATE_NOT_OPEN) {
    return false;
  }
  // save the time of when we open the menu so we can fill based on curtime from then
  m_openTime = m_engine.time().getCurtime();
  // open the menu
  m_menuState = MENU_STATE_MENU_SELECTION;
  // clear the leds
  m_engine.leds().clearAll();
  return true;
}
References Leds::clearAll(), Time::getCurtime(), VortexEngine::leds(), m_engine, m_menuState, m_openTime, MENU_STATE_MENU_SELECTION, MENU_STATE_NOT_OPEN, and VortexEngine::time().
Referenced by VortexEngine::runMainLogic().
run()
bool Menus::run ()
Definition at line 95 of file Menus.cpp.
{
  // if there are no menus, then we don't need to run
  switch (m_menuState) {
  case MENU_STATE_NOT_OPEN:
  default:
    // nothing to run
    return false;
  case MENU_STATE_MENU_SELECTION:
    return runMenuSelection();
  case MENU_STATE_IN_MENU:
    return runCurMenu();
  }
}
References m_menuState, MENU_STATE_IN_MENU, MENU_STATE_MENU_SELECTION, MENU_STATE_NOT_OPEN, runCurMenu(), and runMenuSelection().
Referenced by VortexEngine::runMainLogic().
runCurMenu()
bool Menus::runCurMenu () [private]
Definition at line 181 of file Menus.cpp.
{
  // if the menu run handler returns false that signals the
  // menu was closed by the user leaving the menu
  switch (m_pCurMenu->run()) {
  case Menu::MENU_QUIT:
    // close the current menu when run returns false
    closeCurMenu();
    // return false to let the modes play
    return false;
  case Menu::MENU_CONTINUE:
    // if Menu continue run the click handlers for the menu
    if (m_engine.button().onShortClick()) {
      m_pCurMenu->onShortClick();
    }
    if (m_engine.button().onLongClick()) {
      m_pCurMenu->onLongClick();
    }
    break;
  case Menu::MENU_SKIP:
    // dont run click handlers in this case
    // so the core menu class can handle them
    break;
  }
  // the opened menu and don't play modes
  return true;
}
References VortexEngine::button(), closeCurMenu(), m_engine, m_pCurMenu, Menu::MENU_CONTINUE, Menu::MENU_QUIT, Menu::MENU_SKIP, Menu::onLongClick(), Button::onLongClick(), Menu::onShortClick(), Button::onShortClick(), and Menu::run().
Referenced by run().
runMenuSelection()
bool Menus::runMenuSelection () [private]
Definition at line 110 of file Menus.cpp.
{
  if (m_engine.button().onShortClick()) {
    // otherwise increment selection and wrap around at num menus
    m_selection = (m_selection + 1) % NUM_MENUS;
    DEBUG_LOGF("Cyling to ring menu %u", m_selection);
    // reset the open time so that it starts again
    m_openTime = m_engine.time().getCurtime();
    // clear the leds
    m_engine.leds().clearAll();
    return true;
  }
  // clear the leds so it always fills instead of replacing
  m_engine.leds().clearAll();
  // timings for blink later
  uint8_t offtime = 200;
  uint8_t ontime = 200;
  // whether advanced menus are enabled
  bool advMenus = m_engine.modes().advancedMenusEnabled();
  // if the button was long pressed then select this menu, but we
  // need to check the presstime to ensure we don't catch the initial
  // release after opening the ringmenu
  if (m_engine.button().pressTime() >= m_openTime) {
    // whether to open advanced menus or not
    bool openAdv = (m_engine.button().holdDuration() > ADV_MENU_DURATION_TICKS) && advMenus;
    if (m_engine.button().onLongClick()) {
      // ringmenu is open so select the menu
      DEBUG_LOGF("Selected ringmenu %s", menuList[m_selection].menuName);
      // open the menu we have selected
      if (!openMenu(m_selection, openAdv)) {
        DEBUG_LOGF("Failed to initialize %s menu", menuList[m_selection].menuName);
        return false;
      }
      // display the newly opened menu
      return true;
    }
    // if holding down to select the menu option
    if (m_engine.button().isPressed() && openAdv) {
      // make it strobe aw yiss
      offtime = HYPERSTROBE_OFF_DURATION;
      ontime = HYPERSTROBE_ON_DURATION;
    }
  }
  // blink every even/odd of every pair
  for (Pair p = PAIR_FIRST; p < PAIR_COUNT; ++p) {
    if (pairEven(p) < LED_COUNT) {
      m_engine.leds().blinkIndex(pairEven(p), offtime, ontime, menuList[m_selection].color);
    }
    if (pairOdd(p) < LED_COUNT) {
      m_engine.leds().setIndex(pairOdd(p), menuList[m_selection].color);
      m_engine.leds().blinkIndex(pairOdd(p), offtime, ontime, RGB_OFF);
    }
  }
  // check if the advanced menus have been enabled
  if (m_engine.button().onConsecutivePresses(ADVANCED_MENU_CLICKS)) {
    // toggle the advanced menu
    m_engine.modes().setAdvancedMenus(!advMenus);
    // display a pink or red depending on whether the menu was enabled
    for (uint16_t i = 0; i < 2; ++i) {
      m_engine.leds().holdAll(advMenus ? RGB_RED : RGB_PINK);
    }
  }
  // show when the user selects a menu option
  showSelection(RGBColor(
    menuList[m_selection].color.red << 3,
    menuList[m_selection].color.green << 3,
    menuList[m_selection].color.blue << 3));
  // continue in the menu
  return true;
}
References ADV_MENU_DURATION_TICKS, ADVANCED_MENU_CLICKS, Modes::advancedMenusEnabled(), Leds::blinkIndex(), RGBColor::blue, VortexEngine::button(), Leds::clearAll(), MenuEntry::color, DEBUG_LOGF, Time::getCurtime(), RGBColor::green, Leds::holdAll(), Button::holdDuration(), HYPERSTROBE_OFF_DURATION, HYPERSTROBE_ON_DURATION, Button::isPressed(), LED_COUNT, VortexEngine::leds(), m_engine, m_openTime, m_selection, menuList, VortexEngine::modes(), NUM_MENUS, Button::onConsecutivePresses(), Button::onLongClick(), Button::onShortClick(), openMenu(), PAIR_COUNT, PAIR_FIRST, pairEven, pairOdd, Button::pressTime(), RGB_OFF, RGB_PINK, RGB_RED, Modes::setAdvancedMenus(), Leds::setIndex(), showSelection(), and VortexEngine::time().
Referenced by run().
showSelection()
void Menus::showSelection (RGBColor colval = RGB_WHITE5)
Definition at line 253 of file Menus.cpp.
{
  // blink the tip led white for 150ms when the short
  // click threshold has been surpassed
  if (m_engine.button().isPressed() &&
    m_engine.button().holdDuration() > SHORT_CLICK_THRESHOLD_TICKS &&
    m_engine.button().holdDuration() < (SHORT_CLICK_THRESHOLD_TICKS + MS_TO_TICKS(250))) {
    m_engine.leds().setAll(colval);
  }
}
References VortexEngine::button(), Button::holdDuration(), Button::isPressed(), VortexEngine::leds(), m_engine, MS_TO_TICKS, Leds::setAll(), and SHORT_CLICK_THRESHOLD_TICKS.
Referenced by ColorSelect::run(), GlobalBrightness::run(), PatternSelect::run(), Randomizer::run(), runMenuSelection(), Menu::showBulbSelection(), and Randomizer::showRandomizationSelect().
Member Data Documentation
m_engine
VortexEngine& Menus::m_engine [private]
Definition at line 79 of file Menus.h.
Referenced by checkOpen(), closeCurMenu(), openMenu(), openMenuSelection(), runCurMenu(), runMenuSelection(), and showSelection().
m_menuState
MenuState Menus::m_menuState [private]
Definition at line 93 of file Menus.h.
Referenced by checkInMenu(), checkOpen(), cleanup(), closeCurMenu(), init(), openMenu(), openMenuSelection(), and run().
m_openTime
uint32_t Menus::m_openTime [private]
Definition at line 98 of file Menus.h.
Referenced by checkOpen(), cleanup(), openMenuSelection(), and runMenuSelection().
m_pCurMenu
Menu* Menus::m_pCurMenu [private]
Definition at line 100 of file Menus.h.
Referenced by cleanup(), closeCurMenu(), curMenu(), openMenu(), and runCurMenu().
m_selection
uint8_t Menus::m_selection [private]
Definition at line 96 of file Menus.h.
Referenced by cleanup(), closeCurMenu(), curMenuID(), openMenu(), and runMenuSelection().
The documentation for this class was generated from the following files:
VortexEngine/src/Menus/Menus.h
VortexEngine/src/Menus/Menus.cpp