HueShiftPattern Class Reference
#include <HueShiftPattern.h>
Public Member Functions
HueShiftPattern (VortexEngine &engine, const PatternArgs &args)
virtual ~HueShiftPattern ()
virtual void init () override
virtual void play () override
Private Attributes
uint8_t m_blinkOnDuration
uint8_t m_blinkOffDuration
uint8_t m_blendDelay
uint8_t m_delayCounter
Timer m_blinkTimer
HSVColor m_cur
HSVColor m_next
Additional Inherited Members
Detailed Description
Definition at line 9 of file HueShiftPattern.h.
Constructor & Destructor Documentation
HueShiftPattern()
HueShiftPattern::HueShiftPattern (VortexEngine & engine, const PatternArgs & args)
Definition at line 10 of file HueShiftPattern.cpp.
                                                                              :
  MultiLedPattern(engine, args),
  m_blinkOnDuration(0),
  m_blinkOffDuration(0),
  m_blendDelay(0),
  m_delayCounter(0),
  m_blinkTimer(engine),
  m_cur(0),
  m_next(0)
{
  m_patternID = PATTERN_HUE_SCROLL;
  REGISTER_ARG(m_blinkOnDuration);
  REGISTER_ARG(m_blinkOffDuration);
  REGISTER_ARG(m_blendDelay);
  setArgs(args);
}
References m_blendDelay, m_blinkOffDuration, m_blinkOnDuration, Pattern::m_patternID, PATTERN_HUE_SCROLL, REGISTER_ARG, and Pattern::setArgs().
 HueShiftPattern()
HueShiftPattern::~HueShiftPattern () [virtual]
Definition at line 27 of file HueShiftPattern.cpp.
{
}
Member Function Documentation
init()
void HueShiftPattern::init () [override], [virtual]
Reimplemented from MultiLedPattern.
Definition at line 32 of file HueShiftPattern.cpp.
{
  MultiLedPattern::init();
  m_cur = m_colorset.getNext();
  m_next = m_colorset.getNext();
  // reset the blink timer entirely
  m_blinkTimer.reset();
  // dops timing
  m_blinkTimer.addAlarm(m_blinkOnDuration);
  m_blinkTimer.addAlarm(m_blinkOffDuration);
  // start the blink timer from the next frame
  m_blinkTimer.start();
}
References Timer::addAlarm(), Colorset::getNext(), MultiLedPattern::init(), m_blinkOffDuration, m_blinkOnDuration, m_blinkTimer, Pattern::m_colorset, m_cur, m_next, Timer::reset(), and Timer::start().
play()
void HueShiftPattern::play () [override], [virtual]
Implements Pattern.
Definition at line 47 of file HueShiftPattern.cpp.
{
  switch (m_blinkTimer.alarm()) {
  case 0: // turn on the leds for given mapping
    break;
  case 1: // turn off the leds
    m_engine.leds().clearAll();
  case -1: // just break and still run post-step
    return;
  }
  // if the current hue has reached the next hue
  if (m_cur.hue == m_next.hue) {
    // copy over the sat/val
    m_cur = m_next;
    // get the next color and convert to hsv
    m_next = m_colorset.getNext();
  }
  // check which direction is closer for the next hue
  // tbh idk really how this even works anymore but it does
  int sign = ((((m_next.hue + 255) - m_cur.hue) % 256) <= 128) ? 1 : -1;
  // move hue in the direction of next hue at chosen speed
  // NOTE: if the speed isn't a multiple of the hue values then
  // it will cause oscillation around the target hue
  // because it will never reach the target hue and
  // always over/under shoot
  // only increment every blendDelay times
  ++m_delayCounter;
  if (m_delayCounter >= m_blendDelay) {
    m_delayCounter = 0;
    m_cur.hue += sign;
  }
  HSVColor showColor = HSVColor(m_cur.hue, 255, 255);
  // set the target led with the current HSV color
  for (LedPos pos = LED_FIRST; pos < LED_COUNT; ++pos) {
    m_engine.leds().setIndex(pos, hsv_to_rgb_generic(showColor));
    showColor.hue = (showColor.hue + 5) % 256;
  }
}
References Timer::alarm(), Leds::clearAll(), Colorset::getNext(), hsv_to_rgb_generic(), HSVColor::hue, LED_COUNT, LED_FIRST, VortexEngine::leds(), m_blendDelay, m_blinkTimer, Pattern::m_colorset, m_cur, m_delayCounter, Pattern::m_engine, m_next, and Leds::setIndex().
Member Data Documentation
m_blendDelay
uint8_t HueShiftPattern::m_blendDelay [private]
Definition at line 24 of file HueShiftPattern.h.
Referenced by HueShiftPattern(), and play().
m_blinkOffDuration
uint8_t HueShiftPattern::m_blinkOffDuration [private]
Definition at line 23 of file HueShiftPattern.h.
Referenced by HueShiftPattern(), and init().
m_blinkOnDuration
uint8_t HueShiftPattern::m_blinkOnDuration [private]
Definition at line 22 of file HueShiftPattern.h.
Referenced by HueShiftPattern(), and init().
m_blinkTimer
Timer HueShiftPattern::m_blinkTimer [private]
Definition at line 27 of file HueShiftPattern.h.
Referenced by init(), and play().
m_cur
HSVColor HueShiftPattern::m_cur [private]
Definition at line 30 of file HueShiftPattern.h.
Referenced by init(), and play().
m_delayCounter
uint8_t HueShiftPattern::m_delayCounter [private]
Definition at line 25 of file HueShiftPattern.h.
Referenced by play().
m_next
HSVColor HueShiftPattern::m_next [private]
Definition at line 31 of file HueShiftPattern.h.
Referenced by init(), and play().
The documentation for this class was generated from the following files:
VortexEngine/src/Patterns/Multi/HueShiftPattern.h
VortexEngine/src/Patterns/Multi/HueShiftPattern.cpp