VortexWipePattern Class Reference
#include <VortexWipePattern.h>
Public Member Functions
VortexWipePattern (VortexEngine &engine, const PatternArgs &args)
virtual ~VortexWipePattern ()
virtual void init () override
Protected Member Functions
virtual void blinkOn () override
virtual void poststep () override
Private Attributes
uint8_t m_progress
Static Private Attributes
static const LedPos ledStepPositions []
Additional Inherited Members
Detailed Description
Definition at line 8 of file VortexWipePattern.h.
Constructor & Destructor Documentation
VortexWipePattern()
VortexWipePattern::VortexWipePattern (VortexEngine & engine, const PatternArgs & args)
Definition at line 24 of file VortexWipePattern.cpp.
                                                                                  :
  BlinkStepPattern(engine, args),
  m_progress(0)
{
  m_patternID = PATTERN_VORTEXWIPE;
  setArgs(args);
}
References Pattern::m_patternID, PATTERN_VORTEXWIPE, and Pattern::setArgs().
 VortexWipePattern()
VortexWipePattern::~VortexWipePattern () [virtual]
Definition at line 32 of file VortexWipePattern.cpp.
{
}
Member Function Documentation
blinkOn()
void VortexWipePattern::blinkOn () [override], [protected], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 46 of file VortexWipePattern.cpp.
{
  for (int index = 0; index < m_progress; ++index) {
    m_engine.leds().setIndex(ledStepPositions[index], m_colorset.peekNext());
  }
  for (int index = m_progress; index < LED_COUNT; ++index) {
    m_engine.leds().setIndex(ledStepPositions[index], m_colorset.cur());
  }
}
References Colorset::cur(), LED_COUNT, VortexEngine::leds(), ledStepPositions, Pattern::m_colorset, Pattern::m_engine, m_progress, Colorset::peekNext(), and Leds::setIndex().
init()
void VortexWipePattern::init () [override], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 37 of file VortexWipePattern.cpp.
{
  BlinkStepPattern::init();
  // reset progress
  m_progress = 0;
  // start colorset at index 0 so cur() works
  m_colorset.setCurIndex(0);
}
References BlinkStepPattern::init(), Pattern::m_colorset, m_progress, and Colorset::setCurIndex().
poststep()
void VortexWipePattern::poststep () [override], [protected], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 56 of file VortexWipePattern.cpp.
{
  m_progress = (m_progress + 1) % LED_COUNT;
  if (m_progress == 0) {
    m_colorset.getNext();
  }
}
References Colorset::getNext(), LED_COUNT, Pattern::m_colorset, and m_progress.
Member Data Documentation
ledStepPositions
const LedPos VortexWipePattern::ledStepPositions [static], [private]
Initial value:
= {
  LED_9,
  LED_7,
  LED_5,
  LED_3,
  LED_1,
  LED_0,
  LED_2,
  LED_4,
  LED_6,
  LED_8
}
Definition at line 23 of file VortexWipePattern.h.
Referenced by blinkOn().
m_progress
uint8_t VortexWipePattern::m_progress [private]
Definition at line 26 of file VortexWipePattern.h.
Referenced by blinkOn(), init(), and poststep().
The documentation for this class was generated from the following files:
VortexEngine/src/Patterns/Multi/VortexWipePattern.h
VortexEngine/src/Patterns/Multi/VortexWipePattern.cpp