Timer Class Reference
#include <Timer.h>
Public Member Functions
Timer (VortexEngine &engine)
~Timer ()
void init (uint8_t flags=TIMER_FLAGS_NONE, uint8_t alarm1=0, uint8_t alarm2=0, uint8_t alarm3=0, uint8_t alarm4=0)
AlarmID addAlarm (uint32_t interval)
void restart (uint32_t offset=0)
void start (uint32_t offset=0)
void reset ()
bool onStart () const
bool onEnd () const
AlarmID alarm ()
uint32_t numAlarms () const
uint32_t curAlarm () const
uint32_t startTime () const
Private Member Functions
uint32_t getStartTime () const
void setStartTime (uint32_t)
Private Attributes
VortexEngine & m_engine
uint32_t * m_alarms
uint8_t m_numAlarms
AlarmID m_curAlarm
uint32_t m_startTime
Detailed Description
Definition at line 27 of file Timer.h.
Constructor & Destructor Documentation
Timer()
Timer::Timer (VortexEngine & engine)
Definition at line 10 of file Timer.cpp.
                                 :
  m_engine(engine),
  m_alarms(nullptr),
  m_numAlarms(0),
  m_curAlarm(0),
  m_startTime(0)
#ifdef VORTEX_LIB
  , m_simStartTime(0)
#endif
{
}
 Timer()
Timer::~Timer ()
Definition at line 22 of file Timer.cpp.
{
  if (m_alarms) {
    vfree(m_alarms);
    m_alarms = nullptr;
  }
}
References m_alarms, and vfree.
Member Function Documentation
addAlarm()
AlarmID Timer::addAlarm (uint32_t interval)
Definition at line 40 of file Timer.cpp.
{
  void *temp = vrealloc(m_alarms, sizeof(uint32_t) * (m_numAlarms + 1));
  if (!temp) {
    ERROR_OUT_OF_MEMORY();
    return false;
  }
  m_alarms = (uint32_t *)temp;
  m_alarms[m_numAlarms] = interval;
  return m_numAlarms++;
}
References ERROR_OUT_OF_MEMORY, m_alarms, m_numAlarms, and vrealloc.
Referenced by PulsishPattern::init(), LighthousePattern::init(), BackStrobePattern::init(), ZigzagPattern::init(), HueShiftPattern::init(), DripMorphPattern::init(), BlinkStepPattern::init(), SequencedPattern::init(), and init().
alarm()
AlarmID Timer::alarm ()
Definition at line 112 of file Timer.cpp.
{
  if (!m_numAlarms || !m_alarms || m_curAlarm == ALARM_NONE) {
    return ALARM_NONE;
  }
  uint32_t now = m_engine.time().getCurtime();
  // time since start (forward or backwards)
  int32_t timeDiff = (int32_t)(int64_t)(now - getStartTime());
  if (timeDiff < 0) {
    return ALARM_NONE;
  }
  // if no time passed it's first alarm that is starting
  if (timeDiff == 0) {
    return 0;
  }
  uint32_t alarmTime = m_alarms[m_curAlarm];
  // if the current alarm duration is not a multiple of the current tick
  if (alarmTime && (timeDiff % alarmTime) != 0) {
    // then the alarm was not hit
    return ALARM_NONE;
  }
  // update the start time of the timer
  setStartTime(now);
  // increment current alarm then return that id
  m_curAlarm = (AlarmID)((m_curAlarm + 1) % m_numAlarms);
  return m_curAlarm;
}
References ALARM_NONE, Time::getCurtime(), getStartTime(), m_alarms, m_curAlarm, m_engine, m_numAlarms, setStartTime(), and VortexEngine::time().
Referenced by BasicPattern::play(), PulsishPattern::play(), LighthousePattern::play(), BackStrobePattern::play(), ZigzagPattern::play(), HueShiftPattern::play(), DripMorphPattern::play(), BlinkStepPattern::play(), and SequencedPattern::play().
curAlarm()
uint32_t Timer::curAlarm () const [inline]
Definition at line 64 of file Timer.h.
{ return m_curAlarm; }
References m_curAlarm.
getStartTime()
uint32_t Timer::getStartTime () const [private]
Definition at line 140 of file Timer.cpp.
{
#ifdef VORTEX_LIB
  // timers use a different 'start time' tracker in simulations so that
  // the startTime remains unchanged when the simulation ends
  if (m_engine.time().isSimulation() && m_simStartTime) {
    return m_simStartTime;
  }
#endif
  return m_startTime;
}
References m_engine, m_startTime, and VortexEngine::time().
Referenced by alarm(), onEnd(), and onStart().
init()
void Timer::init (uint8_t flags = TIMER_FLAGS_NONE, uint8_t alarm1 = 0, uint8_t alarm2 = 0, uint8_t alarm3 = 0, uint8_t alarm4 = 0)
Definition at line 30 of file Timer.cpp.
{
  reset();
  if ((flags & TIMER_ALARM_MASK) >= TIMER_1_ALARM) addAlarm(alarm1);
  if ((flags & TIMER_ALARM_MASK) >= TIMER_2_ALARMS) addAlarm(alarm2);
  if ((flags & TIMER_ALARM_MASK) >= TIMER_3_ALARMS) addAlarm(alarm3);
  if ((flags & TIMER_ALARM_MASK) >= TIMER_4_ALARMS) addAlarm(alarm4);
  if ((flags & TIMER_START) != 0) start();
}
References addAlarm(), reset(), start(), TIMER_1_ALARM, TIMER_2_ALARMS, TIMER_3_ALARMS, TIMER_4_ALARMS, TIMER_ALARM_MASK, and TIMER_START.
Referenced by BasicPattern::nextState().
numAlarms()
uint32_t Timer::numAlarms () const [inline]
Definition at line 63 of file Timer.h.
{ return m_numAlarms; }
References m_numAlarms.
onEnd()
bool Timer::onEnd () const
Definition at line 88 of file Timer.cpp.
{
  if (!m_alarms || !m_numAlarms) {
    return false;
  }
  // the tick for when this alarm triggers
  uint32_t alarmTime = m_alarms[m_curAlarm];
  if (alarmTime <= 1) {
    return true;
  }
  // grab curTime
  uint32_t now = m_engine.time().getCurtime();
  // get the start time of the timer
  uint32_t startTime = getStartTime();
  // time since start (forward or backwards)
  int32_t timeDiff = (int32_t)(int64_t)(now - startTime);
  // if no time since start then this definitely isn't the end
  if (!timeDiff) {
    return false;
  }
  // check if timediff is multiple of last tick in alarm
  return ((timeDiff % (alarmTime - 1)) == 0);
}
References Time::getCurtime(), getStartTime(), m_alarms, m_curAlarm, m_engine, m_numAlarms, startTime(), and VortexEngine::time().
onStart()
bool Timer::onStart () const
Definition at line 80 of file Timer.cpp.
{
  if (m_engine.time().getCurtime() == getStartTime() && m_curAlarm == 0) {
    return true;
  }
  return false;
}
References Time::getCurtime(), getStartTime(), m_curAlarm, m_engine, and VortexEngine::time().
reset()
void Timer::reset ()
Definition at line 68 of file Timer.cpp.
{
  vfree(m_alarms);
  m_alarms = nullptr;
  m_numAlarms = 0;
  m_curAlarm = 0;
  m_startTime = 0;
#ifdef VORTEX_LIB
  m_simStartTime = 0;
#endif
}
References m_alarms, m_curAlarm, m_numAlarms, m_startTime, and vfree.
Referenced by PulsishPattern::init(), LighthousePattern::init(), BackStrobePattern::init(), ZigzagPattern::init(), HueShiftPattern::init(), DripMorphPattern::init(), BlinkStepPattern::init(), SequencedPattern::init(), and init().
restart()
void Timer::restart (uint32_t offset = 0)
Definition at line 52 of file Timer.cpp.
{
  start(offset);
  // reset the current alarm
  m_curAlarm = 0;
}
References m_curAlarm, and start().
setStartTime()
void Timer::setStartTime (uint32_t tick) [private]
Definition at line 152 of file Timer.cpp.
{
#ifdef VORTEX_LIB
  // if this timer is running in a simulation then don't actually update
  // the starttime, instead update the simulation start time so that when
  // the simulation ends the startTime will not have changed at all
  if (m_engine.time().isSimulation()) {
    // move the sim start time
    m_simStartTime = tick;
    return;
  }
#endif
  // move the start time forward
  m_startTime = tick;
}
References m_engine, m_startTime, and VortexEngine::time().
Referenced by alarm().
start()
void Timer::start (uint32_t offset = 0)
Definition at line 59 of file Timer.cpp.
{
  // reset the start time
  m_startTime = m_engine.time().getCurtime() + offset;
#ifdef VORTEX_LIB
  m_simStartTime = m_startTime;
#endif
}
References Time::getCurtime(), m_engine, m_startTime, and VortexEngine::time().
Referenced by PulsishPattern::init(), LighthousePattern::init(), BackStrobePattern::init(), ZigzagPattern::init(), HueShiftPattern::init(), DripMorphPattern::init(), BlinkStepPattern::init(), SequencedPattern::init(), init(), and restart().
startTime()
uint32_t Timer::startTime () const [inline]
Definition at line 67 of file Timer.h.
{ return m_startTime; }
References m_startTime.
Referenced by onEnd().
Member Data Documentation
m_alarms
uint32_t* Timer::m_alarms [private]
Definition at line 82 of file Timer.h.
Referenced by addAlarm(), alarm(), onEnd(), reset(), and ~Timer().
m_curAlarm
AlarmID Timer::m_curAlarm [private]
Definition at line 85 of file Timer.h.
Referenced by alarm(), curAlarm(), onEnd(), onStart(), reset(), and restart().
m_engine
VortexEngine& Timer::m_engine [private]
Definition at line 75 of file Timer.h.
Referenced by alarm(), getStartTime(), onEnd(), onStart(), setStartTime(), and start().
m_numAlarms
uint8_t Timer::m_numAlarms [private]
Definition at line 83 of file Timer.h.
Referenced by addAlarm(), alarm(), numAlarms(), onEnd(), and reset().
m_startTime
uint32_t Timer::m_startTime [private]
Definition at line 87 of file Timer.h.
Referenced by getStartTime(), reset(), setStartTime(), start(), and startTime().
The documentation for this class was generated from the following files:
VortexEngine/src/Time/Timer.h
VortexEngine/src/Time/Timer.cpp