SequencedPattern Class Reference
#include <SequencedPattern.h>
Public Member Functions
virtual ~SequencedPattern ()
virtual void init () override
virtual void play () override
void bindSequence (const Sequence &sequence)
Protected Member Functions
SequencedPattern (VortexEngine &engine, const PatternArgs &args)
SequencedPattern (VortexEngine &engine, const PatternArgs &args, const Sequence &sequence)
void playSequenceStep (const SequenceStep &step)
Protected Attributes
Sequence m_sequence
uint8_t m_curSequence
Timer m_timer
Detailed Description
Definition at line 13 of file SequencedPattern.h.
Constructor & Destructor Documentation
SequencedPattern() [1/2]
SequencedPattern::SequencedPattern (VortexEngine & engine, const PatternArgs & args) [protected]
Definition at line 14 of file SequencedPattern.cpp.
                                                                                :
  CompoundPattern(engine, args),
  m_sequence(engine),
  m_curSequence(0),
  m_timer(engine)
{
  // SequencedPattern is an abstract class it cannot be directly
  // instantiated so we do not need to assign a pattern id
}
SequencedPattern() [2/2]
SequencedPattern::SequencedPattern (VortexEngine & engine, const PatternArgs & args, const Sequence & sequence) [protected]
Definition at line 24 of file SequencedPattern.cpp.
                                                                                                          :
  CompoundPattern(engine, args),
  m_sequence(sequence),
  m_curSequence(0),
  m_timer(engine)
{
  // SequencedPattern is an abstract class it cannot be directly
  // instantiated so we do not need to assign a pattern id
}
 SequencedPattern()
SequencedPattern::~SequencedPattern () [virtual]
Definition at line 34 of file SequencedPattern.cpp.
{
}
Member Function Documentation
bindSequence()
void SequencedPattern::bindSequence (const Sequence & sequence)
Definition at line 111 of file SequencedPattern.cpp.
{
  m_sequence = sequence;
}
References m_sequence.
init()
void SequencedPattern::init () [override], [virtual]
Reimplemented from CompoundPattern.
Definition at line 39 of file SequencedPattern.cpp.
{
  CompoundPattern::init();
  // start the sequence at 0
  m_curSequence = 0;
  m_timer.reset();
  // create an alarm for each duration in the sequence
  for (uint8_t i = 0; i < m_sequence.numSteps(); ++i) {
    m_timer.addAlarm(m_sequence[i].m_duration);
  }
  m_timer.start();
  // Play first sequence step in init, if there is one
  if (m_sequence.numSteps() > 0) {
    playSequenceStep(m_sequence[0]);
  }
}
References Timer::addAlarm(), CompoundPattern::init(), m_curSequence, m_sequence, m_timer, Sequence::numSteps(), playSequenceStep(), Timer::reset(), and Timer::start().
play()
void SequencedPattern::play () [override], [virtual]
Reimplemented from CompoundPattern.
Definition at line 61 of file SequencedPattern.cpp.
{
  if (m_timer.alarm() != -1) {
    m_curSequence = (m_curSequence + 1) % m_sequence.numSteps();
  }
  // only index the sequence if the current sequence index is valid
  if (m_curSequence < m_sequence.numSteps()) {
    // play the sequence step
    playSequenceStep(m_sequence[m_curSequence]);
  }
}
References Timer::alarm(), m_curSequence, m_sequence, m_timer, Sequence::numSteps(), and playSequenceStep().
playSequenceStep()
void SequencedPattern::playSequenceStep (const SequenceStep & step) [protected]
Definition at line 73 of file SequencedPattern.cpp.
{
  for (LedPos pos = LED_FIRST; pos < LED_COUNT; ++pos) {
    // the current initialized pattern for this LED
    SingleLedPattern *curPat = m_ledPatterns[pos];
    // the intended pattern ID for this LED on this step
    PatternID stepPattern = step.m_patternMap[pos];
    // the actual colorset being used might be the pattern's colorset
    const Colorset *curSet = &m_colorset;
    if (step.m_colorsetMap.m_colorsets.size() > pos && step.m_colorsetMap[pos].numColors() > 0) {
      // or it might be the steps' colorset if it's not empty
      curSet = &step.m_colorsetMap[pos];
    }
    // if there's no pattern, or pattern is wrong colorset or pattern ID
    if (!curPat || !curPat->getColorset().equals(curSet) || curPat->getPatternID() != stepPattern) {
      // delete any existing pattern and re-create it
      delete m_ledPatterns[pos];
      // create whichever pattern this step is (maybe PATTERN_NONE)
      curPat = m_ledPatterns[pos] = m_engine.patternBuilder().makeSingle(stepPattern);
      // if a pattern was created then bind and init it
      if (curPat) {
        curPat->bind(pos);
        curPat->setColorset(*curSet);
        curPat->init();
      }
    }
    // if there's no pattern set, or the intended pattern of this step is NONE
    if (!curPat || stepPattern == PATTERN_NONE) {
      // clear the LED and don't play the pattern
      m_engine.leds().clearIndex(pos);
      continue;
    }
    // otherwise play the pattern on this index
    curPat->play();
  }
}
References Pattern::bind(), Leds::clearIndex(), Colorset::equals(), Pattern::getColorset(), Pattern::getPatternID(), SingleLedPattern::init(), LED_COUNT, LED_FIRST, VortexEngine::leds(), Pattern::m_colorset, SequenceStep::m_colorsetMap, ColorsetMap::m_colorsets, Pattern::m_engine, CompoundPattern::m_ledPatterns, SequenceStep::m_patternMap, PatternBuilder::makeSingle(), PATTERN_NONE, VortexEngine::patternBuilder(), Pattern::play(), and Pattern::setColorset().
Referenced by init(), and play().
Member Data Documentation
m_curSequence
uint8_t SequencedPattern::m_curSequence [protected]
Definition at line 41 of file SequencedPattern.h.
Referenced by init(), and play().
m_sequence
Sequence SequencedPattern::m_sequence [protected]
Definition at line 38 of file SequencedPattern.h.
Referenced by bindSequence(), ChaserPattern::ChaserPattern(), init(), and play().
m_timer
Timer SequencedPattern::m_timer [protected]
Definition at line 42 of file SequencedPattern.h.
Referenced by init(), and play().
The documentation for this class was generated from the following files:
VortexEngine/src/Patterns/Multi/Sequencer/SequencedPattern.h
VortexEngine/src/Patterns/Multi/Sequencer/SequencedPattern.cpp