SnowballPattern Class Reference
#include <SnowballPattern.h>
Public Member Functions
SnowballPattern (VortexEngine &engine, const PatternArgs &args)
virtual ~SnowballPattern ()
virtual void init () override
Protected Member Functions
virtual void blinkOn () override
virtual void poststep () override
Private Attributes
uint8_t m_progress
Additional Inherited Members
Detailed Description
Definition at line 5 of file SnowballPattern.h.
Constructor & Destructor Documentation
SnowballPattern()
SnowballPattern::SnowballPattern (VortexEngine & engine, const PatternArgs & args)
Definition at line 9 of file SnowballPattern.cpp.
                                                                              :
  BlinkStepPattern(engine, args),
  m_progress()
{
  m_patternID = PATTERN_SNOWBALL;
  setArgs(args);
}
References Pattern::m_patternID, PATTERN_SNOWBALL, and Pattern::setArgs().
 SnowballPattern()
SnowballPattern::~SnowballPattern () [virtual]
Definition at line 17 of file SnowballPattern.cpp.
{
}
Member Function Documentation
blinkOn()
void SnowballPattern::blinkOn () [override], [protected], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 30 of file SnowballPattern.cpp.
{
  m_engine.leds().setAll(m_colorset.get(0));
  for (int body = 0; body < WORM_SIZE; ++body) {
    if (body + m_progress < LED_COUNT) {
      m_engine.leds().setIndex((LedPos)(body + m_progress), m_colorset.cur());
    } else {
      RGBColor col = m_colorset.peekNext();
      if (m_colorset.curIndex() == m_colorset.numColors() - 1) {
        col = m_colorset.peek(2);
      }
      m_engine.leds().setIndex((LedPos)((body + m_progress) % LED_COUNT), col);
    }
  }
}
References Colorset::cur(), Colorset::curIndex(), Colorset::get(), LED_COUNT, VortexEngine::leds(), Pattern::m_colorset, Pattern::m_engine, m_progress, Colorset::numColors(), Colorset::peek(), Colorset::peekNext(), Leds::setAll(), Leds::setIndex(), and WORM_SIZE.
init()
void SnowballPattern::init () [override], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 22 of file SnowballPattern.cpp.
{
  BlinkStepPattern::init();
  // start at index 1
  m_colorset.setCurIndex(1);
}
References BlinkStepPattern::init(), Pattern::m_colorset, and Colorset::setCurIndex().
poststep()
void SnowballPattern::poststep () [override], [protected], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 46 of file SnowballPattern.cpp.
{
  m_colorset.skip();
  if (m_colorset.curIndex() == 0) {
    m_progress = (m_progress + 1) % LED_COUNT;
    m_colorset.skip();
  }
}
References Colorset::curIndex(), LED_COUNT, Pattern::m_colorset, m_progress, and Colorset::skip().
Member Data Documentation
m_progress
uint8_t SnowballPattern::m_progress [private]
Definition at line 20 of file SnowballPattern.h.
Referenced by blinkOn(), and poststep().
The documentation for this class was generated from the following files:
VortexEngine/src/Patterns/Multi/SnowballPattern.h
VortexEngine/src/Patterns/Multi/SnowballPattern.cpp