CompoundPattern Class Reference
#include <CompoundPattern.h>
Public Member Functions
virtual ~CompoundPattern ()
virtual void init () override
virtual void play () override
Protected Member Functions
CompoundPattern (VortexEngine &engine, const PatternArgs &args)
void setPatternAt (LedPos pos, SingleLedPattern *pat, const Colorset *set=nullptr)
void setPatternAt (LedPos pos, PatternID id, const PatternArgs *args=nullptr, const Colorset *set=nullptr)
void clearPatterns ()
void setEvensOdds (PatternID tipPattern, PatternID topPattern, const PatternArgs *tipArgs=nullptr, const PatternArgs *topArgs=nullptr)
Protected Attributes
std::vector< SingleLedPattern * > m_ledPatterns
Detailed Description
Definition at line 12 of file CompoundPattern.h.
Constructor & Destructor Documentation
CompoundPattern()
CompoundPattern::CompoundPattern (VortexEngine & engine, const PatternArgs & args) [protected]
Definition at line 9 of file CompoundPattern.cpp.
                                                                              :
  MultiLedPattern(engine, args),
  m_ledPatterns()
{
  // Hybrid is an abstract class it cannot be directly
  // instantiated so we do not need to assign a pattern id
}
 CompoundPattern()
CompoundPattern::~CompoundPattern () [virtual]
Definition at line 17 of file CompoundPattern.cpp.
{
  // clean up all the sub patterns
  for (LedPos pos = LED_FIRST; pos <= LED_LAST; pos++) {
    if (m_ledPatterns[pos]) {
      delete m_ledPatterns[pos];
      m_ledPatterns[pos] = nullptr;
    }
  }
}
References LED_FIRST, LED_LAST, and m_ledPatterns.
Member Function Documentation
clearPatterns()
void CompoundPattern::clearPatterns () [protected]
Definition at line 50 of file CompoundPattern.cpp.
{
  for (LedPos pos = LED_FIRST; pos <= LED_LAST; pos++) {
    if (!m_ledPatterns[pos]) {
      continue;
    }
    delete m_ledPatterns[pos];
    m_ledPatterns[pos] = nullptr;
  }
}
References LED_FIRST, LED_LAST, and m_ledPatterns.
init()
void CompoundPattern::init () [override], [virtual]
Reimplemented from MultiLedPattern.
Reimplemented in SequencedPattern, and BackStrobePattern.
Definition at line 29 of file CompoundPattern.cpp.
{
  MultiLedPattern::init();
  // resize the pattern list to the number of leds
  m_ledPatterns.resize(LED_COUNT);
}
References MultiLedPattern::init(), LED_COUNT, and m_ledPatterns.
Referenced by BackStrobePattern::init(), and SequencedPattern::init().
play()
void CompoundPattern::play () [override], [virtual]
Implements Pattern.
Reimplemented in SequencedPattern, and BackStrobePattern.
Definition at line 38 of file CompoundPattern.cpp.
{
  for (LedPos pos = LED_FIRST; pos <= LED_LAST; pos++) {
    SingleLedPattern *pat = m_ledPatterns[pos];
    if (!pat) {
      // should never happen, but just in case
      continue;
    }
    pat->play();
  }
}
References LED_FIRST, LED_LAST, m_ledPatterns, and Pattern::play().
Referenced by BackStrobePattern::play().
setEvensOdds()
void CompoundPattern::setEvensOdds (PatternID tipPattern, PatternID topPattern, const PatternArgs * tipArgs = nullptr, const PatternArgs * topArgs = nullptr) [protected]
Definition at line 87 of file CompoundPattern.cpp.
{
  // Set the evenPattern on all evens and oddPattern on all odds
  for (LedPos p = LED_FIRST; p <= LED_LAST; p++) {
    const PatternArgs *args = isEven(p) ? evenArgs : oddArgs;
    PatternID id = isEven(p) ? evenPattern : oddPattern;
    setPatternAt(p, m_engine.patternBuilder().makeSingle(id, args));
  }
}
References isEven, LED_FIRST, LED_LAST, Pattern::m_engine, PatternBuilder::makeSingle(), VortexEngine::patternBuilder(), and setPatternAt().
Referenced by BackStrobePattern::init(), and BackStrobePattern::play().
setPatternAt() [1/2]
void CompoundPattern::setPatternAt (LedPos pos, PatternID id, const PatternArgs * args = nullptr, const Colorset * set = nullptr) [protected]
Definition at line 78 of file CompoundPattern.cpp.
{
  if (pos >= LED_COUNT) {
    return;
  }
  setPatternAt(pos, m_engine.patternBuilder().makeSingle(id, args), set);
}
References LED_COUNT, Pattern::m_engine, PatternBuilder::makeSingle(), VortexEngine::patternBuilder(), and setPatternAt().
setPatternAt() [2/2]
void CompoundPattern::setPatternAt (LedPos pos, SingleLedPattern * pat, const Colorset * set = nullptr) [protected]
Definition at line 61 of file CompoundPattern.cpp.
{
  if (!pat || pos >= LED_COUNT) {
    return;
  }
  pat->bind(pos);
  pat->setColorset(set ? *set : m_colorset);
  pat->init();
  // handle re-initialization and prevent leaks
  if (m_ledPatterns[pos]) {
    delete m_ledPatterns[pos];
  }
  // store the pattern for the given led
  m_ledPatterns[pos] = pat;
}
References Pattern::bind(), SingleLedPattern::init(), LED_COUNT, Pattern::m_colorset, m_ledPatterns, and Pattern::setColorset().
Referenced by setEvensOdds(), and setPatternAt().
Member Data Documentation
m_ledPatterns
std::vector<SingleLedPattern *> CompoundPattern::m_ledPatterns [protected]
Definition at line 38 of file CompoundPattern.h.
Referenced by clearPatterns(), init(), play(), SequencedPattern::playSequenceStep(), setPatternAt(), and ~CompoundPattern().
The documentation for this class was generated from the following files:
VortexEngine/src/Patterns/Multi/CompoundPattern.h
VortexEngine/src/Patterns/Multi/CompoundPattern.cpp