Time Class Reference
#include <TimeControl.h>
Public Member Functions
Time (VortexEngine &engine)
~Time ()
bool init ()
void cleanup ()
void tickClock ()
uint32_t getCurtime ()
uint32_t getRealCurtime ()
void setTickrate (uint32_t tickrate=0)
uint32_t getTickrate ()
uint32_t millisecondsToTicks (uint32_t ms)
uint32_t secondsToTicks (uint32_t sec)
uint32_t microseconds ()
void delayMicroseconds (uint32_t us)
void delayMilliseconds (uint32_t ms)
Private Attributes
VortexEngine & m_engine
uint64_t start = 0
uint32_t m_tickrate
uint32_t m_curTick
uint32_t m_prevTime
uint32_t m_firstTime
Detailed Description
Definition at line 29 of file TimeControl.h.
Constructor & Destructor Documentation
Time()
Time::Time (VortexEngine & engine)
Definition at line 28 of file TimeControl.cpp.
                               :
  m_engine(engine),
#if !defined(_WIN32) || defined(WASM)
  start(0),
#else
  tps(),
  start(),
#endif
#if VARIABLE_TICKRATE == 1
  m_tickrate(DEFAULT_TICKRATE),
#endif
  m_curTick(0),
  m_prevTime(0),
  m_firstTime(0),
#ifdef VORTEX_LIB
  m_simulationTick(0),
  m_isSimulation(false),
  m_instantTimestep(false)
#endif
{
}
 Time()
Time::~Time ()
Definition at line 50 of file TimeControl.cpp.
{
}
Member Function Documentation
cleanup()
void Time::cleanup ()
Definition at line 75 of file TimeControl.cpp.
{
}
Referenced by VortexEngine::cleanup().
delayMicroseconds()
void Time::delayMicroseconds (uint32_t us)
Definition at line 199 of file TimeControl.cpp.
{
#ifdef _WIN32
  uint32_t newtime = microseconds() + us;
  while (microseconds() < newtime) {
    // busy loop
  }
#else
  usleep(us);
#endif
}
References microseconds().
Referenced by delayMilliseconds(), VLSender::sendMark(), VLSender::sendSpace(), and tickClock().
delayMilliseconds()
void Time::delayMilliseconds (uint32_t ms)
Definition at line 211 of file TimeControl.cpp.
{
#ifdef VORTEX_EMBEDDED
  // not very accurate
  for (uint16_t i = 0; i < ms; ++i) {
    delayMicroseconds(1000);
  }
#elif defined(_WIN32)
  Sleep(ms);
#else
  usleep(ms * 1000);
#endif
}
References delayMicroseconds().
Referenced by Leds::holdAll().
getCurtime()
uint32_t Time::getCurtime () [inline]
Definition at line 47 of file TimeControl.h.
{ return m_curTick + SIMULATION_TICK; }
References m_curTick, and SIMULATION_TICK.
Referenced by Timer::alarm(), Leds::blinkAll(), Leds::blinkIndex(), Leds::blinkMap(), Leds::blinkPair(), Leds::blinkPairs(), Leds::blinkRange(), SerialComs::checkSerial(), Timer::onEnd(), Timer::onStart(), Menus::openMenuSelection(), ModeSharing::receiveModeIR(), Randomizer::run(), VortexEngine::runMainLogic(), Menus::runMenuSelection(), IRSender::send(), VLSender::send(), Modes::setCurMode(), Menu::showBulbSelection(), ColorSelect::showFullSet(), ColorSelect::showSelection(), Timer::start(), and Button::update().
getRealCurtime()
uint32_t Time::getRealCurtime ()
Definition at line 133 of file TimeControl.cpp.
{
  return m_curTick;
}
References m_curTick.
getTickrate()
uint32_t Time::getTickrate ()
Definition at line 138 of file TimeControl.cpp.
{
  return TICKRATE;
}
References TICKRATE.
init()
bool Time::init ()
Definition at line 54 of file TimeControl.cpp.
{
  m_firstTime = m_prevTime = microseconds();
  m_curTick = 0;
#if VARIABLE_TICKRATE == 1
  m_tickrate = DEFAULT_TICKRATE;
#endif
#ifdef VORTEX_LIB
  m_simulationTick = 0;
  m_isSimulation = false;
  m_instantTimestep = false;
#endif
#if !defined(_WIN32) || defined(WASM)
  start = microseconds();
#else
  QueryPerformanceFrequency(&tps);
  QueryPerformanceCounter(&start);
#endif
  return true;
}
References DEFAULT_TICKRATE, m_curTick, m_firstTime, m_prevTime, m_tickrate, microseconds(), and start.
Referenced by VortexEngine::init().
microseconds()
uint32_t Time::microseconds ()
Definition at line 178 of file TimeControl.cpp.
{
#ifndef VORTEX_LIB // Embedded avr devices
  // arduino micros, or whatever micro implementation you have chosen for the embedded device
  return micros();
#elif defined(_WIN32) // windows
  LARGE_INTEGER now;
  QueryPerformanceCounter(&now);
  if (!tps.QuadPart) {
    return 0;
  }
  // yes, this will overflow, that's how arduino microseconds() works *shrug*
  return (unsigned long)((now.QuadPart - start.QuadPart) * 1000000 / tps.QuadPart);
#else // linux/wasm/etc
  struct timespec ts;
  clock_gettime(CLOCK_MONOTONIC_RAW, &ts);
  uint64_t us = SEC_TO_US((uint64_t)ts.tv_sec) + NS_TO_US((uint64_t)ts.tv_nsec);
  return (unsigned long)us;
#endif
}
References NS_TO_US, SEC_TO_US, and start.
Referenced by IRSender::beginSend(), VLSender::beginSend(), delayMicroseconds(), init(), IRReceiver::recvPCIHandler(), VLReceiver::recvPCIHandler(), and tickClock().
millisecondsToTicks()
uint32_t Time::millisecondsToTicks (uint32_t ms)
Definition at line 161 of file TimeControl.cpp.
{
  // 0ms = 0 ticks
  if (!ms) {
    return 0;
  }
  // but anything > 0 ms must be no less than 1 tick
  // otherwise short durations will disappear at low
  // tickrates
  uint32_t ticks = (ms * TICKRATE) / 1000;
  if (!ticks) {
    return 1;
  }
  return ticks;
}
References TICKRATE.
Referenced by secondsToTicks().
secondsToTicks()
uint32_t Time::secondsToTicks (uint32_t sec) [inline]
Definition at line 73 of file TimeControl.h.
{ return millisecondsToTicks(sec * 1000); }
References millisecondsToTicks().
setTickrate()
void Time::setTickrate (uint32_t tickrate = 0)
Definition at line 145 of file TimeControl.cpp.
{
#if VARIABLE_TICKRATE == 1
  if (!tickrate) {
    // can't set 0 tickrate, so 0 sets default
    tickrate = DEFAULT_TICKRATE;
  } else if (tickrate > 1000000) {
    // more than 1 million ticks per second won't work anyway
    tickrate = 1000000;
  }
  // update the tickrate
  m_tickrate = tickrate;
#endif
}
References DEFAULT_TICKRATE, and m_tickrate.
tickClock()
void Time::tickClock ()
Definition at line 79 of file TimeControl.cpp.
{
  // tick clock forward
  m_curTick++;
#if DEBUG_ALLOCATIONS == 1
  if ((m_curTick % MS_TO_TICKS(1000)) == 0) {
    DEBUG_LOGF("Cur Memory: %u (%u)", cur_memory_usage(), cur_memory_usage_background());
  }
#endif
#ifdef VORTEX_LIB
  if (m_instantTimestep) {
    return;
  }
#endif
  // perform timestep
  uint32_t elapsed_us;
  uint32_t us;
  do {
    us = microseconds();
    // detect rollover of microsecond counter
    if (us < m_prevTime) {
      // calculate wrapped around difference
      elapsed_us = (uint32_t)((UINT32_MAX - m_prevTime) + us);
    } else {
      // otherwise calculate regular difference
      elapsed_us = (uint32_t)(us - m_prevTime);
    }
    // if building anywhere except visual studio then we can run alternate sleep code
    // because in visual studio + windows it's better to just spin and check the high
    // resolution clock instead of trying to sleep for microseconds.
#if !defined(_WIN32) && defined(VORTEX_LIB)
    uint32_t required = (1000000 / TICKRATE);
    uint32_t sleepTime = 0;
    if (required > elapsed_us) {
      // in vortex lib on linux we can just sleep instead of spinning
      // but on embedded we must spin and on windows it actually ends
      // up being more accurate to poll QPF + QPC via microseconds()
      sleepTime = required - elapsed_us;
    }
    Time::delayMicroseconds(sleepTime);
    break;
#endif
    // 1000us per ms, divided by tickrate gives
    // the number of microseconds per tick
  } while (elapsed_us < (1000000 / TICKRATE));
  // store current time
  m_prevTime = microseconds();
}
References DEBUG_LOGF, delayMicroseconds(), m_curTick, m_prevTime, microseconds(), MS_TO_TICKS, and TICKRATE.
Referenced by VortexEngine::tick().
Member Data Documentation
m_curTick
uint32_t Time::m_curTick [private]
Definition at line 131 of file TimeControl.h.
Referenced by getCurtime(), getRealCurtime(), init(), and tickClock().
m_engine
VortexEngine& Time::m_engine [private]
Definition at line 116 of file TimeControl.h.
m_firstTime
uint32_t Time::m_firstTime [private]
Definition at line 137 of file TimeControl.h.
Referenced by init().
m_prevTime
uint32_t Time::m_prevTime [private]
Definition at line 134 of file TimeControl.h.
Referenced by init(), and tickClock().
m_tickrate
uint32_t Time::m_tickrate [private]
Definition at line 127 of file TimeControl.h.
Referenced by init(), and setTickrate().
start
uint64_t Time::start = 0 [private]
Definition at line 119 of file TimeControl.h.
Referenced by init(), and microseconds().
The documentation for this class was generated from the following files:
VortexEngine/src/Time/TimeControl.h
VortexEngine/src/Time/TimeControl.cpp