LighthousePattern Class Reference
#include <LighthousePattern.h>
Public Member Functions
LighthousePattern (VortexEngine &engine, const PatternArgs &args)
virtual ~LighthousePattern ()
virtual void init () override
virtual void play () override
Protected Member Functions
virtual void blinkOn () override
virtual void blinkOff () override
virtual void poststep () override
virtual void fade ()
Private Attributes
uint8_t m_fadeAmount
uint8_t m_fadeRate
Timer m_fadeTimer
LedStash m_stash
uint8_t m_progress
Additional Inherited Members
Detailed Description
Definition at line 7 of file LighthousePattern.h.
Constructor & Destructor Documentation
LighthousePattern()
LighthousePattern::LighthousePattern (VortexEngine & engine, const PatternArgs & args)
Definition at line 10 of file LighthousePattern.cpp.
                                                                                  :
  BlinkStepPattern(engine, args),
  m_fadeAmount(0),
  m_fadeRate(0),
  m_fadeTimer(engine),
  m_stash(engine),
  m_progress(0)
{
  m_patternID = PATTERN_LIGHTHOUSE;
  REGISTER_ARG(m_fadeAmount);
  REGISTER_ARG(m_fadeRate);
  setArgs(args);
}
References m_fadeAmount, m_fadeRate, Pattern::m_patternID, PATTERN_LIGHTHOUSE, REGISTER_ARG, and Pattern::setArgs().
 LighthousePattern()
LighthousePattern::~LighthousePattern () [virtual]
Definition at line 24 of file LighthousePattern.cpp.
{
}
Member Function Documentation
blinkOff()
void LighthousePattern::blinkOff () [override], [protected], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 59 of file LighthousePattern.cpp.
{
  m_engine.leds().stashAll(m_stash);
  m_engine.leds().clearAll();
}
References Leds::clearAll(), VortexEngine::leds(), Pattern::m_engine, m_stash, and Leds::stashAll().
blinkOn()
void LighthousePattern::blinkOn () [override], [protected], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 52 of file LighthousePattern.cpp.
{
  m_engine.leds().restoreAll(m_stash);
  m_engine.leds().setIndex((LedPos)m_progress, m_colorset.cur());
  m_engine.leds().stashAll(m_stash);
}
References Colorset::cur(), VortexEngine::leds(), Pattern::m_colorset, Pattern::m_engine, m_progress, m_stash, Leds::restoreAll(), Leds::setIndex(), and Leds::stashAll().
fade()
void LighthousePattern::fade () [protected], [virtual]
Definition at line 71 of file LighthousePattern.cpp.
{
  for (int i = 0; i < LED_COUNT; ++i) {
    m_stash[i].adjustBrightness(m_fadeAmount);
  }
}
References LED_COUNT, m_fadeAmount, and m_stash.
Referenced by play().
init()
void LighthousePattern::init () [override], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 29 of file LighthousePattern.cpp.
{
  BlinkStepPattern::init();
  // fade timer setup
  m_fadeTimer.reset();
  m_fadeTimer.addAlarm(m_fadeRate);
  m_fadeTimer.start();
  // start colorset at index 0 so cur() works
  m_colorset.setCurIndex(0);
}
References Timer::addAlarm(), BlinkStepPattern::init(), Pattern::m_colorset, m_fadeRate, m_fadeTimer, Timer::reset(), Colorset::setCurIndex(), and Timer::start().
play()
void LighthousePattern::play () [override], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 43 of file LighthousePattern.cpp.
{
  if (m_fadeTimer.alarm() == 0) {
    fade();
  }
  BlinkStepPattern::play();
}
References Timer::alarm(), fade(), m_fadeTimer, and BlinkStepPattern::play().
poststep()
void LighthousePattern::poststep () [override], [protected], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 65 of file LighthousePattern.cpp.
{
  m_progress = (m_progress + 1) % LED_COUNT;
  m_colorset.getNext();
}
References Colorset::getNext(), LED_COUNT, Pattern::m_colorset, and m_progress.
Member Data Documentation
m_fadeAmount
uint8_t LighthousePattern::m_fadeAmount [private]
Definition at line 30 of file LighthousePattern.h.
Referenced by fade(), and LighthousePattern().
m_fadeRate
uint8_t LighthousePattern::m_fadeRate [private]
Definition at line 32 of file LighthousePattern.h.
Referenced by init(), and LighthousePattern().
m_fadeTimer
Timer LighthousePattern::m_fadeTimer [private]
Definition at line 34 of file LighthousePattern.h.
Referenced by init(), and play().
m_progress
uint8_t LighthousePattern::m_progress [private]
Definition at line 38 of file LighthousePattern.h.
Referenced by blinkOn(), and poststep().
m_stash
LedStash LighthousePattern::m_stash [private]
Definition at line 36 of file LighthousePattern.h.
Referenced by blinkOff(), blinkOn(), and fade().
The documentation for this class was generated from the following files:
VortexEngine/src/Patterns/Multi/LighthousePattern.h
VortexEngine/src/Patterns/Multi/LighthousePattern.cpp