VortexCLI Class Reference
#include <VortexCLI.h>
Classes
class VortexCLICallbacks
Public Member Functions
VortexCLI ()
~VortexCLI ()
bool init (int argc, char *argv[])
void run ()
void cleanup ()
void show ()
bool isButtonPressed ()
bool stillRunning () const
void installLeds (void *leds, uint32_t count)
void setColoredOutput (bool output)
void setHexOutput (bool output)
void setNoTimestep (bool timestep)
void setInPlace (bool inplace)
Static Public Member Functions
static void printlog (const char *file, const char *func, int line, const char *msg, va_list list)
Private Types
enum OutputType { OUTPUT_TYPE_NONE
, OUTPUT_TYPE_HEX
, OUTPUT_TYPE_COLOR
, OUTPUT_TYPE_SILENT
 }
enum JsonMode : uint32_t {
JSON_MODE_NONE = 0
, JSON_MODE_READ_STDIN = (1<<0)
, JSON_MODE_READ_FILE = (1<<1)
, JSON_MODE_WRITE_STDOUT = (1<<2)
,
JSON_MODE_WRITE_FILE = (1<<3)
 }
Private Member Functions
void get_terminal_size ()
Private Attributes
Vortex m_vortex
VortexEngine & m_engine
RGBColor * m_ledList
uint32_t m_numLeds
uint8_t m_ledCount
bool m_initialized
bool m_buttonPressed
bool m_keepGoing
volatile bool m_isPaused
PatternID m_curPattern
Colorset m_curColorset
OutputType m_outputType
JsonMode m_jsonMode
bool m_noTimestep
bool m_lockstep
bool m_inPlace
bool m_record
bool m_storage
bool m_sleepEnabled
bool m_lockEnabled
bool m_jsonPretty
bool m_quickExit
bool m_displayVersion
int m_verbosity
std::string m_storageFile
std::string m_writeSaveFile
std::string m_writeModeFile
std::string m_loadSaveFile
std::string m_jsonInFile
std::string m_jsonOutFile
std::string m_patternIDStr
std::string m_colorsetStr
std::string m_argumentsStr
int m_pipe_fd [2]
int m_saved_stdin
std::string m_inputBuffer
Detailed Description
Definition at line 11 of file VortexCLI.h.
Member Enumeration Documentation
JsonMode
enum VortexCLI::JsonMode : uint32_t [private]
Enumerator
JSON_MODE_NONE
JSON_MODE_READ_STDIN
JSON_MODE_READ_FILE
JSON_MODE_WRITE_STDOUT
JSON_MODE_WRITE_FILE
Definition at line 82 of file VortexCLI.h.
                : uint32_t {
    JSON_MODE_NONE = 0,
    // technically two these are mutually exclusive... but this is easier
    JSON_MODE_READ_STDIN = (1<<0),
    JSON_MODE_READ_FILE = (1<<1),
    // also these too, mutually exclusive but this is easier
    JSON_MODE_WRITE_STDOUT = (1<<2),
    JSON_MODE_WRITE_FILE = (1<<3),
  };
OutputType
enum VortexCLI::OutputType [private]
Enumerator
OUTPUT_TYPE_NONE
OUTPUT_TYPE_HEX
OUTPUT_TYPE_COLOR
OUTPUT_TYPE_SILENT
Definition at line 75 of file VortexCLI.h.
                  {
    OUTPUT_TYPE_NONE,
    OUTPUT_TYPE_HEX,
    OUTPUT_TYPE_COLOR,
    OUTPUT_TYPE_SILENT,
  };
Constructor & Destructor Documentation
VortexCLI()
VortexCLI::VortexCLI ()
Definition at line 146 of file VortexCLI.cpp.
                     :
  m_vortex(),
  m_engine(m_vortex.engine()),
  m_ledList(),
  m_numLeds(0),
  m_ledCount(0),
  m_initialized(false),
  m_buttonPressed(false),
  m_keepGoing(true),
  m_isPaused(true),
  m_curPattern(PATTERN_FIRST),
  m_curColorset(),
  m_outputType(OUTPUT_TYPE_NONE),
  m_jsonMode(JSON_MODE_NONE),
  m_noTimestep(false),
  m_lockstep(false),
  m_inPlace(false),
  m_record(false),
  m_storage(false),
  m_sleepEnabled(true),
  m_lockEnabled(true),
  m_jsonPretty(false),
  m_quickExit(false),
  m_displayVersion(false),
  m_verbosity(0),
  m_storageFile("FlashStorage.flash"),
  m_patternIDStr(),
  m_colorsetStr(),
  m_argumentsStr(),
  m_pipe_fd{-1, -1},
  m_saved_stdin(),
  m_inputBuffer()
{
}
 VortexCLI()
VortexCLI::~VortexCLI ()
Definition at line 181 of file VortexCLI.cpp.
{
}
Member Function Documentation
cleanup()
void VortexCLI::cleanup ()
Definition at line 659 of file VortexCLI.cpp.
{
  DEBUG_LOG("Quitting...");
  if (m_inPlace) {
    printf("\n");
  }
  if (m_record) {
    // Open the file in write mode
    FILE *outputFile = fopen(RECORD_FILE, "w");
    if (!outputFile) {
      printf("Failed to open: [%s] (%s)", RECORD_FILE, strerror(errno));
      exit(2);
    }
    // Print the recorded input to the file
    fprintf(outputFile, "%s", m_vortex.getCommandLog().c_str());
    // Close the output file
    fclose(outputFile);
    printf("Wrote recorded input to " RECORD_FILE "\n");
  }
  if (m_jsonMode & JSON_MODE_WRITE_STDOUT) {
    // dump the current save in json format
    std::cout << m_vortex.printJson(m_jsonPretty);
  }
  if (m_jsonMode & JSON_MODE_WRITE_FILE) {
    m_vortex.printJsonToFile(m_jsonOutFile.c_str(), m_jsonPretty);
    printf("Wrote JSON to file [%s]\n", m_jsonOutFile.c_str());
  }
  if (m_writeSaveFile.length() > 0) {
    ByteStream stream;
    m_vortex.getModes(stream);
    FILE *outputFile = fopen(m_writeSaveFile.c_str(), "w");
    if (!outputFile) {
      printf("Failed to open: [%s] (%s)", m_writeSaveFile.c_str(), strerror(errno));
      exit(2);
    }
    // Print the recorded input to the file
    fwrite(stream.rawData(), 1, stream.rawSize(), outputFile);
    // Close the output file
    fclose(outputFile);
    printf("Wrote vortex save to [%s]\n", m_writeSaveFile.c_str());
  }
  if (m_writeModeFile.length() > 0) {
    ByteStream stream;
    m_vortex.getCurMode(stream);
    FILE *outputFile = fopen(m_writeModeFile.c_str(), "w");
    if (!outputFile) {
      printf("Failed to open: [%s] (%s)", m_writeModeFile.c_str(), strerror(errno));
      exit(2);
    }
    // Print the recorded input to the file
    fwrite(stream.rawData(), 1, stream.rawSize(), outputFile);
    // Close the output file
    fclose(outputFile);
    printf("Wrote vtxmode save to [%s]\n", m_writeModeFile.c_str());
  }
  m_keepGoing = false;
  m_isPaused = false;
  if (m_storage) {
    m_vortex.doSave();
  }
  m_vortex.cleanup();
#ifdef WASM
  emscripten_force_exit(0);
#endif
}
References Vortex::cleanup(), DEBUG_LOG, Vortex::doSave(), Vortex::getCommandLog(), Vortex::getCurMode(), Vortex::getModes(), JSON_MODE_WRITE_FILE, JSON_MODE_WRITE_STDOUT, m_inPlace, m_isPaused, m_jsonMode, m_jsonOutFile, m_jsonPretty, m_keepGoing, m_record, m_storage, m_vortex, m_writeModeFile, m_writeSaveFile, Vortex::printJson(), Vortex::printJsonToFile(), ByteStream::rawData(), ByteStream::rawSize(), and RECORD_FILE.
Referenced by run().
get_terminal_size()
void VortexCLI::get_terminal_size () [private]
Definition at line 340 of file VortexCLI.cpp.
{
#ifdef _WIN32
  // Windows-specific code
  CONSOLE_SCREEN_BUFFER_INFO csbi;
  GetConsoleScreenBufferInfo(GetStdHandle(STD_OUTPUT_HANDLE), &csbi);
  term_columns = csbi.srWindow.Right - csbi.srWindow.Left + 1;
#else
  // Linux-specific code
  struct winsize new_terminal_size = { 0 };
  ioctl(STDOUT_FILENO, TIOCGWINSZ, &new_terminal_size);
  if (term_columns != new_terminal_size.ws_col) {
    term_columns = new_terminal_size.ws_col;
    if (m_inPlace && !system("clear")) {
      printf("Failed to clear\n");
    }
  }
#endif
}
References m_inPlace, and term_columns.
Referenced by init(), and show().
init()
bool VortexCLI::init (int argc, char * argv[])
Definition at line 360 of file VortexCLI.cpp.
{
  if (g_pVortexCLI) {
    return false;
  }
  g_pVortexCLI = this;
  if (argc == 1) {
    print_usage(argv[0]);
    exit(1);
  }
  int opt = -1;
  int option_index = 0;
  while ((opt = getopt_long(argc, argv, "xcstliranquS::W:M:L:I::O::HP:C:A:Vvh", long_options, &option_index)) != -1) {
    switch (opt) {
    case 'x':
      // if the user wants pretty colors or hex codes
      m_outputType = OUTPUT_TYPE_HEX;
      break;
    case 'c':
      // if the user wants pretty colors
      m_outputType = OUTPUT_TYPE_COLOR;
      break;
    case 's':
      // turn off output
      m_outputType = OUTPUT_TYPE_SILENT;
      break;
    case 't':
      // if the user wants to bypass timestep
      m_noTimestep = true;
      break;
    case 'l':
      // if the user wants to step in lockstep with the engine
      m_lockstep = true;
      break;
    case 'i':
      // if the user wants to print in-place (on one line)
      m_inPlace = true;
      break;
    case 'r':
      // record the inputs and dump them to a file after
      m_record = true;
      break;
    case 'a':
      // autuowake prevents sleep
      m_sleepEnabled = false;
      break;
    case 'n':
      // disable the lock
      m_lockEnabled = false;
      break;
    case 'q':
      // quick exit
      m_quickExit = true;
      break;
    case 'u':
      if (optarg == NULL && optind < argc && argv[optind][0] != '-') {
        optarg = argv[optind++];
      }
      if (optarg) {
        m_ledCount = (uint8_t)strtoul(optarg, NULL, 10);
      }
      break;
    case 'S':
      // enable persistent storage to file
      m_storage = true;
      if (optarg == NULL && optind < argc && argv[optind][0] != '-') {
        optarg = argv[optind++];
      }
      if (optarg) {
        m_storageFile = optarg;
      }
      break;
    case 'W':
      m_writeSaveFile = optarg;
      break;
    case 'M':
      m_writeModeFile = optarg;
      break;
    case 'L':
      m_loadSaveFile = optarg;
      break;
    case 'I':
      // read json from stdin or file
      if (optarg == NULL && optind < argc && argv[optind][0] != '-') {
        optarg = argv[optind++];
      }
      if (optarg) {
        m_jsonMode = (JsonMode)(m_jsonMode | JSON_MODE_READ_FILE);
        m_jsonInFile = optarg;
      } else {
        m_jsonMode = (JsonMode)(m_jsonMode | JSON_MODE_READ_STDIN);
      }
      break;
    case 'O':
      // write json to output or file
      if (optarg == NULL && optind < argc && argv[optind][0] != '-') {
        optarg = argv[optind++];
      }
      if (optarg) {
        m_jsonMode = (JsonMode)(m_jsonMode | JSON_MODE_WRITE_FILE);
        m_jsonOutFile = optarg;
      } else {
        m_jsonMode = (JsonMode)(m_jsonMode | JSON_MODE_WRITE_STDOUT);
      }
      break;
    case 'H':
      // json human readable
      m_jsonPretty = true;
      break;
    case 'P':
      // preset the pattern ID on the first mode
      m_patternIDStr = optarg;
      break;
    case 'C':
      // preset the colorset on the first mode
      m_colorsetStr = optarg;
      break;
    case 'A':
      // preset the arguments on the first mode
      m_argumentsStr = optarg;
      break;
    case 'V':
      m_displayVersion = true;
      break;
    case 'v':
      // TODO: make this do something
      m_verbosity++;
      break;
    case 'h':
      // print usage and exit
      print_usage(argv[0]);
      exit(EXIT_SUCCESS);
    default: // '?' for unrecognized options
      printf("Unknown arg: -%c\n", opt);
      exit(EXIT_FAILURE);
    }
  }
  if (m_displayVersion) {
    printf(VORTEX_FULL_NAME "\n");
    exit(0);
  }
  switch (m_outputType) {
  case OUTPUT_TYPE_NONE:
    print_usage(argv[0]);
    exit(EXIT_SUCCESS);
    break;
  case OUTPUT_TYPE_COLOR:
    setColoredOutput(true);
    break;
  case OUTPUT_TYPE_HEX:
    setHexOutput(true);
    break;
  case OUTPUT_TYPE_SILENT:
    break;
  }
  // do the vortex init/setup
  m_vortex.initEx<VortexCLICallbacks>();
  // configure the vortex engine as the parameters dictate
  m_vortex.setInstantTimestep(m_noTimestep);
  m_vortex.enableCommandLog(m_record);
  m_vortex.enableLockstep(m_lockstep);
  m_vortex.enableStorage(m_storage);
  if (m_ledCount > 0 && m_ledCount < 256) {
    m_vortex.setLedCount(m_ledCount);
  }
  if (m_storage) {
    m_vortex.setStorageFilename(m_storageFile);
    if (access(m_storageFile.c_str(), F_OK) == 0) {
      // load storage if the file exists
      m_vortex.loadStorage();
    }
  }
  m_vortex.setSleepEnabled(m_sleepEnabled);
  m_vortex.setLockEnabled(m_lockEnabled);
  if (m_jsonMode & JSON_MODE_READ_STDIN) {
    // todo: read js from stdin
    printf("Reading json from stdin\n");
    std::string inputString;
    // Read from stdin until EOF
    inputString.assign((std::istreambuf_iterator<char>(std::cin)),
                        std::istreambuf_iterator<char>());
    // read from m_jsonInFile;
    m_vortex.parseJson(inputString);
  }
  if (m_jsonMode & JSON_MODE_READ_FILE) {
    printf("Reading json from %s\n", m_jsonInFile.c_str());
    // read from m_jsonInFile;
    m_vortex.parseJsonFromFile(m_jsonInFile);
  }
  // load a .vortex or .vtxmode savefile
  if (m_loadSaveFile.size() > 0) {
    ByteStream stream(4096);
    // Open the file in read mode
    FILE *inputFile = fopen(m_loadSaveFile.c_str(), "r");
    if (!inputFile) {
      printf("Failed to open: [%s] (%s)\n", m_loadSaveFile.c_str(), strerror(errno));
      exit(2);
    }
    if (!fread((void *)stream.rawData(), 1, stream.capacity(), inputFile)) {
      // error
      printf("Failed to read [%s]\n", m_loadSaveFile.c_str());
      exit(2);
    }
    fclose(inputFile);
    // clear existing modes
    m_vortex.engine().modes().clearModes();
    // check if the load from savefile was provided, this is kinda ugly but whatever
    if (m_loadSaveFile.size() >= 8 && m_loadSaveFile.rfind(".vtxmode") == m_loadSaveFile.size() - 8) {
      // match the led count of the savefile, a vtxmode
      m_vortex.matchLedCount(stream, true);
      // ends with .vtxmode, load just a single mode
      m_vortex.addNewMode(stream);
    } else if (m_loadSaveFile.size() >= 7 && m_loadSaveFile.rfind(".vortex") == m_loadSaveFile.size() - 7) {
      // match the led count of the savefile, a vortex file
      m_vortex.matchLedCount(stream, false);
      // ends with .vortex, load the entire save
      m_vortex.setModes(stream);
    } else {
      // wasn't a valid savefile name
      printf("Savefile name must end in .vortex or .vtxmode: [%s]\n", m_loadSaveFile.c_str());
      exit(2);
    }
  }
  if (m_patternIDStr.length() > 0) {
    // convert both numeric and string to see which one seems more correct
    PatternID id = (PatternID)strtoul(m_patternIDStr.c_str(), nullptr, 10);
    PatternID strID = m_vortex.stringToPattern(m_patternIDStr);
    if (id == PATTERN_FIRST && strID != PATTERN_NONE) {
      // use the str ID if the numeric ID didn't convert and the string did
      id = strID;
    }
    // TODO: add arg for the led position
    m_vortex.setPatternAt(LED_ALL, id);
  }
  if (m_colorsetStr.length() > 0) {
    stringstream ss(m_colorsetStr);
    string color;
    Colorset set;
    while (getline(ss, color, ',')) {
      // iterate letters and lowercase them
      transform(color.begin(), color.end(), color.begin(), [](unsigned char c){ return tolower(c); });
      if (color_map.count(color) > 0) {
        set.addColor(color_map[color]);
      } else {
        set.addColor(strtoul(color.c_str(), nullptr, 16));
      }
    }
    // TODO: add arg for the led position
    m_vortex.setColorset(LED_ALL, set);
  }
  if (m_argumentsStr.length() > 0) {
    stringstream ss(m_argumentsStr);
    string arg;
    PatternArgs args;
    while (getline(ss, arg, ',')) {
      args.args[args.numArgs++] = strtoul(arg.c_str(), nullptr, 10);
    }
    // TODO: add arg for the led position
    m_vortex.setPatternArgs(LED_ALL, args);
  }
  if (m_inPlace && !system("clear")) {
    printf("Failed to clear\n");
  }
  set_terminal_nonblocking();
  get_terminal_size();
  m_initialized = true;
#ifndef WASM
#else
  // NOTE: This call does not return and will instead automatically
  // call the VortexCLI::run() in a loop
  wasm_init();
#endif
  return true;
}
References Colorset::addColor(), Vortex::addNewMode(), PatternArgs::args, ByteStream::capacity(), Modes::clearModes(), color_map, Vortex::enableCommandLog(), Vortex::enableLockstep(), Vortex::enableStorage(), Vortex::engine(), g_pVortexCLI, get_terminal_size(), Vortex::initEx(), JSON_MODE_READ_FILE, JSON_MODE_READ_STDIN, JSON_MODE_WRITE_FILE, JSON_MODE_WRITE_STDOUT, LED_ALL, Vortex::loadStorage(), long_options, m_argumentsStr, m_colorsetStr, m_displayVersion, m_initialized, m_inPlace, m_jsonInFile, m_jsonMode, m_jsonOutFile, m_jsonPretty, m_ledCount, m_loadSaveFile, m_lockEnabled, m_lockstep, m_noTimestep, m_outputType, m_patternIDStr, m_quickExit, m_record, m_sleepEnabled, m_storage, m_storageFile, m_verbosity, m_vortex, m_writeModeFile, m_writeSaveFile, Vortex::matchLedCount(), VortexEngine::modes(), PatternArgs::numArgs, OUTPUT_TYPE_COLOR, OUTPUT_TYPE_HEX, OUTPUT_TYPE_NONE, OUTPUT_TYPE_SILENT, Vortex::parseJson(), Vortex::parseJsonFromFile(), PATTERN_FIRST, PATTERN_NONE, print_usage(), ByteStream::rawData(), set_terminal_nonblocking(), setColoredOutput(), Vortex::setColorset(), setHexOutput(), Vortex::setInstantTimestep(), Vortex::setLedCount(), Vortex::setLockEnabled(), Vortex::setModes(), Vortex::setPatternArgs(), Vortex::setPatternAt(), Vortex::setSleepEnabled(), Vortex::setStorageFilename(), Vortex::stringToPattern(), and VORTEX_FULL_NAME.
Referenced by main().
installLeds()
void VortexCLI::installLeds (void * leds, uint32_t count)
Definition at line 803 of file VortexCLI.cpp.
{
  m_ledList = (RGBColor *)leds;
  m_numLeds = count;
}
References m_ledList, and m_numLeds.
Referenced by VortexCLI::VortexCLICallbacks::ledsInit().
isButtonPressed()
bool VortexCLI::isButtonPressed ()
Definition at line 793 of file VortexCLI.cpp.
{
  return m_vortex.isButtonPressed();
}
References Vortex::isButtonPressed(), and m_vortex.
printlog()
static void VortexCLI::printlog (const char * file, const char * func, int line, const char * msg, va_list list) [static]
run()
void VortexCLI::run ()
Definition at line 649 of file VortexCLI.cpp.
{
  if (!stillRunning()) {
    return;
  }
  if (!m_vortex.tick() || m_quickExit) {
    cleanup();
  }
}
References cleanup(), m_quickExit, m_vortex, stillRunning(), and Vortex::tick().
Referenced by main().
setColoredOutput()
void VortexCLI::setColoredOutput (bool output) [inline]
Definition at line 38 of file VortexCLI.h.
{ m_outputType = OUTPUT_TYPE_COLOR; }
References m_outputType, and OUTPUT_TYPE_COLOR.
Referenced by init().
setHexOutput()
void VortexCLI::setHexOutput (bool output) [inline]
Definition at line 39 of file VortexCLI.h.
{ m_outputType = OUTPUT_TYPE_HEX; }
References m_outputType, and OUTPUT_TYPE_HEX.
Referenced by init().
setInPlace()
void VortexCLI::setInPlace (bool inplace) [inline]
Definition at line 41 of file VortexCLI.h.
{ m_inPlace = inplace; }
References m_inPlace.
setNoTimestep()
void VortexCLI::setNoTimestep (bool timestep) [inline]
Definition at line 40 of file VortexCLI.h.
{ m_noTimestep = timestep; }
References m_noTimestep.
show()
void VortexCLI::show ()
Definition at line 726 of file VortexCLI.cpp.
{
  if (!m_initialized) {
    return;
  }
  if (m_outputType == OUTPUT_TYPE_SILENT) {
    return;
  }
  string out;
  get_terminal_size();
  uint32_t wid = term_columns;
  uint32_t odd = (wid) % 2;
  uint32_t halfwid = wid / 2;
  uint32_t midWid = (halfwid - ((2 + (m_outputType == OUTPUT_TYPE_HEX)) * LED_COUNT)) - 1;
  if (m_inPlace) {
    // this resets the cursor back to the beginning of the line and moves it up 12 lines
    out += "\33[2K\033[17A\r";
    // this is the top border line
    out += "+";
    out += LINE((wid + odd) - 2);
    out += "+\n|";
    // this is the left inner line
    out += LINE(midWid + odd);
    out += "=";
  }
  if (m_outputType == OUTPUT_TYPE_COLOR) {
    // the color strip itself
    for (uint32_t i = 0; i < m_numLeds; ++i) {
      out += "\x1B[0m["; // opening |
      out += "\x1B[48;2;"; // colorcode start
      out += to_string(m_ledList[i].red) + ";"; // col red
      out += to_string(m_ledList[i].green) + ";"; // col green
      out += to_string(m_ledList[i].blue) + "m"; // col blue
      out += " "; // colored space
      out += "\x1B[0m]"; // ending |
    }
  } else if (m_outputType == OUTPUT_TYPE_HEX) {
    // otherwise this just prints out the raw hex code if not in color mode
    for (uint32_t i = 0; i < m_numLeds; ++i) {
      char buf[128] = { 0 };
      snprintf(buf, sizeof(buf), "%06X", m_ledList[i].raw());
      out += buf;
    }
  }
  if (!m_inPlace) {
    out += "\n";
  } else {
    // the right inner line
    out += "=";
    out += LINE((midWid - 1) + odd);
    // the end of middle line, fold and start of 3rd line
    out += "|\n+";
    out += LINE((wid + odd) - 2);
    // space line after the box and before usage
    out += "+\n";
    out += SPACES(wid + odd);
    // the usage message
    for (uint32_t i = 0; i < NUM_USAGE; ++i) {
      const char *brief = (wid < 70) ? input_usage_brief[i] : input_usage[i];
      out += brief;
      out += SPACES((wid + odd + 1) - strlen(brief));
    }
  }
  printf("%s", out.c_str());
  fflush(stdout);
}
References get_terminal_size(), input_usage, input_usage_brief, LED_COUNT, LINE, m_initialized, m_inPlace, m_ledList, m_numLeds, m_outputType, NUM_USAGE, OUTPUT_TYPE_COLOR, OUTPUT_TYPE_HEX, OUTPUT_TYPE_SILENT, SPACES, and term_columns.
Referenced by VortexCLI::VortexCLICallbacks::ledsShow().
stillRunning()
bool VortexCLI::stillRunning () const
Definition at line 798 of file VortexCLI.cpp.
{
  return (m_initialized && m_keepGoing);
}
References m_initialized, and m_keepGoing.
Referenced by main(), and run().
Member Data Documentation
m_argumentsStr
std::string VortexCLI::m_argumentsStr [private]
Definition at line 113 of file VortexCLI.h.
Referenced by init().
m_buttonPressed
bool VortexCLI::m_buttonPressed [private]
Definition at line 70 of file VortexCLI.h.
m_colorsetStr
std::string VortexCLI::m_colorsetStr [private]
Definition at line 112 of file VortexCLI.h.
Referenced by init().
m_curColorset
Colorset VortexCLI::m_curColorset [private]
Definition at line 74 of file VortexCLI.h.
m_curPattern
PatternID VortexCLI::m_curPattern [private]
Definition at line 73 of file VortexCLI.h.
m_displayVersion
bool VortexCLI::m_displayVersion [private]
Definition at line 103 of file VortexCLI.h.
Referenced by init().
m_engine
VortexEngine& VortexCLI::m_engine [private]
Definition at line 62 of file VortexCLI.h.
m_initialized
bool VortexCLI::m_initialized [private]
Definition at line 69 of file VortexCLI.h.
Referenced by init(), show(), and stillRunning().
m_inPlace
bool VortexCLI::m_inPlace [private]
Definition at line 96 of file VortexCLI.h.
Referenced by cleanup(), get_terminal_size(), init(), setInPlace(), and show().
m_inputBuffer
std::string VortexCLI::m_inputBuffer [private]
Definition at line 117 of file VortexCLI.h.
m_isPaused
volatile bool VortexCLI::m_isPaused [private]
Definition at line 72 of file VortexCLI.h.
Referenced by cleanup().
m_jsonInFile
std::string VortexCLI::m_jsonInFile [private]
Definition at line 109 of file VortexCLI.h.
Referenced by init().
m_jsonMode
JsonMode VortexCLI::m_jsonMode [private]
Definition at line 93 of file VortexCLI.h.
Referenced by cleanup(), and init().
m_jsonOutFile
std::string VortexCLI::m_jsonOutFile [private]
Definition at line 110 of file VortexCLI.h.
Referenced by cleanup(), and init().
m_jsonPretty
bool VortexCLI::m_jsonPretty [private]
Definition at line 101 of file VortexCLI.h.
Referenced by cleanup(), and init().
m_keepGoing
bool VortexCLI::m_keepGoing [private]
Definition at line 71 of file VortexCLI.h.
Referenced by cleanup(), and stillRunning().
m_ledCount
uint8_t VortexCLI::m_ledCount [private]
Definition at line 68 of file VortexCLI.h.
Referenced by init().
m_ledList
RGBColor* VortexCLI::m_ledList [private]
Definition at line 65 of file VortexCLI.h.
Referenced by installLeds(), and show().
m_loadSaveFile
std::string VortexCLI::m_loadSaveFile [private]
Definition at line 108 of file VortexCLI.h.
Referenced by init().
m_lockEnabled
bool VortexCLI::m_lockEnabled [private]
Definition at line 100 of file VortexCLI.h.
Referenced by init().
m_lockstep
bool VortexCLI::m_lockstep [private]
Definition at line 95 of file VortexCLI.h.
Referenced by init().
m_noTimestep
bool VortexCLI::m_noTimestep [private]
Definition at line 94 of file VortexCLI.h.
Referenced by init(), and setNoTimestep().
m_numLeds
uint32_t VortexCLI::m_numLeds [private]
Definition at line 66 of file VortexCLI.h.
Referenced by installLeds(), and show().
m_outputType
OutputType VortexCLI::m_outputType [private]
Definition at line 81 of file VortexCLI.h.
Referenced by init(), setColoredOutput(), setHexOutput(), and show().
m_patternIDStr
std::string VortexCLI::m_patternIDStr [private]
Definition at line 111 of file VortexCLI.h.
Referenced by init().
m_pipe_fd
int VortexCLI::m_pipe_fd[2] [private]
Definition at line 115 of file VortexCLI.h.
m_quickExit
bool VortexCLI::m_quickExit [private]
Definition at line 102 of file VortexCLI.h.
Referenced by init(), and run().
m_record
bool VortexCLI::m_record [private]
Definition at line 97 of file VortexCLI.h.
Referenced by cleanup(), and init().
m_saved_stdin
int VortexCLI::m_saved_stdin [private]
Definition at line 116 of file VortexCLI.h.
m_sleepEnabled
bool VortexCLI::m_sleepEnabled [private]
Definition at line 99 of file VortexCLI.h.
Referenced by init().
m_storage
bool VortexCLI::m_storage [private]
Definition at line 98 of file VortexCLI.h.
Referenced by cleanup(), and init().
m_storageFile
std::string VortexCLI::m_storageFile [private]
Definition at line 105 of file VortexCLI.h.
Referenced by init().
m_verbosity
int VortexCLI::m_verbosity [private]
Definition at line 104 of file VortexCLI.h.
Referenced by init().
m_vortex
Vortex VortexCLI::m_vortex [private]
Definition at line 60 of file VortexCLI.h.
Referenced by cleanup(), init(), isButtonPressed(), and run().
m_writeModeFile
std::string VortexCLI::m_writeModeFile [private]
Definition at line 107 of file VortexCLI.h.
Referenced by cleanup(), and init().
m_writeSaveFile
std::string VortexCLI::m_writeSaveFile [private]
Definition at line 106 of file VortexCLI.h.
Referenced by cleanup(), and init().
The documentation for this class was generated from the following files:
VortexEngine/VortexCLI/VortexCLI.h
VortexEngine/VortexCLI/VortexCLI.cpp