Mode Class Reference
#include <Mode.h>
Public Member Functions
Mode (VortexEngine &engine, uint8_t numLeds)
Mode (VortexEngine &engine)
Mode (VortexEngine &engine, PatternID id, const Colorset &set)
Mode (VortexEngine &engine, PatternID id, const PatternArgs &args, const Colorset &set)
Mode (VortexEngine &engine, PatternID id, const PatternArgs *args, const Colorset *set)
~Mode ()
Mode (const Mode &other)
void operator= (const Mode &other)
bool operator== (const Mode &other) const
bool operator!= (const Mode &other) const
void init ()
void play ()
bool saveToBuffer (ByteStream &saveBuffer, uint8_t numLeds=0) const
bool loadFromBuffer (ByteStream &saveBuffer)
bool serialize (ByteStream &buffer, uint8_t numLeds=0) const
bool unserialize (ByteStream &buffer)
bool equals (const Mode *other) const
bool setLedCount (uint8_t numLeds)
uint8_t getLedCount () const
const Pattern * getPattern (LedPos pos) const
Pattern * getPattern (LedPos pos)
const Colorset getColorset (LedPos pos) const
Colorset getColorset (LedPos pos)
PatternID getPatternID (LedPos pos) const
bool setPattern (PatternID pat, LedPos pos, const PatternArgs *args=nullptr, const Colorset *set=nullptr)
bool setPatternMap (LedMap pos, PatternID pat, const PatternArgs *args=nullptr, const Colorset *set=nullptr)
bool setColorset (const Colorset &set, LedPos pos)
bool setColorsetMap (LedMap map, const Colorset &set)
void clearPattern (LedPos pos)
void clearPatternMap (LedMap map)
void clearColorset (LedPos pos)
void clearColorsetMap (LedMap map)
void setArg (uint8_t index, uint8_t value, LedMap map)
uint8_t getArg (uint8_t index, LedPos pos)
ModeFlags getFlags () const
bool hasMultiLed () const
bool hasSingleLed () const
bool hasSameSingleLed () const
bool hasSparseSingleLed () const
bool isEmpty () const
LedMap getSingleLedMap () const
bool isMultiLed () const
Private Attributes
VortexEngine & m_engine
Pattern * m_multiPat
std::vector< Pattern * > m_singlePats
Detailed Description
Definition at line 37 of file Mode.h.
Constructor & Destructor Documentation
Mode() [1/6]
Mode::Mode (VortexEngine & engine, uint8_t numLeds)
Definition at line 30 of file Mode.cpp.
                                                :
  m_engine(engine),
#if VORTEX_SLIM == 0
  m_multiPat(nullptr),
#endif
  m_singlePats()
{
  setLedCount(numLeds);
}
References setLedCount().
Mode() [2/6]
Mode::Mode (VortexEngine & engine)
Definition at line 39 of file Mode.cpp.
                               :
  Mode(engine, engine.leds().ledCount())
{
}
Mode() [3/6]
Mode::Mode (VortexEngine & engine, PatternID id, const Colorset & set)
Definition at line 44 of file Mode.cpp.
                                                                  :
  Mode(engine)
{
  setPattern(id, MODE_LED_ANY, nullptr, &set);
}
References MODE_LED_ANY, and setPattern().
Mode() [4/6]
Mode::Mode (VortexEngine & engine, PatternID id, const PatternArgs & args, const Colorset & set)
Definition at line 50 of file Mode.cpp.
                                                                                           :
  Mode(engine)
{
  setPattern(id, MODE_LED_ANY, &args, &set);
}
References MODE_LED_ANY, and setPattern().
Mode() [5/6]
Mode::Mode (VortexEngine & engine, PatternID id, const PatternArgs * args, const Colorset * set)
Definition at line 56 of file Mode.cpp.
                                                                                           :
  Mode(engine)
{
  setPattern(id, MODE_LED_ANY, args, set);
}
References MODE_LED_ANY, and setPattern().
 Mode()
Mode::~Mode ()
Definition at line 62 of file Mode.cpp.
{
  clearPattern(MODE_LED_ALL);
}
References clearPattern(), and MODE_LED_ALL.
Mode() [6/6]
Mode::Mode (const Mode & other)
Definition at line 68 of file Mode.cpp.
                            :
  Mode(other.m_engine)
{
  *this = other;
}
Member Function Documentation
clearColorset()
void Mode::clearColorset (LedPos pos)
Definition at line 676 of file Mode.cpp.
{
  Colorset empty;
  setColorset(empty, pos);
}
References setColorset().
Referenced by clearColorsetMap().
clearColorsetMap()
void Mode::clearColorsetMap (LedMap map)
Definition at line 682 of file Mode.cpp.
{
  MAP_FOREACH_LED(map) {
    clearColorset(pos);
  }
}
References clearColorset(), and MAP_FOREACH_LED.
clearPattern()
void Mode::clearPattern (LedPos pos)
Definition at line 664 of file Mode.cpp.
{
  setPattern(PATTERN_NONE, pos);
}
References PATTERN_NONE, and setPattern().
Referenced by clearPatternMap(), PatternSelect::onShortClick(), operator=(), setPattern(), unserialize(), and ~Mode().
clearPatternMap()
void Mode::clearPatternMap (LedMap map)
Definition at line 669 of file Mode.cpp.
{
  MAP_FOREACH_LED(map) {
    clearPattern(pos);
  }
}
References clearPattern(), and MAP_FOREACH_LED.
equals()
bool Mode::equals (const Mode * other) const
Definition at line 361 of file Mode.cpp.
{
  if (!other) {
    return false;
  }
  // compare the led count
  if (other->getLedCount() != getLedCount()) {
    return false;
  }
#if VORTEX_SLIM == 0
  // compare the multi pattern, either:
  // have a local pat and it's not equal to other (other could be null)
  // or have no local pat and other has one
  if ((m_multiPat && !m_multiPat->equals(other->m_multiPat)) ||
      (!m_multiPat && other->m_multiPat)) {
    return false;
  }
#endif
  // compare all the singles
  for (LedPos pos = LED_FIRST; pos < MODE_LED_COUNT; ++pos) {
    // if entry is valid, do a comparison
    if (m_singlePats[pos]) {
      // checks if other is not null and equal
      if (!m_singlePats[pos]->equals(other->m_singlePats[pos])) {
        return false;
      }
      continue;
    }
    // current is null, check if other is valid
    if (other->m_singlePats[pos]) {
      return false;
    }
    // both are null
  }
  return true;
}
References Pattern::equals(), getLedCount(), LED_FIRST, m_multiPat, m_singlePats, and MODE_LED_COUNT.
Referenced by operator!=(), operator==(), and Vortex::setMenuDemoMode().
getArg()
uint8_t Mode::getArg (uint8_t index, LedPos pos)
Definition at line 700 of file Mode.cpp.
{
  Pattern *pat = getPattern(pos);
  if (!pat) {
    return 0;
  }
  return pat->getArg(index);
}
References Pattern::getArg(), and getPattern().
getColorset() [1/2]
Colorset Mode::getColorset (LedPos pos)
Definition at line 490 of file Mode.cpp.
{
  Pattern *pat = getPattern(pos);
  if (!pat) {
    return Colorset();
  }
  return pat->getColorset();
}
References Pattern::getColorset(), and getPattern().
getColorset() [2/2]
const Colorset Mode::getColorset (LedPos pos) const
Definition at line 485 of file Mode.cpp.
{
  return ((Mode *)this)->getColorset(pos);
}
Referenced by Vortex::getColorset(), ColorSelect::onLedSelected(), and setPattern().
getFlags()
ModeFlags Mode::getFlags () const
Definition at line 709 of file Mode.cpp.
{
  ModeFlags flags = 0;
  if (hasMultiLed()) flags |= MODE_FLAG_MULTI_LED;
  if (hasSingleLed()) flags |= MODE_FLAG_SINGLE_LED;
  if (hasSameSingleLed()) flags |= MODE_FLAG_ALL_SAME_SINGLE;
  if (hasSparseSingleLed()) flags |= MODE_FLAG_SPARSE_SINGLES;
  return flags;
}
References hasMultiLed(), hasSameSingleLed(), hasSingleLed(), hasSparseSingleLed(), MODE_FLAG_ALL_SAME_SINGLE, MODE_FLAG_MULTI_LED, MODE_FLAG_SINGLE_LED, and MODE_FLAG_SPARSE_SINGLES.
Referenced by Vortex::modeToJson(), and serialize().
getLedCount()
uint8_t Mode::getLedCount () const
Definition at line 417 of file Mode.cpp.
{
  return (uint8_t)m_singlePats.size();
}
References m_singlePats.
Referenced by Vortex::checkLedCount(), equals(), Vortex::modeToJson(), Vortex::numLedsInMode(), operator=(), and Vortex::setMenuDemoMode().
getPattern() [1/2]
Pattern * Mode::getPattern (LedPos pos)
Definition at line 427 of file Mode.cpp.
{
  // equivalent to case MODE_LED_ALL
  if (pos == MODE_LED_ALL) {
    // makes no sense
    return nullptr;
  }
  // equivalent to case MODE_LED_ANY and MODE_LED_MULTI
  else if (pos == MODE_LED_ANY || pos == MODE_LED_MULTI) {
    if (m_multiPat) {
      return m_multiPat;
    }
    // Don't fall through if actually multi, it's possible
    // we got here by falling through from MODE_LED_ANY
    else if (pos == MODE_LED_MULTI) {
      return nullptr;
    }
    // For MODE_LED_ANY, try to fall through to MODE_LED_ALL_SINGLE
    else if (pos == MODE_LED_ANY) {
      if (!m_singlePats.size()) {
        return nullptr;
      }
      for (LedPos p = LED_FIRST; p < MODE_LED_COUNT; ++p) {
        if (m_singlePats[p]) {
          return m_singlePats[p];
        }
      }
    }
  }
  // equivalent to case MODE_LED_ALL_SINGLE
  else if (pos == MODE_LED_ALL_SINGLE) {
    if (!m_singlePats.size()) {
      return nullptr;
    }
    for (LedPos p = LED_FIRST; p < MODE_LED_COUNT; ++p) {
      if (m_singlePats[p]) {
        return m_singlePats[p];
      }
    }
  }
  // equivalent to default case (covers any other pos)
  else {
    if (!m_singlePats.size()) {
      return nullptr;
    }
    if (pos < MODE_LED_COUNT && m_singlePats[pos]) {
      return m_singlePats[pos];
    }
  }
  // in case nothing matches, return nullptr
  return nullptr;
}
References LED_FIRST, m_multiPat, m_singlePats, MODE_LED_ALL, MODE_LED_ALL_SINGLE, MODE_LED_ANY, MODE_LED_COUNT, and MODE_LED_MULTI.
getPattern() [2/2]
const Pattern * Mode::getPattern (LedPos pos) const
Definition at line 422 of file Mode.cpp.
{
  return ((Mode *)this)->getPattern(pos);
}
Referenced by getArg(), getColorset(), Vortex::getPatternArgs(), getPatternID(), Randomizer::init(), Vortex::modeToJson(), PatternSelect::onLongClick(), PatternSelect::onShortClick(), Vortex::printPatternJson(), setArg(), and Vortex::setPatternArgs().
getPatternID()
PatternID Mode::getPatternID (LedPos pos) const
Definition at line 499 of file Mode.cpp.
{
  const Pattern *pat = getPattern(pos);
  if (!pat) {
    return PATTERN_NONE;
  }
  return pat->getPatternID();
}
References getPattern(), Pattern::getPatternID(), and PATTERN_NONE.
Referenced by Vortex::getPatternID(), isEmpty(), PatternSelect::onShortClick(), ModeSharing::receiveModeIR(), Randomizer::run(), and Modes::setCurMode().
getSingleLedMap()
LedMap Mode::getSingleLedMap () const
Definition at line 787 of file Mode.cpp.
{
  LedMap map = 0;
  for (LedPos pos = LED_FIRST; pos < MODE_LED_COUNT; pos++) {
    if (m_singlePats[pos]) {
      m_engine.leds().ledmapSetLed(map, pos);
    }
  }
  return map;
}
References LED_FIRST, Leds::ledmapSetLed(), VortexEngine::leds(), m_engine, m_singlePats, and MODE_LED_COUNT.
Referenced by hasSparseSingleLed(), and serialize().
hasMultiLed()
bool Mode::hasMultiLed () const
Definition at line 720 of file Mode.cpp.
{
#if VORTEX_SLIM == 0
  return (m_multiPat != nullptr);
#else
  return false;
#endif
}
References m_multiPat.
Referenced by getFlags(), Randomizer::init(), and isMultiLed().
hasSameSingleLed()
bool Mode::hasSameSingleLed () const
Definition at line 741 of file Mode.cpp.
{
  Pattern *firstPat = nullptr;
  for (LedPos i = LED_FIRST; i < MODE_LED_COUNT; ++i) {
    if (!m_singlePats[i]) {
      continue;
    }
    if (!firstPat) {
      firstPat = m_singlePats[i];
      continue;
    }
    if (!firstPat->equals(m_singlePats[i])) {
      return false;
    }
  }
  // all the same if at least one pattern was found
  return (firstPat != nullptr);
}
References Pattern::equals(), LED_FIRST, m_singlePats, and MODE_LED_COUNT.
Referenced by getFlags(), and Vortex::getModeName().
hasSingleLed()
bool Mode::hasSingleLed () const
Definition at line 730 of file Mode.cpp.
{
  for (LedPos i = LED_FIRST; i < MODE_LED_COUNT; ++i) {
    if (m_singlePats[i]) {
      return true;
    }
  }
  return false;
}
References LED_FIRST, m_singlePats, and MODE_LED_COUNT.
Referenced by getFlags(), and isMultiLed().
hasSparseSingleLed()
bool Mode::hasSparseSingleLed () const
Definition at line 760 of file Mode.cpp.
{
  LedMap map = getSingleLedMap();
  if (map == MAP_LED(MODE_LED_ALL) || map == 0) {
    return false;
  }
  // if anything else is set it's sparse
  return true;
}
References getSingleLedMap(), MAP_LED, and MODE_LED_ALL.
Referenced by getFlags().
init()
void Mode::init ()
Definition at line 103 of file Mode.cpp.
{
#if VORTEX_SLIM == 0
  // initialize the multi pattern if it's present
  if (m_multiPat) {
    m_multiPat->init();
  }
#endif
  // otherwise regular init
  for (LedPos pos = LED_FIRST; pos < MODE_LED_COUNT; ++pos) {
    // grab the entry for this led and initialize it
    Pattern *entry = m_singlePats[pos];
    if (!entry) {
      continue;
    }
    entry->init();
  }
}
References Pattern::init(), LED_FIRST, m_multiPat, m_singlePats, and MODE_LED_COUNT.
Referenced by Modes::addMode(), Modes::addSerializedMode(), EditorConnection::clearDemo(), Menu::init(), loadFromBuffer(), FactoryReset::onLongClick(), ColorSelect::onLongClick(), PatternSelect::onShortClick(), Randomizer::reRoll(), Randomizer::run(), Vortex::setColorset(), Vortex::setMenuDemoMode(), Vortex::setPattern(), Vortex::setPatternArgs(), and Vortex::setPatternAt().
isEmpty()
bool Mode::isEmpty () const
Definition at line 770 of file Mode.cpp.
{
#if VORTEX_SLIM == 0
  if (m_multiPat && m_multiPat->getPatternID() != PATTERN_NONE) {
    return false;
  }
#endif
  for (LedPos i = LED_FIRST; i < MODE_LED_COUNT; ++i) {
    // if any patterns are non-null and not PATTERN_NONE
    if (m_singlePats[i] && m_singlePats[i]->getPatternID() != PATTERN_NONE) {
      // then this mode is not empty
      return false;
    }
  }
  return true;
}
References getPatternID(), Pattern::getPatternID(), LED_FIRST, m_multiPat, m_singlePats, MODE_LED_COUNT, and PATTERN_NONE.
Referenced by ColorSelect::init().
isMultiLed()
bool Mode::isMultiLed () const
Definition at line 799 of file Mode.cpp.
{
#if VORTEX_SLIM == 0
  return hasMultiLed() && !hasSingleLed();
#else
  return false;
#endif
}
References hasMultiLed(), and hasSingleLed().
Referenced by Vortex::getModeName(), FactoryReset::init(), ColorSelect::init(), Vortex::isCurModeMulti(), ColorSelect::isValidLedSelection(), Menu::nextBulbSelection(), and Randomizer::run().
loadFromBuffer()
bool Mode::loadFromBuffer (ByteStream & saveBuffer)
Definition at line 162 of file Mode.cpp.
{
  if (!modeBuffer.decompress()) {
    // failed to decompress the mode
    return false;
  }
  // reset the unserializer index before unserializing anything
  modeBuffer.resetUnserializer();
  uint8_t major = 0;
  uint8_t minor = 0;
  // unserialize the vortex version
  if (!modeBuffer.unserialize8(&major)) {
    return false;
  }
  if (!modeBuffer.unserialize8(&minor)) {
    return false;
  }
  // check the version for incompatibility
  if (!m_engine.checkVersion(major, minor)) {
    // incompatible version
    ERROR_LOGF("Incompatible savefile version: %u.%u", major, minor);
    return false;
  }
  // now just unserialize the list of patterns
  if (!unserialize(modeBuffer)) {
    return false;
  }
  // then initialize the mode so that it is ready to play
  init();
  return true;
}
References VortexEngine::checkVersion(), ByteStream::decompress(), ERROR_LOGF, init(), m_engine, ByteStream::resetUnserializer(), unserialize(), and ByteStream::unserialize8().
Referenced by Modes::ModeLink::instantiate(), EditorConnection::receiveDemoMode(), IRReceiver::receiveMode(), VLReceiver::receiveMode(), and setLedCount().
operator!=()
bool Mode::operator!= (const Mode & other) const
Definition at line 98 of file Mode.cpp.
{
  return !equals(&other);
}
References equals().
operator=()
void Mode::operator= (const Mode & other)
Definition at line 74 of file Mode.cpp.
{
  setLedCount(other.getLedCount());
  clearPattern(MODE_LED_ALL);
#if VORTEX_SLIM == 0
  if (other.m_multiPat) {
    m_multiPat = m_engine.patternBuilder().dupe(other.m_multiPat);
  }
#endif
  for (LedPos i = LED_FIRST; i < other.getLedCount(); ++i) {
    Pattern *otherPat = other.m_singlePats[i];
    if (!otherPat) {
      continue;
    }
    m_singlePats[i] = m_engine.patternBuilder().dupe(otherPat);
  }
}
References clearPattern(), PatternBuilder::dupe(), getLedCount(), LED_FIRST, m_engine, m_multiPat, m_singlePats, MODE_LED_ALL, VortexEngine::patternBuilder(), and setLedCount().
operator==()
bool Mode::operator== (const Mode & other) const
Definition at line 93 of file Mode.cpp.
{
  return equals(&other);
}
References equals().
play()
void Mode::play ()
Definition at line 122 of file Mode.cpp.
{
#if VORTEX_SLIM == 0
  // play multi pattern first so that the singles can override
  if (m_multiPat) {
    m_multiPat->play();
  }
#endif
  // now iterate all singles and play
  for (LedPos pos = LED_FIRST; pos < MODE_LED_COUNT; ++pos) {
    // grab the entry for this led
    Pattern *entry = m_singlePats[pos];
    if (!entry) {
#if VORTEX_SLIM == 0
      // incomplete pattern/set or empty slot
      if (!m_multiPat) {
        // only clear if the multi pattern isn't playing
        m_engine.leds().clearIndex(pos);
      }
#else
      // just clear the index if slim, don't check for multi
      m_engine.leds().clearIndex(pos);
#endif
      continue;
    }
    // play the current pattern with current color set on the current finger
    entry->play();
  }
}
References Leds::clearIndex(), LED_FIRST, VortexEngine::leds(), m_engine, m_multiPat, m_singlePats, MODE_LED_COUNT, and Pattern::play().
Referenced by PatternSelect::run(), Randomizer::run(), EditorConnection::showEditor(), and ModeSharing::showReceiveMode().
saveToBuffer()
bool Mode::saveToBuffer (ByteStream & saveBuffer, uint8_t numLeds = 0) const
Definition at line 152 of file Mode.cpp.
{
  // serialize the engine version into the modes buffer
  m_engine.serializeVersion(modeBuffer);
  // serialize all mode data into the modeBuffer
  serialize(modeBuffer, numLeds);
  DEBUG_LOGF("Serialized mode, uncompressed size: %u", modeBuffer.size());
  return modeBuffer.compress();
}
References ByteStream::compress(), DEBUG_LOGF, m_engine, serialize(), VortexEngine::serializeVersion(), and ByteStream::size().
Referenced by Vortex::getCurMode(), Modes::ModeLink::init(), VLSender::loadMode(), IRSender::loadMode(), and setLedCount().
serialize()
bool Mode::serialize (ByteStream & buffer, uint8_t numLeds = 0) const
Definition at line 194 of file Mode.cpp.
{
  if (!numLeds) {
    numLeds = MODE_LED_COUNT;
  }
  // serialize the number of leds
  if (!buffer.serialize8(numLeds)) {
    return false;
  }
  // empty mode?
  if (!numLeds) {
    return true;
  }
  // serialize the flags
  ModeFlags flags = getFlags();
  if (!buffer.serialize8(flags)) {
    return false;
  }
#if VORTEX_SLIM == 0
  // serialiaze the multi led?
  if ((flags & MODE_FLAG_MULTI_LED) && m_multiPat) {
    // serialize the multi led
    if (!m_multiPat->serialize(buffer)) {
      return false;
    }
  }
#endif
  // if no single leds then just stop here
  if (!(flags & MODE_FLAG_SINGLE_LED)) {
    return true;
  }
  // if there are any sparse singles (spaces) then we need to
  // serialize an led map of which singles are set
  if (flags & MODE_FLAG_SPARSE_SINGLES) {
    if (!buffer.serialize32((uint32_t)getSingleLedMap())) {
      return false;
    }
  }
  // then iterate each single led and serialize it
  for (LedPos pos = LED_FIRST; pos < numLeds; ++pos) {
    const Pattern *entry = m_singlePats[pos];
    if (!entry) {
      continue;
    }
    // just serialize the pattern then colorset
    if (!entry->serialize(buffer)) {
      return false;
    }
    // if they are all same single then only serialize one
    if (flags & MODE_FLAG_ALL_SAME_SINGLE) {
      break;
    }
  }
  return true;
}
References getFlags(), getSingleLedMap(), LED_FIRST, m_multiPat, m_singlePats, MODE_FLAG_ALL_SAME_SINGLE, MODE_FLAG_MULTI_LED, MODE_FLAG_SINGLE_LED, MODE_FLAG_SPARSE_SINGLES, MODE_LED_COUNT, Pattern::serialize(), ByteStream::serialize32(), and ByteStream::serialize8().
Referenced by Modes::saveStorage(), saveToBuffer(), and Modes::serialize().
setArg()
void Mode::setArg (uint8_t index, uint8_t value, LedMap map)
Definition at line 689 of file Mode.cpp.
{
  MAP_FOREACH_LED(map) {
    Pattern *pat = getPattern(pos);
    if (!pat) {
      continue;
    }
    pat->setArg(param, value);
  }
}
References getPattern(), MAP_FOREACH_LED, and Pattern::setArg().
setColorset()
bool Mode::setColorset (const Colorset & set, LedPos pos)
Definition at line 598 of file Mode.cpp.
{
  // Equivalent to cases MODE_LED_ANY, MODE_LED_ALL and MODE_LED_MULTI
  if (pos == MODE_LED_ANY || pos == MODE_LED_ALL || pos == MODE_LED_MULTI) {
#if VORTEX_SLIM == 0
    if (m_multiPat) {
      m_multiPat->setColorset(set);
    }
    if (pos == MODE_LED_MULTI) {
      // don't fallthrough if actually multi, it's possible
      // we got here by falling through from MODE_LED_ALL
      return true;
    }
    // fall through if MODE_LED_ALL and delete the single leds
    else if (pos == MODE_LED_ANY || pos == MODE_LED_ALL) {
      if (!m_singlePats.size()) {
        return false;
      }
      for (LedPos p = LED_FIRST; p < MODE_LED_COUNT; ++p) {
        if (m_singlePats[p]) {
          m_singlePats[p]->setColorset(set);
        }
      }
      return true; // actually break here
    }
#endif
  }
  // equivalent to case MODE_LED_ALL_SINGLE
  else if (pos == MODE_LED_ALL_SINGLE) {
    if (!m_singlePats.size()) {
      return false;
    }
    for (LedPos p = LED_FIRST; p < MODE_LED_COUNT; ++p) {
      if (m_singlePats[p]) {
        m_singlePats[p]->setColorset(set);
      }
    }
    return true;
  }
  // equivalent to default case (covers any other pos)
  else {
    if (!m_singlePats.size()) {
      return false;
    }
    if (pos < MODE_LED_COUNT && m_singlePats[pos]) {
      m_singlePats[pos]->setColorset(set);
      return true;
    }
  }
  return false;
}
References LED_FIRST, m_multiPat, m_singlePats, MODE_LED_ALL, MODE_LED_ALL_SINGLE, MODE_LED_ANY, MODE_LED_COUNT, MODE_LED_MULTI, and Pattern::setColorset().
Referenced by clearColorset(), Randomizer::reRollMulti(), Randomizer::reRollSingles(), Vortex::setColorset(), and setColorsetMap().
setColorsetMap()
bool Mode::setColorsetMap (LedMap map, const Colorset & set)
Definition at line 654 of file Mode.cpp.
{
  MAP_FOREACH_LED(map) {
    if (!setColorset(set, pos)) {
      return false;
    }
  }
  return true;
}
References MAP_FOREACH_LED, and setColorset().
Referenced by ColorSelect::onLongClick().
setLedCount()
bool Mode::setLedCount (uint8_t numLeds)
Definition at line 399 of file Mode.cpp.
{
  ByteStream data;
  if (!saveToBuffer(data)) {
    return false;
  }
  m_singlePats.clear();
  m_singlePats.resize(numLeds);
  if (!m_singlePats.size()) {
    ERROR_OUT_OF_MEMORY();
    return false;
  }
  if (!loadFromBuffer(data)) {
    return false;
  }
  return true;
}
References ERROR_OUT_OF_MEMORY, loadFromBuffer(), m_singlePats, and saveToBuffer().
Referenced by Mode(), Vortex::modeFromJson(), operator=(), and Vortex::setLedCount().
setPattern()
bool Mode::setPattern (PatternID pat, LedPos pos, const PatternArgs * args = nullptr, const Colorset * set = nullptr)
Definition at line 508 of file Mode.cpp.
{
  // Use provided colorset, or colorset from pos if valid, otherwise use effective colorset
  Colorset newSet = set ? *set : getColorset(((pos < MODE_LED_COUNT) && m_singlePats[pos]) ? pos : MODE_LED_ANY);
  // Equivalent to cases MODE_LED_ANY, MODE_LED_ALL and MODE_LED_MULTI
  if (pos == MODE_LED_ANY || pos == MODE_LED_ALL || pos == MODE_LED_MULTI) {
#if VORTEX_SLIM == 0
    if (m_multiPat) {
      delete m_multiPat;
      m_multiPat = nullptr;
    }
    if (isMultiLedPatternID(pat)) {
      m_multiPat = m_engine.patternBuilder().makeMulti(pat, args);
      if (m_multiPat) {
        // they could set PATTERN_NONE to clear
        m_multiPat->setColorset(newSet);
      }
      // TODO: don't clear single leds if we're setting multi
      // but for now it's easier to just clear them
      clearPattern(MODE_LED_ALL_SINGLE);
      return true;
    }
    if (pos == MODE_LED_MULTI) {
      // don't fallthrough if actually multi, it's possible
      // we got here by falling through from MODE_LED_ALL
      return false;
    }
    // fall through if MODE_LED_ALL and delete the single leds
    else if (pos == MODE_LED_ANY || pos == MODE_LED_ALL) {
      if (!m_singlePats.size()) {
        return false;
      }
      for (LedPos p = LED_FIRST; p < MODE_LED_COUNT; ++p) {
        if (!setPattern(pat, p, args, &newSet)) {
          return false;
        }
      }
      return true; // actually break here
    }
#endif
  }
  // equivalent to case MODE_LED_ALL_SINGLE
  else if (pos == MODE_LED_ALL_SINGLE) {
    if (!m_singlePats.size()) {
      return false;
    }
    for (LedPos p = LED_FIRST; p < MODE_LED_COUNT; ++p) {
      if (!setPattern(pat, p, args, &newSet)) {
        return false;
      }
    }
    return true;
  }
  // equivalent to default case (covers any other pos)
  else {
    if (!m_singlePats.size()) {
      return false;
    }
    if (pos >= MODE_LED_COUNT) {
      return false;
    }
    if (m_singlePats[pos]) {
      delete m_singlePats[pos];
    }
    m_singlePats[pos] = m_engine.patternBuilder().makeSingle(pat, args);
    // they could set PATTERN_NONE to clear
    if (m_singlePats[pos]) {
      m_singlePats[pos]->setColorset(newSet);
      m_singlePats[pos]->bind(pos);
    }
    return true;
  }
  return false;
}
References clearPattern(), getColorset(), isMultiLedPatternID(), LED_FIRST, m_engine, m_multiPat, m_singlePats, PatternBuilder::makeMulti(), PatternBuilder::makeSingle(), MODE_LED_ALL, MODE_LED_ALL_SINGLE, MODE_LED_ANY, MODE_LED_COUNT, MODE_LED_MULTI, VortexEngine::patternBuilder(), and Pattern::setColorset().
Referenced by EditorConnection::clearDemo(), clearPattern(), Mode(), Vortex::modeFromJson(), PatternSelect::onShortClick(), Vortex::parsePatternJson(), Randomizer::reRollMulti(), Randomizer::reRollSingles(), Randomizer::rollCustomPattern(), Randomizer::run(), Vortex::setPattern(), Vortex::setPatternAt(), and setPatternMap().
setPatternMap()
bool Mode::setPatternMap (LedMap pos, PatternID pat, const PatternArgs * args = nullptr, const Colorset * set = nullptr)
Definition at line 587 of file Mode.cpp.
{
  MAP_FOREACH_LED(map) {
    if (!setPattern(pat, pos, args, set)) {
      return false;
    }
  }
  return true;
}
References MAP_FOREACH_LED, and setPattern().
Referenced by FactoryReset::onLongClick(), and PatternSelect::onShortClick().
unserialize()
bool Mode::unserialize (ByteStream & buffer)
Definition at line 251 of file Mode.cpp.
{
  clearPattern(MODE_LED_ALL);
  uint8_t ledCount = MODE_LED_COUNT;
  // unserialize the number of leds
  if (!buffer.unserialize8(&ledCount)) {
    return false;
  }
  // adjust the internal led count of the mode if the incoming stream is different
  // generally no embedded device would ever used an unfixed led count, this is purely
  // for vortexlib to allow things like the editor to load modes of any size leds
  if (ledCount != MODE_LED_COUNT) {
    //setLedCount(ledCount);
  }
  if (!ledCount) {
    // empty mode?
    return true;
  }
  // unserialize the flags value
  ModeFlags flags = 0;
  if (!buffer.unserialize8(&flags)) {
    return false;
  }
  Pattern *firstPat = nullptr;
  // if there is a multi led pattern then unserialize it
  if (flags & MODE_FLAG_MULTI_LED) {
#if VORTEX_SLIM == 1
    // unserialize the multi pattern
    Pattern *multiPat = m_engine.patternBuilder().unserialize(buffer);
    // if there are no single leds then discard the firstpat
    if ((flags & MODE_FLAG_SINGLE_LED) != 0 && multiPat) {
      // discard the multi pattern
      delete multiPat;
    } else {
      // otherwise turn on the all same single flag to use the multi as a single
      flags = MODE_FLAG_SINGLE_LED | MODE_FLAG_ALL_SAME_SINGLE;
      firstPat = multiPat;
    }
#else
    // otherwise in normal build actually unserialize it
    m_multiPat = m_engine.patternBuilder().unserialize(buffer);
    if (!m_multiPat) {
      return false;
    }
    m_multiPat->init();
#endif
  }
  // if there is no single led patterns just stop here
  if (!(flags & MODE_FLAG_SINGLE_LED)) {
    return true;
  }
  // is there an led map to unserialize? if not default to all
  LedMap map = (1 << ledCount) - 1;
  if (flags & MODE_FLAG_SPARSE_SINGLES) {
    if (!buffer.unserialize32((uint32_t *)&map)) {
      return false;
    }
  }
  // unserialize all singleled patterns into their positions
  MAP_FOREACH_LED(map) {
    if (pos >= MODE_LED_COUNT) {
      // in case the map encodes led positions this device doesn't support
      break;
    }
    if (!firstPat) {
      // save the first pattern so that it can be duped if this is 'all same'
      m_singlePats[pos] = firstPat = m_engine.patternBuilder().unserialize(buffer);
    } else if (flags & MODE_FLAG_ALL_SAME_SINGLE) {
      // if all same then just dupe first
      m_singlePats[pos] = m_engine.patternBuilder().dupe(firstPat);
    } else {
      // otherwise unserialize the pattern like normal
      m_singlePats[pos] = m_engine.patternBuilder().unserialize(buffer);
    }
    if (!m_singlePats[pos]) {
      clearPattern(MODE_LED_ALL);
      return false;
    }
    if (!m_singlePats[pos]) {
      clearPattern(MODE_LED_ALL);
      return false;
    }
    m_singlePats[pos]->bind(pos);
  }
  // there is a few different possibilities here:
  // 1. The provided ledCount is less than our current MODE_LED_COUNT
  // -> if this happens we need to repeat the first ledCount leds
  // into the remaining MODE_LED_COUNT - ledCount
  // 2. The provided ledCount is more than our current MODE_LED_COUNT
  // -> if this happens then we can just chop the leds and continue
  // 3. The provided ledCount is the same as our current MODE_LED_COUNT
  // -> if this happens all is good we can continue
  if (ledCount >= MODE_LED_COUNT) {
    // in this case we either chopped some off or have the exact amount
    return true;
  }
  // in this case we have to repeat them so we loop MODE_LED_COUNT - ledCount
  // times and walk the first ledCount that are already set and copy them
  LedPos src = LED_FIRST;
  // start from ledCount (the first index we didn't load) and loop till
  // MODE_LED_COUNT and dupe the pattern in the src position, but wrap the src
  // around at ledCount so that we repeat the first ledCount over again
  for (LedPos pos = (LedPos)ledCount; pos < MODE_LED_COUNT; ++pos) {
    m_singlePats[pos] = m_engine.patternBuilder().dupe(m_singlePats[src]);
    m_singlePats[pos]->bind(pos);
    src = (LedPos)((src + 1) % ledCount);
  }
  return true;
}
References clearPattern(), PatternBuilder::dupe(), Pattern::init(), LED_FIRST, m_engine, m_multiPat, m_singlePats, MAP_FOREACH_LED, MODE_FLAG_ALL_SAME_SINGLE, MODE_FLAG_MULTI_LED, MODE_FLAG_SINGLE_LED, MODE_FLAG_SPARSE_SINGLES, MODE_LED_ALL, MODE_LED_COUNT, VortexEngine::patternBuilder(), PatternBuilder::unserialize(), ByteStream::unserialize32(), and ByteStream::unserialize8().
Referenced by Modes::addSerializedMode(), and loadFromBuffer().
Member Data Documentation
m_engine
VortexEngine& Mode::m_engine [private]
Definition at line 137 of file Mode.h.
Referenced by getSingleLedMap(), loadFromBuffer(), operator=(), play(), saveToBuffer(), setPattern(), and unserialize().
m_multiPat
Pattern* Mode::m_multiPat [private]
Definition at line 141 of file Mode.h.
Referenced by equals(), getPattern(), hasMultiLed(), init(), isEmpty(), operator=(), play(), serialize(), setColorset(), setPattern(), and unserialize().
m_singlePats
std::vector<Pattern *> Mode::m_singlePats [private]
Definition at line 144 of file Mode.h.
Referenced by equals(), getLedCount(), getPattern(), getSingleLedMap(), hasSameSingleLed(), hasSingleLed(), init(), isEmpty(), operator=(), play(), serialize(), setColorset(), setLedCount(), setPattern(), and unserialize().
The documentation for this class was generated from the following files:
VortexEngine/src/Modes/Mode.h
VortexEngine/src/Modes/Mode.cpp