Modes Class Reference
#include <Modes.h>
Classes
class ModeLink
Public Member Functions
Modes (VortexEngine &engine)
~Modes ()
bool init ()
void cleanup ()
bool load ()
void play ()
bool saveToBuffer (ByteStream &saveBuffer)
bool loadFromBuffer (ByteStream &saveBuffer)
bool saveHeader ()
bool loadHeader ()
bool saveStorage ()
bool loadStorage ()
bool serializeSaveHeader (ByteStream &saveBuffer)
bool unserializeSaveHeader (ByteStream &saveBuffer)
bool serialize (ByteStream &buffer)
bool unserialize (ByteStream &buffer)
bool setDefaults ()
bool shiftCurMode (int32_t offset=1)
bool addMode (PatternID id, RGBColor c1, RGBColor c2=RGB_OFF, RGBColor c3=RGB_OFF, RGBColor c4=RGB_OFF, RGBColor c5=RGB_OFF, RGBColor c6=RGB_OFF, RGBColor c7=RGB_OFF, RGBColor c8=RGB_OFF)
bool addMode (PatternID id, const PatternArgs *args, const Colorset *set)
bool addMode (const Mode *mode)
bool addSerializedMode (ByteStream &serializedMode)
bool addModeFromBuffer (ByteStream &serializedMode)
bool updateCurMode (const Mode *mode)
Mode * setCurMode (uint8_t index)
Mode * curMode ()
Mode * nextMode ()
Mode * previousMode ()
bool curModeInstantiated ()
Mode * nextModeSkipEmpty ()
uint8_t numModes ()
uint8_t curModeIndex ()
uint32_t lastSwitchTime ()
void deleteCurMode ()
void clearModes ()
void setStartupMode (uint8_t index)
uint8_t startupMode ()
Mode * switchToStartupMode ()
Mode * initCurMode (bool force=false)
bool saveCurMode ()
bool setFlag (uint8_t flag, bool enable, bool save=true)
bool getFlag (uint8_t flag)
void resetFlags ()
bool setOneClickMode (bool enable, bool save=true)
bool oneClickModeEnabled ()
bool setLocked (bool locked, bool save=true)
bool locked ()
bool setAdvancedMenus (bool active, bool save=true)
bool advancedMenusEnabled ()
bool setKeychainMode (bool active, bool save=true)
bool keychainModeEnabled ()
Private Member Functions
ModeLink * getModeLink (uint32_t index)
Private Attributes
VortexEngine & m_engine
bool m_loaded
uint8_t m_curMode
uint8_t m_numModes
ModeLink * m_pCurModeLink
ModeLink * m_storedModes
uint8_t m_globalFlags
uint32_t m_lastSwitchTime
Detailed Description
Definition at line 29 of file Modes.h.
Constructor & Destructor Documentation
Modes()
Modes::Modes (VortexEngine & engine)
Definition at line 18 of file Modes.cpp.
                                 :
  m_engine(engine),
  m_curMode(0),
  m_numModes(0),
  m_pCurModeLink(nullptr),
  m_storedModes(nullptr),
  m_globalFlags(0),
  m_lastSwitchTime(0)
{
}
 Modes()
Modes::~Modes ()
Definition at line 28 of file Modes.cpp.
{
}
Member Function Documentation
addMode() [1/3]
bool Modes::addMode (const Mode * mode)
Definition at line 507 of file Modes.cpp.
{
#if MAX_MODES != 0
  // max modes
  if (m_numModes >= MAX_MODES) {
    return false;
  }
#endif
  if (!m_storedModes) {
    m_storedModes = new ModeLink(m_engine, mode);
    if (!m_storedModes) {
      ERROR_OUT_OF_MEMORY();
      return false;
    }
  } else {
    if (!m_storedModes->append(mode)) {
      ERROR_OUT_OF_MEMORY();
      return false;
    }
  }
  m_numModes++;
  return true;
}
References Modes::ModeLink::append(), ERROR_OUT_OF_MEMORY, m_engine, m_numModes, m_storedModes, and MAX_MODES.
addMode() [2/3]
bool Modes::addMode (PatternID id, const PatternArgs * args, const Colorset * set)
Definition at line 488 of file Modes.cpp.
{
  // max modes
#if MAX_MODES != 0
  if (m_numModes >= MAX_MODES) {
    return false;
  }
#endif
  if (id >= PATTERN_COUNT) {
    return false;
  }
  Mode tmpMode(m_engine, id, args, set);
  // must init the mode so that it can be serialized
  tmpMode.init();
  // not a very good way to do this but it ensures the mode is
  // added in the same way
  return addMode(&tmpMode);
}
References addMode(), Mode::init(), m_engine, m_numModes, MAX_MODES, and PATTERN_COUNT.
addMode() [3/3]
bool Modes::addMode (PatternID id, RGBColor c1, RGBColor c2 = RGB_OFF, RGBColor c3 = RGB_OFF, RGBColor c4 = RGB_OFF, RGBColor c5 = RGB_OFF, RGBColor c6 = RGB_OFF, RGBColor c7 = RGB_OFF, RGBColor c8 = RGB_OFF)
Definition at line 481 of file Modes.cpp.
{
  Colorset set(c1, c2, c3, c4, c5, c6, c7, c8);
  return addMode(id, nullptr, &set);
}
Referenced by Vortex::addMode(), addMode(), Vortex::addNewMode(), addSerializedMode(), Menu::init(), Vortex::loadModeFromJson(), and setDefaults().
addModeFromBuffer()
bool Modes::addModeFromBuffer (ByteStream & serializedMode)
Definition at line 416 of file Modes.cpp.
{
#if MAX_MODES != 0
  if (m_numModes >= MAX_MODES) {
    return false;
  }
#endif
  if (!m_storedModes) {
    m_storedModes = new ModeLink(m_engine, serializedMode);
    if (!m_storedModes) {
      ERROR_OUT_OF_MEMORY();
      return false;
    }
  } else {
    if (!m_storedModes->append(serializedMode)) {
      ERROR_OUT_OF_MEMORY();
      return false;
    }
  }
  // increment mode counter
  m_numModes++;
  return true;
}
References Modes::ModeLink::append(), ERROR_OUT_OF_MEMORY, m_engine, m_numModes, m_storedModes, and MAX_MODES.
Referenced by Vortex::addNewMode().
addSerializedMode()
bool Modes::addSerializedMode (ByteStream & serializedMode)
Definition at line 396 of file Modes.cpp.
{
#if MAX_MODES != 0
  if (m_numModes >= MAX_MODES) {
    return false;
  }
#endif
  // we must unserialize then re-serialize here because the
  // input argument may contain other patterns in the buffer
  // so we cannot just append the input arg to m_storedModes
  Mode tmpMode(m_engine);
  if (!tmpMode.unserialize(serializedMode)) {
    return false;
  }
  // initialize the mode because a pattern could theoretically serialize
  // differently after it has initialized
  tmpMode.init();
  return addMode(&tmpMode);
}
References addMode(), Mode::init(), m_engine, m_numModes, MAX_MODES, and Mode::unserialize().
Referenced by loadStorage(), and unserialize().
advancedMenusEnabled()
bool Modes::advancedMenusEnabled () [inline]
Definition at line 155 of file Modes.h.
                              {
    return getFlag(MODES_FLAG_ADV_MENUS);
  }
References getFlag(), and MODES_FLAG_ADV_MENUS.
Referenced by Menus::runMenuSelection().
cleanup()
void Modes::cleanup ()
Definition at line 50 of file Modes.cpp.
{
  clearModes();
}
References clearModes().
Referenced by VortexEngine::cleanup().
clearModes()
void Modes::clearModes ()
Definition at line 661 of file Modes.cpp.
{
  if (!m_numModes || !m_storedModes) {
    return;
  }
  // delete the first node and it will delete the entire chain
  delete m_storedModes;
  m_pCurModeLink = nullptr;
  m_storedModes = nullptr;
  m_numModes = 0;
  // might as well clear the leds
  m_engine.leds().clearAll();
}
References Leds::clearAll(), VortexEngine::leds(), m_engine, m_numModes, m_pCurModeLink, and m_storedModes.
Referenced by cleanup(), VortexCLI::init(), Vortex::loadFromJson(), loadHeader(), loadStorage(), setDefaults(), Vortex::setModes(), and unserialize().
curMode()
Mode * Modes::curMode ()
Definition at line 591 of file Modes.cpp.
{
  // empty mode list
  if (!m_numModes) {
    return nullptr;
  }
  if (!m_pCurModeLink) {
    if (!initCurMode()) {
      ERROR_LOG("Failed to initialize current mode");
      return nullptr;
    }
  }
  // get current mode, instantiate it if necessary
  return m_pCurModeLink->instantiate();
}
References ERROR_LOG, initCurMode(), Modes::ModeLink::instantiate(), m_numModes, and m_pCurModeLink.
Referenced by ModeSharing::beginSendingIR(), ModeSharing::beginSendingVL(), Vortex::checkLedCount(), VortexEngine::curMode(), Vortex::getColorset(), Vortex::getCurMode(), Vortex::getModeName(), Vortex::getPatternArgs(), Vortex::getPatternID(), Menu::init(), ColorSelect::init(), FactoryReset::init(), Randomizer::init(), Vortex::isCurModeMulti(), Menu::nextBulbSelection(), nextModeSkipEmpty(), Vortex::numLedsInMode(), ColorSelect::onLedSelected(), ColorSelect::onLongClick(), FactoryReset::onLongClick(), Vortex::parsePatternJson(), Vortex::printModeJson(), Vortex::printPatternJson(), Vortex::saveModeToJson(), Vortex::setColorset(), Vortex::setLedCount(), Vortex::setPattern(), Vortex::setPatternArgs(), Vortex::setPatternAt(), and updateCurMode().
curModeIndex()
uint8_t Modes::curModeIndex () [inline]
Definition at line 110 of file Modes.h.
{ return m_curMode; }
References m_curMode.
Referenced by Vortex::curModeIndex(), VortexEngine::enterSleep(), and FactoryReset::onLongClick().
curModeInstantiated()
bool Modes::curModeInstantiated () [inline]
Definition at line 102 of file Modes.h.
{ return (m_pCurModeLink && m_pCurModeLink->mode() != nullptr); }
References m_pCurModeLink, and Modes::ModeLink::mode().
Referenced by Vortex::setLedCount().
deleteCurMode()
void Modes::deleteCurMode ()
Definition at line 640 of file Modes.cpp.
{
  if (!m_numModes || !m_pCurModeLink) {
    return;
  }
  // unlink the current mode so it can be deleted and
  // update the current mode link accordingly
  ModeLink *newCur = m_pCurModeLink->unlinkSelf();
  delete m_pCurModeLink;
  m_pCurModeLink = newCur;
  if (m_curMode) {
    m_curMode--;
  } else {
    m_storedModes = m_pCurModeLink;
  }
  m_numModes--;
  if (!m_numModes) {
    m_storedModes = nullptr;
  }
}
References m_curMode, m_numModes, m_pCurModeLink, m_storedModes, and Modes::ModeLink::unlinkSelf().
Referenced by Vortex::delCurMode().
getFlag()
bool Modes::getFlag (uint8_t flag) [inline]
Definition at line 133 of file Modes.h.
{ return ((m_globalFlags & flag) != 0); }
References m_globalFlags.
Referenced by advancedMenusEnabled(), keychainModeEnabled(), locked(), and oneClickModeEnabled().
getModeLink()
Modes::ModeLink * Modes::getModeLink (uint32_t index) [private]
Definition at line 776 of file Modes.cpp.
{
  if (index >= m_numModes) {
    return nullptr;
  }
  ModeLink *ptr = m_storedModes;
  while (index > 0 && ptr) {
    ptr = ptr->next();
    index--;
  }
  return ptr;
}
References m_numModes, m_storedModes, and Modes::ModeLink::next().
Referenced by initCurMode(), setCurMode(), and shiftCurMode().
init()
bool Modes::init ()
Definition at line 32 of file Modes.cpp.
{
#if MODES_TEST == 1
  Mode::test();
  test();
  return true;
#endif
  ByteStream headerBuffer;
  m_engine.storage().read(0, headerBuffer);
  unserializeSaveHeader(headerBuffer);
  m_loaded = false;
#ifdef VORTEX_LIB
  // enable the adv menus by default in vortex lib
  m_globalFlags |= MODES_FLAG_ADV_MENUS;
#endif
  return true;
}
References m_engine, m_globalFlags, m_loaded, MODES_FLAG_ADV_MENUS, Storage::read(), VortexEngine::storage(), and unserializeSaveHeader().
Referenced by VortexEngine::init().
initCurMode()
Mode * Modes::initCurMode (bool force = false)
Definition at line 789 of file Modes.cpp.
{
  if (!m_numModes) {
    return nullptr;
  }
  // cleanup the current mode link
  if (m_pCurModeLink) {
    m_pCurModeLink->uninstantiate();
  }
  // update the current mode link based on the curmode index
  m_pCurModeLink = getModeLink(m_curMode);
  if (!m_pCurModeLink) {
    return nullptr;
  }
  if (force) {
    m_pCurModeLink->uninstantiate();
  }
  return m_pCurModeLink->instantiate();
}
References getModeLink(), Modes::ModeLink::instantiate(), m_curMode, m_numModes, m_pCurModeLink, and Modes::ModeLink::uninstantiate().
Referenced by curMode(), play(), and updateCurMode().
keychainModeEnabled()
bool Modes::keychainModeEnabled () [inline]
Definition at line 162 of file Modes.h.
                             {
    return getFlag(MODES_FLAG_KEYCHAIN);
  }
References getFlag(), and MODES_FLAG_KEYCHAIN.
lastSwitchTime()
uint32_t Modes::lastSwitchTime () [inline]
Definition at line 113 of file Modes.h.
{ return m_lastSwitchTime; }
References m_lastSwitchTime.
Referenced by VortexEngine::runMainLogic().
load()
bool Modes::load ()
Definition at line 55 of file Modes.cpp.
{
  if (m_loaded) {
    return true;
  }
  // try to load the saved settings or set defaults
  if (!loadStorage()) {
    if (!setDefaults()) {
      return false;
    }
    if (!saveStorage()) {
      return false;
    }
  }
  m_loaded = true;
  return true;
}
References loadStorage(), m_loaded, saveStorage(), and setDefaults().
Referenced by Vortex::init(), and VortexEngine::runMainLogic().
loadFromBuffer()
bool Modes::loadFromBuffer (ByteStream & saveBuffer)
Definition at line 112 of file Modes.cpp.
{
  if (!modesBuffer.decompress()) {
    // failed to decompress?
    return false;
  }
  // read out the header first
  if (!unserializeSaveHeader(modesBuffer)) {
    return false;
  }
  // now just unserialize the list of modes
  if (!unserialize(modesBuffer)) {
    return false;
  }
  if (oneClickModeEnabled()) {
    // set the current mode to the startup mode
    switchToStartupMode();
  }
  return true;
}
References ByteStream::decompress(), oneClickModeEnabled(), switchToStartupMode(), unserialize(), and unserializeSaveHeader().
Referenced by EditorConnection::receiveModes(), and Vortex::setModes().
loadHeader()
bool Modes::loadHeader ()
Definition at line 149 of file Modes.cpp.
{
  ByteStream headerBuffer;
  // only read storage if the modebuffer isn't filled
  if (!m_engine.storage().read(0, headerBuffer) || !headerBuffer.size()) {
    DEBUG_LOG("Empty buffer read from storage");
    // this kinda sucks whatever they had loaded is gone
    return false;
  }
  // this erases what is stored before we know whether there is data
  // but it's the easiest way to just re-load new data from storage
  clearModes();
  // read the header and load the data
  if (!unserializeSaveHeader(headerBuffer)) {
    return false;
  }
  // NOTE: We do not bother loading the number of modes because
  // we can't really do anything with it anyway
  return true;
}
References clearModes(), DEBUG_LOG, m_engine, Storage::read(), ByteStream::size(), VortexEngine::storage(), and unserializeSaveHeader().
loadStorage()
bool Modes::loadStorage ()
Definition at line 213 of file Modes.cpp.
{
  // NOTE: We could call loadHeader here but then we wouldn't have the headerBuffer
  // and in turn wouldn't be able to unserialize the number of modes. The number
  // of modes is a weird case, it's technically part of the mode list not the
  // header but it is stored in the same storage slot as the header
  ByteStream headerBuffer;
  // only read storage if the modebuffer isn't filled
  if (!m_engine.storage().read(0, headerBuffer) || !headerBuffer.size()) {
    DEBUG_LOG("Empty buffer read from storage");
    // this kinda sucks whatever they had loaded is gone
    return false;
  }
  // this erases what is stored before we know whether there is data
  // but it's the easiest way to just re-load new data from storage
  clearModes();
  // read the header and load the data
  if (!unserializeSaveHeader(headerBuffer)) {
    return false;
  }
  // unserialize the number of modes next
  uint8_t numModes = 0;
  if (!headerBuffer.unserialize8(&numModes)) {
    return false;
  }
  if (!numModes) {
    DEBUG_LOG("Did not find any modes");
    // this kinda sucks whatever they had loaded is gone
    return false;
  }
  // iterate each mode and read it out of it's storage slot then add it
  for (uint8_t i = 0; i < numModes; ++i) {
    ByteStream modeBuffer(MAX_MODE_SIZE);
    // read each mode from a storage slot and load it
    if (!m_engine.storage().read(i + 1, modeBuffer) || !addSerializedMode(modeBuffer)) {
      return false;
    }
  }
  if (oneClickModeEnabled()) {
    // set the current mode to the startup mode
    switchToStartupMode();
  }
  return true;
}
References addSerializedMode(), clearModes(), DEBUG_LOG, m_engine, MAX_MODE_SIZE, numModes(), oneClickModeEnabled(), Storage::read(), ByteStream::size(), VortexEngine::storage(), switchToStartupMode(), ByteStream::unserialize8(), and unserializeSaveHeader().
Referenced by load(), and Vortex::loadStorage().
locked()
bool Modes::locked () [inline]
Definition at line 148 of file Modes.h.
                {
    return getFlag(MODES_FLAG_LOCKED);
  }
References getFlag(), and MODES_FLAG_LOCKED.
Referenced by setLocked(), and VortexEngine::tick().
nextMode()
Mode * Modes::nextMode ()
Definition at line 608 of file Modes.cpp.
{
  if (!m_numModes) {
    return nullptr;
  }
  // iterate the cur mode forward
  return setCurMode(m_curMode + 1);
}
References m_curMode, m_numModes, and setCurMode().
Referenced by Vortex::nextMode(), play(), VortexEngine::runMainLogic(), and Vortex::saveToJson().
nextModeSkipEmpty()
Mode * Modes::nextModeSkipEmpty ()
Definition at line 630 of file Modes.cpp.
{
  do {
    if (setCurMode(m_curMode + 1) && !curMode()->isEmpty()) {
      break;
    }
  } while (m_curMode != 0);
  return curMode();
}
References curMode(), m_curMode, and setCurMode().
numModes()
uint8_t Modes::numModes () [inline]
Definition at line 109 of file Modes.h.
{ return m_numModes; }
References m_numModes.
Referenced by Vortex::delCurMode(), Menu::init(), Vortex::loadFromJson(), loadStorage(), Vortex::nextMode(), Vortex::numModes(), previousMode(), Vortex::saveToJson(), Vortex::setCurMode(), Vortex::shiftCurMode(), and unserialize().
oneClickModeEnabled()
bool Modes::oneClickModeEnabled () [inline]
Definition at line 141 of file Modes.h.
                             {
    return getFlag(MODES_FLAG_ONE_CLICK);
  }
References getFlag(), and MODES_FLAG_ONE_CLICK.
Referenced by loadFromBuffer(), and loadStorage().
play()
void Modes::play ()
Definition at line 73 of file Modes.cpp.
{
  if (!m_numModes) {
    // nothing to do just keep the leds cleared
    m_engine.leds().clearAll();
    return;
  }
  // should be able to initialize the current mode
  if (!m_pCurModeLink && !initCurMode()) {
    DEBUG_LOG("Error failed to load any modes!");
    return;
  }
  // shortclick cycles to the next mode
  if (m_engine.button().onShortClick()) {
    nextMode();
  }
  // play the current mode
  m_pCurModeLink->play();
}
References VortexEngine::button(), Leds::clearAll(), DEBUG_LOG, initCurMode(), VortexEngine::leds(), m_engine, m_numModes, m_pCurModeLink, nextMode(), Button::onShortClick(), and Modes::ModeLink::play().
Referenced by VortexEngine::runMainLogic().
previousMode()
Mode * Modes::previousMode ()
Definition at line 618 of file Modes.cpp.
{
  if (!m_numModes) {
    return nullptr;
  }
  // iterate the cur mode backwards
  if (!m_curMode) {
    return setCurMode(numModes() - 1);
  }
  return setCurMode(m_curMode - 1);
}
References m_curMode, m_numModes, numModes(), and setCurMode().
resetFlags()
void Modes::resetFlags () [inline]
Definition at line 135 of file Modes.h.
{ m_globalFlags = 0; }
References m_globalFlags.
Referenced by FactoryReset::onLongClick().
saveCurMode()
bool Modes::saveCurMode ()
Definition at line 809 of file Modes.cpp.
{
  if (!m_pCurModeLink) {
    // if there's no loaded mode currently then there's nothing
    // to save so there's no error
    return false;
  }
  // force the current mode to save back to serial to catch changes
  return m_pCurModeLink->save();
}
References m_pCurModeLink, and Modes::ModeLink::save().
Referenced by saveStorage(), serialize(), and updateCurMode().
saveHeader()
bool Modes::saveHeader ()
Definition at line 133 of file Modes.cpp.
{
  ByteStream headerBuffer(MAX_MODE_SIZE);
  if (!serializeSaveHeader(headerBuffer)) {
    return false;
  }
  // serialize the number of modes
  if (!headerBuffer.serialize8(m_numModes)) {
    return false;
  }
  if (!m_engine.storage().write(0, headerBuffer)) {
    return false;
  }
  return true;
}
References m_engine, m_numModes, MAX_MODE_SIZE, ByteStream::serialize8(), serializeSaveHeader(), VortexEngine::storage(), and Storage::write().
Referenced by saveStorage(), setFlag(), and unserializeSaveHeader().
saveStorage()
bool Modes::saveStorage ()
Definition at line 172 of file Modes.cpp.
{
  DEBUG_LOG("Saving modes...");
  saveHeader();
  // make sure the current mode is saved in case it has changed somehow
  saveCurMode();
  // uninstantiate cur mode so we have stack space to serialize
  if (m_pCurModeLink) {
    m_pCurModeLink->uninstantiate();
  }
  uint8_t i = 0;
  ModeLink *ptr = m_storedModes;
  while (ptr && i < MAX_MODES) {
    ByteStream modeBuffer(MAX_MODE_SIZE);
    // instantiate the mode temporarily
    Mode *mode = ptr->instantiate();
    if (!mode) {
      ERROR_OUT_OF_MEMORY();
      return false;
    }
    // serialize it into the target modes buffer
    if (!mode->serialize(modeBuffer)) {
      return false;
    }
    // just uninstansiate the mode after serializing
    ptr->uninstantiate();
    // next mode
    ptr = ptr->next();
    // now write this mode into a storage slot (skip first slot, that's header)
    if (!m_engine.storage().write(++i, modeBuffer)) {
      return false;
    }
  }
  // reinstanstiate the current mode
  if (m_pCurModeLink && !m_pCurModeLink->instantiate()) {
    return false;
  }
  DEBUG_LOGF("Serialized num modes: %u", m_numModes);
  return true;
}
References DEBUG_LOG, DEBUG_LOGF, ERROR_OUT_OF_MEMORY, Modes::ModeLink::instantiate(), m_engine, m_numModes, m_pCurModeLink, m_storedModes, MAX_MODE_SIZE, MAX_MODES, Modes::ModeLink::next(), saveCurMode(), saveHeader(), Mode::serialize(), VortexEngine::storage(), Modes::ModeLink::uninstantiate(), and Storage::write().
Referenced by Vortex::doSave(), VortexEngine::enterSleep(), Vortex::getCurMode(), Menu::leaveMenu(), load(), and EditorConnection::receiveModes().
saveToBuffer()
bool Modes::saveToBuffer (ByteStream & saveBuffer)
Definition at line 94 of file Modes.cpp.
{
  // first write out the header
  if (!serializeSaveHeader(modesBuffer)) {
    return false;
  }
  // serialize all modes data into the modesBuffer
  if (!serialize(modesBuffer)) {
    return false;
  }
  DEBUG_LOGF("Serialized all modes, uncompressed size: %u", modesBuffer.size());
  if (!modesBuffer.compress()) {
    return false;
  }
  return true;
}
References ByteStream::compress(), DEBUG_LOGF, serialize(), serializeSaveHeader(), and ByteStream::size().
Referenced by Vortex::getModes(), and EditorConnection::sendModes().
serialize()
bool Modes::serialize (ByteStream & buffer)
Definition at line 314 of file Modes.cpp.
{
  // serialize the number of modes
  if (!modesBuffer.serialize8(m_numModes)) {
    return false;
  }
  // make sure the current mode is saved in case it has changed somehow
  saveCurMode();
  // uninstantiate cur mode so we have stack space to serialize
  if (m_pCurModeLink) {
    m_pCurModeLink->uninstantiate();
  }
  ModeLink *ptr = m_storedModes;
  while (ptr) {
    // instantiate the mode temporarily
    Mode *mode = ptr->instantiate();
    if (!mode) {
      ERROR_OUT_OF_MEMORY();
      return false;
    }
    // serialize it into the target modes buffer
    if (!mode->serialize(modesBuffer)) {
      return false;
    }
    // just uninstansiate the mode after serializing
    ptr->uninstantiate();
    // next mode
    ptr = ptr->next();
  }
  // reinstanstiate the current mode
  if (m_pCurModeLink && !m_pCurModeLink->instantiate()) {
    return false;
  }
  DEBUG_LOGF("Serialized num modes: %u", m_numModes);
  return true;
}
References DEBUG_LOGF, ERROR_OUT_OF_MEMORY, Modes::ModeLink::instantiate(), m_numModes, m_pCurModeLink, m_storedModes, Modes::ModeLink::next(), saveCurMode(), Mode::serialize(), ByteStream::serialize8(), and Modes::ModeLink::uninstantiate().
Referenced by saveToBuffer().
serializeSaveHeader()
bool Modes::serializeSaveHeader (ByteStream & saveBuffer)
Definition at line 258 of file Modes.cpp.
{
  // serialize the engine version into the modes buffer
  if (!m_engine.serializeVersion(saveBuffer)) {
    return false;
  }
  // NOTE: instead of global brightness the duo uses this to store the
  // startup mode ID. The duo doesn't offer a global brightness option
  if (!saveBuffer.serialize8(m_globalFlags)) {
    return false;
  }
  // serialize the global brightness
  if (!saveBuffer.serialize8((uint8_t)m_engine.leds().getBrightness())) {
    return false;
  }
  DEBUG_LOGF("Serialized all modes, uncompressed size: %u", saveBuffer.size());
  return true;
}
References DEBUG_LOGF, Leds::getBrightness(), VortexEngine::leds(), m_engine, m_globalFlags, ByteStream::serialize8(), VortexEngine::serializeVersion(), and ByteStream::size().
Referenced by saveHeader(), and saveToBuffer().
setAdvancedMenus()
bool Modes::setAdvancedMenus (bool active, bool save = true) [inline]
Definition at line 152 of file Modes.h.
                                                       {
    return setFlag(MODES_FLAG_ADV_MENUS, active, save);
  }
References MODES_FLAG_ADV_MENUS, and setFlag().
Referenced by Menus::runMenuSelection().
setCurMode()
Mode * Modes::setCurMode (uint8_t index)
Definition at line 551 of file Modes.cpp.
{
  if (!m_numModes) {
    return nullptr;
  }
  // clear the LEDs when switching modes
  m_engine.leds().clearAll();
  // if we have a current mode open, close it
  if (m_pCurModeLink) {
    m_pCurModeLink->uninstantiate();
  }
  int8_t newModeIdx = index % m_numModes;
  // lookup the new mode link
  ModeLink *newCurLink = getModeLink(newModeIdx);
  if (!newCurLink) {
    // what
    return nullptr;
  }
  // instantiate the new mode so it is ready, also so it can be checked for PATTERN_NONE
  Mode *newCur = newCurLink->instantiate();
  if (!newCur) {
    ERROR_OUT_OF_MEMORY();
    return nullptr;
  }
  // update to the new mode
  m_curMode = newModeIdx;
  m_pCurModeLink = newCurLink;
  // record the current time as the last switch time
  m_lastSwitchTime = m_engine.time().getCurtime();
  // update the global startup mode to be this mode, if we turn off
  // and turn back on into one click mode it will select this one
  Modes::setStartupMode(newModeIdx);
  // log the change
  DEBUG_LOGF("Switch to Mode: %u / %u (pattern id: %u)",
    m_curMode, m_numModes - 1, newCur->getPatternID());
  // return the new current mode
  return newCur;
}
References Leds::clearAll(), DEBUG_LOGF, ERROR_OUT_OF_MEMORY, Time::getCurtime(), getModeLink(), Mode::getPatternID(), Modes::ModeLink::instantiate(), VortexEngine::leds(), m_curMode, m_engine, m_lastSwitchTime, m_numModes, m_pCurModeLink, setStartupMode(), VortexEngine::time(), and Modes::ModeLink::uninstantiate().
Referenced by nextMode(), nextModeSkipEmpty(), FactoryReset::onLongClick(), previousMode(), Vortex::saveToJson(), Vortex::setCurMode(), and switchToStartupMode().
setDefaults()
bool Modes::setDefaults ()
Definition at line 384 of file Modes.cpp.
{
  clearModes();
  // add each default mode with each of the given colors
  for (uint8_t i = 0; i < num_default_modes; ++i) {
    const default_mode_entry &def = default_modes[i];
    Colorset set(def.numColors, def.cols);
    addMode(def.patternID, nullptr, &set);
  }
  return true;
}
References addMode(), clearModes(), default_mode_entry::cols, default_modes, num_default_modes, default_mode_entry::numColors, and default_mode_entry::patternID.
Referenced by load(), and FactoryReset::onLongClick().
setFlag()
bool Modes::setFlag (uint8_t flag, bool enable, bool save = true)
Definition at line 694 of file Modes.cpp.
{
  // then actually if it's enabled ensure the upper nibble is set
  if (enable) {
    // set the cur mode index as the upper nibble
    m_globalFlags |= flag;
  } else {
    m_globalFlags &= ~flag;
  }
  DEBUG_LOGF("Toggled instant on/off to %s", enable ? "on" : "off");
  return !save || saveHeader();
}
References DEBUG_LOGF, m_globalFlags, and saveHeader().
Referenced by Vortex::loadFromJson(), setAdvancedMenus(), setKeychainMode(), setLocked(), and setOneClickMode().
setKeychainMode()
bool Modes::setKeychainMode (bool active, bool save = true) [inline]
Definition at line 159 of file Modes.h.
                                                      {
    return setFlag(MODES_FLAG_KEYCHAIN, active, save);
  }
References MODES_FLAG_KEYCHAIN, and setFlag().
setLocked()
bool Modes::setLocked (bool locked, bool save = true) [inline]
Definition at line 145 of file Modes.h.
                                                {
    return setFlag(MODES_FLAG_LOCKED, locked, save);
  }
References locked(), MODES_FLAG_LOCKED, and setFlag().
Referenced by VortexEngine::tick().
setOneClickMode()
bool Modes::setOneClickMode (bool enable, bool save = true) [inline]
Definition at line 138 of file Modes.h.
                                                      {
    return setFlag(MODES_FLAG_ONE_CLICK, enable, save);
  }
References MODES_FLAG_ONE_CLICK, and setFlag().
setStartupMode()
void Modes::setStartupMode (uint8_t index)
Definition at line 675 of file Modes.cpp.
{
  // zero out the upper nibble to disable
  m_globalFlags &= 0x0F;
  // or in the index value shifted into the upper nibble
  m_globalFlags |= (index << 4) & 0xF0;
}
References m_globalFlags.
Referenced by VortexEngine::enterSleep(), and setCurMode().
shiftCurMode()
bool Modes::shiftCurMode (int32_t offset = 1)
Definition at line 442 of file Modes.cpp.
{
  uint32_t newPos = (uint32_t)((int32_t)m_curMode + offset);
  if (newPos >= m_numModes) {
    return false;
  }
  if (newPos == m_curMode) {
    return true;
  }
  // get the target mode at the position of the shift
  ModeLink *target = getModeLink(newPos);
  if (!target) {
    // invalid new position?
    return false;
  }
  // special case for moving first in list forward
  if (!m_curMode && offset > 0) {
    // update main list ptr
    m_storedModes = m_storedModes->next();
  }
  // unlink the current link
  m_pCurModeLink->unlinkSelf();
  // update the current position to reflect our new pos
  m_curMode = newPos;
  // then re-link the mode at the new spot
  if (offset < 0) {
    // link the link before our target link
    target->linkBefore(m_pCurModeLink);
    // special case for moving into first in list
    if (!m_curMode) {
      m_storedModes = m_pCurModeLink;
    }
  } else {
    // link the link after our target link
    target->linkAfter(m_pCurModeLink);
  }
  return true;
}
References getModeLink(), Modes::ModeLink::linkAfter(), Modes::ModeLink::linkBefore(), m_curMode, m_numModes, m_pCurModeLink, m_storedModes, Modes::ModeLink::next(), and Modes::ModeLink::unlinkSelf().
Referenced by Vortex::shiftCurMode().
startupMode()
uint8_t Modes::startupMode ()
Definition at line 683 of file Modes.cpp.
{
  // zero out the upper nibble to disable
  return (m_globalFlags & 0xF0) >> 4;
}
References m_globalFlags.
Referenced by switchToStartupMode().
switchToStartupMode()
Mode * Modes::switchToStartupMode ()
Definition at line 689 of file Modes.cpp.
{
  return setCurMode(startupMode());
}
References setCurMode(), and startupMode().
Referenced by loadFromBuffer(), and loadStorage().
unserialize()
bool Modes::unserialize (ByteStream & buffer)
Definition at line 352 of file Modes.cpp.
{
  DEBUG_LOG("Loading modes...");
  // this is good on memory, but it erases what they have stored before we
  // know whether there is something actually saved in the serial buffer
  clearModes();
  // unserialize the number of modes next
  uint8_t numModes = 0;
  if (!modesBuffer.unserialize8(&numModes)) {
    return false;
  }
  if (!numModes) {
    DEBUG_LOG("Did not find any modes");
    // this kinda sucks whatever they had loaded is gone
    return false;
  }
  // foreach expected mode
  for (uint8_t i = 0; i < numModes; ++i) {
    // just copy the serialized mode into the internal storage because
    // we store the modes in a serialized manner so that they are smaller
    // then we unpack them when we instantiate the mode
    if (!addSerializedMode(modesBuffer)) {
      DEBUG_LOGF("Failed to add mode %u after unserialization", i);
      // clear work so far?
      clearModes();
      return false;
    }
  }
  DEBUG_LOGF("Loaded %u modes from storage (%u bytes)", numModes, modesBuffer.size());
  return (m_numModes == numModes);
}
References addSerializedMode(), clearModes(), DEBUG_LOG, DEBUG_LOGF, m_numModes, numModes(), ByteStream::size(), and ByteStream::unserialize8().
Referenced by loadFromBuffer().
unserializeSaveHeader()
bool Modes::unserializeSaveHeader (ByteStream & saveBuffer)
Definition at line 277 of file Modes.cpp.
{
  // reset the unserializer index before unserializing anything
  saveHeader.resetUnserializer();
  uint8_t major = 0;
  uint8_t minor = 0;
  // unserialize the vortex version
  if (!saveHeader.unserialize8(&major)) {
    return false;
  }
  if (!saveHeader.unserialize8(&minor)) {
    return false;
  }
  // check the version for incompatibility
  if (!m_engine.checkVersion(major, minor)) {
    // incompatible version
    ERROR_LOGF("Incompatible savefile version: %u.%u", major, minor);
    return false;
  }
  // NOTE: instead of global brightness the duo uses this to store the
  // startup mode ID. The duo doesn't offer a global brightness option
  // unserialize the global brightness
  if (!saveHeader.unserialize8(&m_globalFlags)) {
    return false;
  }
  // unserialize the global brightness
  uint8_t brightness = 0;
  if (!saveHeader.unserialize8(&brightness)) {
    return false;
  }
  if (brightness) {
    m_engine.leds().setBrightness(brightness);
  }
  return true;
}
References VortexEngine::checkVersion(), ERROR_LOGF, VortexEngine::leds(), m_engine, m_globalFlags, saveHeader(), and Leds::setBrightness().
Referenced by init(), loadFromBuffer(), loadHeader(), and loadStorage().
updateCurMode()
bool Modes::updateCurMode (const Mode * mode)
Definition at line 531 of file Modes.cpp.
{
  if (!mode) {
    return false;
  }
  Mode *pCur = curMode();
  if (!pCur) {
    return false;
  }
  // utilize copy operator
  *pCur = *mode;
  // immediately save this mode to the internal mode storage
  if (!saveCurMode()) {
    return false;
  }
  // initialize the new mode
  return initCurMode();
}
References curMode(), initCurMode(), and saveCurMode().
Referenced by ModeSharing::onLongClick(), PatternSelect::onLongClick(), Randomizer::onLongClick(), Vortex::parseModeJson(), and ModeSharing::receiveModeIR().
Member Data Documentation
m_curMode
uint8_t Modes::m_curMode [private]
Definition at line 238 of file Modes.h.
Referenced by curModeIndex(), deleteCurMode(), initCurMode(), nextMode(), nextModeSkipEmpty(), previousMode(), setCurMode(), and shiftCurMode().
m_engine
VortexEngine& Modes::m_engine [private]
Definition at line 229 of file Modes.h.
Referenced by addMode(), addModeFromBuffer(), addSerializedMode(), Modes::ModeLink::append(), clearModes(), init(), Modes::ModeLink::instantiate(), loadHeader(), loadStorage(), play(), saveHeader(), saveStorage(), serializeSaveHeader(), setCurMode(), and unserializeSaveHeader().
m_globalFlags
uint8_t Modes::m_globalFlags [private]
Definition at line 250 of file Modes.h.
Referenced by getFlag(), init(), resetFlags(), serializeSaveHeader(), setFlag(), setStartupMode(), startupMode(), and unserializeSaveHeader().
m_lastSwitchTime
uint32_t Modes::m_lastSwitchTime [private]
Definition at line 253 of file Modes.h.
Referenced by lastSwitchTime(), and setCurMode().
m_loaded
bool Modes::m_loaded [private]
Definition at line 235 of file Modes.h.
Referenced by init(), and load().
m_numModes
uint8_t Modes::m_numModes [private]
Definition at line 241 of file Modes.h.
Referenced by addMode(), addModeFromBuffer(), addSerializedMode(), clearModes(), curMode(), deleteCurMode(), getModeLink(), initCurMode(), nextMode(), numModes(), play(), previousMode(), saveHeader(), saveStorage(), serialize(), setCurMode(), shiftCurMode(), and unserialize().
m_pCurModeLink
ModeLink* Modes::m_pCurModeLink [private]
Definition at line 244 of file Modes.h.
Referenced by clearModes(), curMode(), curModeInstantiated(), deleteCurMode(), initCurMode(), play(), saveCurMode(), saveStorage(), serialize(), setCurMode(), and shiftCurMode().
m_storedModes
ModeLink* Modes::m_storedModes [private]
Definition at line 247 of file Modes.h.
Referenced by addMode(), addModeFromBuffer(), clearModes(), deleteCurMode(), getModeLink(), saveStorage(), serialize(), and shiftCurMode().
The documentation for this class was generated from the following files:
VortexEngine/src/Modes/Modes.h
VortexEngine/src/Modes/Modes.cpp