DripPattern Class Reference
#include <DripPattern.h>
Public Member Functions
DripPattern (VortexEngine &engine, const PatternArgs &args)
virtual ~DripPattern ()
virtual void init () override
Protected Member Functions
virtual void blinkOn () override
virtual void poststep () override
Private Attributes
bool m_sync
Additional Inherited Members
Detailed Description
Definition at line 8 of file DripPattern.h.
Constructor & Destructor Documentation
DripPattern()
DripPattern::DripPattern (VortexEngine & engine, const PatternArgs & args)
Definition at line 7 of file DripPattern.cpp.
                                                                      :
  BlinkStepPattern(engine, args),
  m_sync(true)
{
  m_patternID = PATTERN_DRIP;
  setArgs(args);
}
References Pattern::m_patternID, PATTERN_DRIP, and Pattern::setArgs().
 DripPattern()
DripPattern::~DripPattern () [virtual]
Definition at line 15 of file DripPattern.cpp.
{
}
Member Function Documentation
blinkOn()
void DripPattern::blinkOn () [override], [protected], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 28 of file DripPattern.cpp.
{
  if (!m_sync) {
    m_engine.leds().setAllEvens(m_colorset.cur());
    m_engine.leds().setAllOdds(m_colorset.peekNext());
  } else {
    m_engine.leds().setAll(m_colorset.cur());
  }
}
References Colorset::cur(), VortexEngine::leds(), Pattern::m_colorset, Pattern::m_engine, m_sync, Colorset::peekNext(), Leds::setAll(), Leds::setAllEvens(), and Leds::setAllOdds().
init()
void DripPattern::init () [override], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 19 of file DripPattern.cpp.
{
  BlinkStepPattern::init();
  // reset sync bool
  m_sync = true;
  // start colorset at index 0 so cur() works
  m_colorset.setCurIndex(0);
}
References BlinkStepPattern::init(), Pattern::m_colorset, m_sync, and Colorset::setCurIndex().
poststep()
void DripPattern::poststep () [override], [protected], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 38 of file DripPattern.cpp.
{
  m_sync = !m_sync;
  if (m_sync) {
    m_colorset.getNext();
  }
}
References Colorset::getNext(), Pattern::m_colorset, and m_sync.
Member Data Documentation
m_sync
bool DripPattern::m_sync [private]
Definition at line 21 of file DripPattern.h.
Referenced by blinkOn(), init(), and poststep().
The documentation for this class was generated from the following files:
VortexEngine/src/Patterns/Multi/DripPattern.h
VortexEngine/src/Patterns/Multi/DripPattern.cpp