PulsishPattern Class Reference
#include <PulsishPattern.h>
Public Member Functions
PulsishPattern (VortexEngine &engine, const PatternArgs &args)
virtual ~PulsishPattern ()
virtual void init () override
virtual void play () override
Private Attributes
uint8_t m_progress
uint8_t m_stepDuration
Timer m_stepTimer
uint8_t m_onDuration1
uint8_t m_offDuration1
uint8_t m_onDuration2
uint8_t m_offDuration2
Timer m_blinkTimer
Timer m_blink2Timer
Additional Inherited Members
Detailed Description
Definition at line 6 of file PulsishPattern.h.
Constructor & Destructor Documentation
PulsishPattern()
PulsishPattern::PulsishPattern (VortexEngine & engine, const PatternArgs & args)
Definition at line 8 of file PulsishPattern.cpp.
                                                                            :
  MultiLedPattern(engine, args),
  m_progress(),
  m_stepDuration(0),
  m_stepTimer(engine),
  m_onDuration1(0),
  m_offDuration1(0),
  m_onDuration2(0),
  m_offDuration2(0),
  m_blinkTimer(engine),
  m_blink2Timer(engine)
{
  m_patternID = PATTERN_PULSISH;
  REGISTER_ARG(m_onDuration1);
  REGISTER_ARG(m_offDuration1);
  REGISTER_ARG(m_onDuration2);
  REGISTER_ARG(m_offDuration2);
  REGISTER_ARG(m_stepDuration);
  setArgs(args);
}
References m_offDuration1, m_offDuration2, m_onDuration1, m_onDuration2, Pattern::m_patternID, m_stepDuration, PATTERN_PULSISH, REGISTER_ARG, and Pattern::setArgs().
 PulsishPattern()
PulsishPattern::~PulsishPattern () [virtual]
Definition at line 29 of file PulsishPattern.cpp.
{
}
Member Function Documentation
init()
void PulsishPattern::init () [override], [virtual]
Reimplemented from MultiLedPattern.
Definition at line 34 of file PulsishPattern.cpp.
{
  MultiLedPattern::init();
  // reset and add alarm
  m_stepTimer.reset();
  m_stepTimer.addAlarm(m_stepDuration);
  m_stepTimer.start();
  // make blink timer
  m_blinkTimer.reset();
  m_blinkTimer.addAlarm(m_onDuration1);
  m_blinkTimer.addAlarm(m_offDuration1);
  m_blinkTimer.start();
  // make 2nd blink timer
  m_blink2Timer.reset();
  m_blink2Timer.addAlarm(m_onDuration2);
  m_blink2Timer.addAlarm(m_offDuration2);
  m_blink2Timer.start();
}
References Timer::addAlarm(), MultiLedPattern::init(), m_blink2Timer, m_blinkTimer, m_offDuration1, m_offDuration2, m_onDuration1, m_onDuration2, m_stepDuration, m_stepTimer, Timer::reset(), and Timer::start().
play()
void PulsishPattern::play () [override], [virtual]
Implements Pattern.
Definition at line 56 of file PulsishPattern.cpp.
{
  // when the step timer triggers
  if (m_stepTimer.alarm() == 0) {
    m_progress = (m_progress + 1) % PAIR_COUNT;
  }
  switch (m_blinkTimer.alarm()) {
  case -1: // just return
    return;
  case 0: // turn on the leds
    for (Pair pair = PAIR_FIRST; pair < PAIR_COUNT; ++pair) {
      if (pair != m_progress) {
        m_engine.leds().setPair(pair, m_colorset.cur());
      }
    }
    m_colorset.skip();
    if (m_colorset.curIndex() == 0) {
      m_colorset.skip();
    }
    break;
  case 1:
    for (Pair pair = PAIR_FIRST; pair < PAIR_COUNT; ++pair) {
      if (pair != m_progress) {
        m_engine.leds().clearPair(pair);
      }
    }
    break;
  }
  switch (m_blink2Timer.alarm()) {
  case -1: // just return
    return;
  case 0: // turn on the leds
    m_engine.leds().setPair((Pair)m_progress, m_colorset.get(0));
    break;
  case 1:
    m_engine.leds().clearPair((Pair)m_progress);
    break;
  }
}
References Timer::alarm(), Leds::clearPair(), Colorset::cur(), Colorset::curIndex(), Colorset::get(), VortexEngine::leds(), m_blink2Timer, m_blinkTimer, Pattern::m_colorset, Pattern::m_engine, m_progress, m_stepTimer, PAIR_COUNT, PAIR_FIRST, Leds::setPair(), and Colorset::skip().
Member Data Documentation
m_blink2Timer
Timer PulsishPattern::m_blink2Timer [private]
Definition at line 33 of file PulsishPattern.h.
Referenced by init(), and play().
m_blinkTimer
Timer PulsishPattern::m_blinkTimer [private]
Definition at line 32 of file PulsishPattern.h.
Referenced by init(), and play().
m_offDuration1
uint8_t PulsishPattern::m_offDuration1 [private]
Definition at line 28 of file PulsishPattern.h.
Referenced by init(), and PulsishPattern().
m_offDuration2
uint8_t PulsishPattern::m_offDuration2 [private]
Definition at line 30 of file PulsishPattern.h.
Referenced by init(), and PulsishPattern().
m_onDuration1
uint8_t PulsishPattern::m_onDuration1 [private]
Definition at line 27 of file PulsishPattern.h.
Referenced by init(), and PulsishPattern().
m_onDuration2
uint8_t PulsishPattern::m_onDuration2 [private]
Definition at line 29 of file PulsishPattern.h.
Referenced by init(), and PulsishPattern().
m_progress
uint8_t PulsishPattern::m_progress [private]
Definition at line 20 of file PulsishPattern.h.
Referenced by play().
m_stepDuration
uint8_t PulsishPattern::m_stepDuration [private]
Definition at line 23 of file PulsishPattern.h.
Referenced by init(), and PulsishPattern().
m_stepTimer
Timer PulsishPattern::m_stepTimer [private]
Definition at line 25 of file PulsishPattern.h.
Referenced by init(), and play().
The documentation for this class was generated from the following files:
VortexEngine/src/Patterns/Multi/PulsishPattern.h
VortexEngine/src/Patterns/Multi/PulsishPattern.cpp