VortexCLI::VortexCLICallbacks Class Reference
Public Member Functions
VortexCLICallbacks (Vortex &vortex)
virtual ~VortexCLICallbacks ()
virtual long checkPinHook (uint32_t pin) override
virtual void ledsInit (void *cl, int count) override
virtual void ledsShow () override
Additional Inherited Members
Detailed Description
Definition at line 44 of file VortexCLI.h.
Constructor & Destructor Documentation
VortexCLICallbacks()
VortexCLI::VortexCLICallbacks::VortexCLICallbacks (Vortex & vortex) [inline]
Definition at line 47 of file VortexCLI.h.
: VortexCallbacks(vortex) {}
 VortexCLICallbacks()
virtual VortexCLI::VortexCLICallbacks::~VortexCLICallbacks () [inline], [virtual]
Definition at line 48 of file VortexCLI.h.
{}
Member Function Documentation
checkPinHook()
long VortexCLI::VortexCLICallbacks::checkPinHook (uint32_t pin) [override], [virtual]
Reimplemented from VortexCallbacks.
Definition at line 809 of file VortexCLI.cpp.
{
  if (pin == 20) {
    // orbit button 2
    return m_vortex.isButtonPressed(1) ? 0 : 1;
  }
  return m_vortex.isButtonPressed(0) ? 0 : 1;
}
References Vortex::isButtonPressed(), and VortexCallbacks::m_vortex.
ledsInit()
void VortexCLI::VortexCLICallbacks::ledsInit (void * cl, int count) [override], [virtual]
Reimplemented from VortexCallbacks.
Definition at line 818 of file VortexCLI.cpp.
{
  g_pVortexCLI->installLeds(cl, count);
}
References g_pVortexCLI, and VortexCLI::installLeds().
ledsShow()
void VortexCLI::VortexCLICallbacks::ledsShow () [override], [virtual]
Reimplemented from VortexCallbacks.
Definition at line 823 of file VortexCLI.cpp.
{
  g_pVortexCLI->show();
}
References g_pVortexCLI, and VortexCLI::show().
The documentation for this class was generated from the following files:
VortexEngine/VortexCLI/VortexCLI.h
VortexEngine/VortexCLI/VortexCLI.cpp