SerialComs Class Reference
#include <Serial.h>
Public Member Functions
SerialComs (VortexEngine &engine)
~SerialComs ()
bool init ()
void cleanup ()
bool isConnected ()
bool checkSerial ()
void write (const char *msg,...)
void write (ByteStream &byteStream)
void read (ByteStream &byteStream)
bool dataReady ()
Private Attributes
VortexEngine & m_engine
bool m_serialConnected
uint32_t m_lastCheck
Detailed Description
Definition at line 10 of file Serial.h.
Constructor & Destructor Documentation
SerialComs()
SerialComs::SerialComs (VortexEngine & engine)
Definition at line 15 of file Serial.cpp.
                                           :
  m_engine(engine),
  m_serialConnected(false),
  m_lastCheck(0)
{
}
 SerialComs()
SerialComs::~SerialComs ()
Definition at line 22 of file Serial.cpp.
{
}
Member Function Documentation
checkSerial()
bool SerialComs::checkSerial ()
Definition at line 44 of file Serial.cpp.
{
#if VORTEX_SLIM == 0
  if (isConnected()) {
    // already connected
    return true;
  }
  uint32_t now = m_engine.time().getCurtime();
  // don't check for serial too fast
  if (m_lastCheck && (now - m_lastCheck) < MAX_SERIAL_CHECK_INTERVAL) {
    // can't check yet too soon
    return false;
  }
  m_lastCheck = now;
#ifdef VORTEX_LIB
  if (!m_engine.vortexLib().vcallbacks()->serialCheck()) {
    return false;
  }
  m_engine.vortexLib().vcallbacks()->serialBegin(SERIAL_BAUD_RATE);
#else
  // This will check if the serial communication is open
  if (!Serial.available()) {
    // serial is not connected
    return false;
  }
  // Begin serial communications
  Serial.begin(SERIAL_BAUD_RATE);
#endif
#endif
  // serial is now connected
  m_serialConnected = true;
  return true;
}
References Time::getCurtime(), isConnected(), m_engine, m_lastCheck, m_serialConnected, MAX_SERIAL_CHECK_INTERVAL, SERIAL_BAUD_RATE, VortexCallbacks::serialBegin(), VortexCallbacks::serialCheck(), VortexEngine::time(), Vortex::vcallbacks(), and VortexEngine::vortexLib().
Referenced by EditorConnection::run().
cleanup()
void SerialComs::cleanup ()
Definition at line 34 of file Serial.cpp.
{
}
Referenced by VortexEngine::cleanup().
dataReady()
bool SerialComs::dataReady ()
Definition at line 143 of file Serial.cpp.
{
#if VORTEX_SLIM == 0
  if (!isConnected()) {
    return false;
  }
#ifdef VORTEX_LIB
  return (m_engine.vortexLib().vcallbacks()->serialAvail() > 0);
#else
  return (Serial.available() > 0);
#endif
#else
  return false;
#endif
}
References isConnected(), m_engine, VortexCallbacks::serialAvail(), Vortex::vcallbacks(), and VortexEngine::vortexLib().
init()
bool SerialComs::init ()
Definition at line 27 of file Serial.cpp.
{
  // Try connecting serial ?
  //checkSerial();
  return true;
}
Referenced by VortexEngine::init().
isConnected()
bool SerialComs::isConnected ()
Definition at line 38 of file Serial.cpp.
{
  return m_serialConnected;
}
References m_serialConnected.
Referenced by checkSerial(), dataReady(), read(), EditorConnection::run(), and write().
read()
void SerialComs::read (ByteStream & byteStream)
Definition at line 115 of file Serial.cpp.
{
#if VORTEX_SLIM == 0
  if (!isConnected()) {
    return;
  }
#ifdef VORTEX_LIB
  uint32_t amt = m_engine.vortexLib().vcallbacks()->serialAvail();
#else
  uint32_t amt = Serial.available();
#endif
  if (!amt) {
    return;
  }
  do {
    uint8_t byte = 0;
#ifdef VORTEX_LIB
    if (!m_engine.vortexLib().vcallbacks()->serialRead((char *)&byte, 1)) {
      return;
    }
#else
    byte = Serial.read();
#endif
    byteStream.serialize8(byte);
  } while (--amt > 0);
#endif
}
References isConnected(), m_engine, VortexCallbacks::serialAvail(), ByteStream::serialize8(), VortexCallbacks::serialRead(), Vortex::vcallbacks(), and VortexEngine::vortexLib().
Referenced by EditorConnection::receiveData().
write() [1/2]
void SerialComs::write (ByteStream & byteStream)
Definition at line 97 of file Serial.cpp.
{
#if VORTEX_SLIM == 0
  if (!isConnected()) {
    return;
  }
  byteStream.recalcCRC();
  uint32_t size = byteStream.rawSize();
#ifdef VORTEX_LIB
  m_engine.vortexLib().vcallbacks()->serialWrite((const uint8_t *)&size, sizeof(size));
  m_engine.vortexLib().vcallbacks()->serialWrite((const uint8_t *)byteStream.rawData(), byteStream.rawSize());
#else
  Serial.write((const uint8_t *)&size, sizeof(size));
  Serial.write((const uint8_t *)byteStream.rawData(), byteStream.rawSize());
#endif
#endif
}
References isConnected(), m_engine, ByteStream::rawData(), ByteStream::rawSize(), ByteStream::recalcCRC(), VortexCallbacks::serialWrite(), Vortex::vcallbacks(), and VortexEngine::vortexLib().
write() [2/2]
void SerialComs::write (const char * msg, ...)
Definition at line 78 of file Serial.cpp.
{
#if VORTEX_SLIM == 0
  if (!isConnected()) {
    return;
  }
  va_list list;
  va_start(list, msg);
  uint8_t buf[2048] = {0};
  int len = vsnprintf((char *)buf, sizeof(buf), msg, list);
#ifdef VORTEX_LIB
  m_engine.vortexLib().vcallbacks()->serialWrite(buf, len);
#else
  Serial.write(buf, len);
#endif
  va_end(list);
#endif
}
References isConnected(), m_engine, VortexCallbacks::serialWrite(), Vortex::vcallbacks(), and VortexEngine::vortexLib().
Referenced by EditorConnection::leaveMenu(), EditorConnection::run(), and EditorConnection::sendModes().
Member Data Documentation
m_engine
VortexEngine& SerialComs::m_engine [private]
Definition at line 40 of file Serial.h.
Referenced by checkSerial(), dataReady(), read(), and write().
m_lastCheck
uint32_t SerialComs::m_lastCheck [private]
Definition at line 43 of file Serial.h.
Referenced by checkSerial().
m_serialConnected
bool SerialComs::m_serialConnected [private]
Definition at line 42 of file Serial.h.
Referenced by checkSerial(), and isConnected().
The documentation for this class was generated from the following files:
VortexEngine/src/Serial/Serial.h
VortexEngine/src/Serial/Serial.cpp