TheaterChasePattern Class Reference
#include <TheaterChasePattern.h>
Public Member Functions
TheaterChasePattern (VortexEngine &engine, const PatternArgs &args)
virtual ~TheaterChasePattern ()
virtual void init () override
Protected Member Functions
virtual void blinkOn () override
virtual void poststep () override
Protected Attributes
LedMap m_ledPositions
uint8_t m_stepCounter
Detailed Description
Definition at line 8 of file TheaterChasePattern.h.
Constructor & Destructor Documentation
TheaterChasePattern()
TheaterChasePattern::TheaterChasePattern (VortexEngine & engine, const PatternArgs & args)
Definition at line 9 of file TheaterChasePattern.cpp.
                                                                                      :
  BlinkStepPattern(engine, args),
  m_ledPositions(0),
  m_stepCounter(0)
{
  m_patternID = PATTERN_THEATER_CHASE;
  setArgs(args);
}
References Pattern::m_patternID, PATTERN_THEATER_CHASE, and Pattern::setArgs().
 TheaterChasePattern()
TheaterChasePattern::~TheaterChasePattern () [virtual]
Definition at line 18 of file TheaterChasePattern.cpp.
{
}
Member Function Documentation
blinkOn()
void TheaterChasePattern::blinkOn () [override], [protected], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 30 of file TheaterChasePattern.cpp.
{
  m_engine.leds().setMap(m_ledPositions, m_colorset.getNext());
}
References Colorset::getNext(), VortexEngine::leds(), Pattern::m_colorset, Pattern::m_engine, m_ledPositions, and Leds::setMap().
init()
void TheaterChasePattern::init () [override], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 22 of file TheaterChasePattern.cpp.
{
  BlinkStepPattern::init();
  // starts on odd evens
  m_ledPositions = MAP_PAIR_ODD_EVENS;
  m_stepCounter = 0;
}
References BlinkStepPattern::init(), m_ledPositions, m_stepCounter, and MAP_PAIR_ODD_EVENS.
poststep()
void TheaterChasePattern::poststep () [override], [protected], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 35 of file TheaterChasePattern.cpp.
{
  // the first 5 steps are odd evens/odds alternating each step
  if (m_stepCounter < 5) {
    m_ledPositions = (m_stepCounter % 2) ? MAP_PAIR_ODD_ODDS : MAP_PAIR_ODD_EVENS;
  } else {
    // the end 5 steps are even evens/odds alternating each step
    m_ledPositions = (m_stepCounter % 2) ? MAP_PAIR_EVEN_ODDS : MAP_PAIR_EVEN_EVENS;
  }
  // increment step counter
  m_stepCounter = (m_stepCounter + 1) % THEATER_CHASE_STEPS;
}
References m_ledPositions, m_stepCounter, MAP_PAIR_EVEN_EVENS, MAP_PAIR_EVEN_ODDS, MAP_PAIR_ODD_EVENS, MAP_PAIR_ODD_ODDS, and THEATER_CHASE_STEPS.
Member Data Documentation
m_ledPositions
LedMap TheaterChasePattern::m_ledPositions [protected]
Definition at line 20 of file TheaterChasePattern.h.
Referenced by blinkOn(), init(), and poststep().
m_stepCounter
uint8_t TheaterChasePattern::m_stepCounter [protected]
Definition at line 21 of file TheaterChasePattern.h.
Referenced by init(), and poststep().
The documentation for this class was generated from the following files:
VortexEngine/src/Patterns/Multi/TheaterChasePattern.h
VortexEngine/src/Patterns/Multi/TheaterChasePattern.cpp