DoubleStrobePattern Class Reference
#include <DoubleStrobePattern.h>
Public Member Functions
DoubleStrobePattern (VortexEngine &engine, const PatternArgs &args)
virtual ~DoubleStrobePattern ()
virtual void init () override
Protected Member Functions
virtual void blinkOn () override
Additional Inherited Members
Detailed Description
Definition at line 8 of file DoubleStrobePattern.h.
Constructor & Destructor Documentation
DoubleStrobePattern()
DoubleStrobePattern::DoubleStrobePattern (VortexEngine & engine, const PatternArgs & args)
Definition at line 9 of file DoubleStrobePattern.cpp.
                                                                                      :
  BlinkStepPattern(engine, args)
{
  m_patternID = PATTERN_DOUBLESTROBE;
  setArgs(args);
}
References Pattern::m_patternID, PATTERN_DOUBLESTROBE, and Pattern::setArgs().
 DoubleStrobePattern()
DoubleStrobePattern::~DoubleStrobePattern () [virtual]
Definition at line 16 of file DoubleStrobePattern.cpp.
{
}
Member Function Documentation
blinkOn()
void DoubleStrobePattern::blinkOn () [override], [protected], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 27 of file DoubleStrobePattern.cpp.
{
  m_engine.leds().setAllOdds(m_colorset.cur());
  m_engine.leds().setAllEvens(m_colorset.peekNext());
}
References Colorset::cur(), VortexEngine::leds(), Pattern::m_colorset, Pattern::m_engine, Colorset::peekNext(), Leds::setAllEvens(), and Leds::setAllOdds().
init()
void DoubleStrobePattern::init () [override], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 20 of file DoubleStrobePattern.cpp.
{
  BlinkStepPattern::init();
  // start colorset at index 0 so cur() works
  m_colorset.setCurIndex(0);
}
References BlinkStepPattern::init(), Pattern::m_colorset, and Colorset::setCurIndex().
The documentation for this class was generated from the following files:
VortexEngine/src/Patterns/Multi/DoubleStrobePattern.h
VortexEngine/src/Patterns/Multi/DoubleStrobePattern.cpp