PatternMap Class Reference
#include <Sequence.h>
Public Member Functions
PatternMap (VortexEngine &engine)
PatternMap (VortexEngine &engine, PatternID pattern, LedMap positions)
PatternMap (VortexEngine &engine, const PatternMap &other)
void operator= (const PatternMap &other)
bool operator== (const PatternMap &other) const
bool operator!= (const PatternMap &other) const
void setPatternAt (PatternID pattern, LedMap positions)
PatternID operator[] (LedPos index) const
bool serialize (ByteStream &buffer) const
bool unserialize (ByteStream &buffer)
Public Attributes
VortexEngine & m_engine
std::vector< PatternID > m_patterns
Detailed Description
Definition at line 16 of file Sequence.h.
Constructor & Destructor Documentation
PatternMap() [1/3]
PatternMap::PatternMap (VortexEngine & engine)
Definition at line 15 of file Sequence.cpp.
                                           :
  m_engine(engine),
  m_patterns()
{
  m_patterns.resize(LED_COUNT);
  for (LedPos i = LED_FIRST; i < LED_COUNT; ++i) {
    m_patterns[i] = PATTERN_NONE;
  }
}
References LED_COUNT, LED_FIRST, m_patterns, and PATTERN_NONE.
PatternMap() [2/3]
PatternMap::PatternMap (VortexEngine & engine, PatternID pattern, LedMap positions)
Definition at line 25 of file Sequence.cpp.
                                                                                :
  PatternMap(engine)
{
  setPatternAt(pattern, positions);
}
References setPatternAt().
PatternMap() [3/3]
PatternMap::PatternMap (VortexEngine & engine, const PatternMap & other)
Definition at line 31 of file Sequence.cpp.
                                                                    :
  PatternMap(engine)
{
  *this = other;
}
Member Function Documentation
operator!=()
bool PatternMap::operator!= (const PatternMap & other) const
Definition at line 47 of file Sequence.cpp.
{
  return !(*this == other);
}
operator=()
void PatternMap::operator= (const PatternMap & other)
Definition at line 37 of file Sequence.cpp.
{
  m_patterns = other.m_patterns;
}
References m_patterns.
operator==()
bool PatternMap::operator== (const PatternMap & other) const
Definition at line 42 of file Sequence.cpp.
{
  return m_patterns == other.m_patterns;
}
References m_patterns.
operator[]()
PatternID PatternMap::operator[] (LedPos index) const
Definition at line 62 of file Sequence.cpp.
{
  return m_patterns[index];
}
References m_patterns.
serialize()
bool PatternMap::serialize (ByteStream & buffer) const
Definition at line 67 of file Sequence.cpp.
{
  for (LedPos i = LED_FIRST; i < LED_COUNT; ++i) {
    // ensure the PatternID is interpreted as uint8_t
    if (!buffer.serialize8((uint8_t)m_patterns[i])) {
      return false;
    }
  }
  return true;
}
References LED_COUNT, LED_FIRST, m_patterns, and ByteStream::serialize8().
Referenced by SequenceStep::serialize().
setPatternAt()
void PatternMap::setPatternAt (PatternID pattern, LedMap positions)
Definition at line 53 of file Sequence.cpp.
{
  for (LedPos pos = LED_FIRST; pos < LED_COUNT; ++pos) {
    if (m_engine.leds().ledmapCheckLed(positions, pos)) {
      m_patterns[pos] = pattern;
    }
  }
}
References LED_COUNT, LED_FIRST, Leds::ledmapCheckLed(), VortexEngine::leds(), m_engine, and m_patterns.
Referenced by ChaserPattern::ChaserPattern(), and PatternMap().
unserialize()
bool PatternMap::unserialize (ByteStream & buffer)
Definition at line 78 of file Sequence.cpp.
{
  for (LedPos i = LED_FIRST; i < LED_COUNT; ++i) {
    if (!buffer.unserialize8((uint8_t *)m_patterns.data() + i)) {
      return false;
    }
  }
  return true;
}
References LED_COUNT, LED_FIRST, m_patterns, and ByteStream::unserialize8().
Referenced by SequenceStep::unserialize().
Member Data Documentation
m_engine
VortexEngine& PatternMap::m_engine
Definition at line 36 of file Sequence.h.
Referenced by setPatternAt().
m_patterns
std::vector<PatternID> PatternMap::m_patterns
Definition at line 39 of file Sequence.h.
Referenced by operator=(), operator==(), operator[](), PatternMap(), serialize(), setPatternAt(), and unserialize().
The documentation for this class was generated from the following files:
VortexEngine/src/Patterns/Multi/Sequencer/Sequence.h
VortexEngine/src/Patterns/Multi/Sequencer/Sequence.cpp