VortexEngine/src/Serial/Compression.cpp File Reference
#include `Compression.h`
#include `../Memory/Memory.h`
#include `../VortexConfig.h`
#include <string.h>
#include <limits.h>
#include <stdint.h>
#include <stddef.h>
Macros
#define expect(expr, value) (expr)
#define likely(expr) expect((expr) != 0, 1)
#define unlikely(expr) expect((expr) != 0, 0)
#define LZ4_ALIGN_TEST 0
#define MINMATCH 4
#define WILDCOPYLENGTH 8
#define LASTLITERALS 5 /* see ../doc/lz4_Block_format.md#parsing-restrictions */
#define MFLIMIT 12 /* see ../doc/lz4_Block_format.md#parsing-restrictions */
#define MATCH_SAFEGUARD_DISTANCE ((2*WILDCOPYLENGTH) - MINMATCH) /* ensure it's possible to write 2 x wildcopyLength without overflowing output buffer */
#define FASTLOOP_SAFE_DISTANCE 64
#define KB *(1 <<10)
#define MB *(1 <<20)
#define GB *(1U<<30)
#define LZ4_DISTANCE_ABSOLUTE_MAX 65535
#define ML_BITS 4
#define ML_MASK ((1U<<ML_BITS)-1)
#define RUN_BITS (8-ML_BITS)
#define RUN_MASK ((1U<<RUN_BITS)-1)
#define assert(condition) ((void)0)
#define LZ4_STATIC_ASSERT(c) { enum { LZ4_static_assert = 1/(int)(!!(c)) }; } /* use after variable declarations */
#define DEBUGLOG(l, ...) {} /* disabled */
#define LZ4_memcpy(dst, src, size) memcpy(dst, src, size)
#define STEPSIZE sizeof(reg_t)
#define MIN(a, b) ((a) < (b) ? (a) : (b))
Typedefs
typedef uint8_t BYTE
typedef uint16_t U16
typedef uint32_t U32
typedef int32_t S32
typedef uint64_t U64
typedef uintptr_t uptrval
typedef size_t reg_t
Enumerations
enum limitedOutput_directive { notLimited = 0
, limitedOutput = 1
, fillOutput = 2
 }
enum tableType_t { clearedTable = 0
, byPtr
, byU32
, byU16
 }
enum dict_directive { noDict = 0
, withPrefix64k
, usingExtDict
, usingDictCtx
 }
enum dictIssue_directive { noDictIssue = 0
, dictSmall
 }
enum endCondition_directive { endOnOutputSize = 0
, endOnInputSize = 1
 }
enum earlyEnd_directive { decode_full_block = 0
, partial_decode = 1
 }
enum variable_length_error { loop_error = -2
, initial_error = -1
, ok = 0
 }
Functions
static int LZ4_isAligned (const void *ptr, size_t alignment)
static unsigned LZ4_isLittleEndian (void)
static U16 LZ4_read16 (const void *memPtr)
static U32 LZ4_read32 (const void *memPtr)
static reg_t LZ4_read_ARCH (const void *memPtr)
static void LZ4_write16 (void *memPtr, U16 value)
static void LZ4_write32 (void *memPtr, U32 value)
static U16 LZ4_readLE16 (const void *memPtr)
static void LZ4_writeLE16 (void *memPtr, U16 value)
void LZ4_wildCopy8 (void *dstPtr, const void *srcPtr, void *dstEnd)
void LZ4_memcpy_using_offset_base (BYTE *dstPtr, const BYTE *srcPtr, BYTE *dstEnd, const size_t offset)
void LZ4_wildCopy32 (void *dstPtr, const void *srcPtr, void *dstEnd)
void LZ4_memcpy_using_offset (BYTE *dstPtr, const BYTE *srcPtr, BYTE *dstEnd, const size_t offset)
static unsigned LZ4_NbCommonBytes (reg_t val)
unsigned LZ4_count (const BYTE *pIn, const BYTE *pMatch, const BYTE *pInLimit)
int LZ4_compressBound (int isize)
U32 LZ4_hash4 (U32 sequence, tableType_t const tableType)
U32 LZ4_hash5 (U64 sequence, tableType_t const tableType)
U32 LZ4_hashPosition (const void *const p, tableType_t const tableType)
void LZ4_clearHash (U32 h, void *tableBase, tableType_t const tableType)
void LZ4_putIndexOnHash (U32 idx, U32 h, void *tableBase, tableType_t const tableType)
void LZ4_putPositionOnHash (const BYTE *p, U32 h, void *tableBase, tableType_t const tableType, const BYTE *srcBase)
void LZ4_putPosition (const BYTE *p, void *tableBase, tableType_t tableType, const BYTE *srcBase)
U32 LZ4_getIndexOnHash (U32 h, const void *tableBase, tableType_t tableType)
static const BYTE * LZ4_getPositionOnHash (U32 h, const void *tableBase, tableType_t tableType, const BYTE *srcBase)
const BYTE * LZ4_getPosition (const BYTE *p, const void *tableBase, tableType_t tableType, const BYTE *srcBase)
int LZ4_compress_generic_validated (LZ4_stream_t_internal *const cctx, const char *const source, char *const dest, const int inputSize, int *inputConsumed, const int maxOutputSize, const limitedOutput_directive outputDirective, const tableType_t tableType, const dict_directive dictDirective, const dictIssue_directive dictIssue, const int acceleration)
int LZ4_compress_generic (LZ4_stream_t_internal *const cctx, const char *const src, char *const dst, const int srcSize, int *inputConsumed, const int dstCapacity, const limitedOutput_directive outputDirective, const tableType_t tableType, const dict_directive dictDirective, const dictIssue_directive dictIssue, const int acceleration)
int LZ4_compress_fast_extState (void *state, const char *source, char *dest, int inputSize, int maxOutputSize, int acceleration)
int LZ4_compress_fast (const char *source, char *dest, int inputSize, int maxOutputSize, int acceleration)
int LZ4_compress_default (const char *src, char *dst, int srcSize, int maxOutputSize)
static size_t LZ4_stream_t_alignment (void)
LZ4_stream_t * LZ4_initStream (void *buffer, size_t size)
unsigned read_variable_length (const BYTE **ip, const BYTE *lencheck, int loop_check, int initial_check, variable_length_error *error)
int LZ4_decompress_generic (const char *const src, char *const dst, int srcSize, int outputSize, endCondition_directive endOnInput, earlyEnd_directive partialDecoding, dict_directive dict, const BYTE *const lowPrefix, const BYTE *const dictStart, const size_t dictSize)
int LZ4_decompress_safe (const char *source, char *dest, int compressedSize, int maxDecompressedSize)
Variables
static const int LZ4_minLength = (MFLIMIT + 1)
static const unsigned inc32table [8] = { 0, 1, 2, 1, 0, 4, 4, 4 }
static const int dec64table [8] = { 0, 0, 0, -1, -4, 1, 2, 3 }
static const int LZ4_64Klimit = ((64 KB) + (MFLIMIT - 1))
static const U32 LZ4_skipTrigger = 6
Macro Definition Documentation
assert
#define assert(condition) ((void)0)
Definition at line 68 of file Compression.cpp.
DEBUGLOG
#define DEBUGLOG(l, ...) {} /* disabled */
Definition at line 73 of file Compression.cpp.
expect
#define expect(expr, value) (expr)
Definition at line 21 of file Compression.cpp.
FASTLOOP_SAFE_DISTANCE
#define FASTLOOP_SAFE_DISTANCE 64
Definition at line 43 of file Compression.cpp.
GB
#define GB *(1U<<30)
Definition at line 48 of file Compression.cpp.
KB
#define KB *(1 <<10)
Definition at line 46 of file Compression.cpp.
LASTLITERALS
#define LASTLITERALS 5 /* see ../doc/lz4_Block_format.md#parsing-restrictions */
Definition at line 40 of file Compression.cpp.
likely
#define likely(expr) expect((expr) != 0, 1)
Definition at line 25 of file Compression.cpp.
LZ4_ALIGN_TEST
#define LZ4_ALIGN_TEST 0
Definition at line 34 of file Compression.cpp.
LZ4_DISTANCE_ABSOLUTE_MAX
#define LZ4_DISTANCE_ABSOLUTE_MAX 65535
Definition at line 50 of file Compression.cpp.
LZ4_memcpy
#define LZ4_memcpy(dst, src, size) memcpy(dst, src, size)
LZ4 relies on memcpy with a constant size being inlined. In freestanding environments, the compiler can't assume the implementation of memcpy() is standard compliant, so it can't apply its specialized memcpy() inlining logic. When possible, use __builtin_memcpy() to tell the compiler to analyze memcpy() as if it were standard compliant, so it can inline it in freestanding environments. This is needed when decompressing the Linux Kernel, for example.
Definition at line 119 of file Compression.cpp.
LZ4_STATIC_ASSERT
#define LZ4_STATIC_ASSERT(c) { enum { LZ4_static_assert = 1/(int)(!!(c)) }; } /* use after variable declarations */
Definition at line 72 of file Compression.cpp.
MATCH_SAFEGUARD_DISTANCE
#define MATCH_SAFEGUARD_DISTANCE ((2*WILDCOPYLENGTH) - MINMATCH) /* ensure it's possible to write 2 x wildcopyLength without overflowing output buffer */
Definition at line 42 of file Compression.cpp.
MB
#define MB *(1 <<20)
Definition at line 47 of file Compression.cpp.
MFLIMIT
#define MFLIMIT 12 /* see ../doc/lz4_Block_format.md#parsing-restrictions */
Definition at line 41 of file Compression.cpp.
MIN
#define MIN(a, b) ((a) < (b) ? (a) : (b))
Definition at line 993 of file Compression.cpp.
MINMATCH
#define MINMATCH 4
Definition at line 37 of file Compression.cpp.
ML_BITS
#define ML_BITS 4
Definition at line 55 of file Compression.cpp.
ML_MASK
#define ML_MASK ((1U<<ML_BITS)-1)
Definition at line 56 of file Compression.cpp.
RUN_BITS
#define RUN_BITS (8-ML_BITS)
Definition at line 57 of file Compression.cpp.
RUN_MASK
#define RUN_MASK ((1U<<RUN_BITS)-1)
Definition at line 58 of file Compression.cpp.
STEPSIZE
#define STEPSIZE sizeof(reg_t)
Definition at line 300 of file Compression.cpp.
unlikely
#define unlikely(expr) expect((expr) != 0, 0)
Definition at line 28 of file Compression.cpp.
WILDCOPYLENGTH
#define WILDCOPYLENGTH 8
Definition at line 39 of file Compression.cpp.
Typedef Documentation
BYTE
typedef uint8_t BYTE
Definition at line 83 of file Compression.cpp.
reg_t
typedef size_t reg_t
Definition at line 93 of file Compression.cpp.
S32
typedef int32_t S32
Definition at line 86 of file Compression.cpp.
U16
typedef uint16_t U16
Definition at line 84 of file Compression.cpp.
U32
typedef uint32_t U32
Definition at line 85 of file Compression.cpp.
U64
typedef uint64_t U64
Definition at line 87 of file Compression.cpp.
uptrval
typedef uintptr_t uptrval
Definition at line 88 of file Compression.cpp.
Enumeration Type Documentation
dict_directive
enum dict_directive
This enum distinguishes several different modes of accessing previous content in the stream.
noDict : There is no preceding content.
withPrefix64k : Table entries up to ctx->dictSize before the current blob blob being compressed are valid and refer to the preceding content (of length ctx->dictSize), which is available contiguously preceding in memory the content currently being compressed.
usingExtDict : Like withPrefix64k, but the preceding content is somewhere else in memory, starting at ctx->dictionary with length ctx->dictSize.
usingDictCtx : Everything concerning the preceding content is in a separate context, pointed to by ctx->dictCtx. ctx->dictionary, ctx->dictSize, and table entries in the current context that refer to positions preceding the beginning of the current compression are ignored. Instead, ctx->dictCtx->dictionary and ctx->dictCtx ->dictSize describe the location and size of the preceding content, and matches are found by looking in the ctx ->dictCtx->hashTable.
Enumerator
noDict
withPrefix64k
usingExtDict
usingDictCtx
Definition at line 363 of file Compression.cpp.
{ noDict = 0, withPrefix64k, usingExtDict, usingDictCtx } dict_directive;
dictIssue_directive
enum dictIssue_directive
Enumerator
noDictIssue
dictSmall
Definition at line 364 of file Compression.cpp.
{ noDictIssue = 0, dictSmall } dictIssue_directive;
earlyEnd_directive
enum earlyEnd_directive
Enumerator
decode_full_block
partial_decode
Definition at line 990 of file Compression.cpp.
{ decode_full_block = 0, partial_decode = 1 } earlyEnd_directive;
endCondition_directive
enum endCondition_directive
Enumerator
endOnOutputSize
endOnInputSize
Definition at line 989 of file Compression.cpp.
{ endOnOutputSize = 0, endOnInputSize = 1 } endCondition_directive;
limitedOutput_directive
enum limitedOutput_directive
Enumerator
notLimited
limitedOutput
fillOutput
Definition at line 96 of file Compression.cpp.
{
  notLimited = 0,
  limitedOutput = 1,
  fillOutput = 2
} limitedOutput_directive;
tableType_t
enum tableType_t
Enumerator
clearedTable
byPtr
byU32
byU16
Definition at line 338 of file Compression.cpp.
{ clearedTable = 0, byPtr, byU32, byU16 } tableType_t;
variable_length_error
enum variable_length_error
Enumerator
loop_error
initial_error
ok
Definition at line 1003 of file Compression.cpp.
{ loop_error = -2, initial_error = -1, ok = 0 } variable_length_error;
Function Documentation
LZ4_clearHash()
void LZ4_clearHash (U32 h, void * tableBase, tableType_t const tableType)
Definition at line 401 of file Compression.cpp.
{
  switch (tableType) {
  default: /* fallthrough */
  case clearedTable: { /* illegal! */ assert(0); return; }
  case byPtr: { const BYTE **hashTable = (const BYTE **)tableBase; hashTable[h] = NULL; return; }
  case byU32: { U32 *hashTable = (U32 *)tableBase; hashTable[h] = 0; return; }
  case byU16: { U16 *hashTable = (U16 *)tableBase; hashTable[h] = 0; return; }
  }
}
References assert, byPtr, byU16, byU32, and clearedTable.
Referenced by LZ4_compress_generic_validated().
LZ4_compress_default()
int LZ4_compress_default (const char * src, char * dst, int srcSize, int dstCapacity)
LZ4_compress_default() : Compresses 'srcSize' bytes from buffer 'src' into already allocated 'dst' buffer of size 'dstCapacity'. Compression is guaranteed to succeed if 'dstCapacity' >= LZ4_compressBound(srcSize). It also runs faster, so it's a recommended setting. If the function cannot compress 'src' into a more limited 'dst' budget, compression stops immediately, and the function result is zero. In which case, 'dst' content is undefined (invalid). srcSize : max supported value is LZ4_MAX_INPUT_SIZE. dstCapacity : size of buffer 'dst' (which must be already allocated)
Returns
: the number of bytes written into buffer 'dst' (necessarily <= dstCapacity) or 0 if compression fails Note : This function is protected against buffer overflow scenarios (never writes outside 'dst' buffer, nor read outside 'source' buffer).
Definition at line 955 of file Compression.cpp.
{
  return LZ4_compress_fast(src, dst, srcSize, maxOutputSize, 1);
}
References LZ4_compress_fast().
LZ4_compress_fast()
int LZ4_compress_fast (const char * src, char * dst, int srcSize, int dstCapacity, int acceleration)
LZ4_compress_fast() : Same as LZ4_compress_default(), but allows selection of `acceleration` factor. The larger the acceleration value, the faster the algorithm, but also the lesser the compression. It's a trade-off. It can be fine tuned, with each successive value providing roughly +~3% to speed. An acceleration value of `1` is the same as regular LZ4_compress_default() Values <= 0 will be replaced by LZ4_ACCELERATION_DEFAULT (currently == 1, see lz4.c). Values > LZ4_ACCELERATION_MAX will be replaced by LZ4_ACCELERATION_MAX (currently == 65537, see lz4.c).
Definition at line 945 of file Compression.cpp.
{
  int result;
  LZ4_stream_t *ctxPtr = (LZ4_stream_t *)vmalloc(sizeof(LZ4_stream_t)); /* malloc-calloc always properly aligned */
  if (ctxPtr == NULL) return 0;
  result = LZ4_compress_fast_extState(ctxPtr, source, dest, inputSize, maxOutputSize, acceleration);
  vfree(ctxPtr);
  return result;
}
References LZ4_compress_fast_extState(), vfree, and vmalloc.
Referenced by LZ4_compress_default().
LZ4_compress_fast_extState()
int LZ4_compress_fast_extState (void * state, const char * src, char * dst, int srcSize, int dstCapacity, int acceleration)
LZ4_compress_fast_extState() : Same as LZ4_compress_fast(), using an externally allocated memory space for its state. Use LZ4_sizeofState() to know how much memory must be allocated, and allocate it on 8-bytes boundaries (using malloc() typically). Then, provide this buffer as void* state to compression function.
Definition at line 922 of file Compression.cpp.
{
  LZ4_stream_t_internal *const ctx = &LZ4_initStream(state, sizeof(LZ4_stream_t))->internal_donotuse;
  assert(ctx != NULL);
  if (acceleration < 1) acceleration = 1;
  if (acceleration > 65537) acceleration = 65537;
  if (maxOutputSize >= LZ4_compressBound(inputSize)) {
    if (inputSize < LZ4_64Klimit) {
      return LZ4_compress_generic(ctx, source, dest, inputSize, NULL, 0, notLimited, byU16, noDict, noDictIssue, acceleration);
    } else {
      const tableType_t tableType = ((sizeof(void *) == 4) && ((uptrval)source > LZ4_DISTANCE_MAX)) ? byPtr : byU32;
      return LZ4_compress_generic(ctx, source, dest, inputSize, NULL, 0, notLimited, tableType, noDict, noDictIssue, acceleration);
    }
  } else {
    if (inputSize < LZ4_64Klimit) {
      return LZ4_compress_generic(ctx, source, dest, inputSize, NULL, maxOutputSize, limitedOutput, byU16, noDict, noDictIssue, acceleration);
    } else {
      const tableType_t tableType = ((sizeof(void *) == 4) && ((uptrval)source > LZ4_DISTANCE_MAX)) ? byPtr : byU32;
      return LZ4_compress_generic(ctx, source, dest, inputSize, NULL, maxOutputSize, limitedOutput, tableType, noDict, noDictIssue, acceleration);
    }
  }
}
References assert, byPtr, byU16, byU32, LZ4_stream_u::internal_donotuse, limitedOutput, LZ4_64Klimit, LZ4_compress_generic(), LZ4_compressBound(), LZ4_DISTANCE_MAX, LZ4_initStream(), noDict, noDictIssue, and notLimited.
Referenced by LZ4_compress_fast().
LZ4_compress_generic()
int LZ4_compress_generic (LZ4_stream_t_internal *const cctx, const char *const src, char *const dst, const int srcSize, int * inputConsumed, const int dstCapacity, const limitedOutput_directive outputDirective, const tableType_t tableType, const dict_directive dictDirective, const dictIssue_directive dictIssue, const int acceleration)
LZ4_compress_generic() : inlined, to ensure branches are decided at compilation time; takes care of src == (NULL, 0) and forward the rest to LZ4_compress_generic_validated
Definition at line 885 of file Compression.cpp.
{
  DEBUGLOG(5, "LZ4_compress_generic: srcSize=%i, dstCapacity=%i",
    srcSize, dstCapacity);
  if ((U32)srcSize > (U32)LZ4_MAX_INPUT_SIZE) { return 0; } /* Unsupported srcSize, too large (or negative) */
  if (srcSize == 0) { /* src == NULL supported if srcSize == 0 */
    if (outputDirective != notLimited && dstCapacity <= 0) return 0; /* no output, can't write anything */
    DEBUGLOG(5, "Generating an empty block");
    assert(outputDirective == notLimited || dstCapacity >= 1);
    assert(dst != NULL);
    dst[0] = 0;
    if (outputDirective == fillOutput) {
      assert(inputConsumed != NULL);
      *inputConsumed = 0;
    }
    return 1;
  }
  assert(src != NULL);
  return LZ4_compress_generic_validated(cctx, src, dst, srcSize,
    inputConsumed, /* only written into if outputDirective == fillOutput */
    dstCapacity, outputDirective,
    tableType, dictDirective, dictIssue, acceleration);
}
References assert, DEBUGLOG, fillOutput, LZ4_compress_generic_validated(), LZ4_MAX_INPUT_SIZE, and notLimited.
Referenced by LZ4_compress_fast_extState().
LZ4_compress_generic_validated()
int LZ4_compress_generic_validated (LZ4_stream_t_internal *const cctx, const char *const source, char *const dest, const int inputSize, int * inputConsumed, const int maxOutputSize, const limitedOutput_directive outputDirective, const tableType_t tableType, const dict_directive dictDirective, const dictIssue_directive dictIssue, const int acceleration)
LZ4_compress_generic() : inlined, to ensure branches are decided at compilation time. Presumed already validated at this stage:
source != NULL
inputSize > 0
Definition at line 484 of file Compression.cpp.
{
  int result;
  const BYTE *ip = (const BYTE *)source;
  U32 const startIndex = cctx->currentOffset;
  const BYTE *base = (const BYTE *)source - startIndex;
  const BYTE *lowLimit;
  const LZ4_stream_t_internal *dictCtx = (const LZ4_stream_t_internal *)cctx->dictCtx;
  const BYTE *const dictionary =
    dictDirective == usingDictCtx ? dictCtx->dictionary : cctx->dictionary;
  const U32 dictSize =
    dictDirective == usingDictCtx ? dictCtx->dictSize : cctx->dictSize;
  const U32 dictDelta = (dictDirective == usingDictCtx) ? startIndex - dictCtx->currentOffset : 0; /* make indexes in dictCtx comparable with index in current context */
  int const maybe_extMem = (dictDirective == usingExtDict) || (dictDirective == usingDictCtx);
  U32 const prefixIdxLimit = startIndex - dictSize; /* used when dictDirective == dictSmall */
  const BYTE *const dictEnd = dictionary ? dictionary + dictSize : dictionary;
  const BYTE *anchor = (const BYTE *)source;
  const BYTE *const iend = ip + inputSize;
  const BYTE *const mflimitPlusOne = iend - MFLIMIT + 1;
  const BYTE *const matchlimit = iend - LASTLITERALS;
  /* the dictCtx currentOffset is indexed on the start of the dictionary,
   * while a dictionary in the current context precedes the currentOffset */
  const BYTE *dictBase = (dictionary == NULL) ? NULL :
    (dictDirective == usingDictCtx) ?
    dictionary + dictSize - dictCtx->currentOffset :
    dictionary + dictSize - startIndex;
  BYTE *op = (BYTE *)dest;
  BYTE *const olimit = op + maxOutputSize;
  U32 offset = 0;
  U32 forwardH;
  DEBUGLOG(5, "LZ4_compress_generic_validated: srcSize=%i, tableType=%u", inputSize, tableType);
  assert(ip != NULL);
  /* If init conditions are not met, we don't have to mark stream
   * as having dirty context, since no action was taken yet */
  if (outputDirective == fillOutput && maxOutputSize < 1) { return 0; } /* Impossible to store anything */
  if ((tableType == byU16) && (inputSize >= LZ4_64Klimit)) { return 0; } /* Size too large (not within 64K limit) */
  if (tableType == byPtr) assert(dictDirective == noDict); /* only supported use case with byPtr */
  assert(acceleration >= 1);
  lowLimit = (const BYTE *)source - (dictDirective == withPrefix64k ? dictSize : 0);
  /* Update context state */
  if (dictDirective == usingDictCtx) {
    /* Subsequent linked blocks can't use the dictionary. */
    /* Instead, they use the block we just compressed. */
    cctx->dictCtx = NULL;
    cctx->dictSize = (U32)inputSize;
  } else {
    cctx->dictSize += (U32)inputSize;
  }
  cctx->currentOffset += (U32)inputSize;
  cctx->tableType = (U32)tableType;
  if (inputSize < LZ4_minLength) goto _last_literals; /* Input too small, no compression (all literals) */
  /* First Byte */
  LZ4_putPosition(ip, cctx->hashTable, tableType, base);
  ip++; forwardH = LZ4_hashPosition(ip, tableType);
  /* Main Loop */
  for (; ;) {
    const BYTE *match;
    BYTE *token;
    const BYTE *filledIp;
    /* Find a match */
    if (tableType == byPtr) {
      const BYTE *forwardIp = ip;
      int step = 1;
      int searchMatchNb = acceleration << LZ4_skipTrigger;
      do {
        U32 const h = forwardH;
        ip = forwardIp;
        forwardIp += step;
        step = (searchMatchNb++ >> LZ4_skipTrigger);
        if (unlikely(forwardIp > mflimitPlusOne)) goto _last_literals;
        assert(ip < mflimitPlusOne);
        match = LZ4_getPositionOnHash(h, cctx->hashTable, tableType, base);
        forwardH = LZ4_hashPosition(forwardIp, tableType);
        LZ4_putPositionOnHash(ip, h, cctx->hashTable, tableType, base);
      } while ((match + LZ4_DISTANCE_MAX < ip)
        || (LZ4_read32(match) != LZ4_read32(ip)));
    } else { /* byU32, byU16 */
      const BYTE *forwardIp = ip;
      int step = 1;
      int searchMatchNb = acceleration << LZ4_skipTrigger;
      do {
        U32 const h = forwardH;
        U32 const current = (U32)(forwardIp - base);
        U32 matchIndex = LZ4_getIndexOnHash(h, cctx->hashTable, tableType);
        assert(matchIndex <= current);
        assert(forwardIp - base < (ptrdiff_t)(2 GB - 1));
        ip = forwardIp;
        forwardIp += step;
        step = (searchMatchNb++ >> LZ4_skipTrigger);
        if (unlikely(forwardIp > mflimitPlusOne)) goto _last_literals;
        assert(ip < mflimitPlusOne);
        if (dictDirective == usingDictCtx) {
          if (matchIndex < startIndex) {
            /* there was no match, try the dictionary */
            assert(tableType == byU32);
            matchIndex = LZ4_getIndexOnHash(h, dictCtx->hashTable, byU32);
            match = dictBase + matchIndex;
            matchIndex += dictDelta; /* make dictCtx index comparable with current context */
            lowLimit = dictionary;
          } else {
            match = base + matchIndex;
            lowLimit = (const BYTE *)source;
          }
        } else if (dictDirective == usingExtDict) {
          if (matchIndex < startIndex) {
            DEBUGLOG(7, "extDict candidate: matchIndex=%5u < startIndex=%5u", matchIndex, startIndex);
            assert(startIndex - matchIndex >= MINMATCH);
            assert(dictBase);
            match = dictBase + matchIndex;
            lowLimit = dictionary;
          } else {
            match = base + matchIndex;
            lowLimit = (const BYTE *)source;
          }
        } else { /* single continuous memory segment */
          match = base + matchIndex;
        }
        forwardH = LZ4_hashPosition(forwardIp, tableType);
        LZ4_putIndexOnHash(current, h, cctx->hashTable, tableType);
        DEBUGLOG(7, "candidate at pos=%u (offset=%u \n", matchIndex, current - matchIndex);
        if ((dictIssue == dictSmall) && (matchIndex < prefixIdxLimit)) { continue; } /* match outside of valid area */
        assert(matchIndex < current);
        if (((tableType != byU16) || (LZ4_DISTANCE_MAX < LZ4_DISTANCE_ABSOLUTE_MAX))
          && (matchIndex + LZ4_DISTANCE_MAX < current)) {
          continue;
        } /* too far */
        assert((current - matchIndex) <= LZ4_DISTANCE_MAX); /* match now expected within distance */
        if (LZ4_read32(match) == LZ4_read32(ip)) {
          if (maybe_extMem) offset = current - matchIndex;
          break; /* match found */
        }
      } while (1);
    }
    /* Catch up */
    filledIp = ip;
    while (((ip > anchor) & (match > lowLimit)) && (unlikely(ip[-1] == match[-1]))) { ip--; match--; }
    /* Encode Literals */
    {
      unsigned const litLength = (unsigned)(ip - anchor);
      token = op++;
      if ((outputDirective == limitedOutput) && /* Check output buffer overflow */
        (unlikely(op + litLength + (2 + 1 + LASTLITERALS) + (litLength / 255) > olimit))) {
        return 0; /* cannot compress within `dst` budget. Stored indexes in hash table are nonetheless fine */
      }
      if ((outputDirective == fillOutput) &&
        (unlikely(op + (litLength + 240) / 255 /* litlen */ + litLength /* literals */ + 2 /* offset */ + 1 /* token */ + MFLIMIT - MINMATCH /* min last literals so last match is <= end - MFLIMIT */ > olimit))) {
        op--;
        goto _last_literals;
      }
      if (litLength >= RUN_MASK) {
        int len = (int)(litLength - RUN_MASK);
        *token = (RUN_MASK << ML_BITS);
        for (; len >= 255; len -= 255) *op++ = 255;
        *op++ = (BYTE)len;
      } else *token = (BYTE)(litLength << ML_BITS);
      /* Copy Literals */
      LZ4_wildCopy8(op, anchor, op + litLength);
      op += litLength;
      DEBUGLOG(6, "seq.start:%i, literals=%u, match.start:%i",
        (int)(anchor - (const BYTE *)source), litLength, (int)(ip - (const BYTE *)source));
    }
  _next_match:
    /* at this stage, the following variables must be correctly set :
     * - ip : at start of LZ operation
     * - match : at start of previous pattern occurrence; can be within current prefix, or within extDict
     * - offset : if maybe_ext_memSegment==1 (constant)
     * - lowLimit : must be == dictionary to mean "match is within extDict"; must be == source otherwise
     * - token and *token : position to write 4-bits for match length; higher 4-bits for literal length supposed already written
     */
    if ((outputDirective == fillOutput) &&
      (op + 2 /* offset */ + 1 /* token */ + MFLIMIT - MINMATCH /* min last literals so last match is <= end - MFLIMIT */ > olimit)) {
      /* the match was too close to the end, rewind and go to last literals */
      op = token;
      goto _last_literals;
    }
    /* Encode Offset */
    if (maybe_extMem) { /* static test */
      DEBUGLOG(6, " with offset=%u (ext if > %i)", offset, (int)(ip - (const BYTE *)source));
      assert(offset <= LZ4_DISTANCE_MAX && offset > 0);
      LZ4_writeLE16(op, (U16)offset); op += 2;
    } else {
      DEBUGLOG(6, " with offset=%u (same segment)", (U32)(ip - match));
      assert(ip - match <= LZ4_DISTANCE_MAX);
      LZ4_writeLE16(op, (U16)(ip - match)); op += 2;
    }
    /* Encode MatchLength */
    {
      unsigned matchCode;
      if ((dictDirective == usingExtDict || dictDirective == usingDictCtx)
        && (lowLimit == dictionary) /* match within extDict */) {
        const BYTE *limit = ip + (dictEnd - match);
        assert(dictEnd > match);
        if (limit > matchlimit) limit = matchlimit;
        matchCode = LZ4_count(ip + MINMATCH, match + MINMATCH, limit);
        ip += (size_t)matchCode + MINMATCH;
        if (ip == limit) {
          unsigned const more = LZ4_count(limit, (const BYTE *)source, matchlimit);
          matchCode += more;
          ip += more;
        }
        DEBUGLOG(6, " with matchLength=%u starting in extDict", matchCode + MINMATCH);
      } else {
        matchCode = LZ4_count(ip + MINMATCH, match + MINMATCH, matchlimit);
        ip += (size_t)matchCode + MINMATCH;
        DEBUGLOG(6, " with matchLength=%u", matchCode + MINMATCH);
      }
      if ((outputDirective) && /* Check output buffer overflow */
        (unlikely(op + (1 + LASTLITERALS) + (matchCode + 240) / 255 > olimit))) {
        if (outputDirective == fillOutput) {
          /* Match description too long : reduce it */
          U32 newMatchCode = 15 /* in token */ - 1 /* to avoid needing a zero byte */ + ((U32)(olimit - op) - 1 - LASTLITERALS) * 255;
          ip -= matchCode - newMatchCode;
          assert(newMatchCode < matchCode);
          matchCode = newMatchCode;
          if (unlikely(ip <= filledIp)) {
            /* We have already filled up to filledIp so if ip ends up less than filledIp
             * we have positions in the hash table beyond the current position. This is
             * a problem if we reuse the hash table. So we have to remove these positions
             * from the hash table.
             */
            const BYTE *ptr;
            DEBUGLOG(5, "Clearing %u positions", (U32)(filledIp - ip));
            for (ptr = ip; ptr <= filledIp; ++ptr) {
              U32 const h = LZ4_hashPosition(ptr, tableType);
              LZ4_clearHash(h, cctx->hashTable, tableType);
            }
          }
        } else {
          assert(outputDirective == limitedOutput);
          return 0; /* cannot compress within `dst` budget. Stored indexes in hash table are nonetheless fine */
        }
      }
      if (matchCode >= ML_MASK) {
        *token += ML_MASK;
        matchCode -= ML_MASK;
        LZ4_write32(op, 0xFFFFFFFF);
        while (matchCode >= 4 * 255) {
          op += 4;
          LZ4_write32(op, 0xFFFFFFFF);
          matchCode -= 4 * 255;
        }
        op += matchCode / 255;
        *op++ = (BYTE)(matchCode % 255);
      } else
        *token += (BYTE)(matchCode);
    }
    /* Ensure we have enough space for the last literals. */
    assert(!(outputDirective == fillOutput && op + 1 + LASTLITERALS > olimit));
    anchor = ip;
    /* Test end of chunk */
    if (ip >= mflimitPlusOne) break;
    /* Fill table */
    LZ4_putPosition(ip - 2, cctx->hashTable, tableType, base);
    /* Test next position */
    if (tableType == byPtr) {
      match = LZ4_getPosition(ip, cctx->hashTable, tableType, base);
      LZ4_putPosition(ip, cctx->hashTable, tableType, base);
      if ((match + LZ4_DISTANCE_MAX >= ip)
        && (LZ4_read32(match) == LZ4_read32(ip))) {
        token = op++; *token = 0; goto _next_match;
      }
    } else { /* byU32, byU16 */
      U32 const h = LZ4_hashPosition(ip, tableType);
      U32 const current = (U32)(ip - base);
      U32 matchIndex = LZ4_getIndexOnHash(h, cctx->hashTable, tableType);
      assert(matchIndex < current);
      if (dictDirective == usingDictCtx) {
        if (matchIndex < startIndex) {
          /* there was no match, try the dictionary */
          matchIndex = LZ4_getIndexOnHash(h, dictCtx->hashTable, byU32);
          match = dictBase + matchIndex;
          lowLimit = dictionary; /* required for match length counter */
          matchIndex += dictDelta;
        } else {
          match = base + matchIndex;
          lowLimit = (const BYTE *)source; /* required for match length counter */
        }
      } else if (dictDirective == usingExtDict) {
        if (matchIndex < startIndex) {
          assert(dictBase);
          match = dictBase + matchIndex;
          lowLimit = dictionary; /* required for match length counter */
        } else {
          match = base + matchIndex;
          lowLimit = (const BYTE *)source; /* required for match length counter */
        }
      } else { /* single memory segment */
        match = base + matchIndex;
      }
      LZ4_putIndexOnHash(current, h, cctx->hashTable, tableType);
      assert(matchIndex < current);
      if (((dictIssue == dictSmall) ? (matchIndex >= prefixIdxLimit) : 1)
        && (((tableType == byU16) && (LZ4_DISTANCE_MAX == LZ4_DISTANCE_ABSOLUTE_MAX)) ? 1 : (matchIndex + LZ4_DISTANCE_MAX >= current))
        && (LZ4_read32(match) == LZ4_read32(ip))) {
        token = op++;
        *token = 0;
        if (maybe_extMem) offset = current - matchIndex;
        DEBUGLOG(6, "seq.start:%i, literals=%u, match.start:%i",
          (int)(anchor - (const BYTE *)source), 0, (int)(ip - (const BYTE *)source));
        goto _next_match;
      }
    }
    /* Prepare next loop */
    forwardH = LZ4_hashPosition(++ip, tableType);
  }
_last_literals:
  /* Encode Last Literals */
  {
    size_t lastRun = (size_t)(iend - anchor);
    if ((outputDirective) && /* Check output buffer overflow */
      (op + lastRun + 1 + ((lastRun + 255 - RUN_MASK) / 255) > olimit)) {
      if (outputDirective == fillOutput) {
        /* adapt lastRun to fill 'dst' */
        assert(olimit >= op);
        lastRun = (size_t)(olimit - op) - 1/*token*/;
        lastRun -= (lastRun + 256 - RUN_MASK) / 256; /*additional length tokens*/
      } else {
        assert(outputDirective == limitedOutput);
        return 0; /* cannot compress within `dst` budget. Stored indexes in hash table are nonetheless fine */
      }
    }
    DEBUGLOG(6, "Final literal run : %i literals", (int)lastRun);
    if (lastRun >= RUN_MASK) {
      size_t accumulator = lastRun - RUN_MASK;
      *op++ = RUN_MASK << ML_BITS;
      for (; accumulator >= 255; accumulator -= 255) *op++ = 255;
      *op++ = (BYTE)accumulator;
    } else {
      *op++ = (BYTE)(lastRun << ML_BITS);
    }
    LZ4_memcpy(op, anchor, lastRun);
    ip = anchor + lastRun;
    op += lastRun;
  }
  if (outputDirective == fillOutput) {
    *inputConsumed = (int)(((const char *)ip) - source);
  }
  result = (int)(((char *)op) - dest);
  assert(result > 0);
  DEBUGLOG(5, "LZ4_compress_generic: compressed %i bytes into %i bytes", inputSize, result);
  return result;
}
References assert, byPtr, byU16, byU32, LZ4_stream_t_internal::currentOffset, DEBUGLOG, LZ4_stream_t_internal::dictCtx, LZ4_stream_t_internal::dictionary, LZ4_stream_t_internal::dictSize, dictSmall, fillOutput, GB, LZ4_stream_t_internal::hashTable, LASTLITERALS, limitedOutput, LZ4_64Klimit, LZ4_clearHash(), LZ4_count(), LZ4_DISTANCE_ABSOLUTE_MAX, LZ4_DISTANCE_MAX, LZ4_getIndexOnHash(), LZ4_getPosition(), LZ4_getPositionOnHash(), LZ4_hashPosition(), LZ4_memcpy, LZ4_minLength, LZ4_putIndexOnHash(), LZ4_putPosition(), LZ4_putPositionOnHash(), LZ4_read32(), LZ4_skipTrigger, LZ4_wildCopy8(), LZ4_write32(), LZ4_writeLE16(), MFLIMIT, MINMATCH, ML_BITS, ML_MASK, noDict, RUN_MASK, LZ4_stream_t_internal::tableType, unlikely, usingDictCtx, usingExtDict, and withPrefix64k.
Referenced by LZ4_compress_generic().
LZ4_compressBound()
int LZ4_compressBound (int inputSize)
LZ4_compressBound() : Provides the maximum size that LZ4 compression may output in a `worst case` scenario (input data not compressible) This function is primarily useful for memory allocation purposes (destination buffer size). Macro LZ4_COMPRESSBOUND() is also provided for compilation-time evaluation (stack memory allocation for example). Note that LZ4_compress_default() compresses faster when dstCapacity is >= LZ4_compressBound(srcSize) inputSize : max supported value is LZ4_MAX_INPUT_SIZE return : maximum output size in a `worst case` scenario or 0, if input size is incorrect (too large or negative)
Definition at line 370 of file Compression.cpp.
{ return LZ4_COMPRESSBOUND(isize); }
References LZ4_COMPRESSBOUND.
Referenced by LZ4_compress_fast_extState().
LZ4_count()
unsigned LZ4_count (const BYTE * pIn, const BYTE * pMatch, const BYTE * pInLimit)
Definition at line 301 of file Compression.cpp.
{
  const BYTE *const pStart = pIn;
  if (likely(pIn < pInLimit - (STEPSIZE - 1))) {
    reg_t const diff = LZ4_read_ARCH(pMatch) ^ LZ4_read_ARCH(pIn);
    if (!diff) {
      pIn += STEPSIZE; pMatch += STEPSIZE;
    } else {
      return LZ4_NbCommonBytes(diff);
    }
  }
  while (likely(pIn < pInLimit - (STEPSIZE - 1))) {
    reg_t const diff = LZ4_read_ARCH(pMatch) ^ LZ4_read_ARCH(pIn);
    if (!diff) { pIn += STEPSIZE; pMatch += STEPSIZE; continue; }
    pIn += LZ4_NbCommonBytes(diff);
    return (unsigned)(pIn - pStart);
  }
  if ((STEPSIZE == 8) && (pIn < (pInLimit - 3)) && (LZ4_read32(pMatch) == LZ4_read32(pIn))) { pIn += 4; pMatch += 4; }
  if ((pIn < (pInLimit - 1)) && (LZ4_read16(pMatch) == LZ4_read16(pIn))) { pIn += 2; pMatch += 2; }
  if ((pIn < pInLimit) && (*pMatch == *pIn)) pIn++;
  return (unsigned)(pIn - pStart);
}
References likely, LZ4_NbCommonBytes(), LZ4_read16(), LZ4_read32(), LZ4_read_ARCH(), and STEPSIZE.
Referenced by LZ4_compress_generic_validated().
LZ4_decompress_generic()
int LZ4_decompress_generic (const char *const src, char *const dst, int srcSize, int outputSize, endCondition_directive endOnInput, earlyEnd_directive partialDecoding, dict_directive dict, const BYTE *const lowPrefix, const BYTE *const dictStart, const size_t dictSize)
LZ4_decompress_generic() : This generic decompression function covers all use cases. It shall be instantiated several times, using different sets of directives. Note that it is important for performance that this function really get inlined, in order to remove useless branches during compilation optimization.
Definition at line 1033 of file Compression.cpp.
{
  if ((src == NULL) || (outputSize < 0)) { return -1; }
  {
    const BYTE *ip = (const BYTE *)src;
    const BYTE *const iend = ip + srcSize;
    BYTE *op = (BYTE *)dst;
    BYTE *const oend = op + outputSize;
    BYTE *cpy;
    const BYTE *const dictEnd = (dictStart == NULL) ? NULL : dictStart + dictSize;
    const int safeDecode = (endOnInput == endOnInputSize);
    const int checkOffset = ((safeDecode) && (dictSize < (int)(64 KB)));
    /* Set up the "end" pointers for the shortcut. */
    const BYTE *const shortiend = iend - (endOnInput ? 14 : 8) /*maxLL*/ - 2 /*offset*/;
    const BYTE *const shortoend = oend - (endOnInput ? 14 : 8) /*maxLL*/ - 18 /*maxML*/;
    const BYTE *match;
    size_t offset;
    unsigned token;
    size_t length;
    DEBUGLOG(5, "LZ4_decompress_generic (srcSize:%i, dstSize:%i)", srcSize, outputSize);
    /* Special cases */
    assert(lowPrefix <= op);
    if ((endOnInput) && (unlikely(outputSize == 0))) {
      /* Empty output buffer */
      if (partialDecoding) return 0;
      return ((srcSize == 1) && (*ip == 0)) ? 0 : -1;
    }
    if ((!endOnInput) && (unlikely(outputSize == 0))) { return (*ip == 0 ? 1 : -1); }
    if ((endOnInput) && unlikely(srcSize == 0)) { return -1; }
    /* Currently the fast loop shows a regression on qualcomm arm chips. */
    if ((oend - op) < FASTLOOP_SAFE_DISTANCE) {
      DEBUGLOG(6, "skip fast decode loop");
      goto safe_decode;
    }
    /* Fast loop : decode sequences as long as output < iend-FASTLOOP_SAFE_DISTANCE */
    while (1) {
      /* Main fastloop assertion: We can always wildcopy FASTLOOP_SAFE_DISTANCE */
      assert(oend - op >= FASTLOOP_SAFE_DISTANCE);
      if (endOnInput) { assert(ip < iend); }
      token = *ip++;
      length = token >> ML_BITS; /* literal length */
      assert(!endOnInput || ip <= iend); /* ip < iend before the increment */
      /* decode literal length */
      if (length == RUN_MASK) {
        variable_length_error error = ok;
        length += read_variable_length(&ip, iend - RUN_MASK, (int)endOnInput, (int)endOnInput, &error);
        if (error == initial_error) { goto _output_error; }
        if ((safeDecode) && unlikely((uptrval)(op)+length < (uptrval)(op))) { goto _output_error; } /* overflow detection */
        if ((safeDecode) && unlikely((uptrval)(ip)+length < (uptrval)(ip))) { goto _output_error; } /* overflow detection */
        /* copy literals */
        cpy = op + length;
        LZ4_STATIC_ASSERT(MFLIMIT >= WILDCOPYLENGTH);
        if (endOnInput) { /* LZ4_decompress_safe() */
          if ((cpy > oend - 32) || (ip + length > iend - 32)) { goto safe_literal_copy; }
          LZ4_wildCopy32(op, ip, cpy);
        } else { /* LZ4_decompress_fast() */
          if (cpy > oend - 8) { goto safe_literal_copy; }
          LZ4_wildCopy8(op, ip, cpy); /* LZ4_decompress_fast() cannot copy more than 8 bytes at a time :
                                       * it doesn't know input length, and only relies on end-of-block properties */
        }
        ip += length; op = cpy;
      } else {
        cpy = op + length;
        if (endOnInput) { /* LZ4_decompress_safe() */
          DEBUGLOG(7, "copy %u bytes in a 16-bytes stripe", (unsigned)length);
          /* We don't need to check oend, since we check it once for each loop below */
          if (ip > iend - (16 + 1/*max lit + offset + nextToken*/)) { goto safe_literal_copy; }
          /* Literals can only be 14, but hope compilers optimize if we copy by a register size */
          LZ4_memcpy(op, ip, 16);
        } else { /* LZ4_decompress_fast() */
            /* LZ4_decompress_fast() cannot copy more than 8 bytes at a time :
             * it doesn't know input length, and relies on end-of-block properties */
          LZ4_memcpy(op, ip, 8);
          if (length > 8) { LZ4_memcpy(op + 8, ip + 8, 8); }
        }
        ip += length; op = cpy;
      }
      /* get offset */
      offset = LZ4_readLE16(ip); ip += 2;
      match = op - offset;
      assert(match <= op);
      /* get matchlength */
      length = token & ML_MASK;
      if (length == ML_MASK) {
        variable_length_error error = ok;
        if ((checkOffset) && (unlikely(match + dictSize < lowPrefix))) { goto _output_error; } /* Error : offset outside buffers */
        length += read_variable_length(&ip, iend - LASTLITERALS + 1, (int)endOnInput, 0, &error);
        if (error != ok) { goto _output_error; }
        if ((safeDecode) && unlikely((uptrval)(op)+length < (uptrval)op)) { goto _output_error; } /* overflow detection */
        length += MINMATCH;
        if (op + length >= oend - FASTLOOP_SAFE_DISTANCE) {
          goto safe_match_copy;
        }
      } else {
        length += MINMATCH;
        if (op + length >= oend - FASTLOOP_SAFE_DISTANCE) {
          goto safe_match_copy;
        }
        /* Fastpath check: Avoids a branch in LZ4_wildCopy32 if true */
        if ((dict == withPrefix64k) || (match >= lowPrefix)) {
          if (offset >= 8) {
            assert(match >= lowPrefix);
            assert(match <= op);
            assert(op + 18 <= oend);
            LZ4_memcpy(op, match, 8);
            LZ4_memcpy(op + 8, match + 8, 8);
            LZ4_memcpy(op + 16, match + 16, 2);
            op += length;
            continue;
          }
        }
      }
      if (checkOffset && (unlikely(match + dictSize < lowPrefix))) { goto _output_error; } /* Error : offset outside buffers */
      /* match starting within external dictionary */
      if ((dict == usingExtDict) && (match < lowPrefix)) {
        if (unlikely(op + length > oend - LASTLITERALS)) {
          if (partialDecoding) {
            DEBUGLOG(7, "partialDecoding: dictionary match, close to dstEnd");
            length = MIN(length, (size_t)(oend - op));
          } else {
            goto _output_error; /* end-of-block condition violated */
          }
        }
        if (length <= (size_t)(lowPrefix - match)) {
          /* match fits entirely within external dictionary : just copy */
          memmove(op, dictEnd - (lowPrefix - match), length);
          op += length;
        } else {
          /* match stretches into both external dictionary and current block */
          size_t const copySize = (size_t)(lowPrefix - match);
          size_t const restSize = length - copySize;
          LZ4_memcpy(op, dictEnd - copySize, copySize);
          op += copySize;
          if (restSize > (size_t)(op - lowPrefix)) { /* overlap copy */
            BYTE *const endOfMatch = op + restSize;
            const BYTE *copyFrom = lowPrefix;
            while (op < endOfMatch) { *op++ = *copyFrom++; }
          } else {
            LZ4_memcpy(op, lowPrefix, restSize);
            op += restSize;
          }
        }
        continue;
      }
      /* copy match within block */
      cpy = op + length;
      assert((op <= oend) && (oend - op >= 32));
      if (unlikely(offset < 16)) {
        LZ4_memcpy_using_offset(op, match, cpy, offset);
      } else {
        LZ4_wildCopy32(op, match, cpy);
      }
      op = cpy; /* wildcopy correction */
    }
  safe_decode:
    /* Main Loop : decode remaining sequences where output < FASTLOOP_SAFE_DISTANCE */
    while (1) {
      token = *ip++;
      length = token >> ML_BITS; /* literal length */
      assert(!endOnInput || ip <= iend); /* ip < iend before the increment */
      /* A two-stage shortcut for the most common case:
       * 1) If the literal length is 0..14, and there is enough space,
       * enter the shortcut and copy 16 bytes on behalf of the literals
       * (in the fast mode, only 8 bytes can be safely copied this way).
       * 2) Further if the match length is 4..18, copy 18 bytes in a similar
       * manner; but we ensure that there's enough space in the output for
       * those 18 bytes earlier, upon entering the shortcut (in other words,
       * there is a combined check for both stages).
       */
      if ((endOnInput ? length != RUN_MASK : length <= 8)
        /* strictly "less than" on input, to re-enter the loop with at least one byte */
        && likely((endOnInput ? ip < shortiend : 1) & (op <= shortoend))) {
        /* Copy the literals */
        LZ4_memcpy(op, ip, endOnInput ? 16 : 8);
        op += length; ip += length;
        /* The second stage: prepare for match copying, decode full info.
         * If it doesn't work out, the info won't be wasted. */
        length = token & ML_MASK; /* match length */
        offset = LZ4_readLE16(ip); ip += 2;
        match = op - offset;
        assert(match <= op); /* check overflow */
        /* Do not deal with overlapping matches. */
        if ((length != ML_MASK)
          && (offset >= 8)
          && (dict == withPrefix64k || match >= lowPrefix)) {
          /* Copy the match. */
          LZ4_memcpy(op + 0, match + 0, 8);
          LZ4_memcpy(op + 8, match + 8, 8);
          LZ4_memcpy(op + 16, match + 16, 2);
          op += length + MINMATCH;
          /* Both stages worked, load the next token. */
          continue;
        }
        /* The second stage didn't work out, but the info is ready.
         * Propel it right to the point of match copying. */
        goto _copy_match;
      }
      /* decode literal length */
      if (length == RUN_MASK) {
        variable_length_error error = ok;
        length += read_variable_length(&ip, iend - RUN_MASK, (int)endOnInput, (int)endOnInput, &error);
        if (error == initial_error) { goto _output_error; }
        if ((safeDecode) && unlikely((uptrval)(op)+length < (uptrval)(op))) { goto _output_error; } /* overflow detection */
        if ((safeDecode) && unlikely((uptrval)(ip)+length < (uptrval)(ip))) { goto _output_error; } /* overflow detection */
      }
      /* copy literals */
      cpy = op + length;
      safe_literal_copy :
      LZ4_STATIC_ASSERT(MFLIMIT >= WILDCOPYLENGTH);
      if (((endOnInput) && ((cpy > oend - MFLIMIT) || (ip + length > iend - (2 + 1 + LASTLITERALS))))
        || ((!endOnInput) && (cpy > oend - WILDCOPYLENGTH))) {
        /* We've either hit the input parsing restriction or the output parsing restriction.
         * In the normal scenario, decoding a full block, it must be the last sequence,
         * otherwise it's an error (invalid input or dimensions).
         * In partialDecoding scenario, it's necessary to ensure there is no buffer overflow.
         */
        if (partialDecoding) {
          /* Since we are partial decoding we may be in this block because of the output parsing
           * restriction, which is not valid since the output buffer is allowed to be undersized.
           */
          assert(endOnInput);
          DEBUGLOG(7, "partialDecoding: copying literals, close to input or output end")
            DEBUGLOG(7, "partialDecoding: literal length = %u", (unsigned)length);
          DEBUGLOG(7, "partialDecoding: remaining space in dstBuffer : %i", (int)(oend - op));
          DEBUGLOG(7, "partialDecoding: remaining space in srcBuffer : %i", (int)(iend - ip));
          /* Finishing in the middle of a literals segment,
           * due to lack of input.
           */
          if (ip + length > iend) {
            length = (size_t)(iend - ip);
            cpy = op + length;
          }
          /* Finishing in the middle of a literals segment,
           * due to lack of output space.
           */
          if (cpy > oend) {
            cpy = oend;
            assert(op <= oend);
            length = (size_t)(oend - op);
          }
        } else {
          /* We must be on the last sequence because of the parsing limitations so check
           * that we exactly regenerate the original size (must be exact when !endOnInput).
           */
          if ((!endOnInput) && (cpy != oend)) { goto _output_error; }
          /* We must be on the last sequence (or invalid) because of the parsing limitations
           * so check that we exactly consume the input and don't overrun the output buffer.
           */
          if ((endOnInput) && ((ip + length != iend) || (cpy > oend))) {
            DEBUGLOG(6, "should have been last run of literals")
              DEBUGLOG(6, "ip(%p) + length(%i) = %p != iend (%p)", ip, (int)length, ip + length, iend);
            DEBUGLOG(6, "or cpy(%p) > oend(%p)", cpy, oend);
            goto _output_error;
          }
        }
        memmove(op, ip, length); /* supports overlapping memory regions; only matters for in-place decompression scenarios */
        ip += length;
        op += length;
        /* Necessarily EOF when !partialDecoding.
         * When partialDecoding, it is EOF if we've either
         * filled the output buffer or
         * can't proceed with reading an offset for following match.
         */
        if (!partialDecoding || (cpy == oend) || (ip >= (iend - 2))) {
          break;
        }
      } else {
        LZ4_wildCopy8(op, ip, cpy); /* may overwrite up to WILDCOPYLENGTH beyond cpy */
        ip += length; op = cpy;
      }
      /* get offset */
      offset = LZ4_readLE16(ip); ip += 2;
      match = op - offset;
      /* get matchlength */
      length = token & ML_MASK;
    _copy_match:
      if (length == ML_MASK) {
        variable_length_error error = ok;
        length += read_variable_length(&ip, iend - LASTLITERALS + 1, (int)endOnInput, 0, &error);
        if (error != ok) goto _output_error;
        if ((safeDecode) && unlikely((uptrval)(op)+length < (uptrval)op)) goto _output_error; /* overflow detection */
      }
      length += MINMATCH;
      safe_match_copy :
      if ((checkOffset) && (unlikely(match + dictSize < lowPrefix))) goto _output_error; /* Error : offset outside buffers */
      /* match starting within external dictionary */
      if ((dict == usingExtDict) && (match < lowPrefix)) {
        if (unlikely(op + length > oend - LASTLITERALS)) {
          if (partialDecoding) length = MIN(length, (size_t)(oend - op));
          else goto _output_error; /* doesn't respect parsing restriction */
        }
        if (length <= (size_t)(lowPrefix - match)) {
          /* match fits entirely within external dictionary : just copy */
          memmove(op, dictEnd - (lowPrefix - match), length);
          op += length;
        } else {
          /* match stretches into both external dictionary and current block */
          size_t const copySize = (size_t)(lowPrefix - match);
          size_t const restSize = length - copySize;
          LZ4_memcpy(op, dictEnd - copySize, copySize);
          op += copySize;
          if (restSize > (size_t)(op - lowPrefix)) { /* overlap copy */
            BYTE *const endOfMatch = op + restSize;
            const BYTE *copyFrom = lowPrefix;
            while (op < endOfMatch) *op++ = *copyFrom++;
          } else {
            LZ4_memcpy(op, lowPrefix, restSize);
            op += restSize;
          }
        }
        continue;
      }
      assert(match >= lowPrefix);
      /* copy match within block */
      cpy = op + length;
      /* partialDecoding : may end anywhere within the block */
      assert(op <= oend);
      if (partialDecoding && (cpy > oend - MATCH_SAFEGUARD_DISTANCE)) {
        size_t const mlen = MIN(length, (size_t)(oend - op));
        const BYTE *const matchEnd = match + mlen;
        BYTE *const copyEnd = op + mlen;
        if (matchEnd > op) { /* overlap copy */
          while (op < copyEnd) { *op++ = *match++; }
        } else {
          LZ4_memcpy(op, match, mlen);
        }
        op = copyEnd;
        if (op == oend) { break; }
        continue;
      }
      if (unlikely(offset < 8)) {
        LZ4_write32(op, 0); /* silence msan warning when offset==0 */
        op[0] = match[0];
        op[1] = match[1];
        op[2] = match[2];
        op[3] = match[3];
        match += inc32table[offset];
        LZ4_memcpy(op + 4, match, 4);
        match -= dec64table[offset];
      } else {
        LZ4_memcpy(op, match, 8);
        match += 8;
      }
      op += 8;
      if (unlikely(cpy > oend - MATCH_SAFEGUARD_DISTANCE)) {
        BYTE *const oCopyLimit = oend - (WILDCOPYLENGTH - 1);
        if (cpy > oend - LASTLITERALS) { goto _output_error; } /* Error : last LASTLITERALS bytes must be literals (uncompressed) */
        if (op < oCopyLimit) {
          LZ4_wildCopy8(op, match, oCopyLimit);
          match += oCopyLimit - op;
          op = oCopyLimit;
        }
        while (op < cpy) { *op++ = *match++; }
      } else {
        LZ4_memcpy(op, match, 8);
        if (length > 16) { LZ4_wildCopy8(op + 8, match + 8, cpy); }
      }
      op = cpy; /* wildcopy correction */
    }
    /* end of decoding */
    if (endOnInput) {
      DEBUGLOG(5, "decoded %i bytes", (int)(((char *)op) - dst));
      return (int)(((char *)op) - dst); /* Nb of output bytes decoded */
    } else {
      return (int)(((const char *)ip) - src); /* Nb of input bytes read */
    }
    /* Overflow error detected */
  _output_error:
    return (int)(-(((const char *)ip) - src)) - 1;
  }
}
References assert, DEBUGLOG, dec64table, endOnInputSize, FASTLOOP_SAFE_DISTANCE, inc32table, initial_error, KB, LASTLITERALS, likely, LZ4_memcpy, LZ4_memcpy_using_offset(), LZ4_readLE16(), LZ4_STATIC_ASSERT, LZ4_wildCopy32(), LZ4_wildCopy8(), LZ4_write32(), MATCH_SAFEGUARD_DISTANCE, MFLIMIT, MIN, MINMATCH, ML_BITS, ML_MASK, ok, read_variable_length(), RUN_MASK, unlikely, usingExtDict, WILDCOPYLENGTH, and withPrefix64k.
Referenced by LZ4_decompress_safe().
LZ4_decompress_safe()
int LZ4_decompress_safe (const char * src, char * dst, int compressedSize, int dstCapacity)
LZ4_decompress_safe() : compressedSize : is the exact complete size of the compressed block. dstCapacity : is the size of destination buffer (which must be already allocated), presumed an upper bound of decompressed size.
Returns
: the number of bytes decompressed into destination buffer (necessarily <= dstCapacity) If destination buffer is not large enough, decoding will stop and output an error code (negative value). If the source stream is detected malformed, the function will stop decoding and return a negative result. Note 1 : This function is protected against malicious data packets : it will never writes outside 'dst' buffer, nor read outside 'source' buffer, even if the compressed block is maliciously modified to order the decoder to do these actions. In such case, the decoder stops immediately, and considers the compressed block malformed. Note 2 : compressedSize and dstCapacity must be provided to the function, the compressed block does not contain them. The implementation is free to send / store / derive this information in whichever way is most beneficial. If there is a need for a different format which bundles together both compressed data and its metadata, consider looking at lz4frame.h instead.
Definition at line 1461 of file Compression.cpp.
{
  return LZ4_decompress_generic(source, dest, compressedSize, maxDecompressedSize,
    endOnInputSize, decode_full_block, noDict,
    (BYTE *)dest, NULL, 0);
}
References decode_full_block, endOnInputSize, LZ4_decompress_generic(), and noDict.
LZ4_getIndexOnHash()
U32 LZ4_getIndexOnHash (U32 h, const void * tableBase, tableType_t tableType)
Definition at line 447 of file Compression.cpp.
{
  LZ4_STATIC_ASSERT(LZ4_MEMORY_USAGE > 2);
  if (tableType == byU32) {
    const U32 *const hashTable = (const U32 *)tableBase;
    assert(h < (1U << (LZ4_MEMORY_USAGE - 2)));
    return hashTable[h];
  }
  if (tableType == byU16) {
    const U16 *const hashTable = (const U16 *)tableBase;
    assert(h < (1U << (LZ4_MEMORY_USAGE - 1)));
    return hashTable[h];
  }
  assert(0); return 0; /* forbidden case */
}
References assert, byU16, byU32, LZ4_MEMORY_USAGE, and LZ4_STATIC_ASSERT.
Referenced by LZ4_compress_generic_validated().
LZ4_getPosition()
const BYTE* LZ4_getPosition (const BYTE * p, const void * tableBase, tableType_t tableType, const BYTE * srcBase)
Definition at line 470 of file Compression.cpp.
{
  U32 const h = LZ4_hashPosition(p, tableType);
  return LZ4_getPositionOnHash(h, tableBase, tableType, srcBase);
}
References LZ4_getPositionOnHash(), and LZ4_hashPosition().
Referenced by LZ4_compress_generic_validated().
LZ4_getPositionOnHash()
static const BYTE* LZ4_getPositionOnHash (U32 h, const void * tableBase, tableType_t tableType, const BYTE * srcBase) [static]
Definition at line 463 of file Compression.cpp.
{
  if (tableType == byPtr) { const BYTE *const *hashTable = (const BYTE *const *)tableBase; return hashTable[h]; }
  if (tableType == byU32) { const U32 *const hashTable = (const U32 *)tableBase; return hashTable[h] + srcBase; }
  { const U16 *const hashTable = (const U16 *)tableBase; return hashTable[h] + srcBase; } /* default, to ensure a return */
}
References byPtr, and byU32.
Referenced by LZ4_compress_generic_validated(), and LZ4_getPosition().
LZ4_hash4()
U32 LZ4_hash4 (U32 sequence, tableType_t const tableType)
Definition at line 375 of file Compression.cpp.
{
  if (tableType == byU16)
    return ((sequence * 2654435761U) >> ((MINMATCH * 8) - (LZ4_HASHLOG + 1)));
  else
    return ((sequence * 2654435761U) >> ((MINMATCH * 8) - LZ4_HASHLOG));
}
References byU16, LZ4_HASHLOG, and MINMATCH.
Referenced by LZ4_hashPosition().
LZ4_hash5()
U32 LZ4_hash5 (U64 sequence, tableType_t const tableType)
Definition at line 383 of file Compression.cpp.
{
  const U32 hashLog = (tableType == byU16) ? LZ4_HASHLOG + 1 : LZ4_HASHLOG;
  if (LZ4_isLittleEndian()) {
    const U64 prime5bytes = 889523592379ULL;
    return (U32)(((sequence << 24) * prime5bytes) >> (64 - hashLog));
  } else {
    const U64 prime8bytes = 11400714785074694791ULL;
    return (U32)(((sequence >> 24) * prime8bytes) >> (64 - hashLog));
  }
}
References byU16, LZ4_HASHLOG, and LZ4_isLittleEndian().
Referenced by LZ4_hashPosition().
LZ4_hashPosition()
U32 LZ4_hashPosition (const void *const p, tableType_t const tableType)
Definition at line 395 of file Compression.cpp.
{
  if ((sizeof(reg_t) == 8) && (tableType != byU16)) return LZ4_hash5(LZ4_read_ARCH(p), tableType);
  return LZ4_hash4(LZ4_read32(p), tableType);
}
References byU16, LZ4_hash4(), LZ4_hash5(), LZ4_read32(), and LZ4_read_ARCH().
Referenced by LZ4_compress_generic_validated(), LZ4_getPosition(), and LZ4_putPosition().
LZ4_initStream()
LZ4_stream_t* LZ4_initStream (void * buffer, size_t size)
LZ4_initStream() : v1.9.0+ An LZ4_stream_t structure must be initialized at least once. This is automatically done when invoking LZ4_createStream(), but it's not when the structure is simply declared on stack (for example).
Use LZ4_initStream() to properly initialize a newly declared LZ4_stream_t. It can also initialize any arbitrary buffer of sufficient size, and will
Returns
a pointer of proper type upon initialization.
Note : initialization fails if size and alignment conditions are not respected. In which case, the function will
Returns
NULL. Note2: An LZ4_stream_t structure guarantees correct alignment and size. Note3: Before v1.9.0, use LZ4_resetStream() instead
Definition at line 974 of file Compression.cpp.
{
  DEBUGLOG(5, "LZ4_initStream");
  if (buffer == NULL) { return NULL; }
  if (size < sizeof(LZ4_stream_t)) { return NULL; }
  if (!LZ4_isAligned(buffer, LZ4_stream_t_alignment())) return NULL;
  memset(buffer, 0, sizeof(LZ4_stream_t_internal));
  return (LZ4_stream_t *)buffer;
}
References DEBUGLOG, LZ4_isAligned(), and LZ4_stream_t_alignment().
Referenced by LZ4_compress_fast_extState().
LZ4_isAligned()
static int LZ4_isAligned (const void * ptr, size_t alignment) [static]
Definition at line 75 of file Compression.cpp.
{
  return ((size_t)ptr & (alignment - 1)) == 0;
}
Referenced by LZ4_initStream().
LZ4_isLittleEndian()
static unsigned LZ4_isLittleEndian (void) [static]
Definition at line 122 of file Compression.cpp.
{
  const union { U32 u; BYTE c[4]; } one = { 1 }; /* don't use static : performance detrimental */
  return one.c[0];
}
Referenced by LZ4_hash5(), LZ4_NbCommonBytes(), LZ4_readLE16(), and LZ4_writeLE16().
LZ4_memcpy_using_offset()
void LZ4_memcpy_using_offset (BYTE * dstPtr, const BYTE * srcPtr, BYTE * dstEnd, const size_t offset)
Definition at line 224 of file Compression.cpp.
{
  BYTE v[8];
  assert(dstEnd >= dstPtr + MINMATCH);
  switch (offset) {
  case 1:
    memset(v, *srcPtr, 8);
    break;
  case 2:
    LZ4_memcpy(v, srcPtr, 2);
    LZ4_memcpy(&v[2], srcPtr, 2);
    LZ4_memcpy(&v[4], v, 4);
    break;
  case 4:
    LZ4_memcpy(v, srcPtr, 4);
    LZ4_memcpy(&v[4], srcPtr, 4);
    break;
  default:
    LZ4_memcpy_using_offset_base(dstPtr, srcPtr, dstEnd, offset);
    return;
  }
  LZ4_memcpy(dstPtr, v, 8);
  dstPtr += 8;
  while (dstPtr < dstEnd) {
    LZ4_memcpy(dstPtr, v, 8);
    dstPtr += 8;
  }
}
References assert, LZ4_memcpy, LZ4_memcpy_using_offset_base(), and MINMATCH.
Referenced by LZ4_decompress_generic().
LZ4_memcpy_using_offset_base()
void LZ4_memcpy_using_offset_base (BYTE * dstPtr, const BYTE * srcPtr, BYTE * dstEnd, const size_t offset)
Definition at line 187 of file Compression.cpp.
{
  assert(srcPtr + offset == dstPtr);
  if (offset < 8) {
    LZ4_write32(dstPtr, 0); /* silence an msan warning when offset==0 */
    dstPtr[0] = srcPtr[0];
    dstPtr[1] = srcPtr[1];
    dstPtr[2] = srcPtr[2];
    dstPtr[3] = srcPtr[3];
    srcPtr += inc32table[offset];
    LZ4_memcpy(dstPtr + 4, srcPtr, 4);
    srcPtr -= dec64table[offset];
    dstPtr += 8;
  } else {
    LZ4_memcpy(dstPtr, srcPtr, 8);
    dstPtr += 8;
    srcPtr += 8;
  }
  LZ4_wildCopy8(dstPtr, srcPtr, dstEnd);
}
References assert, dec64table, inc32table, LZ4_memcpy, LZ4_wildCopy8(), and LZ4_write32().
Referenced by LZ4_memcpy_using_offset().
LZ4_NbCommonBytes()
static unsigned LZ4_NbCommonBytes (reg_t val) [static]
Definition at line 260 of file Compression.cpp.
{
  assert(val != 0);
  if (LZ4_isLittleEndian()) {
    if (sizeof(val) == 8) {
      /*-*************************************************************************************************
      * ARM64EC is a Microsoft-designed ARM64 ABI compatible with AMD64 applications on ARM64 Windows 11.
      * The ARM64EC ABI does not support AVX/AVX2/AVX512 instructions, nor their relevant intrinsics
      * including _tzcnt_u64. Therefore, we need to neuter the _tzcnt_u64 code path for ARM64EC.
      ****************************************************************************************************/
      const U64 m = 0x0101010101010101ULL;
      val ^= val - 1;
      return (unsigned)(((U64)((val & (m - 1)) * m)) >> 56);
    } else /* 32 bits */ {
      const U32 m = 0x01010101;
      return (unsigned)((((val - 1) ^ val) & (m - 1)) * m) >> 24;
    }
  } else /* Big Endian CPU */ {
    if (sizeof(val) == 8) {
      /* this method doesn't consume memory space like the previous one,
       * but it contains several branches,
       * that may end up slowing execution */
      static const U32 by32 = sizeof(val) * 4; /* 32 on 64 bits (goal), 16 on 32 bits.
      Just to avoid some static analyzer complaining about shift by 32 on 32-bits target.
      Note that this code path is never triggered in 32-bits mode. */
      unsigned r;
      if (!(val >> by32)) { r = 4; } else { r = 0; val >>= by32; }
      if (!(val >> 16)) { r += 2; val >>= 8; } else { val >>= 24; }
      r += (!val);
      return r;
    } else /* 32 bits */ {
      val >>= 8;
      val = ((((val + 0x00FFFF00) | 0x00FFFFFF) + val) |
        (val + 0x00FF0000)) >> 24;
      return (unsigned)val ^ 3;
    }
  }
}
References assert, and LZ4_isLittleEndian().
Referenced by LZ4_count().
LZ4_putIndexOnHash()
void LZ4_putIndexOnHash (U32 idx, U32 h, void * tableBase, tableType_t const tableType)
Definition at line 412 of file Compression.cpp.
{
  switch (tableType) {
  default: /* fallthrough */
  case clearedTable: /* fallthrough */
  case byPtr: { /* illegal! */ assert(0); return; }
  case byU32: { U32 *hashTable = (U32 *)tableBase; hashTable[h] = idx; return; }
  case byU16: { U16 *hashTable = (U16 *)tableBase; assert(idx < 65536); hashTable[h] = (U16)idx; return; }
  }
}
References assert, byPtr, byU16, byU32, and clearedTable.
Referenced by LZ4_compress_generic_validated().
LZ4_putPosition()
void LZ4_putPosition (const BYTE * p, void * tableBase, tableType_t tableType, const BYTE * srcBase)
Definition at line 435 of file Compression.cpp.
{
  U32 const h = LZ4_hashPosition(p, tableType);
  LZ4_putPositionOnHash(p, h, tableBase, tableType, srcBase);
}
References LZ4_hashPosition(), and LZ4_putPositionOnHash().
Referenced by LZ4_compress_generic_validated().
LZ4_putPositionOnHash()
void LZ4_putPositionOnHash (const BYTE * p, U32 h, void * tableBase, tableType_t const tableType, const BYTE * srcBase)
Definition at line 423 of file Compression.cpp.
{
  switch (tableType) {
  case clearedTable: { /* illegal! */ assert(0); return; }
  case byPtr: { const BYTE **hashTable = (const BYTE **)tableBase; hashTable[h] = p; return; }
  case byU32: { U32 *hashTable = (U32 *)tableBase; hashTable[h] = (U32)(p - srcBase); return; }
  case byU16: { U16 *hashTable = (U16 *)tableBase; hashTable[h] = (U16)(p - srcBase); return; }
  }
}
References assert, byPtr, byU16, byU32, and clearedTable.
Referenced by LZ4_compress_generic_validated(), and LZ4_putPosition().
LZ4_read16()
static U16 LZ4_read16 (const void * memPtr) [static]
Definition at line 128 of file Compression.cpp.
{
  U16 val; LZ4_memcpy(&val, memPtr, sizeof(val)); return val;
}
References LZ4_memcpy.
Referenced by LZ4_count(), and LZ4_readLE16().
LZ4_read32()
static U32 LZ4_read32 (const void * memPtr) [static]
Definition at line 133 of file Compression.cpp.
{
  U32 val; LZ4_memcpy(&val, memPtr, sizeof(val)); return val;
}
References LZ4_memcpy.
Referenced by LZ4_compress_generic_validated(), LZ4_count(), and LZ4_hashPosition().
LZ4_read_ARCH()
static reg_t LZ4_read_ARCH (const void * memPtr) [static]
Definition at line 138 of file Compression.cpp.
{
  reg_t val; LZ4_memcpy(&val, memPtr, sizeof(val)); return val;
}
References LZ4_memcpy.
Referenced by LZ4_count(), and LZ4_hashPosition().
LZ4_readLE16()
static U16 LZ4_readLE16 (const void * memPtr) [static]
Definition at line 153 of file Compression.cpp.
{
  if (LZ4_isLittleEndian()) {
    return LZ4_read16(memPtr);
  } else {
    const BYTE *p = (const BYTE *)memPtr;
    return (U16)((U16)p[0] + (p[1] << 8));
  }
}
References LZ4_isLittleEndian(), and LZ4_read16().
Referenced by LZ4_decompress_generic().
LZ4_stream_t_alignment()
static size_t LZ4_stream_t_alignment (void) [static]
Definition at line 964 of file Compression.cpp.
{
#if LZ4_ALIGN_TEST
  typedef struct { char c; LZ4_stream_t t; } t_a;
  return sizeof(t_a) - sizeof(LZ4_stream_t);
#else
  return 1; /* effectively disabled */
#endif
}
Referenced by LZ4_initStream().
LZ4_wildCopy32()
void LZ4_wildCopy32 (void * dstPtr, const void * srcPtr, void * dstEnd)
Definition at line 212 of file Compression.cpp.
{
  BYTE *d = (BYTE *)dstPtr;
  const BYTE *s = (const BYTE *)srcPtr;
  BYTE *const e = (BYTE *)dstEnd;
  do { LZ4_memcpy(d, s, 16); LZ4_memcpy(d + 16, s + 16, 16); d += 32; s += 32; } while (d < e);
}
References LZ4_memcpy.
Referenced by LZ4_decompress_generic().
LZ4_wildCopy8()
void LZ4_wildCopy8 (void * dstPtr, const void * srcPtr, void * dstEnd)
Definition at line 175 of file Compression.cpp.
{
  BYTE *d = (BYTE *)dstPtr;
  const BYTE *s = (const BYTE *)srcPtr;
  BYTE *const e = (BYTE *)dstEnd;
  do { LZ4_memcpy(d, s, 8); d += 8; s += 8; } while (d < e);
}
References LZ4_memcpy.
Referenced by LZ4_compress_generic_validated(), LZ4_decompress_generic(), and LZ4_memcpy_using_offset_base().
LZ4_write16()
static void LZ4_write16 (void * memPtr, U16 value) [static]
Definition at line 143 of file Compression.cpp.
{
  LZ4_memcpy(memPtr, &value, sizeof(value));
}
References LZ4_memcpy.
Referenced by LZ4_writeLE16().
LZ4_write32()
static void LZ4_write32 (void * memPtr, U32 value) [static]
Definition at line 148 of file Compression.cpp.
{
  LZ4_memcpy(memPtr, &value, sizeof(value));
}
References LZ4_memcpy.
Referenced by LZ4_compress_generic_validated(), LZ4_decompress_generic(), and LZ4_memcpy_using_offset_base().
LZ4_writeLE16()
static void LZ4_writeLE16 (void * memPtr, U16 value) [static]
Definition at line 163 of file Compression.cpp.
{
  if (LZ4_isLittleEndian()) {
    LZ4_write16(memPtr, value);
  } else {
    BYTE *p = (BYTE *)memPtr;
    p[0] = (BYTE)value;
    p[1] = (BYTE)(value >> 8);
  }
}
References LZ4_isLittleEndian(), and LZ4_write16().
Referenced by LZ4_compress_generic_validated().
read_variable_length()
unsigned read_variable_length (const BYTE ** ip, const BYTE * lencheck, int loop_check, int initial_check, variable_length_error * error)
Definition at line 1004 of file Compression.cpp.
{
  U32 length = 0;
  U32 s;
  if (initial_check && unlikely((*ip) >= lencheck)) { /* overflow detection */
    *error = initial_error;
    return length;
  }
  do {
    s = **ip;
    (*ip)++;
    length += s;
    if (loop_check && unlikely((*ip) >= lencheck)) { /* overflow detection */
      *error = loop_error;
      return length;
    }
  } while (s == 255);
  return length;
}
References initial_error, loop_error, and unlikely.
Referenced by LZ4_decompress_generic().
Variable Documentation
dec64table
const int dec64table[8] = { 0, 0, 0, -1, -4, 1, 2, 3 } [static]
Definition at line 185 of file Compression.cpp.
Referenced by LZ4_decompress_generic(), and LZ4_memcpy_using_offset_base().
inc32table
const unsigned inc32table[8] = { 0, 1, 2, 1, 0, 4, 4, 4 } [static]
Definition at line 184 of file Compression.cpp.
Referenced by LZ4_decompress_generic(), and LZ4_memcpy_using_offset_base().
LZ4_64Klimit
const int LZ4_64Klimit = ((64 KB) + (MFLIMIT - 1)) [static]
Definition at line 331 of file Compression.cpp.
Referenced by LZ4_compress_fast_extState(), and LZ4_compress_generic_validated().
LZ4_minLength
const int LZ4_minLength = (MFLIMIT + 1) [static]
Definition at line 44 of file Compression.cpp.
Referenced by LZ4_compress_generic_validated().
LZ4_skipTrigger
const U32 LZ4_skipTrigger = 6 [static]
Definition at line 332 of file Compression.cpp.
Referenced by LZ4_compress_generic_validated().