VortexEngine/src/Serial/Compression.h File Reference
#include `../VortexConfig.h`
#include <inttypes.h>
#include <stddef.h>
#include <stdint.h>
Classes
struct LZ4_stream_t_internal
struct LZ4_streamDecode_t_internal
union LZ4_stream_u
union LZ4_streamDecode_u
Macros
#define compress_size(srcSize) LZ4_compressBound(srcSize)
#define compress_buffer(src, dst, srcSize, dstCapacity) LZ4_compress_default((const char *)src, (char *)dst, srcSize, dstCapacity)
#define decompress_buffer(src, dst, srcSize, dstCapacity) LZ4_decompress_safe((const char *)src, (char *)dst, srcSize, dstCapacity)
#define LZ4_MEMORY_USAGE_MIN 10
#define LZ4_MEMORY_USAGE_DEFAULT 10
#define LZ4_MEMORY_USAGE_MAX 20
#define LZ4_MEMORY_USAGE LZ4_MEMORY_USAGE_DEFAULT
#define LZ4_MAX_INPUT_SIZE 0x7E000000 /* 2 113 929 216 bytes */
#define LZ4_COMPRESSBOUND(isize) ((unsigned)(isize) > (unsigned)LZ4_MAX_INPUT_SIZE ? 0 : (isize) + ((isize)/255) + 16)
#define LZ4_DECODER_RING_BUFFER_SIZE(maxBlockSize) (65536 + 14 + (maxBlockSize)) /* for static allocation; maxBlockSize presumed valid */
#define LZ4_DECOMPRESS_INPLACE_MARGIN(compressedSize) (((compressedSize) >> 8) + 32)
#define LZ4_DECOMPRESS_INPLACE_BUFFER_SIZE(decompressedSize) ((decompressedSize) + LZ4_DECOMPRESS_INPLACE_MARGIN(decompressedSize))
#define LZ4_DISTANCE_MAX 65535 /* set to maximum value by default */
#define LZ4_COMPRESS_INPLACE_MARGIN (LZ4_DISTANCE_MAX + 32) /* LZ4_DISTANCE_MAX can be safely replaced by srcSize when it's smaller */
#define LZ4_COMPRESS_INPLACE_BUFFER_SIZE(maxCompressedSize) ((maxCompressedSize) + LZ4_COMPRESS_INPLACE_MARGIN)
#define LZ4_HASHLOG (LZ4_MEMORY_USAGE-2)
#define LZ4_HASHTABLESIZE (1 << LZ4_MEMORY_USAGE)
#define LZ4_HASH_SIZE_U32 (1 << LZ4_HASHLOG) /* required as macro for static allocation */
#define LZ4_STREAMSIZE ((1UL << LZ4_MEMORY_USAGE) + 32) /* static size, for inter-version compatibility */
#define LZ4_STREAMSIZE_VOIDP (LZ4_STREAMSIZE / sizeof(void*))
#define LZ4_STREAMDECODESIZE_U64 (4 + ((sizeof(void*)==16) ? 2 : 0) /*AS-400*/)
#define LZ4_STREAMDECODESIZE (LZ4_STREAMDECODESIZE_U64 * sizeof(unsigned long long))
Typedefs
typedef union LZ4_stream_u LZ4_stream_t
typedef union LZ4_streamDecode_u LZ4_streamDecode_t
typedef int8_t LZ4_i8
typedef uint8_t LZ4_byte
typedef uint16_t LZ4_u16
typedef uint32_t LZ4_u32
typedef struct LZ4_stream_t_internal LZ4_stream_t_internal
Functions
int LZ4_compress_default (const char *src, char *dst, int srcSize, int dstCapacity)
int LZ4_decompress_safe (const char *src, char *dst, int compressedSize, int dstCapacity)
int LZ4_compressBound (int inputSize)
int LZ4_compress_fast (const char *src, char *dst, int srcSize, int dstCapacity, int acceleration)
int LZ4_compress_fast_extState (void *state, const char *src, char *dst, int srcSize, int dstCapacity, int acceleration)
LZ4_stream_t * LZ4_initStream (void *buffer, size_t size)
Macro Definition Documentation
compress_buffer
#define compress_buffer(src, dst, srcSize, dstCapacity) LZ4_compress_default((const char *)src, (char *)dst, srcSize, dstCapacity)
Definition at line 21 of file Compression.h.
compress_size
#define compress_size(srcSize) LZ4_compressBound(srcSize)
Definition at line 20 of file Compression.h.
decompress_buffer
#define decompress_buffer(src, dst, srcSize, dstCapacity) LZ4_decompress_safe((const char *)src, (char *)dst, srcSize, dstCapacity)
Definition at line 22 of file Compression.h.
LZ4_COMPRESS_INPLACE_BUFFER_SIZE
#define LZ4_COMPRESS_INPLACE_BUFFER_SIZE(maxCompressedSize) ((maxCompressedSize) + LZ4_COMPRESS_INPLACE_MARGIN)
maxCompressedSize is generally LZ4_COMPRESSBOUND(inputSize), but can be set to any lower value, with the risk that compression can fail (return code 0(zero))
Definition at line 129 of file Compression.h.
LZ4_COMPRESS_INPLACE_MARGIN
#define LZ4_COMPRESS_INPLACE_MARGIN (LZ4_DISTANCE_MAX + 32) /* LZ4_DISTANCE_MAX can be safely replaced by srcSize when it's smaller */
Definition at line 128 of file Compression.h.
LZ4_COMPRESSBOUND
#define LZ4_COMPRESSBOUND(isize) ((unsigned)(isize) > (unsigned)LZ4_MAX_INPUT_SIZE ? 0 : (isize) + ((isize)/255) + 16)
Definition at line 77 of file Compression.h.
LZ4_DECODER_RING_BUFFER_SIZE
#define LZ4_DECODER_RING_BUFFER_SIZE(maxBlockSize) (65536 + 14 + (maxBlockSize)) /* for static allocation; maxBlockSize presumed valid */
Definition at line 119 of file Compression.h.
LZ4_DECOMPRESS_INPLACE_BUFFER_SIZE
#define LZ4_DECOMPRESS_INPLACE_BUFFER_SIZE(decompressedSize) ((decompressedSize) + LZ4_DECOMPRESS_INPLACE_MARGIN(decompressedSize))
note: presumes that compressedSize < decompressedSize. note2: margin is overestimated a bit, since it could use compressedSize instead
Definition at line 122 of file Compression.h.
LZ4_DECOMPRESS_INPLACE_MARGIN
#define LZ4_DECOMPRESS_INPLACE_MARGIN(compressedSize) (((compressedSize) >> 8) + 32)
Definition at line 121 of file Compression.h.
LZ4_DISTANCE_MAX
#define LZ4_DISTANCE_MAX 65535 /* set to maximum value by default */
Definition at line 125 of file Compression.h.
LZ4_HASH_SIZE_U32
#define LZ4_HASH_SIZE_U32 (1 << LZ4_HASHLOG) /* required as macro for static allocation */
Definition at line 140 of file Compression.h.
LZ4_HASHLOG
#define LZ4_HASHLOG (LZ4_MEMORY_USAGE-2)
Definition at line 138 of file Compression.h.
LZ4_HASHTABLESIZE
#define LZ4_HASHTABLESIZE (1 << LZ4_MEMORY_USAGE)
Definition at line 139 of file Compression.h.
LZ4_MAX_INPUT_SIZE
#define LZ4_MAX_INPUT_SIZE 0x7E000000 /* 2 113 929 216 bytes */
Definition at line 76 of file Compression.h.
LZ4_MEMORY_USAGE
#define LZ4_MEMORY_USAGE LZ4_MEMORY_USAGE_DEFAULT
Definition at line 30 of file Compression.h.
LZ4_MEMORY_USAGE_DEFAULT
#define LZ4_MEMORY_USAGE_DEFAULT 10
Definition at line 26 of file Compression.h.
LZ4_MEMORY_USAGE_MAX
#define LZ4_MEMORY_USAGE_MAX 20
Definition at line 27 of file Compression.h.
LZ4_MEMORY_USAGE_MIN
#define LZ4_MEMORY_USAGE_MIN 10
Definition at line 25 of file Compression.h.
LZ4_STREAMDECODESIZE
#define LZ4_STREAMDECODESIZE (LZ4_STREAMDECODESIZE_U64 * sizeof(unsigned long long))
Definition at line 211 of file Compression.h.
LZ4_STREAMDECODESIZE_U64
#define LZ4_STREAMDECODESIZE_U64 (4 + ((sizeof(void*)==16) ? 2 : 0) /*AS-400*/)
LZ4_streamDecode_t : information structure to track an LZ4 stream during decompression. init this structure using LZ4_setStreamDecode() before first use. note : only use in association with static linking ! this definition is not API/ABI safe, and may change in a future version !
Definition at line 210 of file Compression.h.
LZ4_STREAMSIZE
#define LZ4_STREAMSIZE ((1UL << LZ4_MEMORY_USAGE) + 32) /* static size, for inter-version compatibility */
LZ4_stream_t : Do not use below internal definitions directly ! Declare or allocate an LZ4_stream_t instead. LZ4_stream_t can also be created using LZ4_createStream(), which is recommended. The structure definition can be convenient for static allocation (on stack, or as part of larger structure). Init this structure with LZ4_initStream() before first use. note : only use this definition in association with static linking ! this definition is not API/ABI safe, and may change in future versions.
Definition at line 178 of file Compression.h.
LZ4_STREAMSIZE_VOIDP
#define LZ4_STREAMSIZE_VOIDP (LZ4_STREAMSIZE / sizeof(void*))
Definition at line 179 of file Compression.h.
Typedef Documentation
LZ4_byte
typedef uint8_t LZ4_byte
Definition at line 144 of file Compression.h.
LZ4_i8
typedef int8_t LZ4_i8
Definition at line 143 of file Compression.h.
LZ4_stream_t
typedef union LZ4_stream_u LZ4_stream_t
Definition at line 111 of file Compression.h.
LZ4_stream_t_internal
typedef struct LZ4_stream_t_internal LZ4_stream_t_internal
Definition at line 148 of file Compression.h.
LZ4_streamDecode_t
typedef union LZ4_streamDecode_u LZ4_streamDecode_t
Definition at line 117 of file Compression.h.
LZ4_u16
typedef uint16_t LZ4_u16
Definition at line 145 of file Compression.h.
LZ4_u32
typedef uint32_t LZ4_u32
Definition at line 146 of file Compression.h.
Function Documentation
LZ4_compress_default()
int LZ4_compress_default (const char * src, char * dst, int srcSize, int dstCapacity)
LZ4_compress_default() : Compresses 'srcSize' bytes from buffer 'src' into already allocated 'dst' buffer of size 'dstCapacity'. Compression is guaranteed to succeed if 'dstCapacity' >= LZ4_compressBound(srcSize). It also runs faster, so it's a recommended setting. If the function cannot compress 'src' into a more limited 'dst' budget, compression stops immediately, and the function result is zero. In which case, 'dst' content is undefined (invalid). srcSize : max supported value is LZ4_MAX_INPUT_SIZE. dstCapacity : size of buffer 'dst' (which must be already allocated)
Returns
: the number of bytes written into buffer 'dst' (necessarily <= dstCapacity) or 0 if compression fails Note : This function is protected against buffer overflow scenarios (never writes outside 'dst' buffer, nor read outside 'source' buffer).
Definition at line 955 of file Compression.cpp.
{
  return LZ4_compress_fast(src, dst, srcSize, maxOutputSize, 1);
}
References LZ4_compress_fast().
LZ4_compress_fast()
int LZ4_compress_fast (const char * src, char * dst, int srcSize, int dstCapacity, int acceleration)
LZ4_compress_fast() : Same as LZ4_compress_default(), but allows selection of `acceleration` factor. The larger the acceleration value, the faster the algorithm, but also the lesser the compression. It's a trade-off. It can be fine tuned, with each successive value providing roughly +~3% to speed. An acceleration value of `1` is the same as regular LZ4_compress_default() Values <= 0 will be replaced by LZ4_ACCELERATION_DEFAULT (currently == 1, see lz4.c). Values > LZ4_ACCELERATION_MAX will be replaced by LZ4_ACCELERATION_MAX (currently == 65537, see lz4.c).
Definition at line 945 of file Compression.cpp.
{
  int result;
  LZ4_stream_t *ctxPtr = (LZ4_stream_t *)vmalloc(sizeof(LZ4_stream_t)); /* malloc-calloc always properly aligned */
  if (ctxPtr == NULL) return 0;
  result = LZ4_compress_fast_extState(ctxPtr, source, dest, inputSize, maxOutputSize, acceleration);
  vfree(ctxPtr);
  return result;
}
References LZ4_compress_fast_extState(), vfree, and vmalloc.
Referenced by LZ4_compress_default().
LZ4_compress_fast_extState()
int LZ4_compress_fast_extState (void * state, const char * src, char * dst, int srcSize, int dstCapacity, int acceleration)
LZ4_compress_fast_extState() : Same as LZ4_compress_fast(), using an externally allocated memory space for its state. Use LZ4_sizeofState() to know how much memory must be allocated, and allocate it on 8-bytes boundaries (using malloc() typically). Then, provide this buffer as void* state to compression function.
Definition at line 922 of file Compression.cpp.
{
  LZ4_stream_t_internal *const ctx = &LZ4_initStream(state, sizeof(LZ4_stream_t))->internal_donotuse;
  assert(ctx != NULL);
  if (acceleration < 1) acceleration = 1;
  if (acceleration > 65537) acceleration = 65537;
  if (maxOutputSize >= LZ4_compressBound(inputSize)) {
    if (inputSize < LZ4_64Klimit) {
      return LZ4_compress_generic(ctx, source, dest, inputSize, NULL, 0, notLimited, byU16, noDict, noDictIssue, acceleration);
    } else {
      const tableType_t tableType = ((sizeof(void *) == 4) && ((uptrval)source > LZ4_DISTANCE_MAX)) ? byPtr : byU32;
      return LZ4_compress_generic(ctx, source, dest, inputSize, NULL, 0, notLimited, tableType, noDict, noDictIssue, acceleration);
    }
  } else {
    if (inputSize < LZ4_64Klimit) {
      return LZ4_compress_generic(ctx, source, dest, inputSize, NULL, maxOutputSize, limitedOutput, byU16, noDict, noDictIssue, acceleration);
    } else {
      const tableType_t tableType = ((sizeof(void *) == 4) && ((uptrval)source > LZ4_DISTANCE_MAX)) ? byPtr : byU32;
      return LZ4_compress_generic(ctx, source, dest, inputSize, NULL, maxOutputSize, limitedOutput, tableType, noDict, noDictIssue, acceleration);
    }
  }
}
References assert, byPtr, byU16, byU32, LZ4_stream_u::internal_donotuse, limitedOutput, LZ4_64Klimit, LZ4_compress_generic(), LZ4_compressBound(), LZ4_DISTANCE_MAX, LZ4_initStream(), noDict, noDictIssue, and notLimited.
Referenced by LZ4_compress_fast().
LZ4_compressBound()
int LZ4_compressBound (int inputSize)
LZ4_compressBound() : Provides the maximum size that LZ4 compression may output in a `worst case` scenario (input data not compressible) This function is primarily useful for memory allocation purposes (destination buffer size). Macro LZ4_COMPRESSBOUND() is also provided for compilation-time evaluation (stack memory allocation for example). Note that LZ4_compress_default() compresses faster when dstCapacity is >= LZ4_compressBound(srcSize) inputSize : max supported value is LZ4_MAX_INPUT_SIZE return : maximum output size in a `worst case` scenario or 0, if input size is incorrect (too large or negative)
Definition at line 370 of file Compression.cpp.
{ return LZ4_COMPRESSBOUND(isize); }
References LZ4_COMPRESSBOUND.
Referenced by LZ4_compress_fast_extState().
LZ4_decompress_safe()
int LZ4_decompress_safe (const char * src, char * dst, int compressedSize, int dstCapacity)
LZ4_decompress_safe() : compressedSize : is the exact complete size of the compressed block. dstCapacity : is the size of destination buffer (which must be already allocated), presumed an upper bound of decompressed size.
Returns
: the number of bytes decompressed into destination buffer (necessarily <= dstCapacity) If destination buffer is not large enough, decoding will stop and output an error code (negative value). If the source stream is detected malformed, the function will stop decoding and return a negative result. Note 1 : This function is protected against malicious data packets : it will never writes outside 'dst' buffer, nor read outside 'source' buffer, even if the compressed block is maliciously modified to order the decoder to do these actions. In such case, the decoder stops immediately, and considers the compressed block malformed. Note 2 : compressedSize and dstCapacity must be provided to the function, the compressed block does not contain them. The implementation is free to send / store / derive this information in whichever way is most beneficial. If there is a need for a different format which bundles together both compressed data and its metadata, consider looking at lz4frame.h instead.
Definition at line 1461 of file Compression.cpp.
{
  return LZ4_decompress_generic(source, dest, compressedSize, maxDecompressedSize,
    endOnInputSize, decode_full_block, noDict,
    (BYTE *)dest, NULL, 0);
}
References decode_full_block, endOnInputSize, LZ4_decompress_generic(), and noDict.
LZ4_initStream()
LZ4_stream_t* LZ4_initStream (void * buffer, size_t size)
LZ4_initStream() : v1.9.0+ An LZ4_stream_t structure must be initialized at least once. This is automatically done when invoking LZ4_createStream(), but it's not when the structure is simply declared on stack (for example).
Use LZ4_initStream() to properly initialize a newly declared LZ4_stream_t. It can also initialize any arbitrary buffer of sufficient size, and will
Returns
a pointer of proper type upon initialization.
Note : initialization fails if size and alignment conditions are not respected. In which case, the function will
Returns
NULL. Note2: An LZ4_stream_t structure guarantees correct alignment and size. Note3: Before v1.9.0, use LZ4_resetStream() instead
Definition at line 974 of file Compression.cpp.
{
  DEBUGLOG(5, "LZ4_initStream");
  if (buffer == NULL) { return NULL; }
  if (size < sizeof(LZ4_stream_t)) { return NULL; }
  if (!LZ4_isAligned(buffer, LZ4_stream_t_alignment())) return NULL;
  memset(buffer, 0, sizeof(LZ4_stream_t_internal));
  return (LZ4_stream_t *)buffer;
}
References DEBUGLOG, LZ4_isAligned(), and LZ4_stream_t_alignment().
Referenced by LZ4_compress_fast_extState().