MeteorPattern Class Reference
#include <MeteorPattern.h>
Public Member Functions
MeteorPattern (VortexEngine &engine, const PatternArgs &args)
virtual ~MeteorPattern ()
Protected Member Functions
virtual void blinkOn () override
virtual void blinkOff () override
virtual void poststep () override
Private Attributes
uint8_t m_fadeAmount
Random m_randCtx
LedStash m_stash
Additional Inherited Members
Detailed Description
Definition at line 10 of file MeteorPattern.h.
Constructor & Destructor Documentation
MeteorPattern()
MeteorPattern::MeteorPattern (VortexEngine & engine, const PatternArgs & args)
Definition at line 9 of file MeteorPattern.cpp.
                                                                          :
  BlinkStepPattern(engine, args),
  m_fadeAmount(0),
  m_randCtx(),
  m_stash(engine)
{
  m_patternID = PATTERN_METEOR;
  REGISTER_ARG(m_fadeAmount);
  setArgs(args);
}
References m_fadeAmount, Pattern::m_patternID, PATTERN_METEOR, REGISTER_ARG, and Pattern::setArgs().
 MeteorPattern()
MeteorPattern::~MeteorPattern () [virtual]
Definition at line 20 of file MeteorPattern.cpp.
{
}
Member Function Documentation
blinkOff()
void MeteorPattern::blinkOff () [override], [protected], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 32 of file MeteorPattern.cpp.
{
  m_engine.leds().clearAll();
}
References Leds::clearAll(), VortexEngine::leds(), and Pattern::m_engine.
blinkOn()
void MeteorPattern::blinkOn () [override], [protected], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 24 of file MeteorPattern.cpp.
{
  for (int i = 0; i < LED_COUNT; ++i) {
    m_stash[i].adjustBrightness(m_fadeAmount);
  }
  m_engine.leds().restoreAll(m_stash);
}
References LED_COUNT, VortexEngine::leds(), Pattern::m_engine, m_fadeAmount, m_stash, and Leds::restoreAll().
poststep()
void MeteorPattern::poststep () [override], [protected], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 37 of file MeteorPattern.cpp.
{
  for (uint8_t meteorCount = 0; meteorCount < (LED_COUNT / 2); ++meteorCount) {
    // when a new meteor is created it is incerted into the stash so the blinking pattern is not interrupted
    LedPos target = (LedPos)m_randCtx.next8(LED_FIRST, LED_LAST);
    RGBColor col = m_colorset.getNext();
    m_stash.setIndex(target, col);
  }
}
References Colorset::getNext(), LED_COUNT, LED_FIRST, LED_LAST, Pattern::m_colorset, m_randCtx, m_stash, Random::next8(), and LedStash::setIndex().
Member Data Documentation
m_fadeAmount
uint8_t MeteorPattern::m_fadeAmount [private]
Definition at line 23 of file MeteorPattern.h.
Referenced by blinkOn(), and MeteorPattern().
m_randCtx
Random MeteorPattern::m_randCtx [private]
Definition at line 26 of file MeteorPattern.h.
Referenced by poststep().
m_stash
LedStash MeteorPattern::m_stash [private]
Definition at line 28 of file MeteorPattern.h.
Referenced by blinkOn(), and poststep().
The documentation for this class was generated from the following files:
VortexEngine/src/Patterns/Multi/MeteorPattern.h
VortexEngine/src/Patterns/Multi/MeteorPattern.cpp