Vortex Class Reference
#include <VortexLib.h>
Classes
class VortexButtonEvent
Public Member Functions
Vortex ()
~Vortex ()
void init ()
template<typename T >
T * initEx ()
void cleanup ()
bool tick ()
void installCallbacks (VortexCallbacks *callbacks)
void setInstantTimestep (bool timestep)
void selectButton (uint8_t buttonIndex)
void shortClick (uint8_t buttonIndex=0)
void longClick (uint8_t buttonIndex=0)
void menuEnterClick (uint8_t buttonIndex=0)
void advMenuEnterClick (uint8_t buttonIndex=0)
void deleteColClick (uint8_t buttonIndex=0)
void sleepClick (uint8_t buttonIndex=0)
void forceSleepClick (uint8_t buttonIndex=0)
void pressButton (uint8_t buttonIndex=0)
void releaseButton (uint8_t buttonIndex=0)
bool isButtonPressed (uint8_t buttonIndex=0)
void sendWait (uint32_t amount=0)
void rapidClick (uint32_t amount=3)
Mode * getMenuDemoMode ()
bool setMenuDemoMode (const Mode *mode)
void quitClick ()
void IRDeliver (uint32_t timing)
void VLDeliver (uint32_t timing)
void getStorageStats (uint32_t *outTotal, uint32_t *outUsed)
void loadStorage ()
void openRandomizer (bool advanced=false)
void openColorSelect (bool advanced=false)
void openPatternSelect (bool advanced=false)
void openGlobalBrightness (bool advanced=false)
void openFactoryReset (bool advanced=false)
void openModeSharing (bool advanced=false)
void openEditorConnection (bool advanced=false)
void clearMenuTargetLeds ()
void setMenuTargetLeds (LedMap targetLeds)
void addMenuTargetLeds (LedPos pos)
bool getModes (ByteStream &outStream)
bool setModes (ByteStream &stream, bool save=true)
bool getCurMode (ByteStream &stream)
bool matchLedCount (ByteStream &stream, bool vtxMode)
bool checkLedCount ()
uint8_t setLedCount (uint8_t ledCount)
uint8_t getLedCount ()
uint32_t curModeIndex ()
uint32_t numModes ()
uint32_t numLedsInMode ()
bool addMode (const Mode *mode, bool save=true)
bool addNewMode (bool save=true)
bool addNewMode (ByteStream &stream, bool save=true)
bool setCurMode (uint32_t index, bool save=true)
bool nextMode (bool save=true)
bool delCurMode (bool save=true)
bool shiftCurMode (int8_t offset, bool save=true)
bool setPattern (PatternID id, const PatternArgs *args=nullptr, const Colorset *set=nullptr, bool save=true)
PatternID getPatternID (LedPos pos)
std::string getPatternName (LedPos pos)
std::string getModeName ()
bool setPatternAt (LedPos pos, PatternID id, const PatternArgs *args=nullptr, const Colorset *set=nullptr, bool save=true)
bool getColorset (LedPos pos, Colorset &set)
bool setColorset (LedPos pos, const Colorset &set, bool save=true)
bool getPatternArgs (LedPos pos, PatternArgs &args)
bool setPatternArgs (LedPos pos, PatternArgs &args, bool save=true)
bool isCurModeMulti ()
std::string patternToString (PatternID id=PATTERN_NONE)
PatternID stringToPattern (const std::string &pattern)
std::string ledToString (LedPos pos)
uint32_t numCustomParams (PatternID id)
std::vector< std::string > getCustomParams (PatternID id)
void setUndoBufferLimit (uint32_t limit)
bool addUndoBuffer ()
bool undo ()
bool redo ()
void setTickrate (uint32_t tickrate)
uint32_t getTickrate ()
void enableUndo (bool enabled)
VortexCallbacks * vcallbacks ()
void printlog (const char *file, const char *func, int line, const char *msg, va_list list)
void doCommand (char c)
void setSleepEnabled (bool enable)
bool sleepEnabled ()
void enterSleep (bool save)
bool isSleeping ()
void enableCommandLog (bool enable)
const std::string & getCommandLog ()
void clearCommandLog ()
bool enableLockstep (bool enable)
bool isLockstep ()
bool enableStorage (bool enable)
bool storageEnabled ()
void setStorageFilename (const std::string &name)
std::string getStorageFilename ()
void setLockEnabled (bool enable)
bool lockEnabled ()
json modeToJson (const Mode *mode)
Mode * modeFromJson (const json &modeJson)
json patternToJson (const Pattern *pattern)
Pattern * patternFromJson (const json &patternJson)
json saveModeToJson ()
bool loadModeFromJson (const json &modeJson)
json saveToJson ()
bool loadFromJson (const json &json)
std::string printModeJson (bool pretty=false)
bool parseModeJson (const std::string &json)
std::string printPatternJson (LedPos pos, bool pretty=false)
bool parsePatternJson (LedPos pos, const std::string &json)
std::string printJson (bool pretty=false)
bool parseJson (const std::string &json)
bool printJsonToFile (const std::string &filename, bool pretty=false)
bool parseJsonFromFile (const std::string &filename)
bool doSave ()
bool applyUndo ()
VortexEngine & engine ()
Private Types
enum VortexButtonEventType {
EVENT_NONE
, EVENT_SHORT_CLICK
, EVENT_LONG_CLICK
, EVENT_MENU_ENTER_CLICK
,
EVENT_ADV_MENU_ENTER_CLICK
, EVENT_DELETE_COL
, EVENT_SLEEP_CLICK
, EVENT_FORCE_SLEEP_CLICK
,
EVENT_WAIT
, EVENT_TOGGLE_CLICK
, EVENT_RAPID_CLICK
, EVENT_QUIT_CLICK
,
EVENT_RESET_CLICK
 }
Private Member Functions
bool init (VortexCallbacks *callbacks)
void handleNumber (char c)
void handleInputQueue (Button *buttons, uint32_t numButtons)
uint32_t getNumInputs ()
Private Attributes
VortexEngine m_engine
std::deque< ByteStream > m_undoBuffer
uint32_t m_undoLimit
uint32_t m_undoIndex
bool m_undoEnabled
VortexCallbacks * m_storedCallbacks
FILE * m_consoleHandle
std::deque< VortexButtonEvent > m_buttonEventQueue
bool m_initialized
uint32_t m_buttonsPressed
uint8_t m_selectedButton
std::string m_commandLog
bool m_commandLogEnabled
bool m_lockstepEnabled
bool m_storageEnabled
bool m_sleepEnabled
bool m_lockEnabled
char m_lastCommand
Random m_randCtx
Friends
class Buttons
Detailed Description
Definition at line 85 of file VortexLib.h.
Member Enumeration Documentation
VortexButtonEventType
enum Vortex::VortexButtonEventType [private]
Enumerator
EVENT_NONE
EVENT_SHORT_CLICK
EVENT_LONG_CLICK
EVENT_MENU_ENTER_CLICK
EVENT_ADV_MENU_ENTER_CLICK
EVENT_DELETE_COL
EVENT_SLEEP_CLICK
EVENT_FORCE_SLEEP_CLICK
EVENT_WAIT
EVENT_TOGGLE_CLICK
EVENT_RAPID_CLICK
EVENT_QUIT_CLICK
EVENT_RESET_CLICK
Definition at line 337 of file VortexLib.h.
  {
    // no event
    EVENT_NONE,
    // a short click
    EVENT_SHORT_CLICK,
    // a long click
    EVENT_LONG_CLICK,
    // a press that is just long enough to open the ring menu
    EVENT_MENU_ENTER_CLICK,
    // a press that is just long enough to enter adv menus
    EVENT_ADV_MENU_ENTER_CLICK,
    // a press that is long enough to delete a color from col select
    EVENT_DELETE_COL,
    // a press just long enough to put the device to sleep from main modes
    EVENT_SLEEP_CLICK,
    // a press very long so that the chip triggers it's force sleep
    EVENT_FORCE_SLEEP_CLICK,
    // just wait around a tick (mainly used for testing)
    EVENT_WAIT,
    // toggle the button (press or unpress it)
    EVENT_TOGGLE_CLICK,
    // rapid click the button x times
    EVENT_RAPID_CLICK,
    // quit the engine (not really a 'click')
    EVENT_QUIT_CLICK,
    // this is an automated event that will reset the button click
    // after the ring menu hold-to-enter sequence
    EVENT_RESET_CLICK,
  };
Constructor & Destructor Documentation
Vortex()
Vortex::Vortex ()
Definition at line 652 of file VortexLib.cpp.
               :
  m_engine(*this),
  m_undoBuffer(),
  m_undoLimit(0),
  m_undoIndex(0),
  m_undoEnabled(true),
  m_storedCallbacks(nullptr),
  m_consoleHandle(nullptr),
#if LOG_TO_FILE == 1
  m_logHandle(nullptr),
#endif
#ifdef WASM
  // pointer to the led array and led count in the engine
  m_leds(nullptr),
  m_led_count(0),
#endif
  m_buttonEventQueue(),
  m_initialized(false),
  m_buttonsPressed(0),
  m_selectedButton(0),
  m_commandLog(),
  m_commandLogEnabled(false),
  m_lockstepEnabled(false),
  m_storageEnabled(false),
  m_sleepEnabled(true),
  m_lockEnabled(true),
  m_lastCommand(0),
  m_randCtx(0)
{
  // default callbacks pointer that can be replaced with a derivative
  // of the VortexCallbacks class
  m_storedCallbacks = new VortexCallbacks(*this);
  if (!m_storedCallbacks) {
    // error! out of memory
  }
#ifdef _WIN32
  m_randCtx.seed((uint32_t)(time(NULL) ^ GetTickCount64()));
#else
  struct timespec ts;
  unsigned long theTick = 0U;
  clock_gettime(CLOCK_MONOTONIC, &ts);
  theTick = ts.tv_nsec / 1000000;
  theTick += ts.tv_sec * 1000;
  m_randCtx.seed(time(NULL) ^ theTick);
#endif
}
References m_randCtx, m_storedCallbacks, and Random::seed().
 Vortex()
Vortex::~Vortex ()
Definition at line 699 of file VortexLib.cpp.
{
  cleanup();
}
References cleanup().
Member Function Documentation
addMenuTargetLeds()
void Vortex::addMenuTargetLeds (LedPos pos)
Definition at line 1182 of file VortexLib.cpp.
{
  Menu *cur = m_engine.menus().curMenu();
  if (!cur) {
    return;
  }
  LedMap curMap = cur->getTargetLeds();
  cur->setTargetLeds((LedMap)(curMap | MAP_LED(pos)));
}
References Menus::curMenu(), Menu::getTargetLeds(), m_engine, MAP_LED, VortexEngine::menus(), and Menu::setTargetLeds().
addMode()
bool Vortex::addMode (const Mode * mode, bool save = true)
Definition at line 1302 of file VortexLib.cpp.
{
  if (!m_engine.modes().addMode(mode)) {
    return false;
  }
  return !save || doSave();
}
References Modes::addMode(), doSave(), m_engine, and VortexEngine::modes().
addNewMode() [1/2]
bool Vortex::addNewMode (bool save = true)
Definition at line 1310 of file VortexLib.cpp.
{
  Colorset set;
  set.randomize(m_randCtx);
  // create a random pattern ID from all patterns
  PatternID randomPattern;
  do {
    // continuously re-randomize the pattern so we don't get solids
    randomPattern = (PatternID)m_randCtx.next16(PATTERN_FIRST, PATTERN_SINGLE_LAST);
  } while (randomPattern == PATTERN_SOLID);
  if (!m_engine.modes().addMode(randomPattern, nullptr, &set)) {
    return false;
  }
  return !save || doSave();
}
References Modes::addMode(), doSave(), m_engine, m_randCtx, VortexEngine::modes(), Random::next16(), PATTERN_FIRST, PATTERN_SINGLE_LAST, PATTERN_SOLID, and Colorset::randomize().
Referenced by VortexCLI::init().
addNewMode() [2/2]
bool Vortex::addNewMode (ByteStream & stream, bool save = true)
Definition at line 1326 of file VortexLib.cpp.
{
  if (!m_engine.modes().addModeFromBuffer(stream)) {
    return false;
  }
  return !save || doSave();
}
References Modes::addModeFromBuffer(), doSave(), m_engine, and VortexEngine::modes().
addUndoBuffer()
bool Vortex::addUndoBuffer ()
Definition at line 1610 of file VortexLib.cpp.
{
  if (!m_undoEnabled) {
    return true;
  }
  ByteStream modes;
  getModes(modes);
  if (!modes.size()) {
    return false;
  }
  // only save an undo if the buffer is different
  if (m_undoBuffer.size() > 0 && modes.CRC() == m_undoBuffer.back().CRC()) {
    //printf("Not saving duplicate undo buffer\n");
    return false;
  }
  // must rewind to that step before pushing next step
  while (m_undoIndex > 0) {
    m_undoBuffer.pop_back();
    m_undoIndex--;
  }
  m_undoBuffer.push_back(modes);
  //printf("Pushing undo buffer (pos: %u)\n", m_undoIndex);
  // make sure list doesn't grow too big
  if (m_undoLimit && m_undoBuffer.size() > m_undoLimit) {
    //printf("Popping front of undo buffer\n");
    m_undoBuffer.pop_front();
  }
#if 0
  printf("Buffer:\n");
  for (uint32_t i = 0; i < m_undoBuffer.size(); ++i) {
    printf("\t%u: %x", i, m_undoBuffer[i].CRC());
    if ((m_undoBuffer.size() - 1) - m_undoIndex == i) {
      printf(" <--\n");
    } else {
      printf("\n");
    }
  }
#endif
  return true;
}
References ByteStream::CRC(), getModes(), m_undoBuffer, m_undoEnabled, m_undoIndex, m_undoLimit, and ByteStream::size().
Referenced by doSave().
advMenuEnterClick()
void Vortex::advMenuEnterClick (uint8_t buttonIndex = 0)
Definition at line 999 of file VortexLib.cpp.
{
  if (!buttonIndex) {
    buttonIndex = m_selectedButton;
  }
  m_buttonEventQueue.push_back(VortexButtonEvent(buttonIndex, EVENT_ADV_MENU_ENTER_CLICK));
}
References EVENT_ADV_MENU_ENTER_CLICK, m_buttonEventQueue, and m_selectedButton.
Referenced by doCommand().
applyUndo()
bool Vortex::applyUndo ()
Definition at line 1651 of file VortexLib.cpp.
{
  if (!m_undoBuffer.size()) {
    return false;
  }
  uint32_t highestIndex = (uint32_t)m_undoBuffer.size() - 1;
  if (m_undoIndex > highestIndex) {
    m_undoIndex = highestIndex;
  }
  //printf("Undo position: %u / %u\n", m_undoIndex, highestIndex);
  //printf("Buffer:\n");
#if 0
  for (uint32_t i = 0; i < m_undoBuffer.size(); ++i) {
    printf("\t%u: %x", i, m_undoBuffer[i].CRC());
    if ((m_undoBuffer.size() - 1) - m_undoIndex == i) {
      printf(" <--\n");
    } else {
      printf("\n");
    }
  }
#endif
  // index from the back instead of the front
  uint32_t backIndex = highestIndex - m_undoIndex;
  m_undoBuffer[backIndex].resetUnserializer();
  Vortex::setModes(m_undoBuffer[backIndex], false);
  return true;
}
References m_undoBuffer, m_undoIndex, and setModes().
Referenced by redo(), and undo().
checkLedCount()
bool Vortex::checkLedCount ()
Definition at line 1237 of file VortexLib.cpp.
{
  Mode *mode = m_engine.modes().curMode();
  if (!mode) {
    return false;
  }
  uint8_t numLeds = mode->getLedCount();
  if (numLeds != LED_COUNT) {
    m_engine.leds().setLedCount(numLeds);
  }
  return true;
}
References Modes::curMode(), Mode::getLedCount(), LED_COUNT, VortexEngine::leds(), m_engine, VortexEngine::modes(), and Leds::setLedCount().
cleanup()
void Vortex::cleanup ()
Definition at line 754 of file VortexLib.cpp.
{
  m_engine.cleanup();
  if (m_storedCallbacks) {
    delete m_storedCallbacks;
    m_storedCallbacks = nullptr;
  }
  m_initialized = false;
}
References VortexEngine::cleanup(), m_engine, m_initialized, and m_storedCallbacks.
Referenced by VortexCLI::cleanup(), and ~Vortex().
clearCommandLog()
void Vortex::clearCommandLog () [inline]
Definition at line 264 of file VortexLib.h.
{ m_commandLog.clear(); }
References m_commandLog.
clearMenuTargetLeds()
void Vortex::clearMenuTargetLeds ()
Definition at line 1164 of file VortexLib.cpp.
{
  Menu *cur = m_engine.menus().curMenu();
  if (!cur) {
    return;
  }
  cur->setTargetLeds(MAP_LED_NONE);
}
References Menus::curMenu(), m_engine, MAP_LED_NONE, VortexEngine::menus(), and Menu::setTargetLeds().
curModeIndex()
uint32_t Vortex::curModeIndex ()
Definition at line 1283 of file VortexLib.cpp.
{
  return m_engine.modes().curModeIndex();
}
References Modes::curModeIndex(), m_engine, and VortexEngine::modes().
delCurMode()
bool Vortex::delCurMode (bool save = true)
Definition at line 1354 of file VortexLib.cpp.
{
  if (!m_engine.modes().numModes()) {
    return true;
  }
  m_engine.modes().deleteCurMode();
  return !save || doSave();
}
References Modes::deleteCurMode(), doSave(), m_engine, VortexEngine::modes(), and Modes::numModes().
deleteColClick()
void Vortex::deleteColClick (uint8_t buttonIndex = 0)
Definition at line 1007 of file VortexLib.cpp.
{
  if (!buttonIndex) {
    buttonIndex = m_selectedButton;
  }
  m_buttonEventQueue.push_back(VortexButtonEvent(buttonIndex, EVENT_DELETE_COL));
}
References EVENT_DELETE_COL, m_buttonEventQueue, and m_selectedButton.
Referenced by doCommand().
doCommand()
void Vortex::doCommand (char c)
Definition at line 813 of file VortexLib.cpp.
{
  if (!isprint(c)) {
    return;
  }
  m_commandLog += c;
  switch (c) {
  case 'c':
    if (m_lastCommand != c) {
      DEBUG_LOG("Injecting short click");
    }
    shortClick();
    break;
  case 'l':
    if (m_lastCommand != c) {
      DEBUG_LOG("Injecting long click");
    }
    longClick();
    break;
  case 'm':
    if (m_lastCommand != c) {
      DEBUG_LOG("Injecting menu enter click");
    }
    menuEnterClick();
    break;
  case 'a':
    if (m_lastCommand != c) {
      DEBUG_LOG("Injecting adv menu enter click");
    }
    advMenuEnterClick();
    break;
  case 'd':
    if (m_lastCommand != c) {
      DEBUG_LOG("Injecting adv menu enter click");
    }
    deleteColClick();
    break;
  case 's':
    if (m_lastCommand != c) {
      DEBUG_LOG("Injecting sleep click");
    }
    sleepClick();
    break;
  case 'f':
    if (m_lastCommand != c) {
      DEBUG_LOG("Injecting force sleep click");
    }
    forceSleepClick();
    break;
  case 'q':
    //case '\n':
    if (m_lastCommand != c) {
      DEBUG_LOG("Injecting quit click\n");
    }
    quitClick();
    break;
  case 't':
    if (isButtonPressed()) {
      if (m_lastCommand != c) {
        DEBUG_LOG("Injecting release");
      }
      releaseButton();
    } else {
      if (m_lastCommand != c) {
        DEBUG_LOG("Injecting press");
      }
      pressButton();
    }
    break;
  case 'r':
    // do nothing for the initial 'r', handleNumber() will handle the numeric
    // repeat count that follows this letter and issue the rapidClick(amt) call
    break;
  case 'b':
    // button selector, same as rapid click, it's a little weird because the number
    // it not a repeat amount but actually the button index to select -- but none
    // the less it works the same as rapid click so it will be handled inside handleNumber()
    break;
  case 'w':
    if (m_lastCommand != c) {
      DEBUG_LOG("Injecting wait");
    }
    sendWait();
    break;
  default:
    handleNumber(c);
    // return instead of break because this isn't a command
    return;
  }
  m_lastCommand = c;
}
References advMenuEnterClick(), DEBUG_LOG, deleteColClick(), forceSleepClick(), handleNumber(), isButtonPressed(), longClick(), m_commandLog, m_lastCommand, menuEnterClick(), pressButton(), quitClick(), releaseButton(), sendWait(), shortClick(), and sleepClick().
Referenced by handleNumber(), and tick().
doSave()
bool Vortex::doSave ()
Definition at line 1716 of file VortexLib.cpp.
{
  return m_engine.modes().saveStorage() && addUndoBuffer();
}
References addUndoBuffer(), m_engine, VortexEngine::modes(), and Modes::saveStorage().
Referenced by addMode(), addNewMode(), VortexCLI::cleanup(), delCurMode(), init(), nextMode(), setColorset(), setCurMode(), setModes(), setPattern(), setPatternArgs(), setPatternAt(), and shiftCurMode().
enableCommandLog()
void Vortex::enableCommandLog (bool enable) [inline]
Definition at line 262 of file VortexLib.h.
{ m_commandLogEnabled = enable; }
References m_commandLogEnabled.
Referenced by VortexCLI::init().
enableLockstep()
bool Vortex::enableLockstep (bool enable) [inline]
Definition at line 267 of file VortexLib.h.
{ return m_lockstepEnabled = enable; }
References m_lockstepEnabled.
Referenced by VortexCLI::init().
enableStorage()
bool Vortex::enableStorage (bool enable) [inline]
Definition at line 271 of file VortexLib.h.
{ return m_storageEnabled = enable; }
References m_storageEnabled.
Referenced by VortexCLI::init().
enableUndo()
void Vortex::enableUndo (bool enabled) [inline]
Definition at line 241 of file VortexLib.h.
{ m_undoEnabled = enabled; }
References m_undoEnabled.
engine()
VortexEngine& Vortex::engine () [inline]
Definition at line 313 of file VortexLib.h.
{ return m_engine; }
References m_engine.
Referenced by VortexCLI::init().
enterSleep()
void Vortex::enterSleep (bool save)
Definition at line 919 of file VortexLib.cpp.
{
  m_engine.enterSleep(save);
}
References VortexEngine::enterSleep(), and m_engine.
forceSleepClick()
void Vortex::forceSleepClick (uint8_t buttonIndex = 0)
Definition at line 1023 of file VortexLib.cpp.
{
  if (!buttonIndex) {
    buttonIndex = m_selectedButton;
  }
  m_buttonEventQueue.push_back(VortexButtonEvent(buttonIndex, EVENT_FORCE_SLEEP_CLICK));
}
References EVENT_FORCE_SLEEP_CLICK, m_buttonEventQueue, and m_selectedButton.
Referenced by doCommand().
getColorset()
bool Vortex::getColorset (LedPos pos, Colorset & set)
Definition at line 1436 of file VortexLib.cpp.
{
  Mode *pMode = m_engine.modes().curMode();
  if (!pMode) {
    return false;
  }
  set = pMode->getColorset(pos);
  return true;
}
References Modes::curMode(), Mode::getColorset(), m_engine, and VortexEngine::modes().
getCommandLog()
const std::string& Vortex::getCommandLog () [inline]
Definition at line 263 of file VortexLib.h.
{ return m_commandLog; }
References m_commandLog.
Referenced by VortexCLI::cleanup().
getCurMode()
bool Vortex::getCurMode (ByteStream & stream)
Definition at line 1269 of file VortexLib.cpp.
{
  Mode *pMode = m_engine.modes().curMode();
  if (!pMode) {
    return false;
  }
  // save to ensure we get the correct mode, not using doSave() because it causes
  // an undo buffer entry to be added
  if (!m_engine.modes().saveStorage()) {
    return false;
  }
  return m_engine.modes().curMode()->saveToBuffer(outStream);
}
References Modes::curMode(), m_engine, VortexEngine::modes(), Modes::saveStorage(), and Mode::saveToBuffer().
Referenced by VortexCLI::cleanup().
getCustomParams()
vector< string > Vortex::getCustomParams (PatternID id)
Definition at line 1591 of file VortexLib.cpp.
{
  Pattern *pat = m_engine.patternBuilder().make(id);
  vector<string> params;
  if (!pat) {
    return params;
  }
  for (uint32_t i = 0; i < pat->getNumArgs(); ++i) {
    params.push_back(pat->getArgName(i));
  }
  delete pat;
  return params;
}
References Pattern::getNumArgs(), m_engine, PatternBuilder::make(), and VortexEngine::patternBuilder().
getLedCount()
uint8_t Vortex::getLedCount ()
Definition at line 1264 of file VortexLib.cpp.
{
  return m_engine.leds().ledCount();
}
References Leds::ledCount(), VortexEngine::leds(), and m_engine.
getMenuDemoMode()
Mode * Vortex::getMenuDemoMode ()
Definition at line 1067 of file VortexLib.cpp.
{
  Menu *pMenu = m_engine.menus().curMenu();
  if (!pMenu) {
    return nullptr;
  }
  return &pMenu->m_previewMode;
}
References Menus::curMenu(), m_engine, Menu::m_previewMode, and VortexEngine::menus().
getModeName()
string Vortex::getModeName ()
Definition at line 1407 of file VortexLib.cpp.
{
  Mode *pMode = m_engine.modes().curMode();
  if (!pMode) {
    return patternToString(PATTERN_NONE);
  }
  if (pMode->isMultiLed()) {
    return getPatternName(LED_MULTI);
  }
  if (pMode->hasSameSingleLed()) {
    return getPatternName(LED_FIRST);
  }
  return "custom";
}
References Modes::curMode(), getPatternName(), Mode::hasSameSingleLed(), Mode::isMultiLed(), LED_FIRST, LED_MULTI, m_engine, VortexEngine::modes(), PATTERN_NONE, and patternToString().
getModes()
bool Vortex::getModes (ByteStream & outStream)
Definition at line 1192 of file VortexLib.cpp.
{
  // now serialize all the modes
  m_engine.modes().saveToBuffer(outStream);
  return true;
}
References m_engine, VortexEngine::modes(), and Modes::saveToBuffer().
Referenced by addUndoBuffer(), and VortexCLI::cleanup().
getNumInputs()
uint32_t Vortex::getNumInputs () [private]
Definition at line 1877 of file VortexLib.cpp.
{
  uint32_t numInputs = 0;
  // On linux we need to poll stdin for input to handle commands
#if !defined(_WIN32) && !defined(WASM)
  ioctl(STDIN_FILENO, FIONREAD, &numInputs);
#elif defined(_WIN32)
  HANDLE hStdin = GetStdHandle(STD_INPUT_HANDLE);
  if (GetFileType(hStdin) == FILE_TYPE_CHAR) {
    // Handle console input
    if (!GetNumberOfConsoleInputEvents(hStdin, (DWORD *)&numInputs)) {
      // Handle error here
    }
    INPUT_RECORD inputRecord;
    DWORD eventsRead;
    while (PeekConsoleInput(hStdin, &inputRecord, 1, &eventsRead) && eventsRead > 0) {
      // Discard non-character events
      if (inputRecord.EventType != KEY_EVENT || !inputRecord.Event.KeyEvent.bKeyDown) {
        numInputs--;
      }
      // Remove the event from the input buffer
      ReadConsoleInput(hStdin, &inputRecord, 1, &eventsRead);
    }
  } else {
    // Handle redirected input
    DWORD availableBytes;
    if (PeekNamedPipe(hStdin, NULL, 0, NULL, &availableBytes, NULL)) {
      numInputs = availableBytes;
    } else {
      // Handle error here
    }
  }
#endif
  return numInputs;
}
Referenced by tick().
getPatternArgs()
bool Vortex::getPatternArgs (LedPos pos, PatternArgs & args)
Definition at line 1459 of file VortexLib.cpp.
{
  Mode *pMode = m_engine.modes().curMode();
  if (!pMode) {
    return false;
  }
  Pattern *pat = pMode->getPattern(pos);
  if (!pat) {
    return false;
  }
  pat->getArgs(args);
  return true;
}
References Modes::curMode(), Pattern::getArgs(), Mode::getPattern(), m_engine, and VortexEngine::modes().
Referenced by getPatternName().
getPatternID()
PatternID Vortex::getPatternID (LedPos pos)
Definition at line 1388 of file VortexLib.cpp.
{
  Mode *pMode = m_engine.modes().curMode();
  if (!pMode) {
    return PATTERN_NONE;
  }
  return pMode->getPatternID(pos);
}
References Modes::curMode(), Mode::getPatternID(), m_engine, VortexEngine::modes(), and PATTERN_NONE.
Referenced by getPatternName().
getPatternName()
string Vortex::getPatternName (LedPos pos)
Definition at line 1397 of file VortexLib.cpp.
{
  PatternID id = getPatternID(pos);
  PatternArgs args;
  if (getPatternArgs(pos, args) && !m_engine.patternBuilder().isDefaultArgs(id, args)) {
    return "custom";
  }
  return patternToString(id);
}
References getPatternArgs(), getPatternID(), PatternBuilder::isDefaultArgs(), m_engine, VortexEngine::patternBuilder(), and patternToString().
Referenced by getModeName().
getStorageFilename()
string Vortex::getStorageFilename ()
Definition at line 1946 of file VortexLib.cpp.
{
  return m_engine.storage().getStorageFilename();
}
References m_engine, and VortexEngine::storage().
getStorageStats()
void Vortex::getStorageStats (uint32_t * outTotal, uint32_t * outUsed)
Definition at line 1112 of file VortexLib.cpp.
{
  if (outTotal) {
    *outTotal = m_engine.totalStorageSpace();
  }
  if (outUsed) {
    *outUsed = m_engine.savefileSize();
  }
}
References m_engine.
getTickrate()
uint32_t Vortex::getTickrate ()
Definition at line 1711 of file VortexLib.cpp.
{
  return m_engine.time().getTickrate();
}
References Time::getTickrate(), m_engine, and VortexEngine::time().
handleInputQueue()
void Vortex::handleInputQueue (Button * buttons, uint32_t numButtons) [private]
Definition at line 1721 of file VortexLib.cpp.
{
  // if there's nothing in the queue just return
  if (!m_buttonEventQueue.size()) {
    return;
  }
  // pop the event from the front of the queue
  VortexButtonEvent buttonEvent = m_buttonEventQueue.front();
  m_buttonEventQueue.pop_front();
  // the target button for this event (no target if event is just 'wait')
  Button *pButton = buttons;
  if (buttonEvent.type != EVENT_WAIT && buttonEvent.type != EVENT_RAPID_CLICK) {
    // make sure the button that is targeted is actually a valid index
    if (buttonEvent.target >= numButtons) {
      return;
    }
    // assigned the button based on the array index target
    pButton = buttons + buttonEvent.target;
  }
  // switch on the type of event and then run the operation
  switch (buttonEvent.type) {
  case EVENT_NONE:
  default:
    break;
  case EVENT_SHORT_CLICK:
    pButton->m_newRelease = true;
    pButton->m_shortClick = true;
    pButton->m_pressTime = m_engine.time().getCurtime();
    pButton->m_holdDuration = SHORT_CLICK_THRESHOLD_TICKS - 1;
    DEBUG_LOG("Injecting short click");
    break;
  case EVENT_LONG_CLICK:
    pButton->m_newRelease = true;
    pButton->m_longClick = true;
    pButton->m_pressTime = m_engine.time().getCurtime();
    pButton->m_holdDuration = SHORT_CLICK_THRESHOLD_TICKS + 1;
    DEBUG_LOG("Injecting long click");
    break;
  case EVENT_MENU_ENTER_CLICK:
    // to do this we simply press the button and set the press time
    // to something more than the menu trigger threshold that will make
    // us immediately enter the menus. But we need to unset the pressed
    // button right after so we push a reset click event to reset the button
    pButton->m_pressTime = m_engine.time().getCurtime();
#if defined(SLEEP_ENTER_THRESHOLD_TICKS) && defined(SLEEP_WINDOW_THRESHOLD_TICKS)
    // microlight must hold longer (past sleep time)
    pButton->m_holdDuration = MENU_TRIGGER_THRESHOLD_TICKS + SLEEP_ENTER_THRESHOLD_TICKS + SLEEP_WINDOW_THRESHOLD_TICKS + 1;
#else
    pButton->m_holdDuration = MENU_TRIGGER_THRESHOLD_TICKS + 1;
#endif
    pButton->m_isPressed = true;
    m_buttonEventQueue.push_front(VortexButtonEvent(0, EVENT_RESET_CLICK));
    DEBUG_LOG("Injecting menu enter click");
    break;
  case EVENT_ADV_MENU_ENTER_CLICK:
    // to do this we simply press the button and set the press time
    // to something more than the menu trigger threshold that will make
    // us immediately enter the menus. But we need to unset the pressed
    // button right after so we push a reset click event to reset the button
    pButton->m_pressTime = m_engine.time().getCurtime();
    pButton->m_holdDuration = ADV_MENU_DURATION_TICKS + 1;
    pButton->m_longClick = true;
    pButton->m_newRelease = true;
    DEBUG_LOG("Injecting adv menu enter click");
    break;
  case EVENT_DELETE_COL:
    // to do this we simply press the button and set the press time
    // to something more than the menu trigger threshold that will make
    // us immediately enter the menus. But we need to unset the pressed
    // button right after so we push a reset click event to reset the button
    pButton->m_pressTime = m_engine.time().getCurtime();
    pButton->m_holdDuration = DELETE_THRESHOLD_TICKS + DELETE_CYCLE_TICKS + 1;
    pButton->m_longClick = true;
    pButton->m_newRelease = true;
    DEBUG_LOG("Injecting delete color click");
    break;
  case EVENT_SLEEP_CLICK:
    // to do this we simply press the button and set the press time
    // to something more than the menu trigger threshold that will make
    // us immediately enter the menus. But we need to unset the pressed
    // button right after so we push a reset click event to reset the button
#ifdef SLEEP_ENTER_THRESHOLD_TICKS
    pButton->m_pressTime = m_engine.time().getCurtime();
    pButton->m_holdDuration = SLEEP_ENTER_THRESHOLD_TICKS + 1;
    pButton->m_longClick = true;
    pButton->m_newRelease = true;
    DEBUG_LOG("Injecting sleep click");
#endif
    break;
  case EVENT_FORCE_SLEEP_CLICK:
    // to do this we simply press the button and set the press time
    // to something more than the menu trigger threshold that will make
    // us immediately enter the menus. But we need to unset the pressed
    // button right after so we push a reset click event to reset the button
#ifdef FORCE_SLEEP_THRESHOLD_TICKS
    pButton->m_pressTime = m_engine.time().getCurtime();
    pButton->m_holdDuration = FORCE_SLEEP_THRESHOLD_TICKS + 1;
    pButton->m_longClick = true;
    pButton->m_newRelease = true;
    DEBUG_LOG("Injecting force sleep click");
#endif
    break;
  case EVENT_WAIT:
    if (buttonEvent.target) {
      // backup the event queue and clear it
      deque<Vortex::VortexButtonEvent> backup;
      swap(backup, m_buttonEventQueue);
      // ticks the engine forward some number of ticks, the event queue is empty
      // so the engine won't process any input events while doing this
      for (uint32_t i = 0; i < buttonEvent.target; ++i) {
        m_engine.tick();
      }
      // then restore the event queue so that events are processed like normal
      swap(backup, m_buttonEventQueue);
    }
    break;
  case EVENT_TOGGLE_CLICK:
    if (pButton->isPressed()) {
      // re-calc all this stuff because there's no api in Button class to do it
      // I don't want to add the api there because it's useless besides for this
      pButton->m_buttonState = false;
      pButton->m_isPressed = false;
      pButton->m_holdDuration = (uint32_t)(m_engine.time().getCurtime() - pButton->m_pressTime);
      pButton->m_releaseTime = m_engine.time().getCurtime();
      pButton->m_newRelease = true;
      pButton->m_shortClick = (pButton->m_holdDuration <= SHORT_CLICK_THRESHOLD_TICKS);
      pButton->m_longClick = !pButton->m_shortClick;
      DEBUG_LOG("Injecting release");
    } else {
      pButton->m_buttonState = true;
      pButton->m_isPressed = true;
      pButton->m_releaseDuration = (uint32_t)(m_engine.time().getCurtime() - pButton->m_releaseTime);
      pButton->m_pressTime = m_engine.time().getCurtime();
      pButton->m_newPress = true;
      DEBUG_LOG("Injecting press");
    }
    break;
  case EVENT_RAPID_CLICK:
    pButton->m_consecutivePresses = buttonEvent.target;
    pButton->m_newRelease = true;
    pButton->m_shortClick = true;
    pButton->m_pressTime = m_engine.time().getCurtime();
    pButton->m_holdDuration = 1;
    DEBUG_LOGF("Injecting %u x rapid click", buttonEvent.target);
    break;
  case EVENT_QUIT_CLICK:
    // just uninitialize so tick returns false
    m_initialized = false;
    DEBUG_LOG("Injecting quit");
    break;
  case EVENT_RESET_CLICK:
    pButton->m_isPressed = false;
    break;
  }
}
References ADV_MENU_DURATION_TICKS, DEBUG_LOG, DEBUG_LOGF, DELETE_CYCLE_TICKS, DELETE_THRESHOLD_TICKS, EVENT_ADV_MENU_ENTER_CLICK, EVENT_DELETE_COL, EVENT_FORCE_SLEEP_CLICK, EVENT_LONG_CLICK, EVENT_MENU_ENTER_CLICK, EVENT_NONE, EVENT_QUIT_CLICK, EVENT_RAPID_CLICK, EVENT_RESET_CLICK, EVENT_SHORT_CLICK, EVENT_SLEEP_CLICK, EVENT_TOGGLE_CLICK, EVENT_WAIT, Time::getCurtime(), Button::isPressed(), m_buttonEventQueue, Button::m_buttonState, Button::m_consecutivePresses, m_engine, Button::m_holdDuration, m_initialized, Button::m_isPressed, Button::m_longClick, Button::m_newPress, Button::m_newRelease, Button::m_pressTime, Button::m_releaseDuration, Button::m_releaseTime, Button::m_shortClick, MENU_TRIGGER_THRESHOLD_TICKS, SHORT_CLICK_THRESHOLD_TICKS, Vortex::VortexButtonEvent::target, VortexEngine::tick(), VortexEngine::time(), and Vortex::VortexButtonEvent::type.
Referenced by Buttons::update().
handleNumber()
void Vortex::handleNumber (char c) [private]
Definition at line 764 of file VortexLib.cpp.
{
  if (!isdigit(c) || !m_lastCommand) {
    return;
  }
  int number = c - '0';
  char newc = 0;
  // read the digits into the repeatAmount
  while (1) {
    newc = getchar();
    if (!isdigit(newc)) {
      // stop once we reach a non digit
      break;
    }
    // accumulate the digits into the repeat amount
    number = (number * 10) + (newc - '0');
  }
  // shove the last non-digit back into the stream
  ungetc(newc, stdin);
  DEBUG_LOGF("Repeating last command (%c) x%u times", m_lastCommand, number);
  m_commandLog += to_string(number);
  // check to see if we are repeating a 'rapid click' which is a special case
  // because the rapid click command itself is composed or 'r' and a repeat count
  // to designate how many rapid clicks to deliver
  switch (m_lastCommand) {
  case 'r':
    // perform a rapid click number times
    rapidClick(number);
    break;
  case 'b':
    // select button index to target for click events
    selectButton(number);
    break;
  default: // any other command
    if (number > 0) {
      // offset repeat amount by exactly 1 because it's already done
      number--;
    }
    // repeat the last command that many times
    while (number > 0) {
      doCommand(m_lastCommand);
      number--;
    }
    break;
  }
}
References DEBUG_LOGF, doCommand(), m_commandLog, m_lastCommand, rapidClick(), and selectButton().
Referenced by doCommand().
init() [1/2]
void Vortex::init () [inline]
Definition at line 95 of file VortexLib.h.
{ initEx<VortexCallbacks>(); }
Referenced by initEx().
init() [2/2]
bool Vortex::init (VortexCallbacks * callbacks) [private]
Definition at line 704 of file VortexLib.cpp.
{
  if (m_storedCallbacks) {
    delete m_storedCallbacks;
  }
  // store the callbacks object
  m_storedCallbacks = callbacks;
#if LOG_TO_CONSOLE == 1
  if (!m_consoleHandle) {
#ifdef _WIN32
    AllocConsole();
    freopen_s(&m_consoleHandle, "CONOUT$", "w", stdout);
#else
    m_consoleHandle = stdout;
#endif
  }
#endif
#if LOG_TO_FILE == 1
  if (!m_logHandle) {
    time_t t = time(nullptr);
    tm tm;
    localtime_s(&tm, &t);
    ostringstream oss;
    oss << put_time(&tm, "%d-%m-%Y-%H-%M-%S");
    oss << "." << GetCurrentProcessId();
    string filename = VORTEX_LOG_NAME "." + oss.str() + ".txt";
    int err = fopen_s(&m_logHandle, filename.c_str(), "w");
    if (err != 0 || !m_logHandle) {
      MessageBox(NULL, "Failed to open logfile", to_string(err).c_str(), 0);
      return false;
    }
  }
#endif
  // init the engine
  m_engine.init();
  // load the modes
  // TODO: don't load modes here? separate api?
  m_engine.modes().load();
  // clear the modes
  //m_engine.modes().clearModes();
  // save and set undo buffer
  doSave();
  m_initialized = true;
  return true;
}
References doSave(), VortexEngine::init(), Modes::load(), m_consoleHandle, m_engine, m_initialized, m_storedCallbacks, VortexEngine::modes(), and VORTEX_LOG_NAME.
initEx()
template<typename T >
T* Vortex::initEx () [inline]
Definition at line 99 of file VortexLib.h.
  {
    if (!std::is_base_of<VortexCallbacks, T>()) {
      return nullptr;
    }
    T *callbacks = new T(*this);
    if (!callbacks) {
      return nullptr;
    }
    if (!init(callbacks)) {
      return nullptr;
    }
    return callbacks;
  }
References init().
Referenced by VortexCLI::init().
installCallbacks()
void Vortex::installCallbacks (VortexCallbacks * callbacks)
Definition at line 955 of file VortexLib.cpp.
{
  m_storedCallbacks = callbacks;
}
References m_storedCallbacks.
IRDeliver()
void Vortex::IRDeliver (uint32_t timing)
Definition at line 1098 of file VortexLib.cpp.
{
#if IR_ENABLE_RECEIVER == 1
  m_engine.irReceiver().handleIRTiming(timing);
#endif
}
References IRReceiver::handleIRTiming(), VortexEngine::irReceiver(), and m_engine.
isButtonPressed()
bool Vortex::isButtonPressed (uint8_t buttonIndex = 0)
Definition at line 1047 of file VortexLib.cpp.
{
  if (!buttonIndex) {
    buttonIndex = m_selectedButton;
  }
  return (m_buttonsPressed & (1 << buttonIndex)) != 0;
}
References m_buttonsPressed, and m_selectedButton.
Referenced by VortexCLI::VortexCLICallbacks::checkPinHook(), doCommand(), and VortexCLI::isButtonPressed().
isCurModeMulti()
bool Vortex::isCurModeMulti ()
Definition at line 1538 of file VortexLib.cpp.
{
  Mode *pMode = m_engine.modes().curMode();
  if (!pMode) {
    return false;
  }
  return pMode->isMultiLed();
}
References Modes::curMode(), Mode::isMultiLed(), m_engine, and VortexEngine::modes().
isLockstep()
bool Vortex::isLockstep () [inline]
Definition at line 268 of file VortexLib.h.
{ return m_lockstepEnabled; }
References m_lockstepEnabled.
isSleeping()
bool Vortex::isSleeping ()
Definition at line 924 of file VortexLib.cpp.
{
  return m_engine.isSleeping();
}
References m_engine.
ledToString()
string Vortex::ledToString (LedPos pos)
Definition at line 1580 of file VortexLib.cpp.
{
  return "led " + to_string(pos);
}
loadFromJson()
bool Vortex::loadFromJson (const json & json)
Definition at line 2193 of file VortexLib.cpp.
{
  if (js.is_null()) {
    return false;
  }
  uint8_t major = 0;
  uint8_t minor = 0;
  if (js.contains("version_major") && js["version_major"].is_number_unsigned()) {
    major = js["version_major"].get<uint8_t>();
  }
  if (js.contains("version_minor") && js["version_minor"].is_number_unsigned()) {
    minor = js["version_minor"].get<uint8_t>();
  }
  if (!m_engine.checkVersion(major, minor)) {
    return false;
  }
  if (js.contains("brightness") && js["brightness"].is_number_unsigned()) {
    uint8_t brightness = js["brightness"].get<uint8_t>();
    m_engine.leds().setBrightness(brightness);
  }
  if (js.contains("global_flags") && js["global_flags"].is_number_unsigned()) {
    uint8_t global_flags = js["global_flags"].get<uint8_t>();
    m_engine.modes().setFlag(global_flags, true, false);
  }
  uint8_t num_modes = 0;
  if (js.contains("num_modes") && js["num_modes"].is_number_unsigned()) {
    num_modes = js["num_modes"].get<uint8_t>();
  }
  if (!js.contains("modes") || !js["modes"].is_array()) {
    return false;
  }
  m_engine.modes().clearModes();
  for (const auto &modeValue : js["modes"]) {
    if (modeValue.is_null() || !modeValue.is_object()) {
      continue;
    }
    if (!loadModeFromJson(modeValue)) {
      // error?
      return false;
    }
  }
  return m_engine.modes().numModes() == num_modes;
}
References VortexEngine::checkVersion(), Modes::clearModes(), VortexEngine::leds(), loadModeFromJson(), m_engine, VortexEngine::modes(), Modes::numModes(), Leds::setBrightness(), and Modes::setFlag().
Referenced by parseJson(), and parseJsonFromFile().
loadModeFromJson()
bool Vortex::loadModeFromJson (const json & modeJson)
Definition at line 2140 of file VortexLib.cpp.
{
  if (js.is_null()) {
    return false;
  }
  // TODO: reintroduce version to vtxmode format
  //uint8_t major = 0;
  //uint8_t minor = 0;
  //if (js.contains("version_major") && js["version_major"].is_number_unsigned()) {
  // major = js["version_major"].get<uint8_t>();
  //}
  //if (js.contains("version_minor") && js["version_minor"].is_number_unsigned()) {
  // minor = js["version_minor"].get<uint8_t>();
  //}
  //if (!m_engine.checkVersion(major, minor)) {
  // return false;
  //}
  Mode *mode = modeFromJson(js);
  if (!mode) {
    return false;
  }
  bool rv = m_engine.modes().addMode(mode);
  delete mode;
  return rv;
}
References Modes::addMode(), m_engine, modeFromJson(), and VortexEngine::modes().
Referenced by loadFromJson().
loadStorage()
void Vortex::loadStorage ()
Definition at line 1122 of file VortexLib.cpp.
{
  m_engine.modes().loadStorage();
}
References Modes::loadStorage(), m_engine, and VortexEngine::modes().
Referenced by VortexCLI::init().
lockEnabled()
bool Vortex::lockEnabled () [inline]
Definition at line 280 of file VortexLib.h.
{ return m_lockEnabled; }
References m_lockEnabled.
longClick()
void Vortex::longClick (uint8_t buttonIndex = 0)
Definition at line 983 of file VortexLib.cpp.
{
  if (!buttonIndex) {
    buttonIndex = m_selectedButton;
  }
  m_buttonEventQueue.push_back(VortexButtonEvent(buttonIndex, EVENT_LONG_CLICK));
}
References EVENT_LONG_CLICK, m_buttonEventQueue, and m_selectedButton.
Referenced by doCommand().
matchLedCount()
bool Vortex::matchLedCount (ByteStream & stream, bool vtxMode)
Definition at line 1209 of file VortexLib.cpp.
{
  if (!stream.decompress()) {
    return false;
  }
  // reset the unserializer index before unserializing anything
  stream.resetUnserializer();
  uint8_t major = 0;
  uint8_t minor = 0;
  // unserialize the vortex version
  stream.unserialize8(&major);
  stream.unserialize8(&minor);
  // unserialize the global brightness
  if (!vtxMode) {
    uint8_t flags;
    stream.unserialize8(&flags);
    uint8_t brightness = 0;
    stream.unserialize8(&brightness);
    uint8_t numModes = 0;
    stream.unserialize8(&numModes);
  }
  uint8_t ledCount = 0;
  stream.unserialize8(&ledCount);
  // put the unserializer back where it was for the next thing
  stream.resetUnserializer();
  return setLedCount(ledCount);
}
References ByteStream::decompress(), numModes(), ByteStream::resetUnserializer(), setLedCount(), and ByteStream::unserialize8().
Referenced by VortexCLI::init().
menuEnterClick()
void Vortex::menuEnterClick (uint8_t buttonIndex = 0)
Definition at line 991 of file VortexLib.cpp.
{
  if (!buttonIndex) {
    buttonIndex = m_selectedButton;
  }
  m_buttonEventQueue.push_back(VortexButtonEvent(buttonIndex, EVENT_MENU_ENTER_CLICK));
}
References EVENT_MENU_ENTER_CLICK, m_buttonEventQueue, and m_selectedButton.
Referenced by doCommand().
modeFromJson()
Mode * Vortex::modeFromJson (const json & modeJson)
Definition at line 1980 of file VortexLib.cpp.
{
  if (modeJson.is_null()) {
    return nullptr;
  }
  Mode *mode = new Mode(m_engine);
  if (!mode) {
    return nullptr;
  }
  if (modeJson.contains("num_leds") && modeJson["num_leds"].is_number_unsigned()) {
    mode->setLedCount(modeJson["num_leds"].get<uint8_t>());
  }
  // Extract and set multiPattern
  if (modeJson.contains("multi_pat") && modeJson["multi_pat"].is_object()) {
    const json &multiPatJson = modeJson["multi_pat"];
    Pattern *multiPattern = patternFromJson(multiPatJson);
    if (multiPattern) {
      PatternArgs args;
      multiPattern->getArgs(args);
      Colorset set = multiPattern->getColorset();
      mode->setPattern(multiPattern->getPatternID(), LED_MULTI, &args, &set);
      delete multiPattern;
    }
  }
  // Extract and set singlePatterns
  if (modeJson.contains("single_pats") && modeJson["single_pats"].is_array()) {
    LedPos pos = LED_FIRST;
    for (const json &patJson : modeJson["single_pats"]) {
      if (patJson.is_object()) {
        Pattern *pattern = patternFromJson(patJson);
        if (pattern) {
          PatternArgs args;
          pattern->getArgs(args);
          Colorset set = pattern->getColorset();
          mode->setPattern(pattern->getPatternID(), pos++, &args, &set);
          delete pattern;
        }
      }
    }
  }
  // fallback to load 1-led pattern data as the mode if multi_pat and single_pats are missing
  if (!modeJson.contains("multi_pat") && !modeJson.contains("single_pats")) {
    Pattern *pattern = patternFromJson(modeJson);
    if (!pattern) {
      return mode;
    }
    PatternArgs args;
    pattern->getArgs(args);
    Colorset set = pattern->getColorset();
    mode->setPattern(pattern->getPatternID(), LED_FIRST, &args, &set);
    delete pattern;
  }
  return mode;
}
References Pattern::getArgs(), Pattern::getColorset(), Pattern::getPatternID(), LED_FIRST, LED_MULTI, m_engine, patternFromJson(), Mode::setLedCount(), and Mode::setPattern().
Referenced by loadModeFromJson(), and parseModeJson().
modeToJson()
json Vortex::modeToJson (const Mode * mode)
Definition at line 1951 of file VortexLib.cpp.
{
  if (!mode) {
    return nullptr;
  }
  json modeJson;
  modeJson["num_leds"] = mode->getLedCount();
  modeJson["flags"] = (uint8_t)mode->getFlags();
  const Pattern *multiPattern = mode->getPattern(LED_MULTI);
  if (multiPattern) {
    modeJson["multi_pat"] = patternToJson(multiPattern);
  }
  json singlePatterns = json::array();
  for (LedPos l = LED_FIRST; l < mode->getLedCount(); ++l) {
    const Pattern *pattern = mode->getPattern(l);
    if (pattern) {
      singlePatterns.push_back(patternToJson(pattern));
    } else {
      singlePatterns.push_back(nullptr);
    }
  }
  modeJson["single_pats"] = singlePatterns;
  return modeJson;
}
References Mode::getFlags(), Mode::getLedCount(), Mode::getPattern(), LED_FIRST, LED_MULTI, and patternToJson().
Referenced by printModeJson(), and saveModeToJson().
nextMode()
bool Vortex::nextMode (bool save = true)
Definition at line 1345 of file VortexLib.cpp.
{
  if (!m_engine.modes().numModes()) {
    return true;
  }
  m_engine.modes().nextMode();
  return !save || doSave();
}
References doSave(), m_engine, VortexEngine::modes(), Modes::nextMode(), and Modes::numModes().
numCustomParams()
uint32_t Vortex::numCustomParams (PatternID id)
Definition at line 1586 of file VortexLib.cpp.
{
  return m_engine.patternBuilder().numDefaultArgs(id);
}
References m_engine, PatternBuilder::numDefaultArgs(), and VortexEngine::patternBuilder().
numLedsInMode()
uint32_t Vortex::numLedsInMode ()
Definition at line 1293 of file VortexLib.cpp.
{
  Mode *pMode = m_engine.modes().curMode();
  if (!pMode) {
    return false;
  }
  return pMode->getLedCount();
}
References Modes::curMode(), Mode::getLedCount(), m_engine, and VortexEngine::modes().
numModes()
uint32_t Vortex::numModes ()
Definition at line 1288 of file VortexLib.cpp.
{
  return m_engine.modes().numModes();
}
References m_engine, VortexEngine::modes(), and Modes::numModes().
Referenced by matchLedCount(), and saveToJson().
openColorSelect()
void Vortex::openColorSelect (bool advanced = false)
Definition at line 1132 of file VortexLib.cpp.
{
  m_engine.menus().openMenu(MENU_COLOR_SELECT, advanced);
}
References m_engine, MENU_COLOR_SELECT, VortexEngine::menus(), and Menus::openMenu().
openEditorConnection()
void Vortex::openEditorConnection (bool advanced = false)
Definition at line 1157 of file VortexLib.cpp.
{
#if ENABLE_EDITOR_CONNECTION == 1
  m_engine.menus().openMenu(MENU_EDITOR_CONNECTION, advanced);
#endif
}
References m_engine, MENU_EDITOR_CONNECTION, VortexEngine::menus(), and Menus::openMenu().
openFactoryReset()
void Vortex::openFactoryReset (bool advanced = false)
Definition at line 1147 of file VortexLib.cpp.
{
  m_engine.menus().openMenu(MENU_FACTORY_RESET, advanced);
}
References m_engine, MENU_FACTORY_RESET, VortexEngine::menus(), and Menus::openMenu().
openGlobalBrightness()
void Vortex::openGlobalBrightness (bool advanced = false)
Definition at line 1142 of file VortexLib.cpp.
{
  m_engine.menus().openMenu(MENU_GLOBAL_BRIGHTNESS, advanced);
}
References m_engine, MENU_GLOBAL_BRIGHTNESS, VortexEngine::menus(), and Menus::openMenu().
openModeSharing()
void Vortex::openModeSharing (bool advanced = false)
Definition at line 1152 of file VortexLib.cpp.
{
  m_engine.menus().openMenu(MENU_MODE_SHARING, advanced);
}
References m_engine, MENU_MODE_SHARING, VortexEngine::menus(), and Menus::openMenu().
openPatternSelect()
void Vortex::openPatternSelect (bool advanced = false)
Definition at line 1137 of file VortexLib.cpp.
{
  m_engine.menus().openMenu(MENU_PATTERN_SELECT, advanced);
}
References m_engine, MENU_PATTERN_SELECT, VortexEngine::menus(), and Menus::openMenu().
openRandomizer()
void Vortex::openRandomizer (bool advanced = false)
Definition at line 1127 of file VortexLib.cpp.
{
  m_engine.menus().openMenu(MENU_RANDOMIZER, advanced);
}
References m_engine, MENU_RANDOMIZER, VortexEngine::menus(), and Menus::openMenu().
parseJson()
bool Vortex::parseJson (const std::string & json)
Definition at line 2326 of file VortexLib.cpp.
{
  try {
    json jsonObj = json::parse(jsonStr);
    return loadFromJson(jsonObj);
  } catch (json::parse_error &e) {
    std::cerr << "JSON Parse Error: " << e.what() << std::endl;
    return false;
  }
}
References loadFromJson().
Referenced by VortexCLI::init().
parseJsonFromFile()
bool Vortex::parseJsonFromFile (const std::string & filename)
Definition at line 2352 of file VortexLib.cpp.
{
  std::ifstream file(filename);
  if (!file.is_open()) {
    return false;
  }
  try {
    json jsonObj = json::parse(file);
    return loadFromJson(jsonObj);
  } catch (json::parse_error &e) {
    std::cerr << "JSON Parse Error: " << e.what() << std::endl;
    return false;
  }
}
References loadFromJson().
Referenced by VortexCLI::init().
parseModeJson()
bool Vortex::parseModeJson (const std::string & json)
Definition at line 2258 of file VortexLib.cpp.
{
  json jsonObj;
  try {
    jsonObj = json::parse(jsonStr);
  } catch (json::parse_error &e) {
    std::cerr << "JSON Parse Error: " << e.what() << std::endl;
    return false;
  }
  Mode *tempMode = modeFromJson(jsonObj);
  if (!tempMode) {
    return false;
  }
  // update the current mode with the parsed json mode
  bool result = m_engine.modes().updateCurMode(tempMode);
  delete tempMode;
  return result;
}
References m_engine, modeFromJson(), VortexEngine::modes(), and Modes::updateCurMode().
parsePatternJson()
bool Vortex::parsePatternJson (LedPos pos, const std::string & json)
Definition at line 2293 of file VortexLib.cpp.
{
  Mode *cur = m_engine.modes().curMode();
  if (!cur) {
    return false;
  }
  json jsonObj;
  try {
    jsonObj = json::parse(jsonStr);
  } catch (json::parse_error &e) {
    std::cerr << "JSON Parse Error: " << e.what() << std::endl;
    return false;
  }
  Pattern *tempPat = patternFromJson(jsonObj);
  if (!tempPat) {
    return false;
  }
  // update the current mode with the parsed json mode
  PatternID patID = tempPat->getPatternID();
  PatternArgs args;
  tempPat->getArgs(args);
  Colorset set = tempPat->getColorset();
  delete tempPat;
  return cur->setPattern(patID, pos, &args, &set);
}
References Modes::curMode(), Pattern::getArgs(), Pattern::getColorset(), Pattern::getPatternID(), m_engine, VortexEngine::modes(), patternFromJson(), and Mode::setPattern().
patternFromJson()
Pattern * Vortex::patternFromJson (const json & patternJson)
Definition at line 2075 of file VortexLib.cpp.
{
  if (patternJson.is_null()) {
    return nullptr;
  }
  // Get pattern ID
  PatternID id = PATTERN_NONE;
  if (patternJson.contains("pattern_id") && patternJson["pattern_id"].is_number_unsigned()) {
    id = static_cast<PatternID>(patternJson["pattern_id"].get<uint8_t>());
  }
  // Validate the pattern ID
  if (id >= PATTERN_COUNT) {
    return nullptr;
  }
  // Parse out the args
  PatternArgs args;
  if (patternJson.contains("args") && patternJson["args"].is_array()) {
    for (const auto &arg : patternJson["args"]) {
      if (arg.is_number_unsigned()) {
        args.addArgs(static_cast<uint8_t>(arg.get<uint8_t>()));
      }
    }
  }
  // Parse out the colorset
  Colorset set;
  if (patternJson.contains("colorset") && patternJson["colorset"].is_array()) {
    for (const auto &colorElement : patternJson["colorset"]) {
      if (colorElement.is_string()) {
        string strVal = colorElement.get<string>();
        if (strVal.find("0x") == 0) {
          strVal = strVal.substr(2);
        }
        uint32_t dwCol = strtoul(strVal.c_str(), NULL, 16);
        set.addColor(RGBColor(dwCol));
      }
    }
  }
  // Build the pattern with ID + args
  Pattern *pattern = m_engine.patternBuilder().make(id, &args);
  if (!pattern) {
    return nullptr;
  }
  // Apply colorset and init
  pattern->setColorset(set);
  pattern->init();
  return pattern;
}
References PatternArgs::addArgs(), Colorset::addColor(), Colorset::get(), Pattern::init(), m_engine, PatternBuilder::make(), PATTERN_COUNT, PATTERN_NONE, VortexEngine::patternBuilder(), and Pattern::setColorset().
Referenced by modeFromJson(), and parsePatternJson().
patternToJson()
json Vortex::patternToJson (const Pattern * pattern)
Definition at line 2041 of file VortexLib.cpp.
{
  if (!pattern) {
    return nullptr;
  }
  json patternJson;
  patternJson["pattern_id"] = pattern->getPatternID();
  patternJson["flags"] = pattern->getFlags();
  const Colorset &colorset = pattern->getColorset();
  patternJson["numColors"] = colorset.numColors();
  json colorsetArray = json::array();
  for (uint8_t c = 0; c < colorset.numColors(); ++c) {
    const RGBColor &color = colorset.get(c);
    std::stringstream colorString;
    colorString << "0x"
      << std::setfill('0') << std::setw(2) << std::hex << (int)color.red
      << std::setfill('0') << std::setw(2) << std::hex << (int)color.green
      << std::setfill('0') << std::setw(2) << std::hex << (int)color.blue;
    colorsetArray.push_back(colorString.str());
  }
  patternJson["colorset"] = colorsetArray;
  json argsArray = json::array();
  for (uint8_t a = 0; a < pattern->getNumArgs(); ++a) {
    argsArray.push_back(pattern->getArg(a));
  }
  patternJson["args"] = argsArray;
  return patternJson;
}
References RGBColor::blue, Colorset::get(), Pattern::getArg(), Pattern::getColorset(), Pattern::getFlags(), Pattern::getNumArgs(), Pattern::getPatternID(), RGBColor::green, Colorset::numColors(), and RGBColor::red.
Referenced by modeToJson(), and printPatternJson().
patternToString()
string Vortex::patternToString (PatternID id = PATTERN_NONE)
Definition at line 1547 of file VortexLib.cpp.
{
  // this shouldn't happen but just in case somebody messes with stuff
  if (sizeof(patternNames) / sizeof(patternNames[0]) != PATTERN_COUNT) {
    // if you see this it means the list of strings above is not equal to
    // the number of patterns in the enum, so you need to update the list
    // above to match the enum.
    return "fix patternToString()";
  }
  if (id <= PATTERN_NONE || id >= PATTERN_COUNT) {
    return "none";
  }
  return patternNames[id];
}
References PATTERN_COUNT, and patternNames.
Referenced by getModeName(), and getPatternName().
pressButton()
void Vortex::pressButton (uint8_t buttonIndex = 0)
Definition at line 1031 of file VortexLib.cpp.
{
  if (!buttonIndex) {
    buttonIndex = m_selectedButton;
  }
  m_buttonsPressed |= (1 << buttonIndex);
}
References m_buttonsPressed, and m_selectedButton.
Referenced by doCommand().
printJson()
std::string Vortex::printJson (bool pretty = false)
Definition at line 2320 of file VortexLib.cpp.
{
  json json = saveToJson();
  return pretty ? json.dump(4) : json.dump();
}
References saveToJson().
Referenced by VortexCLI::cleanup(), and printJsonToFile().
printJsonToFile()
bool Vortex::printJsonToFile (const std::string & filename, bool pretty = false)
Definition at line 2337 of file VortexLib.cpp.
{
  std::ofstream file(filename);
  if (!file.is_open()) {
    return false;
  }
  std::string jsonStr = printJson(pretty);
  if (!jsonStr.length()) {
    return false;
  }
  file << jsonStr;
  file.close();
  return true;
}
References printJson().
Referenced by VortexCLI::cleanup().
printlog()
void Vortex::printlog (const char * file, const char * func, int line, const char * msg, va_list list)
Definition at line 1914 of file VortexLib.cpp.
{
  if (!Vortex::m_consoleHandle) {
    return;
  }
  string strMsg;
  if (file) {
    strMsg = file;
    if (strMsg.find_last_of('\\') != string::npos) {
      strMsg = strMsg.substr(strMsg.find_last_of('\\') + 1);
    }
    strMsg += ":";
    strMsg += to_string(line);
  }
  if (func) {
    strMsg += " ";
    strMsg += func;
    strMsg += "(): ";
  }
  strMsg += msg;
  strMsg += "\n";
  vfprintf(Vortex::m_consoleHandle, strMsg.c_str(), list);
#if LOG_TO_FILE == 1
  vfprintf(Vortex::m_logHandle, strMsg.c_str(), list);
#endif
}
References m_consoleHandle.
printModeJson()
std::string Vortex::printModeJson (bool pretty = false)
Definition at line 2247 of file VortexLib.cpp.
{
  std::string jsonStr = "{}";
  Mode *cur = m_engine.modes().curMode();
  if (!cur) {
    return jsonStr;
  }
  json modeJs = modeToJson(cur);
  return pretty ? modeJs.dump(4) : modeJs.dump();
}
References Modes::curMode(), m_engine, VortexEngine::modes(), and modeToJson().
printPatternJson()
std::string Vortex::printPatternJson (LedPos pos, bool pretty = false)
Definition at line 2278 of file VortexLib.cpp.
{
  std::string jsonStr = "{}";
  Mode *cur = m_engine.modes().curMode();
  if (!cur) {
    return jsonStr;
  }
  Pattern *pat = cur->getPattern(pos);
  if (!pat) {
    return jsonStr;
  }
  json patternJs = patternToJson(pat);
  return pretty ? patternJs.dump(4) : patternJs.dump();
}
References Modes::curMode(), Mode::getPattern(), m_engine, VortexEngine::modes(), and patternToJson().
quitClick()
void Vortex::quitClick ()
Definition at line 1093 of file VortexLib.cpp.
{
  m_buttonEventQueue.push_back(VortexButtonEvent(0, EVENT_QUIT_CLICK));
}
References EVENT_QUIT_CLICK, and m_buttonEventQueue.
Referenced by doCommand().
rapidClick()
void Vortex::rapidClick (uint32_t amount = 3)
Definition at line 1061 of file VortexLib.cpp.
{
  // reusing the button index as the consecutive press amount
  m_buttonEventQueue.push_back(VortexButtonEvent(amount, EVENT_RAPID_CLICK));
}
References EVENT_RAPID_CLICK, and m_buttonEventQueue.
Referenced by handleNumber().
redo()
bool Vortex::redo ()
Definition at line 1694 of file VortexLib.cpp.
{
  if (!m_undoBuffer.size()) {
    return false;
  }
  // cannot undo further into history
  if (m_undoIndex > 0) {
    m_undoIndex--;
  }
  return applyUndo();
}
References applyUndo(), m_undoBuffer, and m_undoIndex.
releaseButton()
void Vortex::releaseButton (uint8_t buttonIndex = 0)
Definition at line 1039 of file VortexLib.cpp.
{
  if (!buttonIndex) {
    buttonIndex = m_selectedButton;
  }
  m_buttonsPressed &= ~(1 << buttonIndex);
}
References m_buttonsPressed, and m_selectedButton.
Referenced by doCommand().
saveModeToJson()
json Vortex::saveModeToJson ()
Definition at line 2130 of file VortexLib.cpp.
{
  json saveJson;
  Mode *cur = m_engine.modes().curMode();
  if (!cur) {
    return nullptr;
  }
  return modeToJson(cur);
}
References Modes::curMode(), m_engine, VortexEngine::modes(), and modeToJson().
Referenced by saveToJson().
saveToJson()
json Vortex::saveToJson ()
Definition at line 2170 of file VortexLib.cpp.
{
  json saveJson;
  saveJson["version_major"] = static_cast<uint8_t>(VORTEX_VERSION_MAJOR);
  saveJson["version_minor"] = static_cast<uint8_t>(VORTEX_VERSION_MINOR);
  saveJson["global_flags"] = m_engine.modes().globalFlags();
  saveJson["brightness"] = static_cast<uint8_t>(m_engine.leds().getBrightness());
  uint8_t numModes = m_engine.modes().numModes();
  saveJson["num_modes"] = numModes;
  json modesArray = json::array();
  m_engine.modes().setCurMode(0);
  for (uint8_t i = 0; i < numModes; ++i) {
    modesArray.push_back(saveModeToJson());
    m_engine.modes().nextMode();
  }
  saveJson["modes"] = modesArray;
  return saveJson;
}
References Leds::getBrightness(), VortexEngine::leds(), m_engine, VortexEngine::modes(), Modes::nextMode(), Modes::numModes(), numModes(), saveModeToJson(), Modes::setCurMode(), VORTEX_VERSION_MAJOR, and VORTEX_VERSION_MINOR.
Referenced by printJson().
selectButton()
void Vortex::selectButton (uint8_t buttonIndex)
Definition at line 966 of file VortexLib.cpp.
{
  if (buttonIndex >= m_engine.buttons().numButtons()) {
    return;
  }
  m_selectedButton = buttonIndex;
}
References VortexEngine::buttons(), m_engine, m_selectedButton, and Buttons::numButtons().
Referenced by handleNumber().
sendWait()
void Vortex::sendWait (uint32_t amount = 0)
Definition at line 1055 of file VortexLib.cpp.
{
  // reusing the button index as the wait amount
  m_buttonEventQueue.push_back(VortexButtonEvent(amount, EVENT_WAIT));
}
References EVENT_WAIT, and m_buttonEventQueue.
Referenced by doCommand().
setColorset()
bool Vortex::setColorset (LedPos pos, const Colorset & set, bool save = true)
Definition at line 1446 of file VortexLib.cpp.
{
  Mode *pMode = m_engine.modes().curMode();
  if (!pMode) {
    return false;
  }
  if (!pMode->setColorset(set, pos)) {
    return false;
  }
  pMode->init();
  return !save || doSave();
}
References Modes::curMode(), doSave(), Mode::init(), m_engine, VortexEngine::modes(), and Mode::setColorset().
Referenced by VortexCLI::init().
setCurMode()
bool Vortex::setCurMode (uint32_t index, bool save = true)
Definition at line 1334 of file VortexLib.cpp.
{
  if (index >= m_engine.modes().numModes()) {
    return true;
  }
  if (!m_engine.modes().setCurMode(index)) {
    return false;
  }
  return !save || doSave();
}
References doSave(), m_engine, VortexEngine::modes(), Modes::numModes(), and Modes::setCurMode().
setInstantTimestep()
void Vortex::setInstantTimestep (bool timestep)
Definition at line 960 of file VortexLib.cpp.
{
  m_engine.time().setInstantTimestep(timestep);
}
References m_engine, and VortexEngine::time().
Referenced by VortexCLI::init().
setLedCount()
uint8_t Vortex::setLedCount (uint8_t ledCount)
Definition at line 1250 of file VortexLib.cpp.
{
  // must change the 'leds' led count before changing a mode
  m_engine.leds().setLedCount(count);
  // if the current mdoe is instantiated then need to update it too
  if (m_engine.modes().curModeInstantiated()) {
    Mode *cur = m_engine.modes().curMode();
    if (cur && !cur->setLedCount(count)) {
      return false;
    }
  }
  return true;
}
References Modes::curMode(), Modes::curModeInstantiated(), VortexEngine::leds(), m_engine, VortexEngine::modes(), Leds::setLedCount(), and Mode::setLedCount().
Referenced by VortexCLI::init(), and matchLedCount().
setLockEnabled()
void Vortex::setLockEnabled (bool enable) [inline]
Definition at line 279 of file VortexLib.h.
{ m_lockEnabled = enable; }
References m_lockEnabled.
Referenced by VortexCLI::init().
setMenuDemoMode()
bool Vortex::setMenuDemoMode (const Mode * mode)
Definition at line 1076 of file VortexLib.cpp.
{
  if (!mode) {
     return false;
  }
  Menu *pMenu = m_engine.menus().curMenu();
  if (!pMenu) {
    return false;
  }
  if (!mode->getLedCount() || pMenu->m_previewMode.equals(mode)) {
    return false;
  }
  pMenu->m_previewMode = *mode;
  pMenu->m_previewMode.init();
  return true;
}
References Menus::curMenu(), Mode::equals(), Mode::getLedCount(), Mode::init(), m_engine, Menu::m_previewMode, and VortexEngine::menus().
setMenuTargetLeds()
void Vortex::setMenuTargetLeds (LedMap targetLeds)
Definition at line 1173 of file VortexLib.cpp.
{
  Menu *cur = m_engine.menus().curMenu();
  if (!cur) {
    return;
  }
  cur->setTargetLeds(targetLeds);
}
References Menus::curMenu(), m_engine, VortexEngine::menus(), and Menu::setTargetLeds().
setModes()
bool Vortex::setModes (ByteStream & stream, bool save = true)
Definition at line 1199 of file VortexLib.cpp.
{
  m_engine.modes().clearModes();
  // now unserialize the stream of data that was read
  if (!m_engine.modes().loadFromBuffer(stream)) {
    return false;
  }
  return !save || doSave();
}
References Modes::clearModes(), doSave(), Modes::loadFromBuffer(), m_engine, and VortexEngine::modes().
Referenced by applyUndo(), and VortexCLI::init().
setPattern()
bool Vortex::setPattern (PatternID id, const PatternArgs * args = nullptr, const Colorset * set = nullptr, bool save = true)
Definition at line 1375 of file VortexLib.cpp.
{
  Mode *pMode = m_engine.modes().curMode();
  if (!pMode) {
    return false;
  }
  if (!pMode->setPattern(id, LED_ANY, args, set)) {
    return false;
  }
  pMode->init();
  return !save || doSave();
}
References Modes::curMode(), doSave(), Mode::init(), LED_ANY, m_engine, VortexEngine::modes(), and Mode::setPattern().
setPatternArgs()
bool Vortex::setPatternArgs (LedPos pos, PatternArgs & args, bool save = true)
Definition at line 1473 of file VortexLib.cpp.
{
  Mode *pMode = m_engine.modes().curMode();
  if (!pMode) {
    return false;
  }
  Pattern *pat = nullptr;
  // Equivalent to cases LED_ANY, LED_ALL and LED_MULTI
  if (pos == LED_ANY || pos == LED_ALL || pos == LED_MULTI) {
#if VORTEX_SLIM == 0
    pat = pMode->getPattern(LED_MULTI);
    if (pat) {
      pat->setArgs(args);
    }
    if (pos == LED_MULTI) {
      // don't fallthrough if actually multi, it's possible
      // we got here by falling through from LED_ALL
      pMode->init();
      return !save || doSave();
    }
    // fall through if LED_ALL and change the single leds
    else if (pos == LED_ANY || pos == LED_ALL) {
      for (LedPos pos = LED_FIRST; pos < LED_COUNT; ++pos) {
        pat = pMode->getPattern(pos);
        if (pat) {
          pat->setArgs(args);
        }
      }
      pMode->init();
      // actually break here
      return !save || doSave();
    }
#endif
  }
  // equivalent to case LED_ALL_SINGLE
  else if (pos == LED_ALL_SINGLE) {
    for (LedPos pos = LED_FIRST; pos < LED_COUNT; ++pos) {
      pat = pMode->getPattern(pos);
      if (pat) {
        pat->setArgs(args);
      }
    }
    pMode->init();
    // actually break here
    return !save || doSave();
  }
  // equivalent to default case (covers any other pos)
  else {
    if (pos >= LED_COUNT) {
      return false;
    }
    pat = pMode->getPattern(pos);
    if (!pat) {
      return false;
    }
    pat->setArgs(args);
    pMode->init();
    return !save || doSave();
  }
  return false;
}
References Modes::curMode(), doSave(), Mode::getPattern(), Mode::init(), LED_ALL, LED_ALL_SINGLE, LED_ANY, LED_COUNT, LED_FIRST, LED_MULTI, m_engine, VortexEngine::modes(), and Pattern::setArgs().
Referenced by VortexCLI::init().
setPatternAt()
bool Vortex::setPatternAt (LedPos pos, PatternID id, const PatternArgs * args = nullptr, const Colorset * set = nullptr, bool save = true)
Definition at line 1422 of file VortexLib.cpp.
{
  Mode *pMode = m_engine.modes().curMode();
  if (!pMode) {
    return false;
  }
  if (!pMode->setPattern(id, pos, args, set)) {
    return false;
  }
  pMode->init();
  return !save || doSave();
}
References Modes::curMode(), doSave(), Mode::init(), m_engine, VortexEngine::modes(), and Mode::setPattern().
Referenced by VortexCLI::init().
setSleepEnabled()
void Vortex::setSleepEnabled (bool enable)
Definition at line 908 of file VortexLib.cpp.
{
  m_sleepEnabled = enable;
}
References m_sleepEnabled.
Referenced by VortexCLI::init().
setStorageFilename()
void Vortex::setStorageFilename (const std::string & name)
Definition at line 1941 of file VortexLib.cpp.
{
  m_engine.storage().setStorageFilename(name);
}
References m_engine, and VortexEngine::storage().
Referenced by VortexCLI::init().
setTickrate()
void Vortex::setTickrate (uint32_t tickrate)
Definition at line 1706 of file VortexLib.cpp.
{
  m_engine.time().setTickrate(tickrate);
}
References m_engine, Time::setTickrate(), and VortexEngine::time().
setUndoBufferLimit()
void Vortex::setUndoBufferLimit (uint32_t limit)
Definition at line 1605 of file VortexLib.cpp.
{
  m_undoLimit = limit;
}
References m_undoLimit.
shiftCurMode()
bool Vortex::shiftCurMode (int8_t offset, bool save = true)
Definition at line 1363 of file VortexLib.cpp.
{
  if (!m_engine.modes().numModes()) {
    return true;
  }
  if (offset == 0) {
    return true;
  }
  m_engine.modes().shiftCurMode(offset);
  return !save || doSave();
}
References doSave(), m_engine, VortexEngine::modes(), Modes::numModes(), and Modes::shiftCurMode().
shortClick()
void Vortex::shortClick (uint8_t buttonIndex = 0)
Definition at line 975 of file VortexLib.cpp.
{
  if (!buttonIndex) {
    buttonIndex = m_selectedButton;
  }
  m_buttonEventQueue.push_back(VortexButtonEvent(buttonIndex, EVENT_SHORT_CLICK));
}
References EVENT_SHORT_CLICK, m_buttonEventQueue, and m_selectedButton.
Referenced by doCommand().
sleepClick()
void Vortex::sleepClick (uint8_t buttonIndex = 0)
Definition at line 1015 of file VortexLib.cpp.
{
  if (!buttonIndex) {
    buttonIndex = m_selectedButton;
  }
  m_buttonEventQueue.push_back(VortexButtonEvent(buttonIndex, EVENT_SLEEP_CLICK));
}
References EVENT_SLEEP_CLICK, m_buttonEventQueue, and m_selectedButton.
Referenced by doCommand().
sleepEnabled()
bool Vortex::sleepEnabled ()
Definition at line 913 of file VortexLib.cpp.
{
  return m_sleepEnabled;
}
References m_sleepEnabled.
Referenced by VortexEngine::tick().
storageEnabled()
bool Vortex::storageEnabled () [inline]
Definition at line 272 of file VortexLib.h.
{ return m_storageEnabled; }
References m_storageEnabled.
Referenced by Storage::init(), Storage::read(), and Storage::write().
stringToPattern()
PatternID Vortex::stringToPattern (const std::string & pattern)
Definition at line 1562 of file VortexLib.cpp.
{
  static map<string, PatternID> cachedNames;
  if (cachedNames.empty()) {
    for (PatternID i = PATTERN_FIRST; i < PATTERN_COUNT; ++i) {
      cachedNames[patternNames[i]] = (PatternID)i;
    }
  }
  // lowercase the name and look it up
  string lowerPat = pattern;
  transform(lowerPat.begin(), lowerPat.end(), lowerPat.begin(), [](unsigned char c) { return tolower(c); });
  if (cachedNames.find(pattern) == cachedNames.end()) {
    return PATTERN_NONE;
  }
  return cachedNames[pattern];
}
References PATTERN_COUNT, PATTERN_FIRST, PATTERN_NONE, and patternNames.
Referenced by VortexCLI::init().
tick()
bool Vortex::tick ()
Definition at line 929 of file VortexLib.cpp.
{
  if (!m_initialized) {
    // do not cleanup prematurely here
    return false;
  }
  // use ioctl to determine how many characters are on stdin so that
  // we don't call getchar() too many times and accidentally block
  uint32_t numInputs = getNumInputs();
  if (m_lockstepEnabled && !numInputs) {
    // don't tick till we have input
    return true;
  }
  // iterate the number of inputs on stdin and parse each letter
  // into a command for the engine, this will inject all of the commands
  // that are available into the engine but that doesn't necessarily
  // mean that the engine will do anything with them right away
  for (uint32_t i = 0; i < numInputs; ++i) {
    doCommand(getchar());
  }
  // tick the vortex engine forward
  m_engine.tick();
  return true;
}
References doCommand(), getNumInputs(), m_engine, m_initialized, m_lockstepEnabled, and VortexEngine::tick().
Referenced by VortexCLI::run().
undo()
bool Vortex::undo ()
Definition at line 1679 of file VortexLib.cpp.
{
  if (!m_undoBuffer.size()) {
    return false;
  }
  uint32_t highestIndex = (uint32_t)m_undoBuffer.size() - 1;
  // cannot undo further into history
  if (m_undoIndex > highestIndex) {
    m_undoIndex = highestIndex;
  } else {
    m_undoIndex++;
  }
  return applyUndo();
}
References applyUndo(), m_undoBuffer, and m_undoIndex.
vcallbacks()
VortexCallbacks* Vortex::vcallbacks () [inline]
Definition at line 244 of file VortexLib.h.
{ return m_storedCallbacks; }
References m_storedCallbacks.
Referenced by Button::check(), SerialComs::checkSerial(), SerialComs::dataReady(), Leds::init(), SerialComs::read(), IRSender::sendMark(), VLSender::sendMark(), IRSender::sendSpace(), VLSender::sendSpace(), Leds::setLedCount(), Leds::update(), and SerialComs::write().
VLDeliver()
void Vortex::VLDeliver (uint32_t timing)
Definition at line 1105 of file VortexLib.cpp.
{
#if VL_ENABLE_RECEIVER == 1
  m_engine.vlReceiver().handleVLTiming(timing);
#endif
}
References VLReceiver::handleVLTiming(), m_engine, and VortexEngine::vlReceiver().
Friends And Related Function Documentation
Buttons
friend class Buttons [friend]
Definition at line 328 of file VortexLib.h.
Member Data Documentation
m_buttonEventQueue
std::deque<VortexButtonEvent> Vortex::m_buttonEventQueue [private]
Definition at line 406 of file VortexLib.h.
Referenced by advMenuEnterClick(), deleteColClick(), forceSleepClick(), handleInputQueue(), longClick(), menuEnterClick(), quitClick(), rapidClick(), sendWait(), shortClick(), and sleepClick().
m_buttonsPressed
uint32_t Vortex::m_buttonsPressed [private]
Definition at line 411 of file VortexLib.h.
Referenced by isButtonPressed(), pressButton(), and releaseButton().
m_commandLog
std::string Vortex::m_commandLog [private]
Definition at line 415 of file VortexLib.h.
Referenced by clearCommandLog(), doCommand(), getCommandLog(), and handleNumber().
m_commandLogEnabled
bool Vortex::m_commandLogEnabled [private]
Definition at line 417 of file VortexLib.h.
Referenced by enableCommandLog().
m_consoleHandle
FILE* Vortex::m_consoleHandle [private]
Definition at line 396 of file VortexLib.h.
Referenced by init(), and printlog().
m_engine
VortexEngine Vortex::m_engine [private]
Definition at line 384 of file VortexLib.h.
Referenced by addMenuTargetLeds(), addMode(), addNewMode(), checkLedCount(), cleanup(), clearMenuTargetLeds(), curModeIndex(), delCurMode(), doSave(), engine(), enterSleep(), getColorset(), getCurMode(), getCustomParams(), getLedCount(), getMenuDemoMode(), getModeName(), getModes(), getPatternArgs(), getPatternID(), getPatternName(), getStorageFilename(), getStorageStats(), getTickrate(), handleInputQueue(), init(), IRDeliver(), isCurModeMulti(), isSleeping(), loadFromJson(), loadModeFromJson(), loadStorage(), modeFromJson(), nextMode(), numCustomParams(), numLedsInMode(), numModes(), openColorSelect(), openEditorConnection(), openFactoryReset(), openGlobalBrightness(), openModeSharing(), openPatternSelect(), openRandomizer(), parseModeJson(), parsePatternJson(), patternFromJson(), printModeJson(), printPatternJson(), saveModeToJson(), saveToJson(), selectButton(), setColorset(), setCurMode(), setInstantTimestep(), setLedCount(), setMenuDemoMode(), setMenuTargetLeds(), setModes(), setPattern(), setPatternArgs(), setPatternAt(), setStorageFilename(), setTickrate(), shiftCurMode(), tick(), and VLDeliver().
m_initialized
bool Vortex::m_initialized [private]
Definition at line 408 of file VortexLib.h.
Referenced by cleanup(), handleInputQueue(), init(), and tick().
m_lastCommand
char Vortex::m_lastCommand [private]
Definition at line 427 of file VortexLib.h.
Referenced by doCommand(), and handleNumber().
m_lockEnabled
bool Vortex::m_lockEnabled [private]
Definition at line 425 of file VortexLib.h.
Referenced by lockEnabled(), and setLockEnabled().
m_lockstepEnabled
bool Vortex::m_lockstepEnabled [private]
Definition at line 419 of file VortexLib.h.
Referenced by enableLockstep(), isLockstep(), and tick().
m_randCtx
Random Vortex::m_randCtx [private]
Definition at line 429 of file VortexLib.h.
Referenced by addNewMode(), and Vortex().
m_selectedButton
uint8_t Vortex::m_selectedButton [private]
Definition at line 413 of file VortexLib.h.
Referenced by advMenuEnterClick(), deleteColClick(), forceSleepClick(), isButtonPressed(), longClick(), menuEnterClick(), pressButton(), releaseButton(), selectButton(), shortClick(), and sleepClick().
m_sleepEnabled
bool Vortex::m_sleepEnabled [private]
Definition at line 423 of file VortexLib.h.
Referenced by setSleepEnabled(), and sleepEnabled().
m_storageEnabled
bool Vortex::m_storageEnabled [private]
Definition at line 421 of file VortexLib.h.
Referenced by enableStorage(), and storageEnabled().
m_storedCallbacks
VortexCallbacks* Vortex::m_storedCallbacks [private]
Definition at line 394 of file VortexLib.h.
Referenced by cleanup(), init(), installCallbacks(), vcallbacks(), and Vortex().
m_undoBuffer
std::deque<ByteStream> Vortex::m_undoBuffer [private]
Definition at line 386 of file VortexLib.h.
Referenced by addUndoBuffer(), applyUndo(), redo(), and undo().
m_undoEnabled
bool Vortex::m_undoEnabled [private]
Definition at line 392 of file VortexLib.h.
Referenced by addUndoBuffer(), and enableUndo().
m_undoIndex
uint32_t Vortex::m_undoIndex [private]
Definition at line 390 of file VortexLib.h.
Referenced by addUndoBuffer(), applyUndo(), redo(), and undo().
m_undoLimit
uint32_t Vortex::m_undoLimit [private]
Definition at line 388 of file VortexLib.h.
Referenced by addUndoBuffer(), and setUndoBufferLimit().
The documentation for this class was generated from the following files:
VortexEngine/VortexLib/VortexLib.h
VortexEngine/VortexLib/VortexLib.cpp