VLReceiver Class Reference
#include <VLReceiver.h>
Static Public Member Functions
static bool init ()
static void cleanup ()
static bool dataReady ()
static bool isReceiving ()
static uint8_t percentReceived ()
static uint16_t bytesReceived ()
static bool receiveMode (Mode *pMode)
static bool beginReceiving ()
static bool endReceiving ()
static bool onNewData ()
static void resetVLState ()
static void recvPCIHandler ()
Private Types
enum RecvState : uint8_t { WAITING_HEADER_MARK
, WAITING_HEADER_SPACE
, READING_DATA_MARK
, READING_DATA_SPACE
 }
Private Member Functions
VLReceiver ()
Static Private Member Functions
static bool read (ByteStream &data)
static void handleVLTiming (uint32_t diff)
Static Private Attributes
static BitStream m_vlData
static RecvState m_recvState = WAITING_HEADER_MARK
static uint32_t m_prevTime = 0
static uint8_t m_pinState = 0
static uint32_t m_previousBytes = 0
Detailed Description
Definition at line 15 of file VLReceiver.h.
Member Enumeration Documentation
RecvState
enum VLReceiver::RecvState : uint8_t [private]
Enumerator
WAITING_HEADER_MARK
WAITING_HEADER_SPACE
READING_DATA_MARK
READING_DATA_SPACE
Definition at line 59 of file VLReceiver.h.
  {
    WAITING_HEADER_MARK,
    WAITING_HEADER_SPACE,
    READING_DATA_MARK,
    READING_DATA_SPACE
  };
Constructor & Destructor Documentation
VLReceiver()
VLReceiver::VLReceiver () [private]
Member Function Documentation
beginReceiving()
bool VLReceiver::beginReceiving () [static]
Definition at line 132 of file VLReceiver.cpp.
{
#ifdef VORTEX_EMBEDDED
  // Set up the ADC
  // sample campacitance, VDD reference, prescaler division
  // Options are:
  // 0x0 DIV2 CLK_PER divided by 2 > works
  // 0x1 DIV4 CLK_PER divided by 4 > works
  // 0x2 DIV8 CLK_PER divided by 8 > works
  // 0x3 DIV16 CLK_PER divided by 16 > works
  // 0x4 DIV32 CLK_PER divided by 32 > doesn't work
  // 0x5 DIV64 CLK_PER divided by 64 > doesn't work
  // 0x6 DIV128 CLK_PER divided by 128 > doesn't work
  // 0x7 DIV256 CLK_PER divided by 256 > doesn't work
#if (F_CPU == 20000000)
  ADC0.CTRLC = ADC_SAMPCAP_bm | ADC_REFSEL_VDDREF_gc | ADC_PRESC_DIV2_gc;
#else
  ADC0.CTRLC = ADC_SAMPCAP_bm | ADC_REFSEL_VDDREF_gc | ADC_PRESC_DIV2_gc;
#endif
  // no sampling delay and no delay variation
  ADC0.CTRLD = 0;
  // sample length
  // 0 = doesn't work
  // 1+ = works
  ADC0.SAMPCTRL = 1;
  // Select the analog pin input PB1 (AIN10)
  ADC0.MUXPOS = ADC_MUXPOS_AIN10_gc;
  // Initialize the Window Comparator Mode in above
  ADC0.CTRLE = ADC_WINCM_ABOVE_gc;
  // Set the threshold value very low
  ADC0.WINHT = 0x1;
  ADC0.WINLT = 0;
  // set sampling amount
  // 0x0 NONE No accumulation > doesn't work
  // 0x1 ACC2 2 results accumulated > doesn't work
  // 0x2 ACC4 4 results accumulated > works okay
  // 0x3 ACC8 8 results accumulated > works decent
  // 0x4 ACC16 16 results accumulated > works very well
  // 0x5 ACC32 32 results accumulated > works best
  // 0x6 ACC64 64 results accumulated > doesn't work
  ADC0.CTRLB = SAMPLE_COUNT;
  // Enable Window Comparator interrupt
  ADC0.INTCTRL = ADC_WCMP_bm;
  // Enable the ADC and start continuous conversions
  ADC0.CTRLA = ADC_ENABLE_bm | ADC_FREERUN_bm;
  // start the first conversion
  ADC0.COMMAND = ADC_STCONV_bm;
#endif
  resetVLState();
  return true;
}
References resetVLState(), and SAMPLE_COUNT.
Referenced by ModeSharing::beginReceiving().
bytesReceived()
static uint16_t VLReceiver::bytesReceived () [inline], [static]
Definition at line 30 of file VLReceiver.h.
{ return m_vlData.bytepos(); }
References BitStream::bytepos(), and m_vlData.
Referenced by onNewData().
cleanup()
void VLReceiver::cleanup () [static]
Definition at line 72 of file VLReceiver.cpp.
{
}
Referenced by VortexEngine::cleanup().
dataReady()
bool VLReceiver::dataReady () [static]
Definition at line 76 of file VLReceiver.cpp.
{
  // is the receiver actually receiving data?
  if (!isReceiving()) {
    return false;
  }
  uint8_t blocks = m_vlData.data()[0];
  uint8_t remainder = m_vlData.data()[1];
  uint32_t total = ((blocks - 1) * 32) + remainder;
  if (!total || total > VL_MAX_DATA_TRANSFER) {
    DEBUG_LOGF("Bad VL Data size: %u", total);
    return false;
  }
  // if there are size + 2 bytes in the VLData receiver
  // then a full message is ready, the + 2 is from the
  // two bytes for blocks + remainder that are sent first
  return (m_vlData.bytepos() >= (uint32_t)(total + 2));
}
References BitStream::bytepos(), BitStream::data(), DEBUG_LOGF, isReceiving(), m_vlData, and VL_MAX_DATA_TRANSFER.
Referenced by ModeSharing::receiveMode().
endReceiving()
bool VLReceiver::endReceiving () [static]
Definition at line 184 of file VLReceiver.cpp.
{
#ifdef VORTEX_EMBEDDED
  // Stop conversions and disable the ADC
  ADC0.CTRLA &= ~(ADC_ENABLE_bm | ADC_FREERUN_bm);
  ADC0.INTCTRL = 0;
#endif
  resetVLState();
  return true;
}
References resetVLState().
Referenced by ModeSharing::onShortClick().
handleVLTiming()
void VLReceiver::handleVLTiming (uint32_t diff) [static], [private]
Definition at line 253 of file VLReceiver.cpp.
{
  // if the diff is too long or too short then it's not useful
  if ((diff > VL_HEADER_MARK_MAX && m_recvState < READING_DATA_MARK) || diff < VL_TIMING_MIN) {
    DEBUG_LOGF("bad delay: %u, resetting...", diff);
    resetVLState();
    return;
  }
  switch (m_recvState) {
  case WAITING_HEADER_MARK: // initial state
    if (diff >= VL_HEADER_SPACE_MIN && diff <= VL_HEADER_MARK_MAX) {
      m_recvState = WAITING_HEADER_SPACE;
    } else {
      DEBUG_LOGF("Bad header mark %u, resetting...", diff);
      resetVLState();
    }
    break;
  case WAITING_HEADER_SPACE:
    if (diff >= VL_HEADER_SPACE_MIN && diff <= VL_HEADER_MARK_MAX) {
      m_recvState = READING_DATA_MARK;
    } else {
      DEBUG_LOGF("Bad header space %u, resetting...", diff);
      resetVLState();
    }
    break;
  case READING_DATA_MARK:
    // classify mark/space based on the timing and write into buffer
    m_vlData.write1Bit((diff > (VL_TIMING * 2)) ? 1 : 0);
    m_recvState = READING_DATA_SPACE;
    break;
  case READING_DATA_SPACE:
    // the space could be just a regular space, or a gap in between blocks
    m_recvState = READING_DATA_MARK;
    break;
  default: // ??
    DEBUG_LOGF("Bad receive state: %u", m_recvState);
    break;
  }
}
References DEBUG_LOGF, m_recvState, m_vlData, READING_DATA_MARK, READING_DATA_SPACE, resetVLState(), VL_HEADER_MARK_MAX, VL_HEADER_SPACE_MIN, VL_TIMING, VL_TIMING_MIN, WAITING_HEADER_MARK, WAITING_HEADER_SPACE, and BitStream::write1Bit().
Referenced by recvPCIHandler(), and Vortex::VLDeliver().
init()
bool VLReceiver::init () [static]
Definition at line 62 of file VLReceiver.cpp.
{
#ifdef VORTEX_EMBEDDED
  // Disable digital input buffer on the pin to save power
  PORTB.PIN1CTRL &= ~PORT_ISC_gm;
  PORTB.PIN1CTRL |= PORT_ISC_INPUT_DISABLE_gc;
#endif
  return m_vlData.init(VL_RECV_BUF_SIZE);
}
References BitStream::init(), m_vlData, and VL_RECV_BUF_SIZE.
Referenced by VortexEngine::init().
isReceiving()
bool VLReceiver::isReceiving () [static]
Definition at line 96 of file VLReceiver.cpp.
{
  // if there are at least 2 bytes in the data buffer then
  // the receiver is receiving a packet. If there is less
  // than 2 bytes then we're still waiting for the 'blocks'
  // and 'remainder' bytes which prefix a packet
  return (m_vlData.bytepos() > 2);
}
References BitStream::bytepos(), and m_vlData.
Referenced by dataReady(), percentReceived(), and ModeSharing::showReceiveMode().
onNewData()
bool VLReceiver::onNewData () [static]
Definition at line 195 of file VLReceiver.cpp.
{
  if (bytesReceived() == m_previousBytes) {
    return false;
  }
  m_previousBytes = bytesReceived();
  return true;
}
References bytesReceived(), and m_previousBytes.
Referenced by ModeSharing::receiveMode().
percentReceived()
uint8_t VLReceiver::percentReceived () [static]
Definition at line 106 of file VLReceiver.cpp.
{
  if (!isReceiving()) {
    return 0;
  }
  uint8_t blocks = m_vlData.data()[0];
  uint8_t remainder = m_vlData.data()[1];
  uint16_t total = ((blocks - 1) * 32) + remainder;
  // round by adding half of the total to the numerator
  return (uint8_t)((uint16_t)((m_vlData.bytepos() * 100 + (total / 2)) / total));
}
References BitStream::bytepos(), BitStream::data(), isReceiving(), and m_vlData.
Referenced by ModeSharing::showReceiveMode().
read()
bool VLReceiver::read (ByteStream & data) [static], [private]
Definition at line 204 of file VLReceiver.cpp.
{
  if (!m_vlData.bytepos() || m_vlData.bytepos() > VL_MAX_DATA_TRANSFER) {
    DEBUG_LOG("Nothing to read, or read too much");
    return false;
  }
  // read the size out (blocks + remainder)
  uint8_t blocks = m_vlData.data()[0];
  uint8_t remainder = m_vlData.data()[1];
  // calculate size from blocks + remainder
  uint32_t size = ((blocks - 1) * 32) + remainder;
  if (!size || size > VL_MAX_DATA_TRANSFER) {
    DEBUG_LOGF("Bad VL Data size: %u", size);
    return false;
  }
  // the actual data starts 2 bytes later because of the size byte
  const uint8_t *actualData = m_vlData.data() + 2;
  if (!data.rawInit(actualData, size)) {
    DEBUG_LOG("Failed to init buffer for VL read");
    return false;
  }
  // reset the VL state and receive buffer now
  resetVLState();
  return true;
}
References BitStream::bytepos(), BitStream::data(), DEBUG_LOG, DEBUG_LOGF, m_vlData, ByteStream::rawInit(), resetVLState(), and VL_MAX_DATA_TRANSFER.
Referenced by receiveMode().
receiveMode()
bool VLReceiver::receiveMode (Mode * pMode) [static]
Definition at line 118 of file VLReceiver.cpp.
{
  ByteStream buf;
  // read from the receive buffer into the byte stream
  if (!read(buf)) {
    // no data to read right now, or an error
    DEBUG_LOG("No data available to read, or error reading");
    return false;
  }
  DEBUG_LOGF("Received %u bytes", buf.rawSize());
  // load the data into the target mode
  return pMode->loadFromBuffer(buf);
}
References DEBUG_LOG, DEBUG_LOGF, Mode::loadFromBuffer(), ByteStream::rawSize(), and read().
Referenced by ModeSharing::receiveMode().
recvPCIHandler()
void VLReceiver::recvPCIHandler () [static]
Definition at line 231 of file VLReceiver.cpp.
{
  // toggle the tracked pin state no matter what
  m_pinState = (uint8_t)!m_pinState;
  // grab current time
  uint32_t now = Time::microseconds();
  // check previous time for validity
  if (!m_prevTime || m_prevTime > now) {
    m_prevTime = now;
    DEBUG_LOG("Bad first time diff, resetting...");
    resetVLState();
    return;
  }
  // calc time difference between previous change and now
  uint32_t diff = (uint32_t)(now - m_prevTime);
  // and update the previous changetime for next loop
  m_prevTime = now;
  // handle the bliank duration and process it
  handleVLTiming(diff);
}
References DEBUG_LOG, handleVLTiming(), m_pinState, m_prevTime, Time::microseconds(), and resetVLState().
Referenced by ISR().
resetVLState()
void VLReceiver::resetVLState () [static]
Definition at line 293 of file VLReceiver.cpp.
{
  m_previousBytes = 0;
  m_recvState = WAITING_HEADER_MARK;
  // zero out the receive buffer and reset bit receiver position
  m_vlData.reset();
#ifdef VORTEX_EMBEDDED
  // reset the threshold to a high value so that it can be pulled down again
  threshold = THRESHOLD_BEGIN;
#endif
  DEBUG_LOG("VL State Reset");
}
References DEBUG_LOG, m_previousBytes, m_recvState, m_vlData, BitStream::reset(), threshold, THRESHOLD_BEGIN, and WAITING_HEADER_MARK.
Referenced by beginReceiving(), endReceiving(), handleVLTiming(), read(), ModeSharing::receiveMode(), and recvPCIHandler().
Member Data Documentation
m_pinState
uint8_t VLReceiver::m_pinState = 0 [static], [private]
Definition at line 71 of file VLReceiver.h.
Referenced by recvPCIHandler().
m_previousBytes
uint32_t VLReceiver::m_previousBytes = 0 [static], [private]
Definition at line 74 of file VLReceiver.h.
Referenced by onNewData(), and resetVLState().
m_prevTime
uint32_t VLReceiver::m_prevTime = 0 [static], [private]
Definition at line 70 of file VLReceiver.h.
Referenced by recvPCIHandler().
m_recvState
VLReceiver::RecvState VLReceiver::m_recvState = WAITING_HEADER_MARK [static], [private]
Definition at line 68 of file VLReceiver.h.
Referenced by handleVLTiming(), and resetVLState().
m_vlData
BitStream VLReceiver::m_vlData [static], [private]
Definition at line 56 of file VLReceiver.h.
Referenced by bytesReceived(), dataReady(), handleVLTiming(), init(), isReceiving(), percentReceived(), read(), and resetVLState().
The documentation for this class was generated from the following files:
VortexEngine/src/Wireless/VLReceiver.h
VortexEngine/src/Wireless/VLReceiver.cpp