ColorsetMap Class Reference
#include <Sequence.h>
Public Member Functions
ColorsetMap (VortexEngine &engine)
ColorsetMap (VortexEngine &engine, const Colorset &colorset, LedMap positions)
ColorsetMap (VortexEngine &engine, const ColorsetMap &other)
void operator= (const ColorsetMap &other)
bool operator== (const ColorsetMap &other) const
bool operator!= (const ColorsetMap &other) const
void setColorsetAt (const Colorset &colorset, LedMap positions)
const Colorset & operator[] (LedPos index) const
bool serialize (ByteStream &buffer) const
bool unserialize (ByteStream &buffer)
Public Attributes
VortexEngine & m_engine
std::vector< Colorset > m_colorsets
Detailed Description
Definition at line 43 of file Sequence.h.
Constructor & Destructor Documentation
ColorsetMap() [1/3]
ColorsetMap::ColorsetMap (VortexEngine & engine)
Definition at line 88 of file Sequence.cpp.
                                             :
  m_engine(engine),
  m_colorsets()
{
}
ColorsetMap() [2/3]
ColorsetMap::ColorsetMap (VortexEngine & engine, const Colorset & colorset, LedMap positions)
Definition at line 94 of file Sequence.cpp.
                                                                                         :
  ColorsetMap(engine)
{
  setColorsetAt(colorset, positions);
}
References setColorsetAt().
ColorsetMap() [3/3]
ColorsetMap::ColorsetMap (VortexEngine & engine, const ColorsetMap & other)
Definition at line 100 of file Sequence.cpp.
                                                                       :
  ColorsetMap(engine)
{
  *this = other;
}
Member Function Documentation
operator!=()
bool ColorsetMap::operator!= (const ColorsetMap & other) const
Definition at line 116 of file Sequence.cpp.
{
  return !(*this == other);
}
operator=()
void ColorsetMap::operator= (const ColorsetMap & other)
Definition at line 106 of file Sequence.cpp.
{
  m_colorsets = other.m_colorsets;
}
References m_colorsets.
operator==()
bool ColorsetMap::operator== (const ColorsetMap & other) const
Definition at line 111 of file Sequence.cpp.
{
  return m_colorsets == other.m_colorsets;
}
References m_colorsets.
operator[]()
const Colorset & ColorsetMap::operator[] (LedPos index) const
Definition at line 130 of file Sequence.cpp.
{
  return m_colorsets[index];
}
References m_colorsets.
serialize()
bool ColorsetMap::serialize (ByteStream & buffer) const
Definition at line 135 of file Sequence.cpp.
{
  for (LedPos i = LED_FIRST; i < LED_COUNT; ++i) {
    if (!m_colorsets[i].serialize(buffer)) {
      return false;
    }
  }
  return true;
}
References LED_COUNT, LED_FIRST, and m_colorsets.
Referenced by SequenceStep::serialize().
setColorsetAt()
void ColorsetMap::setColorsetAt (const Colorset & colorset, LedMap positions)
Definition at line 122 of file Sequence.cpp.
{
  for (LedPos pos = LED_FIRST; pos < LED_COUNT; ++pos) {
    if (m_engine.leds().ledmapCheckLed(positions, pos)) {
      m_colorsets[pos] = colorset;
    }
  }
}
References LED_COUNT, LED_FIRST, Leds::ledmapCheckLed(), VortexEngine::leds(), m_colorsets, and m_engine.
Referenced by ColorsetMap().
unserialize()
bool ColorsetMap::unserialize (ByteStream & buffer)
Definition at line 145 of file Sequence.cpp.
{
  for (LedPos i = LED_FIRST; i < LED_COUNT; ++i) {
    if (!m_colorsets[i].unserialize(buffer)) {
      return false;
    }
  }
  return true;
}
References LED_COUNT, LED_FIRST, and m_colorsets.
Referenced by SequenceStep::unserialize().
Member Data Documentation
m_colorsets
std::vector<Colorset> ColorsetMap::m_colorsets
Definition at line 66 of file Sequence.h.
Referenced by operator=(), operator==(), operator[](), SequencedPattern::playSequenceStep(), serialize(), setColorsetAt(), and unserialize().
m_engine
VortexEngine& ColorsetMap::m_engine
Definition at line 63 of file Sequence.h.
Referenced by setColorsetAt().
The documentation for this class was generated from the following files:
VortexEngine/src/Patterns/Multi/Sequencer/Sequence.h
VortexEngine/src/Patterns/Multi/Sequencer/Sequence.cpp