CrossDopsPattern Class Reference
#include <CrossDopsPattern.h>
Public Member Functions
CrossDopsPattern (VortexEngine &engine, const PatternArgs &args)
virtual ~CrossDopsPattern ()
virtual void init () override
Protected Member Functions
virtual void blinkOn () override
virtual void poststep () override
Private Attributes
LedMap m_ledMap
Additional Inherited Members
Detailed Description
Definition at line 8 of file CrossDopsPattern.h.
Constructor & Destructor Documentation
CrossDopsPattern()
CrossDopsPattern::CrossDopsPattern (VortexEngine & engine, const PatternArgs & args)
Definition at line 7 of file CrossDopsPattern.cpp.
                                                                                :
  BlinkStepPattern(engine, args),
  m_ledMap(0)
{
  m_patternID = PATTERN_CROSSDOPS;
  setArgs(args);
}
References Pattern::m_patternID, PATTERN_CROSSDOPS, and Pattern::setArgs().
 CrossDopsPattern()
CrossDopsPattern::~CrossDopsPattern () [virtual]
Definition at line 15 of file CrossDopsPattern.cpp.
{
}
Member Function Documentation
blinkOn()
void CrossDopsPattern::blinkOn () [override], [protected], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 29 of file CrossDopsPattern.cpp.
{
  // set the current color on all the given leds
  m_engine.leds().setMap(m_ledMap, m_colorset.cur());
}
References Colorset::cur(), VortexEngine::leds(), Pattern::m_colorset, Pattern::m_engine, m_ledMap, and Leds::setMap().
init()
void CrossDopsPattern::init () [override], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 20 of file CrossDopsPattern.cpp.
{
  BlinkStepPattern::init();
  // Alternating evens and odds mapping of leds to turn on/off
  m_ledMap = MAP_PAIR_EVENS;
  // start colorset at index 0 so cur() works
  m_colorset.setCurIndex(0);
}
References BlinkStepPattern::init(), Pattern::m_colorset, m_ledMap, MAP_PAIR_EVENS, and Colorset::setCurIndex().
poststep()
void CrossDopsPattern::poststep () [override], [protected], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 35 of file CrossDopsPattern.cpp.
{
  // iterate to next color and invert of all the evens/odds
  m_colorset.getNext();
  m_ledMap = MAP_INVERSE(m_ledMap);
}
References Colorset::getNext(), Pattern::m_colorset, m_ledMap, and MAP_INVERSE.
Member Data Documentation
m_ledMap
LedMap CrossDopsPattern::m_ledMap [private]
Definition at line 23 of file CrossDopsPattern.h.
Referenced by blinkOn(), init(), and poststep().
The documentation for this class was generated from the following files:
VortexEngine/src/Patterns/Multi/CrossDopsPattern.h
VortexEngine/src/Patterns/Multi/CrossDopsPattern.cpp