Pattern Class Reference
#include <Pattern.h>
Public Member Functions
virtual ~Pattern ()
virtual void bind (LedPos pos)
virtual void init ()
virtual void play ()=0
bool serialize (ByteStream &buffer) const
bool unserialize (ByteStream &buffer)
void setArg (uint8_t index, uint8_t value)
uint8_t getArg (uint8_t index) const
uint8_t & argRef (uint8_t index)
void setArgs (const PatternArgs &args)
void getArgs (PatternArgs &args) const
uint8_t getNumArgs () const
bool equals (const Pattern *other)
const Colorset getColorset () const
Colorset getColorset ()
void setColorset (const Colorset &set)
void clearColorset ()
void setLedPos (LedPos pos)
PatternID getPatternID () const
LedPos getLedPos () const
uint32_t getFlags () const
bool hasFlags (uint32_t flags) const
Protected Member Functions
Pattern (VortexEngine &engine)
Pattern (VortexEngine &engine, const PatternArgs &args)
void registerArg (arg_offset_t argOffset)
Protected Attributes
VortexEngine & m_engine
PatternID m_patternID
uint8_t m_patternFlags
Colorset m_colorset
LedPos m_ledPos
uint8_t m_numArgs
arg_offset_t m_argList [MAX_PATTERN_ARGS]
Friends
class PatternBuilder
Detailed Description
Definition at line 51 of file Pattern.h.
Constructor & Destructor Documentation
Pattern() [1/2]
Pattern::Pattern (VortexEngine & engine) [protected]
Definition at line 14 of file Pattern.cpp.
                                     :
  m_engine(engine),
  m_patternID(PATTERN_FIRST),
  m_patternFlags(0),
  m_colorset(),
  m_ledPos(LED_FIRST),
  m_numArgs(0),
  m_argList()
#ifdef VORTEX_LIB
  ,m_argNameList()
#endif
{
}
Pattern() [2/2]
Pattern::Pattern (VortexEngine & engine, const PatternArgs & args) [protected]
Definition at line 28 of file Pattern.cpp.
                                                              :
  Pattern(engine)
{
}
 Pattern()
Pattern::~Pattern () [virtual]
Definition at line 33 of file Pattern.cpp.
{
}
Member Function Documentation
argRef()
uint8_t & Pattern::argRef (uint8_t index)
Definition at line 120 of file Pattern.cpp.
{
  if (index >= m_numArgs) {
    index = 0;
  }
  return *((uint8_t *)this + m_argList[index]);
}
References m_argList, and m_numArgs.
Referenced by PatternSelect::onShortClick().
bind()
void Pattern::bind (LedPos pos) [virtual]
Reimplemented in MultiLedPattern.
Definition at line 37 of file Pattern.cpp.
{
  if (pos > LED_COUNT) {
    return;
  }
  m_ledPos = pos;
}
References LED_COUNT, and m_ledPos.
Referenced by MultiLedPattern::bind(), PatternBuilder::dupe(), SequencedPattern::playSequenceStep(), and CompoundPattern::setPatternAt().
clearColorset()
void Pattern::clearColorset ()
Definition at line 175 of file Pattern.cpp.
{
  m_colorset.clear();
}
References Colorset::clear(), and m_colorset.
equals()
bool Pattern::equals (const Pattern * other)
Definition at line 143 of file Pattern.cpp.
{
  if (!other) {
    return false;
  }
  // compare pattern id
  if (m_patternID != other->m_patternID) {
    return false;
  }
  // then colorset
  if (!m_colorset.equals(&other->m_colorset)) {
    return false;
  }
  // number of args
  if (m_numArgs != other->m_numArgs) {
    return false;
  }
  // compare each arg
  for (uint8_t i = 0; i < m_numArgs; ++i) {
    if (getArg(i) != other->getArg(i)) {
      return false;
    }
  }
  return true;
}
References Colorset::equals(), getArg(), m_colorset, m_numArgs, and m_patternID.
Referenced by Mode::equals(), and Mode::hasSameSingleLed().
getArg()
uint8_t Pattern::getArg (uint8_t index) const
Definition at line 112 of file Pattern.cpp.
{
  if (index >= m_numArgs) {
    return 0;
  }
  return *((uint8_t *)this + m_argList[index]);
}
References m_argList, and m_numArgs.
Referenced by equals(), and Mode::getArg().
getArgs()
void Pattern::getArgs (PatternArgs & args) const
Definition at line 135 of file Pattern.cpp.
{
  args.init();
  for (uint32_t i = 0; i < m_numArgs; ++i) {
    args.addArgs(*((uint8_t *)this + m_argList[i]));
  }
}
References PatternArgs::addArgs(), PatternArgs::init(), m_argList, and m_numArgs.
Referenced by PatternBuilder::dupe(), and serialize().
getColorset() [1/2]
Colorset Pattern::getColorset () [inline]
Definition at line 108 of file Pattern.h.
{ return m_colorset; }
References m_colorset.
getColorset() [2/2]
const Colorset Pattern::getColorset () const [inline]
Definition at line 107 of file Pattern.h.
{ return m_colorset; }
References m_colorset.
Referenced by PatternBuilder::dupe(), Mode::getColorset(), and SequencedPattern::playSequenceStep().
getFlags()
uint32_t Pattern::getFlags () const [inline]
Definition at line 122 of file Pattern.h.
{ return m_patternFlags; }
References m_patternFlags.
getLedPos()
LedPos Pattern::getLedPos () const [inline]
Definition at line 119 of file Pattern.h.
{ return m_ledPos; }
References m_ledPos.
Referenced by PatternBuilder::dupe().
getNumArgs()
uint8_t Pattern::getNumArgs () const [inline]
Definition at line 98 of file Pattern.h.
{ return m_numArgs; }
References m_numArgs.
Referenced by PatternBuilder::numDefaultArgs(), PatternSelect::onLongClick(), and PatternSelect::onShortClick().
getPatternID()
PatternID Pattern::getPatternID () const [inline]
Definition at line 116 of file Pattern.h.
{ return m_patternID; }
References m_patternID.
Referenced by PatternBuilder::dupe(), Mode::getPatternID(), Mode::isEmpty(), and SequencedPattern::playSequenceStep().
hasFlags()
bool Pattern::hasFlags (uint32_t flags) const [inline]
Definition at line 123 of file Pattern.h.
{ return (m_patternFlags & flags) != 0; }
References m_patternFlags.
init()
void Pattern::init () [virtual]
Reimplemented in SingleLedPattern, BlendPattern, BasicPattern, ZigzagPattern, WarpWormPattern, WarpPattern, VortexWipePattern, VortexPattern, TheaterChasePattern, SnowballPattern, SequencedPattern, PulsishPattern, MultiLedPattern, LighthousePattern, HueShiftPattern, FillPattern, DripPattern, DripMorphPattern, DoubleStrobePattern, CrossDopsPattern, CompoundPattern, BouncePattern, BlinkStepPattern, and BackStrobePattern.
Definition at line 45 of file Pattern.cpp.
{
  m_colorset.resetIndex();
}
References m_colorset, and Colorset::resetIndex().
Referenced by Mode::init(), MultiLedPattern::init(), BasicPattern::init(), SingleLedPattern::init(), and Mode::unserialize().
play()
virtual void Pattern::play () [pure virtual]
Implemented in BasicPattern, ZigzagPattern, SequencedPattern, PulsishPattern, LighthousePattern, HueShiftPattern, DripMorphPattern, CompoundPattern, BlinkStepPattern, and BackStrobePattern.
Referenced by Mode::play(), CompoundPattern::play(), and SequencedPattern::playSequenceStep().
registerArg()
void Pattern::registerArg (arg_offset_t argOffset) [protected]
Definition at line 183 of file Pattern.cpp.
{
  if (m_numArgs >= MAX_PATTERN_ARGS) {
    ERROR_LOG("too many args");
    return;
  }
#ifdef VORTEX_LIB
  m_argNameList[m_numArgs] = name;
#endif
  m_argList[m_numArgs++] = argOffset;
}
References ERROR_LOG, and MAX_PATTERN_ARGS.
serialize()
bool Pattern::serialize (ByteStream & buffer) const
Definition at line 63 of file Pattern.cpp.
{
  if (!buffer.serialize8((uint8_t)m_patternID)) {
    return false;
  }
  if (!m_colorset.serialize(buffer)) {
    return false;
  }
  PatternArgs args;
  getArgs(args);
  PatternArgs defaults = m_engine.patternBuilder().getDefaultArgs(m_patternID);
  // generate a bitmap of which args are defaulted
  uint8_t argmap = ARG_NONE;
  for (uint32_t i = 0; i < MAX_ARGS; ++i) {
    if (args.args[i] != defaults.args[i]) {
      ARGMAP_SET(argmap, i);
    }
  }
  if (!args.serialize(buffer, argmap)) {
    return false;
  }
  return true;
}
References ARG_NONE, ARGMAP_SET, PatternArgs::args, getArgs(), PatternBuilder::getDefaultArgs(), m_colorset, m_engine, m_patternID, MAX_ARGS, VortexEngine::patternBuilder(), Colorset::serialize(), PatternArgs::serialize(), and ByteStream::serialize8().
Referenced by Randomizer::init(), and Mode::serialize().
setArg()
void Pattern::setArg (uint8_t index, uint8_t value)
Definition at line 104 of file Pattern.cpp.
{
  if (index >= m_numArgs) {
    return;
  }
  *((uint8_t *)this + m_argList[index]) = value;
}
References m_argList, and m_numArgs.
Referenced by Mode::setArg().
setArgs()
void Pattern::setArgs (const PatternArgs & args)
Definition at line 128 of file Pattern.cpp.
{
  for (uint32_t i = 0; i < m_numArgs; ++i) {
    *((uint8_t *)this + m_argList[i]) = args.args[i];
  }
}
References PatternArgs::args, m_argList, and m_numArgs.
Referenced by BackStrobePattern::BackStrobePattern(), BasicPattern::BasicPattern(), BlendPattern::BlendPattern(), BouncePattern::BouncePattern(), ChaserPattern::ChaserPattern(), CrossDopsPattern::CrossDopsPattern(), DoubleStrobePattern::DoubleStrobePattern(), DripMorphPattern::DripMorphPattern(), DripPattern::DripPattern(), FillPattern::FillPattern(), HueShiftPattern::HueShiftPattern(), LighthousePattern::LighthousePattern(), MeteorPattern::MeteorPattern(), PulsishPattern::PulsishPattern(), SnowballPattern::SnowballPattern(), SolidPattern::SolidPattern(), SparkleTracePattern::SparkleTracePattern(), TheaterChasePattern::TheaterChasePattern(), unserialize(), VortexPattern::VortexPattern(), VortexWipePattern::VortexWipePattern(), WarpPattern::WarpPattern(), WarpWormPattern::WarpWormPattern(), and ZigzagPattern::ZigzagPattern().
setColorset()
void Pattern::setColorset (const Colorset & set)
Definition at line 170 of file Pattern.cpp.
{
  m_colorset = set;
}
References m_colorset.
Referenced by PatternBuilder::dupe(), SequencedPattern::playSequenceStep(), Mode::setColorset(), Mode::setPattern(), and CompoundPattern::setPatternAt().
setLedPos()
void Pattern::setLedPos (LedPos pos) [inline]
Definition at line 113 of file Pattern.h.
{ m_ledPos = pos; }
References m_ledPos.
unserialize()
bool Pattern::unserialize (ByteStream & buffer)
Definition at line 88 of file Pattern.cpp.
{
  // don't unserialize the pattern ID because it is already
  // unserialized by the pattern builder to decide which pattern
  // to instantiate, instead only unserialize the colorset
  if (!m_colorset.unserialize(buffer)) {
    return false;
  }
  // start with the default args for this pattern
  PatternArgs args = m_engine.patternBuilder().getDefaultArgs(m_patternID);
  // then unserialize any different args overtop of the defaults
  args.unserialize(buffer);
  setArgs(args);
  return true;
}
References PatternBuilder::getDefaultArgs(), m_colorset, m_engine, m_patternID, VortexEngine::patternBuilder(), setArgs(), Colorset::unserialize(), and PatternArgs::unserialize().
Referenced by PatternBuilder::unserialize().
Friends And Related Function Documentation
PatternBuilder
friend class PatternBuilder [friend]
Definition at line 54 of file Pattern.h.
Member Data Documentation
m_argList
arg_offset_t Pattern::m_argList[MAX_PATTERN_ARGS] [protected]
Definition at line 138 of file Pattern.h.
Referenced by argRef(), getArg(), getArgs(), setArg(), and setArgs().
m_colorset
Colorset Pattern::m_colorset [protected]
Definition at line 133 of file Pattern.h.
Referenced by BasicPattern::beginDash(), DripMorphPattern::blinkOn(), BouncePattern::blinkOn(), CrossDopsPattern::blinkOn(), DoubleStrobePattern::blinkOn(), DripPattern::blinkOn(), FillPattern::blinkOn(), LighthousePattern::blinkOn(), SnowballPattern::blinkOn(), SparkleTracePattern::blinkOn(), TheaterChasePattern::blinkOn(), VortexPattern::blinkOn(), VortexWipePattern::blinkOn(), WarpPattern::blinkOn(), WarpWormPattern::blinkOn(), clearColorset(), ZigzagPattern::Snake::drawSnake(), equals(), getColorset(), init(), BouncePattern::init(), CrossDopsPattern::init(), DoubleStrobePattern::init(), DripMorphPattern::init(), DripPattern::init(), FillPattern::init(), HueShiftPattern::init(), LighthousePattern::init(), SnowballPattern::init(), VortexPattern::init(), VortexWipePattern::init(), WarpPattern::init(), WarpWormPattern::init(), ZigzagPattern::init(), BasicPattern::init(), BlendPattern::init(), ZigzagPattern::Snake::init(), BasicPattern::onBlinkOn(), BlendPattern::onBlinkOn(), SolidPattern::onBlinkOn(), HueShiftPattern::play(), PulsishPattern::play(), BasicPattern::play(), SequencedPattern::playSequenceStep(), BlinkStepPattern::poststep(), BouncePattern::poststep(), CrossDopsPattern::poststep(), DripPattern::poststep(), FillPattern::poststep(), LighthousePattern::poststep(), MeteorPattern::poststep(), SnowballPattern::poststep(), SparkleTracePattern::poststep(), VortexPattern::poststep(), VortexWipePattern::poststep(), WarpPattern::poststep(), WarpWormPattern::poststep(), serialize(), setColorset(), CompoundPattern::setPatternAt(), ZigzagPattern::Snake::step(), and unserialize().
m_engine
VortexEngine& Pattern::m_engine [protected]
Definition at line 127 of file Pattern.h.
Referenced by BasicPattern::beginDash(), BasicPattern::beginGap(), BlinkStepPattern::blinkOff(), DripMorphPattern::blinkOff(), LighthousePattern::blinkOff(), MeteorPattern::blinkOff(), DripMorphPattern::blinkOn(), BouncePattern::blinkOn(), CrossDopsPattern::blinkOn(), DoubleStrobePattern::blinkOn(), DripPattern::blinkOn(), FillPattern::blinkOn(), LighthousePattern::blinkOn(), MeteorPattern::blinkOn(), SnowballPattern::blinkOn(), SparkleTracePattern::blinkOn(), TheaterChasePattern::blinkOn(), VortexPattern::blinkOn(), VortexWipePattern::blinkOn(), WarpPattern::blinkOn(), WarpWormPattern::blinkOn(), ZigzagPattern::Snake::draw(), ZigzagPattern::Snake::drawSnake(), BasicPattern::onBlinkOff(), BasicPattern::onBlinkOn(), BlendPattern::onBlinkOn(), HueShiftPattern::play(), PulsishPattern::play(), SequencedPattern::playSequenceStep(), SparkleTracePattern::poststep(), serialize(), CompoundPattern::setEvensOdds(), CompoundPattern::setPatternAt(), and unserialize().
m_ledPos
LedPos Pattern::m_ledPos [protected]
Definition at line 135 of file Pattern.h.
Referenced by BasicPattern::beginDash(), BasicPattern::beginGap(), bind(), getLedPos(), BasicPattern::onBlinkOff(), BasicPattern::onBlinkOn(), BlendPattern::onBlinkOn(), and setLedPos().
m_numArgs
uint8_t Pattern::m_numArgs [protected]
Definition at line 137 of file Pattern.h.
Referenced by argRef(), equals(), getArg(), getArgs(), getNumArgs(), setArg(), and setArgs().
m_patternFlags
uint8_t Pattern::m_patternFlags [protected]
Definition at line 131 of file Pattern.h.
Referenced by getFlags(), hasFlags(), and MultiLedPattern::MultiLedPattern().
m_patternID
PatternID Pattern::m_patternID [protected]
Definition at line 129 of file Pattern.h.
Referenced by BackStrobePattern::BackStrobePattern(), BasicPattern::BasicPattern(), BlendPattern::BlendPattern(), BouncePattern::BouncePattern(), CrossDopsPattern::CrossDopsPattern(), DoubleStrobePattern::DoubleStrobePattern(), DripMorphPattern::DripMorphPattern(), DripPattern::DripPattern(), equals(), FillPattern::FillPattern(), getPatternID(), HueShiftPattern::HueShiftPattern(), LighthousePattern::LighthousePattern(), PatternBuilder::makeInternal(), MeteorPattern::MeteorPattern(), PulsishPattern::PulsishPattern(), serialize(), SnowballPattern::SnowballPattern(), SolidPattern::SolidPattern(), SparkleTracePattern::SparkleTracePattern(), TheaterChasePattern::TheaterChasePattern(), unserialize(), VortexPattern::VortexPattern(), VortexWipePattern::VortexWipePattern(), WarpPattern::WarpPattern(), WarpWormPattern::WarpWormPattern(), and ZigzagPattern::ZigzagPattern().
The documentation for this class was generated from the following files:
VortexEngine/src/Patterns/Pattern.h
VortexEngine/src/Patterns/Pattern.cpp