FillPattern Class Reference
#include <FillPattern.h>
Public Member Functions
FillPattern (const PatternArgs &args)
virtual ~FillPattern ()
virtual void init () override
Protected Member Functions
virtual void blinkOn () override
virtual void poststep () override
Private Attributes
uint8_t m_progress
Additional Inherited Members
Detailed Description
Definition at line 8 of file FillPattern.h.
Constructor & Destructor Documentation
FillPattern()
FillPattern::FillPattern (const PatternArgs & args)
Definition at line 8 of file FillPattern.cpp.
                                                :
  BlinkStepPattern(args),
  m_progress(0)
{
  m_patternID = PATTERN_FILL;
  setArgs(args);
}
References Pattern::m_patternID, PATTERN_FILL, and Pattern::setArgs().
 FillPattern()
FillPattern::~FillPattern () [virtual]
Definition at line 16 of file FillPattern.cpp.
{
}
Member Function Documentation
blinkOn()
void FillPattern::blinkOn () [override], [protected], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 29 of file FillPattern.cpp.
{
  LedPos edgePos = (LedPos)(m_progress * (LED_COUNT / 4));
  Leds::setRange(LED_FIRST, edgePos, m_colorset.peekNext());
  Leds::setRange(edgePos, LED_LAST, m_colorset.cur());
}
References Colorset::cur(), LED_COUNT, LED_FIRST, LED_LAST, Pattern::m_colorset, m_progress, Colorset::peekNext(), and Leds::setRange().
init()
void FillPattern::init () [override], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 20 of file FillPattern.cpp.
{
  BlinkStepPattern::init();
  // reset progress
  m_progress = 0;
  // start colorset at index 0 so cur() works
  m_colorset.setCurIndex(0);
}
References BlinkStepPattern::init(), Pattern::m_colorset, m_progress, and Colorset::setCurIndex().
poststep()
void FillPattern::poststep () [override], [protected], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 36 of file FillPattern.cpp.
{
  m_progress = (m_progress + 1) % 4;
  if (m_progress == 0) {
    m_colorset.getNext();
  }
}
References Colorset::getNext(), Pattern::m_colorset, and m_progress.
Member Data Documentation
m_progress
uint8_t FillPattern::m_progress [private]
Definition at line 22 of file FillPattern.h.
Referenced by blinkOn(), init(), and poststep().
The documentation for this class was generated from the following files:
VortexEngine/src/Patterns/Multi/FillPattern.h
VortexEngine/src/Patterns/Multi/FillPattern.cpp