BitStream Class Reference
#include <BitStream.h>
Public Member Functions
BitStream ()
BitStream (uint32_t size)
BitStream (uint8_t *buf, uint32_t size)
~BitStream ()
bool init (uint8_t *buf, uint32_t size)
bool init (uint32_t size)
void reset ()
void resetPos ()
uint8_t read1Bit ()
void write1Bit (uint8_t bit)
uint8_t readBits (uint32_t numBits)
void writeBits (uint32_t numBits, uint32_t val)
bool eof () const
bool allocated () const
uint16_t size () const
const uint8_t * data () const
const uint32_t * dwData () const
uint16_t dwordpos () const
uint16_t bytepos () const
uint16_t bitpos () const
Private Attributes
uint8_t * m_buf
uint16_t m_buf_size
uint16_t m_bit_pos
bool m_buf_eof
bool m_allocated
Detailed Description
Definition at line 7 of file BitStream.h.
Constructor & Destructor Documentation
BitStream() [1/3]
BitStream::BitStream ()
Definition at line 8 of file BitStream.cpp.
                     :
  m_buf(nullptr), m_buf_size(0),
  m_bit_pos(0), m_buf_eof(false),
  m_allocated(false)
{
}
BitStream() [2/3]
BitStream::BitStream (uint32_t size)
Definition at line 21 of file BitStream.cpp.
                                  :
  BitStream()
{
  init(size);
}
References init(), and size().
BitStream() [3/3]
BitStream::BitStream (uint8_t * buf, uint32_t size)
Definition at line 15 of file BitStream.cpp.
                                                :
  BitStream()
{
  init(buf, size);
}
References init(), and size().
 BitStream()
BitStream::~BitStream ()
Definition at line 27 of file BitStream.cpp.
{
  if (m_allocated) {
    vfree(m_buf);
  }
}
References m_allocated, m_buf, and vfree.
Member Function Documentation
allocated()
bool BitStream::allocated () const [inline]
Definition at line 34 of file BitStream.h.
{ return m_allocated; }
References m_allocated.
bitpos()
uint16_t BitStream::bitpos () const [inline]
Definition at line 40 of file BitStream.h.
{ return m_bit_pos; }
References m_bit_pos.
bytepos()
uint16_t BitStream::bytepos () const [inline]
Definition at line 39 of file BitStream.h.
{ return m_bit_pos / 8; }
References m_bit_pos.
Referenced by VLReceiver::bytesReceived(), VLReceiver::dataReady(), VLReceiver::isReceiving(), VLReceiver::percentReceived(), and VLReceiver::read().
data()
const uint8_t* BitStream::data () const [inline]
Definition at line 36 of file BitStream.h.
{ return m_buf; }
References m_buf.
Referenced by VLReceiver::dataReady(), VLReceiver::percentReceived(), VLReceiver::read(), and VLSender::send().
dwData()
const uint32_t* BitStream::dwData () const [inline]
Definition at line 37 of file BitStream.h.
{ return (uint32_t *)m_buf; }
References m_buf.
dwordpos()
uint16_t BitStream::dwordpos () const [inline]
Definition at line 38 of file BitStream.h.
{ return m_bit_pos / 32; }
References m_bit_pos.
eof()
bool BitStream::eof () const [inline]
Definition at line 33 of file BitStream.h.
{ return m_buf_eof; }
References m_buf_eof.
init() [1/2]
bool BitStream::init (uint32_t size)
Definition at line 42 of file BitStream.cpp.
{
  if (m_buf) {
    vfree(m_buf);
  }
  m_buf = (uint8_t *)vcalloc(1, size);
  if (!m_buf) {
    ERROR_OUT_OF_MEMORY();
    return false;
  }
  m_buf_size = size;
  m_allocated = true;
  resetPos();
  return true;
}
References ERROR_OUT_OF_MEMORY, m_allocated, m_buf, m_buf_size, resetPos(), size(), vcalloc, and vfree.
init() [2/2]
bool BitStream::init (uint8_t * buf, uint32_t size)
Definition at line 34 of file BitStream.cpp.
{
  m_buf = buf;
  m_buf_size = size;
  resetPos();
  return true;
}
References m_buf, m_buf_size, resetPos(), and size().
Referenced by BitStream(), VLReceiver::init(), and VLSender::loadMode().
read1Bit()
uint8_t BitStream::read1Bit ()
Definition at line 72 of file BitStream.cpp.
{
  if (m_buf_eof) {
    return 0;
  }
  if (m_bit_pos >= (m_buf_size * 8)) {
    m_buf_eof = true;
    return 0;
  }
  uint32_t rv = (m_buf[m_bit_pos / 8] >> (7 - (m_bit_pos % 8))) & 1;
  m_bit_pos++;
  if (m_bit_pos >= (m_buf_size * 8)) {
    m_buf_eof = true;
  }
  return rv;
}
References m_bit_pos, m_buf, m_buf_eof, and m_buf_size.
Referenced by readBits().
readBits()
uint8_t BitStream::readBits (uint32_t numBits)
Definition at line 105 of file BitStream.cpp.
{
  uint32_t val = 0;
  if (m_buf_eof) {
    return 0;
  }
  for (uint32_t i = 0; i < numBits; ++i) {
    val = (val << 1) | read1Bit();
    if (m_buf_eof) {
      break;
    }
  }
  if (m_bit_pos >= (m_buf_size * 8)) {
    m_buf_eof = true;
  }
  return val;
}
References m_bit_pos, m_buf_eof, m_buf_size, and read1Bit().
reset()
void BitStream::reset ()
Definition at line 58 of file BitStream.cpp.
{
  if (m_buf) {
    memset(m_buf, 0, m_buf_size);
  }
  resetPos();
}
References m_buf, m_buf_size, and resetPos().
Referenced by VLReceiver::resetVLState().
resetPos()
void BitStream::resetPos ()
Definition at line 66 of file BitStream.cpp.
{
  m_bit_pos = 0;
  m_buf_eof = false;
}
References m_bit_pos, and m_buf_eof.
Referenced by init(), and reset().
size()
uint16_t BitStream::size () const [inline]
Definition at line 35 of file BitStream.h.
{ return m_buf_size; }
References m_buf_size.
Referenced by BitStream(), and init().
write1Bit()
void BitStream::write1Bit (uint8_t bit)
Definition at line 89 of file BitStream.cpp.
{
  if (m_buf_eof) {
    return;
  }
  if (m_bit_pos >= (m_buf_size * 8)) {
    m_buf_eof = true;
    return;
  }
  m_buf[m_bit_pos / 8] |= (bit & 1) << (7 - (m_bit_pos % 8));
  m_bit_pos++;
  if (m_bit_pos >= (m_buf_size * 8)) {
    m_buf_eof = true;
  }
}
References m_bit_pos, m_buf, m_buf_eof, and m_buf_size.
Referenced by VLReceiver::handleVLTiming(), and writeBits().
writeBits()
void BitStream::writeBits (uint32_t numBits, uint32_t val)
Definition at line 124 of file BitStream.cpp.
{
  for (uint32_t i = 0; i < numBits; ++i) {
    // write each bit in order, for ex if numBits is 4:
    //
    // 00000000 01010101
    // ^^^^
    // write these four bits from left to right
    write1Bit((val >> ((numBits - 1) - i)) & 1);
  }
}
References write1Bit().
Member Data Documentation
m_allocated
bool BitStream::m_allocated [private]
Definition at line 47 of file BitStream.h.
Referenced by allocated(), init(), and ~BitStream().
m_bit_pos
uint16_t BitStream::m_bit_pos [private]
Definition at line 45 of file BitStream.h.
Referenced by bitpos(), bytepos(), dwordpos(), read1Bit(), readBits(), resetPos(), and write1Bit().
m_buf
uint8_t* BitStream::m_buf [private]
Definition at line 43 of file BitStream.h.
Referenced by data(), dwData(), init(), read1Bit(), reset(), write1Bit(), and ~BitStream().
m_buf_eof
bool BitStream::m_buf_eof [private]
Definition at line 46 of file BitStream.h.
Referenced by eof(), read1Bit(), readBits(), resetPos(), and write1Bit().
m_buf_size
uint16_t BitStream::m_buf_size [private]
Definition at line 44 of file BitStream.h.
Referenced by init(), read1Bit(), readBits(), reset(), size(), and write1Bit().
The documentation for this class was generated from the following files:
VortexEngine/src/Serial/BitStream.h
VortexEngine/src/Serial/BitStream.cpp