Randomizer Class Reference
#include <Randomizer.h>
Public Member Functions
Randomizer (const RGBColor &col, bool advanced)
~Randomizer ()
bool init () override
MenuAction run () override
void onShortClick () override
void onLongClick () override
bool reRoll ()
Private Types
enum RandomizeFlags : uint8_t { RANDOMIZE_NONE = 0
, RANDOMIZE_COLORSET = (1 << 0)
, RANDOMIZE_PATTERN = (1 << 1)
, RANDOMIZE_BOTH = (RANDOMIZE_COLORSET | RANDOMIZE_PATTERN)
 }
Private Member Functions
void showRandomizationSelect ()
bool reRollMulti ()
PatternID rollMultiLedPatternID (Random &ctx)
bool splitMultiRandomize ()
bool rollSinglesLedMap (Random &ctx, LedMap map)
bool reRollSingles ()
PatternID rollSingleLedPatternID (Random &ctx)
Colorset rollColorset (Random &ctx)
bool rollCustomPattern (Random &ctx, Mode *pMode, LedPos pos)
void traditionalPattern (Random &ctx, PatternArgs &outArgs)
void gapPattern (Random &ctx, PatternArgs &outArgs)
void dashPattern (Random &ctx, PatternArgs &outArgs)
void crushPattern (Random &ctx, PatternArgs &outArgs)
Private Attributes
Random m_singlesRandCtx [LED_COUNT]
Random m_multiRandCtx
uint32_t m_lastRandomization
uint8_t m_flags
uint8_t m_displayHue
bool m_needToSelect
bool m_autoCycle
Additional Inherited Members
Detailed Description
Definition at line 11 of file Randomizer.h.
Member Enumeration Documentation
RandomizeFlags
enum Randomizer::RandomizeFlags : uint8_t [private]
Enumerator
RANDOMIZE_NONE
RANDOMIZE_COLORSET
RANDOMIZE_PATTERN
RANDOMIZE_BOTH
Definition at line 38 of file Randomizer.h.
                      : uint8_t {
    // this isn't a valid randomization state, if the flags are
    // on this state then the user will be prompted to pick
    RANDOMIZE_NONE = 0,
    // the two main kinds of randomization
    RANDOMIZE_COLORSET = (1 << 0),
    RANDOMIZE_PATTERN = (1 << 1),
    // compound flags both colorset and pattern randomization
    RANDOMIZE_BOTH = (RANDOMIZE_COLORSET | RANDOMIZE_PATTERN)
  };
Constructor & Destructor Documentation
Randomizer()
Randomizer::Randomizer (const RGBColor & col, bool advanced)
Definition at line 31 of file Randomizer.cpp.
                                                         :
  Menu(col, advanced),
  m_lastRandomization(0),
  m_flags(advanced ? RANDOMIZE_COLORSET : RANDOMIZE_BOTH),
  m_displayHue(0),
  m_needToSelect(advanced),
  m_autoCycle(false)
{
}
 Randomizer()
Randomizer::~Randomizer ()
Definition at line 41 of file Randomizer.cpp.
{
}
Member Function Documentation
crushPattern()
void Randomizer::crushPattern (Random & ctx, PatternArgs & outArgs) [private]
Definition at line 425 of file Randomizer.cpp.
{
  // call next8 explicitly in this order because the order they
  // are called is undefined when called as parameters to another function.
  // ex: f(a,b,c) may call in the order a,b,c or c,b,a depending on compiler.
  // So different compilers may produce different results,
  // but like this it is explicit
  uint8_t group = ctx.next8(0, 8); // groupsize 0 to 8
  uint8_t dash = 0; // dash 0
  uint8_t gap = ctx.next8(20, 40); // need gap 20 -> 40
  uint8_t off = ctx.next8(0, 10); // off duration 0 -> 5
  uint8_t on = ctx.next8(1, 10); // on duration 1 -> 10
  outArgs.init(on, off, gap, dash, group);
}
References PatternArgs::init(), and Random::next8().
Referenced by rollCustomPattern().
dashPattern()
void Randomizer::dashPattern (Random & ctx, PatternArgs & outArgs) [private]
Definition at line 411 of file Randomizer.cpp.
{
  // call next8 explicitly in this order because the order they
  // are called is undefined when called as parameters to another function.
  // ex: f(a,b,c) may call in the order a,b,c or c,b,a depending on compiler.
  // So different compilers may produce different results,
  // but like this it is explicit
  uint8_t dash = ctx.next8(20, 30); // dash duration 20 -> 30
  uint8_t gap = ctx.next8(20, 30); // need gap 20 -> 30
  uint8_t off = ctx.next8(0, 10); // off duration 0 -> 10
  uint8_t on = ctx.next8(1, 10); // on duration 1 -> 10
  outArgs.init(on, off, gap, dash);
}
References PatternArgs::init(), and Random::next8().
Referenced by rollCustomPattern().
gapPattern()
void Randomizer::gapPattern (Random & ctx, PatternArgs & outArgs) [private]
Definition at line 398 of file Randomizer.cpp.
{
  // call next8 explicitly in this order because the order they
  // are called is undefined when called as parameters to another function.
  // ex: f(a,b,c) may call in the order a,b,c or c,b,a depending on compiler.
  // So different compilers may produce different results,
  // but like this it is explicit
  uint8_t gap = ctx.next8(40, 100); // gap duration 40 -> 100
  uint8_t off = ctx.next8(0, 6); // off duration 0 -> 6
  uint8_t on = ctx.next8(1, 10); // on duration 1 -> 10
  outArgs.init(on, off, gap);
}
References PatternArgs::init(), and Random::next8().
Referenced by rollCustomPattern().
init()
bool Randomizer::init () [override], [virtual]
Reimplemented from Menu.
Definition at line 45 of file Randomizer.cpp.
{
  if (!Menu::init()) {
    return false;
  }
  // grab the multi ld pattern colorset crc if it's present
  Mode *cur = Modes::curMode();
#if VORTEX_SLIM == 0
  if (cur->hasMultiLed()) {
    ByteStream ledData;
    Pattern *pat = cur->getPattern(LED_MULTI);
    if (pat) {
      if (!pat->serialize(ledData)) {
        return false;
      }
    }
    m_multiRandCtx.seed(ledData.recalcCRC());
  }
#endif
  // initialize the randomseed of each led with the
  // CRC of the colorset on the respective LED
  for (LedPos l = LED_FIRST; l < LED_COUNT; ++l) {
    ByteStream ledData;
    Pattern *pat = cur->getPattern(l);
    if (pat) {
      if (!pat->serialize(ledData)) {
        return false;
      }
    }
    m_singlesRandCtx[l].seed(ledData.recalcCRC());
  }
  DEBUG_LOG("Entered randomizer");
  return true;
}
References Modes::curMode(), DEBUG_LOG, Mode::getPattern(), Mode::hasMultiLed(), Menu::init(), LED_COUNT, LED_FIRST, LED_MULTI, m_multiRandCtx, m_singlesRandCtx, ByteStream::recalcCRC(), Random::seed(), and Pattern::serialize().
onLongClick()
void Randomizer::onLongClick () [override], [virtual]
Reimplemented from Menu.
Definition at line 143 of file Randomizer.cpp.
{
  // if done the randomization selection part
  if (m_needToSelect) {
    // we are complete the randomization selection stage
    m_needToSelect = false;
    return;
  }
  // update the current mode with the new randomized mode
  Modes::updateCurMode(&m_previewMode);
  // then done here, save if the mode was different
  leaveMenu(true);
}
References Menu::leaveMenu(), m_needToSelect, Menu::m_previewMode, and Modes::updateCurMode().
onShortClick()
void Randomizer::onShortClick () [override], [virtual]
Reimplemented from Menu.
Definition at line 121 of file Randomizer.cpp.
{
  if (m_needToSelect) {
    if (m_flags == RANDOMIZE_BOTH) {
      m_flags = RANDOMIZE_COLORSET;
    } else {
      m_flags = (RandomizeFlags)(m_flags + 1);
    }
    return;
  }
  // if the user fast-clicks 3 times then toggle automode
  if (m_autoCycle || g_pButton->onConsecutivePresses(AUTO_CYCLE_RANDOMIZER_CLICKS)) {
    // toggle the auto cycle flag
    m_autoCycle = !m_autoCycle;
    // display a quick flash of either green or red to indicate whether auto mode is on or not
    Leds::holdAll(m_autoCycle ? RGB_GREEN : RGB_RED);
    return;
  }
  // shortClick re-roll the randomization
  reRoll();
}
References AUTO_CYCLE_RANDOMIZER_CLICKS, g_pButton, Leds::holdAll(), m_autoCycle, m_flags, m_needToSelect, Button::onConsecutivePresses(), RANDOMIZE_BOTH, RANDOMIZE_COLORSET, reRoll(), RGB_GREEN, and RGB_RED.
reRoll()
bool Randomizer::reRoll ()
Definition at line 157 of file Randomizer.cpp.
{
#if VORTEX_SLIM == 0
  if (m_targetLeds == MAP_LED(LED_MULTI)) {
    if (!reRollMulti()) {
      return false;
    }
  }
#endif
  if (!reRollSingles()) {
    return false;
  }
  // initialize the mode with the new pattern and colorset
  m_previewMode.init();
  return true;
}
References Mode::init(), LED_MULTI, Menu::m_previewMode, Menu::m_targetLeds, MAP_LED, reRollMulti(), and reRollSingles().
Referenced by onShortClick(), and run().
reRollMulti()
bool Randomizer::reRollMulti () [private]
Definition at line 188 of file Randomizer.cpp.
{
  // 50% chance to roll a 'split multi' which is a random mapping of singles half
  // being one pattern/color and the other half being another pattern/color
  if (m_multiRandCtx.next8() > 128) {
    return splitMultiRandomize();
  }
  if (m_flags & RANDOMIZE_PATTERN) {
    // TODO: Roll custom multi pattern?
    //if (m_advanced) {
    // if (!rollCustomPattern(ctx, &m_previewMode, pos)) {
    // ERROR_LOG("Failed to roll custom pattern");
    // return false;
    // }
    //}
    if (!m_previewMode.setPattern(rollMultiLedPatternID(m_multiRandCtx), LED_MULTI)) {
      ERROR_LOG("Failed to select pattern");
      return false;
    }
  }
  if (m_flags & RANDOMIZE_COLORSET) {
    if (!m_previewMode.setColorset(rollColorset(m_multiRandCtx), LED_MULTI)) {
      ERROR_LOG("Failed to roll new colorset");
      return false;
    }
  }
  return true;
}
References ERROR_LOG, LED_MULTI, m_flags, m_multiRandCtx, Menu::m_previewMode, Random::next8(), RANDOMIZE_COLORSET, RANDOMIZE_PATTERN, rollColorset(), rollMultiLedPatternID(), Mode::setColorset(), Mode::setPattern(), and splitMultiRandomize().
Referenced by reRoll().
reRollSingles()
bool Randomizer::reRollSingles () [private]
Definition at line 257 of file Randomizer.cpp.
{
  // re-roll each led position with it's respective random context
  MAP_FOREACH_LED(m_targetLeds) {
    Random &ctx = m_singlesRandCtx[pos];
    if (m_flags & RANDOMIZE_PATTERN) {
      // in advanced mode, when not randomizing the multi position, use a
      // special function to randomize totally custom led pattern timings
      if (m_advanced) {
        if (!rollCustomPattern(ctx, &m_previewMode, pos)) {
          ERROR_LOG("Failed to roll custom pattern");
          return false;
        }
      } else {
        if (!m_previewMode.setPattern(rollSingleLedPatternID(ctx), pos)) {
          ERROR_LOG("Failed to select pattern");
          return false;
        }
      }
    }
    if (m_flags & RANDOMIZE_COLORSET) {
      if (!m_previewMode.setColorset(rollColorset(ctx), pos)) {
        ERROR_LOG("Failed to roll new colorset");
        return false;
      }
    }
  }
  return true;
}
References ERROR_LOG, Menu::m_advanced, m_flags, Menu::m_previewMode, m_singlesRandCtx, Menu::m_targetLeds, MAP_FOREACH_LED, RANDOMIZE_COLORSET, RANDOMIZE_PATTERN, rollColorset(), rollCustomPattern(), rollSingleLedPatternID(), Mode::setColorset(), and Mode::setPattern().
Referenced by reRoll().
rollColorset()
Colorset Randomizer::rollColorset (Random & ctx) [private]
Definition at line 298 of file Randomizer.cpp.
{
  Colorset randomSet;
  // pick a random type of randomizer to use then use
  // the randomizer to generate a random colorset
  uint8_t randType = ctx.next8(0, 8);
  switch (randType) {
  default:
  case 0:
    randomSet.randomize(ctx);
    break;
  case 1:
    randomSet.randomizeColors(ctx, 0, Colorset::ColorMode::THEORY);
    break;
  case 2:
    randomSet.randomizeColors(ctx, 0, Colorset::ColorMode::MONOCHROMATIC);
    break;
  case 3:
    randomSet.randomizeColors2(ctx, Colorset::ColorMode2::DOUBLE_SPLIT_COMPLIMENTARY);
    break;
  case 4:
    randomSet.randomizeColors2(ctx, Colorset::ColorMode2::TETRADIC);
    break;
  case 5:
    randomSet.randomize(ctx, 1);
    break;
  case 6:
    randomSet.randomizeColors(ctx, 0, Colorset::ColorMode::EVENLY_SPACED);
    break;
  case 7:
    randomSet.randomizeColors(ctx, 2, Colorset::ColorMode::EVENLY_SPACED);
    break;
  case 8:
    randomSet.randomizeColors(ctx, 3, Colorset::ColorMode::EVENLY_SPACED);
    break;
  }
  // take the randomized colorset and repeate colors to make an additional pattern
  if (randomSet.numColors() <= 4 && ctx.next8(0, 1) != 0) {
    // using uint8_t here actually costs more bytes than int16_t
    int16_t startingNumColors = randomSet.numColors();
    for (int16_t i = 0; i < startingNumColors - 1; ++i) {
      // add a duplicate of each color in the colorset to in reverse
      randomSet.addColor(randomSet.get(startingNumColors - (i + 2)));
    }
  }
  return randomSet;
}
References Colorset::addColor(), Colorset::get(), Random::next8(), Colorset::numColors(), Colorset::randomize(), Colorset::randomizeColors(), and Colorset::randomizeColors2().
Referenced by reRollMulti(), reRollSingles(), and rollSinglesLedMap().
rollCustomPattern()
bool Randomizer::rollCustomPattern (Random & ctx, Mode * pMode, LedPos pos) [private]
Definition at line 347 of file Randomizer.cpp.
{
  PatternArgs args;
  // pick a random type of randomizer to use then use
  // the randomizer to generate a random pattern
  uint8_t patternType = ctx.next8(0, 3);
  switch (patternType) {
  default:
  case 0:
    traditionalPattern(ctx, args);
    break;
  case 1:
    gapPattern(ctx, args);
    break;
  case 2:
    dashPattern(ctx, args);
    break;
  case 3:
    crushPattern(ctx, args);
    break;
  }
  PatternID newPat = PATTERN_STROBE;
  // 1/3 chance to roll a blend pattern instead which will animate between
  // colors instead of blinking each color in the set
  if (!ctx.next8(0, 3)) {
    newPat = PATTERN_BLEND;
    // set the blend speed
    args.arg6 = ctx.next8(1, 10);
    // 1/2 chance to make the blend a flipping blend of some kind
    if (!ctx.next8(0, 2)) {
      // this is the number of blinks to a complementary color
      args.arg7 = ctx.next8(0, 3);
    }
    // up to arg7 is filled now
    args.numArgs = 7;
  }
  return pMode->setPattern(newPat, pos, &args);
}
References PatternArgs::arg6, PatternArgs::arg7, crushPattern(), dashPattern(), gapPattern(), Random::next8(), PatternArgs::numArgs, PATTERN_BLEND, PATTERN_STROBE, Mode::setPattern(), and traditionalPattern().
Referenced by reRollSingles().
rollMultiLedPatternID()
PatternID Randomizer::rollMultiLedPatternID (Random & ctx) [private]
Definition at line 217 of file Randomizer.cpp.
{
  return (PatternID)ctx.next8(PATTERN_MULTI_FIRST, PATTERN_MULTI_LAST);
}
References Random::next8(), PATTERN_MULTI_FIRST, and PATTERN_MULTI_LAST.
Referenced by reRollMulti().
rollSingleLedPatternID()
PatternID Randomizer::rollSingleLedPatternID (Random & ctx) [private]
Definition at line 287 of file Randomizer.cpp.
{
  PatternID newPat;
  // the random range begin/end
  do {
    // continuously re-randomize the pattern so we don't get undesirable patterns
    newPat = (PatternID)ctx.next8(PATTERN_SINGLE_FIRST, PATTERN_SINGLE_LAST);
  } while (newPat == PATTERN_SOLID || newPat == PATTERN_RIBBON || newPat == PATTERN_MINIRIBBON);
  return newPat;
}
References Random::next8(), PATTERN_MINIRIBBON, PATTERN_RIBBON, PATTERN_SINGLE_FIRST, PATTERN_SINGLE_LAST, and PATTERN_SOLID.
Referenced by reRollSingles(), and rollSinglesLedMap().
rollSinglesLedMap()
bool Randomizer::rollSinglesLedMap (Random & ctx, LedMap map) [private]
Definition at line 241 of file Randomizer.cpp.
{
  // apply pattern2 and colorset2 to the inverse bitmap
  PatternID pat = rollSingleLedPatternID(ctx);
  Colorset set = rollColorset(ctx);
  MAP_FOREACH_LED(map) {
    // apply the pattern and colorset
    if (!m_previewMode.setPattern(pat, pos, nullptr, &set)) {
      ERROR_LOG("Failed to apply pattern or colorset");
      return false;
    }
  }
  return true;
}
References ERROR_LOG, Menu::m_previewMode, MAP_FOREACH_LED, rollColorset(), rollSingleLedPatternID(), and Mode::setPattern().
Referenced by splitMultiRandomize().
run()
Menu::MenuAction Randomizer::run () [override], [virtual]
Reimplemented from Menu.
Definition at line 80 of file Randomizer.cpp.
{
  // run the base menu logic
  MenuAction result = Menu::run();
  if (result != MENU_CONTINUE) {
    return result;
  }
  // if the ranomization flags haven't been set yet just show a selection
  if (m_needToSelect) {
    // display the randomization selection menu
    showRandomizationSelect();
    return MENU_CONTINUE;
  }
#if VORTEX_SLIM == 0
  // if they are trying to randomize a multi-led pattern just convert
  // the pattern to all singles with the same colorset upon entry
  if (m_previewMode.isMultiLed() && m_targetLeds != MAP_LED(LED_MULTI)) {
    // convert the pattern to a single led pattern, this will map
    // all multi led patterns to single led patterns using modulo
    // so no matter which multi-led pattern they have selected it
    // will convert to a single led pattern of some kind
    PatternID newID = (PatternID)((m_previewMode.getPatternID() - PATTERN_MULTI_FIRST) % PATTERN_SINGLE_COUNT);
    // solid sucks
    if (newID == PATTERN_SOLID) ++newID;
    m_previewMode.setPattern(newID);
    m_previewMode.init();
  }
#endif
  uint32_t now = Time::getCurtime();
  if (m_autoCycle && (m_lastRandomization + AUTO_RANDOM_DELAY_TICKS < now)) {
    m_lastRandomization = now;
    reRoll();
  }
  // display the randomized mode
  m_previewMode.play();
  // show the selection
  Menus::showSelection();
  // return true to continue staying in randomizer menu
  return MENU_CONTINUE;
}
References AUTO_RANDOM_DELAY_TICKS, Time::getCurtime(), Mode::getPatternID(), Mode::init(), Mode::isMultiLed(), LED_MULTI, m_autoCycle, m_lastRandomization, m_needToSelect, Menu::m_previewMode, Menu::m_targetLeds, MAP_LED, Menu::MENU_CONTINUE, PATTERN_MULTI_FIRST, PATTERN_SINGLE_COUNT, PATTERN_SOLID, Mode::play(), reRoll(), Menu::run(), Mode::setPattern(), showRandomizationSelect(), and Menus::showSelection().
showRandomizationSelect()
void Randomizer::showRandomizationSelect () [private]
Definition at line 174 of file Randomizer.cpp.
{
  // show iterating rainbow if they are randomizing color, otherwise 0 sat if they
  // are only randomizing the pattern
  Leds::setAll(HSVColor(m_displayHue++, (m_flags & RANDOMIZE_COLORSET) * 255, 84));
  if (m_flags & RANDOMIZE_PATTERN) {
    // this is blinking the light to off so the params are switched but still effectively correct
    Leds::blinkAll(DOPS_ON_DURATION, DOPS_OFF_DURATION);
  }
  // render the click selection blink
  Menus::showSelection();
}
References Leds::blinkAll(), DOPS_OFF_DURATION, DOPS_ON_DURATION, m_displayHue, m_flags, RANDOMIZE_COLORSET, RANDOMIZE_PATTERN, Leds::setAll(), and Menus::showSelection().
Referenced by run().
splitMultiRandomize()
bool Randomizer::splitMultiRandomize () [private]
Definition at line 222 of file Randomizer.cpp.
{
  // clear any existing patterns just in case a multi is set
  m_previewMode.clearPattern();
  // generate random bitmap of which leds to set
  LedMap randomMap = maps[m_multiRandCtx.next8(0, (NUM_MAPS - 1))];
  // roll all of one side of the map one way
  if (!rollSinglesLedMap(m_multiRandCtx, randomMap)) {
    ERROR_LOG("Failed to roll first half of split multi map");
    return false;
  }
  // roll the flipped map with new singles
  if (!rollSinglesLedMap(m_multiRandCtx, MAP_INVERSE(randomMap))) {
    ERROR_LOG("Failed to roll first half of split multi map");
    return false;
  }
  return true;
}
References Mode::clearPattern(), ERROR_LOG, m_multiRandCtx, Menu::m_previewMode, MAP_INVERSE, maps, Random::next8(), NUM_MAPS, and rollSinglesLedMap().
Referenced by reRollMulti().
traditionalPattern()
void Randomizer::traditionalPattern (Random & ctx, PatternArgs & outArgs) [private]
Definition at line 386 of file Randomizer.cpp.
{
  // call next8 explicitly in this order because the order they
   // are called is undefined when called as parameters to another function.
   // ex: f(a,b,c) may call in the order a,b,c or c,b,a depending on compiler.
   // So different compilers may produce different results,
   // but like this it is explicit
  uint8_t off = ctx.next8(8, 60); // off duration 0 -> 60
  uint8_t on = ctx.next8(1, 20); // on duration 1 -> 20
  outArgs.init(on, off);
}
References PatternArgs::init(), and Random::next8().
Referenced by rollCustomPattern().
Member Data Documentation
m_autoCycle
bool Randomizer::m_autoCycle [private]
Definition at line 60 of file Randomizer.h.
Referenced by onShortClick(), and run().
m_displayHue
uint8_t Randomizer::m_displayHue [private]
Definition at line 55 of file Randomizer.h.
Referenced by showRandomizationSelect().
m_flags
uint8_t Randomizer::m_flags [private]
Definition at line 52 of file Randomizer.h.
Referenced by onShortClick(), reRollMulti(), reRollSingles(), and showRandomizationSelect().
m_lastRandomization
uint32_t Randomizer::m_lastRandomization [private]
Definition at line 36 of file Randomizer.h.
Referenced by run().
m_multiRandCtx
Random Randomizer::m_multiRandCtx [private]
Definition at line 32 of file Randomizer.h.
Referenced by init(), reRollMulti(), and splitMultiRandomize().
m_needToSelect
bool Randomizer::m_needToSelect [private]
Definition at line 58 of file Randomizer.h.
Referenced by onLongClick(), onShortClick(), and run().
m_singlesRandCtx
Random Randomizer::m_singlesRandCtx[LED_COUNT] [private]
Definition at line 29 of file Randomizer.h.
Referenced by init(), and reRollSingles().
The documentation for this class was generated from the following files:
VortexEngine/src/Menus/MenuList/Randomizer.h
VortexEngine/src/Menus/MenuList/Randomizer.cpp