Modes::ModeLink Class Reference
Public Member Functions
ModeLink (VortexEngine &engine, const Mode *src=nullptr, bool inst=false)
ModeLink (VortexEngine &engine, const ByteStream &src, bool inst=false)
~ModeLink ()
bool init (const Mode *mode=nullptr)
bool append (const Mode *next)
bool append (const ByteStream &next)
void play ()
ModeLink * unlinkSelf ()
void linkAfter (ModeLink *link)
void linkBefore (ModeLink *link)
Mode * instantiate ()
void uninstantiate ()
bool save ()
ByteStream & buffer ()
Mode * mode ()
ModeLink * next ()
ModeLink * prev ()
operator ByteStream & ()
operator ByteStream ()
operator Mode * ()
Private Attributes
VortexEngine & m_engine
Mode * m_pInstantiatedMode
ByteStream m_storedMode
ModeLink * m_next
ModeLink * m_prev
Detailed Description
Definition at line 181 of file Modes.h.
Constructor & Destructor Documentation
ModeLink() [1/2]
Modes::ModeLink::ModeLink (VortexEngine & engine, const Mode * src = nullptr, bool inst = false)
Definition at line 820 of file Modes.cpp.
                                                                        :
  m_engine(engine),
  m_pInstantiatedMode(nullptr),
  m_storedMode(),
  m_next(nullptr),
  m_prev(nullptr)
{
  if (src) {
    init(src);
  }
  if (src && inst) {
    instantiate();
  }
}
References init(), and instantiate().
ModeLink() [2/2]
Modes::ModeLink::ModeLink (VortexEngine & engine, const ByteStream & src, bool inst = false)
Definition at line 835 of file Modes.cpp.
                                                                              :
  m_engine(engine),
  m_pInstantiatedMode(nullptr),
  m_storedMode(src),
  m_next(nullptr),
  m_prev(nullptr)
{
  if (src.size() && inst) {
    instantiate();
  }
}
References instantiate(), and ByteStream::size().
 ModeLink()
Modes::ModeLink::~ModeLink ()
Definition at line 847 of file Modes.cpp.
{
  if (m_next) {
    delete m_next;
  }
  if (m_pInstantiatedMode) {
    delete m_pInstantiatedMode;
  }
}
Member Function Documentation
append() [1/2]
bool Modes::ModeLink::append (const ByteStream & next)
Definition at line 888 of file Modes.cpp.
{
  if (!next.size()) {
    return false;
  }
  // if not end of chain, recurse on next link
  if (m_next) {
    return m_next->append(next);
  }
  m_next = new ModeLink(m_engine, next);
  if (!m_next) {
    ERROR_OUT_OF_MEMORY();
    return false;
  }
  m_next->m_prev = this;
  return true;
}
References ERROR_OUT_OF_MEMORY, Modes::m_engine, and ByteStream::size().
append() [2/2]
bool Modes::ModeLink::append (const Mode * next)
Definition at line 870 of file Modes.cpp.
{
  if (!next) {
    return false;
  }
  // if not end of chain, recurse on next link
  if (m_next) {
    return m_next->append(next);
  }
  m_next = new ModeLink(m_engine, next);
  if (!m_next) {
    ERROR_OUT_OF_MEMORY();
    return false;
  }
  m_next->m_prev = this;
  return true;
}
References ERROR_OUT_OF_MEMORY, and Modes::m_engine.
Referenced by Modes::addMode(), and Modes::addModeFromBuffer().
buffer()
ByteStream& Modes::ModeLink::buffer () [inline]
Definition at line 212 of file Modes.h.
{ return m_storedMode; }
References m_storedMode.
init()
bool Modes::ModeLink::init (const Mode * mode = nullptr)
Definition at line 857 of file Modes.cpp.
{
  if (!mode) {
    return false;
  }
  m_storedMode.clear();
  // serialize the mode so it can be instantiated anytime
  if (!mode->saveToBuffer(m_storedMode)) {
    return false;
  }
  return true;
}
References Mode::saveToBuffer().
Referenced by ModeLink().
instantiate()
Mode * Modes::ModeLink::instantiate ()
Definition at line 957 of file Modes.cpp.
{
  if (m_pInstantiatedMode) {
    return m_pInstantiatedMode;
  }
  Mode *newMode = new Mode(m_engine);
  if (!newMode) {
    ERROR_OUT_OF_MEMORY();
    return nullptr;
  }
  m_storedMode.resetUnserializer();
  if (!newMode->loadFromBuffer(m_storedMode)) {
    return nullptr;
  }
  // TODO: init new mode?
  m_pInstantiatedMode = newMode;
  return m_pInstantiatedMode;
}
References ERROR_OUT_OF_MEMORY, Mode::loadFromBuffer(), and Modes::m_engine.
Referenced by Modes::curMode(), Modes::initCurMode(), ModeLink(), Modes::saveStorage(), Modes::serialize(), and Modes::setCurMode().
linkAfter()
void Modes::ModeLink::linkAfter (ModeLink * link)
Definition at line 931 of file Modes.cpp.
{
  if (!link) {
    return;
  }
  if (m_next) {
    m_next->m_prev = link;
    link->m_next = m_next;
  }
  m_next = link;
  link->m_prev = this;
}
References m_next, and m_prev.
Referenced by Modes::shiftCurMode().
linkBefore()
void Modes::ModeLink::linkBefore (ModeLink * link)
Definition at line 944 of file Modes.cpp.
{
  if (!link) {
    return;
  }
  if (m_prev) {
    m_prev->m_next = link;
    link->m_prev = m_prev;
  }
  m_prev = link;
  link->m_next = this;
}
References m_next, and m_prev.
Referenced by Modes::shiftCurMode().
mode()
Mode* Modes::ModeLink::mode () [inline]
Definition at line 213 of file Modes.h.
{ return m_pInstantiatedMode; }
References m_pInstantiatedMode.
Referenced by Modes::curModeInstantiated().
next()
ModeLink* Modes::ModeLink::next () [inline]
Definition at line 214 of file Modes.h.
{ return m_next; }
References m_next.
Referenced by Modes::getModeLink(), Modes::saveStorage(), Modes::serialize(), and Modes::shiftCurMode().
operator ByteStream()
Modes::ModeLink::operator ByteStream () [inline]
Definition at line 218 of file Modes.h.
{ return m_storedMode; }
References m_storedMode.
operator ByteStream &()
Modes::ModeLink::operator ByteStream & () [inline]
Definition at line 217 of file Modes.h.
{ return m_storedMode; }
References m_storedMode.
operator Mode *()
Modes::ModeLink::operator Mode * () [inline]
Definition at line 219 of file Modes.h.
{ return m_pInstantiatedMode; }
References m_pInstantiatedMode.
play()
void Modes::ModeLink::play ()
Definition at line 906 of file Modes.cpp.
{
  if (!m_pInstantiatedMode) {
    return;
  }
  m_pInstantiatedMode->play();
}
Referenced by Modes::play().
prev()
ModeLink* Modes::ModeLink::prev () [inline]
Definition at line 215 of file Modes.h.
{ return m_prev; }
References m_prev.
save()
bool Modes::ModeLink::save ()
Definition at line 984 of file Modes.cpp.
{
  if (!m_pInstantiatedMode) {
    return false;
  }
  m_storedMode.clear();
  return m_pInstantiatedMode->saveToBuffer(m_storedMode);
}
Referenced by Modes::saveCurMode().
uninstantiate()
void Modes::ModeLink::uninstantiate ()
Definition at line 976 of file Modes.cpp.
{
  if (m_pInstantiatedMode) {
    delete m_pInstantiatedMode;
    m_pInstantiatedMode = nullptr;
  }
}
Referenced by Modes::initCurMode(), Modes::saveStorage(), Modes::serialize(), and Modes::setCurMode().
unlinkSelf()
Modes::ModeLink * Modes::ModeLink::unlinkSelf ()
Definition at line 914 of file Modes.cpp.
{
  // unlink this node from the chain
  if (m_prev) {
    m_prev->m_next = m_next;
  }
  if (m_next) {
    m_next->m_prev = m_prev;
  }
  // grab the new link that will take this place
  ModeLink *newLink = m_prev ? m_prev : m_next;
  // clear the links of this node
  m_prev = nullptr;
  m_next = nullptr;
  return newLink;
}
References m_next, and m_prev.
Referenced by Modes::deleteCurMode(), and Modes::shiftCurMode().
Member Data Documentation
m_engine
VortexEngine& Modes::ModeLink::m_engine [private]
Definition at line 221 of file Modes.h.
m_next
ModeLink* Modes::ModeLink::m_next [private]
Definition at line 224 of file Modes.h.
Referenced by linkAfter(), linkBefore(), next(), and unlinkSelf().
m_pInstantiatedMode
Mode* Modes::ModeLink::m_pInstantiatedMode [private]
Definition at line 222 of file Modes.h.
Referenced by mode(), and operator Mode *().
m_prev
ModeLink* Modes::ModeLink::m_prev [private]
Definition at line 225 of file Modes.h.
Referenced by linkAfter(), linkBefore(), prev(), and unlinkSelf().
m_storedMode
ByteStream Modes::ModeLink::m_storedMode [private]
Definition at line 223 of file Modes.h.
Referenced by buffer(), operator ByteStream(), and operator ByteStream &().
The documentation for this class was generated from the following files:
VortexEngine/src/Modes/Modes.h
VortexEngine/src/Modes/Modes.cpp