SparkleTracePattern Class Reference
#include <SparkleTracePattern.h>
Public Member Functions
SparkleTracePattern (VortexEngine &engine, const PatternArgs &args)
virtual ~SparkleTracePattern ()
Protected Member Functions
virtual void blinkOn () override
virtual void poststep () override
Protected Attributes
Random m_randCtx
Detailed Description
Definition at line 8 of file SparkleTracePattern.h.
Constructor & Destructor Documentation
SparkleTracePattern()
SparkleTracePattern::SparkleTracePattern (VortexEngine & engine, const PatternArgs & args)
Definition at line 9 of file SparkleTracePattern.cpp.
                                                                                      :
  BlinkStepPattern(engine, args),
  m_randCtx()
{
  m_patternID = PATTERN_SPARKLETRACE;
  setArgs(args);
}
References Pattern::m_patternID, PATTERN_SPARKLETRACE, and Pattern::setArgs().
 SparkleTracePattern()
SparkleTracePattern::~SparkleTracePattern () [virtual]
Definition at line 17 of file SparkleTracePattern.cpp.
{
}
Member Function Documentation
blinkOn()
void SparkleTracePattern::blinkOn () [override], [protected], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 21 of file SparkleTracePattern.cpp.
{
  m_engine.leds().setAll(m_colorset.get(0));
}
References Colorset::get(), VortexEngine::leds(), Pattern::m_colorset, Pattern::m_engine, and Leds::setAll().
poststep()
void SparkleTracePattern::poststep () [override], [protected], [virtual]
Reimplemented from BlinkStepPattern.
Definition at line 26 of file SparkleTracePattern.cpp.
{
  for (uint8_t dot = 0; dot < 4; ++dot) {
    m_engine.leds().setPair((Pair)m_randCtx.next8(PAIR_FIRST, PAIR_LAST), m_colorset.cur());
  }
  m_colorset.skip();
  if (m_colorset.curIndex() == 0) {
    m_colorset.skip();
  }
}
References Colorset::cur(), Colorset::curIndex(), VortexEngine::leds(), Pattern::m_colorset, Pattern::m_engine, m_randCtx, Random::next8(), PAIR_FIRST, PAIR_LAST, Leds::setPair(), and Colorset::skip().
Member Data Documentation
m_randCtx
Random SparkleTracePattern::m_randCtx [protected]
Definition at line 18 of file SparkleTracePattern.h.
Referenced by poststep().
The documentation for this class was generated from the following files:
VortexEngine/src/Patterns/Multi/SparkleTracePattern.h
VortexEngine/src/Patterns/Multi/SparkleTracePattern.cpp