PatternBuilder Class Reference
#include <PatternBuilder.h>
Public Member Functions
PatternBuilder (VortexEngine &engine)
~PatternBuilder ()
bool init ()
void cleanup ()
Pattern * make (PatternID id, const PatternArgs *args=nullptr)
Pattern * dupe (const Pattern *pat)
SingleLedPattern * makeSingle (PatternID id, const PatternArgs *args=nullptr)
MultiLedPattern * makeMulti (PatternID id, const PatternArgs *args=nullptr)
Pattern * unserialize (ByteStream &buffer)
PatternArgs getDefaultArgs (PatternID id)
uint8_t numDefaultArgs (PatternID id)
bool isDefaultArgs (PatternID id, const PatternArgs &args)
Private Member Functions
Pattern * makeInternal (PatternID id, const PatternArgs *args=nullptr)
Pattern * generate (PatternID id, const PatternArgs *args=nullptr)
Private Attributes
VortexEngine & m_engine
Detailed Description
Definition at line 13 of file PatternBuilder.h.
Constructor & Destructor Documentation
PatternBuilder()
PatternBuilder::PatternBuilder (VortexEngine & engine)
Definition at line 38 of file PatternBuilder.cpp.
                                                   :
  m_engine(engine)
{
}
 PatternBuilder()
PatternBuilder::~PatternBuilder ()
Definition at line 43 of file PatternBuilder.cpp.
{
}
Member Function Documentation
cleanup()
void PatternBuilder::cleanup ()
Definition at line 52 of file PatternBuilder.cpp.
{
}
Referenced by VortexEngine::cleanup().
dupe()
Pattern * PatternBuilder::dupe (const Pattern * pat)
Definition at line 74 of file PatternBuilder.cpp.
{
  if (!pat) {
    return nullptr;
  }
  PatternArgs args;
  pat->getArgs(args);
  Pattern *newPat = make(pat->getPatternID(), &args);
  if (!newPat) {
    return nullptr;
  }
  newPat->setColorset(pat->getColorset());
  newPat->bind(pat->getLedPos());
  return newPat;
}
References Pattern::bind(), Pattern::getArgs(), Pattern::getColorset(), Pattern::getLedPos(), Pattern::getPatternID(), make(), and Pattern::setColorset().
Referenced by Mode::operator=(), and Mode::unserialize().
generate()
Pattern * PatternBuilder::generate (PatternID id, const PatternArgs * args = nullptr) [private]
Definition at line 246 of file PatternBuilder.cpp.
{
  PatternArgs args = userArgs ? *userArgs : getDefaultArgs(id);
  switch (id) {
    // =====================
    // Single Led Patterns:
    default:
    case PATTERN_STROBE:
    case PATTERN_HYPERSTROBE:
    case PATTERN_PICOSTROBE:
    case PATTERN_STROBIE:
    case PATTERN_DOPS:
    case PATTERN_ULTRADOPS:
    case PATTERN_STROBEGAP:
    case PATTERN_HYPERGAP:
    case PATTERN_PICOGAP:
    case PATTERN_STROBIEGAP:
    case PATTERN_DOPSGAP:
    case PATTERN_ULTRAGAP:
    case PATTERN_BLINKIE:
    case PATTERN_GHOSTCRUSH:
    case PATTERN_DOUBLEDOPS:
    case PATTERN_CHOPPER:
    case PATTERN_DASHGAP:
    case PATTERN_DASHDOPS:
    case PATTERN_DASHCRUSH:
    case PATTERN_ULTRADASH:
    case PATTERN_GAPCYCLE:
    case PATTERN_DASHCYCLE:
    case PATTERN_TRACER:
    case PATTERN_RIBBON:
    case PATTERN_MINIRIBBON: return new BasicPattern(m_engine, args);
    case PATTERN_BLEND:
    case PATTERN_BLENDSTROBE:
    case PATTERN_BLENDSTROBEGAP:
    case PATTERN_COMPLEMENTARY_BLEND:
    case PATTERN_COMPLEMENTARY_BLENDSTROBE:
    case PATTERN_COMPLEMENTARY_BLENDSTROBEGAP: return new BlendPattern(m_engine, args);
    case PATTERN_SOLID: return new SolidPattern(m_engine, args);
    // =====================
    // Multi Led Patterns:
#if VORTEX_SLIM == 0
    case PATTERN_HUE_SCROLL: return new HueShiftPattern(m_engine, args);
    case PATTERN_THEATER_CHASE: return new TheaterChasePattern(m_engine, args);
    case PATTERN_CHASER: return new ChaserPattern(m_engine, args);
    case PATTERN_ZIGZAG:
    case PATTERN_ZIPFADE: return new ZigzagPattern(m_engine, args);
    case PATTERN_DRIP: return new DripPattern(m_engine, args);
    case PATTERN_DRIPMORPH: return new DripMorphPattern(m_engine, args);
    case PATTERN_CROSSDOPS: return new CrossDopsPattern(m_engine, args);
    case PATTERN_DOUBLESTROBE: return new DoubleStrobePattern(m_engine, args);
    case PATTERN_METEOR: return new MeteorPattern(m_engine, args);
    case PATTERN_SPARKLETRACE: return new SparkleTracePattern(m_engine, args);
    case PATTERN_VORTEXWIPE: return new VortexWipePattern(m_engine, args);
    case PATTERN_WARP: return new WarpPattern(m_engine, args);
    case PATTERN_WARPWORM: return new WarpWormPattern(m_engine, args);
    case PATTERN_SNOWBALL: return new SnowballPattern(m_engine, args);
    case PATTERN_LIGHTHOUSE: return new LighthousePattern(m_engine, args);
    case PATTERN_PULSISH: return new PulsishPattern(m_engine, args);
    case PATTERN_FILL: return new FillPattern(m_engine, args);
    case PATTERN_BOUNCE: return new BouncePattern(m_engine, args);
    case PATTERN_SPLITSTROBIE:
    case PATTERN_BACKSTROBE: return new BackStrobePattern(m_engine, args);
    case PATTERN_VORTEX: return new VortexPattern(m_engine, args);
    case PATTERN_NONE: return nullptr;
#else
    // in vortex slim just use basic pattern for all multi led
    case PATTERN_NONE: return nullptr;
#endif
  }
  DEBUG_LOGF("Unknown pattern id: %u", id);
  return nullptr;
}
References DEBUG_LOGF, getDefaultArgs(), m_engine, PATTERN_BACKSTROBE, PATTERN_BLEND, PATTERN_BLENDSTROBE, PATTERN_BLENDSTROBEGAP, PATTERN_BLINKIE, PATTERN_BOUNCE, PATTERN_CHASER, PATTERN_CHOPPER, PATTERN_COMPLEMENTARY_BLEND, PATTERN_COMPLEMENTARY_BLENDSTROBE, PATTERN_COMPLEMENTARY_BLENDSTROBEGAP, PATTERN_CROSSDOPS, PATTERN_DASHCRUSH, PATTERN_DASHCYCLE, PATTERN_DASHDOPS, PATTERN_DASHGAP, PATTERN_DOPS, PATTERN_DOPSGAP, PATTERN_DOUBLEDOPS, PATTERN_DOUBLESTROBE, PATTERN_DRIP, PATTERN_DRIPMORPH, PATTERN_FILL, PATTERN_GAPCYCLE, PATTERN_GHOSTCRUSH, PATTERN_HUE_SCROLL, PATTERN_HYPERGAP, PATTERN_HYPERSTROBE, PATTERN_LIGHTHOUSE, PATTERN_METEOR, PATTERN_MINIRIBBON, PATTERN_NONE, PATTERN_PICOGAP, PATTERN_PICOSTROBE, PATTERN_PULSISH, PATTERN_RIBBON, PATTERN_SNOWBALL, PATTERN_SOLID, PATTERN_SPARKLETRACE, PATTERN_SPLITSTROBIE, PATTERN_STROBE, PATTERN_STROBEGAP, PATTERN_STROBIE, PATTERN_STROBIEGAP, PATTERN_THEATER_CHASE, PATTERN_TRACER, PATTERN_ULTRADASH, PATTERN_ULTRADOPS, PATTERN_ULTRAGAP, PATTERN_VORTEX, PATTERN_VORTEXWIPE, PATTERN_WARP, PATTERN_WARPWORM, PATTERN_ZIGZAG, and PATTERN_ZIPFADE.
Referenced by makeInternal().
getDefaultArgs()
PatternArgs PatternBuilder::getDefaultArgs (PatternID id)
Definition at line 150 of file PatternBuilder.cpp.
{
  switch (id) {
    // =====================
    // Single Led Patterns:
    case PATTERN_STROBE: return PatternArgs(STROBE_ON_DURATION, STROBE_OFF_DURATION);
    case PATTERN_HYPERSTROBE: return PatternArgs(HYPERSTROBE_ON_DURATION, HYPERSTROBE_OFF_DURATION);
    case PATTERN_PICOSTROBE: return PatternArgs(PICOSTROBE_ON_DURATION, PICOSTROBE_OFF_DURATION);
    case PATTERN_STROBIE: return PatternArgs(STROBIE_ON_DURATION, STROBIE_OFF_DURATION);
    case PATTERN_DOPS: return PatternArgs(DOPS_ON_DURATION, DOPS_OFF_DURATION);
    case PATTERN_ULTRADOPS: return PatternArgs(ULTRADOPS_ON_DURATION, ULTRADOPS_OFF_DURATION);
    case PATTERN_STROBEGAP: return PatternArgs(STROBE_ON_DURATION, STROBE_OFF_DURATION, 25);
    case PATTERN_HYPERGAP: return PatternArgs(HYPERSTROBE_ON_DURATION, HYPERSTROBE_OFF_DURATION, 218);
    case PATTERN_PICOGAP: return PatternArgs(PICOSTROBE_ON_DURATION, PICOSTROBE_OFF_DURATION, 90);
    case PATTERN_STROBIEGAP: return PatternArgs(STROBIE_ON_DURATION, STROBIE_OFF_DURATION, 100);
    case PATTERN_DOPSGAP: return PatternArgs(DOPS_ON_DURATION, DOPS_OFF_DURATION, 40);
    case PATTERN_ULTRAGAP: return PatternArgs(ULTRADOPS_ON_DURATION, ULTRADOPS_OFF_DURATION, 55);
    case PATTERN_BLINKIE: return PatternArgs(3, 1, 65);
    case PATTERN_GHOSTCRUSH: return PatternArgs(3, 1, 18);
    case PATTERN_DOUBLEDOPS: return PatternArgs(ULTRADOPS_ON_DURATION, ULTRADOPS_OFF_DURATION, DOPS_OFF_DURATION, 0, 2);
    case PATTERN_CHOPPER: return PatternArgs(ULTRADOPS_ON_DURATION, STROBIE_OFF_DURATION, 0, STROBE_ON_DURATION);
    case PATTERN_DASHGAP: return PatternArgs(ULTRADOPS_ON_DURATION, ULTRADOPS_OFF_DURATION, 20, 20);
    case PATTERN_DASHDOPS: return PatternArgs(DOPS_ON_DURATION, DOPS_OFF_DURATION, DOPS_OFF_DURATION, 18);
    case PATTERN_DASHCRUSH: return PatternArgs(4, 1, 10, 18);
    case PATTERN_ULTRADASH: return PatternArgs(ULTRADOPS_ON_DURATION, ULTRADOPS_OFF_DURATION, ULTRADOPS_OFF_DURATION, 14);
    case PATTERN_GAPCYCLE: return PatternArgs(STROBIE_ON_DURATION, STROBE_OFF_DURATION, 12, 25, 2);
    case PATTERN_DASHCYCLE: return PatternArgs(ULTRADOPS_ON_DURATION, ULTRADOPS_OFF_DURATION, ULTRADOPS_OFF_DURATION, 30, 2);
    case PATTERN_TRACER: return PatternArgs(3, 0, 0, 20, 1);
    case PATTERN_RIBBON: return PatternArgs(RIBBON_DURATION);
    case PATTERN_MINIRIBBON: return PatternArgs(1);
    case PATTERN_BLEND: return PatternArgs(BLEND_ON_DURATION, BLEND_OFF_DURATION, 0, 0, 0, 5, 0);
    case PATTERN_BLENDSTROBE: return PatternArgs(STROBE_ON_DURATION, STROBE_OFF_DURATION, 0, 0, 0, 10, 0);
    case PATTERN_BLENDSTROBEGAP: return PatternArgs(STROBE_ON_DURATION, STROBE_OFF_DURATION, 25, 0, 0, 10, 0);
    case PATTERN_COMPLEMENTARY_BLEND: return PatternArgs(BLEND_ON_DURATION, BLEND_OFF_DURATION, 0, 0, 0, 5, 1);
    case PATTERN_COMPLEMENTARY_BLENDSTROBE: return PatternArgs(STROBE_ON_DURATION, STROBE_OFF_DURATION, 0, 0, 0, 10, 1);
    case PATTERN_COMPLEMENTARY_BLENDSTROBEGAP: return PatternArgs(STROBE_ON_DURATION, STROBE_OFF_DURATION, 25, 0, 0, 10, 1);
    case PATTERN_SOLID: return PatternArgs(250);
    // =====================
    // Multi Led Patterns:
#if VORTEX_SLIM == 0
    case PATTERN_HUE_SCROLL: return PatternArgs(1, 1, 10);
    case PATTERN_THEATER_CHASE: return PatternArgs(DOPS_ON_DURATION, DOPS_OFF_DURATION, 28);
    case PATTERN_CHASER: return PatternArgs();
    case PATTERN_ZIGZAG: return PatternArgs(DOPS_ON_DURATION, 3, 3, 5, 55);
    case PATTERN_ZIPFADE: return PatternArgs(DOPS_ON_DURATION, 2, 75, 9, 230);
    case PATTERN_DRIP: return PatternArgs(STROBE_ON_DURATION, STROBE_OFF_DURATION, 150);
    case PATTERN_DRIPMORPH: return PatternArgs(STROBE_ON_DURATION, STROBE_OFF_DURATION, 1);
    case PATTERN_CROSSDOPS: return PatternArgs(DOPS_ON_DURATION, 2, 25);
    case PATTERN_DOUBLESTROBE: return PatternArgs(DOPS_ON_DURATION, DOPS_OFF_DURATION, 115);
    case PATTERN_METEOR: return PatternArgs(1, 1, 20, 130);
    case PATTERN_SPARKLETRACE: return PatternArgs(1, 5, 3);
    case PATTERN_VORTEXWIPE: return PatternArgs(DOPS_ON_DURATION, 3, 80);
    case PATTERN_WARP: return PatternArgs(3, DOPS_OFF_DURATION, 50);
    case PATTERN_WARPWORM: return PatternArgs(DOPS_ON_DURATION, 10, 100);
    case PATTERN_SNOWBALL: return PatternArgs(3, 3, 33);
    case PATTERN_LIGHTHOUSE: return PatternArgs(DOPS_ON_DURATION, 5, 22, 3, 3);
    case PATTERN_PULSISH: return PatternArgs(DOPS_ON_DURATION, 6, 5, 1, 100);
    case PATTERN_FILL: return PatternArgs(DOPS_ON_DURATION, 5, 50);
    case PATTERN_BOUNCE: return PatternArgs(10, 5, 50, 10);
    case PATTERN_SPLITSTROBIE: return PatternArgs(DOPS_ON_DURATION, DOPS_OFF_DURATION, 0, 16, 3, 10, PATTERN_DOPS, PATTERN_STROBIE);
    case PATTERN_BACKSTROBE: return PatternArgs(DOPS_ON_DURATION, DOPS_OFF_DURATION, 0, HYPERSTROBE_ON_DURATION, HYPERSTROBE_OFF_DURATION, 10, PATTERN_DOPS, PATTERN_HYPERSTROBE);
    case PATTERN_VORTEX: return PatternArgs(1, 1, 130);
    case PATTERN_NONE: break;
    default: break;
#else
    // in vortex slim just use DOPS for all mult-led
    case PATTERN_NONE: break;
    default: return PatternArgs(DOPS_ON_DURATION, DOPS_OFF_DURATION);
#endif
  }
  return PatternArgs();
}
References BLEND_OFF_DURATION, BLEND_ON_DURATION, DOPS_OFF_DURATION, DOPS_ON_DURATION, HYPERSTROBE_OFF_DURATION, HYPERSTROBE_ON_DURATION, PATTERN_BACKSTROBE, PATTERN_BLEND, PATTERN_BLENDSTROBE, PATTERN_BLENDSTROBEGAP, PATTERN_BLINKIE, PATTERN_BOUNCE, PATTERN_CHASER, PATTERN_CHOPPER, PATTERN_COMPLEMENTARY_BLEND, PATTERN_COMPLEMENTARY_BLENDSTROBE, PATTERN_COMPLEMENTARY_BLENDSTROBEGAP, PATTERN_CROSSDOPS, PATTERN_DASHCRUSH, PATTERN_DASHCYCLE, PATTERN_DASHDOPS, PATTERN_DASHGAP, PATTERN_DOPS, PATTERN_DOPSGAP, PATTERN_DOUBLEDOPS, PATTERN_DOUBLESTROBE, PATTERN_DRIP, PATTERN_DRIPMORPH, PATTERN_FILL, PATTERN_GAPCYCLE, PATTERN_GHOSTCRUSH, PATTERN_HUE_SCROLL, PATTERN_HYPERGAP, PATTERN_HYPERSTROBE, PATTERN_LIGHTHOUSE, PATTERN_METEOR, PATTERN_MINIRIBBON, PATTERN_NONE, PATTERN_PICOGAP, PATTERN_PICOSTROBE, PATTERN_PULSISH, PATTERN_RIBBON, PATTERN_SNOWBALL, PATTERN_SOLID, PATTERN_SPARKLETRACE, PATTERN_SPLITSTROBIE, PATTERN_STROBE, PATTERN_STROBEGAP, PATTERN_STROBIE, PATTERN_STROBIEGAP, PATTERN_THEATER_CHASE, PATTERN_TRACER, PATTERN_ULTRADASH, PATTERN_ULTRADOPS, PATTERN_ULTRAGAP, PATTERN_VORTEX, PATTERN_VORTEXWIPE, PATTERN_WARP, PATTERN_WARPWORM, PATTERN_ZIGZAG, PATTERN_ZIPFADE, PICOSTROBE_OFF_DURATION, PICOSTROBE_ON_DURATION, RIBBON_DURATION, STROBE_OFF_DURATION, STROBE_ON_DURATION, STROBIE_OFF_DURATION, STROBIE_ON_DURATION, ULTRADOPS_OFF_DURATION, and ULTRADOPS_ON_DURATION.
Referenced by generate(), isDefaultArgs(), Pattern::serialize(), and Pattern::unserialize().
init()
bool PatternBuilder::init ()
Definition at line 47 of file PatternBuilder.cpp.
{
  return true;
}
Referenced by VortexEngine::init().
isDefaultArgs()
bool PatternBuilder::isDefaultArgs (PatternID id, const PatternArgs & args)
Definition at line 224 of file PatternBuilder.cpp.
{
  PatternArgs defaultArgs = getDefaultArgs(id);
  // force the number of args to match, the defaults returned from the above
  // API will have the wrong number of args
  defaultArgs.numArgs = args.numArgs;
  // now compare them
  return (args == defaultArgs);
}
References getDefaultArgs(), and PatternArgs::numArgs.
Referenced by Vortex::getPatternName().
make()
Pattern * PatternBuilder::make (PatternID id, const PatternArgs * args = nullptr)
Definition at line 56 of file PatternBuilder.cpp.
{
#if VORTEX_SLIM == 0
  if (id > PATTERN_LAST) {
#else
  if (id > PATTERN_SINGLE_LAST) {
#endif
    DEBUG_LOGF("Invalid pattern id: %u", id);
    id = PATTERN_FIRST;
  }
#if VORTEX_SLIM == 0
  if (isMultiLedPatternID(id)) {
    return makeMulti(id, args);
  }
#endif
  return makeSingle(id, args);
}
References DEBUG_LOGF, isMultiLedPatternID(), makeMulti(), makeSingle(), PATTERN_FIRST, PATTERN_LAST, and PATTERN_SINGLE_LAST.
Referenced by dupe(), Vortex::getCustomParams(), numDefaultArgs(), Vortex::patternFromJson(), and unserialize().
makeInternal()
Pattern * PatternBuilder::makeInternal (PatternID id, const PatternArgs * args = nullptr) [private]
Definition at line 134 of file PatternBuilder.cpp.
{
  if (id == PATTERN_NONE) {
    // no error
    return nullptr;
  }
  Pattern *pat = generate(id, args);
  if (!pat) {
    ERROR_OUT_OF_MEMORY();
    return nullptr;
  }
  // set private pattern ID via friend class relationship
  pat->m_patternID = id;
  return pat;
}
References ERROR_OUT_OF_MEMORY, generate(), Pattern::m_patternID, and PATTERN_NONE.
Referenced by makeMulti(), and makeSingle().
makeMulti()
MultiLedPattern * PatternBuilder::makeMulti (PatternID id, const PatternArgs * args = nullptr)
Definition at line 105 of file PatternBuilder.cpp.
{
  if (!isMultiLedPatternID(id)) {
    return nullptr;
  }
  Pattern *pat = makeInternal(id, args);
  if (!pat) {
    return nullptr;
  }
  return (MultiLedPattern *)pat;
}
References isMultiLedPatternID(), and makeInternal().
Referenced by make(), and Mode::setPattern().
makeSingle()
SingleLedPattern * PatternBuilder::makeSingle (PatternID id, const PatternArgs * args = nullptr)
Definition at line 91 of file PatternBuilder.cpp.
{
  if (!isSingleLedPatternID(id)) {
    return nullptr;
  }
  Pattern *pat = makeInternal(id, args);
  if (!pat) {
    return nullptr;
  }
  // don't set any flags on single pattersn
  return (SingleLedPattern *)pat;
}
References isSingleLedPatternID(), and makeInternal().
Referenced by make(), SequencedPattern::playSequenceStep(), CompoundPattern::setEvensOdds(), Mode::setPattern(), and CompoundPattern::setPatternAt().
numDefaultArgs()
uint8_t PatternBuilder::numDefaultArgs (PatternID id)
Definition at line 234 of file PatternBuilder.cpp.
{
  Pattern *pat = make(id);
  if (!pat) {
    return 0;
  }
  uint8_t numArgs = pat->getNumArgs();
  delete pat;
  return numArgs;
}
References Pattern::getNumArgs(), and make().
Referenced by Vortex::numCustomParams().
unserialize()
Pattern * PatternBuilder::unserialize (ByteStream & buffer)
Definition at line 117 of file PatternBuilder.cpp.
{
  PatternID id = PATTERN_NONE;
  if (!buffer.unserialize8((uint8_t *)&id)) {
    return nullptr;
  }
  Pattern *pat = make(id);
  if (!pat) {
    return nullptr;
  }
  if (!pat->unserialize(buffer)) {
    delete pat;
    return nullptr;
  }
  return pat;
}
References make(), PATTERN_NONE, Pattern::unserialize(), and ByteStream::unserialize8().
Referenced by Mode::unserialize().
Member Data Documentation
m_engine
VortexEngine& PatternBuilder::m_engine [private]
Definition at line 52 of file PatternBuilder.h.
Referenced by generate().
The documentation for this class was generated from the following files:
VortexEngine/src/Patterns/PatternBuilder.h
VortexEngine/src/Patterns/PatternBuilder.cpp