ModeSharing Class Reference
#include <ModeSharing.h>
Public Member Functions
ModeSharing (const RGBColor &col, bool advanced)
~ModeSharing ()
bool init () override
MenuAction run () override
void onShortClick () override
void onLongClick () override
Private Types
enum class ModeShareState { SHARE_SEND_IR
, SHARE_SEND_VL
, SHARE_RECEIVE
 }
Private Member Functions
void beginSendingVL ()
void beginSendingIR ()
void continueSendingVL ()
void continueSendingIR ()
void beginReceivingIR ()
void receiveModeIR ()
void showSendModeVL ()
void showSendModeIR ()
void showReceiveMode ()
Private Attributes
ModeShareState m_sharingMode
uint32_t m_timeOutStartTime
uint32_t m_lastSendTime
bool m_shouldEndSend
Additional Inherited Members
Detailed Description
Definition at line 6 of file ModeSharing.h.
Member Enumeration Documentation
ModeShareState
enum ModeSharing::ModeShareState [strong], [private]
Enumerator
SHARE_SEND_IR
SHARE_SEND_VL
SHARE_RECEIVE
Definition at line 31 of file ModeSharing.h.
                            {
    SHARE_SEND_IR, // send mode over ir
    SHARE_SEND_VL, // send mode over vl
    SHARE_RECEIVE, // receive mode
  };
Constructor & Destructor Documentation
ModeSharing()
ModeSharing::ModeSharing (const RGBColor & col, bool advanced)
Definition at line 16 of file ModeSharing.cpp.
                                                           :
  Menu(col, advanced),
  m_sharingMode(ModeShareState::SHARE_RECEIVE),
  m_timeOutStartTime(0),
  m_lastSendTime(0),
  m_shouldEndSend(false)
{
}
 ModeSharing()
ModeSharing::~ModeSharing ()
Definition at line 25 of file ModeSharing.cpp.
{
}
Member Function Documentation
beginReceivingIR()
void ModeSharing::beginReceivingIR () [private]
Definition at line 171 of file ModeSharing.cpp.
{
  m_sharingMode = ModeShareState::SHARE_RECEIVE;
  IRReceiver::beginReceiving();
}
References IRReceiver::beginReceiving(), m_sharingMode, and SHARE_RECEIVE.
Referenced by beginSendingVL(), continueSendingIR(), continueSendingVL(), init(), and onShortClick().
beginSendingIR()
void ModeSharing::beginSendingIR () [private]
Definition at line 120 of file ModeSharing.cpp.
{
  // if the sender is sending then cannot start again
  if (IRSender::isSending()) {
    ERROR_LOG("Cannot begin sending, sender is busy");
    return;
  }
  m_sharingMode = ModeShareState::SHARE_SEND_IR;
  Leds::clearAll();
  Leds::update();
  // initialize it with the current mode data
  IRSender::loadMode(Modes::curMode());
  // send the first chunk of data, leave if we're done
  if (!IRSender::send()) {
    // just set the last time and wait
    m_lastSendTime = Time::getCurtime();
  }
}
References Leds::clearAll(), Modes::curMode(), ERROR_LOG, Time::getCurtime(), IRSender::isSending(), IRSender::loadMode(), m_lastSendTime, m_sharingMode, IRSender::send(), SHARE_SEND_IR, and Leds::update().
Referenced by continueSendingIR(), and onShortClick().
beginSendingVL()
void ModeSharing::beginSendingVL () [private]
Definition at line 103 of file ModeSharing.cpp.
{
  // if the sender is sending then cannot start again
  if (VLSender::isSending()) {
    ERROR_LOG("Cannot begin sending, sender is busy");
    return;
  }
  m_sharingMode = ModeShareState::SHARE_SEND_VL;
  // initialize it with the current mode data
  VLSender::loadMode(Modes::curMode());
  // send the first chunk of data, leave if we're done
  if (!VLSender::send()) {
    // when send has completed, stores time that last action was completed to calculate interval between sends
    beginReceivingIR();
  }
}
References beginReceivingIR(), Modes::curMode(), ERROR_LOG, VLSender::isSending(), VLSender::loadMode(), m_sharingMode, VLSender::send(), and SHARE_SEND_VL.
continueSendingIR()
void ModeSharing::continueSendingIR () [private]
Definition at line 151 of file ModeSharing.cpp.
{
  // if the sender isn't sending then nothing to do
  if (!IRSender::isSending()) {
    if (m_lastSendTime && m_lastSendTime < (Time::getCurtime() + MS_TO_TICKS(350))) {
      if (m_shouldEndSend) {
        beginReceivingIR();
        m_shouldEndSend = false;
      } else {
        beginSendingIR();
      }
    }
    return;
  }
  if (!IRSender::send()) {
    // just set the last time and wait
    m_lastSendTime = Time::getCurtime();
  }
}
References beginReceivingIR(), beginSendingIR(), Time::getCurtime(), IRSender::isSending(), m_lastSendTime, m_shouldEndSend, MS_TO_TICKS, and IRSender::send().
Referenced by run().
continueSendingVL()
void ModeSharing::continueSendingVL () [private]
Definition at line 139 of file ModeSharing.cpp.
{
  // if the sender isn't sending then nothing to do
  if (!VLSender::isSending()) {
    return;
  }
  if (!VLSender::send()) {
    // when send has completed, stores time that last action was completed to calculate interval between sends
    beginReceivingIR();
  }
}
References beginReceivingIR(), VLSender::isSending(), and VLSender::send().
Referenced by run().
init()
bool ModeSharing::init () [override], [virtual]
Reimplemented from Menu.
Definition at line 29 of file ModeSharing.cpp.
{
  if (!Menu::init()) {
    return false;
  }
  // skip led selection
  m_ledSelected = true;
  // start on receive because it's the more responsive of the two
  // the odds of opening receive and then accidentally receiving
  // a mode that is being broadcast nearby is completely unlikely
  beginReceivingIR();
  DEBUG_LOG("Entering Mode Sharing");
  return true;
}
References beginReceivingIR(), DEBUG_LOG, Menu::init(), and Menu::m_ledSelected.
onLongClick()
void ModeSharing::onLongClick () [override], [virtual]
Reimplemented from Menu.
Definition at line 97 of file ModeSharing.cpp.
{
  Modes::updateCurMode(&m_previewMode);
  leaveMenu(true);
}
References Menu::leaveMenu(), Menu::m_previewMode, and Modes::updateCurMode().
onShortClick()
void ModeSharing::onShortClick () [override], [virtual]
Reimplemented from Menu.
Definition at line 74 of file ModeSharing.cpp.
{
  switch (m_sharingMode) {
  case ModeShareState::SHARE_RECEIVE:
    // click while on receive -> end receive, start sending
    IRReceiver::endReceiving();
    beginSendingIR();
    DEBUG_LOG("Switched to send mode");
    break;
  case ModeShareState::SHARE_SEND_IR:
    if (!IRSender::isSending()) {
      beginReceivingIR();
      DEBUG_LOG("Switched to send mode");
    } else {
      m_shouldEndSend = true;
    }
    break;
  default:
    break;
  }
  Leds::clearAll();
}
References beginReceivingIR(), beginSendingIR(), Leds::clearAll(), DEBUG_LOG, IRReceiver::endReceiving(), IRSender::isSending(), m_sharingMode, m_shouldEndSend, SHARE_RECEIVE, and SHARE_SEND_IR.
receiveModeIR()
void ModeSharing::receiveModeIR () [private]
Definition at line 177 of file ModeSharing.cpp.
{
  // if reveiving new data set our last data time
  if (IRReceiver::onNewData()) {
    m_timeOutStartTime = Time::getCurtime();
    // if our last data was more than time out duration reset the recveiver
  } else if (m_timeOutStartTime > 0 && (m_timeOutStartTime + MAX_TIMEOUT_DURATION) < Time::getCurtime()) {
    IRReceiver::resetIRState();
    m_timeOutStartTime = 0;
    return;
  }
  // check if the IRReceiver has a full packet available
  if (!IRReceiver::dataReady()) {
    // nothing available yet
    return;
  }
  DEBUG_LOG("Mode ready to receive! Receiving...");
  // receive the IR mode into the current mode
  if (!IRReceiver::receiveMode(&m_previewMode)) {
    ERROR_LOG("Failed to receive mode");
    return;
  }
  DEBUG_LOGF("Success receiving mode: %u", m_previewMode.getPatternID());
  if (!m_advanced) {
    Modes::updateCurMode(&m_previewMode);
    // leave menu and save settings, even if the mode was the same whatever
    leaveMenu(true);
  }
}
References IRReceiver::dataReady(), DEBUG_LOG, DEBUG_LOGF, ERROR_LOG, Time::getCurtime(), Mode::getPatternID(), Menu::leaveMenu(), Menu::m_advanced, Menu::m_previewMode, m_timeOutStartTime, MAX_TIMEOUT_DURATION, IRReceiver::onNewData(), IRReceiver::receiveMode(), IRReceiver::resetIRState(), and Modes::updateCurMode().
Referenced by run().
run()
Menu::MenuAction ModeSharing::run () [override], [virtual]
Reimplemented from Menu.
Definition at line 44 of file ModeSharing.cpp.
{
  MenuAction result = Menu::run();
  if (result != MENU_CONTINUE) {
    return result;
  }
  switch (m_sharingMode) {
  case ModeShareState::SHARE_SEND_IR:
    // render the 'send mode' lights
    showSendModeIR();
    // continue sending any data as long as there is more to send
    continueSendingIR();
    break;
  case ModeShareState::SHARE_SEND_VL:
    // render the 'send mode' lights
    showSendModeVL();
    // continue sending any data as long as there is more to send
    continueSendingVL();
    break;
  case ModeShareState::SHARE_RECEIVE:
    // render the 'receive mode' lights
    showReceiveMode();
    // load any modes that are received
    receiveModeIR();
    break;
  }
  return MENU_CONTINUE;
}
References continueSendingIR(), continueSendingVL(), m_sharingMode, Menu::MENU_CONTINUE, receiveModeIR(), Menu::run(), SHARE_RECEIVE, SHARE_SEND_IR, SHARE_SEND_VL, showReceiveMode(), showSendModeIR(), and showSendModeVL().
showReceiveMode()
void ModeSharing::showReceiveMode () [private]
Definition at line 220 of file ModeSharing.cpp.
{
  if (IRReceiver::isReceiving()) {
    // using uint32_t to avoid overflow, the result should be within 10 to 255
    Leds::setAll(RGBColor(0, IRReceiver::percentReceived(), 0));
  } else {
    if (m_advanced) {
      m_previewMode.play();
    } else {
      Leds::setAll(RGB_WHITE0);
    }
  }
}
References IRReceiver::isReceiving(), Menu::m_advanced, Menu::m_previewMode, IRReceiver::percentReceived(), Mode::play(), RGB_WHITE0, and Leds::setAll().
Referenced by run().
showSendModeIR()
void ModeSharing::showSendModeIR () [private]
Definition at line 213 of file ModeSharing.cpp.
{
  // show a dim color when not sending
  Leds::setIndex(LED_1, RGB_CYAN1);
  Leds::setIndex(LED_2, RGB_CYAN1);
}
References LED_1, LED_2, RGB_CYAN1, and Leds::setIndex().
Referenced by run().
showSendModeVL()
void ModeSharing::showSendModeVL () [private]
Definition at line 207 of file ModeSharing.cpp.
{
  // show a dim color when not sending
  Leds::clearAll();
}
References Leds::clearAll().
Referenced by run().
Member Data Documentation
m_lastSendTime
uint32_t ModeSharing::m_lastSendTime [private]
Definition at line 41 of file ModeSharing.h.
Referenced by beginSendingIR(), and continueSendingIR().
m_sharingMode
ModeShareState ModeSharing::m_sharingMode [private]
Definition at line 37 of file ModeSharing.h.
Referenced by beginReceivingIR(), beginSendingIR(), beginSendingVL(), onShortClick(), and run().
m_shouldEndSend
bool ModeSharing::m_shouldEndSend [private]
Definition at line 44 of file ModeSharing.h.
Referenced by continueSendingIR(), and onShortClick().
m_timeOutStartTime
uint32_t ModeSharing::m_timeOutStartTime [private]
Definition at line 40 of file ModeSharing.h.
Referenced by receiveModeIR().
The documentation for this class was generated from the following files:
VortexEngine/src/Menus/MenuList/ModeSharing.h
VortexEngine/src/Menus/MenuList/ModeSharing.cpp