SequenceStep Class Reference
#include <Sequence.h>
Public Member Functions
SequenceStep ()
SequenceStep (uint16_t duration, const PatternMap &patternMap, const ColorsetMap &colorsetMap=Colorset())
SequenceStep (const SequenceStep &other)
bool serialize (ByteStream &buffer) const
bool unserialize (ByteStream &buffer)
Public Attributes
uint16_t m_duration
PatternMap m_patternMap
ColorsetMap m_colorsetMap
Detailed Description
Definition at line 52 of file Sequence.h.
Constructor & Destructor Documentation
SequenceStep() [1/3]
SequenceStep::SequenceStep ()
Definition at line 109 of file Sequence.cpp.
                           :
  m_duration(0), m_patternMap(), m_colorsetMap()
{
}
SequenceStep() [2/3]
SequenceStep::SequenceStep (uint16_t duration, const PatternMap & patternMap, const ColorsetMap & colorsetMap = Colorset())
Definition at line 113 of file Sequence.cpp.
                                                                                                          :
  m_duration(duration), m_patternMap(patternMap), m_colorsetMap(colorsetMap)
{
}
SequenceStep() [3/3]
SequenceStep::SequenceStep (const SequenceStep & other)
Definition at line 117 of file Sequence.cpp.
                                                    :
  SequenceStep(other.m_duration, other.m_patternMap, other.m_colorsetMap)
{
}
Member Function Documentation
serialize()
bool SequenceStep::serialize (ByteStream & buffer) const
Definition at line 122 of file Sequence.cpp.
{
  if (!buffer.serialize16(m_duration)) {
    return false;
  }
  if (!m_patternMap.serialize(buffer)) {
    return false;
  }
  if (!m_colorsetMap.serialize(buffer)) {
    return false;
  }
  return true;
}
References m_colorsetMap, m_duration, m_patternMap, PatternMap::serialize(), ColorsetMap::serialize(), and ByteStream::serialize16().
unserialize()
bool SequenceStep::unserialize (ByteStream & buffer)
Definition at line 136 of file Sequence.cpp.
{
  if (!buffer.unserialize16(&m_duration)) {
    return false;
  }
  if (!m_patternMap.unserialize(buffer)) {
    return false;
  }
  if (!m_colorsetMap.unserialize(buffer)) {
    return false;
  }
  return true;
}
References m_colorsetMap, m_duration, m_patternMap, PatternMap::unserialize(), ColorsetMap::unserialize(), and ByteStream::unserialize16().
Member Data Documentation
m_colorsetMap
ColorsetMap SequenceStep::m_colorsetMap
Definition at line 66 of file Sequence.h.
Referenced by SequencedPattern::playSequenceStep(), serialize(), and unserialize().
m_duration
uint16_t SequenceStep::m_duration
Definition at line 64 of file Sequence.h.
Referenced by serialize(), and unserialize().
m_patternMap
PatternMap SequenceStep::m_patternMap
Definition at line 65 of file Sequence.h.
Referenced by SequencedPattern::playSequenceStep(), serialize(), and unserialize().
The documentation for this class was generated from the following files:
VortexEngine/src/Patterns/Multi/Sequencer/Sequence.h
VortexEngine/src/Patterns/Multi/Sequencer/Sequence.cpp