GlobalBrightness Class Reference
#include <GlobalBrightness.h>
Public Member Functions
GlobalBrightness (const RGBColor &col, bool advanced)
~GlobalBrightness ()
bool init () override
MenuAction run () override
void onShortClick () override
void onLongClick () override
Private Types
enum keychain_mode_state : uint8_t {
KEYCHAIN_MODE_STATE_OFF = 0
, KEYCHAIN_MODE_STATE_SOLID
, KEYCHAIN_MODE_STATE_DOPS
, KEYCHAIN_MODE_STATE_SIGNAL
,
KEYCHAIN_MODE_STATE_COUNT
 }
Private Member Functions
void showBrightnessSelection ()
void setKeychainModeState (keychain_mode_state newState)
Menu::MenuAction runKeychainMode ()
Private Attributes
const uint8_t m_brightnessOptions [4]
keychain_mode_state m_keychain_modeState
uint32_t m_lastStateChange
uint8_t m_colorIndex
Additional Inherited Members
Detailed Description
Definition at line 6 of file GlobalBrightness.h.
Member Enumeration Documentation
keychain_mode_state
enum GlobalBrightness::keychain_mode_state : uint8_t [private]
Enumerator
KEYCHAIN_MODE_STATE_OFF
KEYCHAIN_MODE_STATE_SOLID
KEYCHAIN_MODE_STATE_DOPS
KEYCHAIN_MODE_STATE_SIGNAL
KEYCHAIN_MODE_STATE_COUNT
Definition at line 32 of file GlobalBrightness.h.
  {
    // sleeping / fake off
    KEYCHAIN_MODE_STATE_OFF = 0,
    // solid/tracer
    KEYCHAIN_MODE_STATE_SOLID,
    // dops blink 4 / 16
    KEYCHAIN_MODE_STATE_DOPS,
    // signal blink 16 / 120
    KEYCHAIN_MODE_STATE_SIGNAL,
    // total states
    KEYCHAIN_MODE_STATE_COUNT
  };
Constructor & Destructor Documentation
GlobalBrightness()
GlobalBrightness::GlobalBrightness (const RGBColor & col, bool advanced)
Definition at line 20 of file GlobalBrightness.cpp.
                                                                     :
  Menu(col, advanced),
  m_keychain_modeState(KEYCHAIN_MODE_STATE_OFF),
  m_lastStateChange(0),
  m_colorIndex(0)
{
}
 GlobalBrightness()
GlobalBrightness::~GlobalBrightness ()
Definition at line 28 of file GlobalBrightness.cpp.
{
  // ensure force sleep is turned back on when we leave
  VortexEngine::toggleForceSleep(true);
}
References VortexEngine::toggleForceSleep().
Member Function Documentation
init()
bool GlobalBrightness::init () [override], [virtual]
Reimplemented from Menu.
Definition at line 34 of file GlobalBrightness.cpp.
{
  if (!Menu::init()) {
    return false;
  }
  // bypass led selection
  m_ledSelected = true;
  // would be nice if there was a more elegant way to do this
  for (uint8_t i = 0; i < NUM_BRIGHTNESS_OPTIONS; ++i) {
    if (m_brightnessOptions[i] == Leds::getBrightness()) {
      // make sure the default selection matches cur value
      m_curSelection = i;
    }
  }
  if (m_advanced) {
    // turn off force sleep while running keychain mode
    VortexEngine::toggleForceSleep(false);
    // enable keychain mode so if the device sleeps it will wake into keychain mode
    Modes::setKeychainMode(true);
    // start in the off position, this call is necessary to update the
    // lastStateChange time to the current time of init
    setKeychainModeState(KEYCHAIN_MODE_STATE_SOLID);
    // reset the color index to ensure it starts on first color
    m_colorIndex = 0;
  }
  DEBUG_LOG("Entered global brightness");
  return true;
}
References DEBUG_LOG, Leds::getBrightness(), Menu::init(), KEYCHAIN_MODE_STATE_SOLID, Menu::m_advanced, m_brightnessOptions, m_colorIndex, Menu::m_curSelection, Menu::m_ledSelected, NUM_BRIGHTNESS_OPTIONS, Modes::setKeychainMode(), setKeychainModeState(), and VortexEngine::toggleForceSleep().
onLongClick()
void GlobalBrightness::onLongClick () [override], [virtual]
Reimplemented from Menu.
Definition at line 89 of file GlobalBrightness.cpp.
{
  if (m_advanced) {
    return;
  }
  if (m_curSelection >= NUM_BRIGHTNESS_OPTIONS) {
    // no save exit
    leaveMenu();
    return;
  }
  // set the global brightness
  Leds::setBrightness(m_brightnessOptions[m_curSelection]);
  // done here, save settings with new brightness
  leaveMenu(true);
}
References Menu::leaveMenu(), Menu::m_advanced, m_brightnessOptions, Menu::m_curSelection, NUM_BRIGHTNESS_OPTIONS, and Leds::setBrightness().
onShortClick()
void GlobalBrightness::onShortClick () [override], [virtual]
Reimplemented from Menu.
Definition at line 80 of file GlobalBrightness.cpp.
{
  if (m_advanced) {
    return;
  }
  // include one extra option for the exit slot
  m_curSelection = (m_curSelection + 1) % (NUM_BRIGHTNESS_OPTIONS + 1);
}
References Menu::m_advanced, Menu::m_curSelection, and NUM_BRIGHTNESS_OPTIONS.
run()
Menu::MenuAction GlobalBrightness::run () [override], [virtual]
Reimplemented from Menu.
Definition at line 63 of file GlobalBrightness.cpp.
{
  MenuAction result = Menu::run();
  if (result != MENU_CONTINUE) {
    return result;
  }
  if (m_advanced) {
    return runKeychainMode();
  }
  // show the current brightness
  showBrightnessSelection();
  // show selections
  Menus::showSelection();
  // continue
  return MENU_CONTINUE;
}
References Menu::m_advanced, Menu::MENU_CONTINUE, Menu::run(), runKeychainMode(), showBrightnessSelection(), and Menus::showSelection().
runKeychainMode()
Menu::MenuAction GlobalBrightness::runKeychainMode () [private]
Definition at line 124 of file GlobalBrightness.cpp.
{
  // check for exit
  if (g_pButton->onConsecutivePresses(KEYCHAIN_MODE_EXIT_CLICKS)) {
    // turn off keychain mode now
    Modes::setKeychainMode(false);
    return MENU_QUIT;
  }
  uint32_t now = Time::getCurtime();
  // whether the button was pressed before the timer expired
  // when the button is first pressed after the window has expired switch off
  if (g_pButton->onPress() && m_keychain_modeState != KEYCHAIN_MODE_STATE_OFF && now > (m_lastStateChange + KEYCHAIN_MODE_TIMER_TICKS)) {
    setKeychainModeState(KEYCHAIN_MODE_STATE_OFF);
    return MENU_CONTINUE;
  }
  // when the button is released, but only if they pressed it within this state
  if (g_pButton->onRelease() && g_pButton->pressTime() > m_lastStateChange) {
    // advance the state or turn off based on press time
    setKeychainModeState((keychain_mode_state)(m_keychain_modeState + 1));
    return MENU_CONTINUE;
  }
  // as long as the button is held down the leds clear
  if (g_pButton->isPressed()) {
    Leds::clearAll();
    return MENU_CONTINUE;
  }
  // check for sleep after some seconds
  if (m_keychain_modeState == KEYCHAIN_MODE_STATE_OFF && now > (m_lastStateChange + KEYCHAIN_MODE_SLEEP_TICKS)) {
    // Optional: indicate when the keychain is turning off (useful mainly for debugging)
    //Leds::holdAll(RGB_PURPLE);
    VortexEngine::enterSleep(false);
    return MENU_QUIT;
  }
  // render the signal mode in a different way
  if (m_keychain_modeState == KEYCHAIN_MODE_STATE_SIGNAL) {
    // use a custom blink because the SIGNAL_OFF duration is too large for uint8 params
    Leds::clearAll();
    Leds::blinkIndexOffset(LED_ALL,
      Time::getCurtime() - m_lastStateChange,
      SIGNAL_OFF_DURATION,
      SIGNAL_ON_DURATION,
      m_previewMode.getColorset().get(m_colorIndex));
  } else {
    // play the keychain_mode mode
    m_previewMode.play();
  }
  return MENU_CONTINUE;
}
References Leds::blinkIndexOffset(), Leds::clearAll(), VortexEngine::enterSleep(), g_pButton, Colorset::get(), Mode::getColorset(), Time::getCurtime(), Button::isPressed(), KEYCHAIN_MODE_EXIT_CLICKS, KEYCHAIN_MODE_SLEEP_TICKS, KEYCHAIN_MODE_STATE_OFF, KEYCHAIN_MODE_STATE_SIGNAL, KEYCHAIN_MODE_TIMER_TICKS, LED_ALL, m_colorIndex, m_keychain_modeState, m_lastStateChange, Menu::m_previewMode, Menu::MENU_CONTINUE, Menu::MENU_QUIT, Button::onConsecutivePresses(), Button::onPress(), Button::onRelease(), Mode::play(), Button::pressTime(), Modes::setKeychainMode(), setKeychainModeState(), SIGNAL_OFF_DURATION, and SIGNAL_ON_DURATION.
Referenced by run().
setKeychainModeState()
void GlobalBrightness::setKeychainModeState (keychain_mode_state newState) [private]
Definition at line 173 of file GlobalBrightness.cpp.
{
  // update the keychain_mode state
  m_keychain_modeState = (keychain_mode_state)(newState % KEYCHAIN_MODE_STATE_COUNT);
  // record the time of this statechange
  m_lastStateChange = Time::getCurtime();
  // this could
  uint8_t numCols = Modes::curMode()->getColorset().numColors();
  // the args that will define the timing of the blink on the solid pattern
  PatternArgs args;
  switch (m_keychain_modeState) {
  case KEYCHAIN_MODE_STATE_OFF:
  default:
    // iterate to next color and wrap to 0, don't use modulus because numCols could be 0
    m_colorIndex++;
    if (m_colorIndex >= numCols) {
      m_colorIndex = 0;
    }
    break;
  case KEYCHAIN_MODE_STATE_SOLID:
    args.init(200);
    break;
  case KEYCHAIN_MODE_STATE_DOPS:
    args.init(1, 10);
    break;
  case KEYCHAIN_MODE_STATE_SIGNAL:
    // unfortunately the signal blink timing is too large to fit into the uint8 params
    // so we just use a custom blink to render that one, but use the previewMode for
    // the other two states
    break;
  }
  // update the mode and ensure current colorset is always used, use PATTERN_SOLID
  // because that will never iterate to the next color and allows us to force
  // the color index via argument 6
  args.arg6 = m_colorIndex;
  m_previewMode.setPattern(PATTERN_SOLID, LED_ALL, &args);
  m_previewMode.init();
}
References PatternArgs::arg6, Modes::curMode(), Mode::getColorset(), Time::getCurtime(), Mode::init(), PatternArgs::init(), KEYCHAIN_MODE_STATE_COUNT, KEYCHAIN_MODE_STATE_DOPS, KEYCHAIN_MODE_STATE_OFF, KEYCHAIN_MODE_STATE_SIGNAL, KEYCHAIN_MODE_STATE_SOLID, LED_ALL, m_colorIndex, m_keychain_modeState, m_lastStateChange, Menu::m_previewMode, Colorset::numColors(), PATTERN_SOLID, and Mode::setPattern().
Referenced by init(), and runKeychainMode().
showBrightnessSelection()
void GlobalBrightness::showBrightnessSelection () [private]
Definition at line 105 of file GlobalBrightness.cpp.
{
  if (m_curSelection >= NUM_BRIGHTNESS_OPTIONS) {
    showExit();
    return;
  }
  Leds::setAll(HSVColor(38, 255, m_brightnessOptions[m_curSelection]));
}
References m_brightnessOptions, Menu::m_curSelection, NUM_BRIGHTNESS_OPTIONS, Leds::setAll(), and Menu::showExit().
Referenced by run().
Member Data Documentation
m_brightnessOptions
const uint8_t GlobalBrightness::m_brightnessOptions[4] [private]
Initial value:
= {
    BRIGHTNESS_OPTION_1,
    BRIGHTNESS_OPTION_2,
    BRIGHTNESS_OPTION_3,
    BRIGHTNESS_OPTION_4
  }
Definition at line 23 of file GlobalBrightness.h.
Referenced by init(), onLongClick(), and showBrightnessSelection().
m_colorIndex
uint8_t GlobalBrightness::m_colorIndex [private]
Definition at line 52 of file GlobalBrightness.h.
Referenced by init(), runKeychainMode(), and setKeychainModeState().
m_keychain_modeState
keychain_mode_state GlobalBrightness::m_keychain_modeState [private]
Definition at line 50 of file GlobalBrightness.h.
Referenced by runKeychainMode(), and setKeychainModeState().
m_lastStateChange
uint32_t GlobalBrightness::m_lastStateChange [private]
Definition at line 51 of file GlobalBrightness.h.
Referenced by runKeychainMode(), and setKeychainModeState().
The documentation for this class was generated from the following files:
VortexEngine/src/Menus/MenuList/GlobalBrightness.h
VortexEngine/src/Menus/MenuList/GlobalBrightness.cpp