IRReceiver Class Reference
#include <IRReceiver.h>
Static Public Member Functions
static bool init ()
static void cleanup ()
static bool dataReady ()
static bool isReceiving ()
static uint8_t percentReceived ()
static uint16_t bytesReceived ()
static bool receiveMode (Mode *pMode)
static bool beginReceiving ()
static bool endReceiving ()
static bool onNewData ()
static void resetIRState ()
Private Types
enum RecvState : uint8_t { WAITING_HEADER_MARK
, WAITING_HEADER_SPACE
, READING_DATA_MARK
, READING_DATA_SPACE
 }
Private Member Functions
IRReceiver ()
Static Private Member Functions
static bool read (ByteStream &data)
static void recvPCIHandler ()
static void handleIRTiming (uint32_t diff)
Static Private Attributes
static BitStream m_irData
static RecvState m_recvState = WAITING_HEADER_MARK
static uint32_t m_prevTime = 0
static uint8_t m_pinState = 0
static uint32_t m_previousBytes = 0
Detailed Description
Definition at line 15 of file IRReceiver.h.
Member Enumeration Documentation
RecvState
enum IRReceiver::RecvState : uint8_t [private]
Enumerator
WAITING_HEADER_MARK
WAITING_HEADER_SPACE
READING_DATA_MARK
READING_DATA_SPACE
Definition at line 58 of file IRReceiver.h.
  {
    WAITING_HEADER_MARK,
    WAITING_HEADER_SPACE,
    READING_DATA_MARK,
    READING_DATA_SPACE
  };
Constructor & Destructor Documentation
IRReceiver()
IRReceiver::IRReceiver () [private]
Member Function Documentation
beginReceiving()
bool IRReceiver::beginReceiving () [static]
Definition at line 91 of file IRReceiver.cpp.
{
#ifdef VORTEX_EMBEDDED
  attachInterrupt(digitalPinToInterrupt(IR_RECEIVER_PIN), IRReceiver::recvPCIHandler, CHANGE);
#endif
  resetIRState();
  return true;
}
References IR_RECEIVER_PIN, recvPCIHandler(), and resetIRState().
Referenced by ModeSharing::onShortClick().
bytesReceived()
static uint16_t IRReceiver::bytesReceived () [inline], [static]
Definition at line 30 of file IRReceiver.h.
{ return m_irData.bytepos(); }
References BitStream::bytepos(), and m_irData.
Referenced by onNewData().
cleanup()
void IRReceiver::cleanup () [static]
Definition at line 31 of file IRReceiver.cpp.
{
}
Referenced by VortexEngine::cleanup().
dataReady()
bool IRReceiver::dataReady () [static]
Definition at line 35 of file IRReceiver.cpp.
{
  // is the receiver actually receiving data?
  if (!isReceiving()) {
    return false;
  }
  uint8_t blocks = m_irData.data()[0];
  uint8_t remainder = m_irData.data()[1];
  uint32_t total = ((blocks - 1) * 32) + remainder;
  if (!total || total > IR_MAX_DATA_TRANSFER) {
    DEBUG_LOGF("Bad IR Data size: %u", total);
    return false;
  }
  // if there are size + 2 bytes in the IRData receiver
  // then a full message is ready, the + 2 is from the
  // two bytes for blocks + remainder that are sent first
  return (m_irData.bytepos() >= (uint32_t)(total + 2));
}
References BitStream::bytepos(), BitStream::data(), DEBUG_LOGF, IR_MAX_DATA_TRANSFER, isReceiving(), and m_irData.
Referenced by ModeSharing::receiveMode().
endReceiving()
bool IRReceiver::endReceiving () [static]
Definition at line 100 of file IRReceiver.cpp.
{
#ifdef VORTEX_EMBEDDED
  detachInterrupt(digitalPinToInterrupt(IR_RECEIVER_PIN));
#endif
  resetIRState();
  return true;
}
References IR_RECEIVER_PIN, and resetIRState().
Referenced by ModeSharing::onShortClick().
handleIRTiming()
void IRReceiver::handleIRTiming (uint32_t diff) [static], [private]
Definition at line 167 of file IRReceiver.cpp.
{
  // if the diff is too long or too short then it's not useful
  if ((diff > IR_HEADER_MARK_MAX && m_recvState < READING_DATA_MARK) || diff < IR_TIMING_MIN) {
    DEBUG_LOGF("bad delay: %u, resetting...", diff);
    resetIRState();
    return;
  }
  switch (m_recvState) {
  case WAITING_HEADER_MARK: // initial state
    if (diff >= IR_HEADER_MARK_MIN && diff <= IR_HEADER_MARK_MAX) {
      m_recvState = WAITING_HEADER_SPACE;
    } else {
      DEBUG_LOGF("Bad header mark %u, resetting...", diff);
      resetIRState();
    }
    break;
  case WAITING_HEADER_SPACE:
    if (diff >= IR_HEADER_SPACE_MIN && diff <= IR_HEADER_SPACE_MAX) {
      m_recvState = READING_DATA_MARK;
    } else {
      DEBUG_LOGF("Bad header space %u, resetting...", diff);
      resetIRState();
    }
    break;
  case READING_DATA_MARK:
    // classify mark/space based on the timing and write into buffer
    m_irData.write1Bit((diff > (IR_TIMING * 2)) ? 1 : 0);
    m_recvState = READING_DATA_SPACE;
    break;
  case READING_DATA_SPACE:
    // the space could be just a regular space, or a gap in between blocks
    m_recvState = READING_DATA_MARK;
    break;
  default: // ??
    DEBUG_LOGF("Bad receive state: %u", m_recvState);
    break;
  }
}
References DEBUG_LOGF, IR_HEADER_MARK_MAX, IR_HEADER_MARK_MIN, IR_HEADER_SPACE_MAX, IR_HEADER_SPACE_MIN, IR_TIMING, IR_TIMING_MIN, m_irData, m_recvState, READING_DATA_MARK, READING_DATA_SPACE, resetIRState(), WAITING_HEADER_MARK, WAITING_HEADER_SPACE, and BitStream::write1Bit().
Referenced by recvPCIHandler().
init()
bool IRReceiver::init () [static]
Definition at line 22 of file IRReceiver.cpp.
{
#ifdef VORTEX_EMBEDDED
  pinMode(IR_RECEIVER_PIN, INPUT_PULLUP);
#endif
  m_irData.init(IR_RECV_BUF_SIZE);
  return true;
}
References BitStream::init(), IR_RECEIVER_PIN, IR_RECV_BUF_SIZE, and m_irData.
Referenced by VortexEngine::init().
isReceiving()
bool IRReceiver::isReceiving () [static]
Definition at line 55 of file IRReceiver.cpp.
{
  // if there are at least 2 bytes in the data buffer then
  // the receiver is receiving a packet. If there is less
  // than 2 bytes then we're still waiting for the 'blocks'
  // and 'remainder' bytes which prefix a packet
  return (m_irData.bytepos() > 2);
}
References BitStream::bytepos(), and m_irData.
Referenced by dataReady(), percentReceived(), and ModeSharing::showReceiveMode().
onNewData()
bool IRReceiver::onNewData () [static]
Definition at line 109 of file IRReceiver.cpp.
{
  if (bytesReceived() == m_previousBytes) {
    return false;
  }
  m_previousBytes = bytesReceived();
  return true;
}
References bytesReceived(), and m_previousBytes.
Referenced by ModeSharing::receiveMode().
percentReceived()
uint8_t IRReceiver::percentReceived () [static]
Definition at line 65 of file IRReceiver.cpp.
{
  if (!isReceiving()) {
    return 0;
  }
  uint8_t blocks = m_irData.data()[0];
  uint8_t remainder = m_irData.data()[1];
  uint16_t total = ((blocks - 1) * 32) + remainder;
  // round by adding half of the total to the numerator
  return (uint8_t)((uint16_t)((m_irData.bytepos() * 100 + (total / 2)) / total));
}
References BitStream::bytepos(), BitStream::data(), isReceiving(), and m_irData.
Referenced by ModeSharing::showReceiveMode().
read()
bool IRReceiver::read (ByteStream & data) [static], [private]
Definition at line 118 of file IRReceiver.cpp.
{
  if (!m_irData.bytepos() || m_irData.bytepos() > IR_MAX_DATA_TRANSFER) {
    DEBUG_LOG("Nothing to read, or read too much");
    return false;
  }
  // read the size out (blocks + remainder)
  uint8_t blocks = m_irData.data()[0];
  uint8_t remainder = m_irData.data()[1];
  // calculate size from blocks + remainder
  uint32_t size = ((blocks - 1) * 32) + remainder;
  if (!size || size > IR_MAX_DATA_TRANSFER) {
    DEBUG_LOGF("Bad IR Data size: %u", size);
    return false;
  }
  // the actual data starts 2 bytes later because of the size byte
  const uint8_t *actualData = m_irData.data() + 2;
  if (!data.rawInit(actualData, size)) {
    DEBUG_LOG("Failed to init buffer for IR read");
    return false;
  }
  // reset the IR state and receive buffer now
  resetIRState();
  return true;
}
References BitStream::bytepos(), BitStream::data(), DEBUG_LOG, DEBUG_LOGF, IR_MAX_DATA_TRANSFER, m_irData, ByteStream::rawInit(), and resetIRState().
Referenced by receiveMode().
receiveMode()
bool IRReceiver::receiveMode (Mode * pMode) [static]
Definition at line 77 of file IRReceiver.cpp.
{
  ByteStream buf;
  // read from the receive buffer into the byte stream
  if (!read(buf)) {
    // no data to read right now, or an error
    DEBUG_LOG("No data available to read, or error reading");
    return false;
  }
  DEBUG_LOGF("Received %u bytes", buf.rawSize());
  // load the data into the target mode
  return pMode->loadFromBuffer(buf);
}
References DEBUG_LOG, DEBUG_LOGF, Mode::loadFromBuffer(), ByteStream::rawSize(), and read().
Referenced by ModeSharing::receiveMode().
recvPCIHandler()
void IRReceiver::recvPCIHandler () [static], [private]
Definition at line 145 of file IRReceiver.cpp.
{
  // toggle the tracked pin state no matter what
  m_pinState = (uint8_t)!m_pinState;
  // grab current time
  uint32_t now = Time::microseconds();
  // check previous time for validity
  if (!m_prevTime || m_prevTime > now) {
    m_prevTime = now;
    DEBUG_LOG("Bad first time diff, resetting...");
    resetIRState();
    return;
  }
  // calc time difference between previous change and now
  uint32_t diff = (uint32_t)(now - m_prevTime);
  // and update the previous changetime for next loop
  m_prevTime = now;
  // handle the blink duration and process it
  handleIRTiming(diff);
}
References DEBUG_LOG, handleIRTiming(), m_pinState, m_prevTime, Time::microseconds(), and resetIRState().
Referenced by beginReceiving().
resetIRState()
void IRReceiver::resetIRState () [static]
Definition at line 207 of file IRReceiver.cpp.
{
  m_previousBytes = 0;
  m_recvState = WAITING_HEADER_MARK;
  // zero out the receive buffer and reset bit receiver position
  m_irData.reset();
  DEBUG_LOG("IR State Reset");
}
References DEBUG_LOG, m_irData, m_previousBytes, m_recvState, BitStream::reset(), and WAITING_HEADER_MARK.
Referenced by beginReceiving(), endReceiving(), handleIRTiming(), read(), ModeSharing::receiveMode(), and recvPCIHandler().
Member Data Documentation
m_irData
BitStream IRReceiver::m_irData [static], [private]
Definition at line 55 of file IRReceiver.h.
Referenced by bytesReceived(), dataReady(), handleIRTiming(), init(), isReceiving(), percentReceived(), read(), and resetIRState().
m_pinState
uint8_t IRReceiver::m_pinState = 0 [static], [private]
Definition at line 70 of file IRReceiver.h.
Referenced by recvPCIHandler().
m_previousBytes
uint32_t IRReceiver::m_previousBytes = 0 [static], [private]
Definition at line 73 of file IRReceiver.h.
Referenced by onNewData(), and resetIRState().
m_prevTime
uint32_t IRReceiver::m_prevTime = 0 [static], [private]
Definition at line 69 of file IRReceiver.h.
Referenced by recvPCIHandler().
m_recvState
IRReceiver::RecvState IRReceiver::m_recvState = WAITING_HEADER_MARK [static], [private]
Definition at line 67 of file IRReceiver.h.
Referenced by handleIRTiming(), and resetIRState().
The documentation for this class was generated from the following files:
VortexEngine/src/Wireless/IRReceiver.h
VortexEngine/src/Wireless/IRReceiver.cpp