BasicPattern Class Reference
#include <BasicPattern.h>
Public Member Functions
BasicPattern (VortexEngine &engine, const PatternArgs &args)
virtual ~BasicPattern ()
virtual void init () override
virtual void play () override
Protected Types
enum PatternState : uint8_t {
STATE_DISABLED
, STATE_BLINK_ON
, STATE_ON
, STATE_BLINK_OFF
,
STATE_OFF
, STATE_BEGIN_GAP
, STATE_IN_GAP
, STATE_BEGIN_DASH
,
STATE_IN_DASH
, STATE_BEGIN_GAP2
, STATE_IN_GAP2
 }
Protected Member Functions
virtual void onBlinkOn ()
virtual void onBlinkOff ()
virtual void beginGap ()
virtual void beginDash ()
void nextState (uint8_t timing)
Protected Attributes
uint8_t m_onDuration
uint8_t m_offDuration
uint8_t m_gapDuration
uint8_t m_dashDuration
uint8_t m_groupSize
uint8_t m_groupCounter
PatternState m_state
Timer m_blinkTimer
Detailed Description
Definition at line 7 of file BasicPattern.h.
Member Enumeration Documentation
PatternState
enum BasicPattern::PatternState : uint8_t [protected]
Enumerator
STATE_DISABLED
STATE_BLINK_ON
STATE_ON
STATE_BLINK_OFF
STATE_OFF
STATE_BEGIN_GAP
STATE_IN_GAP
STATE_BEGIN_DASH
STATE_IN_DASH
STATE_BEGIN_GAP2
STATE_IN_GAP2
Definition at line 36 of file BasicPattern.h.
  {
    // the led is disabled (there is no on or dash)
    STATE_DISABLED,
    // the pattern is blinking on the next color in the set
    STATE_BLINK_ON,
    STATE_ON,
    // the pattern is blinking off
    STATE_BLINK_OFF,
    STATE_OFF,
    // the pattern is starting a gap after a colorset
    STATE_BEGIN_GAP,
    STATE_IN_GAP,
    // the pattern is beginning a dash after a colorset or gap
    STATE_BEGIN_DASH,
    STATE_IN_DASH,
    // the pattern is starting a gap after a dash
    STATE_BEGIN_GAP2,
    STATE_IN_GAP2,
  };
Constructor & Destructor Documentation
BasicPattern()
BasicPattern::BasicPattern (VortexEngine & engine, const PatternArgs & args)
Definition at line 36 of file BasicPattern.cpp.
                                                                        :
  SingleLedPattern(engine, args),
  m_onDuration(0),
  m_offDuration(0),
  m_gapDuration(0),
  m_dashDuration(0),
  m_groupSize(0),
  m_groupCounter(0),
  m_state(STATE_BLINK_ON),
  m_blinkTimer(engine)
{
  m_patternID = PATTERN_STROBE;
  REGISTER_ARG(m_onDuration);
  REGISTER_ARG(m_offDuration);
  REGISTER_ARG(m_gapDuration);
  REGISTER_ARG(m_dashDuration);
  REGISTER_ARG(m_groupSize);
  setArgs(args);
}
References m_dashDuration, m_gapDuration, m_groupSize, m_offDuration, m_onDuration, Pattern::m_patternID, PATTERN_STROBE, REGISTER_ARG, and Pattern::setArgs().
 BasicPattern()
BasicPattern::~BasicPattern () [virtual]
Definition at line 56 of file BasicPattern.cpp.
{
}
Member Function Documentation
beginDash()
void BasicPattern::beginDash () [protected], [virtual]
Definition at line 189 of file BasicPattern.cpp.
{
  PRINT_STATE(STATE_IN_DASH);
  m_engine.leds().setIndex(m_ledPos, m_colorset.getNext());
}
References Colorset::getNext(), VortexEngine::leds(), Pattern::m_colorset, Pattern::m_engine, Pattern::m_ledPos, PRINT_STATE, Leds::setIndex(), and STATE_IN_DASH.
Referenced by play().
beginGap()
void BasicPattern::beginGap () [protected], [virtual]
Definition at line 183 of file BasicPattern.cpp.
{
  PRINT_STATE(STATE_IN_GAP);
  m_engine.leds().clearIndex(m_ledPos);
}
References Leds::clearIndex(), VortexEngine::leds(), Pattern::m_engine, Pattern::m_ledPos, PRINT_STATE, and STATE_IN_GAP.
Referenced by play().
init()
void BasicPattern::init () [override], [virtual]
Reimplemented from SingleLedPattern.
Reimplemented in BlendPattern.
Definition at line 60 of file BasicPattern.cpp.
{
  // run base pattern init logic
  Pattern::init();
  // the default state to begin with
  m_state = STATE_BLINK_ON;
  // if a dash is present then always start with the dash because
  // it consumes the first color in the colorset
  if (m_dashDuration > 0) {
    m_state = STATE_BEGIN_DASH;
  }
  // if there's no on duration or dash duration the led is just disabled
  if ((!m_onDuration && !m_dashDuration) || !m_colorset.numColors()) {
    m_state = STATE_DISABLED;
  }
  m_groupCounter = m_groupSize ? m_groupSize : (m_colorset.numColors() - (m_dashDuration != 0));
}
References Pattern::init(), Pattern::m_colorset, m_dashDuration, m_groupCounter, m_groupSize, m_onDuration, m_state, Colorset::numColors(), STATE_BEGIN_DASH, STATE_BLINK_ON, and STATE_DISABLED.
Referenced by BlendPattern::init().
nextState()
void BasicPattern::nextState (uint8_t timing) [protected]
Definition at line 79 of file BasicPattern.cpp.
{
  m_blinkTimer.init(TIMER_1_ALARM | TIMER_START, timing);
  m_state = (PatternState)(m_state + 1);
}
References Timer::init(), m_blinkTimer, m_state, TIMER_1_ALARM, and TIMER_START.
Referenced by play().
onBlinkOff()
void BasicPattern::onBlinkOff () [protected], [virtual]
Definition at line 177 of file BasicPattern.cpp.
{
  PRINT_STATE(STATE_OFF);
  m_engine.leds().clearIndex(m_ledPos);
}
References Leds::clearIndex(), VortexEngine::leds(), Pattern::m_engine, Pattern::m_ledPos, PRINT_STATE, and STATE_OFF.
Referenced by play().
onBlinkOn()
void BasicPattern::onBlinkOn () [protected], [virtual]
Reimplemented in SolidPattern, and BlendPattern.
Definition at line 171 of file BasicPattern.cpp.
{
  PRINT_STATE(STATE_ON);
  m_engine.leds().setIndex(m_ledPos, m_colorset.getNext());
}
References Colorset::getNext(), VortexEngine::leds(), Pattern::m_colorset, Pattern::m_engine, Pattern::m_ledPos, PRINT_STATE, Leds::setIndex(), and STATE_ON.
Referenced by SolidPattern::onBlinkOn(), and play().
play()
void BasicPattern::play () [override], [virtual]
Implements Pattern.
Definition at line 85 of file BasicPattern.cpp.
{
  // Sometimes the pattern needs to cycle multiple states in a single frame so
  // instead of using a loop or recursion I have just used a simple goto
replay:
  // its kinda evolving as i go
  switch (m_state) {
  case STATE_DISABLED:
    return;
  case STATE_BLINK_ON:
    if (m_onDuration > 0) {
      onBlinkOn();
      --m_groupCounter;
      nextState(m_onDuration);
      return;
    }
    m_state = STATE_BLINK_OFF;
  case STATE_BLINK_OFF:
    // the whole 'should blink off' situation is tricky because we might need
    // to go back to blinking on if our colorset isn't at the end yet
    if (m_groupCounter > 0 || (!m_gapDuration && !m_dashDuration)) {
      if (m_offDuration > 0) {
        onBlinkOff();
        nextState(m_offDuration);
        return;
      }
      if (m_groupCounter > 0 && m_onDuration > 0) {
        m_state = STATE_BLINK_ON;
        goto replay;
      }
    }
    m_state = STATE_BEGIN_GAP;
  case STATE_BEGIN_GAP:
    m_groupCounter = m_groupSize ? m_groupSize : (m_colorset.numColors() - (m_dashDuration != 0));
    if (m_gapDuration > 0) {
      beginGap();
      nextState(m_gapDuration);
      return;
    }
    m_state = STATE_BEGIN_DASH;
  case STATE_BEGIN_DASH:
    if (m_dashDuration > 0) {
      beginDash();
      nextState(m_dashDuration);
      return;
    }
    m_state = STATE_BEGIN_GAP2;
  case STATE_BEGIN_GAP2:
    if (m_dashDuration > 0 && m_gapDuration > 0) {
      beginGap();
      nextState(m_gapDuration);
      return;
    }
    m_state = STATE_BLINK_ON;
    goto replay;
  default:
    break;
  }
  if (m_blinkTimer.alarm() == -1) {
    // no alarm triggered just stay in current state, return and don't transition states
    PRINT_STATE(m_state);
    return;
  }
  // this just transitions the state into the next state, with some edge conditions for
  // transitioning to different states under certain circumstances. Honestly this is
  // a nightmare to read now and idk how to fix it
  if (m_state == STATE_IN_GAP2 || (m_state == STATE_OFF && m_groupCounter > 0)) {
    // this is an edge condition for when in the second gap or off in the non-last off blink
    // then the state actually needs to jump backwards rather than iterate
    m_state = m_onDuration ? STATE_BLINK_ON : (m_dashDuration ? STATE_BEGIN_DASH : STATE_BEGIN_GAP);
  } else if (m_state == STATE_OFF && (!m_groupCounter || m_colorset.numColors() == 1)) {
    // this is an edge condition when the state is off but this is the last off blink in the
    // group or there's literally only one color in the group then if there is more blinks
    // left in the group we need to cycle back to blink on instead of to the next state
    m_state = (m_groupCounter > 0) ? STATE_BLINK_ON : STATE_BEGIN_GAP;
  } else {
    // this is the standard case, iterate to the next state
    m_state = (PatternState)(m_state + 1);
  }
  // poor-mans recurse with the new state change (this transitions to a new state within the same tick)
  goto replay;
}
References Timer::alarm(), beginDash(), beginGap(), m_blinkTimer, Pattern::m_colorset, m_dashDuration, m_gapDuration, m_groupCounter, m_groupSize, m_offDuration, m_onDuration, m_state, nextState(), Colorset::numColors(), onBlinkOff(), onBlinkOn(), PRINT_STATE, STATE_BEGIN_DASH, STATE_BEGIN_GAP, STATE_BEGIN_GAP2, STATE_BLINK_OFF, STATE_BLINK_ON, STATE_DISABLED, STATE_IN_GAP2, and STATE_OFF.
Member Data Documentation
m_blinkTimer
Timer BasicPattern::m_blinkTimer [protected]
Definition at line 66 of file BasicPattern.h.
Referenced by nextState(), and play().
m_dashDuration
uint8_t BasicPattern::m_dashDuration [protected]
Definition at line 30 of file BasicPattern.h.
Referenced by BasicPattern(), init(), and play().
m_gapDuration
uint8_t BasicPattern::m_gapDuration [protected]
Definition at line 29 of file BasicPattern.h.
Referenced by BasicPattern(), and play().
m_groupCounter
uint8_t BasicPattern::m_groupCounter [protected]
Definition at line 33 of file BasicPattern.h.
Referenced by init(), and play().
m_groupSize
uint8_t BasicPattern::m_groupSize [protected]
Definition at line 31 of file BasicPattern.h.
Referenced by BasicPattern(), init(), and play().
m_offDuration
uint8_t BasicPattern::m_offDuration [protected]
Definition at line 28 of file BasicPattern.h.
Referenced by BasicPattern(), and play().
m_onDuration
uint8_t BasicPattern::m_onDuration [protected]
Definition at line 27 of file BasicPattern.h.
Referenced by BasicPattern(), init(), and play().
m_state
PatternState BasicPattern::m_state [protected]
Definition at line 63 of file BasicPattern.h.
Referenced by init(), nextState(), and play().
The documentation for this class was generated from the following files:
VortexEngine/src/Patterns/Single/BasicPattern.h
VortexEngine/src/Patterns/Single/BasicPattern.cpp