Colorset Class Reference
#include <Colorset.h>
Public Types
enum ValueStyle : uint8_t {
VAL_STYLE_RANDOM = 0
, VAL_STYLE_LOW_FIRST_COLOR
, VAL_STYLE_HIGH_FIRST_COLOR
, VAL_STYLE_ALTERNATING
,
VAL_STYLE_ASCENDING
, VAL_STYLE_DESCENDING
, VAL_STYLE_CONSTANT
, VAL_STYLE_COUNT
 }
enum ColorMode { THEORY
, MONOCHROMATIC
, EVENLY_SPACED
 }
enum ColorMode2 { DOUBLE_SPLIT_COMPLIMENTARY
, TETRADIC
 }
Public Member Functions
Colorset ()
Colorset (RGBColor c1, RGBColor c2=RGB_OFF, RGBColor c3=RGB_OFF, RGBColor c4=RGB_OFF, RGBColor c5=RGB_OFF, RGBColor c6=RGB_OFF, RGBColor c7=RGB_OFF, RGBColor c8=RGB_OFF)
Colorset (uint8_t numCols, const uint32_t *cols)
~Colorset ()
Colorset (Colorset &&other) noexcept
Colorset (const Colorset &other)
void operator= (const Colorset &other)
bool operator== (const Colorset &other) const
bool operator!= (const Colorset &other) const
void init (RGBColor c1=RGB_OFF, RGBColor c2=RGB_OFF, RGBColor c3=RGB_OFF, RGBColor c4=RGB_OFF, RGBColor c5=RGB_OFF, RGBColor c6=RGB_OFF, RGBColor c7=RGB_OFF, RGBColor c8=RGB_OFF)
void clear ()
bool equals (const Colorset &set) const
bool equals (const Colorset *set) const
RGBColor operator[] (int index) const
bool addColor (RGBColor col)
bool addColorHSV (uint8_t hue, uint8_t sat, uint8_t val)
void addColorWithValueStyle (Random &ctx, uint8_t hue, uint8_t sat, ValueStyle valStyle, uint8_t numColors, uint8_t colorPos)
void removeColor (uint8_t index)
void randomize (Random &ctx, uint8_t numColors=0)
void randomizeColors (Random &ctx, uint8_t numColors, ColorMode mode)
void randomizeColors2 (Random &ctx, ColorMode2 mode)
void randomizeSolid (Random &ctx)
void randomizeComplimentary (Random &ctx)
void randomizeTriadic (Random &ctx)
void randomizeSquare (Random &ctx)
void randomizePentadic (Random &ctx)
void randomizeRainbow (Random &ctx)
void adjustBrightness (uint8_t fadeby)
RGBColor get (uint8_t index=0) const
void set (uint8_t index, RGBColor col)
void skip (int32_t amount=1)
RGBColor cur ()
void setCurIndex (uint8_t index)
void resetIndex ()
uint8_t curIndex () const
RGBColor getPrev ()
RGBColor getNext ()
RGBColor peek (int32_t offset) const
RGBColor peekNext () const
uint8_t numColors () const
bool onStart () const
bool onEnd () const
bool serialize (ByteStream &buffer) const
bool unserialize (ByteStream &buffer)
Private Member Functions
bool initPalette (uint8_t numColors)
Private Attributes
RGBColor * m_palette
uint8_t m_curIndex
uint8_t m_numColors
Detailed Description
Definition at line 11 of file Colorset.h.
Member Enumeration Documentation
ColorMode
enum Colorset::ColorMode
Enumerator
THEORY
MONOCHROMATIC
EVENLY_SPACED
Definition at line 81 of file Colorset.h.
                 {
    THEORY,
    MONOCHROMATIC,
    EVENLY_SPACED
  };
ColorMode2
enum Colorset::ColorMode2
Enumerator
DOUBLE_SPLIT_COMPLIMENTARY
TETRADIC
Definition at line 89 of file Colorset.h.
                  {
    DOUBLE_SPLIT_COMPLIMENTARY,
    TETRADIC
  };
ValueStyle
enum Colorset::ValueStyle : uint8_t
Enumerator
VAL_STYLE_RANDOM
VAL_STYLE_LOW_FIRST_COLOR
VAL_STYLE_HIGH_FIRST_COLOR
VAL_STYLE_ALTERNATING
VAL_STYLE_ASCENDING
VAL_STYLE_DESCENDING
VAL_STYLE_CONSTANT
VAL_STYLE_COUNT
Definition at line 49 of file Colorset.h.
  {
    // Random values
    VAL_STYLE_RANDOM = 0,
    // First color low value, the rest are random
    VAL_STYLE_LOW_FIRST_COLOR,
    // First color high value, the rest are low
    VAL_STYLE_HIGH_FIRST_COLOR,
    // Alternat between high and low value
    VAL_STYLE_ALTERNATING,
    // Ascending values from low to high
    VAL_STYLE_ASCENDING,
    // Descending values from high to low
    VAL_STYLE_DESCENDING,
    // Constant value
    VAL_STYLE_CONSTANT,
    // Total number of value styles
    VAL_STYLE_COUNT
  };
Constructor & Destructor Documentation
Colorset() [1/5]
Colorset::Colorset ()
Definition at line 16 of file Colorset.cpp.
                   :
  m_palette(nullptr),
  m_curIndex(INDEX_NONE),
  m_numColors(0)
{
  init();
}
References init().
Colorset() [2/5]
Colorset::Colorset (RGBColor c1, RGBColor c2 = RGB_OFF, RGBColor c3 = RGB_OFF, RGBColor c4 = RGB_OFF, RGBColor c5 = RGB_OFF, RGBColor c6 = RGB_OFF, RGBColor c7 = RGB_OFF, RGBColor c8 = RGB_OFF)
Definition at line 24 of file Colorset.cpp.
                                                      :
  Colorset()
{
  init(c1, c2, c3, c4, c5, c6, c7, c8);
}
References init().
Colorset() [3/5]
Colorset::Colorset (uint8_t numCols, const uint32_t * cols)
Definition at line 31 of file Colorset.cpp.
                                                        :
  Colorset()
{
  if (numCols > MAX_COLOR_SLOTS) {
    numCols = MAX_COLOR_SLOTS;
  }
  for (uint8_t i = 0; i < numCols; ++i) {
    addColor(RGBColor(cols[i]));
  }
}
References addColor(), and MAX_COLOR_SLOTS.
 Colorset()
Colorset::~Colorset ()
Definition at line 49 of file Colorset.cpp.
{
  clear();
}
References clear().
Colorset() [4/5]
Colorset::Colorset (Colorset && other) [noexcept]
Definition at line 54 of file Colorset.cpp.
                                            :
  m_palette(other.m_palette),
  m_curIndex(INDEX_NONE),
  m_numColors(other.m_numColors)
{
  other.m_palette = nullptr;
  other.m_numColors = 0;
  other.m_curIndex = INDEX_NONE;
}
References INDEX_NONE.
Colorset() [5/5]
Colorset::Colorset (const Colorset & other)
Definition at line 42 of file Colorset.cpp.
                                        :
  Colorset()
{
  // invoke = operator
  *this = other;
}
Member Function Documentation
addColor()
bool Colorset::addColor (RGBColor col)
Definition at line 131 of file Colorset.cpp.
{
  if (m_numColors >= MAX_COLOR_SLOTS) {
    return false;
  }
  // allocate a new palette one larger than before
  RGBColor *temp = new RGBColor[m_numColors + 1];
  if (!temp) {
    return false;
  }
  // if there is already some colors in the palette
  if (m_numColors && m_palette) {
    // copy over existing colors
    for (uint8_t i = 0; i < m_numColors; ++i) {
      temp[i] = m_palette[i];
    }
    // and delete the existing palette
    delete[] m_palette;
  }
  // reassign new palette
  m_palette = temp;
  // insert new color and increment number of colors
  m_palette[m_numColors] = col;
  m_numColors++;
  return true;
}
References m_numColors, m_palette, and MAX_COLOR_SLOTS.
Referenced by addColorHSV(), Colorset(), VortexCLI::init(), init(), Vortex::patternFromJson(), Randomizer::rollColorset(), and set().
addColorHSV()
bool Colorset::addColorHSV (uint8_t hue, uint8_t sat, uint8_t val)
Definition at line 158 of file Colorset.cpp.
{
  return addColor(HSVColor(hue, sat, val));
}
References addColor().
Referenced by addColorWithValueStyle().
addColorWithValueStyle()
void Colorset::addColorWithValueStyle (Random & ctx, uint8_t hue, uint8_t sat, ValueStyle valStyle, uint8_t numColors, uint8_t colorPos)
Definition at line 163 of file Colorset.cpp.
{
  if (numColors == 1) {
    addColorHSV(hue, sat, ctx.next8(16, 255));
    return;
  }
  switch (valStyle) {
  default:
  case VAL_STYLE_RANDOM:
    addColorHSV(hue, sat, 85 * ctx.next8(1, 4));
    break;
  case VAL_STYLE_LOW_FIRST_COLOR:
    if (m_numColors == 0) {
      addColorHSV(hue, sat, ctx.next8(0, 86));
    } else {
      addColorHSV(hue, sat, 85 * ctx.next8(1, 4));
    }
    break;
  case VAL_STYLE_HIGH_FIRST_COLOR:
    if (m_numColors == 0) {
      addColorHSV(hue, sat, 255);
    } else {
      addColorHSV(hue, sat, ctx.next8(0, 86));
    }
    break;
  case VAL_STYLE_ALTERNATING:
    if (m_numColors % 2 == 0) {
      addColorHSV(hue, sat, 255);
    } else {
      addColorHSV(hue, sat, 85);
    }
    break;
  case VAL_STYLE_ASCENDING:
    addColorHSV(hue, sat, (colorPos + 1) * (255 / numColors));
    break;
  case VAL_STYLE_DESCENDING:
    addColorHSV(hue, sat, 255 - (colorPos * (255 / numColors)));
    break;
  case VAL_STYLE_CONSTANT:
    addColorHSV(hue, sat, 255);
  }
}
References addColorHSV(), m_numColors, Random::next8(), numColors(), VAL_STYLE_ALTERNATING, VAL_STYLE_ASCENDING, VAL_STYLE_CONSTANT, VAL_STYLE_DESCENDING, VAL_STYLE_HIGH_FIRST_COLOR, VAL_STYLE_LOW_FIRST_COLOR, and VAL_STYLE_RANDOM.
Referenced by randomize(), randomizeColors(), and randomizeColors2().
adjustBrightness()
void Colorset::adjustBrightness (uint8_t fadeby)
Definition at line 303 of file Colorset.cpp.
{
  for (uint8_t i = 0; i < m_numColors; ++i) {
    m_palette[i].adjustBrightness(fadeby);
  }
}
References RGBColor::adjustBrightness(), m_numColors, and m_palette.
clear()
void Colorset::clear ()
Definition at line 102 of file Colorset.cpp.
{
  if (m_palette) {
    delete[] m_palette;
    m_palette = nullptr;
  }
  m_numColors = 0;
  resetIndex();
}
References m_numColors, m_palette, and resetIndex().
Referenced by Pattern::clearColorset(), init(), operator=(), randomize(), randomizeColors(), randomizeColors2(), and ~Colorset().
cur()
RGBColor Colorset::cur ()
Definition at line 365 of file Colorset.cpp.
{
  if (m_curIndex >= m_numColors || !m_palette) {
    return RGBColor(0, 0, 0);
  }
  if (m_curIndex == INDEX_NONE) {
    return m_palette[0];
  }
  return m_palette[m_curIndex];
}
References INDEX_NONE, m_curIndex, m_numColors, and m_palette.
Referenced by DripMorphPattern::blinkOn(), BouncePattern::blinkOn(), CrossDopsPattern::blinkOn(), DoubleStrobePattern::blinkOn(), DripPattern::blinkOn(), FillPattern::blinkOn(), LighthousePattern::blinkOn(), SnowballPattern::blinkOn(), VortexWipePattern::blinkOn(), WarpPattern::blinkOn(), WarpWormPattern::blinkOn(), PulsishPattern::play(), and SparkleTracePattern::poststep().
curIndex()
uint8_t Colorset::curIndex () const [inline]
Definition at line 124 of file Colorset.h.
{ return m_curIndex; }
References m_curIndex.
Referenced by SnowballPattern::blinkOn(), WarpWormPattern::blinkOn(), PulsishPattern::play(), SnowballPattern::poststep(), SparkleTracePattern::poststep(), and WarpWormPattern::poststep().
equals() [1/2]
bool Colorset::equals (const Colorset & set) const
Definition at line 112 of file Colorset.cpp.
{
  return operator==(set);
}
References operator==(), and set().
Referenced by Pattern::equals(), ColorSelect::onLongClick(), and SequencedPattern::playSequenceStep().
equals() [2/2]
bool Colorset::equals (const Colorset * set) const
Definition at line 117 of file Colorset.cpp.
{
  if (!set) {
    return false;
  }
  return operator==(*set);
}
References operator==(), and set().
get()
RGBColor Colorset::get (uint8_t index = 0) const
Definition at line 311 of file Colorset.cpp.
{
  if (index >= m_numColors || !m_palette) {
    return RGBColor(0, 0, 0);
  }
  return m_palette[index];
}
References m_numColors, and m_palette.
Referenced by SnowballPattern::blinkOn(), SparkleTracePattern::blinkOn(), WarpWormPattern::blinkOn(), operator[](), Vortex::patternFromJson(), Vortex::patternToJson(), PulsishPattern::play(), and Randomizer::rollColorset().
getNext()
RGBColor Colorset::getNext ()
Definition at line 407 of file Colorset.cpp.
{
  if (!m_numColors || !m_palette) {
    return RGB_OFF;
  }
  // iterate current index, let it wrap at max uint8
  m_curIndex++;
  // then modulate the result within max colors
  m_curIndex %= numColors();
  // return the color
  return m_palette[m_curIndex];
}
References m_curIndex, m_numColors, m_palette, numColors(), and RGB_OFF.
Referenced by BasicPattern::beginDash(), DripMorphPattern::blinkOn(), TheaterChasePattern::blinkOn(), DripMorphPattern::init(), HueShiftPattern::init(), BlendPattern::init(), BasicPattern::onBlinkOn(), BlendPattern::onBlinkOn(), HueShiftPattern::play(), BlinkStepPattern::poststep(), BouncePattern::poststep(), CrossDopsPattern::poststep(), DripPattern::poststep(), FillPattern::poststep(), LighthousePattern::poststep(), MeteorPattern::poststep(), VortexPattern::poststep(), VortexWipePattern::poststep(), WarpPattern::poststep(), WarpWormPattern::poststep(), and ZigzagPattern::Snake::step().
getPrev()
RGBColor Colorset::getPrev ()
Definition at line 392 of file Colorset.cpp.
{
  if (!m_numColors || !m_palette) {
    return RGB_OFF;
  }
  // handle wrapping at 0
  if (m_curIndex == 0 || m_curIndex == INDEX_NONE) {
    m_curIndex = numColors() - 1;
  } else {
    m_curIndex--;
  }
  // return the color
  return m_palette[m_curIndex];
}
References INDEX_NONE, m_curIndex, m_numColors, m_palette, numColors(), and RGB_OFF.
init()
void Colorset::init (RGBColor c1 = RGB_OFF, RGBColor c2 = RGB_OFF, RGBColor c3 = RGB_OFF, RGBColor c4 = RGB_OFF, RGBColor c5 = RGB_OFF, RGBColor c6 = RGB_OFF, RGBColor c7 = RGB_OFF, RGBColor c8 = RGB_OFF)
Definition at line 86 of file Colorset.cpp.
{
  // clear any existing colors
  clear();
  // would be nice if we could do this another way
  if (!c1.empty()) addColor(c1);
  if (!c2.empty()) addColor(c2);
  if (!c3.empty()) addColor(c3);
  if (!c4.empty()) addColor(c4);
  if (!c5.empty()) addColor(c5);
  if (!c6.empty()) addColor(c6);
  if (!c7.empty()) addColor(c7);
  if (!c8.empty()) addColor(c8);
}
References addColor(), clear(), and RGBColor::empty().
Referenced by Colorset().
initPalette()
bool Colorset::initPalette (uint8_t numColors) [private]
Definition at line 507 of file Colorset.cpp.
{
  if (m_palette) {
    delete[] m_palette;
    m_palette = nullptr;
  }
  if (!numColors) {
    return true;
  }
  //m_palette = (RGBColor *)vcalloc(numColors, sizeof(RGBColor));
  m_palette = new RGBColor[numColors];
  if (!m_palette) {
    ERROR_OUT_OF_MEMORY();
    return false;
  }
  m_numColors = numColors;
  return true;
}
References ERROR_OUT_OF_MEMORY, m_numColors, m_palette, and numColors().
Referenced by operator=(), and unserialize().
numColors()
uint8_t Colorset::numColors () const [inline]
Definition at line 139 of file Colorset.h.
{ return m_numColors; }
References m_numColors.
Referenced by addColorWithValueStyle(), SnowballPattern::blinkOn(), WarpWormPattern::blinkOn(), ColorSelect::blinkSelection(), getNext(), getPrev(), BasicPattern::init(), initPalette(), ColorSelect::onLongClick(), ColorSelect::onShortClick(), ColorSelect::onShortClick2(), Vortex::patternToJson(), peek(), BasicPattern::play(), randomize(), randomizeColors(), Randomizer::rollColorset(), and ColorSelect::showSlotSelection().
onEnd()
bool Colorset::onEnd () const
Definition at line 445 of file Colorset.cpp.
{
  if (!m_numColors) {
    return false;
  }
  return (m_curIndex == m_numColors - 1);
}
References m_curIndex, and m_numColors.
onStart()
bool Colorset::onStart () const
Definition at line 440 of file Colorset.cpp.
{
  return (m_curIndex == 0);
}
References m_curIndex.
operator!=()
bool Colorset::operator!= (const Colorset & other) const
Definition at line 81 of file Colorset.cpp.
{
  return !operator==(other);
}
References operator==().
operator=()
void Colorset::operator= (const Colorset & other)
Definition at line 64 of file Colorset.cpp.
{
  clear();
  initPalette(other.m_numColors);
  for (uint8_t i = 0; i < other.m_numColors; ++i) {
    m_palette[i] = other.m_palette[i];
  }
  resetIndex();
}
References clear(), initPalette(), m_numColors, m_palette, and resetIndex().
operator==()
bool Colorset::operator== (const Colorset & other) const
Definition at line 74 of file Colorset.cpp.
{
  // only compare the palettes for equality
  return (m_numColors == other.m_numColors) &&
         (memcmp(m_palette, other.m_palette, m_numColors * sizeof(RGBColor)) == 0);
}
References m_numColors, and m_palette.
Referenced by equals(), and operator!=().
operator[]()
RGBColor Colorset::operator[] (int index) const
Definition at line 125 of file Colorset.cpp.
{
  return get(index);
}
References get().
peek()
RGBColor Colorset::peek (int32_t offset) const
Definition at line 421 of file Colorset.cpp.
{
  if (!m_numColors || !m_palette) {
    return RGB_OFF;
  }
  uint8_t nextIndex = 0;
  // get index of the next color
  if (offset >= 0) {
    nextIndex = (m_curIndex + offset) % numColors();
  } else {
    if (offset < -1 * (int32_t)(numColors())) {
      return RGB_OFF;
    }
    nextIndex = ((m_curIndex + numColors()) + (int)offset) % numColors();
  }
  // return the color
  return m_palette[nextIndex];
}
References m_curIndex, m_numColors, m_palette, numColors(), and RGB_OFF.
Referenced by SnowballPattern::blinkOn(), WarpWormPattern::blinkOn(), ZigzagPattern::Snake::drawSnake(), and peekNext().
peekNext()
RGBColor Colorset::peekNext () const [inline]
Definition at line 136 of file Colorset.h.
{ return peek(1); }
References peek().
Referenced by BouncePattern::blinkOn(), DoubleStrobePattern::blinkOn(), DripPattern::blinkOn(), FillPattern::blinkOn(), SnowballPattern::blinkOn(), VortexPattern::blinkOn(), VortexWipePattern::blinkOn(), WarpPattern::blinkOn(), and WarpWormPattern::blinkOn().
randomize()
void Colorset::randomize (Random & ctx, uint8_t numColors = 0)
Definition at line 222 of file Colorset.cpp.
{
  clear();
  if (!numColors) {
    numColors = ctx.next8(2, 9);
  }
  ValueStyle valStyle = (ValueStyle)ctx.next8(0, VAL_STYLE_COUNT);
  for (uint8_t i = 0; i < numColors; ++i) {
    // call next8 explicitly in this order because the order they
    // are called is undefined when called as parameters to another function.
    // ex: f(a,b,c) may call in the order a,b,c or c,b,a depending on compiler.
    // So different compilers may produce different results,
    // but like this it is explicit
    uint8_t sat = ctx.next8();
    uint8_t hue = ctx.next8();
    addColorWithValueStyle(ctx, hue, sat, valStyle, numColors, i);
  }
}
References addColorWithValueStyle(), clear(), Random::next8(), numColors(), and VAL_STYLE_COUNT.
Referenced by Vortex::addNewMode(), and Randomizer::rollColorset().
randomizeColors()
void Colorset::randomizeColors (Random & ctx, uint8_t numColors, ColorMode mode)
Definition at line 242 of file Colorset.cpp.
{
  clear();
  if (!numColors) {
    numColors = ctx.next8(mode == MONOCHROMATIC ? 2 : 1, 9);
  }
  uint8_t randomizedHue = ctx.next8();
  uint8_t colorGap = 0;
  if (mode == THEORY && numColors > 1) {
    colorGap = ctx.next8(16, 256 / (numColors - 1));
  }
  ValueStyle valStyle = (ValueStyle)ctx.next8(0, VAL_STYLE_COUNT);
  // the doubleStyle decides if some colors are added to the set twice
  uint8_t doubleStyle = 0;
  if (numColors <= 7) {
    doubleStyle = (ctx.next8(0, 1));
  }
  if (numColors <= 4) {
    doubleStyle = (ctx.next8(0, 2));
  }
  for (uint8_t i = 0; i < numColors; i++) {
    uint8_t hueToUse;
    uint8_t valueToUse = 255;
    if (mode == THEORY) {
      hueToUse = (randomizedHue + (i * colorGap));
    } else if (mode == MONOCHROMATIC) {
      hueToUse = randomizedHue;
      valueToUse = 255 - (i * (256 / numColors));
    } else { // EVENLY_SPACED
      hueToUse = (randomizedHue + (256 / numColors) * i);
    }
    addColorWithValueStyle(ctx, hueToUse, valueToUse, valStyle, numColors, i);
    // double all colors or only first color
    if (doubleStyle == 2 || (doubleStyle == 1 && !i)) {
      addColorWithValueStyle(ctx, hueToUse, valueToUse, valStyle, numColors, i);
    }
  }
}
References addColorWithValueStyle(), clear(), MONOCHROMATIC, Random::next8(), numColors(), THEORY, and VAL_STYLE_COUNT.
Referenced by randomizeComplimentary(), randomizePentadic(), randomizeRainbow(), randomizeSolid(), randomizeSquare(), randomizeTriadic(), and Randomizer::rollColorset().
randomizeColors2()
void Colorset::randomizeColors2 (Random & ctx, ColorMode2 mode)
Definition at line 281 of file Colorset.cpp.
{
  clear();
  uint8_t primaryHue = ctx.next8();
  if (mode == DOUBLE_SPLIT_COMPLIMENTARY) {
    uint8_t splitGap = ctx.next8(1, 64);
    ValueStyle valStyle = (ValueStyle)ctx.next8(0, VAL_STYLE_COUNT);
    addColorWithValueStyle(ctx, (primaryHue + splitGap + 128), 255, valStyle, 5, 0);
    addColorWithValueStyle(ctx, (primaryHue - splitGap), 255, valStyle, 5, 1);
    addColorWithValueStyle(ctx, primaryHue, 255, valStyle, 5, 2);
    addColorWithValueStyle(ctx, (primaryHue + splitGap), 255, valStyle, 5, 3);
    addColorWithValueStyle(ctx, (primaryHue - splitGap + 128), 255, valStyle, 5, 4);
  } else if (mode == TETRADIC) {
    uint8_t secondaryHue = ctx.next8();
    ValueStyle valStyle = (ValueStyle)ctx.next8(0, VAL_STYLE_COUNT);
    addColorWithValueStyle(ctx, primaryHue, 255, valStyle, 4, 0);
    addColorWithValueStyle(ctx, secondaryHue, 255, valStyle, 4, 1);
    addColorWithValueStyle(ctx, (primaryHue + 128), 255, valStyle, 4, 2);
    addColorWithValueStyle(ctx, (secondaryHue + 128), 255, valStyle, 4, 3);
  }
}
References addColorWithValueStyle(), clear(), DOUBLE_SPLIT_COMPLIMENTARY, Random::next8(), TETRADIC, and VAL_STYLE_COUNT.
Referenced by Randomizer::rollColorset().
randomizeComplimentary()
void Colorset::randomizeComplimentary (Random & ctx) [inline]
Definition at line 97 of file Colorset.h.
{ randomizeColors(ctx, 2, Colorset::ColorMode::EVENLY_SPACED); }
References randomizeColors().
randomizePentadic()
void Colorset::randomizePentadic (Random & ctx) [inline]
Definition at line 100 of file Colorset.h.
{ randomizeColors(ctx, 5, Colorset::ColorMode::EVENLY_SPACED); }
References randomizeColors().
randomizeRainbow()
void Colorset::randomizeRainbow (Random & ctx) [inline]
Definition at line 101 of file Colorset.h.
{ randomizeColors(ctx, 8, Colorset::ColorMode::EVENLY_SPACED); }
References randomizeColors().
randomizeSolid()
void Colorset::randomizeSolid (Random & ctx) [inline]
Definition at line 96 of file Colorset.h.
{ randomizeColors(ctx, 1, Colorset::ColorMode::EVENLY_SPACED); }
References randomizeColors().
randomizeSquare()
void Colorset::randomizeSquare (Random & ctx) [inline]
Definition at line 99 of file Colorset.h.
{ randomizeColors(ctx, 4, Colorset::ColorMode::EVENLY_SPACED); }
References randomizeColors().
randomizeTriadic()
void Colorset::randomizeTriadic (Random & ctx) [inline]
Definition at line 98 of file Colorset.h.
{ randomizeColors(ctx, 3, Colorset::ColorMode::EVENLY_SPACED); }
References randomizeColors().
removeColor()
void Colorset::removeColor (uint8_t index)
Definition at line 206 of file Colorset.cpp.
{
  if (index >= m_numColors) {
    return;
  }
  for (uint8_t i = index; i < (m_numColors - 1); ++i) {
    m_palette[i] = m_palette[i + 1];
  }
  m_palette[--m_numColors].clear();
  if (!m_numColors) {
    delete[] m_palette;
    m_palette = nullptr;
  }
}
References RGBColor::clear(), m_numColors, and m_palette.
Referenced by ColorSelect::onLongClick().
resetIndex()
void Colorset::resetIndex ()
Definition at line 387 of file Colorset.cpp.
{
  m_curIndex = INDEX_NONE;
}
References INDEX_NONE, and m_curIndex.
Referenced by clear(), Pattern::init(), SolidPattern::onBlinkOn(), and operator=().
serialize()
bool Colorset::serialize (ByteStream & buffer) const
Definition at line 453 of file Colorset.cpp.
{
  if (!buffer.serialize8(m_numColors)) {
    return false;
  }
  // write all the reds/greens/blues together to maximize chance of
  // repeated values to improve RLE compression
  for (uint8_t i = 0; i < m_numColors; ++i) {
    if (!buffer.serialize8(m_palette[i].red)) {
      return false;
    }
  }
  for (uint8_t i = 0; i < m_numColors; ++i) {
    if (!buffer.serialize8(m_palette[i].green)) {
      return false;
    }
  }
  for (uint8_t i = 0; i < m_numColors; ++i) {
    if (!buffer.serialize8(m_palette[i].blue)) {
      return false;
    }
  }
  return true;
}
References RGBColor::blue, RGBColor::green, m_numColors, m_palette, RGBColor::red, and ByteStream::serialize8().
Referenced by Pattern::serialize().
set()
void Colorset::set (uint8_t index, RGBColor col)
Definition at line 321 of file Colorset.cpp.
{
  // special case for 'setting' a color at the edge of the palette,
  // ie adding a new color when you set an index higher than the max
  if (index >= m_numColors) {
    if (!addColor(col)) {
      ERROR_LOGF("Failed to add new color at index %u", index);
    }
    return;
  }
  if (!m_palette) {
    // should be impossible because if the index is less than
    // the number of colors then there must be non-zero number
    // of colors which means the palette should be initialized
    ERROR_LOGF("Programmer error setting color index %u with no palette", index);
    return;
  }
  m_palette[index] = col;
}
References addColor(), ERROR_LOGF, m_numColors, and m_palette.
Referenced by equals(), and ColorSelect::onLongClick().
setCurIndex()
void Colorset::setCurIndex (uint8_t index)
Definition at line 376 of file Colorset.cpp.
{
  if (!m_numColors) {
    return;
  }
  if (index > (m_numColors - 1)) {
    return;
  }
  m_curIndex = index;
}
References m_curIndex, and m_numColors.
Referenced by BouncePattern::init(), CrossDopsPattern::init(), DoubleStrobePattern::init(), DripPattern::init(), FillPattern::init(), LighthousePattern::init(), SnowballPattern::init(), VortexPattern::init(), VortexWipePattern::init(), WarpPattern::init(), WarpWormPattern::init(), ZigzagPattern::Snake::init(), and SolidPattern::onBlinkOn().
skip()
void Colorset::skip (int32_t amount = 1)
Definition at line 342 of file Colorset.cpp.
{
  if (!m_numColors || !m_palette) {
    return;
  }
  // if the colorset hasn't started yet
  if (m_curIndex == INDEX_NONE) {
    m_curIndex = 0;
  }
  // first modulate the amount to skip to be within +/- the number of colors
  amount %= (int32_t)m_numColors;
  // max = 3
  // m_curIndex = 2
  // amount = -10
  m_curIndex = ((int32_t)m_curIndex + (int32_t)amount) % (int32_t)m_numColors;
  if (m_curIndex > m_numColors) { // must have wrapped
    // simply wrap it back
    m_curIndex += m_numColors;
  }
}
References INDEX_NONE, m_curIndex, m_numColors, and m_palette.
Referenced by PulsishPattern::play(), SnowballPattern::poststep(), and SparkleTracePattern::poststep().
unserialize()
bool Colorset::unserialize (ByteStream & buffer)
Definition at line 478 of file Colorset.cpp.
{
  if (!buffer.unserialize8(&m_numColors)) {
    return false;
  }
  if (m_numColors > MAX_COLOR_SLOTS) {
    return false;
  }
  if (!initPalette(m_numColors)) {
    return false;
  }
  for (uint8_t i = 0; i < m_numColors; ++i) {
    if (!buffer.unserialize8(&m_palette[i].red)) {
      return false;
    }
  }
  for (uint8_t i = 0; i < m_numColors; ++i) {
    if (!buffer.unserialize8(&m_palette[i].green)) {
      return false;
    }
  }
  for (uint8_t i = 0; i < m_numColors; ++i) {
    if (!buffer.unserialize8(&m_palette[i].blue)) {
      return false;
    }
  }
  return true;
}
References RGBColor::blue, RGBColor::green, initPalette(), m_numColors, m_palette, MAX_COLOR_SLOTS, RGBColor::red, and ByteStream::unserialize8().
Referenced by Pattern::unserialize().
Member Data Documentation
m_curIndex
uint8_t Colorset::m_curIndex [private]
Definition at line 157 of file Colorset.h.
Referenced by cur(), curIndex(), getNext(), getPrev(), onEnd(), onStart(), peek(), resetIndex(), setCurIndex(), and skip().
m_numColors
uint8_t Colorset::m_numColors [private]
Definition at line 159 of file Colorset.h.
Referenced by addColor(), addColorWithValueStyle(), adjustBrightness(), clear(), cur(), get(), getNext(), getPrev(), initPalette(), numColors(), onEnd(), operator=(), operator==(), peek(), removeColor(), serialize(), set(), setCurIndex(), skip(), and unserialize().
m_palette
RGBColor* Colorset::m_palette [private]
Definition at line 154 of file Colorset.h.
Referenced by addColor(), adjustBrightness(), clear(), cur(), get(), getNext(), getPrev(), initPalette(), operator=(), operator==(), peek(), removeColor(), serialize(), set(), skip(), and unserialize().
The documentation for this class was generated from the following files:
VortexEngine/src/Colors/Colorset.h
VortexEngine/src/Colors/Colorset.cpp