BackStrobePattern Class Reference
#include <BackStrobePattern.h>
Public Member Functions
BackStrobePattern (const PatternArgs &args)
virtual ~BackStrobePattern ()
virtual void init () override
virtual void play () override
Private Attributes
uint8_t m_stepSpeed
Timer m_stepTimer
bool m_switch
PatternArgs m_firstPatternArgs
PatternArgs m_secondPatternArgs
uint8_t m_firstPat
uint8_t m_secPat
Additional Inherited Members
Detailed Description
Definition at line 9 of file BackStrobePattern.h.
Constructor & Destructor Documentation
BackStrobePattern()
BackStrobePattern::BackStrobePattern (const PatternArgs & args)
Definition at line 3 of file BackStrobePattern.cpp.
                                                            :
  CompoundPattern(args),
  m_stepSpeed(0),
  m_stepTimer(),
  m_switch(),
  m_firstPatternArgs(0, 0, 0),
  m_secondPatternArgs(0, 0, 0),
  m_firstPat(PATTERN_DOPS),
  m_secPat(PATTERN_STROBE)
{
  m_patternID = PATTERN_BACKSTROBE;
  REGISTER_ARG(m_firstPatternArgs.arg1);
  REGISTER_ARG(m_firstPatternArgs.arg2);
  REGISTER_ARG(m_firstPatternArgs.arg3);
  REGISTER_ARG(m_secondPatternArgs.arg1);
  REGISTER_ARG(m_secondPatternArgs.arg2);
  REGISTER_ARG(m_stepSpeed);
  REGISTER_ARG(m_firstPat);
  REGISTER_ARG(m_secPat);
  setArgs(args);
}
References PatternArgs::arg1, PatternArgs::arg2, PatternArgs::arg3, m_firstPat, m_firstPatternArgs, Pattern::m_patternID, m_secondPatternArgs, m_secPat, m_stepSpeed, PATTERN_BACKSTROBE, REGISTER_ARG, and Pattern::setArgs().
 BackStrobePattern()
BackStrobePattern::~BackStrobePattern () [virtual]
Definition at line 25 of file BackStrobePattern.cpp.
{
}
Member Function Documentation
init()
void BackStrobePattern::init () [override], [virtual]
Reimplemented from CompoundPattern.
Definition at line 30 of file BackStrobePattern.cpp.
{
  CompoundPattern::init();
  // timer for switch
  m_stepTimer.reset();
  m_stepTimer.addAlarm(m_stepSpeed * 100);
  m_stepTimer.start();
  // initialize the sub patterns one time first
  setEvensOdds((PatternID)m_firstPat, (PatternID)m_secPat, &m_firstPatternArgs, &m_secondPatternArgs);
}
References Timer::addAlarm(), CompoundPattern::init(), m_firstPat, m_firstPatternArgs, m_secondPatternArgs, m_secPat, m_stepSpeed, m_stepTimer, Timer::reset(), CompoundPattern::setEvensOdds(), and Timer::start().
play()
void BackStrobePattern::play () [override], [virtual]
Reimplemented from CompoundPattern.
Definition at line 43 of file BackStrobePattern.cpp.
{
  if (m_stepTimer.alarm() == 0) {
    // switch which patterns are displayed
    m_switch = !m_switch;
    // update the tip/top patterns based on the switch
    setEvensOdds(m_switch ? (PatternID)m_firstPat : (PatternID)m_secPat,
                m_switch ? (PatternID)m_secPat : (PatternID)m_firstPat,
                m_switch ? &m_firstPatternArgs : &m_secondPatternArgs,
                m_switch ? &m_secondPatternArgs : &m_firstPatternArgs);
  }
  CompoundPattern::play();
}
References Timer::alarm(), m_firstPat, m_firstPatternArgs, m_secondPatternArgs, m_secPat, m_stepTimer, m_switch, CompoundPattern::play(), and CompoundPattern::setEvensOdds().
Member Data Documentation
m_firstPat
uint8_t BackStrobePattern::m_firstPat [private]
Definition at line 30 of file BackStrobePattern.h.
Referenced by BackStrobePattern(), init(), and play().
m_firstPatternArgs
PatternArgs BackStrobePattern::m_firstPatternArgs [private]
Definition at line 28 of file BackStrobePattern.h.
Referenced by BackStrobePattern(), init(), and play().
m_secondPatternArgs
PatternArgs BackStrobePattern::m_secondPatternArgs [private]
Definition at line 29 of file BackStrobePattern.h.
Referenced by BackStrobePattern(), init(), and play().
m_secPat
uint8_t BackStrobePattern::m_secPat [private]
Definition at line 31 of file BackStrobePattern.h.
Referenced by BackStrobePattern(), init(), and play().
m_stepSpeed
uint8_t BackStrobePattern::m_stepSpeed [private]
Definition at line 22 of file BackStrobePattern.h.
Referenced by BackStrobePattern(), and init().
m_stepTimer
Timer BackStrobePattern::m_stepTimer [private]
Definition at line 24 of file BackStrobePattern.h.
Referenced by init(), and play().
m_switch
bool BackStrobePattern::m_switch [private]
Definition at line 26 of file BackStrobePattern.h.
Referenced by play().
The documentation for this class was generated from the following files:
VortexEngine/src/Patterns/Multi/BackStrobePattern.h
VortexEngine/src/Patterns/Multi/BackStrobePattern.cpp