Menu Class Reference
#include <Menu.h>
Public Types
enum MenuAction : uint8_t { MENU_QUIT
, MENU_CONTINUE
, MENU_SKIP
 }
Public Member Functions
Menu (VortexEngine &engine, const RGBColor &col, bool advanced)
virtual ~Menu ()
virtual bool init ()
virtual MenuAction run ()
virtual void onLedSelected ()
virtual void onShortClick ()
virtual void onLongClick ()
virtual void leaveMenu (bool doSave=false)
void setTargetLeds (LedMap targetLeds)
LedMap getTargetLeds () const
Protected Member Functions
void showBulbSelection ()
void showExit ()
void nextBulbSelection ()
virtual bool isValidLedSelection (LedMap selection) const
Protected Attributes
VortexEngine & m_engine
Mode m_previewMode
RGBColor m_menuColor
LedMap m_targetLeds
uint8_t m_curSelection
bool m_ledSelected
bool m_advanced
Private Attributes
bool m_shouldClose
Detailed Description
Definition at line 10 of file Menu.h.
Member Enumeration Documentation
MenuAction
enum Menu::MenuAction : uint8_t
Enumerator
MENU_QUIT
MENU_CONTINUE
MENU_SKIP
Definition at line 19 of file Menu.h.
                  :uint8_t {
    // quit the menus
    MENU_QUIT,
    // continue running the menu
    MENU_CONTINUE,
    // don't run derived menu code, this is used internally
    // by the menu class itself
    MENU_SKIP
  };
Constructor & Destructor Documentation
Menu()
Menu::Menu (VortexEngine & engine, const RGBColor & col, bool advanced)
Definition at line 14 of file Menu.cpp.
                                                                   :
  m_engine(engine),
  m_previewMode(engine),
  m_menuColor(col),
  m_targetLeds(MAP_LED_ALL),
  m_curSelection(0),
  m_ledSelected(false),
  m_advanced(advanced),
  m_shouldClose(false)
{
}
 Menu()
Menu::~Menu () [virtual]
Definition at line 26 of file Menu.cpp.
{
}
Member Function Documentation
getTargetLeds()
LedMap Menu::getTargetLeds () const [inline]
Definition at line 45 of file Menu.h.
                               {
    return m_targetLeds;
  }
References m_targetLeds.
init()
bool Menu::init () [virtual]
Reimplemented in Randomizer, PatternSelect, ModeSharing, GlobalBrightness, FactoryReset, EditorConnection, and ColorSelect.
Definition at line 30 of file Menu.cpp.
{
  // menu is initialized before being run
  if (!m_engine.modes().curMode()) {
    // if you enter a menu and there's no modes, it will add an empty one
    if (m_engine.modes().numModes() > 0) {
      // some kind of serious error
      return false;
    }
    if (!m_engine.modes().addMode(PATTERN_STROBE, RGBColor(RGB_OFF))) {
      // some kind of serious error
      return false;
    }
    if (!m_engine.modes().curMode()) {
      // serious error again
      return false;
    }
  }
  // copy the current mode into the demo mode and initialize it
  m_previewMode = *m_engine.modes().curMode();
  m_previewMode.init();
  // just in case
  m_shouldClose = false;
  return true;
}
References Modes::addMode(), Modes::curMode(), Mode::init(), m_engine, m_previewMode, m_shouldClose, VortexEngine::modes(), Modes::numModes(), PATTERN_STROBE, and RGB_OFF.
Referenced by ColorSelect::init(), EditorConnection::init(), FactoryReset::init(), GlobalBrightness::init(), ModeSharing::init(), PatternSelect::init(), Randomizer::init(), and Menus::openMenu().
isValidLedSelection()
virtual bool Menu::isValidLedSelection (LedMap selection) const [inline], [protected], [virtual]
Reimplemented in ColorSelect.
Definition at line 58 of file Menu.h.
{ return true; }
Referenced by run().
leaveMenu()
void Menu::leaveMenu (bool doSave = false) [virtual]
Reimplemented in EditorConnection.
Definition at line 171 of file Menu.cpp.
{
  m_shouldClose = true;
  if (doSave) {
    m_engine.modes().saveStorage();
  }
}
References m_engine, m_shouldClose, VortexEngine::modes(), and Modes::saveStorage().
Referenced by EditorConnection::leaveMenu(), onLongClick(), ColorSelect::onLongClick(), FactoryReset::onLongClick(), GlobalBrightness::onLongClick(), ModeSharing::onLongClick(), PatternSelect::onLongClick(), Randomizer::onLongClick(), and ModeSharing::receiveModeIR().
nextBulbSelection()
void Menu::nextBulbSelection () [protected]
Definition at line 128 of file Menu.cpp.
{
  Mode *cur = m_engine.modes().curMode();
  // The target led can be 0 through LED_COUNT to represent any led or all leds
  // modulo by LED_COUNT + 1 to include LED_COUNT (all) as a target
  if (m_targetLeds == MAP_LED_ALL) {
    if (cur->isMultiLed()) {
      // do not allow multi led to select anything else
      //break;
    }
    m_targetLeds = MAP_LED(LED_FIRST);
  } else if (m_targetLeds == MAP_LED(LED_LAST)) {
    m_targetLeds = MAP_PAIR_EVENS;
  } else if (m_targetLeds == MAP_PAIR_EVENS) {
    m_targetLeds = MAP_PAIR_ODDS;
  } else if (m_targetLeds == MAP_PAIR_ODDS) {
    m_targetLeds = MAP_LED(LED_MULTI);
  } else if (m_targetLeds == MAP_LED(LED_MULTI)) {
    m_targetLeds = MAP_LED_ALL;
  } else {
    // do not allow multi led to select anything else
    if (cur->isMultiLed()) {
      //m_targetLeds = MAP_LED_ALL;
      //break;
    }
    // iterate as normal
    m_targetLeds = MAP_LED(((m_engine.leds().ledmapGetFirstLed(m_targetLeds) + 1) % (LED_COUNT + 1)));
  }
}
References Modes::curMode(), Mode::isMultiLed(), LED_COUNT, LED_FIRST, LED_LAST, LED_MULTI, Leds::ledmapGetFirstLed(), VortexEngine::leds(), m_engine, m_targetLeds, MAP_LED, MAP_LED_ALL, MAP_PAIR_EVENS, MAP_PAIR_ODDS, and VortexEngine::modes().
Referenced by run().
onLedSelected()
void Menu::onLedSelected () [virtual]
Reimplemented in PatternSelect, and ColorSelect.
Definition at line 158 of file Menu.cpp.
{
}
Referenced by run().
onLongClick()
void Menu::onLongClick () [virtual]
Reimplemented in Randomizer, PatternSelect, ModeSharing, GlobalBrightness, FactoryReset, EditorConnection, and ColorSelect.
Definition at line 166 of file Menu.cpp.
{
  leaveMenu(false);
}
References leaveMenu().
Referenced by Menus::runCurMenu().
onShortClick()
void Menu::onShortClick () [virtual]
Reimplemented in Randomizer, PatternSelect, ModeSharing, GlobalBrightness, FactoryReset, EditorConnection, and ColorSelect.
Definition at line 162 of file Menu.cpp.
{
}
Referenced by Menus::runCurMenu().
run()
Menu::MenuAction Menu::run () [virtual]
Reimplemented in Randomizer, PatternSelect, ModeSharing, GlobalBrightness, FactoryReset, EditorConnection, and ColorSelect.
Definition at line 56 of file Menu.cpp.
{
  // check whether the close flag has been set
  if (m_shouldClose) {
    // reset flag and close
    m_shouldClose = false;
    return MENU_QUIT;
  }
  // if the led has already been selected continue as normal
  // and allow derived menu logic to perform work
  if (m_ledSelected) {
    return MENU_CONTINUE;
  }
  // using manual onShortClick and onLongClick check here because
  // there is no guarantee the child class will call the parent
  // class's onShortClick and onLongClick functions so
  // every time the button is clicked, change the target led
  if (m_engine.button().onShortClick()) {
    do {
      nextBulbSelection();
    } while (!isValidLedSelection(m_targetLeds));
  }
  // on a long press of the button, lock in the target led
  if (m_engine.button().onLongClick()) {
    m_ledSelected = true;
    // call led selected callback
    onLedSelected();
    // log about the selection
    DEBUG_LOGF("Led Selected: 0x%x (%s)", m_targetLeds,
      (m_targetLeds == MAP_LED(LED_MULTI)) ? "multi"
        : (m_targetLeds == MAP_LED_ALL) ? "all"
          : "some singles");
  }
  // render the bulb selection
  showBulbSelection();
  // return MENU_SKIP to indicate to derived menu classes that
  // they should skip their logic and just return so that the
  // bulb selection can be rendered
  return MENU_SKIP;
}
References VortexEngine::button(), DEBUG_LOGF, isValidLedSelection(), LED_MULTI, m_engine, m_ledSelected, m_shouldClose, m_targetLeds, MAP_LED, MAP_LED_ALL, MENU_CONTINUE, MENU_QUIT, MENU_SKIP, nextBulbSelection(), onLedSelected(), Button::onLongClick(), Button::onShortClick(), and showBulbSelection().
Referenced by ColorSelect::run(), EditorConnection::run(), FactoryReset::run(), GlobalBrightness::run(), ModeSharing::run(), PatternSelect::run(), Randomizer::run(), and Menus::runCurMenu().
setTargetLeds()
void Menu::setTargetLeds (LedMap targetLeds) [inline]
Definition at line 41 of file Menu.h.
                                        {
    m_targetLeds = targetLeds;
    m_ledSelected = true;
  }
References m_ledSelected, and m_targetLeds.
showBulbSelection()
void Menu::showBulbSelection () [protected]
Definition at line 102 of file Menu.cpp.
{
  m_engine.leds().clearAll();
  if (m_targetLeds == MAP_LED(LED_MULTI)) {
    LedPos pos = (LedPos)((m_engine.time().getCurtime() / 30) % LED_COUNT);
    m_engine.leds().blinkIndexOffset(pos, pos * 10, 50, 500, m_menuColor);
  } else {
    m_engine.leds().blinkMap(m_targetLeds, BULB_SELECT_OFF_MS, BULB_SELECT_ON_MS, m_menuColor);
  }
  // blink when selecting
  m_engine.menus().showSelection(RGBColor(m_menuColor.red << 3,
                                          m_menuColor.green << 3,
                                          m_menuColor.blue << 3));
}
References Leds::blinkIndexOffset(), Leds::blinkMap(), RGBColor::blue, BULB_SELECT_OFF_MS, BULB_SELECT_ON_MS, Leds::clearAll(), Time::getCurtime(), RGBColor::green, LED_COUNT, LED_MULTI, VortexEngine::leds(), m_engine, m_menuColor, m_targetLeds, MAP_LED, VortexEngine::menus(), RGBColor::red, Menus::showSelection(), and VortexEngine::time().
Referenced by run().
showExit()
void Menu::showExit () [protected]
Definition at line 117 of file Menu.cpp.
{
  if (m_engine.button().isPressed() && m_engine.button().holdDuration() > SHORT_CLICK_THRESHOLD_TICKS) {
    m_engine.leds().setAll(RGB_RED);
    return;
  }
  m_engine.leds().clearAll();
  m_engine.leds().setAll(RGB_WHITE0);
  m_engine.leds().blinkAll(EXIT_MENU_OFF_MS, EXIT_MENU_ON_MS, RGB_RED0);
}
References Leds::blinkAll(), VortexEngine::button(), Leds::clearAll(), EXIT_MENU_OFF_MS, EXIT_MENU_ON_MS, Button::holdDuration(), Button::isPressed(), VortexEngine::leds(), m_engine, RGB_RED, RGB_RED0, RGB_WHITE0, Leds::setAll(), and SHORT_CLICK_THRESHOLD_TICKS.
Referenced by GlobalBrightness::showBrightnessSelection(), and ColorSelect::showSelection().
Member Data Documentation
m_advanced
bool Menu::m_advanced [protected]
Definition at line 75 of file Menu.h.
Referenced by FactoryReset::init(), FactoryReset::onLongClick(), PatternSelect::onLongClick(), PatternSelect::onShortClick(), ModeSharing::receiveModeIR(), Randomizer::reRollSingles(), PatternSelect::run(), and ModeSharing::showReceiveMode().
m_curSelection
uint8_t Menu::m_curSelection [protected]
Definition at line 71 of file Menu.h.
Referenced by FactoryReset::init(), GlobalBrightness::init(), ColorSelect::onLongClick(), FactoryReset::onLongClick(), GlobalBrightness::onLongClick(), ColorSelect::onShortClick(), FactoryReset::onShortClick(), GlobalBrightness::onShortClick(), GlobalBrightness::showBrightnessSelection(), FactoryReset::showReset(), ColorSelect::showSelection(), and ColorSelect::showSlotSelection().
m_engine
VortexEngine& Menu::m_engine [protected]
Definition at line 61 of file Menu.h.
Referenced by ModeSharing::beginReceivingIR(), ModeSharing::beginSendingIR(), ModeSharing::beginSendingVL(), ModeSharing::continueSendingIR(), ModeSharing::continueSendingVL(), init(), ColorSelect::init(), FactoryReset::init(), GlobalBrightness::init(), Randomizer::init(), leaveMenu(), EditorConnection::leaveMenu(), nextBulbSelection(), ColorSelect::onLedSelected(), PatternSelect::onLedSelected(), ColorSelect::onLongClick(), FactoryReset::onLongClick(), GlobalBrightness::onLongClick(), ModeSharing::onLongClick(), PatternSelect::onLongClick(), Randomizer::onLongClick(), ModeSharing::onShortClick(), PatternSelect::onShortClick(), Randomizer::onShortClick(), EditorConnection::receiveData(), ModeSharing::receiveModeIR(), EditorConnection::receiveModes(), run(), ColorSelect::run(), EditorConnection::run(), GlobalBrightness::run(), PatternSelect::run(), Randomizer::run(), EditorConnection::sendCurModeVL(), EditorConnection::sendModes(), GlobalBrightness::showBrightnessSelection(), showBulbSelection(), EditorConnection::showEditor(), showExit(), ColorSelect::showFullSet(), Randomizer::showRandomizationSelect(), ModeSharing::showReceiveMode(), FactoryReset::showReset(), ColorSelect::showSelection(), ModeSharing::showSendModeIR(), ModeSharing::showSendModeVL(), and ColorSelect::showSlotSelection().
m_ledSelected
bool Menu::m_ledSelected [protected]
Definition at line 73 of file Menu.h.
Referenced by ColorSelect::init(), EditorConnection::init(), FactoryReset::init(), GlobalBrightness::init(), ModeSharing::init(), run(), and setTargetLeds().
m_menuColor
RGBColor Menu::m_menuColor [protected]
Definition at line 66 of file Menu.h.
Referenced by PatternSelect::onLongClick(), and showBulbSelection().
m_previewMode
Mode Menu::m_previewMode [protected]
Definition at line 64 of file Menu.h.
Referenced by EditorConnection::clearDemo(), init(), ColorSelect::isValidLedSelection(), ModeSharing::onLongClick(), PatternSelect::onLongClick(), Randomizer::onLongClick(), PatternSelect::onShortClick(), EditorConnection::receiveDemoMode(), ModeSharing::receiveModeIR(), Randomizer::reRoll(), Randomizer::reRollMulti(), Randomizer::reRollSingles(), PatternSelect::run(), Randomizer::run(), EditorConnection::sendCurModeVL(), EditorConnection::showEditor(), and ModeSharing::showReceiveMode().
m_shouldClose
bool Menu::m_shouldClose [private]
Definition at line 79 of file Menu.h.
Referenced by init(), leaveMenu(), and run().
m_targetLeds
LedMap Menu::m_targetLeds [protected]
Definition at line 69 of file Menu.h.
Referenced by getTargetLeds(), ColorSelect::init(), FactoryReset::init(), nextBulbSelection(), ColorSelect::onLedSelected(), PatternSelect::onLedSelected(), ColorSelect::onLongClick(), FactoryReset::onLongClick(), PatternSelect::onShortClick(), Randomizer::reRoll(), Randomizer::reRollSingles(), run(), Randomizer::run(), setTargetLeds(), and showBulbSelection().
The documentation for this class was generated from the following files:
VortexEngine/src/Menus/Menu.h
VortexEngine/src/Menus/Menu.cpp