VortexCallbacks Class Reference
#include <VortexLib.h>
Public Member Functions
VortexCallbacks (Vortex &vortex)
virtual ~VortexCallbacks ()
virtual long checkPinHook (uint32_t pin)
virtual void infraredWrite (bool mark, uint32_t amount)
virtual bool serialCheck ()
virtual void serialBegin (uint32_t baud)
virtual int32_t serialAvail ()
virtual size_t serialRead (char *buf, size_t amt)
virtual uint32_t serialWrite (const uint8_t *buf, size_t amt)
virtual void ledsInit (void *cl, int count)
virtual void ledsBrightness (int brightness)
virtual void ledsShow ()
Protected Attributes
Vortex & m_vortex
Detailed Description
Definition at line 38 of file VortexLib.h.
Constructor & Destructor Documentation
VortexCallbacks()
VortexCallbacks::VortexCallbacks (Vortex & vortex) [inline]
Definition at line 41 of file VortexLib.h.
: m_vortex(vortex) {}
 VortexCallbacks()
virtual VortexCallbacks::~VortexCallbacks () [inline], [virtual]
Definition at line 42 of file VortexLib.h.
{}
Member Function Documentation
checkPinHook()
long VortexCallbacks::checkPinHook (uint32_t pin) [virtual]
Reimplemented in VortexCLI::VortexCLICallbacks.
Definition at line 637 of file VortexLib.cpp.
{
  // leaving the pin checking to user-overrides rather than
  // checking the default pins here
  return 1; // HIGH
}
Referenced by Button::check().
infraredWrite()
virtual void VortexCallbacks::infraredWrite (bool mark, uint32_t amount) [inline], [virtual]
Definition at line 48 of file VortexLib.h.
{ }
Referenced by IRSender::sendMark(), VLSender::sendMark(), VLSender::sendSpace(), and IRSender::sendSpace().
ledsBrightness()
virtual void VortexCallbacks::ledsBrightness (int brightness) [inline], [virtual]
Definition at line 63 of file VortexLib.h.
{ }
ledsInit()
virtual void VortexCallbacks::ledsInit (void * cl, int count) [inline], [virtual]
Reimplemented in VortexCLI::VortexCLICallbacks.
Definition at line 61 of file VortexLib.h.
{ }
Referenced by Leds::init(), and Leds::setLedCount().
ledsShow()
virtual void VortexCallbacks::ledsShow () [inline], [virtual]
Reimplemented in VortexCLI::VortexCLICallbacks.
Definition at line 65 of file VortexLib.h.
{ }
Referenced by Leds::update().
serialAvail()
virtual int32_t VortexCallbacks::serialAvail () [inline], [virtual]
Definition at line 54 of file VortexLib.h.
{ return 0; }
Referenced by SerialComs::dataReady(), and SerialComs::read().
serialBegin()
virtual void VortexCallbacks::serialBegin (uint32_t baud) [inline], [virtual]
Definition at line 52 of file VortexLib.h.
{ }
Referenced by SerialComs::checkSerial().
serialCheck()
virtual bool VortexCallbacks::serialCheck () [inline], [virtual]
Definition at line 50 of file VortexLib.h.
{ return false; }
Referenced by SerialComs::checkSerial().
serialRead()
virtual size_t VortexCallbacks::serialRead (char * buf, size_t amt) [inline], [virtual]
Definition at line 57 of file VortexLib.h.
{ return 0; }
Referenced by SerialComs::read().
serialWrite()
virtual uint32_t VortexCallbacks::serialWrite (const uint8_t * buf, size_t amt) [inline], [virtual]
Definition at line 59 of file VortexLib.h.
{ return 0; }
Referenced by SerialComs::write().
Member Data Documentation
m_vortex
Vortex& VortexCallbacks::m_vortex [protected]
Definition at line 69 of file VortexLib.h.
Referenced by VortexCLI::VortexCLICallbacks::checkPinHook().
The documentation for this class was generated from the following files:
VortexEngine/VortexLib/VortexLib.h
VortexEngine/VortexLib/VortexLib.cpp