VortexEngine/src/Leds/LedTypes.h File Reference
#include <inttypes.h>
#include <stdarg.h>
#include `../VortexConfig.h`
Macros
#define isEven(pos) ((pos % 2) == 0)
#define isOdd(pos) ((pos % 2) != 0)
#define isOrbitEven(pos) ((MAP_LED(pos) & MAP_RINGS_EVEN) == MAP_LED(pos))
#define pairEven(pair) (LedPos)((uint32_t)pair * 2)
#define pairOdd(pair) (LedPos)(((uint32_t)pair * 2) + 1)
#define MAP_LED(led) (LedMap)((uint64_t)1 << led)
#define MAP_PAIR_TOP(pair) MAP_LED(pairTop(pair))
#define MAP_PAIR_BOT(pair) MAP_LED(pairBot(pair))
#define MAP_PAIR_EVEN(pair) MAP_LED(pairEven(pair))
#define MAP_PAIR_ODD(pair) MAP_LED(pairOdd(pair))
#define MAP_PAIR(pair) (MAP_PAIR_EVEN(pair) | MAP_PAIR_ODD(pair))
#define MAP_IS_ONE_LED(map) (map && !(map & (map-1)))
#define MAP_FOREACH_LED(map) for (LedPos pos = ledmapGetFirstLed(map); pos < LED_COUNT; pos = ledmapGetNextLed(map, pos))
#define MAP_LED_ALL ((2 << (LED_COUNT - 1)) - 1)
#define MAP_LED_NONE 0
#define MAP_INVERSE(map) ((~map) & MAP_LED_ALL)
#define MAP_PAIR_EVENS (((1 << LED_COUNT) - 1) & 0x55555555)
#define MAP_PAIR_ODDS (((1 << LED_COUNT) - 1) & 0xAAAAAAAA)
#define MAP_PAIR_ODD_EVENS (MAP_PAIR_EVEN(PAIR_0) | MAP_PAIR_EVEN(PAIR_2) | MAP_PAIR_EVEN(PAIR_4))
#define MAP_PAIR_ODD_ODDS (MAP_PAIR_ODD(PAIR_0) | MAP_PAIR_ODD(PAIR_2) | MAP_PAIR_ODD(PAIR_4))
#define MAP_PAIR_EVEN_EVENS (MAP_PAIR_EVEN(PAIR_3) | MAP_PAIR_EVEN(PAIR_1))
#define MAP_PAIR_EVEN_ODDS (MAP_PAIR_ODD(PAIR_3) | MAP_PAIR_ODD(PAIR_1))
#define MAP_ALL_TOP
#define MAP_ALL_BOT
#define MAP_ALL_FACE (MAP_ALL_TOP | MAP_ALL_BOT)
#define MAP_RING_INNER
#define MAP_RING_MIDDLE
#define MAP_RING_OUTER
#define MAP_RING_EDGE (MAP_LED(LED_3) | MAP_LED(LED_10) | MAP_LED(LED_17) | MAP_LED(LED_24))
#define MAP_RINGS_EVEN (MAP_RING_INNER | MAP_RING_OUTER)
#define MAP_RINGS_ODD (MAP_RING_MIDDLE | MAP_RING_EDGE)
#define MAP_QUADRANT_1
#define MAP_QUADRANT_2
#define MAP_QUADRANT_3
#define MAP_QUADRANT_4
#define MAP_LINE_1 (MAP_QUADRANT_1 | MAP_QUADRANT_3)
#define MAP_LINE_2 (MAP_QUADRANT_2 | MAP_QUADRANT_4)
Typedefs
typedef uint64_t LedMap
Enumerations
enum LedPos : uint8_t {
LED_FIRST = 0
, LED_0 = LED_FIRST
, LED_1
, LED_2
,
LED_3
, LED_4
, LED_5
, LED_6
,
LED_7
, LED_8
, LED_9
, LED_10
,
LED_11
, LED_12
, LED_13
, LED_14
,
LED_15
, LED_16
, LED_17
, LED_18
,
LED_19
, LED_20
, LED_21
, LED_22
,
LED_23
, LED_24
, LED_25
, LED_26
,
LED_27
, LED_COUNT
, LED_LAST = (LED_COUNT - 1)
, LED_ALL = LED_COUNT
,
LED_MULTI = (LED_COUNT + 1)
, LED_ALL_SINGLE = (LED_COUNT + 2)
, LED_ANY = (LED_COUNT + 3)
 }
enum Quadrant : uint8_t {
QUADRANT_FIRST = 0
, QUADRANT_1 = QUADRANT_FIRST
, QUADRANT_2
, QUADRANT_3
,
QUADRANT_4
, QUADRANT_5
, QUADRANT_COUNT
, QUADRANT_LAST = (QUADRANT_COUNT - 1)
 }
enum Ring : uint8_t {
RING_FIRST = 0
, RING_1 = RING_FIRST
, RING_2
, RING_3
,
RING_4
, RING_COUNT
, RING_LAST = (RING_COUNT - 1)
 }
enum Pair : uint8_t {
PAIR_FIRST = 0
, PAIR_0 = PAIR_FIRST
, PAIR_1
, PAIR_2
,
PAIR_3
, PAIR_4
, PAIR_5
, PAIR_6
,
PAIR_7
, PAIR_8
, PAIR_9
, PAIR_10
,
PAIR_11
, PAIR_12
, PAIR_13
, PAIR_14
,
PAIR_15
, PAIR_COUNT
, PAIR_LAST = (PAIR_COUNT - 1)
 }
Functions
bool isPairTop (LedPos pos)
bool isPairBot (LedPos pos)
bool isPairSide (LedPos pos)
Pair ledToPair (LedPos pos)
LedPos pairTop (Pair pair)
LedPos pairBot (Pair pair)
Quadrant ledToQuadrant (LedPos led)
LedPos quadrantFirstLed (Quadrant quadrant)
LedPos quadrantMiddleLed (Quadrant quadrant)
LedPos quadrantLastLed (Quadrant quadrant)
LedPos ledmapGetFirstLed (LedMap map)
LedPos ledmapGetNextLed (LedMap map, LedPos pos)
void ledmapSetLed (LedMap &map, LedPos pos)
void ledmapSetPair (LedMap &map, Pair pair)
bool ledmapCheckLed (LedMap map, LedPos pos)
bool ledmapCheckPair (LedMap map, Pair pair)
LedPos & operator++ (LedPos &c)
LedPos operator++ (LedPos &c, int)
LedPos operator+ (LedPos &c, int b)
LedPos & operator+= (LedPos &c, int b)
LedPos operator- (LedPos &c, int b)
LedPos & operator-= (LedPos &c, int b)
Quadrant & operator++ (Quadrant &c)
Quadrant operator++ (Quadrant &c, int)
Quadrant operator+ (Quadrant &c, int b)
Quadrant & operator+= (Quadrant &c, int b)
Quadrant operator- (Quadrant &c, int b)
Quadrant & operator-= (Quadrant &c, int b)
Ring & operator++ (Ring &c)
Ring operator++ (Ring &c, int)
Ring operator+ (Ring &c, int b)
Ring & operator+= (Ring &c, int b)
Ring operator- (Ring &c, int b)
Ring & operator-= (Ring &c, int b)
Pair & operator++ (Pair &c)
Pair operator++ (Pair &c, int)
Pair operator+ (Pair &c, int b)
Pair operator- (Pair &c, int b)
Macro Definition Documentation
isEven
#define isEven(pos) ((pos % 2) == 0)
Definition at line 161 of file LedTypes.h.
isOdd
#define isOdd(pos) ((pos % 2) != 0)
Definition at line 162 of file LedTypes.h.
isOrbitEven
#define isOrbitEven(pos) ((MAP_LED(pos) & MAP_RINGS_EVEN) == MAP_LED(pos))
Definition at line 165 of file LedTypes.h.
MAP_ALL_BOT
#define MAP_ALL_BOT
Value:
                     (MAP_LED(LED_4) | MAP_LED(LED_5) | MAP_LED(LED_6) | MAP_LED(LED_7) | \
                     MAP_LED(LED_8) | MAP_LED(LED_9) | MAP_LED(LED_18) | MAP_LED(LED_19) | \
                     MAP_LED(LED_20) | MAP_LED(LED_21) | MAP_LED(LED_22) | MAP_LED(LED_23))
Definition at line 361 of file LedTypes.h.
MAP_ALL_FACE
#define MAP_ALL_FACE (MAP_ALL_TOP | MAP_ALL_BOT)
Definition at line 366 of file LedTypes.h.
MAP_ALL_TOP
#define MAP_ALL_TOP
Value:
                     (MAP_LED(LED_0) | MAP_LED(LED_1) | MAP_LED(LED_2) | MAP_LED(LED_11) | \
                     MAP_LED(LED_12) | MAP_LED(LED_13) | MAP_LED(LED_14) | MAP_LED(LED_15) | \
                     MAP_LED(LED_16) | MAP_LED(LED_25) | MAP_LED(LED_26) | MAP_LED(LED_27))
Definition at line 356 of file LedTypes.h.
MAP_FOREACH_LED
#define MAP_FOREACH_LED(map) for (LedPos pos = ledmapGetFirstLed(map); pos < LED_COUNT; pos = ledmapGetNextLed(map, pos))
Definition at line 302 of file LedTypes.h.
MAP_INVERSE
#define MAP_INVERSE(map) ((~map) & MAP_LED_ALL)
Definition at line 342 of file LedTypes.h.
MAP_IS_ONE_LED
#define MAP_IS_ONE_LED(map) (map && !(map & (map-1)))
Definition at line 299 of file LedTypes.h.
MAP_LED
#define MAP_LED(led) (LedMap)((uint64_t)1 << led)
Definition at line 291 of file LedTypes.h.
MAP_LED_ALL
#define MAP_LED_ALL ((2 << (LED_COUNT - 1)) - 1)
Definition at line 337 of file LedTypes.h.
MAP_LED_NONE
#define MAP_LED_NONE 0
Definition at line 340 of file LedTypes.h.
MAP_LINE_1
#define MAP_LINE_1 (MAP_QUADRANT_1 | MAP_QUADRANT_3)
Definition at line 389 of file LedTypes.h.
MAP_LINE_2
#define MAP_LINE_2 (MAP_QUADRANT_2 | MAP_QUADRANT_4)
Definition at line 390 of file LedTypes.h.
MAP_PAIR
#define MAP_PAIR(pair) (MAP_PAIR_EVEN(pair) | MAP_PAIR_ODD(pair))
Definition at line 296 of file LedTypes.h.
MAP_PAIR_BOT
#define MAP_PAIR_BOT(pair) MAP_LED(pairBot(pair))
Definition at line 293 of file LedTypes.h.
MAP_PAIR_EVEN
#define MAP_PAIR_EVEN(pair) MAP_LED(pairEven(pair))
Definition at line 294 of file LedTypes.h.
MAP_PAIR_EVEN_EVENS
#define MAP_PAIR_EVEN_EVENS (MAP_PAIR_EVEN(PAIR_3) | MAP_PAIR_EVEN(PAIR_1))
Definition at line 352 of file LedTypes.h.
MAP_PAIR_EVEN_ODDS
#define MAP_PAIR_EVEN_ODDS (MAP_PAIR_ODD(PAIR_3) | MAP_PAIR_ODD(PAIR_1))
Definition at line 353 of file LedTypes.h.
MAP_PAIR_EVENS
#define MAP_PAIR_EVENS (((1 << LED_COUNT) - 1) & 0x55555555)
Definition at line 345 of file LedTypes.h.
MAP_PAIR_ODD
#define MAP_PAIR_ODD(pair) MAP_LED(pairOdd(pair))
Definition at line 295 of file LedTypes.h.
MAP_PAIR_ODD_EVENS
#define MAP_PAIR_ODD_EVENS (MAP_PAIR_EVEN(PAIR_0) | MAP_PAIR_EVEN(PAIR_2) | MAP_PAIR_EVEN(PAIR_4))
Definition at line 349 of file LedTypes.h.
MAP_PAIR_ODD_ODDS
#define MAP_PAIR_ODD_ODDS (MAP_PAIR_ODD(PAIR_0) | MAP_PAIR_ODD(PAIR_2) | MAP_PAIR_ODD(PAIR_4))
Definition at line 350 of file LedTypes.h.
MAP_PAIR_ODDS
#define MAP_PAIR_ODDS (((1 << LED_COUNT) - 1) & 0xAAAAAAAA)
Definition at line 346 of file LedTypes.h.
MAP_PAIR_TOP
#define MAP_PAIR_TOP(pair) MAP_LED(pairTop(pair))
Definition at line 292 of file LedTypes.h.
MAP_QUADRANT_1
#define MAP_QUADRANT_1
Value:
                         (MAP_LED(LED_0) | MAP_LED(LED_1) | MAP_LED(LED_2) | MAP_LED(LED_3) | \
                         MAP_LED(LED_4) | MAP_LED(LED_5) | MAP_LED(LED_6))
Definition at line 381 of file LedTypes.h.
MAP_QUADRANT_2
#define MAP_QUADRANT_2
Value:
                         (MAP_LED(LED_7) | MAP_LED(LED_8) | MAP_LED(LED_9) | MAP_LED(LED_10) | \
                         MAP_LED(LED_11) | MAP_LED(LED_12) | MAP_LED(LED_13))
Definition at line 383 of file LedTypes.h.
MAP_QUADRANT_3
#define MAP_QUADRANT_3
Value:
                         (MAP_LED(LED_14) | MAP_LED(LED_15) | MAP_LED(LED_16) | MAP_LED(LED_17) | \
                         MAP_LED(LED_18) | MAP_LED(LED_19) | MAP_LED(LED_20))
Definition at line 385 of file LedTypes.h.
MAP_QUADRANT_4
#define MAP_QUADRANT_4
Value:
                         (MAP_LED(LED_21) | MAP_LED(LED_22) | MAP_LED(LED_23) | MAP_LED(LED_24) | \
                         MAP_LED(LED_25) | MAP_LED(LED_26) | MAP_LED(LED_27))
Definition at line 387 of file LedTypes.h.
MAP_RING_EDGE
#define MAP_RING_EDGE (MAP_LED(LED_3) | MAP_LED(LED_10) | MAP_LED(LED_17) | MAP_LED(LED_24))
Definition at line 375 of file LedTypes.h.
MAP_RING_INNER
#define MAP_RING_INNER
Value:
                         (MAP_LED(LED_0) | MAP_LED(LED_6) | MAP_LED(LED_7) | MAP_LED(LED_13) | \
                         MAP_LED(LED_14) | MAP_LED(LED_20) | MAP_LED(LED_21) | MAP_LED(LED_27))
Definition at line 369 of file LedTypes.h.
MAP_RING_MIDDLE
#define MAP_RING_MIDDLE
Value:
                         (MAP_LED(LED_1) | MAP_LED(LED_5) | MAP_LED(LED_8) | MAP_LED(LED_12) | \
                         MAP_LED(LED_15) | MAP_LED(LED_19) | MAP_LED(LED_22) | MAP_LED(LED_26))
Definition at line 371 of file LedTypes.h.
MAP_RING_OUTER
#define MAP_RING_OUTER
Value:
                         (MAP_LED(LED_2) | MAP_LED(LED_4) | MAP_LED(LED_9) | MAP_LED(LED_11) | \
                         MAP_LED(LED_16) | MAP_LED(LED_18) | MAP_LED(LED_23) | MAP_LED(LED_25))
Definition at line 373 of file LedTypes.h.
MAP_RINGS_EVEN
#define MAP_RINGS_EVEN (MAP_RING_INNER | MAP_RING_OUTER)
Definition at line 377 of file LedTypes.h.
MAP_RINGS_ODD
#define MAP_RINGS_ODD (MAP_RING_MIDDLE | MAP_RING_EDGE)
Definition at line 378 of file LedTypes.h.
pairEven
#define pairEven(pair) (LedPos)((uint32_t)pair * 2)
Definition at line 168 of file LedTypes.h.
pairOdd
#define pairOdd(pair) (LedPos)(((uint32_t)pair * 2) + 1)
Definition at line 169 of file LedTypes.h.
Typedef Documentation
LedMap
typedef uint64_t LedMap
Definition at line 288 of file LedTypes.h.
Enumeration Type Documentation
LedPos
enum LedPos : uint8_t
Enumerator
LED_FIRST
LED_0
LED_1
LED_2
LED_3
LED_4
LED_5
LED_6
LED_7
LED_8
LED_9
LED_10
LED_11
LED_12
LED_13
LED_14
LED_15
LED_16
LED_17
LED_18
LED_19
LED_20
LED_21
LED_22
LED_23
LED_24
LED_25
LED_26
LED_27
LED_COUNT
LED_LAST
LED_ALL
LED_MULTI
LED_ALL_SINGLE
LED_ANY
Definition at line 10 of file LedTypes.h.
{
  // this should always be first
  LED_FIRST = 0,
  // the first quadrant middle to outside
  LED_0 = LED_FIRST,
  LED_1,
  LED_2,
  // first quadrant tip
  LED_3,
  // the first quadrant outside to middle
  LED_4,
  LED_5,
  LED_6,
  // the second quadrant middle to outside
  LED_7,
  LED_8,
  LED_9,
  // the second quadrant tip
  LED_10,
  // the second quadrant outside to middle
  LED_11,
  LED_12,
  LED_13,
  // the third quadrant middle to outside
  LED_14,
  LED_15,
  LED_16,
  // the third quadrant tip
  LED_17,
  // the third quadrant outside to middle
  LED_18,
  LED_19,
  LED_20,
  // the fourth quadrant middle to outside
  LED_21,
  LED_22,
  LED_23,
  // the fourth quadrant tip
  LED_24,
  // the fourth quadrant outside to middle
  LED_25,
  LED_26,
  LED_27,
  // the number of entries above
  LED_COUNT,
  // the last LED index
  LED_LAST = (LED_COUNT - 1),
  // target all leds (multi and single)
  // When fetching this the same as LED_ANY
  // When setting this will set all of the leds
  LED_ALL = LED_COUNT,
  // target the multi led slot
  //
  // When fetching this will return the multi led slot
  // When setting this will set the multi led slot
  LED_MULTI = (LED_COUNT + 1),
  // target all single led slots
  //
  // When fetching this will return the first single led slot
  // When setting this will set all single led slots
  LED_ALL_SINGLE = (LED_COUNT + 2),
  // Target the 'effective' led slot (any slot)
  //
  // When fetching this will:
  // 1. return the multi led slot if it exists
  // 2. otherwise the first single led slot
  //
  // When setting this will:
  // 1. if setting single led pattern will set all
  // 2. if setting multi led pattern will set multi
  LED_ANY = (LED_COUNT + 3),
  // other customs?
  // LED_EVENS = (LED_COUNT + 2),
  // LED_ODDS = (LED_COUNT + 3),
};
Pair
enum Pair : uint8_t
Enumerator
PAIR_FIRST
PAIR_0
PAIR_1
PAIR_2
PAIR_3
PAIR_4
PAIR_5
PAIR_6
PAIR_7
PAIR_8
PAIR_9
PAIR_10
PAIR_11
PAIR_12
PAIR_13
PAIR_14
PAIR_15
PAIR_COUNT
PAIR_LAST
Definition at line 131 of file LedTypes.h.
{
  PAIR_FIRST = 0,
  // Quadrant 1
  PAIR_0 = PAIR_FIRST,
  PAIR_1,
  PAIR_2,
  PAIR_3,
  // Quadrant 2
  PAIR_4,
  PAIR_5,
  PAIR_6,
  PAIR_7,
  // Quadrant 3
  PAIR_8,
  PAIR_9,
  PAIR_10,
  PAIR_11,
  // Quadrant 4
  PAIR_12,
  PAIR_13,
  PAIR_14,
  PAIR_15,
  PAIR_COUNT,
  PAIR_LAST = (PAIR_COUNT - 1),
};
Quadrant
enum Quadrant : uint8_t
Enumerator
QUADRANT_FIRST
QUADRANT_1
QUADRANT_2
QUADRANT_3
QUADRANT_4
QUADRANT_5
QUADRANT_COUNT
QUADRANT_LAST
Definition at line 106 of file LedTypes.h.
{
  QUADRANT_FIRST = 0,
  QUADRANT_1 = QUADRANT_FIRST,
  QUADRANT_2,
  QUADRANT_3,
  QUADRANT_4,
  QUADRANT_5, // This may look confusing but the extra "quadrant" improves compatibility. The name could improve
  QUADRANT_COUNT, // 5
  QUADRANT_LAST = (QUADRANT_COUNT - 1)
};
Ring
enum Ring : uint8_t
Enumerator
RING_FIRST
RING_1
RING_2
RING_3
RING_4
RING_COUNT
RING_LAST
Definition at line 120 of file LedTypes.h.
{
  RING_FIRST = 0,
  RING_1 = RING_FIRST,
  RING_2,
  RING_3,
  RING_4,
  RING_COUNT,
  RING_LAST = (RING_COUNT - 1)
};
Function Documentation
isPairBot()
bool isPairBot (LedPos pos) [inline]
Definition at line 186 of file LedTypes.h.
{
  switch (pos) {
  case LED_4: case LED_5: case LED_6:
  case LED_7: case LED_8: case LED_9:
  case LED_18: case LED_19: case LED_20:
  case LED_21: case LED_22: case LED_23:
    return true;
  default:
    return false;
  }
}
References LED_18, LED_19, LED_20, LED_21, LED_22, LED_23, LED_4, LED_5, LED_6, LED_7, LED_8, and LED_9.
isPairSide()
bool isPairSide (LedPos pos) [inline]
Definition at line 200 of file LedTypes.h.
{
  switch (pos) {
  case LED_3: case LED_10: case LED_17: case LED_24:
    return true;
  default:
    return false;
  }
}
References LED_10, LED_17, LED_24, and LED_3.
isPairTop()
bool isPairTop (LedPos pos) [inline]
Definition at line 172 of file LedTypes.h.
{
  switch (pos) {
  case LED_0: case LED_1: case LED_2:
  case LED_11: case LED_12: case LED_13:
  case LED_14: case LED_15: case LED_16:
  case LED_25: case LED_26: case LED_27:
    return true;
  default:
    return false;
  }
}
References LED_0, LED_1, LED_11, LED_12, LED_13, LED_14, LED_15, LED_16, LED_2, LED_25, LED_26, and LED_27.
ledmapCheckLed()
bool ledmapCheckLed (LedMap map, LedPos pos) [inline]
Definition at line 408 of file LedTypes.h.
{
  return ((map & (1ull << pos)) != 0);
}
Referenced by Leds::blinkMap(), Leds::clearMap(), ledmapCheckPair(), ColorsetMap::setColorsetAt(), Leds::setMap(), and PatternMap::setPatternAt().
ledmapCheckPair()
bool ledmapCheckPair (LedMap map, Pair pair) [inline]
Definition at line 414 of file LedTypes.h.
{
  return ledmapCheckLed(map, pairTop(pair)) && ledmapCheckLed(map, pairBot(pair));
}
References ledmapCheckLed(), pairBot(), and pairTop().
ledmapGetFirstLed()
LedPos ledmapGetFirstLed (LedMap map) [inline]
Definition at line 305 of file LedTypes.h.
{
  if (map == MAP_LED(LED_MULTI)) {
    return LED_MULTI;
  }
  LedPos pos = LED_FIRST;
  while (map && pos < LED_COUNT) {
    if (map & 1) {
      return pos;
    }
    map >>= 1;
    pos = (LedPos)(pos + 1);
  }
  return LED_COUNT;
}
References LED_COUNT, LED_FIRST, LED_MULTI, and MAP_LED.
Referenced by ColorSelect::onLongClick(), and ColorSelect::run().
ledmapGetNextLed()
LedPos ledmapGetNextLed (LedMap map, LedPos pos) [inline]
Definition at line 322 of file LedTypes.h.
{
  pos = (LedPos)(pos + 1);
  map >>= pos;
  while (map && pos < LED_COUNT) {
    if (map & 1) {
      return pos;
    }
    map >>= 1;
    pos = (LedPos)(pos + 1);
  }
  return LED_COUNT;
}
References LED_COUNT.
ledmapSetLed()
void ledmapSetLed (LedMap & map, LedPos pos) [inline]
Definition at line 395 of file LedTypes.h.
{
  if (pos < LED_COUNT) map |= (1ull << pos);
}
References LED_COUNT.
Referenced by Mode::getSingleLedMap(), and ledmapSetPair().
ledmapSetPair()
void ledmapSetPair (LedMap & map, Pair pair) [inline]
Definition at line 401 of file LedTypes.h.
{
  ledmapSetLed(map, pairTop(pair));
  ledmapSetLed(map, pairBot(pair));
}
References ledmapSetLed(), pairBot(), and pairTop().
ledToPair()
Pair ledToPair (LedPos pos) [inline]
Definition at line 211 of file LedTypes.h.
{
  switch (pos) {
    // Quadrant 1
    case LED_0: case LED_6: return PAIR_0;
    case LED_1: case LED_5: return PAIR_1;
    case LED_2: case LED_4: return PAIR_2;
    case LED_3: return PAIR_3;
    // Quadrant 2
    case LED_7: case LED_13: return PAIR_4;
    case LED_8: case LED_12: return PAIR_5;
    case LED_9: case LED_11: return PAIR_6;
    case LED_10: return PAIR_7;
    // Quadrant 3
    case LED_14: case LED_20: return PAIR_8;
    case LED_15: case LED_19: return PAIR_9;
    case LED_16: case LED_18: return PAIR_10;
    case LED_17: return PAIR_11;
    // Quadrant 4
    case LED_21: case LED_27: return PAIR_12;
    case LED_22: case LED_26: return PAIR_13;
    case LED_23: case LED_25: return PAIR_14;
    case LED_24: return PAIR_15;
    default: return PAIR_FIRST;
  }
}
References LED_0, LED_1, LED_10, LED_11, LED_12, LED_13, LED_14, LED_15, LED_16, LED_17, LED_18, LED_19, LED_2, LED_20, LED_21, LED_22, LED_23, LED_24, LED_25, LED_26, LED_27, LED_3, LED_4, LED_5, LED_6, LED_7, LED_8, LED_9, PAIR_0, PAIR_1, PAIR_10, PAIR_11, PAIR_12, PAIR_13, PAIR_14, PAIR_15, PAIR_2, PAIR_3, PAIR_4, PAIR_5, PAIR_6, PAIR_7, PAIR_8, PAIR_9, and PAIR_FIRST.
ledToQuadrant()
Quadrant ledToQuadrant (LedPos led) [inline]
Definition at line 263 of file LedTypes.h.
{
  return (Quadrant)(led / 7);
}
operator+() [1/4]
LedPos operator+ (LedPos & c, int b) [inline]
Definition at line 431 of file LedTypes.h.
{
  return (LedPos)((uint32_t)c + b);
}
operator+() [2/4]
Pair operator+ (Pair & c, int b) [inline]
Definition at line 530 of file LedTypes.h.
{
  return (Pair)((uint32_t)c + b);
}
operator+() [3/4]
Quadrant operator+ (Quadrant & c, int b) [inline]
Definition at line 462 of file LedTypes.h.
{
  return (Quadrant)((uint32_t)c + b);
}
operator+() [4/4]
Ring operator+ (Ring & c, int b) [inline]
Definition at line 496 of file LedTypes.h.
{
  return (Ring)((uint32_t)c + b);
}
operator++() [1/8]
LedPos& operator++ (LedPos & c) [inline]
Definition at line 420 of file LedTypes.h.
{
  c = LedPos(((uint32_t)c) + 1);
  return c;
}
operator++() [2/8]
LedPos operator++ (LedPos & c, int) [inline]
Definition at line 425 of file LedTypes.h.
{
  LedPos temp = c;
  ++c;
  return temp;
}
operator++() [3/8]
Pair& operator++ (Pair & c) [inline]
Definition at line 519 of file LedTypes.h.
{
  c = Pair(((uint32_t)c) + 1);
  return c;
}
operator++() [4/8]
Pair operator++ (Pair & c, int) [inline]
Definition at line 524 of file LedTypes.h.
{
  Pair temp = c;
  ++c;
  return temp;
}
operator++() [5/8]
Quadrant& operator++ (Quadrant & c) [inline]
Definition at line 451 of file LedTypes.h.
{
  c = Quadrant(((uint32_t)c) + 1);
  return c;
}
operator++() [6/8]
Quadrant operator++ (Quadrant & c, int) [inline]
Definition at line 456 of file LedTypes.h.
{
  Quadrant temp = c;
  ++c;
  return temp;
}
operator++() [7/8]
Ring& operator++ (Ring & c) [inline]
Definition at line 485 of file LedTypes.h.
{
  c = Ring(((uint32_t)c) + 1);
  return c;
}
operator++() [8/8]
Ring operator++ (Ring & c, int) [inline]
Definition at line 490 of file LedTypes.h.
{
  Ring temp = c;
  ++c;
  return temp;
}
operator+=() [1/3]
LedPos& operator+= (LedPos & c, int b) [inline]
Definition at line 435 of file LedTypes.h.
{
  c = LedPos(((uint32_t)c) + b);
  return c;
}
operator+=() [2/3]
Quadrant& operator+= (Quadrant & c, int b) [inline]
Definition at line 467 of file LedTypes.h.
{
  c = Quadrant(((uint32_t)c) + b);
  return c;
}
operator+=() [3/3]
Ring& operator+= (Ring & c, int b) [inline]
Definition at line 501 of file LedTypes.h.
{
  c = Ring(((uint32_t)c) + b);
  return c;
}
operator-() [1/4]
LedPos operator- (LedPos & c, int b) [inline]
Definition at line 440 of file LedTypes.h.
{
  return (LedPos)((uint32_t)c - b);
}
operator-() [2/4]
Pair operator- (Pair & c, int b) [inline]
Definition at line 534 of file LedTypes.h.
{
  return (Pair)((uint32_t)c - b);
}
operator-() [3/4]
Quadrant operator- (Quadrant & c, int b) [inline]
Definition at line 473 of file LedTypes.h.
{
  return (Quadrant)((uint32_t)c - b);
}
operator-() [4/4]
Ring operator- (Ring & c, int b) [inline]
Definition at line 507 of file LedTypes.h.
{
  return (Ring)((uint32_t)c - b);
}
operator-=() [1/3]
LedPos& operator-= (LedPos & c, int b) [inline]
Definition at line 444 of file LedTypes.h.
{
  c = LedPos(((uint32_t)c) - b);
  return c;
}
operator-=() [2/3]
Quadrant& operator-= (Quadrant & c, int b) [inline]
Definition at line 478 of file LedTypes.h.
{
  c = Quadrant(((uint32_t)c) - b);
  return c;
}
operator-=() [3/3]
Ring& operator-= (Ring & c, int b) [inline]
Definition at line 512 of file LedTypes.h.
{
  c = Ring(((uint32_t)c) - b);
  return c;
}
pairBot()
LedPos pairBot (Pair pair) [inline]
Definition at line 251 of file LedTypes.h.
{
  switch (((int)pair) / 4) {
    case 0: return (LedPos)(6 - pair); // pair 0 1 2 3 -> 6 5 4 3
    case 1: return (LedPos)(3 + pair); // pair 4 5 6 7 -> 7 8 9 10
    case 2: return (LedPos)(28 - pair); // pair 8 9 10 11 -> 20 19 18 17
    case 3: return (LedPos)(9 + pair); // pair 12 13 14 15 -> 21 22 23 24
    default: return LED_FIRST;
  }
}
References LED_FIRST.
Referenced by ledmapCheckPair(), ledmapSetPair(), and Leds::setPair().
pairTop()
LedPos pairTop (Pair pair) [inline]
Definition at line 239 of file LedTypes.h.
{
  switch (((int)pair) / 4) {
    case 0: return (LedPos)pair; // pair 0 1 2 3 -> 0 1 2 3
    case 1: return (LedPos)(17 - pair); // pair 4 5 6 7 -> 13 12 11 10
    case 2: return (LedPos)(6 + pair); // pair 8 9 10 11 -> 14 15 16 17
    case 3: return (LedPos)(39 - pair); // pair 12 13 14 15 -> 27 26 25 24
    default: return LED_FIRST;
  }
}
References LED_FIRST.
Referenced by ledmapCheckPair(), ledmapSetPair(), and Leds::setPair().
quadrantFirstLed()
LedPos quadrantFirstLed (Quadrant quadrant) [inline]
Definition at line 269 of file LedTypes.h.
{
  return (LedPos)((uint32_t)quadrant * 7);
}
Referenced by Menu::blinkSelection(), Leds::setQuadrant(), and PatternSelect::showListSelection().
quadrantLastLed()
LedPos quadrantLastLed (Quadrant quadrant) [inline]
Definition at line 281 of file LedTypes.h.
{
  return (LedPos)(((uint32_t)quadrant * 7) + 6);
}
Referenced by Leds::setQuadrant(), and PatternSelect::showListSelection().
quadrantMiddleLed()
LedPos quadrantMiddleLed (Quadrant quadrant) [inline]
Definition at line 275 of file LedTypes.h.
{
  return (LedPos)(((uint32_t)quadrant * 7) + 3);
}