VortexEngine/src/Patterns/Patterns.h File Reference
#include <inttypes.h>
Enumerations
enum PatternID : int8_t {
PATTERN_NONE = (PatternID)-1
, PATTERN_FIRST = 0
, PATTERN_SINGLE_FIRST = PATTERN_FIRST
, PATTERN_STROBE = PATTERN_FIRST
,
PATTERN_HYPERSTROBE
, PATTERN_PICOSTROBE
, PATTERN_STROBIE
, PATTERN_DOPS
,
PATTERN_ULTRADOPS
, PATTERN_STROBEGAP
, PATTERN_HYPERGAP
, PATTERN_PICOGAP
,
PATTERN_STROBIEGAP
, PATTERN_DOPSGAP
, PATTERN_ULTRAGAP
, PATTERN_BLINKIE
,
PATTERN_GHOSTCRUSH
, PATTERN_DOUBLEDOPS
, PATTERN_CHOPPER
, PATTERN_DASHGAP
,
PATTERN_DASHDOPS
, PATTERN_DASHCRUSH
, PATTERN_ULTRADASH
, PATTERN_GAPCYCLE
,
PATTERN_DASHCYCLE
, PATTERN_TRACER
, PATTERN_RIBBON
, PATTERN_MINIRIBBON
,
PATTERN_BLEND
, PATTERN_BLENDSTROBE
, PATTERN_BLENDSTROBEGAP
, PATTERN_COMPLEMENTARY_BLEND
,
PATTERN_COMPLEMENTARY_BLENDSTROBE
, PATTERN_COMPLEMENTARY_BLENDSTROBEGAP
, PATTERN_SOLID
, PATTERN_MULTI_FIRST
,
PATTERN_SINGLE_LAST = (PATTERN_MULTI_FIRST - 1)
, PATTERN_SINGLE_COUNT = (PATTERN_SINGLE_LAST - PATTERN_SINGLE_FIRST) + 1
, PATTERN_HUE_SCROLL = PATTERN_MULTI_FIRST
, PATTERN_THEATER_CHASE
,
PATTERN_CHASER
, PATTERN_ZIGZAG
, PATTERN_ZIPFADE
, PATTERN_DRIP
,
PATTERN_DRIPMORPH
, PATTERN_CROSSDOPS
, PATTERN_DOUBLESTROBE
, PATTERN_METEOR
,
PATTERN_SPARKLETRACE
, PATTERN_VORTEXWIPE
, PATTERN_WARP
, PATTERN_WARPWORM
,
PATTERN_SNOWBALL
, PATTERN_LIGHTHOUSE
, PATTERN_PULSISH
, PATTERN_FILL
,
PATTERN_BOUNCE
, PATTERN_SPLITSTROBIE
, PATTERN_BACKSTROBE
, PATTERN_VORTEX
,
INTERNAL_PATTERNS_END
, PATTERN_MULTI_LAST = (INTERNAL_PATTERNS_END - 1)
, PATTERN_MULTI_COUNT = (PATTERN_MULTI_LAST - PATTERN_MULTI_FIRST) + 1
, PATTERN_LAST = PATTERN_MULTI_LAST
,
PATTERN_COUNT = (PATTERN_LAST - PATTERN_FIRST) + 1
 }
Functions
bool isMultiLedPatternID (PatternID id)
bool isSingleLedPatternID (PatternID id)
PatternID & operator++ (PatternID &c)
PatternID operator++ (PatternID &c, int)
PatternID operator+ (PatternID &c, int b)
PatternID operator- (PatternID &c, int b)
Enumeration Type Documentation
PatternID
enum PatternID : int8_t
Enumerator
PATTERN_NONE
PATTERN_FIRST
PATTERN_SINGLE_FIRST
PATTERN_STROBE
PATTERN_HYPERSTROBE
PATTERN_PICOSTROBE
PATTERN_STROBIE
PATTERN_DOPS
PATTERN_ULTRADOPS
PATTERN_STROBEGAP
PATTERN_HYPERGAP
PATTERN_PICOGAP
PATTERN_STROBIEGAP
PATTERN_DOPSGAP
PATTERN_ULTRAGAP
PATTERN_BLINKIE
PATTERN_GHOSTCRUSH
PATTERN_DOUBLEDOPS
PATTERN_CHOPPER
PATTERN_DASHGAP
PATTERN_DASHDOPS
PATTERN_DASHCRUSH
PATTERN_ULTRADASH
PATTERN_GAPCYCLE
PATTERN_DASHCYCLE
PATTERN_TRACER
PATTERN_RIBBON
PATTERN_MINIRIBBON
PATTERN_BLEND
PATTERN_BLENDSTROBE
PATTERN_BLENDSTROBEGAP
PATTERN_COMPLEMENTARY_BLEND
PATTERN_COMPLEMENTARY_BLENDSTROBE
PATTERN_COMPLEMENTARY_BLENDSTROBEGAP
PATTERN_SOLID
PATTERN_MULTI_FIRST
PATTERN_SINGLE_LAST
PATTERN_SINGLE_COUNT
PATTERN_HUE_SCROLL
PATTERN_THEATER_CHASE
PATTERN_CHASER
PATTERN_ZIGZAG
PATTERN_ZIPFADE
PATTERN_DRIP
PATTERN_DRIPMORPH
PATTERN_CROSSDOPS
PATTERN_DOUBLESTROBE
PATTERN_METEOR
PATTERN_SPARKLETRACE
PATTERN_VORTEXWIPE
PATTERN_WARP
PATTERN_WARPWORM
PATTERN_SNOWBALL
PATTERN_LIGHTHOUSE
PATTERN_PULSISH
PATTERN_FILL
PATTERN_BOUNCE
PATTERN_SPLITSTROBIE
PATTERN_BACKSTROBE
PATTERN_VORTEX
INTERNAL_PATTERNS_END
PATTERN_MULTI_LAST
PATTERN_MULTI_COUNT
PATTERN_LAST
PATTERN_COUNT
Definition at line 11 of file Patterns.h.
{
  // no pattern at all, use this sparingly and default to
  // PATTERN_FIRST when possible
  PATTERN_NONE = (PatternID)-1,
  // first pattern of all
  PATTERN_FIRST = 0,
  // first 'single led' pattern
  PATTERN_SINGLE_FIRST = PATTERN_FIRST,
  // =====================================
  // all 'single led' patterns below
  PATTERN_STROBE = PATTERN_FIRST,
  PATTERN_HYPERSTROBE,
  PATTERN_PICOSTROBE,
  PATTERN_STROBIE,
  PATTERN_DOPS,
  PATTERN_ULTRADOPS,
  PATTERN_STROBEGAP,
  PATTERN_HYPERGAP,
  PATTERN_PICOGAP,
  PATTERN_STROBIEGAP,
  PATTERN_DOPSGAP,
  PATTERN_ULTRAGAP,
  PATTERN_BLINKIE,
  PATTERN_GHOSTCRUSH,
  PATTERN_DOUBLEDOPS,
  PATTERN_CHOPPER,
  PATTERN_DASHGAP,
  PATTERN_DASHDOPS,
  PATTERN_DASHCRUSH,
  PATTERN_ULTRADASH,
  PATTERN_GAPCYCLE,
  PATTERN_DASHCYCLE,
  PATTERN_TRACER,
  PATTERN_RIBBON,
  PATTERN_MINIRIBBON,
  PATTERN_BLEND,
  PATTERN_BLENDSTROBE,
  PATTERN_BLENDSTROBEGAP,
  PATTERN_COMPLEMENTARY_BLEND,
  PATTERN_COMPLEMENTARY_BLENDSTROBE,
  PATTERN_COMPLEMENTARY_BLENDSTROBEGAP,
  PATTERN_SOLID,
  // ADD NEW SINGLE LED PATTERNS HERE
  // WARNING This will offset all multi-led patterns so sharing of patterns
  // will be misaligned, for ex. IR and save files.
  // =====================================
  // Pattern Meta Constants:
  PATTERN_MULTI_FIRST,
  PATTERN_SINGLE_LAST = (PATTERN_MULTI_FIRST - 1),
  PATTERN_SINGLE_COUNT = (PATTERN_SINGLE_LAST - PATTERN_SINGLE_FIRST) + 1,
  // =====================================
  // all 'multi led' patterns below
  PATTERN_HUE_SCROLL = PATTERN_MULTI_FIRST,
  PATTERN_THEATER_CHASE,
  PATTERN_CHASER,
  PATTERN_ZIGZAG,
  PATTERN_ZIPFADE,
  PATTERN_DRIP,
  PATTERN_DRIPMORPH,
  PATTERN_CROSSDOPS,
  PATTERN_DOUBLESTROBE,
  PATTERN_METEOR,
  PATTERN_SPARKLETRACE,
  PATTERN_VORTEXWIPE,
  PATTERN_WARP,
  PATTERN_WARPWORM,
  PATTERN_SNOWBALL,
  PATTERN_LIGHTHOUSE,
  PATTERN_PULSISH,
  PATTERN_FILL,
  PATTERN_BOUNCE,
  PATTERN_SPLITSTROBIE,
  PATTERN_BACKSTROBE,
  PATTERN_VORTEX,
  // ADD NEW MULTI LED PATTERNS HERE
  // =====================================
  INTERNAL_PATTERNS_END, // <<< DON'T USE OR TOUCH THIS ONE
  PATTERN_MULTI_LAST = (INTERNAL_PATTERNS_END - 1),
  PATTERN_MULTI_COUNT = (PATTERN_MULTI_LAST - PATTERN_MULTI_FIRST) + 1,
  PATTERN_LAST = PATTERN_MULTI_LAST,
  PATTERN_COUNT = (PATTERN_LAST - PATTERN_FIRST) + 1, // total number of patterns
};
Function Documentation
isMultiLedPatternID()
bool isMultiLedPatternID (PatternID id) [inline]
Definition at line 106 of file Patterns.h.
                                              {
  return id >= PATTERN_MULTI_FIRST && id <= PATTERN_MULTI_LAST;
}
References PATTERN_MULTI_FIRST, and PATTERN_MULTI_LAST.
Referenced by PatternBuilder::make(), PatternBuilder::makeMulti(), PatternSelect::onShortClick(), and Mode::setPattern().
isSingleLedPatternID()
bool isSingleLedPatternID (PatternID id) [inline]
Definition at line 109 of file Patterns.h.
                                               {
  return id < PATTERN_MULTI_FIRST;
}
References PATTERN_MULTI_FIRST.
Referenced by PatternBuilder::makeSingle().
operator+()
PatternID operator+ (PatternID & c, int b) [inline]
Definition at line 125 of file Patterns.h.
{
  return (PatternID)((uint16_t)c + b);
}
operator++() [1/2]
PatternID& operator++ (PatternID & c) [inline]
Definition at line 114 of file Patterns.h.
{
  c = PatternID(((uint16_t)c) + 1);
  return c;
}
operator++() [2/2]
PatternID operator++ (PatternID & c, int) [inline]
Definition at line 119 of file Patterns.h.
{
  PatternID temp = c;
  ++c;
  return temp;
}
operator-()
PatternID operator- (PatternID & c, int b) [inline]
Definition at line 129 of file Patterns.h.
{
  return (PatternID)((uint16_t)c - b);
}