VortexEngine/VortexCLI/VortexCLI.cpp File Reference
#include <algorithm>
#include <iostream>
#include <sstream>
#include <iomanip>
#include <string>
#include <ctime>
#include <map>
#include <sys/ioctl.h>
#include <termios.h>
#include <unistd.h>
#include <getopt.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <stdio.h>
#include `VortexCLI.h`
#include `Log/Log.h`
#include `VortexLib.h`
#include `Patterns/PatternBuilder.h`
#include `Time/TimeControl.h`
#include `Colors/ColorTypes.h`
#include `Colors/Colorset.h`
#include `Buttons/Button.h`
#include `Time/Timings.h`
#include `Menus/Menus.h`
#include `Modes/Modes.h`
#include `Modes/Mode.h`
#include `Patterns/Pattern.h`
#include `Patterns/Single/SingleLedPattern.h`
Macros
#define RECORD_FILE `recorded_input.txt`
#define NUM_USAGE (sizeof(input_usage) / sizeof(input_usage[0]))
#define SPACESTR
#define LINESTR
#define SPACES(amt) SPACESTR + (sizeof(SPACESTR) - (amt))
#define LINE(amt) LINESTR + (sizeof(LINESTR) - (amt))
Functions
static void print_usage (const char *program_name)
static void restore_terminal ()
void set_terminal_nonblocking ()
int main (int argc, char *argv[])
Variables
VortexCLI * g_pVortexCLI = nullptr
const char * input_usage []
const char * input_usage_brief [NUM_USAGE]
static struct option long_options []
std::map< std::string, int > color_map
static struct termios orig_term_attr = {0}
uint32_t term_columns = 0
Macro Definition Documentation
LINE
#define LINE(amt) LINESTR + (sizeof(LINESTR) - (amt))
Definition at line 113 of file VortexCLI.cpp.
LINESTR
#define LINESTR
Value:
                 "-----------------------------------------------------------------------------------------------------------------------------------------------------" \
                 "-----------------------------------------------------------------------------------------------------------------------------------------------------" \
                 "-----------------------------------------------------------------------------------------------------------------------------------------------------" \
                 "-----------------------------------------------------------------------------------------------------------------------------------------------------" \
                 "-----------------------------------------------------------------------------------------------------------------------------------------------------" \
                 "-----------------------------------------------------------------------------------------------------------------------------------------------------" \
                 "-----------------------------------------------------------------------------------------------------------------------------------------------------" \
                 "-----------------------------------------------------------------------------------------------------------------------------------------------------" \
                 "-----------------------------------------------------------------------------------------------------------------------------------------------------"
Definition at line 100 of file VortexCLI.cpp.
NUM_USAGE
#define NUM_USAGE (sizeof(input_usage) / sizeof(input_usage[0]))
Definition at line 66 of file VortexCLI.cpp.
RECORD_FILE
#define RECORD_FILE `recorded_input.txt`
Definition at line 43 of file VortexCLI.cpp.
SPACES
#define SPACES(amt) SPACESTR + (sizeof(SPACESTR) - (amt))
Definition at line 111 of file VortexCLI.cpp.
SPACESTR
#define SPACESTR
Value:
                 " " \
                 " " \
                 " " \
                 " " \
                 " " \
                 " " \
                 " " \
                 " " \
                 " " \
                 " "
Definition at line 88 of file VortexCLI.cpp.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 784 of file VortexCLI.cpp.
{
  VortexCLI cli;
  cli.init(argc, argv);
#ifndef WASM
  while (cli.stillRunning()) {
    cli.run();
  }
#endif
  return 0;
}
References VortexCLI::init(), VortexCLI::run(), and VortexCLI::stillRunning().
print_usage()
static void print_usage (const char * program_name) [static]
Definition at line 228 of file VortexCLI.cpp.
{
  fprintf(stderr, "Usage: %s [options] < input commands\n", program_name);
  fprintf(stderr, "Output Selection (at least one required):\n");
  fprintf(stderr, " -x, --hex Use hex values to represent led colors\n");
  fprintf(stderr, " -c, --color Use console color codes to represent led colors\n");
  fprintf(stderr, " -s, --silent Do not print any output while running\n");
  fprintf(stderr, "\n");
  fprintf(stderr, "Engine Control Flags (optional):\n");
  fprintf(stderr, " -t, --no-timestep Bypass the timestep and run as fast as possible\n");
  fprintf(stderr, " -l, --lockstep Only step once each time an input is received\n");
  fprintf(stderr, " -i, --in-place Print the output in-place (interactive mode)\n");
  fprintf(stderr, " -r, --record Record the inputs and dump to a file after (" RECORD_FILE ")\n");
  fprintf(stderr, " -a, --autowake Automatically and instantly wake on sleep (disable sleep)\n");
  fprintf(stderr, " -n, --nolock Automatically unlock upon locking the chip (disable lock)\n");
  fprintf(stderr, " -q, --quick Exit immediately after initialization (useful to convert data)\n");
  fprintf(stderr, "\n");
  fprintf(stderr, "Storage and Data Conversion (optional):\n");
  fprintf(stderr, " -S, --storage [file] Persistent storage to file (default file: FlashStorage.flash)\n");
  fprintf(stderr, " -W, --write-save <file> Write a full .vortex savefile at exit\n");
  fprintf(stderr, " -M, --write-mode <file> At exit write the current mode to a .vtxmode file\n");
  fprintf(stderr, " -L, --load-save <file> Load a vortex savefile (either .vortex or .vtxmode)\n");
  fprintf(stderr, " -I, --json-in [file] Load json from file at init (if no file: read from stdin)\n");
  fprintf(stderr, " -O, --json-out [file] Dump json to file at exit (if no file: write to stdout)\n");
  fprintf(stderr, " -H, --json-human-read Dump human readable json, instead of condensed json\n");
  fprintf(stderr, "\n");
  fprintf(stderr, "Initial Pattern Options (optional):\n");
  fprintf(stderr, " -P, --pattern <id> Preset the pattern ID on the first mode (numeric ID or pattern name ex: blend)\n");
  fprintf(stderr, " -C, --colorset c1,c2... Preset the colorset on the first mode (csv list of hex codes or color names)\n");
  fprintf(stderr, " -A, --arguments a1,a2... Preset the arguments on the first mode (csv list of arguments)\n");
  fprintf(stderr, "\n");
  fprintf(stderr, "Other Options:\n");
  fprintf(stderr, " -h, --help Display this help message\n");
  fprintf(stderr, "\n");
  fprintf(stderr, "Input Commands (pass to stdin):");
  for (uint32_t i = 0; i < NUM_USAGE; ++i) {
    fprintf(stderr, "%s", input_usage[i]);
  }
  fprintf(stderr, "\n\n");
  fprintf(stderr, "Example Usage:\n");
  fprintf(stderr, " ./vortex --color\n");
  fprintf(stderr, " ./vortex -ci -P42 -Ccyan,purple\n");
  fprintf(stderr, " ./vortex -ct -Pblend -Ccyan,yellow,magenta <<< w100q\n");
  fprintf(stderr, " ./vortex -sq -L mysave.vortex -O output_data.json\n");
  fprintf(stderr, " ./vortex -sq -L mymode.vtxmode -O output_data.json\n");
}
Referenced by VortexCLI::init().
restore_terminal()
static void restore_terminal () [static]
Definition at line 292 of file VortexCLI.cpp.
{
  tcsetattr(STDIN_FILENO, TCSANOW, &orig_term_attr);
}
References orig_term_attr.
Referenced by set_terminal_nonblocking().
set_terminal_nonblocking()
void set_terminal_nonblocking ()
Definition at line 297 of file VortexCLI.cpp.
{
  struct termios term_attr = {0};
  // Get the current terminal attributes and store them
  tcgetattr(STDIN_FILENO, &term_attr);
  orig_term_attr = term_attr;
  // Set the terminal in non-canonical mode (raw mode)
  term_attr.c_lflag &= ~(ICANON | ECHO);
  // Set the minimum number of input bytes read at a time to 1
  term_attr.c_cc[VMIN] = 1;
  // Set the timeout for read to 0 (no waiting)
  term_attr.c_cc[VTIME] = 0;
  // Apply the new terminal attributes
  tcsetattr(STDIN_FILENO, TCSANOW, &term_attr);
  // Set the terminal to non-blocking mode
  int flags = fcntl(STDIN_FILENO, F_GETFL, 0);
  fcntl(STDIN_FILENO, F_SETFL, flags | O_NONBLOCK);
  // Register the restore_terminal function to be called at exit
  atexit(restore_terminal);
}
References orig_term_attr, and restore_terminal().
Referenced by VortexCLI::init().
Variable Documentation
color_map
std::map<std::string, int> color_map
Initial value:
= {
    {"black", 0x000000},
    {"white", 0xFFFFFF},
    {"red", 0xFF0000},
    {"lime", 0x00FF00},
    {"blue", 0x0000FF},
    {"yellow", 0xFFFF00},
    {"cyan", 0x00FFFF},
    {"magenta", 0xFF00FF},
    {"silver", 0xC0C0C0},
    {"gray", 0x808080},
    {"maroon", 0x800000},
    {"olive", 0x808000},
    {"green", 0x008000},
    {"purple", 0x800080},
    {"teal", 0x008080},
    {"navy", 0x000080},
    {"orange", 0xFFA500},
    {"pink", 0xFFC0CB},
    {"brown", 0xA52A2A}
    
}
Definition at line 205 of file VortexCLI.cpp.
Referenced by VortexCLI::init().
g_pVortexCLI
VortexCLI* g_pVortexCLI = nullptr
Definition at line 45 of file VortexCLI.cpp.
Referenced by VortexCLI::init(), VortexCLI::VortexCLICallbacks::ledsInit(), and VortexCLI::VortexCLICallbacks::ledsShow().
input_usage
const char* input_usage[]
Initial value:
= {
  "\n c standard short click",
  "\n l standard long click",
  "\n m open menus length click",
  "\n a enter adv menu length click (enter adv menu from menus)",
  "\n d delete length click (delete color in col select)",
  "\n s enter sleep length click (enter sleep at main modes)",
  "\n f force sleep length click (force sleep anywhere)",
  "\n t toggle button pressed (only way to wake after sleep)",
  "\n r rapid button click (ex: r15)",
  "\n w wait 1 tick",
  "\n <digits> repeat command n times (only single digits in -i mode)",
  "\n b<index> select button index (ex: b0 for first button or b1 for second button)",
  "\n q quit",
}
Definition at line 50 of file VortexCLI.cpp.
Referenced by VortexCLI::show().
input_usage_brief
const char* input_usage_brief[NUM_USAGE]
Initial value:
= {
  "\n c short",
  "\n l long",
  "\n m menus",
  "\n a adv menu",
  "\n d delete col",
  "\n s sleep",
  "\n f force sleep",
  "\n t toggle",
  "\n r rapid",
  "\n w wait",
  "\n <digits> repeat",
  "\n b<index> button idx",
  "\n q quit",
}
Definition at line 69 of file VortexCLI.cpp.
Referenced by VortexCLI::show().
long_options
struct option long_options[] [static]
Initial value:
= {
  {"hex", no_argument, nullptr, 'x'},
  {"color", no_argument, nullptr, 'c'},
  {"silent", no_argument, nullptr, 's'},
  {"no-timestep", no_argument, nullptr, 't'},
  {"lockstep", no_argument, nullptr, 'l'},
  {"in-place", no_argument, nullptr, 'i'},
  {"record", no_argument, nullptr, 'r'},
  {"autowake", no_argument, nullptr, 'a'},
  {"nolock", no_argument, nullptr, 'n'},
  {"quick", no_argument, nullptr, 'q'},
  {"storage", optional_argument, nullptr, 'S'},
  {"write-save", required_argument, nullptr, 'W'},
  {"write-mode", required_argument, nullptr, 'M'},
  {"load-save", required_argument, nullptr, 'L'},
  {"json-in", optional_argument, nullptr, 'I'},
  {"json-out", optional_argument, nullptr, 'O'},
  {"json-human-read", no_argument, nullptr, 'H'},
  {"pattern", required_argument, nullptr, 'P'},
  {"colorset", required_argument, nullptr, 'C'},
  {"arguments", required_argument, nullptr, 'A'},
  {"help", no_argument, nullptr, 'h'},
  {nullptr, 0, nullptr, 0}
}
Definition at line 175 of file VortexCLI.cpp.
Referenced by VortexCLI::init().
orig_term_attr
struct termios orig_term_attr = {0} [static]
Definition at line 228 of file VortexCLI.cpp.
Referenced by restore_terminal(), and set_terminal_nonblocking().
term_columns
uint32_t term_columns = 0
Definition at line 326 of file VortexCLI.cpp.
Referenced by VortexCLI::get_terminal_size(), and VortexCLI::show().