title: Vortex Engine
description: Documentation for the Vortex Engine
remote_theme: pmarsceill/just-the-docs
color_scheme: dark
search_enabled: true
heading_anchors: true
markdown: kramdown
callouts:
  warning:
    title: Warning
    color: yellow
  note:
    title: Note
    color: purple
  important:
    title: Important
    color: red
  remember:
    title: Remember
    color: green
  example:
    title: Example
    color: blue
include:
  - assets/images/
  - assets/js/
  - core/
  - desktop/
  - gloves/
  - orbit/
  - handle/
  - duo/
  - chromadeck/
  - spark/
