MainMenu Class Reference
#include <MainMenu.h>
Static Public Member Functions
static bool init ()
static bool run ()
static void show ()
static void open ()
static bool isOpen ()
Static Private Member Functions
static void pressLeft ()
static void pressRight ()
static void select ()
Static Private Attributes
static bool m_isOpen = true
static uint8_t m_curSelection = 0
Detailed Description
Definition at line 6 of file MainMenu.h.
Member Function Documentation
init()
bool MainMenu::init () [static]
Definition at line 16 of file MainMenu.cpp.
{
  // main menus start open
  m_isOpen = true;
  m_curSelection = 0;
  return true;
}
References m_curSelection, and m_isOpen.
Referenced by VortexEngine::init().
isOpen()
bool MainMenu::isOpen () [static]
Definition at line 73 of file MainMenu.cpp.
{
  return m_isOpen;
}
References m_isOpen.
open()
void MainMenu::open () [static]
Definition at line 68 of file MainMenu.cpp.
{
  m_isOpen = true;
}
References m_isOpen.
pressLeft()
void MainMenu::pressLeft () [static], [private]
Definition at line 78 of file MainMenu.cpp.
{
  if (!m_curSelection) {
    m_curSelection = NUM_SELECTIONS - 1;
  } else {
    m_curSelection--;
  }
}
References m_curSelection, and NUM_SELECTIONS.
Referenced by run().
pressRight()
void MainMenu::pressRight () [static], [private]
Definition at line 87 of file MainMenu.cpp.
{
  m_curSelection = (m_curSelection + 1) % NUM_SELECTIONS;
}
References m_curSelection, and NUM_SELECTIONS.
Referenced by run().
run()
bool MainMenu::run () [static]
Definition at line 24 of file MainMenu.cpp.
{
  // if the main menus aren't open then nothing to do here
  if (!m_isOpen) {
    return false;
  }
  // press <
  if (g_pButtonL->onShortClick()) {
    pressLeft();
  }
  // press o
  if (g_pButtonM->onShortClick()) {
    select();
  }
  // press >
  if (g_pButtonR->onShortClick()) {
    pressRight();
  }
  // render
  show();
  return true;
}
References g_pButtonL, g_pButtonM, g_pButtonR, m_isOpen, Button::onShortClick(), pressLeft(), pressRight(), select(), and show().
Referenced by VortexEngine::runMainLogic().
select()
void MainMenu::select () [static], [private]
Definition at line 92 of file MainMenu.cpp.
{
  m_isOpen = false;
  Storage::setStoragePage(m_curSelection);
  if (!Modes::loadStorage()) {
    Modes::setDefaults();
  }
  DEBUG_LOGF("Selected storage page: %u", m_curSelection);
}
References DEBUG_LOGF, Modes::loadStorage(), m_curSelection, m_isOpen, Modes::setDefaults(), and Storage::setStoragePage().
Referenced by run().
show()
void MainMenu::show () [static]
Definition at line 49 of file MainMenu.cpp.
{
  Leds::clearAll();
  // render the main menu
  uint8_t hue = 0;
  uint32_t now = Time::getCurtime();
  MAP_FOREACH_LED(MAP_OUTER_RING) {
    Leds::breatheIndex(pos, hue, (now / 2), 8, 255, 180);
    hue += (255 / (LED_COUNT / 2));
  }
  hue = 0;
  MAP_FOREACH_LED(MAP_INNER_RING) {
    Leds::breatheIndex(pos, hue, (now / 2), 8, 255, 180);
    hue += (255 / (LED_COUNT / 2));
  }
  Leds::blinkIndex((LedPos)m_curSelection);
  Leds::blinkIndex((LedPos)(m_curSelection + 10));
}
References Leds::blinkIndex(), Leds::breatheIndex(), Leds::clearAll(), Time::getCurtime(), LED_COUNT, m_curSelection, MAP_FOREACH_LED, MAP_INNER_RING, and MAP_OUTER_RING.
Referenced by run().
Member Data Documentation
m_curSelection
uint8_t MainMenu::m_curSelection = 0 [static], [private]
Definition at line 22 of file MainMenu.h.
Referenced by init(), pressLeft(), pressRight(), select(), and show().
m_isOpen
bool MainMenu::m_isOpen = true [static], [private]
Definition at line 21 of file MainMenu.h.
Referenced by init(), isOpen(), open(), run(), and select().
The documentation for this class was generated from the following files:
VortexEngine/src/Menus/MainMenu.h
VortexEngine/src/Menus/MainMenu.cpp