MultiLedPattern Class Reference
#include <MultiLedPattern.h>
Public Member Functions
virtual ~MultiLedPattern ()
virtual void bind (LedPos pos) override
virtual void init () override
Protected Member Functions
MultiLedPattern (const PatternArgs &args)
Additional Inherited Members
Detailed Description
Definition at line 6 of file MultiLedPattern.h.
Constructor & Destructor Documentation
MultiLedPattern()
MultiLedPattern::MultiLedPattern (const PatternArgs & args) [protected]
Definition at line 3 of file MultiLedPattern.cpp.
                                                        :
  Pattern(args)
{
  // this is a multi led pattern
  m_patternFlags |= PATTERN_FLAG_MULTI;
  // MultiLed is an abstract class it cannot be directly
  // instantiated so we do not need to assign a pattern id
}
References Pattern::m_patternFlags, and PATTERN_FLAG_MULTI.
 MultiLedPattern()
MultiLedPattern::~MultiLedPattern () [virtual]
Definition at line 13 of file MultiLedPattern.cpp.
{
}
Member Function Documentation
bind()
void MultiLedPattern::bind (LedPos pos) [override], [virtual]
Reimplemented from Pattern.
Definition at line 17 of file MultiLedPattern.cpp.
{
  // the 'LedPos' is LED_COUNT when binding a multi-led pattern
  // as opposed to being an individual LED when it's single
  Pattern::bind(LED_COUNT);
}
References Pattern::bind(), and LED_COUNT.
init()
void MultiLedPattern::init () [override], [virtual]
Reimplemented from Pattern.
Reimplemented in ZigzagPattern, WarpWormPattern, WarpPattern, VortexWipePattern, TheaterChasePattern, SnowballPattern, SequencedPattern, PulsishPattern, MateriaPattern, LighthousePattern, HueShiftPattern, FillPattern, DripPattern, DripMorphPattern, DoubleStrobePattern, CrossDopsPattern, CompoundPattern, BouncePattern, BlinkStepPattern, and BackStrobePattern.
Definition at line 25 of file MultiLedPattern.cpp.
{
  Pattern::init();
}
References Pattern::init().
Referenced by BlinkStepPattern::init(), CompoundPattern::init(), DripMorphPattern::init(), HueShiftPattern::init(), MateriaPattern::init(), PulsishPattern::init(), and ZigzagPattern::init().
The documentation for this class was generated from the following files:
VortexEngine/src/Patterns/Multi/MultiLedPattern.h
VortexEngine/src/Patterns/Multi/MultiLedPattern.cpp