name: Core Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # manual trigger

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout outer repository
      uses: actions/checkout@v3
      with:
        repository: "StoneOrbits/VortexEmulator"
        path: VortexEmulator

    - name: Checkout current repository inside the outer repository
      uses: actions/checkout@v3
      with:
        path: VortexEmulator/VortexTestingFramework/VortexEngine

    - name: Install Dependencies
      run: sudo apt-get install valgrind g++ make doxygen graphviz texlive

    - name: Build
      run: make -j
      working-directory: VortexEmulator/VortexTestingFramework
      
    - name: Set execute permissions for test script
      run: chmod +x ./runtests.sh
      working-directory:  VortexEmulator/VortexTestingFramework/tests

    - name: Run tests
      run: ./runtests.sh --core
      working-directory:  VortexEmulator/VortexTestingFramework/tests

    - name: Checkout doxygen-awesome
      run: |
        git clone https://github.com/jothepro/doxygen-awesome-css.git doxygen-awesome-css
      working-directory:  VortexEmulator/VortexTestingFramework/VortexEngine

    - name: Generate Documentation
      run: doxygen Doxyfile
      working-directory:  VortexEmulator/VortexTestingFramework/VortexEngine

    - name: Commit and Push Documentation
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs
        git commit -m "Update Doxygen documentation"
        git push -f origin HEAD:core-docs
      working-directory:  VortexEmulator/VortexTestingFramework/VortexEngine
