name: Build and Deploy Documentation

on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby for Jekyll
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0

    - name: Install Jekyll and Bundler
      run: |
        gem install jekyll bundler
        bundle install

    - name: Build Jekyll site
      run: bundle exec jekyll build --source ./docs --destination ./site/main

    - name: Install Doxygen
      run: sudo apt-get install doxygen -y

    - name: Generate Doxygen docs for core and devices
      run: |
        branches=("master" "orbit" "handle" "gloves" "desktop" "duo" "chromadeck" "spark")
        for branch in "${branches[@]}"
        do
          if [ "$branch" == "master" ]; then
            folder_name="core"
          else
            folder_name=$branch
          fi
          git fetch origin $branch:$branch
          git checkout $branch
          doxygen Doxyfile
          mkdir -p site/$folder_name
          mv html/* site/$folder_name
        done

    - name: Upload site artifacts
      uses: actions/upload-artifact@v3
      with:
        name: documentation
        path: ./site

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site

