name: Build and Deploy Documentation

on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install Doxygen
        run: sudo apt-get install doxygen -y

      - name: Generate Doxygen Documentation for Branches
        run: |
          branches=("master" "orbit" "handle" "gloves" "desktop" "duo" "chromadeck" "spark")
          for branch in "${branches[@]}"
          do
            if [ "$branch" == "master" ]; then
              folder_name="core"
            else
              folder_name=$branch
            fi
            # Create a temporary directory for Doxygen output
            mkdir -p /tmp/$folder_name
            
            git fetch origin $branch:$branch
            git checkout $branch
            
            # Generate Doxygen docs to the temporary directory
            doxygen Doxyfile
            
            # Move the Doxygen output to the Jekyll site directory
            mkdir -p _site/$folder_name
            mv /tmp/$folder_name/docs/* _site/$folder_name
          done
        env:
          DOXYFILE: ./Doxyfile # Ensure this points to the correct location

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

