name: Deploy Documentation to GitHub Pages

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure full history is available

      - name: Install Doxygen and Dependencies
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz texlive

      - name: Checkout doxygen-awesome
        run: git clone https://github.com/jothepro/doxygen-awesome-css.git doxygen-awesome-css

      - name: Generate and Collect Doxygen Documentation
        run: |
          # Ensure docs directory starts clean
          rm -rf docs || true

          # Branches and their corresponding doc directories
          branches=("master:core" "duo" "handle" "orbit" "gloves" "desktop" "spark" "chromadeck")

          for item in "${branches[@]}"; do
            IFS=':' read -r branch dest <<< "$item"

            # Default destination is the branch name unless specified
            dest="${dest:-$branch}"

            # Checkout each branch, generate documentation, and move it to the correct directory
            git checkout $branch
            doxygen Doxyfile

            # Move generated files to the correct directory
            mkdir -p docs/$dest
            mv -v docs/* docs/$dest/ # Verbose output for logging

            # Clean up to prepare for the next branch
            rm -rf docs/*

            echo "Generated docs for $branch, deployed to docs/$dest"
          done

      - name: Checkout gh-pages Branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Copy Generated Docs to gh-pages
        run: |
          # Create a temporary directory for deployment
          mkdir -p new-docs
          cp -r docs/* new-docs/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./new-docs
          keep_files: false

