name: Build and Deploy Documentation

on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install Doxygen
        run: sudo apt-get install doxygen graphviz texlive --fix-missing

      - name: Generate Doxygen Documentation for Branches
        run: |
          branches=("master" "orbit" "handle" "gloves" "desktop" "duo" "chromadeck" "spark")
          for branch in "${branches[@]}"
          do
            if [ "$branch" == "master" ]; then
              folder_name="core"
            else
              folder_name=$branch
            fi
            git fetch origin $branch:$branch
            git checkout $branch
            mkdir -p docs/$folder_name
            doxygen Doxyfile
            echo "Listing contents of docs/$folder_name:"
            ls -R docs/$folder_name || echo "No files found in docs/$folder_name"
          done

      - name: Checkout gh-pages again
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

