name: Embedded Build

on:
  push:
    branches: [ "daniel/orbit/arduino_makefile" ]
  pull_request:
    branches: [ "daniel/orbit/arduino_makefile" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Depdendencies
      run: make install
    - name: Build Binary
      run: make build
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: embedded firmware
        path: VortexEngine/VortexEngine.ino.adafruit_trinket_m0.bin
