name: Gloves Embedded

on:
  push:
    branches: [ "daniel/orbit/arduino_makefile" ]
  pull_request:
    branches: [ "daniel/orbit/arduino_makefile" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: make install
    
    - name: Download uf2conv script
      run: wget https://raw.githubusercontent.com/microsoft/uf2/master/utils/uf2conv.py
      
    - name: Download uf2families.json
      run: wget https://raw.githubusercontent.com/microsoft/uf2/master/utils/uf2families.json

    - name: Make scripts executable
      run: chmod +x uf2conv.py uf2families.json

    - name: Build Binary
      run: make build

    - name: Convert BIN to UF2
      run: python3 uf2conv.py -c -b 0x2000 build/VortexEngine.ino.bin -o build/VortexEngine.ino.uf2
    
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: embedded firmware
        path: |
          build/VortexEngine.ino.bin
          build/VortexEngine.ino.elf
          build/VortexEngine.ino.map
          build/VortexEngine.ino.hex
          build/VortexEngine.ino.uf2
