name: Gloves Build

on:
  push:
    branches: [ "gloves" ]
  pull_request:
    branches: [ "gloves" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout outer repository
      uses: actions/checkout@v3
      with:
        repository: "StoneOrbits/VortexEmulator"
        path: VortexEmulator

    - name: Checkout current repository inside the outer repository
      uses: actions/checkout@v3
      with:
        path: VortexEmulator/VortexTestingFramework/VortexEngine

    - name: Install Dependencies
      run: sudo apt-get install valgrind g++ make

    - name: Build
      run: make
      working-directory: VortexEmulator/VortexTestingFramework

    - name: Set execute permissions for test script
      run: chmod +x ./runtests.sh
      working-directory:  VortexEmulator/VortexTestingFramework/tests

    - name: Run tests
      run: ./runtests.sh --gloves
      working-directory:  VortexEmulator/VortexTestingFramework/tests
