name: Gloves Doxygen

on:
  workflow_run:
    workflows: ["Gloves Build"]
    types:
      - completed

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Doxygen
      run: sudo apt-get install doxygen graphviz texlive make

    - name: Checkout doxygen-awesome
      run: |
        git clone https://github.com/jothepro/doxygen-awesome-css.git doxygen-awesome-css

    - name: Generate Documentation
      run: doxygen Doxyfile

    - name: Commit and Push Documentation
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs
        git commit -m "Update Doxygen documentation"
        git push -f origin HEAD:gloves-docs
